<?php
$form = $this->placeholder('form')->getValue();
$inspectionId = $form->get('data')->get('id')->getValue();
$area = $this->placeholder('enforcementAreaName');
echo $this->render('partials/read-only/main',
    [
        'items' => [
            ['label' => $this->translate('internal-inspection-request-form.id'), 'value' => $inspectionId],
            [
                'label' => $this->translate('internal-inspection-request-form.area'),
                'value' => $area ? $area : $this->translate('internal-inspection-request-form.area-not-set'),
                'class' => 'full-width'
            ]
        ]
    ]
);
echo $this->formErrors($form);
echo $this->form($form);
