<?php
    echo $this->render(
        '/view-new/partials/page-header.phtml',
        array(
            'pageTitle' => $this->translate($this->params['pageTitle']),
            'pageSubTitle'=> $this->translate($this->params['pageSubTitle'])
        )
    );
?>

<div class="two-thirds">
    <?php
        echo $this->formErrors($form);
        echo $this->form($form);
    ?>
</div><!-- end three-quarters -->
