<p class="notice--<?php echo $this->active ? 'danger' : 'warning' ?>">
    <strong>
        <?php
        echo $this->translate('Operator disqualified')
        ?>
    </strong>
    <br>
    <?php
    echo $this->startDateTime->format(\DATE_FORMAT);
    if (!empty($this->endDateTime)) {
        echo ' to '. $this->endDateTime->format(\DATE_FORMAT);
    }
    ?>
    <br>
    <?php
        echo $this->linkModal(
            $this->url('operator/disqualify', ['organisation' => $this->organisationId]),
            'Edit disqualification'
        );
    ?>
</p>
