<?php 
$this->placeholder('body-class')->set("full-page");
$this->headScript()->prependFile($this->basePath() . '/js/columnToggle.js');
?>
<tbody id="listTable">
<?php foreach ($listData as $row) : ?>
    <tr>
        <td><?php echo $this->escapeHtml( $row['convictionNumber']); ?></td>
        <td><?php echo $this->escapeHtml( $row['name']); ?><br><?php echo $this->escapeHtml( $row['defType']); ?></td>
        <td><span class="noWrap"><?php echo $this->escapeHtml( $row['dateOfOffence']); //TODO ->format('d.m.Y')); ?></span></td>
        <td><span class="noWrap"><?php echo $this->escapeHtml( $row['dateOfConviction']); //TODO ->format('d.m.Y')); ?></span></td>
        <td class="cur colToggle">
            <span><img  src="/img/p.png" class="sprt arrRt" /><?php echo $this->escapeHtml(substr($row['description'], 0, 20).'...'); ?></span>
            <span class="theRest hide" style="display:block">
                <?php echo $this->escapeHtml(substr($row['description'], 20)); ?>
            </span>
        </td>
        <td><?php echo $this->escapeHtml( $row['courtFpn']); ?></td>
        <td class="cur colToggle">
            <span><img  src="/img/p.png" class="sprt arrRt" /><?php echo $this->escapeHtml(substr($row['penalty'], 0, 20).'...'); ?></span>
            <span class="theRest hide" style="display:block">
                <?php echo $this->escapeHtml(substr($row['penalty'], 20)); ?>
            </span>
        </td>
        <td><?php echo $this->escapeHtml( $row['msi']); ?></td>
        <td><?php echo $this->escapeHtml( $row['decToTc']); ?></td>
        <td class="centre"><input type="checkbox" /></td>
        <td class="centre"><input type="checkbox" /></td>
    </tr>
<?php endforeach; ?>
</tbody>
