<?php 
$this->placeholder('body-class')->set("full-page");
$this->headScript()->prependFile($this->basePath() . '/js/olc.ajax.js');
$this->headScript()->prependFile($this->basePath() . '/js/caseTabs.js');
$this->headScript()->prependFile($this->basePath() . '/js/collapsible.init.js');
$this->headScript()->prependFile($this->basePath() . '/js/collapsible.js');
?>
<?php $detailsForm->prepare(); ?>
<?php echo $this->form()->openTag($detailsForm); ?>
<div id="caseDetailsDiv" class="row">
    <?php
    echo $this->partial('olcs/vcase/partials/details', array(
        'params' => $params,
        'caseId' => $caseId,
        'licenceId' => $licenceId,
        'caseTabs' => array('convictionActive' => 'active'),
    ));
    ?>
    <div class="conviction-details-textarea">
        <?php echo $this->formRow($detailsForm->get('caseDetailsNote')); ?>
        <button type="button" data-url="/case/ajax-detail-save" data-params="caseDetailsNote" class="btn btn-small btn-save"><?php echo $this->resourceHelper('save'); ?></button>
        <?php echo $this->formRow($detailsForm->get('detailTypeId')); ?>
        <?php echo $this->formRow($detailsForm->get('commentId')); ?>
    </div>
    <div class="accordionAll">
        <div>
            <div class="row">
                <a href="#" class="col-md-6  acc-buttons collapsible acc-collapsed expanded"><?php echo $this->resourceHelper('list-of-convictions'); ?></a>
                <button type="button" name="addConviction" class="btn btn-success btn-new pull-right" id="createCase"><?php echo $this->resourceHelper('add-conviction'); ?></button>
            </div>
            <div id="acc-convictions" class="accordion-row">
                <?php echo $this->dataListView; ?>
                <div style="text-align: right"><button type="button" name="applyChanges" class="btn btn-success"><?php echo $this->resourceHelper('apply-changes'); ?></button></div>
            </div>
        </div>
    </div>
    <?php
    echo $this->partial('olcs/vcase/partials/action-form', array(
        'form' => $detailsForm,
        'noFormTags' => true,
    ));
    ?>
</div>
<?php echo $this->form()->closeTag(); ?>
