<?php echo $this->flashMessengerAll(); ?>
<?php echo $this->form()->openTag($form); ?>
    <fieldset>
        <legend><?php echo $this->translate('auth.expired-password.title'); ?></legend>
        <p><?php echo $this->translate('auth.change-password.subtitle'); ?></p>
        <?php
        echo $this->formErrors($form);
        if (isset($failed) && $failed) {
            ?>
            <div class="validation-summary">
                <h2><?php echo $this->translate('auth.expired-password.failed.title'); ?></h2>
                <p><?php echo $this->translate($failureReason); ?></p>
            </div>
            <?php
        }
        ?>
        <?php echo $this->formRow($form->get('newPassword')); ?>
        <?php echo $this->formRow($form->get('confirmPassword')); ?>
        <?php echo $this->formElement($form->get('submit')); ?>
    </fieldset>

<?php echo $this->formElement($form->get('security')); ?>
<?php echo $this->form()->closeTag(); ?>
