<h1>Case List Placeholder</h1>
<p>This file is located here:<strong><?php echo __FILE__; ?></strong></p>

<a href="/case/new">New Case</a>
<br />
<a href="/searchresults">Back to Search Results</a>

<?php
foreach ($this->data as $result) {
    ?>
    <div class="well">
        <a href="/case?id=<?php echo $result['caseId']; ?>">Case</a>
        <pre><?php print_r($result); ?></pre>
    </div>
    <?php
}