<h1>Search results</h1>
<p>This file is located here:<strong><?php echo __FILE__; ?></strong></p>

<a href="/search">Search</a>

<?php

foreach ($this->data['listData'] as $result) {

    ?>
    <div class="well">
        <?php
        if ((int)$result['caseCount'] > 0) {
            ?>
            <a href="/case/">View cases (<?php echo $result['caseCount']; ?>)</a>
            <?php
        } else {
            ?>
            <a href="/case/new">Create cases</a>
            <?php
        }
        ?>
        <pre><?php print_r($result); ?></pre>
    </div>
    <?php
}