<?php

$noOfVehiclesContent = [
    'label' => 'No. of vehicles',
    'value' => $numberOfVehicles,
    'hideIfEmpty' => true,
];

$noOfOperatingCentresContent = [
    'label' => 'No. of operating centres',
    'value' => $numberOfOperatingCentres,
    'hideIfEmpty' => true,
];

$totalTrailerAuthorisationContent = [
    'label' => 'Total trailer authorisation',
    'value' => $totalTrailerAuthorisation,
    'hideIfEmpty' => true,
];

$numberOfIssuedDiscsContent = [
    'label' => 'No. of issued discs',
    'numeric' => $numberOfIssuedDiscs,
    'hideIfEmpty' => true,
];

$numberOfCommunityLicencesContent = [
    'label' => $this->translate($isPsv ? 'lva.overview.number-psv-certified-copies' : 'lva.overview.number-uk-licences-community'),
    'numeric' => $numberOfCommunityLicences,
    'hideIfEmpty' => true,
];

// Due to the tabular manner in which the items are laid out on the page, the items for key 3 need to be ordered
// differently depending on whether we're displaying one vehicle authorisation number or a HGV/LGV split
if (is_null($totalVehicleAuthorisation)) {
    $key3Content = [
        $noOfVehiclesContent,
        [
            'label' => 'Total Heavy goods vehicle authorisation',
            'value' => $totalHgvAuthorisation,
            'hideIfEmpty' => true,
        ],
        $noOfOperatingCentresContent,
        [
            'label' => 'Total Light goods vehicle authorisation',
            'value' => $totalLgvAuthorisation,
            'hideIfEmpty' => true,
        ],
        $numberOfIssuedDiscsContent,
        $totalTrailerAuthorisationContent,
        $numberOfCommunityLicencesContent,
    ];
} else {
    $key3Content = [
        $noOfVehiclesContent,
        [
            'label' => 'Total vehicle authorisation',
            'value' => $totalVehicleAuthorisation,
            'hideIfEmpty' => true,
        ],
        $noOfOperatingCentresContent,
        $totalTrailerAuthorisationContent,
        $numberOfIssuedDiscsContent,
        $numberOfCommunityLicencesContent,
    ];
}

echo $this->render('partials/read-only/main',
    [
        'multiItems' =>  [
            0 => [
                [
                    'label' => 'Operator name',
                    'url' => $this->url('operator/business-details', ['organisation' => $operatorId]),
                    'value' => $operatorName,
                ],
                ['label' => 'Trading name', 'value' => $tradingName],
                ['label' => 'Previous operator name', 'value' => $previousOperatorName, 'hideIfEmpty' => true],
                ['label' => 'Previous licence No.', 'value' => $previousLicenceNumber, 'hideIfEmpty' => true],
                ['label' => 'No. of licences ', 'numeric' => $numberOfLicences],
                ['label' => 'Current applications ', 'value' => $currentApplications, 'noEscape' => true],
            ],
            1 => [
                ['label' => 'Application created', 'date' => $applicationCreated],
                ['label' => 'Out of objection', 'date' => $outOfOpposition, 'dateFormat' => 'Y-m-d'],
                ['label' => 'No. of oppositions', 'numeric' => $oppositionCount],
                ['label' => 'Out of representation', 'date' =>  $outOfRepresentation, 'dateFormat' => 'Y-m-d'],
                ['label' => 'Change of entity', 'value' => $changeOfEntity, 'noEscape' => true, 'hideIfEmpty' => true],
                ['label' => 'Interim status', 'value' => $interimStatus, 'noEscape' => true, 'hideIfEmpty' => true],
            ],
            2 => [
                ['label' => 'Licence status', 'value' => $this->status($licenceStatus), 'noEscape' => true],
                ['label' => 'Outstanding fees', 'numeric' => $outstandingFees],
                ['label' => 'Application licence type', 'value' => $this->translate((string)$appLicenceType)],

                [
                    'label' => 'Continuation date',
                    'date' => $continuationDate,
                    'dateFormat' => 'Y-m-d',
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'Licence start date',
                    'date' => $licenceStartDate,
                    'dateFormat' => 'Y-m-d',
                    'hideIfEmpty' => true,
                ],
                ['label' => 'Grace period', 'value' => $licenceGracePeriods, 'noEscape' => true],
                ['label' => 'Current licence type', 'value' => $this->translate((string)$licenceType), 'hideIfEmpty' => true]
            ],
            3 => $key3Content,
            4 => [
                ['label' => 'Open cases', 'value' => $openCases],  // not numeric, may be suffixed with ' (PI)'
                ['label' => 'Current review complaints', 'numeric' => $currentReviewComplaints],
                ['label' => 'Receives mail electronically', 'value' => $receivesMailElectronically],
                ['label' => 'Registered for self service', 'value' => $registeredForSelfService],
            ],
        ],
    ]
);
if (isset($form)) {
    $form->prepare();
    echo $this->formErrors($form);
    echo $this->form($form);
}
