<?php
if (count($this->data['vehicles']['vehicles']) > 0) {
    echo $this->partial(
        'partials/continuation/checklist-section',
        [
            'data' => $this->licenceChecklist(\Common\RefData::LICENCE_CHECKLIST_VEHICLES, $this->data)
        ]
    );
} else {
    echo $this->translate('There are no vehicles recorded on your licence');
}
?>
<?php if (count($this->data['vehicles']['vehicles']) > \Common\RefData::CONTINUATIONS_DISPLAY_VEHICLES_COUNT) : ?>
    <p>
    <a
        href="<?php echo $this->url(
            'continuation/checklist/vehicles', ['continuationDetailId' => $this->data['continuationDetailId']])
        ; ?>"
        class="govuk-button govuk-button--secondary" target="_blank" role="button" draggable="false">
        <?php echo $this->translate('continuations.vehicles.button-label'); ?>
    </a>
    </p>
    <p><?php echo $this->translate('continuations.checklist.section.opens_in_a_new_window'); ?></p>
<?php endif; ?>
