<?php
if (count($this->data['people']['persons']) > 0) {
    echo $this->partial(
        'partials/continuation/checklist-section',
        [
            'data' => $this->licenceChecklist(\Common\RefData::LICENCE_CHECKLIST_PEOPLE, $this->data)
        ]
    );
} else {
    echo $this->data['people']['emptyTableMessage'];
}
?>
<?php if (count($this->data['people']['persons']) > \Common\RefData::CONTINUATIONS_DISPLAY_PERSON_COUNT) : ?>
    <p>
    <a
        href="<?php echo $this->url(
            'continuation/checklist/people', ['continuationDetailId' => $this->data['continuationDetailId']])
        ; ?>"
        class="govuk-button govuk-button--secondary" target="_blank" role="button" draggable="false">
        <?php
            echo $this->translate(
                'continuations.people.button-label.'. $this->data['businessType']['typeOfBusinessId']
            );
        ?>
    </a>
    </p>
    <p><?php echo $this->translate('continuations.checklist.section.opens_in_a_new_window'); ?></p>
<?php endif; ?>

