<?php $tmChanges = $this->data['transportManagers']['tmChanges']; ?>
<?php if ($tmChanges > 0): ?>
    <p class="important">
        <strong>
            <?php
            echo $tmChanges
                . ' '
                . $this->translate('continuations.pending.change'. ($tmChanges > 1 ? 's' : ''));
            ?>
        </strong>
    </p>
<?php endif;?>
<?php
if (count($this->data['transportManagers']['transportManagers']) > 0) {
    echo $this->partial(
        'partials/continuation/checklist-section',
        [
            'data' => $this->licenceChecklist(\Common\RefData::LICENCE_CHECKLIST_TRANSPORT_MANAGERS, $this->data)
        ]
    );
} else {
    echo $this->translate('There are no transport managers recorded on your licence');
}
?>
<?php
    if (
        count($this->data['transportManagers']['transportManagers']) > \Common\RefData::CONTINUATIONS_DISPLAY_TM_COUNT
    ) :
?>
    <p>
    <a
        href="<?php echo $this->url(
            'continuation/checklist/transport-managers',
            ['continuationDetailId' => $this->data['continuationDetailId']])
        ; ?>"
        class="govuk-button govuk-button--secondary" target="_blank" role="button" draggable="false">
        <?php echo $this->translate('continuations.transport-managers.button-label'); ?>
    </a>
    </p>
    <p><?php echo $this->translate('continuations.checklist.section.opens_in_a_new_window'); ?></p>
<?php endif; ?>

