<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <div class="gem-c-title govuk-!-margin-top-8 govuk-!-margin-bottom-8">
            <h1 class="gem-c-title__text "><?php echo $this->translate('cookie-detail-heading'); ?></h1>
        </div>
    </div>
</div>

<div class="govuk-grid-row responsive-bottom-margin">
    <div class="govuk-grid-column-two-thirds">
        <div class="gem-c-govspeak govuk-govspeak direction-ltr" data-module="govspeak">
            <p><?php echo $this->translate('cookie-detail-summary'); ?></p>
            <?php
                echo $this->translate('markup-cookie-detail-analytics');
                echo $this->translate('markup-cookie-detail-settings');
                echo $this->translate('markup-cookie-detail-security');
                echo $this->translate('markup-cookie-detail-strictly-necessary');
                echo $this->translate('markup-cookie-detail-third-party');
                echo $this->translate('markup-cookie-detail-ip-addresses');
                echo $this->translate('markup-cookie-detail-data-protection');
                echo $this->translate('markup-cookie-detail-change-settings');
                echo $this->translate('markup-cookie-detail-last-updated');
            ?>
        </div>

        <?php echo $this->translate('markup-cookie-detail-elsewhere'); ?>
    </div>
</div>