<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l govuk-!-margin-top-8 govuk-!-margin-bottom-8">
      <?php echo $this->translate('cookie-detail-heading'); ?>
    </h1>
  </div>
</div>

<div class="govuk-grid-row govuk-!-margin-bottom-8">
  <div class="govuk-grid-column-two-thirds">
    <div class="govuk-body">
      <p><?php echo $this->translate('cookie-detail-summary'); ?></p>
    </div>

    <?php
    echo $this->translate('markup-cookie-detail-analytics');
    echo $this->translate('markup-cookie-detail-settings');
    echo $this->translate('markup-cookie-detail-security');
    echo $this->translate('markup-cookie-detail-strictly-necessary');
    echo $this->translate('markup-cookie-detail-third-party');
    echo $this->translate('markup-cookie-detail-ip-addresses');
    echo $this->translate('markup-cookie-detail-data-protection');
    echo $this->translate('markup-cookie-detail-change-settings');
    echo $this->translate('markup-cookie-detail-last-updated');
    ?>

    <?php echo $this->translate('markup-cookie-detail-elsewhere'); ?>
  </div>
</div>
