<div class="nopad tPagBar  tBorder2t">
        <div class="tBgCol"><span><?php echo $this->resourceHelper('lookup-search-results-total-pages'); ?></span>
                <ul class="list-inline" style="display: inline;">
                    <li><?php echo $this->resourceHelper('lookup-search-results-prefix'); ?> <a href="#"><?php echo $this->resourceHelper('lookup-search-results-first-twenty-five'); ?></a></li>
                    <li><a href="#"><?php echo $this->resourceHelper('lookup-search-results-first-fifty'); ?></a></li>
                    <li><a href="#"><?php echo $this->resourceHelper('lookup-search-results-first-hundred'); ?></a></li>
                </ul>
        </div>
</div>