<div class="version-header">
    <p class="environment">Environment: <span class="environment-marker"><?= $this->escapeHtml($environment) ?></span></p>
    <p class="version">PHP: <span><?= $this->escapeHtml($phpVersion) ?></span></p>
    <p class="version">Description: <span><?= $this->escapeHtml($description) ?></span></p>
    <p class="version">Version: <span><?= $this->escapeHtml($release) ?></span></p>
</div>
