<?php
    echo $this->render(
        '/partials/page-header.phtml',
        array(
        'pageTitle' => 'Previous History',
        // 'pageSubTitle'=> 'Tell us about the type of licence you are applying for'
        )
    );
?>
<div class="one-quarter">
    <ol class="vertical-navigation" role="navigation">
        <li class="vertical-navigation__item">
            <a href="#operating-centres">Financial history</a>
        </li>
        <li class="vertical-navigation__item">
            <a href="#authorised-vehicles">Licence history</a>
        </li>
        <li class="vertical-navigation__item">
            <a href="#financial-evidence">Convictions &amp; penalties</a>
        </li>
    </ol><!-- end .vertical-navigation -->

</div><!-- end .one-quarter -->
<div class="three-quarters">
    <?php 
    echo $this->partial($formPartialPath, array(
        'form' => $form,
    ));
    ?>
    <a href="<?php echo $this->url('selfserve/dashboard-home'); ?>">Back to home</a>
</div>