version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    schedule:
      interval: "weekly"
    groups:
      root-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-action-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/website"
    versioning-strategy: "increase-if-necessary"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
