<div class="one-fifth--left">
    <h4><?php echo $this->translate('internal-licence-processing'); ?></h4>
    <?php
        echo $this->navigation($navigation)->menu()->setPartial('layout/partials/subNavigation');

        $tableFilters = $this->placeholder('tableFilters')->getValue();
        if($tableFilters instanceof \Zend\Form\Form) {
            echo $this->form($tableFilters);
        }
    ?>
</div>
<div class="three-fifths    js-content--main">
    <?php echo $this->flashMessengerAll(); ?>
    <?php echo $this->table; ?>

    <?php
    // need to fix view hierarchy/composition
    if (isset($form)) {
        echo $this->formErrors($form);
        echo $this->form($form);
    }
    ?>
</div>
