<?php
    echo $this->render(
        '/partials/page-header.phtml',
        array(
        'pageTitle' => 'Type of licence',    
        // 'pageSubTitle'=> 'Tell us about the type of licence you are applying for'
        )
    );
?>

<div class="two-thirds">
    <?php 
    echo $this->partial('self-serve/forms/licence-type', array(
        'licenceTypeForm' => $licenceTypeForm,
    ));
    ?>
    <a href="<?php echo $this->url('selfserve/dashboard-home'); ?>">Back to home</a>
</div>