<div class="four-fiths--left">
    <?php
        echo $this->navigation('navigation')
                  ->menu($this->navigation()->findOneBy('id', 'application'))
                  ->setUlClass('horizontal-navigation')
                  ->setAddClassToListItem(true)
                  ->setPartial('layout/partials/tabs');
    ?>
    <div class="content">
        <div class="one-fifth--left">
            <h4>Application details</h4>
            <?php echo $this->navigation; ?>
        </div>
        <div class="three-fifths">
            <?php echo $this->flashMessengerAll(); ?>
            <?php echo $this->main; ?>
        </div>
    </div>
</div>

<div class="one-fifth--right">
    <div class="record-actions">
        <h5>Operator</h5>
        <h5>Quick actions</h5>
        <ul class="record-actions__group">
            <li class="record-actions__item actions--secondary"><a href="">Create case</a></li>
        </ul>
    </div>
</div>
