<ul class="app-navigation" role="menubar">
    <?php
    foreach($sections as $section) {

        if ($section['display']) {
            $section['subSections'][] = $section;
        }

        foreach ($section['subSections'] as $subSection) {

            $classes = array();

            if (!$subSection['enabled']) {
                $classes[] = 'disabled';
            }

            if ($subSection['current']) {
                $classes[] = 'current';
            }

            if ($subSection['status'] !== null) {
                $classes[] = $subSection['status'];
            } else {
                $classes[] = 'no-background';
            }

            $classes[] = $subSection['class'];

            ?>
            <li class="app-navigation__item <?php echo implode(' ', $classes); ?>">
                <?php
                if (!$subSection['current'] && $subSection['enabled']) {
                    ?>
                    <a href="<?php echo $this->url($subSection['route'], array(), array(), true); ?>">
                    <?php
                    }
                ?>
                <span><?php echo $this->translate($subSection['title']); ?></span>
                <?php
                if (!$subSection['current'] && $subSection['enabled']) {
                    ?>
                    </a>
                    <?php
                }
                ?>
            </li>
        <?php
        }
    }
    ?>
</ul>