<div class="content__header">
	<h3>Legacy offence details</h3>
</div>
<?php
$details = $this->placeholder('details')->getValue();

$noRender = array('createdOn', 'lastModifiedOn', 'createdBy', 'lastModifiedBy', 'id', 'version');

$items = [];

foreach ($details as $key => $value) {
    if (!is_array($value) && !in_array($key, $noRender)) {
        if (strstr(strtolower($key), 'date')) {
            $item = ['label' => $key, 'date' => $value];
        } else {
            $item = ['label' => $key, 'value' => $value];
        }

        $items[] = $item;
    }
}

echo $this->render('partials/read-only/main', ['items' => $items]);
