<div class="content__header">
	<h4>Opposition details</h4>
</div>

<?php
$details = $this->placeholder('details')->getValue();
var_dump($details);exit;
$oooDate = $this->placeholder('oooDate')->getValue();
$oorDate = $this->placeholder('oorDate')->getValue();

echo $this->render('partials/read-only/main',
    [
        'items' => [
            ['label' => 'OOO Date', 'date' => $oooDate, 'showNotSet' => true],
            ['label' => 'OOR Date', 'date' => $oorDate, 'showNotSet' => true],
        ]
    ]
);

$oppositionsTable = $this->placeholder('oppositionsTable')->getValue();
echo $oppositionsTable;

$envComplaintsTable = $this->placeholder('envComplaintsTable')->getValue();
echo $envComplaintsTable;
