<?php

$case = $this->placeholder('case')->getValue();
$categories = isset($case['categorys']) && is_array($case['categorys']) ?
    implode(', ', array_map(function($item){return $item['description'];}, $case['categorys'])) :
    'None selected';

$actions = [
    [
        'label' => 'Edit case',
        'url' => $this->url('case', ['case' => $case['id'], 'action' => 'edit'], [], false)
    ],
];

if (isset($closeAction) && is_array($closeAction)) {

    $closeActionUrl = [
        'label' => $closeAction['label'],
        'url' => $this->url(
                $closeAction['route'], $closeAction['params']
            )
    ];
    array_push($actions, $closeActionUrl);
}
//case overview
echo $this->render('partials/read-only/main',
    [
        'header' => $this->navigation('navigation')->findOneBy('active', 1)->getLabel(),
        'actions' => $actions,
        'items' => [
            ['label' => 'Case type', 'value' => $case['caseType']['description']],
            ['label' => 'Open date', 'date' => $case['openDate']],
            ['label' => 'ECMS', 'value' => $case['ecmsNo']],
            ['label' => 'Description', 'value' => $case['description'], 'class' => 'full-width'],
            ['label' => 'Categories', 'value' => $categories, 'class' => 'full-width']
        ]
    ]
);

//last submission
echo $this->render('partials/read-only/main',
    [
        'header' => 'Last submission',
        'actions' => [
            [
                'label' => 'Edit submission',
                'url' => $this->url('case', ['case' => $case['id'], 'action' => 'edit'], [], false)
            ],
        ],
        'items' => [
            ['label' => 'Submission No.', 'value' => '1234'],
            ['label' => 'Type', 'value' => 'Lorem ispum'],
            ['label' => 'Date created', 'value' => '17/05/2014'],
            ['label' => 'Date closed', 'value' => 'N/a'],
            ['label' => 'Currenly with', 'value' => 'Kevin Rooney'],
            ['label' => 'Note', 'value' => 'This section contains test data.', 'class' => 'full-width']
        ]
    ]
);
