<?php

$case = $this->placeholder('case')->getValue();
$categories = isset($case['categorys']) && is_array($case['categorys']) ?
    implode(', ', array_map(function($item){return $item['description'];}, $case['categorys'])) :
    'None selected';
$outcomes = isset($case['outcomes']) && is_array($case['outcomes']) ?
    implode(', ', array_map(function($item){return $item['description'];}, $case['outcomes'])) :
    'None selected';
$actions = [
    [
        'label' => 'Edit case',
        'url' => $this->url('case', ['case' => $case['id'], 'action' => 'edit'], [], false),
        'class' => 'action--secondary js-modal-ajax'
    ],
];

if (isset($closeAction) && is_array($closeAction)) {

    $closeActionUrl = [
        'label' => $closeAction['label'],
        'url' => $this->url(
                $closeAction['route'], $closeAction['params']
            )
    ];
    array_push($actions, $closeActionUrl);
}
//case overview
echo $this->render('partials/read-only/main',
    [
        'header' => $this->navigation('navigation')->findOneBy('active', 1)->getLabel(),
        'actions' => $actions,
        'items' => [
            ['label' => 'Case type', 'value' => $case['caseType']['description']],
            ['label' => 'Open date', 'date' => $case['createdOn']],
            ['label' => 'ECMS', 'value' => $case['ecmsNo']],
            ['label' => 'Closed date', 'date' => $case['closedDate']],
            ['label' => 'Description', 'value' => $case['description'], 'class' => 'full-width'],
            ['label' => 'Categories', 'value' => $categories, 'class' => 'full-width'],
            ['label' => 'Outcomes', 'value' => $outcomes, 'class' => 'full-width']
        ]
    ]
);
