<?php
    $prohibition = $this->placeholder('prohibition')->getValue();

    echo $this->render('partials/read-only/main',
        [
            'header' => 'Prohibition detail',
            'actions' => [
                [
                    'label' => 'Return to list',
                    'url' => $this->url('case_prohibition', ['action' => 'index', 'prohibition' => null], [], true),
                ],
                [
                    'label' => 'Edit prohibition',
                    'url' => $this->url('case_prohibition', ['action' => 'edit'], [], true),
                ],
            ],
            'items' => [
                ['label' => 'Prohibition date', 'date' => $prohibition['prohibitionDate']],
                ['label' => 'Vehicle registration mark', 'value' => $prohibition['vrm']],
                ['label' => 'Trailer', 'value' => $prohibition['isTrailer']],
                ['label' => 'Prohibition type', 'value' => $prohibition['prohibitionType']['description']],
                ['label' => 'Date cleared', 'date' => $prohibition['clearedDate']],
                ['label' => 'Location prohibition issued', 'value' => $prohibition['imposedAt']]
            ]
        ]
    );

echo $this->render('partials/table');