<?php
$readonly = false;

$pi = current($this->placeholder('pi')->getArrayCopy());

if (isset($pi['isClosed'])) {
    $readonly = $pi['isClosed'];
}

$actions = [];
if (isset($closeAction) && is_array($closeAction)) {
    $closeActionUrl = [
        'label' => $closeAction['label'],
        'url' => $this->url(
            $closeAction['route'], $closeAction['params']
        )
    ];
    array_push($actions, $closeActionUrl);
}
echo $this->render('partials/read-only/main',
    [
        'header' => 'Public Inquiry',
        'actions' => $actions
    ]
);

if (isset($pi['agreedDate'])):
    echo $this->render('partials/pi-agreed.phtml', array('pi' => $pi, 'readonly' => $readonly));

    //we have a Pi so a hearing can be added
    if (isset($pi['piHearings']) && !empty($pi['piHearings'])):
        echo $this->render('partials/table');

        //we have a hearing, so decision can be added
        if (isset($pi['decidedByTc']) && !empty($pi['decidedByTc'])):
            echo $this->render('partials/pi-decision.phtml', array('pi' => $pi, 'readonly' => $readonly));
        else:
            echo $this->render('partials/pi-empty.phtml',
                array(
                    'heading' => 'Decision',
                    'shortHeading' => 'decision',
                    'route' => 'case_pi_decision',
                    'readonly' => $readonly
                )
            );
        endif;
    else:
        echo $this->render('partials/pi-empty.phtml',
            array('heading' => 'Hearing',
                'shortHeading' => 'hearing',
                'route' => 'case_pi_hearing',
                'section' => 'hearing',
                'pi' => $pi,
                'readonly' => $readonly
            )
        );
    endif;

    echo $this->render('partials/pi-sla.phtml', array('pi' => $pi, 'readonly' => $readonly));

else:
    echo $this->render(
        'partials/pi-empty.phtml',
        array(
            'heading' => 'Agreed and legislation',
            'shortHeading' => 'Public Inquiry',
            'route' => 'case_pi_agreed',
            'readonly' => $readonly
        )
    );
endif;