<?php
    use Zend\Form\Element\Button;
?>

<div class="submission-section__header">
    <h4 class="submission-section_title"><?php echo(isset($header) ? $this->translate($header) : '') ?></h4>
    <?php if (isset($actions)) : ?>
        <div class="actions-container">
            <?php
            foreach ($actions as $action) {
                if (isset($action['url'])) {
                    $attributeString = ' ';
                    if (isset($action['attributes']) && is_array($action['attributes'])) {
                        foreach ($action['attributes'] as $a_key => $a_val) {
                            $attributeString .= $a_key . '="' . $a_val . '"';
                        }
                    }
                    echo '<a href="' . $action['url'] . '" class="' . (isset($action['class']) ? $action['class'] :
                            'action--secondary') . '"' . $attributeString . '>' . $this->translate($action['label']) .
                        '</a>';
                }
                else{
                    $lowerLabel = strtolower($action['label']);
                    $element = new Button(str_replace(' ', '-', $lowerLabel));
                    $element->setAttribute('type', 'submit');
                    $element->setAttribute('name', 'action');
                    $element->setAttribute('id', $lowerLabel);
                    $element->setAttribute('class', (isset($action['class']) ? $action['class'] : 'action--secondary'));
                    $element->setAttribute('value', $this->translate($action['label']));
                    echo $this->formInput($element);
                }
            }
            ?>
        </div>
    <?php endif; ?>
</div>
