<?php
$data = $this->data['data']['overview'];
echo $this->render('partials/read-only/main',
    [
        'id' => $this->data['submissionSection'],
        'header' => (isset($this->data['description']) ? $this->data['description'] : ''),
        'multiItems' => [
            0 => [
                [
                    'label' => 'Name',
                    'value' => $data['title'] . ' ' . $data['forename'] . ' ' . $data['familyName']
                ],
                ['label' => 'Email', 'value' => $data['emailAddress']],
                ['label' => 'Dob', 'value' => $data['dob']],
                ['label' => 'Place of birth', 'value' => $data['placeOfBirth']],
                ['label' => 'Type', 'value' => $data['tmType']]
            ],
            1 => [
                ['label' => 'Home address', 'value' => $this->addressFormat($data['homeAddress'])],
                ['label' => 'Work address', 'value' => $this->addressFormat($data['workAddress'])]
            ]
        ]
    ]
);
