<div id="main" role="main">

    <div class="page-header">
        <div class="page-header__wrapper">
            <h1><?php echo $this->translate('500-title') ?></h1>
        </div>
    </div><!-- page-header-->

    <div class="row ">
        <div class="full-width">

            <?php if (!empty($id)): ?>
                <p>Correlation id <em><?php echo $this->escapeHtml($id); ?></em>.</p>
            <?php endif ?>

            <?php echo $this->partial('partials/error/exception'); ?>

        </div><!-- end .full-width -->
    </div>
</div>