<div id="main" role="main">
  
    <div class="page-header">
        <div class="page-header__wrapper">
            <h1><?php echo $this->translate('500-title') ?></h1>
        </div>
    </div><!-- page-header-->

    <div class="row">
      <div class="two-thirds">
          <div class="article">
              <?php echo $this->translate('markup-500-text'); ?>
              <hr>
              <p><a href="<?php echo $this->url('index'); ?>"><?php echo $this->translate('back-to-home'); ?></a></p>
          </div>
      </div>
    </div>
    
</div>

<?php

  if (!isset($stopRedirect)) {
      $url = $this->url('server-error') . (!empty($id) ? "?id=$id" : '');
      $this->inlineScript()->appendScript(
          '
          OLCS.ready(function() {
              window.location.href = "' . $url . '";
          });
          '
      );
  }