<?php
    $busReg = $this->placeholder('busReg')->getValue();
    $note = $this->placeholder('note')->getValue();
?>
<div class="small-module">
    <h4 class="title">Operator details</h4>
    <p class="small-module__details">
        <a href="<?php echo $this->url('operator/business-details', ['organisation' => $busReg['licence']['organisation']['id']], [], true);?>">
            <?php echo $this->escapeHtml($busReg['licence']['organisation']['name']); ?>
        </a>
    </p>
</div>

<div class="small-module">
    <h4 class="title">Licence details</h4>
    <p class="small-module__details">
        <a href="<?php echo $this->url('lva-licence', ['licence' => $busReg['licence']['id']], [], false); ?>"><?php echo $this->escapeHtml($busReg['licence']['licNo']); ?></a><br>
        <?php echo $this->translate($busReg['licence']['licenceType']['id']); ?><br/>
        <?php echo $this->translate($busReg['licence']['status']['id']); ?>
    </p>
</div>

<?php
echo $this->showMarkers(
    [
        \Olcs\Service\Marker\BusRegShortNoticeRefused::class,
        \Olcs\Service\Marker\BusRegEbsrMarker::class,
        \Olcs\Service\Marker\DisqualificationMarker::class,
    ]
);
?>

<?php
/**
 * Case quick actions
 *
 * @var \Zend\Navigation\Navigation
 */
$nav = $this->navigation('right-sidebar')
    ->menu($this->navigation()->findOneBy('id', 'bus-registration-quick-actions'))
    ->setPartial('partials/record-actions__group');
?>
<?php if (count($nav->getContainer()) > 0): ?>
    <div class="record-actions">
        <h4 class="title">Quick actions</h4>
        <?php echo $nav; ?>
    </div>
<?php endif; ?>

<?php
/**
 * Case quick actions
 *
 * @var \Zend\Navigation\Navigation
 */
$nav = $this->navigation('right-sidebar')
    ->menu($this->navigation()->findOneBy('id', 'bus-registration-decisions'))
    ->setPartial('partials/record-actions__group');
?>
<?php if (count($nav->getContainer()) > 0): ?>
    <div class="record-actions">
        <h4 class="title">Decisions</h4>
        <?php echo $nav; ?>
    </div>
<?php endif; ?>

<?php if (!empty($note) && !$this->isGranted(Common\RefData::PERMISSION_INTERNAL_LIMITED_READ_ONLY)):?>
    <div class="latest-note">
        <div class="latest-note__details"><?php echo substr($note, 0, 100); ?></div>
        <a
            class="latest-note__link"
            href="<?php echo $this->url(
                'licence/bus-processing/notes',
                [
                    'licence' => $busReg['licence']['id'],
                    'busRegId' => $busReg['id']
                ]
            ); ?>"
        >View all notes</a>
    </div>
<?php endif; ?>
