<div class="js-body__main">
<?php

echo $this->render(
    'partials/read-only/main',
    [
        'multiItems' => [
            [
                ['label' => 'No:', 'value' => $invoiceNo, 'class' => 'full-width'],
                ['label' => 'Description:', 'value' => $description, 'class' => 'full-width'],
                ['label' => 'Fee amount:', 'money' => $amount, 'class' => 'full-width'],
                ['label' => 'Outstanding:', 'money' => $outstanding, 'class' => 'full-width'],
                ['label' => 'Created:', 'date' => $created, 'class' => 'full-width'],
                [
                    'label' => 'Status:',
                    'noEscape' => true,
                    'value' => \Common\Service\Table\Formatter\FeeStatus::format($fee),
                    'class' => 'full-width',
                ],
            ],
        ]
    ]
);

if ($table) {
    echo $table;
}

if ($form) {
    echo $this->form($form);
}
?>
</div>