<?php

if (isset($title)) {
    ?>
    <div class="content__header js-title">
        <h3><?php echo $this->translate($title); ?></h3>
    </div>
    <?php
}
?>
<div class="js-body">
<?php
if (isset($sectionText)) {
    ?><p><?php echo $this->translate($sectionText); ?></p><?php
}

echo $table;


if (isset($scripts)) {
    foreach ($scripts as $script) {
        $this->inlineScript()->appendScript($script);
    }
}
