<div class="js-body__main">
<?php

echo $this->render(
    'partials/read-only/main',
    [
        'multiItems' => [
            [
                ['label' => 'Transaction No:', 'value' => $transaction['id'], 'class' => 'full-width'],
                ['label' => 'Date:', 'date' => $transaction['completedDate'], 'class' => 'full-width'],
                ['label' => 'Type:', 'value' => $transaction['type']['description'], 'class' => 'full-width'],
                ['label' => 'Method:', 'value' => $transaction['paymentMethod']['description'], 'class' => 'full-width'],
                ['label' => 'Reference:', 'date' => $transaction['reference'], 'class' => 'full-width'],
                ['label' => 'Processed by:', 'value' => $transaction['processedByUser']['loginId'], 'class' => 'full-width'],
                ['label' => 'Amount:', 'money' => $transaction['amount'], 'class' => 'full-width'],
            ],
        ]
    ]
);

if ($table) {
    echo $table;
}

?>
<a href="<?php echo $backLink; ?>" class="action--secondary">Back</a>
</div>