<?php

return [
    'bus_subsidy' => [
        'bus_subsidy.no' => 'No',
        'bus_subsidy.yes' => 'Yes',
        'bus_subsidy.in_part' => 'In Part'
    ],
    'bus_trc_status' => [
        'bus_trc_status.new' => 'New',
        'bus_trc_status.valid' => 'Valid',
        'bus_trc_status.revoked' => 'Revoked',
        'bus_trc_status.refused' => 'Refused'
    ],
    'case_categories_compliance' => [
        'case_category.1' => 'Offences (inc. driver hours)',
        'case_category.2' => 'Prohibitions',
        'case_category.3' => 'Convictions',
        'case_category.4' => 'Penalties',
        'case_category.5' => 'ERRU MSI',
        'case_category.6' => 'Bus compliance',
        'case_category.7' => 'Section 9',
        'case_category.8' => 'Section 43',
        'case_category.9' => 'Impounding'
    ],
    'case_categories_tm' => [
        'case_category.10' => 'Duplicate TM',
        'case_category.11' => 'Repute / professional competence of TM',
        'case_category.12' => 'TM Hours'
    ],
    'case_categories_app' => [
        'case_category.13' => 'Interim with / without submission',
        'case_category.14' => 'Representation',
        'case_category.15' => 'Objection',
        'case_category.16' => 'Non-chargeable variation',
        'case_category.17' => 'Regulation 31/29',
        'case_category.18' => 'Schedule 4/1',
        'case_category.19' => 'Chargeable variation',
        'case_category.20' => 'New application'
    ],
    'case_categories_referral' => [
        'case_category.21' => 'Surrender',
        'case_category.22' => 'Non application related maintenance issue',
        'case_category.23' => 'Review complaint',
        'case_category.24' => 'Late fee',
        'case_category.25' => 'Financial standing issue (continuation)',
        'case_category.26' => 'Repute fitness of director',
        'case_category.27' => 'Period of grace',
        'case_category.28' => 'In-Office revocation'
    ],
    'case_categories_bus' => [
        'case_category.29' => 'Yes'
    ],
    'case_stay_outcome' => [
        'stay_status_granted' => 'Granted',
        'stay_status_refused' => 'Refused'
    ],
    'operator_locations' => [
        'N' => 'Great Britain',
        'Y' => 'Northern Ireland'
    ],
    'operator_types' => [
        'lcat_gv' => 'Goods',
        'lcat_psv' => 'PSV'
    ],
    'licence_types' => [
        'ltyp_r' => 'Restricted',
        'ltyp_sn' => 'Standard National',
        'ltyp_si' => 'Standard International',
        'ltyp_sr' => 'Special Restricted',
    ],
    'business_types' =>
    [
        'org_t_rc' => 'Limited company',
        'org_t_st' => 'Sole Trader',
        'org_t_p' => 'Partnership',
        'org_t_llp' => 'Limited Liability Partnership',
        'org_t_pa' => 'Other (eg public authority, charity, trust, university)',
        'org_t_ir' => 'IRFO',
    ],
    'defendant_types' =>
    [
        'def_t_op'     => 'Operator',
        'def_t_owner'  => 'Owner',
        'def_t_part'   => 'Partner',
        'def_t_dir'    => 'Director',
        'def_t_driver' => 'Driver',
        'def_t_tm'     => 'Transport Manager',
        'def_t_other' => 'Other'
    ],
    'yes_no' => [
        'Y' => 'Yes',
        'N' => 'No'
    ],
    'document_types' => [
        'all' => 'All',
        'external' => 'Selfserve',
        'internal' => 'Internal'
    ],
    'vehicle_body_types' =>
    [
        'vhl_body_type.flat' => 'Flat sided or skeletal',
        'vhl_body_type.box' => 'Box body, or van, or curtain side',
        'vhl_body_type.tanker' => 'Tanker',
        'vhl_body_type.other' => 'Other type (such as cement mixer, livestock carrier)'
    ],
    'statement_types' =>
    [
        'statement_type.1' => 'Section 43',
        'statement_type.2' => 'Section 9',
        'statement_type.3' => 'NI Section 43',
        'statement_type.4' => 'NI Section 9',
        'statement_type.5' => 'NI Section 36',
        'statement_type.6' => 'NI Section 38'
    ],
    'contact_method' =>
    [
        'cm_email' => 'Email',
        'cm_fax' => 'Fax',
        'cm_letter' => 'Letter',
        'cm_tel' => 'Telephone',
    ],
    'countries' =>
    [
        'GB' => 'United Kingdom',
        'AF' => 'Afghanistan',
        'AX' => 'Aland Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua And Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia And Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Island',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo, Democratic Republic',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'CI' => "Cote D'Ivoire",
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands (Malvinas)',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard Island & Mcdonald Islands',
        'VA' => 'Holy See (Vatican City State)',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran, Islamic Republic Of',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle Of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KR' => 'Korea',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => "Lao People's Democratic Republic",
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libyan Arab Jamahiriya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MK' => 'Macedonia',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia, Federated States Of',
        'MD' => 'Moldova',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'AN' => 'Netherlands Antilles',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestinian Territory, Occupied',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Reunion',
        'RO' => 'Romania',
        'RU' => 'Russia',
        'RW' => 'Rwanda',
        'BL' => 'Saint Barthelemy',
        'SH' => 'Saint Helena',
        'KN' => 'Saint Kitts And Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin',
        'PM' => 'Saint Pierre And Miquelon',
        'VC' => 'Saint Vincent And Grenadines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome And Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia And Sandwich Isl.',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard And Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syrian Arab Republic',
        'TW' => 'Taiwan',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad And Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks And Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'US' => 'United States',
        'UM' => 'United States Outlying Islands',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela',
        'VN' => 'Viet Nam',
        'VG' => 'Virgin Islands, British',
        'VI' => 'Virgin Islands, U.S.',
        'WF' => 'Wallis And Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe'
    ],
    'appeal_reasons' => [
        'appeal_r_app' => 'Application',
        'appeal_r_lic_non_pi' => 'Disciplinary Non-PI',
        'appeal_r_lic_pi' => 'Disciplinary PI',
        'appeal_r_tm_non_pi' => 'Regulatory Non-PI',
        'appeal_r_tm_pi' => 'Regulatory PI'
    ],
    'appeal_outcomes' => [
        'appeal_o_dis' => 'Dismissed',
        'appeal_o_pas' => 'Partially Successful',
        'appeal_o_ref' => 'Refer Back to TC',
        'appeal_o_suc' => 'Successful'
    ],
    'submission_recommendation' => [
        'submission_recommendation.other' => 'Other',
        'submission_recommendation.propose-to-revoke' => 'In-Office revocation',
        'submission_recommendation.warning-letter' => 'Warning letter',
        'submission_recommendation.nfa' => 'NFA',
        'submission_recommendation.undertakings-conditions' => 'Undertakings & conditions',
        'submission_recommendation.public-inquiry' => 'Public Inquiry',
        'submission_recommendation.preliminary-hearing' => 'Preliminary Hearing',
        'submission_recommendation.stl-interview' => 'STL Interview'
    ],
     'submission_decision' => [
        'submission_decision.agree' => 'Agree',
        'submission_decision.partially-agree' => 'Partially agree',
        'submission_decision.disagree' => 'Disagree',
        'submission_decision.further-info' => 'Further information required'
    ],
    'complaint_types' =>
    [
        'ct_cor' => 'Continuing to operate after revocation',
        'ct_cov' => 'Condition of vehicles',
        'ct_dgm' => 'Driving in a dangerous manner',
        'ct_dsk' => 'Driver smoking',
        'ct_fls' => 'Failure to operate local service',
        'ct_lvu' => 'Leaving vehicle unattended with engine running',
        'ct_ndl' => 'Not having correct category of drivers licence',
        'ct_nol' => 'No operators licence',
        'ct_olr' => 'Operating local service off route',
        'ct_ovb' => 'Obstructing other vehicles at bus station/bus stop',
        'ct_pvo' => 'Parking vehicle out-with operating centre',
        'ct_rds' => 'Registration of duplicate services',
        'ct_rta' => 'Registered times not being adhered to',
        'ct_sln' => 'Speed limiters non-operative',
        'ct_spe' => 'Speeding',
        'ct_tgo' => 'Tachograph offences',
        'ct_ufl' => 'Unsafe loads',
        'ct_ump' => 'Use of mobile phones while driving',
        'ct_urd' => 'Using red diesel',
        'ct_vpo' => 'Vehicles parked and causing an obstruction',
    ],
    'complaint_status_types' =>
    [
        'cs_ack' => 'Acknowledged',
        'cs_pin' => 'PI Notififed',
        'cs_rfs' => 'Review Form Sent',
        'cs_vfr' => 'Valid For Review',
        'cs_yst' => 'Are you still there'
    ],
    'inspection_interval_vehicle' => [
        'inspection_interval_vehicle.1' => '1 {Week}',
        'inspection_interval_vehicle.2' => '2 {Weeks}',
        'inspection_interval_vehicle.3' => '3 {Weeks}',
        'inspection_interval_vehicle.4' => '4 {Weeks}',
        'inspection_interval_vehicle.5' => '5 {Weeks}',
        'inspection_interval_vehicle.6' => '6 {Weeks}',
        'inspection_interval_vehicle.7' => '7 {Weeks}',
        'inspection_interval_vehicle.8' => '8 {Weeks}',
        'inspection_interval_vehicle.9' => '9 {Weeks}',
        'inspection_interval_vehicle.10' => '10 {Weeks}',
        'inspection_interval_vehicle.11' => '11 {Weeks}',
        'inspection_interval_vehicle.12' => '12 {Weeks}',
        'inspection_interval_vehicle.13' => '13 {Weeks}'
    ],
    'inspection_interval_trailer' => [
        'inspection_interval_trailer.1' => '1 {Week}',
        'inspection_interval_trailer.2' => '2 {Weeks}',
        'inspection_interval_trailer.3' => '3 {Weeks}',
        'inspection_interval_trailer.4' => '4 {Weeks}',
        'inspection_interval_trailer.5' => '5 {Weeks}',
        'inspection_interval_trailer.6' => '6 {Weeks}',
        'inspection_interval_trailer.7' => '7 {Weeks}',
        'inspection_interval_trailer.8' => '8 {Weeks}',
        'inspection_interval_trailer.9' => '9 {Weeks}',
        'inspection_interval_trailer.10' => '10 {Weeks}',
        'inspection_interval_trailer.11' => '11 {Weeks}',
        'inspection_interval_trailer.12' => '12 {Weeks}',
        'inspection_interval_trailer.13' => '13 {Weeks}',
        'inspection_interval_trailer.0' => 'N/A'
    ],
    'tachograph_analyser' => [
        'tach_internal' => 'tachograph_analyser.tach_internal',
        'tach_external' => 'tachograph_analyser.tach_external',
        'tach_na' => 'tachograph_analyser.tach_na',
    ],
    'impounding_type' => [
        'impt_hearing' => 'Hearing',
        'impt_paper' => 'Paperwork only'
    ],
    'impounding_outcome' => [
        'impo_returned' => 'Vehicle(s) returned',
        'impo_not' => 'Vehicle(s) not returned',
    ],
    'hearing_location' => [
        'hearing_location.1' => 'Hearing location 1',
        'hearing_location.2' => 'Hearing location 2',
        'hearing_location.3' => 'Hearing location 3',
    ],
    'presiding_tc' => [
        'presiding_tc.1' => 'Presiding TC 1',
        'presiding_tc.2' => 'Presiding TC 2',
        'presiding_tc.3' => 'Presiding TC 3',
    ],
    'task-date-types' => [
        'today' => 'Today',
        'all' => 'All dates'
    ],
    'task-status-types' => [
        'open' => 'Open',
        'closed' => 'Closed',
        'all' => 'All'
    ],
    'prohibition_type' => [
        'pro_t_si' => 'Immediate (S)',
        'pro_t_sd' => 'Delayed (S)',
        'pro_t_sv' => 'Variation (S)',
        'pro_t_i' => 'Immediate',
        'pro_t_d' => 'Delayed',
        'pro_t_v' => 'Variation',
        'pro_t_ro' => 'Refusals Only',
        'pro_t_vr' => 'Variation & Refusals Only',
    ],
    'legislation_type.psv.gb' => [
        'legislation_type.psv.gb.1' => 'Section A The user of the vehicle held a valid operator\'s licence (whether or not '
            . 'authorising the use of the vehicle)',
        'legislation_type.psv.gb.2' => 'Section B It was not being, and had not been used in contravention of Section 12 of the 1981 Act.',
        'legislation_type.psv.gb.3' => 'Section C i did not know it was being or had been used in contravention  of '
            . 'Section 12 of the 1981 Act.',
        'legislation_type.psv.gb.4' => 'Section D That although knowing that at the time the vehicle was detained it was '
            . 'being or had been used in contravention of Section 12(1) '
            . 'of the 1981 Act, but; (i) had taken steps with a view to '
            . 'preventing that (ii) Has taken steps with a view to '
            . 'preventing any further such use.'
    ],
    'legislation_type.goods.ni' => [
        'legislation_type.goods.ni.1' => 'Section A At the time the vehicle was detained, the person using the vehicle held '
            . 'a valid licence (whether or not authorising the use of '
            . 'the vehicle);',
        'legislation_type.goods.ni.2' => 'Section B At the time the vehicle was detained, the vehicle was not being, and '
            . 'had not been, used in contravention of section 1 of the'
            . '2010 Act;',
        'legislation_type.goods.ni.3' => 'Section C Although at the time the vehicle was detained it was being, or had been,'
            . 'used in contravention of section 1 of the 2010 Act, the '
            . 'owner did not know that it was being, or had been, so used;',
        'legislation_type.goods.ni.4' => 'Section D Although knowing at the time the vehicle was detained that it was being, or '
            . 'had been, used in contravention of section 1 of the 2010 '
            . 'Act, the owner— (i)had taken steps with a view to '
            . 'preventing that use; and '
            . '(ii)has taken steps with a view to preventing any '
            . 'further such use.'
    ],
    'legislation_type.goods.gb' => [
        'legislation_type.goods.gb.1' => 'Section A The user of the vehicle held a valid operator\'s licence (whether of not authorising '
            . 'the use of the vehicle)',
        'legislation_type.goods.gb.2' => 'Section B It was not being, and had not been used in contravention of Section 2 of  the 1995 Act.',
        'legislation_type.goods.gb.3' => 'Section C I did not know it was being or had been used in contravention of '
            . 'Section 2 of the 1995 Act.',
        'legislation_type.goods.gb.4' => 'Section D That although knowing that at the time the '
            . 'vehicle was detained it was being or had been used in '
            . 'contravention of Section 2 of the 1995 Act, but;  had taken '
            . 'steps with a view to preventing that (ii) Has taken steps '
            . 'with a view to preventing any further such use.'
    ],
];
