<?php $payForm->prepare(); ?>
<div id="payGroup">
    <?php if ($payType == 'receipt') : ?>
    <div class="form-group">
        <label for="receipt" class="col-lg-2"><?php echo $this->resourceHelper('receipt'); ?></label>
        <div class="col-lg-2">
            <?php echo $this->formRow($payForm->get('receipt')); ?>
        </div>
    </div>
    <?php endif; ?>
    <div class="form-group">
        <div class="col-lg-4">
                    <?php echo $this->formButton($payForm->get('payCancel'), $this->resourceHelper('cancel')); ?>
                    <?php echo $this->formButton($payForm->get('payNowButton'), $this->resourceHelper('pay-now')); ?>
        </div>
    </div>
</div>