<?php
        $this->headScript()->prependFile($this->basePath() . '/js/listSort.js'); 
        $sort = array();
        if (isset($this->tableHeaderParams['sortColumn'])) {
            $sort[$this->tableHeaderParams['sortColumn']]['dir'] = $this->tableHeaderParams['sortDir'] == 'dn' ? 'arrDn' : 'arrUp';
        }
?>
<thead>
        <tr>
            <th class="text-muted columnSortable" id="licenceNumber">
                <span class="noWrap">
                    <img  src="/img/p.png" class="sprt <?php echo array_key_exists('licenceNumber', $sort) ? $sort['licenceNumber']['dir'] : 'arrUp'; ?>" />
                    <?php echo $this->resourceHelper('operator-search-results-licence-header'); ?>
                </span>
                <br><span class="noWrap"><?php echo $this->resourceHelper('operator-search-results-licence-header-status'); ?></span>
            </th>
            <th class="text-muted columnSortable" id="appId">
                <span class="noWrap">
                    <img  src="/img/p.png" class="sprt <?php echo array_key_exists('appId', $sort) ? $sort['appId']['dir'] : 'arrUp'; ?>" />
                    <?php echo $this->resourceHelper('operator-search-results-licence-header-app-id'); ?>/
                </span>
                <br><?php echo $this->resourceHelper('operator-search-results-licence-header-app-status'); ?>
            </th>
            <th class="text-muted columnSortable" id="operatorName">
                <span class="noWrap">
                    <img  src="/img/p.png" class="sprt <?php echo array_key_exists('operatorName', $sort) ? $sort['operatorName']['dir'] : 'arrUp'; ?>" />
                    <?php echo $this->resourceHelper('operator-search-results-licence-header-op-name'); ?> 
                </span>
                <br><span class="noWrap"><?php echo $this->resourceHelper('operator-search-results-licence-header-trading-name'); ?></span></th>
            <th class="text-muted columnSortable" id="companyNumber">
                <span class="noWrap">
                    <img  src="/img/p.png" class="sprt <?php echo array_key_exists('companyNumber', $sort) ? $sort['companyNumber']['dir'] : 'arrUp'; ?>" />
                    <?php echo $this->resourceHelper('operator-search-results-licence-header-company'); ?>
                </span><br><span class="noWrap"><?php echo $this->resourceHelper('licence-type'); ?></span></th>
            <th class="text-muted columnSortable" id="lastActionDate">
                <span class="noWrap">
                    <img  src="/img/p.png" class="sprt <?php echo array_key_exists('lastActionDate', $sort) ? $sort['lastActionDate']['dir'] : 'arrUp'; ?>" />
                    <?php echo $this->resourceHelper('operator-search-results-licence-header-last-act'); ?>/
                </span><br><?php echo $this->resourceHelper('operator-search-results-licence-header-cn-date'); ?>
            </th>
            <th class="text-muted columnSortable" id="correspondenceAddress">
                <span class="noWrap">
                    <img  src="/img/p.png" class="sprt <?php echo array_key_exists('correspondenceAddress', $sort) ? $sort['correspondenceAddress']['dir'] : 'arrUp'; ?>" />
                    <?php echo $this->resourceHelper('operator-search-results-licence-header-correspondence'); ?>
                </span><br><?php echo $this->resourceHelper('operator-search-results-licence-header-address'); ?>
            </th>
            <th class="text-muted columnSortable" id="operatorCentre">
                <span class="noWrap">
                    <img  src="/img/p.png" class="sprt <?php echo array_key_exists('operatorCentre', $sort) ? $sort['operatorCentre']['dir'] : 'arrUp'; ?>" />
                    <?php echo $this->resourceHelper('operator-search-results-licence-op-center'); ?>
                </span><br><?php echo $this->resourceHelper('operator-search-results-licence-header-address'); ?>
            </th>
            <th class="text-muted columnSortable" id="caseNumber">
                <span class="noWrap">
                    <img  src="/img/p.png" class="sprt <?php echo array_key_exists('caseNumber', $sort) ? $sort['caseNumber']['dir'] : 'arrUp'; ?>" />
                    <?php echo $this->resourceHelper('operator-search-results-licence-header-case'); ?>
                </span>
            </th>
            <th class="text-muted columnSortable" id="mlh">
                <span class="noWrap">
                    <img  src="/img/p.png" class="sprt <?php echo array_key_exists('mlh', $sort) ? $sort['mlh']['dir'] : 'arrUp'; ?>" />
                    <?php echo $this->resourceHelper('operator-search-results-licence-header-mlh'); ?>
                </span>
            </th>
            <th class="text-muted columnSortable" id="addInfo">
                <span class="noWrap">
                    <img  src="/img/p.png" class="sprt <?php echo array_key_exists('addInfo', $sort) ? $sort['addInfo']['dir'] : 'arrUp'; ?>" />
                    <?php echo $this->resourceHelper('operator-search-results-licence-header-add'); ?>
                </span><br><?php echo $this->resourceHelper('operator-search-results-licence-header-info'); ?>
            </th>
        </tr>
    </thead>