<?php 
$this->headScript()->prependFile($this->basePath() . '/js/selfserve/application/businessDetails.js');
$this->placeholder('body-class')->set("full-page");
?>
<?php
    echo $this->partial('selfserve/application/partials/navigation', array(
        'selectedPage' => 'your-business',
    ));
?>
<?php $businessDetailsForm->prepare(); ?>

<?php echo $this->partial('common/errorMessages', array('messages' => $messages)); ?>
<?php echo $this->form()->openTag($businessDetailsForm); ?>

<div id="businessDetailsDiv" class="row">

<?php
    echo $this->partial('selfserve/application/forms/business-details-form', array(
        'businessDetailsForm' => $businessDetailsForm,
        'licence' => $licence,
        'application' => $application
    ));
    
?>
    
<div>
    <div class="form-group">
<?php echo $this->formButton($businessDetailsForm->get('back'), $this->resourceHelper('back')); ?>
<?php echo $this->formButton($businessDetailsForm->get('exit'), $this->resourceHelper('exit')); ?>
<?php echo $this->formButton($businessDetailsForm->get('savenext'), $this->resourceHelper('savenext')); ?>
    </div>

    <div class='clear-both'></div>
</div>
<?php echo $this->form()->closeTag(); ?>    
