<?php 
$this->placeholder('body-class')->set("full-page");

?>
<?php $businessDetailsForm->prepare(); ?>

<?php echo $this->partial('common/errorMessages', array('messages' => $messages)); ?>
<?php echo $this->form()->openTag($businessDetailsForm); ?>

<div id="businessDetailsDiv" class="row">

<?php
    echo $this->partial('selfserve/application/forms/business-details-form', array(
        'businessDetailsForm' => $businessDetailsForm
    ));
    
?>
    <div class="form-group">
        
        <button id="cancelbutton" name="cancel" class="btn btn-cancel" type="button"><?php echo $this->resourceHelper('common-button-cancel'); ?></button>
        <button id="submitbutton" name="submit" class="btn btn-success btn-save pull-right"><?php echo $this->resourceHelper('common-button-save-and-next'); ?></button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
