<?php
echo $this->formRow($registeredCompanyDetailsForm->get('entityTypes'));
echo $this->formRow($registeredCompanyDetailsForm->get('licenceTypes'));
echo $this->formRow($registeredCompanyDetailsForm->get('operatorTypes'));
echo $this->formRow($registeredCompanyDetailsForm->get('trafficAreaType'));
echo $this->formRow($registeredCompanyDetailsForm->get('dateApplicationReceived'));
?>
<div class="">
    <div class="row">
        <div class="pheading">
            <a href="#" class="acc-buttons collapsible acc-collapsed expanded"><?php echo $this->resourceHelper('registered-company-details-header'); ?></a>
        </div>

        <div class="accordion">
            <div class="row form-group required" >
                <label for="companyNumId" class="col-lg-3 control-label"><?php echo $this->resourceHelper('company-registration-form-label-company-id'); ?></label>
                <div class="col-lg-4 itext">
                    <?php echo $this->formRow($registeredCompanyDetailsForm->get('companyNumId')); ?>
                </div>
            </div>
            
            <div class="row form-group " id="operatorNameContainer">
                <label for="mainOperatorName" class="col-lg-3 control-label"><?php echo $this->resourceHelper('company-registration-form-label-operator-name'); ?></label>
                <div class="col-lg-4 itext">
                    <?php  
                        $prefilled = $registeredCompanyDetailsForm->get('operatorNameTextHidden')->getValue();
                        
                        if (!empty($prefilled)) {
                    ?>
<script type="text/javascript">
    // prefill the operator name
    $(document).ready(function(){
        var $fieldgroup = $('#operatorNameContainer');
     
        olcs.overlayForm.mapDataToField($fieldgroup, {
                    name : '<?php echo $prefilled;?>'
                }, 'operator');
    }); // end document.ready()
</script>                
                    <?php
                            
                            //$registeredCompanyDetailsForm->get('mainOperatorName')->setValue($prefilled);
                            //$registeredCompanyDetailsForm->get('mainOperatorName')->setAttribute('style', 'display:none;');

                            //$html = '<div id="operatorNameText" class="help-block"><a href="#" id="editOperatorName" class="value">'.$prefilled.'</a> <a href="#" id="removeOperatorName">X</a></div>';                           
                            echo $this->formRow($registeredCompanyDetailsForm->get('mainOperatorName'));
                            //echo $html; 
                        } else {
                            echo $this->formRow($registeredCompanyDetailsForm->get('mainOperatorName'));
                        }

                        echo $this->formRow($registeredCompanyDetailsForm->get('operatorNameTextHidden'));
                        echo $this->formRow($registeredCompanyDetailsForm->get('operatorId'));
                        echo $this->formRow($registeredCompanyDetailsForm->get('operatorVersion'));
                    ?>
                </div>
                <div class="col-lg-2">
                    <?php echo $this->formButton($registeredCompanyDetailsForm->get('search'), $this->resourceHelper('search')); ?>
                    <a href='/application/search/operator' id='searchOperatorPopup'></a>
                </div>
            </div>
            <div class="row form-group" id="tradingNameContainer">
                <label for="tradingNameId" class="col-lg-3 control-label"><?php echo $this->resourceHelper('company-registration-form-label-trading-name'); ?></label>
                <div class="col-lg-4 itext">
                    <?php echo $this->formRow($registeredCompanyDetailsForm->get('tradingNameId')); ?>
                    <span class="trading-names-collection"><?php
                        $tradingNames = $registeredCompanyDetailsForm->get('tradingNames');
                        if (!empty($tradingNames) && count($tradingNames) > 0) {
                        
                            echo $this->formCollection($registeredCompanyDetailsForm->get('tradingNames'));
                            echo '<div style="display: block;" id="tradingNameText" class="help-block default-hidden">';
                            foreach($tradingNames as $tn) {
                                echo '<span class="tradingNameEntry">'.$tn->getValue().' <a href="#" class="removeTradingName">X</a></span>';
                            }
                            echo '</div>';
                            
                        } else {
                            //echo $this->formRow($registeredCompanyDetailsForm->get('mainOperatorName'));
                        }
                    
                    ?></span>
                    <div id='tradingNameText' class='help-block default-hidden'></div>
                </div>
                <div class="col-lg-2">
                    <?php echo $this->formButton($registeredCompanyDetailsForm->get('tradingAddAnother'), $this->resourceHelper('add-another')); ?>
                </div>
            </div>
            <?php
                if ( ! ( $operatorType == "psv" && $licenceType == "special restricted" ) ) {
                    if ( ( $operatorType == "psv" && $licenceType == "restricted" ) ) {
                        ?>
                        <div class="row form-group required">
                            <label for="tradingDetails" class="col-lg-3 control-label"><?php
                                        echo $this->resourceHelper('company-registration-form-label-main-occupation'); ?>
                            </label>
                            <div class="col-lg-4 itext">
                                <?php echo $this->formRow($registeredCompanyDetailsForm->get('tradingDetails')); ?>
                            </div>
                        </div>
                        <?php

                    } else {
                        ?>
                        <div class="row form-group required">
                            <label for="tradingDetails" class="col-lg-3 control-label">
                                <?php echo $this->resourceHelper('company-registration-form-label-trade-business'); ?>
                            </label>
                            <div class="col-lg-4 itext">
                                <?php echo $this->formRow($registeredCompanyDetailsForm->get('tradingDropdown')); ?>
                            </div>
                            <div class="col-lg-5 itext">
                                <?php echo $this->formRow($registeredCompanyDetailsForm->get('tradingOther')); ?>
                            </div>
                        </div>
                        <?php
                    }
                }
            ?>
    </div>
    </div>
</div>
