<div class="row form-group" id="tradingNameContainer">
    <label for="tradingNameId" class="col-lg-3 control-label"><?php echo $this->resourceHelper('company-registration-form-label-trading-name'); ?></label>
    <div class="col-lg-4 itext">
        <?php echo $this->formRow($form->get('tradingNameId')); ?>
        <span class="trading-names-collection"><?php
            echo $this->formCollection($form->get('tradingNames'));
        ?></span>
        <div id='tradingNameText' class='help-block default-hidden'></div>
    </div>
    <div class="col-lg-2">
        <?php echo $this->formButton($form->get('tradingAddAnother'), $this->resourceHelper('add-another')); ?>
    </div>
</div>

<div class="row form-group required">
    <label for="tradingDetails" class="col-lg-3 control-label">
        <?php echo $this->resourceHelper('company-registration-form-label-trade-business'); ?>
    </label>
    <div class="col-lg-4 itext">
        <?php echo $this->formRow($form->get('tradingDropdown')); ?>
    </div>
    <div class="col-lg-5 itext">
        <?php echo $this->formRow($form->get('tradingOther')); ?>
    </div>

</div>