<div class="list-grey">
<div class="govuk-inset-text">
  Use this information to progress the operator's application:
</div>
<h4>Vehicle discs</h4>
<dl class="govuk-summary-list govuk-summary-list--no-border">
      <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key">
          Number of destroyed discs
        </dt>
        <dd class="govuk-summary-list__value">
            <?php echo $this->surrender['discDestroyed'] ?? 0;?>
        </dd>
      </div>
      <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key">
          Number of lost discs
        </dt>
        <dd class="govuk-summary-list__value">
            <?php echo $this->surrender['discLost'] ?? 0;?>
            <?php if (!empty($this->surrender['discLostInfo'])): ?>
            <br> <?php echo $this->surrender['discLostInfo']; ?>
            <?php endif ?>
        </dd>
      </div>
      <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key">
          Number of stolen discs
        </dt>
        <dd class="govuk-summary-list__value">
           <?php echo $this->surrender['discStolen'] ?? 0;?>
           <?php if (!empty($this->surrender['discStolenInfo'])): ?>
           <br> <?php echo $this->surrender['discStolenInfo']; ?>
           <?php endif ?>
        </dd>
      </div>
</dl>
<hr class="govuk-section-break govuk-section-break--visible">
<dl class="govuk-summary-list">
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      Operator Licence
    </dt>
    <dd class="govuk-summary-list__value">
        <?php echo $this->surrender['licenceDocumentStatus']['description'];?>
        <?php if (isset($this->surrender['licenceDocumentInfo'])): ?>
            <br> <?php echo $this->surrender['licenceDocumentInfo']; ?>
        <?php endif ?>
    </dd>
  </div>

  <?php if (isset($this->surrender['communityLicenceDocumentStatus'])):?>
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      Community licence
    </dt>
    <dd class="govuk-summary-list__value">
        <?php echo $this->surrender['communityLicenceDocumentStatus']['description'];?>
        <?php if (isset($this->surrender['communityLicenceDocumentInfo'])): ?>
            <br> <?php echo $this->surrender['communityLicenceDocumentInfo']; ?>
        <?php endif ?>
    </dd>
  </div>
  <?php endif ?>

  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      Declaration signature
    </dt>
    <dd class="govuk-summary-list__value">
        <?php echo $this->surrenderDetails($this->surrender)->getDeclarationSignatureText();?>
    </dd>
  </div>
</dl>
</div>