<div class="list-grey">
<div class="govuk-inset-text">
  Use this information to progress the operator's application:
</div>
<h4>Vehicle discs</h4>
<dl class="govuk-summary-list govuk-summary-list--no-border">
      <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key">
          Number of destroyed discs
        </dt>
        <dd class="govuk-summary-list__value">
            <?php echo $this->surrender['discDestroyed'] ?? 0;?>
        </dd>
      </div>
      <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key">
          Number of lost discs
        </dt>
        <dd class="govuk-summary-list__value">
            <?php echo $this->surrender['discLost'] ?? 0;?>
        </dd>
      </div>
      <?php if (!empty($this->surrender['discLostInfo'])): ?>
      <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key govuk-summary-list__key--weight-normal">
          Details of lost discs
        </dt>
        <dd class="govuk-summary-list__value">
            <?php echo $this->surrender['discLostInfo']; ?>
        </dd>
      </div>
      <?php endif ?>
      <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key">
          Number of stolen discs
        </dt>
        <dd class="govuk-summary-list__value">
           <?php echo $this->surrender['discStolen'] ?? 0;?>
        </dd>
      </div>
      <?php if (!empty($this->surrender['discStolenInfo'])): ?>
      <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key govuk-summary-list__key--weight-normal">
          Details of stolen discs
        </dt>
        <dd class="govuk-summary-list__value">
            <?php echo $this->surrender['discStolenInfo']; ?>
        </dd>
      </div>
      <?php endif ?>
</dl>
<dl class="govuk-summary-list govuk-summary-list--no-border">
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      Operator licence
    </dt>
    <dd class="govuk-summary-list__value">
        <?php echo $this->surrender['licenceDocumentStatus']['description'];?>
    </dd>
  </div>
  <?php if (isset($this->surrender['licenceDocumentInfo'])): ?>
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key govuk-summary-list__key--weight-normal">
      <?php echo $this->surrenderDetails($this->surrender)->returnLicenceDocumentDetailsText();?>
    </dt>
    <dd class="govuk-summary-list__value">
        <?php echo $this->surrender['licenceDocumentInfo'];?>
    </dd>
  </div>
  <?php endif ?>

  <?php if (isset($this->surrender['communityLicenceDocumentStatus'])):?>
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      Community licence
    </dt>
    <dd class="govuk-summary-list__value">
        <?php echo $this->surrender['communityLicenceDocumentStatus']['description'];?>
    </dd>
  </div>
  <?php if (isset($this->surrender['communityLicenceDocumentInfo'])): ?>
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key govuk-summary-list__key--weight-normal">
      <?php echo $this->surrenderDetails($this->surrender)->returnCommunityLicenceDocumentDetailsText();?>
    </dt>
    <dd class="govuk-summary-list__value">
        <?php echo $this->surrender['communityLicenceDocumentInfo']; ?>
    </dd>
  </div>
  <?php endif ?>
  <?php endif ?>
</dl>

<dl class="govuk-summary-list govuk-summary-list--no-border">

  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      Declaration signature
    </dt>
    <dd class="govuk-summary-list__value">
        <?php echo $this->surrenderDetails($this->surrender)->getDeclarationSignatureText();?>
    </dd>
  </div>
</dl>
</div>