<div class="surrender-govuk-summary-list list-grey">
<div class="govuk-inset-text">
  Use this information to progress the operator's application:
</div>
<dl class="govuk-summary-list">
<section class="vehicle-discs-section">
    <h4 class="govuk-heading-s">Vehicle discs</h4>
      <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key govuk-summary-list--border-bottom">
          <p class="govuk-body">Number of destroyed discs</p>
        </dt>
        <dd class="govuk-summary-list__value govuk-summary-list--border-bottom">
          <?php echo "" ?>
        </dd>
      </div>
      <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key govuk-summary-list--border-bottom">
          <p class="govuk-body">Number of lost discs</p>
        </dt>
        <dd class="govuk-summary-list__value govuk-summary-list--border-bottom">
          Sarah Philips
        </dd>
      </div>
      <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key">
          <p class="govuk-body">Details</p>
        </dt>
        <dd class="govuk-summary-list__value">
          Sarah Philips
        </dd>
      </div>
</section>
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      Operator licence
    </dt>
    <dd class="govuk-summary-list__value">
      5 January 1978
    </dd>
  </div>
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      Community licence
    </dt>
    <dd class="govuk-summary-list__value">
      72 Guild Street
    </dd>
  </div>
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      Declaration signature
    </dt>
    <dd class="govuk-summary-list__value">
      <p class="govuk-body">07700 900457</p>
      <p class="govuk-body">sarah.phillips@example.com</p>
    </dd>
  </div>
</dl>
</div>