<?php
$pageTitle = $this->placeholder('pageTitle')->getValue();
?>

<div class="js-response">
  <div class="js-title">
    <?php if (isset($this->pageTitle)):
        echo $this->translate($this->pageTitle);
    elseif ($pageTitle):
        echo $this->translate($pageTitle);
    endif;
    ?>
  </div>
  <div class="js-body">
    <div class="js-content">
      <?php echo $this->content; ?>
    </div>

    <div class="js-script">
      <?php echo $this->inlineScript() ?>
    </div>
  </div>
</div>
