<div class="four-fiths--left">
    <?php
        echo $this->navigation('navigation')
                    ->menu($this->navigation()->findOneBy('id', 'application'))
                    ->setPartial('view-new/partials/horizontal-navigation');
    ?>
    <div class="content">
        <?php echo $this->content; ?>
    </div>
</div>

<div class="one-fifth--right">
    <div class="record-actions">
        <h5>Quick actions</h5>
        <ul class="record-actions__group">
            <li class="record-actions__item actions--secondary"><a href="">Create case</a></li>
        </ul>
    </div>
</div>
