<div class="four-fifths--left">
    <?php
        echo $this->navigation('navigation')
                    ->menu($this->navigation()->findOneBy('id', 'application'))
                    ->setPartial('partials/horizontal-navigation');
    ?>
    <div class="content">
        <?php echo $this->content; ?>
    </div>
</div>

<div class="one-fifth--right">

    <?php
    echo $this->showMarkers();
    ?>

  <?php
  /**
   * Application quick actions
   *
   * @var \Zend\Navigation\Navigation
   */
  $nav = $this->navigation('right-sidebar')
      ->menu($this->navigation()->findOneBy('id', 'application-quick-actions'))
      ->setPartial('partials/record-actions__group');
  ?>
  <?php if ($nav->getContainer()->hasPages(true) && $nav->getContainer()->isVisible()): ?>
    <div class="record-actions">
      <h5>Quick actions</h5>
      <?php echo $nav; ?>
    </div>
  <?php endif; ?>

  <?php
  /**
   * Decisions quick actions
   *
   * @var \Zend\Navigation\Navigation
   */
  $nav = $this->navigation('right-sidebar')
      ->menu($this->navigation()->findOneBy('id', 'application-decisions'))
      ->setPartial('partials/record-actions__group');
  ?>
  <?php if ($nav->getContainer()->hasPages(true)): ?>
    <div class="record-actions">
      <h5>Decisions</h5>
      <?php echo $nav; ?>
    </div>
  <?php endif; ?>
</div>
