<div class="four-fifths--left">
    <?php
        echo $this->navigation('navigation')
                    ->menu($this->navigation()->findOneBy('id', 'application'))
                    ->setPartial('partials/horizontal-navigation');
    ?>
    <div class="content js-body__main">
        <?php echo $this->content; ?>
    </div>
</div>

<div class="one-fifth--right">
    <?php if (isset($actions)) { echo $actions; } ?>
</div>
