<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('')); ?>
    <?php echo $this->headMeta() ->appendName('viewport', 'width=device-width, initial-scale=1.0') ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>
    <?php /* echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')); */
      echo $this->headLink()->appendStylesheet($this->assetPath('/styles/' . $this->applicationName() . '.css')) ?>
    <?php echo $this->headScript(); ?>
  </head>
  <body class="internal">
    <script>document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');</script>

    <div role="banner" class="global-header">
      <div class="global-header__wrapper">
        <h2 class="global-header__title"><a href="/">OLCS</a></h2>
        
        <div class="search">
          <div class="search__wrapper">
            <?php if ($this->searchForm):?>
              <form action="<?php echo $this->url('search')?>" method="POST">
                <?php echo $this->formInput($this->searchForm->get('search')); ?>
                <div class="search__select">
                  <?php echo $this->formSelect($this->searchForm->get('index')); ?>
                </div><!-- .search__select -->
                <?php echo $this->formSubmit($this->searchForm->get('submit')); ?>
                  <?php echo $this->formElement($this->searchForm->get('csrf')) ?>
              </form>
            <?php endif?>
          </div>
          <a href="<?php echo $this->url('advancedsearch')?>" class="search__advanced"><?php echo $this->translate('Advanced'); ?></a>
        </div><!--  search -->

        <ul class="admin">
          <li class="admin__title"><?php echo $this->translate('Admin'); ?>
            <div class="admin__menu">
              <ul class="admin__submenu">
                <li class="admin__item"><a href="/admin/scanning"><?php echo $this->translate('Scanning'); ?></a></li>
                <li class="admin__item"><a href="/admin/printing"><?php echo $this->translate('Printing'); ?></a></li>
                <li class="admin__item"><a href="/admin/disc-printing"><?php echo $this->translate('Disc Printing'); ?></a></li>
                <li class="admin__item"><a href="/admin/publication"><?php echo $this->translate('Publications'); ?></a></li>
                <li class="admin__item"><a href="/admin/continuation"><?php echo $this->translate('Continuations'); ?></a></li>
                <li class="admin__item"><a href="/admin/report"><?php echo $this->translate('Reports'); ?></a></li>
              </ul>
              <ul class="admin__submenu">
                <li class="admin__item"><?php echo $this->translate('System settings'); ?></li>
                <li class="admin__item"><a href="/admin/user-management"><?php echo $this->translate('User management'); ?></a></li>
                <li class="admin__item"><a href="/admin/financial-standing"><?php echo $this->translate('Financial standing rates'); ?></a></li>
                <li class="admin__item"><a href="/admin/public-holiday"><?php echo $this->translate('Public holidays'); ?></a></li>
                <li class="admin__item"><a href="/admin/system-message"><?php echo $this->translate('System messages'); ?></a></li>
              </ul><!-- admin__submenu -->
            </div><!-- admin__menu -->
          </li>
        </ul><!-- admin -->
      </div><!-- end global-header__wrapper -->
    </div><!-- end global-header -->

    <?php echo $this->header; ?>

    <div class="page-wrapper">
      <div id="main" role="main">
        <?php echo $this->content; ?>
      </div>
    </div><!-- .page-wrapper-->

    <!-- Start: Global and Inline Script -->
    <?php echo $this->inlineScript()
        ->prependFile($this->assetPath('js/' . $this->applicationName() . '.js')) ?>
    <!-- End: Global and Inline Script -->
    </body>
</html>
