<div class="four-fifths--left">
    <?php
    echo $this->navigation('navigation')
        ->menu($this->navigation()->findOneBy('id', 'licence_bus'))
        ->setUlClass('horizontal-navigation')
        ->setAddClassToListItem(true)
        ->setPartial('partials/horizontal-navigation');
    ?>
    <div class="content">
        <?php echo $this->content ?>
    </div>
</div>

<div class="one-fifth--right">

</div>