<div class="one-fifth--left">
    <h4>Filter by:</h4>
    <?php
        $tableFilters = $this->placeholder('tableFilters')->getValue();
        if($tableFilters instanceof \Zend\Form\Form) {
            echo $this->form($tableFilters);
        }
    ?>
</div><!-- one-fifth-left -->
<div class="three-fifths">
<?php

$table = $this->placeholder('table')->getValue();

if (!empty($table)) {

    echo $table;
}
?>
</div><!-- three-fifths -->
