<div class="one-fifth--left">
    <?php
    if (!isset($navigation)) {

        $navigation = $this->navigation('navigation');

        if ($navigation) {
            $navigation = $navigation->findOneBy('active', true);
        }
    }

    if ($navigation):

    ?>
    <h4><?php echo $this->translate($navigation->getLabel()); ?></h4>
    <?php
        echo $this->navigation($navigation)
            ->menu()->setPartial('partials/vertical-navigation');

    endif;
    ?>
</div>
<div class="three-fifths  js-body__main">
    <?php echo $this->flashMessengerAll(); ?>
    <?php echo $this->content; ?>
</div>
