<div class="four-fifths--left">
    <?php
    echo $this->navigation('navigation')
        ->menu($this->navigation()->findOneBy('id', 'licence'))
        ->setUlClass('horizontal-navigation')
        ->setAddClassToListItem(true)
        ->setPartial('layout/partials/tabs');
    ?>
    <div class="one-fifth--left">
        <div class="content">
            <h4><?php echo $this->translate('internal-licence-bus'); ?></h4>
            <?php
            $tableFilters = $this->placeholder('tableFilters')->getValue();
            echo $this->form($tableFilters);
            ?>
        </div>

    </div>
    <div class="three-fifths">
        <div class="content">
            <h4><?php echo $this->translate('internal-licence-bus-list'); ?></h4>
            <?php echo $this->content ?>
        </div>
    </div>
</div>

<div class="one-fifth--right">
    <div class="record-actions">
        <h5>Quick actions</h5>
        <ul class="record-actions__group">
            <li class="record-actions__item actions--secondary"><a href="">Create case</a></li>
        </ul>
    </div>
</div>