<?php

$currentSection = $this->navigation('navigation')->findOneBy('active', 1);
$currentSectionParent = $currentSection->getParent();

$case = $this->placeholder('case')->getValue();

?>

<div class="one-fifth--left">
    <h4><?php echo $this->translate($currentSection->getParent()->getLabel()); ?></h4>
    <?php
        echo $this->navigation($currentSectionParent)->menu()->setPartial('partials/vertical-navigation');
    ?>
</div>
<div class="three-fifths     js-body__main">
    <?php echo $this->flashMessengerAll(); ?>
    <?php echo $this->content; ?>
</div>
