<?php

$case = $this->placeholder('case')->getValue();
$markers = $this->placeholder('markers')->getValue();
?>

<div class="four-fiths--left">
    <?php
        echo $this->navigation('navigation')
                  ->menu($this->navigation()->findOneBy('id', 'case'))
                  ->setPartial('layout/partials/tabs');
    ?>
    <div class="content">
      <?php echo $this->content ?>
    </div>
</div>

<div class="one-fifth--right">

    <?php if (isset($case['licence'])): ?>
    <?php if ($case['licence']['organisation']): ?>
    <h3>Operator</h3>
    <p><a href="#"><?php echo $case['licence']['organisation']['name']; ?></a></p>
    <p><?php echo $this->translate($case['licence']['organisation']['type']['id']); ?><br/>{Sample Traffic Area}</p>
    <?php endif; ?>

    <h3>Licence</h3>
    <p><a href="<?php echo $this->url('lva-licence', ['licence' => $case['licence']['id']], [], false); ?>"><?php echo $case['licence']['licNo']; ?></a></p>
    <p><?php echo $this->translate($case['licence']['licenceType']['id']); ?><br/><?php echo $this->translate($case['licence']['status']['id']); ?></p>
    <?php endif; ?>

    <?php
        echo $this->markers($markers, 'appeal');
        echo $this->markers($markers, 'stay');
    ?>

<div class="record-actions">
    <h5>Quick actions</h5>
    <ul class="record-actions__group">
        <li class="record-actions__item">
            <a href="<?php echo $this->url('submission', ['action' => 'add'], [], true); ?>" class="action--secondary">Create submission</a>
        </li>
        <li class="record-actions__item">
            <a href="<?php echo $this->url('case_statement', ['action' => 'add'], [], true); ?>" class="action--secondary">Generate statement</a>
        </li>
    </ul>
    <h5>Decisions</h5>
    <ul class="record-actions__group">
        <li class="record-actions__item"><a href="#" class="action--secondary">Suspend</a></li>
        <li class="record-actions__item"><a href="#" class="action--secondary">Curtail</a></li>
        <li class="record-actions__item"><a href="#" class="action--secondary">Revoke</a></li>
    </ul>
</div>
</div>
