<div class="four-fiths--left">
    <?php
        echo $this->navigation('navigation')
                  ->menu($this->navigation()->findOneBy('id', 'case'))
                  ->setPartial('layout/partials/tabs');
    ?>
    <div class="content">
      <?php echo $this->content ?>
    </div>
</div>

<div class="one-fifth--right">

    <?php if ($case['licence']): ?>
    <?php if ($case['licence']['organisation']): ?>
    <h3>Operator</h3>
    <p><a href="#"><?php echo $case['licence']['organisation']['name']; ?></a></p>
    <p><?php echo $this->translate($case['licence']['organisation']['type']['id']); ?><br/>{Sample Traffic Area}</p>
    <?php endif; ?>
    <h3>Licence</h3>
    <p><a href="<?php $this->url('licence/details/overview', ['licence' => $case['licence']['id']], [], true); ?>"><?php echo $case['licence']['licNo']; ?></a></p>
    <p><?php echo $this->translate($case['licence']['licenceType']['id']); ?><br/><?php echo $this->translate($case['licence']['status']['id']); ?></p>
    <?php endif; ?>

</div>
