<div class="four-fiths--left">
    <?php
        echo $this->navigation('navigation')
                  ->menu($this->navigation()->findOneBy('id', 'case'))
                  ->setPartial('layout/partials/tabs');
    ?>
    <div class="content">
      <?php echo $this->content ?>
    </div>
</div>

<div class="one-fifth--right">
  <div class="record-actions">
    <h4>Operator</h4>
    <ul class="record-actions__group">
      <li class="record-actions__item actions--secondary"><a href="">List Item</a></li>
    </ul>
  </div>
</div>
