<?php

$case = $this->placeholder('case')->getValue();
$markers = $this->placeholder('markers')->getValue();

$application = $this->placeholder('application')->getValue();

$transportManager = $this->placeholder('transportManager')->getValue();

?>

<div class="four-fifths--left">
  <?php
  echo $this->navigation('navigation')
  ->menu($this->navigation()->findOneBy('id', 'case'))
  ->setPartial('partials/horizontal-navigation');
  ?>

  <div class="content">
    <?php echo $this->content; ?>
  </div>
</div>

<div class="one-fifth--right">
  <?php if (isset($case['licence']) && !empty($case['licence'])): ?>
    <?php if ($case['licence']['organisation']): ?>
    <div class="small-module">
      <h4 class="small-module__title">Operator details</h4>
      <p class="small-module__details">
        <a href="#"><?php echo $case['licence']['organisation']['name']; ?></a><br>
        <?php echo $this->translate($case['licence']['organisation']['type']['id']); ?><br>
          <?php echo $this->translate($case['licence']['trafficArea']['name']); ?><br>
      </p>
    </div><!-- end .small-details -->
    <?php endif; ?>

    <div class="small-module">
      <h4 class="small-module__title">Licence details</h4>
        <p class="small-module__details">
          <a href="<?php echo $this->url('lva-licence', ['licence' => $case['licence']['id']], [], false); ?>"><?php echo $case['licence']['licNo']; ?></a><br>
          <?php echo $this->translate($case['licence']['licenceType']['id']); ?><br/>
          <?php echo $this->translate($case['licence']['status']['id']); ?>
        </p>
    </div><!-- end .small-details -->
  <?php endif; ?>

    <?php
    $transportManager = $this->placeholder('transportManager')->getValue();
    if ($transportManager) :
    ?>
    <div class="small-module">
        <h4 class="small-module__title">Transport manager details</h4>

        <p class="small-module__details">

        <?php if (isset($transportManager['contactDetails']['person'])): ?>
            <p><strong><a href="<?php echo $this->url('transport-manager/details', [], [], true); ?>">
                <?php echo $transportManager['contactDetails']['person']['forename']
                    . ' ' . $transportManager['contactDetails']['person']['familyName']; ?></a></strong>
            </p>
            <p><?php echo date('d/m/Y', strtotime($transportManager['contactDetails']['person']['birthDate'])); ?></p>

        <?php endif; ?>

        <?php if (isset($transportManager['contactDetails']['address'])): ?>
            <p><?php echo $this->addressFormat($transportManager['contactDetails']['address']); ?></p>
        <?php endif; ?>

        <?php $tmStatus = $transportManager['tmStatus']['description']; ?>
        <p><span class="status <?php echo strtolower($tmStatus) == 'active' ? 'green' : 'grey'; ?>">
            <?php echo $tmStatus; ?>
        </p>
    </div>
    <?php endif; ?>

  <?php if (isset($markers) && is_array($markers)): ?>
    <?php echo $this->markers($markers, 'appeal') ?>
    <?php echo $this->markers($markers, 'stay') ?>
  <?php endif; ?>

    <?php
    /**
     * Case quick actions
     *
     * @var \Zend\Navigation\Navigation
     */
    $nav = $this->navigation('right-sidebar')
        ->menu($this->navigation()->findOneBy('id', 'case-quick-actions'))
        ->setPartial('partials/record-actions__group');
    ?>
    <?php if (count($nav->getContainer()) > 0): ?>
    <div class="record-actions">
        <h5>Quick actions</h5>
        <?php echo $nav; ?>
    </div>
    <?php endif; ?>

    <?php
    /**
     * Case decisions
     *
     * @var \Zend\Navigation\Navigation
     */

    $caseDecisions = $transportManager ? 'case-decisions-transport-manager' : 'case-decisions-licence';
    $nav = $this->navigation('right-sidebar')
        ->menu($this->navigation()->findOneBy('id', $caseDecisions))
        ->setPartial('partials/record-actions__group');
    ?>
    <?php if (count($nav->getContainer()) > 0): ?>
        <div class="record-actions">
            <h5>Decisions</h5>
            <?php echo $nav; ?>
        </div>
    <?php endif; ?>

  <div class="latest-note">
  <p class="latest-note__details">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidid...</p>
  <a class="latest-note__link">View all 13 notes</a>
  </div><!-- end .small-details -->
</div><!-- one-fifth-right -->
