<div class="four-fifths--left">
  <?php
  echo $this->navigation('navigation')
  ->menu($this->navigation()->findOneBy('id', 'licence'))
  ->setPartial('partials/horizontal-navigation');
  ?>
  <div class="content js-body__main">
      <?php echo $this->content; ?>
  </div>
</div>

<div class="one-fifth--right">
  <div class="small-module">
  <h4 class="small-module__title">Operator details</h4>
    <p class="small-module__details">
      <a href="">Don Tarmacadam Ltd</a><br>
      Limited Company<br>
      North East England</p>
  </div><!-- end .small-details -->

  <div class="small-module">
    <h4 class="small-module__title">Licence details</h4>
    <p class="small-module__details">
      <a href="">OB1625270</a><br>
      Standard National<br>
      Valid</p>
  </div><!-- end .small-details -->

  <?php if (isset($markers) && is_array($markers)): ?>
    <?php foreach($markers as $marker): ?>
      <?php echo $this->markers($marker, 'appeal') ?>
      <?php echo $this->markers($marker, 'stay') ?>
    <?php endforeach; ?>
  <?php endif; ?>

  <?php
  /**
   * Case quick actions
   *
   * @var \Zend\Navigation\Navigation
   */
  $nav = $this->navigation('right-sidebar')
      ->menu($this->navigation()->findOneBy('id', 'licence-quick-actions'))
      ->setPartial('partials/record-actions__group');
  ?>
  <?php if (count($nav->getContainer()) > 0): ?>
    <div class="record-actions">
      <h5>Quick actions</h5>
      <?php echo $nav; ?>
    </div>
  <?php endif; ?>

  <?php
  /**
   * Case quick actions
   *
   * @var \Zend\Navigation\Navigation
   */
  $nav = $this->navigation('right-sidebar')
      ->menu($this->navigation()->findOneBy('id', 'licence-decisions'))
      ->setPartial('partials/record-actions__group');
  ?>
  <?php if (count($nav->getContainer()) > 0): ?>
    <div class="record-actions">
      <h5>Decisions</h5>
      <?php echo $nav; ?>
    </div>
  <?php endif; ?>

  <div class="latest-note">
    <p class="latest-note__details">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidid...</p>
    <a class="latest-note__link">View all 13 notes</a>
  </div><!-- end .small-details -->
</div><!-- one-fifth-right -->
