<?php
$allCaseMarkers = isset($markers) ? $markers : [];
?>
<div class="four-fiths--left">
    <?php
        echo $this->navigation('navigation')
                  ->menu($this->navigation()->findOneBy('id', 'licence'))
                  ->setUlClass('horizontal-navigation')
                  ->setAddClassToListItem(true)
                  ->setPartial('layout/partials/tabs');
    ?>
    <div class="content">
      <?php echo $this->content ?>
    </div>
</div>

<div class="one-fifth--right">
  <div class="record-actions">
    <h5>Quick actions</h5>
    <ul class="record-actions__group">
      <li class="record-actions__item"><a class="action--secondary" href="">Create case</a></li>
    </ul>
  </div>
    <?php
    if (is_array($allCaseMarkers)) {
        foreach($allCaseMarkers as $markers) {
            echo $this->markers($markers, 'appeal');
            echo $this->markers($markers, 'stay');
        }
    }
    ?>
</div>
