<div class="four-fifths--left">
    <?php
    if (!$this->disable) {
        echo $this->navigation('navigation')
            ->menu($this->navigation()->findOneBy('id', 'operator'))
            ->setUlClass('horizontal-navigation')
            ->setAddClassToListItem(true)
            ->setPartial('partials/horizontal-navigation');
    }
    ?>
    <div class="content">
        <?php echo $this->content ?>
    </div>
</div>

<div class="one-fifth--right">
  <div class="record-actions">
    <?php
    if (!isset($this->hideQuickActions) || $this->hideQuickActions === false) {
        ?>
        <h5><?php echo $this->translate('internal-operator-quick-actions'); ?></h5>
        <ul class="record-actions__group">
            <li class="record-actions__item">
                <a class="action--secondary<?php echo $this->disable ? ' disabled' : ''; ?> js-modal-ajax" href="<?php echo $this->url('operator/new-application', [], [], true); ?>">
                    <?php echo $this->translate('internal-operator-new-application'); ?>
                </a>
            </li>
        </ul>
        <?php
    }
    ?>
</div>
