<div class="four-fiths--left">
    <div class="content">
        <div class="one-fifth--left">
            <h4><?php echo $this->translate('internal-navigation-operator-profile'); ?></h4>
                <?php
                    $layout = 'layout/partials/vertical-navigation' . ($this->disable ? '-disabled' : '');
                    echo $this->navigation('navigation')
                              ->menu($this->navigation()->findOneBy('id', 'operator'))
                              ->setUlClass('vertical-navigation')
                              ->setAddClassToListItem(true)
                              ->setPartial($layout);
                ?>
        </div>
        <div class="three-fifths">
            <h4><?php echo $this->translate('internal-navigation-operator-' . $section); ?></h4>
          <?php echo $this->flashMessengerAll(); ?>
          <?php echo $this->content; ?>
        </div>
    </div>
</div>

<div class="one-fifth--right">
  <div class="record-actions">
    <h5><?php echo $this->translate('internal-operator-quick-actions'); ?></h5>
    <ul class="record-actions__group">
        <li class="record-actions__item">
            <a class="action--secondary<?php echo $this->disable ? ' disabled' : ''; ?> js-modal-ajax" href="<?php echo $this->url('operator/new-application', [], [], true); ?>">
                <?php echo $this->translate('internal-operator-new-application'); ?>
            </a>
        </li>
    </ul>
</div>
