<div class="four-fiths--left">
    <div class="content">
        <div class="one-fifth--left">
            <h4><?php echo $operatorName; ?></h4>
                <?php
                    echo $this->navigation('navigation')
                              ->menu($this->navigation()->findOneBy('id', 'operator'))
                              ->setUlClass('vertical-navigation')
                              ->setAddClassToListItem(true)
                              ->setPartial('layout/partials/tabs');
                ?>
            ?>
        </div>
        <div class="three-fifths">
          <?php echo $this->flashMessengerAll(); ?>
          <?php echo $this->content; ?>
        </div>
    </div>
</div>

<div class="one-fifth--right">
  <div class="record-actions">
    <h5><?php echo $this->translate('internal-operator-quick-actions'); ?></h5>
  </div>
</div>
