<?php if (!$this->disable && (!isset($documents) || !$documents)): ?>
<div class="one-fifth--left">
    <?php
    if (!isset($navigation)) {

        $navigation = $this->navigation('navigation');

        if ($navigation) {
            $navigation = $navigation->findOneBy('active', true);
        }

        if ($navigation) {
            $navigation = $navigation->getParent();
        }

    }

    if ($navigation):

    ?>
    <h4><?php echo $this->translate($navigation->getLabel()); ?></h4>
    <?php
        echo $this->navigation($navigation)
            ->menu()->setPartial('partials/vertical-navigation');

    endif;
    ?>
    <?php if (isset($documents) && $documents && isset($filterForm)): ?>
        <div class="filters">
            <?php echo $this->form($filterForm); ?>
        </div>
    <?php endif;?>
</div>
<?php endif; ?>
<div class="four-fifths  js-body__main">
    <?php echo $this->flashMessengerAll(); ?>
    <?php echo $this->content; ?>
</div>
