<?php
{
    $title = null;
    if (isset($this->pageTitle)) {
        $title = $this->pageTitle;
    } else {
        $title = $this->getPlaceholder('pageTitle')->asString();
    }

    $subTitle = null;
    if (isset($pageSubTitle)) {
        $subTitle = $pageSubTitle;
    } else {
        $subTitle = $this->getPlaceholder('pageSubtitle')->asString();
    }

    if (!isset($contentTitle)) {
        $contentTitle = $this->getPlaceholder('contentTitle')->asString();
    }

}

$this->doctype();
?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php
    {
        echo $this->headTitle(strip_tags($title));
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headLink()->appendStylesheet($this->assetPath('/styles/' . $this->applicationName() . '.css'));
    }
    ?>
  </head>
  <body class="internal">
    <?php echo $this->version(); ?>

    <div class="page-wrapper">
      <div id="main" role="main">

          <div class="content">
              <div class="js-body">
                <?php
                  echo $this->content;
                ?>
              </div><!-- End: js-body -->
          </div><!-- End: content -->
      </div><!-- End: main -->
    </div><!-- .page-wrapper-->

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];
    a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    <?php

    if (isset($userId)) {
      $gacode = "ga('create', 'UA-56585177-1', 'auto', {'userId': '%s'});";
      echo sprintf($gacode, $userId);
    } else {
      $gacode = "ga('create', 'UA-56585177-1', 'auto');";
      echo sprintf($gacode);
    }?>

    ga('send', 'pageview');
  </script>
  </body>
</html>
