<div class="one-fifth--left">
    <h4><?php echo $this->translate('internal-licence-processing'); ?></h4>
    <?php
        echo $this->navigation($navigation)->menu()->setPartial('view-new/partials/vertical-navigation');

        $tableFilters = $this->placeholder('tableFilters')->getValue();
        if($tableFilters instanceof \Zend\Form\Form) {
            echo $this->form($tableFilters);
        }
    ?>
</div>
<div class="three-fifths    js-content--main">
    <?php echo $this->flashMessengerAll(); ?>
    <?php echo $this->content; ?>
</div>
