<?php $this->doctype(); ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php
    {
        echo $this->headTitle(strip_tags($title));
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        /* echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')); */
        echo $this->headLink()->appendStylesheet($this->assetPath('/styles/' . $this->applicationName() . '.css'));
        echo $this->headScript();
    }
    ?>
    <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body class="internal sign-in" id="<?php echo $this->pageId(); ?>">
    <?php echo $this->version(); ?>
    <script>document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');</script>

    <div role="banner" class="global-header">
      <div class="global-header__wrapper">
          <h2 class="global-header__title">OLCS</h2>
      </div><!-- global-header__wrapper -->
    </div>
    <div class="page-wrapper">
      <div id="main" role="main">
        <?php echo $this->content; ?>
      </div><!-- End: main -->
    </div><!-- .page-wrapper-->

  <!-- Start: Global and Inline Script -->
  <?php echo $this->inlineScript()->prependFile($this->assetPath('js/' . $this->applicationName() . '.js')); ?>
  <!-- End: Global and Inline Script -->

  <script>
    OLCS.ready(function() {
      OLCS.eventEmitter.emit("render");
    });
  </script>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];
    a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    <?php

    $userId = $this->currentUser()->getUniqueId();

    if (!empty($userId)) {
      echo sprintf('ga(\'create\', \'UA-56585177-1\', \'auto\', {\'userId\': \'%s\'});', $userId);
    } else {
      ?>
      ga('create', 'UA-56585177-1', 'auto');
      <?php
    }
    ?>

    ga('send', 'pageview');
  </script>
  </body>
</html>
