<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('')); ?>
    <?php echo $this->headMeta() ->appendName('viewport', 'width=device-width, initial-scale=1.0') ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>
    <?php echo $this->headLink()->appendStylesheet($this->assetPath('/styles/' . $this->applicationName() . '.css')) ?>
    <?php echo $this->headScript(); ?>
  </head>
  <body class="internal" id="<?php echo $this->pageId(); ?>">
    <div class="iframe-controls">
      <a href="#" class="iframe-controls--close">Close</a>
      <a href="#" class="iframe-controls--orientation">Switch orientation</a>
      <a href="#" class="iframe-controls--toggle">Minimize</a>
    </div>
    <iframe name="iframe-one" id="iframe-one"></iframe>
    <iframe name="iframe-two" id="iframe-two"></iframe>
    <!-- Start: Global and Inline Script -->
    <?php echo $this->inlineScript()
        ->prependFile($this->assetPath('js/' . $this->applicationName() . '.js')) ?>
    <!-- End: Global and Inline Script -->
  </body>
</html>
