
<?php
echo $this->navigation('navigation')
    ->menu($this->navigation()->findOneBy('id', 'transport_manager'))
    ->setUlClass('horizontal-navigation')
    ->setAddClassToListItem(true)
    ->setPartial('partials/horizontal-navigation');
?>
<div class="content">
    <?php echo $this->content; ?>
</div>

<div class="one-fifth--right">
    <?php
    echo $this->showMarkers();
    ?>
    <?php
        $nav = $this->navigation('right-sidebar')
            ->menu($this->navigation()->findById('transport-manager-quick-actions'))
            ->setPartial('partials/record-actions__group');

        if ($nav->getContainer()->hasPages()) {
            ?>
            <div class="record-actions">
                <h5><?php echo $this->translate('internal-transport-manager-quick-actions'); ?></h5>
                <?php echo $nav; ?>
            </div>
            <?php
        }
    ?>
</div>
