<?php $tmMarkers = $this->placeholder('tmMarkers')->getValue(); ?>
<?php if (isset($section)): ?>
<div class="four-fifths--left">
    <?php if (!$this->disable): ?>
        <?php
        echo $this->navigation('navigation')
            ->menu($this->navigation()->findOneBy('id', 'transport_manager'))
            ->setUlClass('horizontal-navigation')
            ->setAddClassToListItem(true)
            ->setPartial('partials/horizontal-navigation');
        ?>
    <?php else: ?>
        <ul class="horizontal-navigation">
            <li class="horizontal-navigation__item current">
                <span><?php echo $this->translate('internal-transport-manager-tm-details'); ?></span>
            </li>
        </ul>
    <?php endif; ?>
    <?php
    $verticalNavigation = null;
    if (substr($section, 0, 7) == 'details') {
        $verticalNavigation = $this->navigation('navigation')
            ->menu($this->navigation()
                ->findOneBy('id', 'transport_manager_details'));
        $layout = 'partials/vertical-navigation' . ($this->disable ? '-disabled' : '');
    } elseif (substr($section, 0, 10) == 'processing') {
        $verticalNavigation = $this->navigation('navigation')
            ->menu($this->navigation()
                ->findOneBy('id', 'transport_manager_processing'));
        $layout = 'partials/vertical-navigation';
    }
    ?>
    <div class="content">
        <?php $contentClass = 'four-fifths'; ?>
        <?php if ($verticalNavigation): ?>
            <?php $contentClass = 'three-fifths'; ?>
            <div class="one-fifth--left">
                <h4><?php echo $this->translate('internal-navigation-transport-manager-' . $section); ?></h4>
                <?php echo $verticalNavigation->setUlClass('vertical-navigation')
                    ->setAddClassToListItem(true)
                    ->setPartial($layout);
                ?>
            </div>
        <?php endif; ?>
        <div class="<?php $contentClass; ?> js-body">
            <?php echo $this->flashMessengerAll(); ?>
            <?php echo $this->content; ?>
        </div>
    </div>
</div>

<div class="one-fifth--right">

    <?php
    if (isset($quickActionsId)) {
        $nav = $this->navigation('right-sidebar')
            ->menu($this->navigation()->findOneBy('id', $quickActionsId))
            ->setPartial('partials/record-actions__group');

        if ($nav->getContainer()->hasPages()) {
            ?>
            <div class="record-actions">
                <h5><?php echo $this->translate('internal-transport-manager-quick-actions'); ?></h5>
                <?php echo $nav; ?>
            </div>
            <?php
        }
    }
    ?>
    <?php if (isset($tmMarkers) && is_array($tmMarkers)): ?>
        <?php echo $this->markers($tmMarkers, 'transportManager') ?>
    <?php endif; ?>
</div>
<?php else: ?>
    <?php echo $this->content; ?>
<?php endif;
