<div class="four-fiths--left">
    <?php
        echo $this->navigation('navigation')
                  ->menu($this->navigation()->findOneBy('id', 'transport_manager'))
                  ->setUlClass('horizontal-navigation')
                  ->setAddClassToListItem(true)
                  ->setPartial('layout/partials/tabs');
    ?>
    <?php
        $verticalNavigation = null;
        if (substr($section, 0, 7) == 'details') {
            $verticalNavigation = $this->navigation('navigation')->menu($this->navigation()->findOneBy('id', 'transport_manager_details'));
        } elseif (substr($section, 0, 10) == 'processing') {
            $verticalNavigation = $this->navigation('navigation')->menu($this->navigation()->findOneBy('id', 'transport_manager_processing'));
        }
    ?>
    <div class="content">
        <?php $contentClass = 'four-fifths'; ?>
        <?php if ($verticalNavigation): ?>
            <?php $contentClass = 'three-fifths'; ?>
            <div class="one-fifth--left">
                <h4><?php echo $this->translate('internal-navigation-transport-manager-' . $section); ?></h4>
                <?php echo $verticalNavigation->setUlClass('verical-navigation')
                                              ->setAddClassToListItem(true)
                                              ->setPartial('layout/partials/vertical-navigation');
                ?>
            </div>
        <?php endif; ?>
        <div class="<?php $contentClass; ?>">
          <?php echo $this->flashMessengerAll(); ?>
          <?php echo $this->content; ?>
        </div>
    </div>
</div>

<div class="one-fifth--right">
  <div class="record-actions">
    <h5><?php echo $this->translate('internal-transport-manager-quick-actions'); ?></h5>
  </div>
</div>
