<?php if (isset($section)): ?>
    <div class="four-fifths--left">
        <?php if (!$this->disable): ?>
        <?php
            echo $this->navigation('navigation')
                      ->menu($this->navigation()->findOneBy('id', 'transport_manager'))
                      ->setUlClass('horizontal-navigation')
                      ->setAddClassToListItem(true)
                      ->setPartial('partials/horizontal-navigation');
        ?>
        <?php else: ?>
            <ul class="horizontal-navigation">
                <li class="horizontal-navigation__item current">
                    <span><?php echo $this->translate('internal-transport-manager-tm-details'); ?></span>
                </li>
            </ul>
        <?php endif; ?>
        <?php
            $verticalNavigation = null;
            if (substr($section, 0, 7) == 'details') {
                $verticalNavigation = $this->navigation('navigation')
                    ->menu($this->navigation()
                    ->findOneBy('id', 'transport_manager_details'));
                $layout = 'partials/vertical-navigation' . ($this->disable ? '-disabled' : '');
            } elseif (substr($section, 0, 10) == 'processing') {
                $verticalNavigation = $this->navigation('navigation')
                    ->menu($this->navigation()
                    ->findOneBy('id', 'transport_manager_processing'));
                $layout = 'partials/vertical-navigation';
            }
        ?>
        <div class="content">
            <?php $contentClass = 'four-fifths'; ?>
            <?php if ($verticalNavigation): ?>
                <?php $contentClass = 'three-fifths'; ?>
                <div class="one-fifth--left">
                    <h4><?php echo $this->translate('internal-navigation-transport-manager-' . $section); ?></h4>
                    <?php echo $verticalNavigation->setUlClass('vertical-navigation')
                                                  ->setAddClassToListItem(true)
                                                  ->setPartial($layout);
                    ?>
                </div>
            <?php endif; ?>
            <div class="<?php $contentClass; ?>">
              <?php echo $this->flashMessengerAll(); ?>
              <?php echo $this->content; ?>
            </div>
        </div>
    </div>

    <div class="one-fifth--right">
      <div class="record-actions">
        <h5><?php echo $this->translate('internal-transport-manager-quick-actions'); ?></h5>
        <?php
        $transportManager = $this->placeholder('transportManager')->getValue();
        ?>

        <?php if (isset($transportManager['contactDetails']['person'])): ?>
            <p><a href="<?php echo $this->url('transport-manager/details', [], [], true); ?>"">
                    <?php echo $transportManager['contactDetails']['person']['forename']
                . ' ' . $transportManager['contactDetails']['person']['familyName']; ?></a>
            </p>
            <p><?php echo date('d/m/Y', strtotime($transportManager['contactDetails']['person']['birthDate'])); ?></p>
        <?php endif; ?>

        <?php if (isset($transportManager['contactDetails']['address'])): ?>
            <p><?php echo $this->addressFormat($transportManager['contactDetails']['address']); ?></p>
        <?php endif; ?>
      </div>
    </div>
<?php else: ?>
    <?php echo $this->content; ?>
<?php endif; ?>
