<div class="four-fifths--left">
    <?php
    if (!$this->disable) {
        echo $this->navigation('navigation')
            ->menu($this->navigation()->findOneBy('id', 'unlicensed_operator'))
            ->setUlClass('horizontal-navigation')
            ->setAddClassToListItem(true)
            ->setPartial('partials/horizontal-navigation');
    }
    ?>
    <div class="content">
        <?php echo $this->content ?>
    </div>
</div>

<div class="one-fifth--right">
</div>
