<div class="full-width">
    <?php
        echo $this->render('case/page/partials/pi-empty.phtml', array('heading' => 'Agreed and Legislation', 'route' => 'case_pi', 'type' => 'agreed'));
        echo $this->render('case/page/partials/pi-empty.phtml', array('heading' => 'Schedule and publish', 'route' => 'case_pi', 'type' => 'schedule'));
        echo $this->render('case/page/partials/pi-empty.phtml', array('heading' => 'Register decision', 'route' => 'case_pi', 'type' => 'register'));
        echo $this->render('case/page/partials/pi-empty.phtml', array('heading' => 'Summary / SLA', 'route' => 'case_pi', 'type' => 'sla'));
    ?>
</div><!-- end .full-width -->