<?php
$pi = current($this->placeholder('pi')->getArrayCopy());

if (isset($pi['agreedDate'])):
    echo $this->render('case/page/partials/pi-agreed.phtml', array('pi' => $pi));

    //we have a Pi so a hearing can be added
    if (isset($pi['piHearings']) && !empty($pi['piHearings'])):
        echo $this->render('widget/table');

        //we have a hearing, so decision can be added
        if (isset($pi['decidedByTc']) && !empty($pi['decidedByTc'])):
            echo $this->render('case/page/partials/pi-decision.phtml', array('pi' => $pi));
        else:
            echo $this->render('case/page/partials/pi-empty.phtml',
                array('heading' => 'Decision', 'shortHeading' => 'decision', 'route' => 'case_pi_decision'));
        endif;
    else:
        echo $this->render('case/page/partials/pi-empty.phtml',
            array('heading' => 'Hearing',
                'shortHeading' => 'hearing',
                'route' => 'case_pi_hearing',
                'section' => 'hearing',
                'pi' => $pi
            )
        );
    endif;

    echo $this->render('case/page/partials/pi-sla.phtml', array('pi' => $pi));

else:
    echo $this->render('case/page/partials/pi-empty.phtml', array('heading' => 'Agreed and legislation', 'shortHeading' => 'Public Inquiry', 'route' => 'case_pi_agreed'));
endif;
