<div class="full-width">
    <div class="four-fifths">
        <?php
        //die(print_r((array)$this->vars()['complete'], 1));

        if (isset($pi['agreedDate'])):
            echo $this->render('case/page/partials/pi-agreed.phtml', array('pi' => $pi));
        else:
            echo $this->render('case/page/partials/pi-empty.phtml', array('heading' => 'Agreed and legislation', 'route' => 'case_pi', 'type' => 'agreed'));
        endif;

        if (isset($pi['piHearings']) && !empty($pi['piHearings'])):
            echo $this->render('case/page/partials/pi-hearings.phtml', array('pi' => $pi, 'table' => $piTable));
        else:
            echo $this->render('case/page/partials/pi-empty.phtml', array('heading' => 'Hearing', 'route' => 'case_pi', 'type' => 'schedule'));
        endif;

        if (isset($pi['decisionDate']) && !empty($pi['decisionDate'])):
            echo $this->render('case/page/partials/pi-decision.phtml', array('pi' => $pi));
        else:
            echo $this->render('case/page/partials/pi-empty.phtml', array('heading' => 'Decision', 'route' => 'case_pi', 'type' => 'decision'));
        endif;

        if (isset($pi['dateCallUpLetterIssued']) && !empty($pi['dateCallUpLetterIssued'])):
            echo $this->render('case/page/partials/pi-sla.phtml', array('pi' => $pi));
        else:
            echo $this->render('case/page/partials/pi-empty.phtml', array('heading' => 'Service level agreement', 'route' => 'case_pi', 'type' => 'sla'));
        endif;
        ?>
    </div><!-- end .full-width -->
</div>