<div class="full-width">
    <?php
    echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Stays & Appeals'));

    foreach ($stayTypes as $id => $type) {
        if (isset($stayRecords[$id])) {
            echo $this->render('partials/case/stay.phtml', array('stay' => $stayRecords[$id], 'stayType' => $type));
        } else {
            echo  $this->render('partials/case/stay-empty.phtml', array('heading' => $type, 'addHref' => $addHref[$id]));
        }
    }

    if(!empty($appealRecords)){
        print_r($appealRecords);
        echo  $this->render('partials/case/appeal.phtml', array('record' => $appealRecords[0]));
    } else {
        echo  $this->render('partials/case/stay-empty.phtml', array('heading' => 'Appeal', 'addHref' => $addHref['appeal']));
    }

    ?>
</div>