<div class="full-width">
<?php

if (!empty($appealRecord)) {
    echo  $this->render('partials/case/appeal.phtml', array('record' => $appealRecord));

    if ($appealRecord['withdrawnDate'] != null) {
        foreach ($stayTypes as $id => $type) {
            if (isset($stayRecords[$id])) {
                echo $this->render('partials/case/stay.phtml', array('stay' => $stayRecords[$id], 'stayType' => $type));
            } else {
                echo  $this->render('partials/case/stay-empty.phtml', array('heading' => $type . ' Stay', 'route' => 'case_stay_action', 'stayTypeId' => $id));
            }
        }
    }
} else {
    echo  $this->render('partials/case/stay-empty.phtml', array('heading' => 'Appeal', 'route' => 'case_appeal'));
}

?>
</div>