<?php
$cfg = $this->config();

$googleTag = (isset($cfg['google-tag']) ? $cfg['google-tag'] : null);
if (empty($googleTag)) {
    return;
}
?>

<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<?php echo $googleTag['id']; ?>&gtm_auth=<?php echo $googleTag['gtm_auth']; ?>&gtm_preview=<?php echo $googleTag['gtm_preview']; ?>&gtm_cookies_win=x"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl+ '&gtm_auth=<?php echo $googleTag['gtm_auth']; ?>&gtm_preview=<?php echo $googleTag['gtm_preview']; ?>&gtm_cookies_win=x';f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','<?php echo $googleTag['id']; ?>');</script>
<!-- End Google Tag Manager -->
