<div class="govuk-inset-text guidance-blue">
    <?php
        if (!is_array($this->guidance)) {
            echo $this->escapeHtml($this->translate($this->guidance));
        } else {
            if (isset($this->guidance['replacements'])) {
                echo $this->escapeHtml(
                    $this->translateReplace(
                        $this->guidance['key'], $this->guidance['replacements']
                    )
                );
            } else {
                foreach ($this->guidance as $key => $line) {
                    echo $this->escapeHtml($this->translate($line));

                    if ($key !== (count($this->guidance) - 1)) {
                        echo '<br /><br />';
                    }
                }
            }
        }
    ?>
</div>