<li class="overview-item <?php echo ($enabled ? '' : 'disabled'); ?>">

  <h3>
  <?php if ($enabled) : ?>
  <a
   class="overview-item__link"
   href="<?php echo $this->url($route, array($identifierIndex => $identifier)); ?>"
   <?php if (isset($anchorRef)): ?>
   id="overview-item__<?php echo $anchorRef; ?>"
   <?php endif; ?>
  >
  <?php else : ?>
  <div class="overview-item__link">
  <?php endif; ?>
  <?php
    if (isset($sectionNumber)){
        echo $sectionNumber . '. ';
    }
    echo $this->translate($name);
  ?>
  <?php if ($enabled) : ?></a><?php else : ?></div><?php endif; ?>
  </h3>


  <?php if ($enabled) : ?>
    <?php if (isset($status) && $status !== ''): ?>
      <span class="status <?php echo $statusColour; ?>"><?php echo $this->translate($status); ?></span>
    <?php endif; ?>
  <?php else : ?>
    <span class="status grey"><?php echo $this->translate('selfserve-app-overview-status-cant-start'); ?></span>
  <?php endif; ?>

</li>