<li class="overview-item <?php echo ($enabled ? '' : 'disabled'); ?>">
  <?php if ($enabled) : ?>
  <a class="overview-item__link" href="<?php echo $this->url($route, array($identifierIndex => $identifier)); ?>">
  <?php else : ?>
  <div class="overview-item__link">
  <?php endif; ?>
  <h4><?php echo $sectionNumber . '. ' . $this->translate($name); ?></h4>
  <?php if ($enabled) : ?>
    <?php if (isset($status)): ?>
      <span class="status <?php echo $statusColour; ?>"><?php echo $this->translate($status); ?></span>
    <?php endif; ?>
    <p><?php echo $this->translate($link); ?></p>
  <?php endif; ?>
  <?php if ($enabled) : ?></a><?php else : ?></div><?php endif; ?>
</li>