<div class="page-header">
    <?php
    if ($this->backUrl === true) {
        echo $this->linkBack();
        
    } elseif (is_array($this->backUrl) && count($this->backUrl) > 0) {
        echo $this->linkBack($this->backUrl);
    }
    ?>

    <div class="page-header__wrapper">
        <?php if ($this->pageSubTitle !== '') : ?>
            <h3 class="page-header__subtitle"><?php
                echo (
                    $this->pageSubTitleEscape === false
                    ? $this->pageSubTitle
                    : $this->escapeHtml($this->pageSubTitle)
                )
            ?></h3>
        <?php endif; ?>

        <h1 class="js-title"><?php
            echo (
                $this->pageTitleEscape === false
                ? $this->pageTitle
                : $this->escapeHtml($this->pageTitle)
            );
        ?></h1>

        <?php if ($this->pageHeaderText !== '') : ?>
            <div class="page-header__text">
                <p><?php
                    echo (
                        $this->pageHeaderTextEscape === false
                        ? $this->pageHeaderText
                        : $this->escapeHtml($this->pageHeaderText)
                    )
                ?></p>
            </div>
        <?php endif; ?>
    </div>
</div><!-- page-header-->
