<div class="article">
    <h3 class="important"><?php echo $this->translate('lva-summary-important'); ?></h3>
    <?php echo $this->translate($warningText); ?>
    <h3><?php echo $this->translate('lva-summary-application-before-processing'); ?></h3>
    <ul>
        <?php foreach ($actions as $action) : ?>
        <li><?php echo $this->translate($action); ?></li>
        <?php endforeach; ?>
    </ul>
    <h3><?php echo $this->translate('lva-summary-what-next-title'); ?></h3>
    <p><?php echo $this->translate('lva-summary-application-what-next-text'); ?></p>
    <a href="<?php echo $this->url('dashboard'); ?>" class="action--primary large">
        <?php echo $this->translate('lva-summary-back-to-dashboard'); ?>
    </a>
</div><!-- .article -->