<div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
        <?php echo $this->escapeHtml($this->translate($this->key)); ?>
    </dt>
    <dd class="govuk-summary-list__value">
        <?php if (isset($this->disableHtmlEscape) && $this->disableHtmlEscape) { ?>
            <?php echo $this->translate($this->value); ?>
        <?php } else { ?>
            <?php echo $this->escapeHtml($this->translate($this->value)); ?>
        <?php } ?>
    </dd>
</div>