<div class="govuk-tabs" data-module="govuk-tabs">
    <ul class="govuk-tabs__list">
        <?php
        if (isset($this->tabs) && is_array($this->tabs)) {
            foreach ($this->tabs as $tabConfig) {
                $active = isset($tabConfig['active']) ? 'govuk-tabs__list-item--selected' : '';
                $label = isset($tabConfig['label']) ? $tabConfig['label'] : '';
                $route = isset($tabConfig['route']) ? $tabConfig['route'] : null;
                $params = isset($tabConfig['params']) ? $tabConfig['params'] : [];
                $options = isset($tabConfig['query']) ? $tabConfig['query'] : [];
                $reuseMatchedParams = isset($tabConfig['reuseMatchedParams']) ? $tabConfig['reuseMatchedParams'] :
                    false;
                ?>
                <li class="govuk-tabs__list-item <?php echo $active;?>">
                    <?php echo $this->link(
                            $this->url($route, $params, $options, $reuseMatchedParams),
                            $label,
                            'govuk-tabs__tab'
                        );
                    ?>
                </li>
                <?php
            }
        }
        ?>
    </ul>
</div>
