<div class="tabs">
    <ul class="tab-list">
        <?php
        if (isset($this->tabs) && is_array($this->tabs)) {
            foreach ($this->tabs as $tabConfig) {
                $active = isset($tabConfig['active']) ? 'active' : '';
                $label = isset($tabConfig['label']) ? $tabConfig['label'] : '';
                $route = isset($tabConfig['route']) ? $tabConfig['route'] : null;
                $params = isset($tabConfig['params']) ? $tabConfig['params'] : [];
                $options = isset($tabConfig['query']) ? $tabConfig['query'] : [];
                $reuseMatchedParams = isset($tabConfig['reuseMatchedParams']) ? $tabConfig['reuseMatchedParams'] :
                    false;
                ?>
                <li class="tab-list__item <?php echo $active;?>">
                    <a href="<?php echo $this->url($route, $params, $options, $reuseMatchedParams);?>">
                        <?php echo $this->translate($label);?></a>
                </li>
                <?php
            }
        }
        ?>
    </ul>
</div>
