# installing the base image from ECR, tag is appended with v0.1 it may require discussion
# FROM $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/php-base:7.4.33-fpm-alpine3.16-v0.1

FROM dvsa-base:latest

USER root

# Installing require pacakges
RUN apk add --update --no-cache && \
  apk add --virtual build-dependencies icu-dev \
                                      autoconf \
                                      build-base && \
  docker-php-ext-configure intl && \
  docker-php-ext-install pdo_mysql \
                        opcache \
                        intl && \
  pecl install redis \
              igbinary && \
	docker-php-ext-enable redis \ 
                        igbinary

USER www-data

# opcache config file
COPY ./10-opcache.ini ${PHP_INI_DIR}/conf.d/10-opcache.ini

# nginx server config file
COPY ./backend.conf /etc/nginx/conf.d/backend.conf

# Configure php-fpm configs
COPY ./zzz-www.conf /usr/local/etc/php-fpm.d/zzz-www.conf

# copy entire app directory excluding the content in dockerignore
# COPY . /var/www

# Default startup command when container is launched
CMD ["supervisord", "-c", "/etc/supervisord.conf"]
