# installing the base image from ECR, tag is appended with v0.1 it may require discussion
FROM $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/php-base:7.4.33-fpm-alpine3.16-v0.1

# Installing require pacakges
RUN apk add --no-cache \
        pdo_mysql \
        redis \
        intl \
        igbinary \
        opcache \
        intl

# Do we need Soffice, LPR and PDFUnite extensions based on VOL-4796 

# opcache config file
COPY ./conf/opcache.ini /etc/php7/conf.d/opcache.ini

# nginx server config file
COPY ./conf/nginx/api-server.conf /etc/nginx/conf.d/api-server.conf

# copy entire app directory excluding the content in dockerignore
COPY . /var/www

# Default command executed during container startup
ENTRYPOINT ["supervisord"]

# Default startup command when container is launched
CMD ["-c", "/etc/supervisord.conf", "-n"]


