<h2 class="govuk-heading-m govuk-!-margin-top-7">Cwcis sy'n mesur defnydd gwefan</h2>

<h3 class="govuk-heading-s" id="messages-across-govuk">Google analytics</h3>

<p class="govuk-body">
  Rydym yn defnyddio meddalwedd Google Analytics (Universal Analytics) i gasglu gwybodaeth ddienw am sut rydych yn defnyddio'r safle hwn. Rydym yn gwneud hyn i helpu i sicrhau bod y safle yn diwallu anghenion ei ddefnyddwyr ac i'n helpu i wneud gwelliannau i'r safle ac i wasanaethau digidol y Llywodraeth.
</p>

<div class="govuk-inset-text">
  <p class="govuk-body">
    Nid ydym yn caniatáu i Google ddefnyddio neu rannu'r data am sut rydych yn defnyddio'r safle hwn.
  </p>
</div>

<p class="govuk-body">Mae Google Analytics yn storio gwybodaeth am:</p>

<ul class="govuk-list govuk-list--bullet govuk-hint">
  <li>sut y cawsoch chi'r safle</li>
  <li>y tudalennau rydych yn ymweld â nhw o fewn y gwasanaeth a faint o amser rydych yn ei dreulio arnynt</li>
  <li>Beth rydych chi'n clicio arno wrth ddefnyddio'r gwasanaeth</li>
</ul>

<p class="govuk-body">Mae Google Analytics yn gosod y cwcis canlynol.</p>

<table class="govuk-table">
  <thead class="govuk-table__head">
  <tr class="govuk-table__row">
    <th scope="col" class="govuk-table__header">Enw</th>
    <th scope="col" class="govuk-table__header">Diben</th>
    <th scope="col" class="govuk-table__header">Daw i ben</th>
  </tr>
  </thead>
  <tbody class="govuk-table__body">
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">_ga</td>
    <td class="govuk-table__cell">Defnyddio i gyfrif faint o bobl sy'n ymweld â'r gwasanaeth trwy olrhain os ydych wedi ymweld cyn</td>
    <td class="govuk-table__cell">2 flynedd</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">_gid</td>
    <td class="govuk-table__cell">Defnyddio i neilltuoli'n unigryw ymwelwyr â'r safle</td>
    <td class="govuk-table__cell">24 awr</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">_gat</td>
    <td class="govuk-table__cell">Defnyddio i gyfyngu'r ceisiadau i Google</td>
    <td class="govuk-table__cell">1 funud</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">__utmt</td>
    <td class="govuk-table__cell">Defnyddio i gyfyngu'r ceisiadau i Google</td>
    <td class="govuk-table__cell">10 munud</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">_gat_{ID}</td>
    <td class="govuk-table__cell">Defnyddio i gyfyngu'r ceisiadau i Google</td>
    <td class="govuk-table__cell">1 funud</td>
  </tr>
  </tbody>
</table>
