<h3 class="govuk-heading-m">Gwybodaeth am y datganiad</h3>
<p>Rydw I wedi dinistrio fy ndisgiau cerbyd a thrwydded gweithredwr yn ddiogel.</p>
<p>Byddaf yn dinistrio unrhyw ddisgiau coll neu drwyddedau a geir yn ddiweddarach.</p>
<p>Datganaf fod y datganiad a wnaed yn y cais hwn yn wir.</p>
<p>Rwy ' n gwneud cais i gael trwydded ildio %s.</p>
<p>Rwy ' n deall ei bod yn drosedd gwneud datganiad ffug.</p>