<div class="info-box info-box--large-padding info-box--grey">
	<h3>Camau nesaf</h3>
	<p class="info-box__text">Byddwn yn anfon ffurflen ar-lein at eich Rheolwr Trafnidiaeth yn y cyfeiriad rydych wedi'i ddarparu.</p>
	<p class="info-box__text">Byddwn yn rhoi gwybod ichi pan ydynt wedi cyflwyno eu manylion.</p>
	<p class="info-box__text important"><strong>Ni allwn ystyried eich cais tan fod cyfarwyddwr busnes neu berchennog wedi cymeradwyo holl fanylion eich Rheolwr Trafnidiaeth.</strong></p>
</div>