<p class = "govuk-body"> Dinistriwchl yn ddiogel: </p>
<ul class = "govuk-list govuk-list - bullet">
    <li> bob disg cerbyd yn eich meddiant </li>
    <li> eich dogfen drwydded (ac unrhyw gopïau)> </li>
    <li> eich trwydded gymunedol yr UE (ac unrhyw gopïau) </li>
</ul>
<p class = "govuk-body"> Sicrhewch eich bod yn dinistrio pob dogfen sy'n gysylltiedig â'ch trwydded gweithredwr. Bwriad hwn yw sicrhau nad yw'r wybodaeth yn cael ei chamddefnyddio. </p>
<p class = "govuk-body"> Gellir rhwygo neu losgi dogfennau. </ p>
