<p>Mae'n ddrwg gennym, rydym yn cael problemau technegol. Rhowch gynnig arall arni mewn ychydig funudau.</p>
<p>Os nad yw'r dudalen yn gweithio o hyd e-bost <?php echo $this->partial('en_GB/markup-contact-email-link'); ?>.</p>
<p>Gadewch i ni wybod:</p>
<ul>
    <li>Pa dudalen yr oeddech yn ymweld â hi</li>
    <li>Beth yr oeddech yn ceisio'i wneud</li>
    <?php if (!empty($correlationId)): ?>
        <li>gan ddyfynnu'r cyfeirnod <?php echo $this->escapeHtml($correlationId); ?></li>
    <?php endif; ?>
</ul>
