Darllen rhagor am
<span id="typeOfLicence-hint-goods">
    <a
        href="https://www.gov.uk/being-a-goods-vehicle-operator/types-of-licence"
        target="_blank"
        aria-label="Darllen rhagor am mathau o drwydded"
        rel="external noreferrer noopener"
    >
        mathau o drwydded <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?></a>
</span>
<span id="typeOfLicence-hint-psv">
    <a
        href="https://www.gov.uk/psv-operator-licences"
        target="_blank"
        aria-label="Darllen rhagor am mathau o drwydded"
        rel="external noreferrer noopener"
    >
        mathau o drwydded <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?></a>
</span>