<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary" aria-controls="details-content-trips">
        <span class="govuk-details__summary-text">
            Helpwch i gyfrifo'ch teithiau rhyngwladol
        </span>
    </summary>
    <div class="govuk-details__text" id="details-content-trips">
        <p class="govuk-body-l"><?php echo $this->escapeHtml($this->translate('permits.page.ecmt.trips.hint.heading')); ?></p>
        <h4 class="govuk-heading-s"><?php echo $this->escapeHtml($this->translate('permits.page.ecmt.trips.hint1')); ?></h4>
        <p class="govuk-body"><?php echo $this->escapeHtml($this->translate('permits.page.ecmt.trips.hint2')); ?></p>
        <hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">
        <h4 class="govuk-heading-s"><?php echo $this->escapeHtml($this->translate('permits.page.ecmt.trips.hint3')); ?></h4>
        <p class="govuk-body"><?php echo $this->escapeHtml($this->translate('permits.page.ecmt.trips.hint4')); ?></p>
        <hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">
        <h4 class="govuk-heading-s"><?php echo $this->escapeHtml($this->translate('permits.page.ecmt.trips.hint5')); ?></h4>
        <p class="govuk-body"><?php echo $this->escapeHtml($this->translate('permits.page.ecmt.trips.hint6')); ?></p>
    </div>
</details>
