<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary" aria-controls="details-content-licence-type">
        <span class="govuk-details__summary-text">
            Beth yw'r gwahaniaeth?
        </span>
    </summary>
    <div class="govuk-details__text" id="details-content-licence-type">
        <h3>Cerbydau nwyddau</h3>
        <p>Mae gan gerbydau nwyddau naill ai:</p>
        <ul class="govuk-list govuk-list--bullet">
            <li>pwysau plât gros o fwy na 3,5cg</li>
            <li>pwysau di-lwyth o fwy na 1,525cg (lle nad oes pwysau plât)</li>
        </ul>
        <p>Darllenwch ragor ynghylch
            <?php echo $this->linkNewWindowExternal('http://gov.uk/being-a-goods-vehicle-operator', 'bod yn weithredwr cerbyd nwyddau'); ?> a
            <?php echo $this->linkNewWindowExternal('https://www.gov.uk/vehicle-weights-explained', 'pwysau cerbyd nwyddau'); ?>.</p>
        <h3>Cerbydau gwasanaeth cyhoeddus</h3>
        <p>Mae cerbydau gwasanaeth cyhoeddus (PSVs) naill ai'n:</p>
        <ul class="govuk-list govuk-list--bullet">
            <li>gerbydau a ddefnyddir ar log neu er elw sy'n gallu cludo 9 teithiwr neu fwy</li>
            <li>cerbydau llai a ddefnyddir i gludo teithwyr a chodi tocynnau ar wahân arnynt</li>
        </ul>
        <p>Darllenwch ragor ynghylch <?php echo $this->linkNewWindowExternal('https://www.gov.uk/psv-operator-licences', 'trwyddedau gweithredwr PSV'); ?>.</p>
        <h3>Rheolau ac esemptiadau eraill</h3>
        <p>Mae rheolau gwahanol <?php echo $this->linkNewWindowExternal('http://www.nidirect.gov.uk/index/information-and-services/motoring/driving-for-a-living.htm', 'yng Ngogledd Iwerddon'); ?>.</p>
        <p>Nid oes angen trwydded gweithredwr ar rai mathau o gerbydau. Darllenwch fwy am
            <?php echo $this->linkNewWindowExternal('https://www.gov.uk/being-a-goods-vehicle-operator/exemptions', 'eithriadau'); ?>.
        </p>
    </div>
</details>
