<p class="govuk-hint">Mae'r cwcis hyn yn hanfodol er mwyn eich galluogi i ddechrau defnyddio'r gwasanaeth, symud o gwmpas y wefan a defnyddio ei nodweddion. Heb y cwcis hyn, ni ellir darparu'r gwasanaethau yr hoffech eu defnyddio.</p>
<p class="govuk-hint">Mae angen iddynt fod ymlaen bob amser.</p>
<p class="govuk-hint">
  <?php echo $this->link($this->url('cookies/settings'), 'Dysgwch fwy am gwcis ar y gwasanaeth Trwyddedu Gweithredwyr Cerbydau'); ?>.
</p>
