<div class="govuk-width-container">

<div class="govuk-panel govuk-panel--confirmation">
  <h1 class="govuk-panel__title centered">
      Cais i drwydded ildio %s
  </h1>

  <div class="govuk-panel__body">
      Llofnodwyd y datganiad drwy GOV.UK dilysu<br><strong>Llofnodwyd gan %s Ar %s</strong>
  </div>

</div>
</div>

<div class="govuk-width-container">
  <main class="govuk-main-wrapper">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <h3 class="govuk-heading-m">Beth sy'n digwydd nesaf</h3>
          <p class="govuk-body-l">
              Byddwn yn ysgrifennu atoch pan fydd penderfyniad wedi ' i wneud am eich cais i ildio ' ch trwydded. Hyd nes y byddwch wedi derbyn penderfyniad, rhaid i chi ddilyn telerau ac amodau eich trwydded gyfredol.
          </p>
           <p class="govuk-body">
               Os ydych wedi gwneud camgymeriad yn y wybodaeth a ddarparwyd gennych neu wedi ildio ' r drwydded anghywir rhaid i chi gysylltu â ' r Swyddfa drwyddedu ganolog ar
             </p>
            <a href="%s" type="submit" role="button" draggable="false" data-module="govuk-button" class="govuk-button">
                Dychwelyd i ' r cartref
            </a>
       </div>
    </div>
</main>
</div>
