<h2 class="govuk-heading-m govuk-!-margin-top-7">Cwcis sy'n cofio eich gosodiadau</h2>

<p class="govuk-body">
  Mae'r cwcis hyn yn gwneud pethau fel cofio eich hoffterau a'r dewisiadau rydych yn eu gwneud, i bersonoli eich profiad o ddefnyddio'r gwasanaeth.
</p>

<table class="govuk-table">
  <thead class="govuk-table__head">
  <tr class="govuk-table__row">
    <th scope="col" class="govuk-table__header">Enw</th>
    <th scope="col" class="govuk-table__header">Diben</th>
    <th scope="col" class="govuk-table__header">Daw i ben</th>
  </tr>
  </thead>
  <tbody class="govuk-table__body">
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">langPref</td>
    <td class="govuk-table__cell">Defnyddio i storio eich dewis iaith gyfredol (Cymraeg neu Saesneg)</td>
    <td class="govuk-table__cell">10 mlynedd</td>
  </tr>
  </tbody>
</table>
