<div class="article js-financial-history">
    <h3>Gwybodaeth ychwanegol</h3>
    <p>Rhowch ragor o wybodaeth ynghylch unrhyw ansolfedd blaenorol (o leiaf 150 nod).<br/>Hefyd gallwch lanlwytho tystiolaeth, megis dogfennau cyfreithiol, isod.</p>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary" aria-controls="details-content-insolvency">
            <span class="govuk-details__summary-text">
                Am beth mae angen ichi roi gwybod inni?
            </span>
        </summary>
        <div class="govuk-details__text" id="details-content-insolvency">
            <p>Rhowch wybod inni:</p>
            <ul class="govuk-list govuk-list--bullet">
                <li>sut ddigwyddodd yr ansolfedd</li>
                <li>pryd ddigwyddodd</li>
                <li>pwy oedd yn ymwneud ag ef</li>
                <li>pa lysoedd oedd yn ymwneud ag ef</li>
                <li>pa drwyddedau gweithredwr a effeithiwyd, os oedd rhai</li>
                <li>unrhyw wybodaeth arall rydych yn ystyried ei bod yn berthnasol</li>
            </ul>
            <p>Hefyd dylech lanlwytho eich:</p>
            <ul class="govuk-list govuk-list--bullet">
                <li>tystysgrif rhyddhau rhag methdaliad</li>
                <li>adroddiad y diddymwr</li>
                <li>adroddiad y derbynnydd</li>
                <li>adroddiad y gweinyddwr</li>
                <li>gorchmynion anghymwyso</li>
            </ul>
        </div>
    </details>
</div>