<p class="govuk-body">Mae'r ffenestr ymgeisio ar gyfer hawlenni ar gau.</p>
<p class="govuk-body">Bydd unrhyw ffenestri cais yn y dyfodol yn cael eu hysbysebu.</p>
<p class="govuk-body">I gadw'ch hun yn gyfredol rydym yn argymell eich bod yn ymweld â'r dudalen hawlenni ar <a class="govuk-link" rel="external noreferrer noopener" href="{{ECMT_PERMITS_GUIDANCE_LINK}}" target="_blank" rel="external noreferrer noopener">GOV.UK <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?></a>.</p>
