<h4>Amod 1</h4>
<p>Rhaid i’r teithwyr fod wedi dod ynghyd er dibenion mynd ar y daith gan y gyrrwr neu berchennog y cerbyd neu drwy
    unrhyw gyfryngwr arall y telir amdano. Yn ogystal rhaid i bob taith fod wedi ei hysbysebu i’r cyhoedd, er mwyn creu
    cyfle gwirioneddol i’r cyhoedd gael eu cludo ar y daith dan sylw h.y., nid yw’r daith yn hurio unigryw ar gyfer
    unigolyn neu grŵp, er bod ffioedd ar wahân wedi eu talu. Nid yw hysbysebu mewn addoldai, gweithle, clwb neu
    gymdeithas wirfoddol arall ar gyfer pobl sy’n bresennol yn y lleoedd hynny, neu mewn cyfnodolion a gylchwyd i’r holl
    neu rai o’r bobl hynny yn cael ei ystyried fel hysbysebu’r cyhoedd yn gyffredinol. Yn olaf, os ceir mwy nag un
    cyrchfan, dylid gosod gwahanol ffioedd ar gyfer y daith yn seiliedig ar bellter ac amser.
</p>
<h4>Amod 2</h4>
<p>
    Rhaid i’r gwaith o bennu’r cytundeb ar gyfer talu’r ffioedd ar wahân fod wedi ei wneud gan y gyrrwr neu berchennog y
    cerbyd neu drwy unrhyw gyfryngwr arall a delir am wneud hynny – nid gan y teithwyr eu hunain, neu unrhyw barti
    arall. Yn ogystal, yn unol ag amod 1, rhaid i bob taith fod wedi ei hysbysebu i’r cyhoedd ymlaen llaw fel un sydd ar
    gael i deithwyr a gludir am ffioedd ar wahân.
</p>