<p>Os nad ydych chi ' n defnyddio trwydded y gweithredwr hwn mwyach, os ydych chi wedi cau eich busnes neu wedi newid endid cyfreithiol, mae angen i chi ildio trwydded eich gweithredwr presennol.</p>
<h3>Cyn i chi ddechrau</h3>
%s
<p>Dylech gasglu ynghyd eich dogfennau trwydded a disgiau cerbydau.</p>
<p>Yn ystod y broses ymgeisio Bydd angen i chi ddinistrio unrhyw ddogfennau sy ' n ymwneud â ' r drwydded gweithredwr hon.</p>
