<div class="govuk-!-margin-top-7">
  <h2 class="govuk-heading-m">Cyfeiriadau IP</h2>

  <p class="govuk-body">
    Mae Trwyddedu Gweithredwyr Cerbydau yn casglu cyfeiriad IP i olrhain ac i gydgrynhoi gwybodaeth nad yw'n bersonol. Er enghraifft, mae'r gwasanaeth yn defnyddio cyfeiriadau IP i fonitro tueddiadau, rhanbarthau lle mae defnyddwyr yn llywio'r wefan a'r tudalennau yr ymwelwyd â nhw.
  </p>

  <div class="govuk-inset-text">
    <p class="govuk-body">
      Allwn ni ddim defnyddio eich cyfeiriad IP i'ch adnabod chi'n bersonol.
    </p>
  </div>
</div>
