<p class="govuk-body">
  Er mwyn cael trwydded gyfyngedig, mae angen i chi ddarparu tystiolaeth i fodloni’r Comisiynydd Traffig nad yw gweithredu trwydded gweithredwr PSV yn mynd i fod yn brif alwedigaeth yr ymgeisydd, o ran yr amser a dreulir a'r incwm a gynhyrchir.
</p>
<h3 class="govuk-heading-m">Y dystiolaeth y mae angen i chi ei darparu</h3>
<p class="govuk-body">
  Rhaid i’r holl dystiolaeth a ddarperir fod yn enw’r endid sy’n gwneud cais am y drwydded.
</p>
<p class="govuk-body">
  Gallwch ddod o hyd i ganllawiau ar y dudalen hon am y mathau penodol o dystiolaeth y mae’n rhaid i chi eu darparu ar gyfer eich math penodol o fusnes.
</p>

<div class="govuk-accordion" data-module="govuk-accordion" id="accordion-legal-entity">
  <div class="govuk-accordion__section">
    <div class="govuk-accordion__section-header">
      <h2 class="govuk-accordion__section-heading">
        <span class="govuk-accordion__section-button" id="accordion-legal-entity-heading-1">
          Os ydych wedi gwneud cais fel unig fasnachwr
        </span>
      </h2>
    </div>
    <div id="accordion-legal-entity-content-1" class="govuk-accordion__section-content">
      <h3 class="govuk-heading-s">Darparwch esboniad ysgrifenedig a dogfennau ategol sy'n ymdrin â'r canlynol:</h3>
      <h3 class="govuk-heading-s">Eich prif alwedigaeth</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>Pa waith rydych yn ei wneud heblaw am y gweithrediad PSV arfaethedig – cynnwys pob galwedigaeth heblaw'r gweithrediad PSV.</li>
        <li>A ydych yn hunangyflogedig neu'n gyflogai – os ydych yn gyflogai, rhaid darparu manylion eich cyflogwr.</li>
        <li>Os yw pobl eraill yn gweithio i chi – os felly, nodwch faint a pha waith y maent fel arfer yn ei wneud i chi.</li>
        <li>Rhaid darparu unrhyw dystiolaeth allanol o'ch busnes sy'n dangos nad gweithredu PSV yw eich prif alwedigaeth, megis gwefan, anfonebau, contractau ac ati.</li>
        <li>Y ffigurau ar gyfer yr incwm misol ac blynyddol nodweddiadol a gewch ar gyfer pob galwedigaeth nad yw'n ymwneud â'r PSV, a gynhyrchwyd dros y 12–18 mis diwethaf.</li>
        <li>Tystiolaeth o'r incwm o'ch cyflogaeth:
          <ul class="govuk-list govuk-list--number govuk-list--spaced">
            <li>Os ydych yn hunangyflogedig, dylech ddarparu eich Ffurflen Dreth Hunanasesiad ddiweddaraf neu gyfrifon archwiliedig.</li>
            <li>Os ydych yn gyflogai, darparwch eich ffurflen P60 ddiweddaraf a slipiau cyflog am y 3 mis diwethaf.</li>
          </ul>
        </li>
        <li>Dadansoddiad manwl o'r dyddiau a'r oriau rydych fel arfer yn ymgymryd ag unrhyw alwedigaeth nad yw'n gysylltiedig â'r gweithrediad PSV.</li>
        <li>Manylion y dyddiau a'r oriau na fyddwch yn gweithio ar unrhyw alwedigaeth, gan gynnwys y gweithrediad PSV arfaethedig.</li>
      </ul>

      <h3 class="govuk-heading-s">Eich cynlluniau ar gyfer y gweithrediad PSV</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>Pa fath o waith PSV fydd yn cael ei wneud (er enghraifft, contractau, archebion ad hoc, llwybrau bysiau ac ati).</li>
        <li>Sut y bydd unrhyw ffioedd y mae cwsmeriaid yn eu talu am ddefnyddio'r PSV yn cael eu talu (er enghraifft, taliadau sengl, archebion grŵp, wedi’u cynnwys mewn ffi am wasanaeth ehangach).</li>
        <li>Sut y bydd unrhyw ffioedd/ffarwel yn cael eu cyfrifo.</li>
        <li>Dadansoddiad manwl o'r dyddiau a'r oriau rydych yn bwriadu cynnal y gwaith sydd ei angen i redeg eich gweithrediad PSV yn ddiogel, yn effeithiol ac yn broffidiol.</li>
        <li>Copi o’ch cynllun busnes ar gyfer y gweithrediad PSV – dylai hyn gynnwys:
          <ul class="govuk-list govuk-list--number govuk-list--spaced">
            <li>Pwrpas y busnes.</li>
            <li>Incwm amcangyfrifedig o weithredu’r PSV am bob mis dros gyfnod o flwyddyn.</li>
            <li>Manylion pwy fydd yn gyrru ar gyfer y gweithrediad.</li>
            <li>Manylion costau rhedeg amcangyfrifedig blynyddol y PSV (gan gynnwys MOT, treth, yswiriant, glanhau, cynnal a chadw, atgyweiriadau, tanwydd, cyflogau ac unrhyw gostau eraill).</li>
          </ul>
        </li>
        <li>Enwau llawn y bobl a fydd yn gyrru'r PSVs os yw'n hysbys, a chopi o'r ddwy ochr o'u trwydded yrru fel tystiolaeth o’u hawl i yrru’r categori priodol.</li>
      </ul>

      <h3 class="govuk-heading-s">Oriau gyrwyr ac amser gweithio</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>Os yw eich prif alwedigaeth yn cynnwys gyrru, rhaid darparu manylion sawl awr yr ydych fel arfer yn eu gyrru mewn wythnos nodweddiadol ac wythnos brysur.</li>
        <li>Sut y byddwch yn sicrhau y byddwch chi/eich gyrwyr yn cydymffurfio ag oriau gyrwyr/rheolau amser gweithio os rhoddir trwydded i chi.</li>
        <li>Os ydych yn bwriadu bod yn yrrwr, a fydd yr oriau a dreulir ar eich prif alwedigaeth yn cael eu lleihau i gynnwys yr oriau a dreulir yn gyrru/gweithredu eich PSV – os felly, rhaid i chi ddweud wrthym:
          <ul class="govuk-list govuk-list--number govuk-list--spaced">
            <li>Beth fydd yr oriau newydd a’r dyddiau yr wythnos.</li>
            <li>Beth fydd yr incwm wythnosol/misol/blynyddol newydd.</li>
          </ul>
        </li>
      </ul>
    </div>
  </div>

  <div class="govuk-accordion__section">
    <div class="govuk-accordion__section-header">
      <h2 class="govuk-accordion__section-heading">
      <span class="govuk-accordion__section-button" id="accordion-legal-entity-heading-2">
        Os ydych wedi gwneud cais fel partneriaeth
      </span>
      </h2>
    </div>
    <div id="accordion-legal-entity-content-2" class="govuk-accordion__section-content">
      <h3 class="govuk-heading-s">Darparwch esboniad ysgrifenedig a dogfennau ategol sy'n ymdrin â'r canlynol:</h3>
      <h3 class="govuk-heading-s">Prif alwedigaeth y bartneriaeth</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>Pa waith y mae'r bartneriaeth yn ei wneud heblaw am y gweithrediad PSV arfaethedig.</li>
        <li>Os oes pobl eraill yn gweithio i'ch partneriaeth – os felly, nodwch faint a pha waith y maent fel arfer yn ei wneud i chi.</li>
        <li>Rhaid darparu unrhyw dystiolaeth allanol o’ch busnes sy’n dangos nad gweithredu PSVs yw eich prif alwedigaeth megis gwefan, anfonebau, contractau ac ati.</li>
        <li>Ffigurau ar gyfer yr incwm misol a blynyddol nodweddiadol a gynhyrchwyd o brif alwedigaeth y bartneriaeth dros y 12–18 mis diwethaf.</li>
        <li>Tystiolaeth o’r incwm a gynhyrchir gan brif alwedigaeth y bartneriaeth (cyfrifon blynyddol, ffurflenni treth).</li>
        <li>Dadansoddiad manwl o’r dyddiau a’r oriau y mae’r bartneriaeth yn ymgymryd ag unrhyw alwedigaeth nad yw’n gysylltiedig â’r gweithrediad PSV.</li>
      </ul>
      <h3 class="govuk-heading-s">Eich cynlluniau ar gyfer y gweithrediad PSV</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>Pa fath o waith PSV fydd yn cael ei wneud (megis gwaith contract, archebion ad hoc, llwybrau bysiau ac ati).</li>
        <li>Sut y bydd unrhyw ffioedd gan gwsmeriaid am ddefnyddio’r PSV yn cael eu talu (er enghraifft, tâl sengl, archebion grŵp, wedi’u cynnwys mewn ffi am wasanaeth ehangach).</li>
        <li>Sut y bydd unrhyw ffioedd/ffarwel yn cael eu cyfrifo.</li>
        <li>Pa ddiwrnod(au) y bydd pob cerbyd PSV yn cael ei ddefnyddio a sawl awr bob dydd – rhaid darparu’r ffigurau uchaf ar gyfer unrhyw wythnos benodol.</li>
        <li>Dadansoddiad manwl o’r dyddiau a’r oriau rydych yn bwriadu cynnal y gwaith angenrheidiol i redeg eich gweithrediad PSV yn ddiogel, yn effeithiol ac yn broffidiol.</li>
        <li>Copi o’ch cynllun busnes ar gyfer y gweithrediad PSV – dylai hwn gynnwys:
          <ul class="govuk-list govuk-list--number govuk-list--spaced">
            <li>Pwrpas y busnes.</li>
            <li>Incwm amcangyfrifedig o weithredu’r PSV ar gyfer pob mis dros gyfnod o flwyddyn.</li>
            <li>Manylion pwy fydd yn gyrru ar gyfer y gweithrediad.</li>
            <li>Manylion y costau rhedeg blynyddol amcangyfrifedig ar gyfer y PSV (gan gynnwys MOT, treth, yswiriant, glanhau, cynnal a chadw, atgyweiriadau, tanwydd, cyflogau ac unrhyw gostau eraill).</li>
          </ul>
        </li>
        <li>Enwau llawn y bobl fydd yn gyrru’r PSVs os ydynt yn hysbys, a chopïau o’r ddwy ochr o’u trwydded yrru fel tystiolaeth o’u hawl i yrru’r categori perthnasol.</li>
      </ul>
      <h3 class="govuk-heading-s">Oriau gyrwyr ac amser gweithio</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>Os yw prif alwedigaeth y bartneriaeth yn cynnwys gyrru, rhaid darparu manylion sawl awr y byddech fel arfer yn eu gyrru mewn wythnos nodweddiadol ac wythnos brysur.</li>
        <li>Sut y byddwch yn sicrhau y byddwch chi/eich gyrwyr yn cydymffurfio ag oriau gyrwyr/rheolau amser gweithio os rhoddir trwydded i chi.</li>
        <li>Os yw unrhyw un o’r partneriaid yn bwriadu gyrru, a fydd eu horiau ar eu prif alwedigaeth yn cael eu lleihau i gynnwys y gyrru/gweithredu PSV – os felly, rhaid i chi ddweud wrthym:
          <ul class="govuk-list govuk-list--number govuk-list--spaced">
            <li>Beth fydd yr oriau a’r dyddiau newydd yr wythnos.</li>
            <li>Beth fydd yr incwm wythnosol/misol/blynyddol newydd.</li>
          </ul>
        </li>
      </ul>
    </div>
  </div>

  <div class="govuk-accordion__section">
    <div class="govuk-accordion__section-header">
      <h2 class="govuk-accordion__section-heading">
      <span class="govuk-accordion__section-button" id="accordion-legal-entity-heading-3">
        Os ydych wedi gwneud cais fel cwmni cyfyngedig
      </span>
      </h2>
    </div>
    <div id="accordion-legal-entity-content-3" class="govuk-accordion__section-content">
      <h3 class="govuk-heading-s">Darparwch esboniad ysgrifenedig a dogfennau ategol sy'n ymdrin â'r canlynol:</h3>
      <h3 class="govuk-heading-s">Prif alwedigaeth y cwmni cyfyngedig</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>Pa waith y mae'r cwmni cyfyngedig yn ei wneud heblaw am y gweithrediad PSV arfaethedig.</li>
        <li>Faint o bobl sy’n gweithio i’ch cwmni a pha waith y maent fel arfer yn ei wneud i chi.</li>
        <li>Dadansoddiad manwl o’r dyddiau a’r oriau y cynhelir prif alwedigaeth eich cwmni.</li>
        <li>Rhaid darparu unrhyw dystiolaeth allanol o’ch busnes sy’n dangos nad gweithredu PSVs yw eich prif alwedigaeth megis gwefan, anfonebau, contractau ac ati.</li>
        <li>Ffigurau ar gyfer yr incwm misol a blynyddol nodweddiadol a gynhyrchwyd o brif alwedigaeth y cwmni cyfyngedig dros y 12–18 mis diwethaf.</li>
        <li>Tystiolaeth o’r incwm a gynhyrchir gan y cwmni cyfyngedig (cyfrifon blynyddol, ffurflenni treth).</li>
      </ul>
      <h3 class="govuk-heading-s">Eich cynlluniau ar gyfer y gweithrediad PSV</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>Pa fath o waith PSV fydd yn cael ei wneud (megis gwaith contract, archebion ad hoc, llwybrau bysiau ac ati).</li>
        <li>Sut y bydd unrhyw ffioedd gan gwsmeriaid am ddefnyddio’r PSV yn cael eu talu (er enghraifft, taliadau sengl, archebion grŵp, wedi’u cynnwys mewn ffi am wasanaeth ehangach).</li>
        <li>Sut y bydd unrhyw ffioedd/ffarwel yn cael eu cyfrifo.</li>
        <li>Pa ddiwrnod(au) y bydd pob cerbyd PSV yn cael ei ddefnyddio a sawl awr bob dydd – rhaid darparu’r ffigurau uchaf ar gyfer unrhyw wythnos benodol.</li>
        <li>Dadansoddiad manwl o’r dyddiau a’r oriau rydych yn bwriadu cynnal y gwaith angenrheidiol i redeg eich gweithrediad PSV yn ddiogel, yn effeithiol ac yn broffidiol.</li>
        <li>Copi o’ch cynllun busnes ar gyfer y gweithrediad PSV – dylai hwn gynnwys:
          <ul class="govuk-list govuk-list--number govuk-list--spaced">
            <li>Pwrpas y busnes.</li>
            <li>Incwm amcangyfrifedig o weithredu’r PSV ar gyfer pob mis dros gyfnod o flwyddyn.</li>
            <li>Manylion pwy fydd yn gyrru ar gyfer y gweithrediad.</li>
            <li>Manylion y costau rhedeg blynyddol amcangyfrifedig ar gyfer y PSV (gan gynnwys MOT, treth, yswiriant, glanhau, cynnal a chadw, atgyweiriadau, tanwydd, cyflogau ac unrhyw gostau eraill).</li>
          </ul>
        </li>
        <li>Enwau llawn y bobl fydd yn gyrru’r PSVs os ydynt yn hysbys, a chopïau o’r ddwy ochr o’u trwydded yrru fel tystiolaeth o’u hawl i yrru’r categori perthnasol.</li>
      </ul>
      <h3 class="govuk-heading-s">Oriau gyrwyr ac amser gweithio</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>Os yw prif alwedigaeth y cwmni cyfyngedig yn cynnwys gyrru, rhaid darparu manylion sawl awr y byddech fel arfer yn eu gyrru mewn wythnos nodweddiadol ac wythnos brysur.</li>
        <li>Sut y byddwch yn sicrhau y byddwch chi/eich gyrwyr yn cydymffurfio ag oriau gyrwyr/rheolau amser gweithio os rhoddir trwydded i chi.</li>
        <li>Os yw unrhyw un o gyfarwyddwyr y cwmni yn bwriadu gyrru, a fydd eu horiau ar alwedigaeth y cwmni yn cael eu lleihau i gynnwys y gyrru/gweithredu PSV – os felly, rhaid i chi ddweud wrthym:
          <ul class="govuk-list govuk-list--number govuk-list--spaced">
            <li>Beth fydd yr oriau a’r dyddiau newydd yr wythnos.</li>
            <li>Beth fydd yr incwm wythnosol/misol/blynyddol newydd.</li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>
