<h3 class="govuk-heading-s">Deddfau</h3>
<p class="govuk-body">Rheolir gweithredu cerbydau yn y DU gan Ddeddfau gan gynnwys:</p>
<ul class="govuk-list govuk-list--bullet">
    <li>Deddf Cerbydau Nwyddau (Trwyddedu Gweithredwyr) 1995</li>
    <li>Deddf Cerbydau  Cludo Teithwyr 1981 (diwygiedig)</li>
    <li>Deddf Cerbydau Nwyddau (Trwyddedu Gweithredwyr) (Gogledd Iwerddon) 2010 (diwygiedig)</li>
</ul>

<h3 class="govuk-heading-s">Caniatâd</h3>
<p class="govuk-body">
    Mae'r gwasanaeth hwn ar gyfer gweithredwyr a chynrychiolwyr sydd â chaniatâd i'w ddefnyddio  yn unig. Os na wyddoch
    os oes gennych chi ganiatâd anfonwch e-bost at
    <?php echo $this->partial('en_GB/markup-contact-email-link'); ?>.
</p>

<p class="govuk-body">Yr ymgeisiadwyr neu dalwyr y drwydded sydd yn gyfrifol am reoli mynediad i’r gwasanaeth. Gall unrhyw berson sy’n ceisio mewngofnodi heb ganiatȃd gael ei wahardd rhag mynediad i’r gwasaneth yn y dyfodol.</p>

<h3 class="govuk-heading-s">Cynrychiolwyr</h3>

<p class="govuk-body">Os ydych yn gwneud cais ar ran gweithredwr neu ymgeisydd, bydd rhaid i chi sicrhau bod hyn yn glir.</p>

<p class="govuk-body">Gallwch wneud hyn trwy:</p>

<ul class="govuk-list govuk-list--bullet">
  <li>Sicrhau mai’ch manylion chi yr ydych yn mewnbynnu ac nid manylion yr ymgeisydd</li>
  <li>Sicrhau bod ID y defnyddiwr yn adlewyrchu’ch busnes e.e. ABConsultants, Xsolicitiors</li>
  <li>Mae’n rhaid i’r cyfeiriad e-bost fod yn e-bost eich busnes</li>
</ul>

<p class="govuk-body">Os nad ydych yn cydymffurfio gyda’r gofynion uchod neu os ydych yn personadu’r ymgeisydd, gall eich cyfrif defnyddiwr gael ei derfynu.</p>

<p class="govuk-body">Mae’n rhaid i’r cyfeiriadau sydd ganddym ar gyfer yr ymgeisiadwyr neu ddalwyr y drwydded fod at y person/pobol yma eu hunain. Ni ddylid cyfeirio gohibiaeth at gyferiradau cynrhychiadol.</p>

<p class="govuk-body">Os y cynfyddir eich bod wedi ymddwyn yn anonest, mae’n bosibl y bydd eich hawliau yn cael eu dileu ar gyfer unrhyw ymgais neu ddeiliad trwydded ar hyn o bryd neu yn y dyfodol.</p>

<h3 class="govuk-heading-s">Gofalu am eich cyfrinair ac enw defnyddiwr</h3>
<p class="govuk-body">Er mwyn atal twyll ac i ddiogelu eich trwydded rhaid i chi ofalu am eich cyfrinair a'ch enw defnyddiwr.</p>
<p class="govuk-body">Medrwch wneud hyn trwy:</p>
<ul class="govuk-list govuk-list--bullet">
    <li>gymryd camau rhesymol i'w cadw'n gyfrinachol</li>
    <li>peidio â gadael i unrhyw un arall eu defnyddio</li>
    <li>peidio â'u nodi heb geisio eu cuddio</li>
    <li>eu defnyddio pan ofynnir i chi wneud a'r pryd hynny yn unig</li>
</ul>
<p class="govuk-body">
    Efallai byddwn yn gofyn am eich manylion mewngofnodi megis eich enw defnyddiwr, er mwyn eich adnabod, ond ni ddylai
    unrhyw un ofyn am eich cyfrinair. Peidiwch byth â'u ddatgelu yn llawn.
</p>

<h3 class="govuk-heading-s">Camddefnydd o'ch gwybodaeth</h3>
<p class="govuk-body">
    Os ydych yn meddwl bod gan rhywun arall eich gwybodaeth, neu ei fod yn cael ei gamddefnyddio, dylech newid eich
    cyfrinair ar unwaith ac anfon e-bost at
    <?php echo $this->partial('en_GB/markup-contact-email-link'); ?>.
</p>
<p class="govuk-body">
    Nid ydych yn atebol am gam-ddefnydd o'ch cyfrinair neu eich enw defnyddiwr cyn i chi eu derbyn, neu wedi i chi
    ddweud wrthym eu bod yn cael eu camddefnydio.
</p>

<h3 class="govuk-heading-s">Ni fyddwn yn goddef ymddygiad amhriodol na cham-drin</h3>

<p class="govuk-body">Ni ddylai neb dderbyn unrhyw gam-drin nac ymddygiad amhriodol fel rhan o'u cyflogaeth. Anogir staff i roi gwybod am bob achos o gam-drin a brofir - ar ba bynnag ffurf - heb betruso. Ni ddylai gweithredoedd ychydig leihau'r cyfraniad a'r gefnogaeth a ddarperir i ddefnyddwyr y gwasanaeth bob dydd.</p>

<p class="govuk-body">Gall defnyddwyr y gwasanaeth VOL ganfod bod eu mynediad wedi'i derfynu neu wedi'i atal yn llawn neu'n rhannol, os canfyddir bod y defnyddiwr, ei asiant neu ei weithiwr, wedi cam-drin unrhyw aelod o staff a/neu gomisiynydd traffig.</p>

<h3 class="govuk-heading-s">Terfynu neu atal eich cyfrinair a'ch enw defnyddiwr</h3>
<p class="govuk-body">Gallwn derfynu neu atal eich hawl i ddefnyddio cyfrinair neu enw defnyddiwr ar unrhyw adeg. Oni bai ein bod yn teimlo bod angen camau gweithredu mwy brys, byddwn yn rhoi o leiaf 7 diwrnod o rybudd i chi.</p>
<p class="govuk-body">Efallai y byddwn hefyd yn tynnu eich cyfrinair neu enw defnyddiwr yn ôl:</p>
<ul class="govuk-list govuk-list--bullet">
  <li>
    os bu gormod o ymdrechion i fewngofnodi gan ddefnyddio cyfrinair neu enw defnyddiwr anghywir  (e-bostiwch
    <?php echo $this->partial('en_GB/markup-contact-email-link'); ?> os digwydd hyn )
  </li>
  <li>os ydym yn credu ei fod yn angenrheidiol am resymau diogelwch</li>
  <li>i atal camddefnyddio eich trwydded</li>
  <li>os ydych chi'n defnyddio'r system, neu'r wybodaeth sy'n gysylltiedig â defnyddio'r system, mewn modd sy'n debygol o achosi gofid, cynhyrfu, neu ddifenwi comisiynwyr traffig neu staff Swyddfa'r Comisiynydd Traffig</li>
  <li>os ydych chi wedi dewis y math defnyddiwr anghywir, e.e. mae ymgynghorydd trafnidiaeth yn cofrestru fel Gweinyddwr Gweithredwr yn hytrach nag fel Gweinyddwr Ymgynghorol</li>
  <li>os yw telerau'r defnydd wedi cael eu torri</li>
</ul>

<h3 class="govuk-heading-s">Data nad oes gennych hawl i'w gyrchu</h3>
<p class="govuk-body">
    Os dowch chi ar draws data nad oes gennych hawl i'w gyrchu rhowch wybod i ni ar unwaith trwy e-bostio
    <?php echo $this->partial('en_GB/markup-contact-email-link'); ?>.
</p>
<p class="govuk-body">Mae defnyddio data rydych yn ei dderbyn ar ddamwain yn anghyfreithlon.</p>

<h3 class="govuk-heading-s">Trafodion</h3>
<p class="govuk-body">Efallai byddwn yn gwrthod gweithredu neu ddefnyddio trafodion os nad ydym yn sicr am y canlynol:</p>
<ul class="govuk-list govuk-list--bullet">
    <li>hunaniaeth neu awdurdod rhywun sydd yn ceisio eu defnyddio</li>
    <li>a yw'r trafodion yn gyfreithlon</li>
</ul>

<h3 class="govuk-heading-s">Diogelu rhag firysau</h3>
<p class="govuk-body">Gweler <?php echo $this->linkNewWindowExternal('https://www.gov.uk/help/terms-conditions', 'GOV.UK telerau ac amodau'); ?>.</p>

<h3 class="govuk-heading-s">Gwybodaeth statudol</h3>
<p class="govuk-body">
    Efallai byddwn yn cyhoeddi gwybodaeth statudol am eich cais am drwydded neu newidiadau i'r cais am drwydded ar ein
    gwefan.
</p>

<h3 class="govuk-heading-s">Data</h3>
<p class="govuk-body">
    Os ydych yn cymryd data o'r gwasanaeth, rhaid i chi ei gadw'n ddiogel a'i ddinistrio wedi i chi orffen ei
    ddefnyddio.
</p>
<p class="govuk-body">
    Mae mynediad heb awdurdod i ddata yn anghyfreithlon ac yn drosedd dan Ddeddf Camddefnyddio Cyfrifiadur 1990. Gall
    arwain at erlyniad a /neu hawlio iawndal.
</p>

<h3 class="govuk-heading-s">Defnyddio manylion eich cerdyn credyd neu ddebyd</h3>
<p class="govuk-body">Ni fedrwn gymryd cyfrifoldeb os caiff eich taliad ei wrthod gan y cyflenwr cardiau.</p>
<p class="govuk-body">Eich cyfrifoldeb chi yw sicrhau gwneud taliadau yn brydlon.</p>
<p class="govuk-body">Rydym yn dal yr hawl i gymryd camau cyfreithiol yn erbyn pobl sydd yn twyllo neu yn ceisio twyllo ar-lein.</p>

<h3 class="govuk-heading-s">Hyperlincio</h3>
<p class="govuk-body">Gweler <?php echo $this->linkNewWindowExternal('https://www.gov.uk/help/terms-conditions', 'GOV.UK telerau ac amodau'); ?>.</p>

<h3 class="govuk-heading-s">Diweddaru gwybodaeth</h3>
<p class="govuk-body">Dan Ddeddf Diogelu Data 2018 gallwch ofyn i ni:</p>
<ul class="govuk-list govuk-list--bullet">
    <li>anfon copi atoch o'r wybodaeth bersonol sydd gennym amdanoch</li>
    <li>gywiro unrhyw fanylion sydd yn anghywir</li>
</ul>
<p class="govuk-body">
    I wneud cais am gopi neu i wneud newidiadau, anfonwch e-bost at
    <?php echo $this->partial('en_GB/markup-contact-email-link'); ?>.
</p>

<h3 class="govuk-heading-s">Gwybodaeth gywir a gonest</h3>
<p class="govuk-body">
    Eich cyfrifoldeb chi yw sicrhau bod y manylion a gânt eu cyflwyno gennych chi, neu unrhyw un o weithwyr neu asiantau
    eich sefydliad, yn gywir ac yn onest.
</p>

<h3 class="govuk-heading-s">Tynnu partneriaid, cyfarwyddwyr neu Reolwyr Trafnidaeth yn ôl</h3>
<p class="govuk-body">
    Dylech dynnu yn ôl partner, cyfarwyddwr neu Reolwr Trafnidiaeth yn unig os nad ydynt bellach yn gysylltiedig â'r
    drwydded.
</p>

<h3 class="govuk-heading-s">Atebolrwydd</h3>
<p class="govuk-body">
    Nid ydych chi'n atebol am drafodion ar-lein ar eich trwyddedau nad ydych chi yn eu gweithredu, neu fynediad i neu
    ddefnydd o'r gwasanaeth gan rywun arall, oni bai:
</p>
<ul class="govuk-list govuk-list--bullet">
    <li>eich bod chi wedi awdurdodi'r trafodion, y mynediad i neu ddefnydd o'r gwasanaeth</li>
    <li>eich bod wedi twyllo neu weithredu yn esgeulus, sydd yn cynnwys peidio â diogelu eich cyfrinair</li>
</ul>
<p class="govuk-body">
    Byddwn yn disgwyl i chi gyd-weithredu â'r heddlu os bydd ymchwiliad. Byddwn ninnau yn rhoi unrhyw wybodaeth i'r
    heddlu sydd, yn ein barn ni, yn berthnasol.
</p>

<h3 class="govuk-heading-s">Rhyddid gwybodaeth</h3>
<p class="govuk-body">
    Rydym yn atebol i Ddeddf Rhyddid Gwybodaeth 2000 ac mae'n bosibl y bydd gofyn inni ddatgelu gwybodaeth am y
    gwasanaeth os daw cais am hyn.
</p>
<p class="govuk-body">
    Bydd yn rhaid i chi ein helpu i gydymffurfio â'r ceisiadau i ddatgelu gwybodaeth sydd yn gysylltiedig â gwasanaethau
    ar-lein neu eich trwydded os byddwn yn gofyn i chi wneud hynny.
</p>

<h3 class="govuk-heading-s">Hawlildio a gorfodaeth </h3>
<p class="govuk-body">Gweler <?php echo $this->linkNewWindowExternal('https://www.gov.uk/help/terms-conditions', 'GOV.UK telerau ac amodau'); ?>.</p>

<h3 class="govuk-heading-s">Deddf sy'n gymwys </h3>
<p class="govuk-body">Gweler <?php echo $this->linkNewWindowExternal('https://www.gov.uk/help/terms-conditions', 'GOV.UK telerau ac amodau'); ?>.</p>

<h3 class="govuk-heading-s">Newidiadau</h3>
<p class="govuk-body">
    Mae gennym yr hawl i newid y telerau hyn. Os byddwn yn gwneud newidiadau arwyddocaol i'r telerau byddwn yn rhoi
    gwybod i chi.
</p>
<p class="govuk-body">
    Mae telerau newydd yn dod i rym unwaith maent wedi eu postio ar y safle. Os byddwch chi'n defnyddio'r safle wedi
    iddynt gael eu postio, rydych yn cytuno iddynt.
</p>

<h3 class="govuk-heading-s">Aseiniad</h3>
<p class="govuk-body">
    Rhaid i chi beidio, heb dderbyn ein caniatâd ysgrifenedig ymlaen llaw, ag aseinio, newid, isgontractio neu gael
    gwared ar neu fel arall ymdrin ag unrhwy un o'ch hawliau neu oblygiadau o dan y telerau hyn, nac unrhyw ran ohonynt.
</p>

<h3 class="govuk-heading-s">Hawliau trydydd parti</h3>
<p class="govuk-body">Ni ellir gorfodi'r hawliau yn y telerau hyn gan unrhyw un ar wahân i chi a ni.</p>

<h3 class="govuk-heading-s">Cytundeb cyflawn</h3>
<p class="govuk-body">
    Mae'r telerau hyn yn cynnwys y dealltwriaeth lawn a chyflawn rhwng y partïon sydd yn berthnasol i destun y telerau
    hyn, ac heblaw lle'r cyfeirir fel arall yn benodol yn y telerau hyn, maent yn disodli pob cyflwyniad, ysgrifeniadau,
    trafodaethau neu ddealltwriaethau blaenorol mewn perthynas â thestun y telerau hyn, gyda phob parti yn cytuno nad yw
    wedi dibynnu ar unrhyw gynrychiolaeth wrth gytuno â'r telerau defnydd amodau hyn.
</p>
<p class="govuk-body">
    Fodd bynnag, nid oes unrhyw beth yn y cymal hwn fydd yn gweithredu i gyfyngu ar neu wahardd atebolrwydd mewn
    materion o dwyll.
</p>
