<div class="govuk-warning-text">
    <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
    <strong class="govuk-warning-text__text">
        <span class="govuk-warning-text__assistive">Rhybudd</span>
        Mae eich cais i ildio'ch trwydded wedi dod i ben.
    </strong>
</div>

<p class="govuk-body">Dydy'r wybodaeth roesoch chi ddim ar gael rhagor.</p>
<p class="govuk-body">Dechrau cais newydd.</p>
<p class="govuk-body">Rhaid i chi gael eich dogfennau trwydded a disgiau cerbydau wrth law.</p>
<p class="govuk-body">Yn ystod y broses ymgeisio Bydd angen i chi ddinistrio unrhyw ddogfennau sy'n ymwneud â'r drwydded gweithredwr hon.</p>