<ul class="govuk-list govuk-list--bullet">
    <li>deall bod yn rhaid i'ch cerbyd gario trionglau rhybuddio wrth deithio yn Ewrop</li>
    <li>deall bod yn rhaid i'ch gyrwyr gario'r Dystysgrif Ar y Ffordd a'r Dystysgrif Cydymffurfio ar gyfer y daith gyfan a'i chyflwyno i unrhyw awdurdod neu arolygwyr cymwys</li>
    <li>yn ymwybodol y bydd Tystysgrif diogelwch ar y ffyrdd yn dod i ben ar yr un diwrnod â thystysgrif MOT</li>
</ul>
