<div class="govuk-warning-text">
    <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
    <strong class="govuk-warning-text__text">
        <span class="govuk-warning-text__assistive">Rhybudd</span>
        Ers dechrau eich cais i ildio eich trwydded, rydych wedi gwneud newidiadau i ' ch gwybodaeth drwydded.
    </strong>
</div>

<p class="govuk-body">Mae angen i chi adolygu ' r wybodaeth a ddarparwyd gennych yn flaenorol.</p>
<p class="govuk-body">Rhaid i chi gael eich dogfennau trwydded a disgiau cerbydau wrth law.</p>
<p class="govuk-body">Yn ystod y broses ymgeisio Bydd angen i chi ddinistrio unrhyw ddogfennau sy ' n ymwneud â ' r drwydded gweithredwr hon.</p>