<h3>Gwybodaeth ychwanegol (dewisol)</h3><p>Gallwch lanlwytho rhagor o fanylion ynghylch trefniadau diogelwch a
    chynhaliaeth eich cerbyd isod. Nid oes angen ichi ddarparu'ch contract(au) cynhaliaeth. Gwelwch <a
            href="https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/321988/guide-to-maintaining-roadworthiness.pdf"
            target="_blank" rel="external">canllaw'r gweithredwr diogel</a> am ragor o wybodaeth.</p>
<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary" aria-controls="details-content-safety-additional-documents">
        <span class="govuk-details__summary-text">
            Enghreifftiau o wybodaeth ychwanegol
        </span>
    </summary>
    <div class="govuk-details__text" id="details-content-safety-additional-documents">
        <ul class="govuk-list govuk-list--bullet">
            <li>Adroddiadau cydymffurfiad</li>
            <li>Asesiadau risg</li>
            <li>Adroddiadau archwiliadau diogelwch</li>
            <li>Pa systemau sydd gennych yn eu lle ar gyfer adrodd am ddiffygion</li>
            <li>Pa gyfleusterau sydd gennych ar gyfer gwneud archwiliadau diogelwch (os yn gymwys)</li>
        </ul>
    </div>
</details>