<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary" aria-controls="details-content-operating-centre">
        <span class="govuk-details__summary-text">
            Help gydag awdurdodi cerbyd
        </span>
    </summary>
    <div class="govuk-details__text" id="details-content-operating-centre">
        <p>Ni all eich cyfanswm awdurdodi cerbydau fod:</p>
        <ul class="govuk-list govuk-list--bullet">
            <li>yn llai na'r nifer o gerbydau rydych eisiau eu cadw yn eich canolfan weithredu fwyaf</li>
            <li>yn fwy na'r cyfanswm o gerbydau rydych eisiau eu cadw ar draws eich holl ganolfannau gweithredu gyda'i
                gilydd
            </li>
        </ul>
    </div>
</details>