<h1 class="govuk-heading-xl govuk-!-margin-top-7 govuk-!-margin-bottom-7">Pa wasanaeth sydd ei angen arnoch?</h1>
<p class="govuk-body-l">Mae galw mawr am ein gwasanaethau ar hyn o bryd. Er mwyn sicrhau y gall pawb ei ddefnyddio, byddwn yn eich ailgyfeirio i'r adran gywir.</p>

<h2 class="govuk-heading-m">Trwyddedau</h2>
<p class="govuk-body">O 1 Ionawr 2021, bydd y rheolau ar gyfer cludo nwyddau ar y ffyrdd rhyngwladol yn newid.</p>
<p class="govuk-body">Bydd angen caniatâd ar weithredwyr rhyngwladol y DU i deithio i, trwy neu oddi wrth:</p>
<ul class="govuk-list govuk-list--bullet">
    <li>Gwledydd yr UE</li>
    <li>Gwlad yr Ia</li>
    <li>Liechtenstein</li>
    <li>Norwy</li>
    <li>Swistir</li>
</ul>

<p class="govuk-body">Mae hyn yn cynnwys swyddi traws-fasnach a theithiau tramwy.</p>
<p class="govuk-body">Gwiriwch y <?php echo $this->linkNewWindowExternal('https://www.gov.uk/guidance/carry-out-international-road-haulage-from-1-january-2021', 'rheolau newydd a pha ddogfennau sydd eu hangen ar weithredwyr y DU i gludo nwyddau ar y ffyrdd yn rhyngwladol'); ?></p>
<a href="<?php echo $this->url('permits'); ?>" role="button" class="govuk-button">Gwneud cais am drwydded neu weld trwyddedau sy'n bodoli eisoes</a>

<h2 class="govuk-heading-m govuk-!-margin-top-4">Trwyddedau</h2>
<a href="<?php echo $this->url('dashboard'); ?>" role="button" class="govuk-button">Rheoli neu wneud cais am drwydded</a>
