<div class="govuk-phase-banner">
  <p class="govuk-phase-banner__content">
    <span class="govuk-phase-banner__text">
      <a class="govuk-link" href="{{URL_SMART_SURVEY_IN_PAGE}}" aria-label="Helpwch ni i wella'r gwasanaeth hwn" rel="external noreferrer noopener" target="_blank">
        Beth oedd eich barn am y gwasanaeth hwn? <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?>
      </a> (yn cymryd 30 eiliad)
    </span>
  </p>
</div>

