<div class="govuk-!-margin-top-7">
  <h2 class="govuk-heading-m">Diogelu data</h2>

  <p class="govuk-body">
    Bydd y Comisiynydd Trafnidiaeth neu Adran Isadeiledd Gogledd Iwerddon yn defnyddio'ch gwybodaeth bersonol fel rhan o'u gwaith. Efallai y byddant yn ei rhannu â'i gilydd a:
  </p>

  <ul class="govuk-list govuk-list--bullet govuk-hint">
    <li>Chomisiynwyr Trafnidiaeth eraill</li>
    <li>yr Adran Drafnidiaeth</li>
    <li>adrannau eraill y Llywodraeth</li>
    <li>asiantaethau gorfodis</li>
  </ul>

  <p class="govuk-body">Efallai y byddwn hefyd yn ei ddefnyddio i gysylltu â chi ynghylch ymchwil defnyddwyr.</p>
  <p class="govuk-body">Os ydych yn gwneud cais am drwydded safonol mae'n ofynnol yn gyfreithiol i ni ychwanegu eich manylion at gofrestr genedlaethol.</p>

  <div class="govuk-inset-text">
    <p class="govuk-body">Byddwn yn rhannu data dienw gyda GOV.UK ar sut y gwnaethoch chi ddefnyddio'r safle.</p>
  </div>
</div>
