<p>
    (a) Bydd y gweithredwr yn cynghori’r comisiynydd traffig o wneuthuriad, model a rhif cofrestru’r cerbydau a
    ddefnyddir dan y drwydded honno, ac yn amlygu unrhyw newidiadau.
</p>
<p>
    (b) Mewn perthynas ag unrhyw gerbyd gydag wyth neu lai o seddau i deithwyr a ddefnyddir dan y drwydded, bydd y
    gweithredwr yn darparu cofnod awdit i’r comisiynydd traffig neu unrhyw gorff gorfodi ar gais, sy’n dangos
    cydymffurfiaeth â’r gofynion PSV. Mae hyn yn cynnwys gwaith papur ynghylch unrhyw ffioedd teithio ar wahân a dalwyd
    a bod un o’r ddau amod a amlinellwyd yng Nghwestiwn 1 wedi’u bodloni. Nodwch nad yw’r gweithrediad hwn yn berthnasol
    pan ddefnyddir y cerbyd dan ddarpariaethau Adran 79A.
</p>
<p>
    (c) Bydd gan bob cerbyd bach i’w ddefnyddio dan y drwydded dystysgrif cofrestru V5CW, a rhaid i’r gweithredwr feddu
    a dangos dogfen sy’n cadarnhau hynny pan ofynnir i’w gweld.
</p>
<p>
    (d) Bydd pob cerbyd bach yn cael archwiliad diogelwch llawn (bob 10 wythnos fel uchafswm) ar safle sy’n addas ar
    gyfer y cerbyd i sicrhau bod ei gyflwr derbyniol i fynd ar y ffordd fawr yn cael ei gynnal. Rhaid cadw cofnodion o’r
    holl archwiliadau yn unol â’r Canllaw i Gynnal Cerbyd i Fynd ar y Ffordd Fawr.
</p>
<p>(e) Ni chaiff y cerbyd ar unrhyw adeg gludo mwy nag wyth o deithwyr.</p>
<p>
    (f) Bydd y gweithredwr yn cydymffurfio bob amser â’r ddeddfwriaeth mewn perthynas â chodi ffioedd ar wahân a chadw
    tystiolaeth dros 12 mis o’r gydymffurfiaeth hon ar gyfer pob taith.
</p>
<p>
    (g) Bydd gyrwyr cerbydau bach yn cadw tystiolaeth ysgrifenedig gyda nhw bod ffioedd ar wahân wedi cael eu codi ar
    gyfer y daith gyfredol.
</p>
<p>
    (h) Ni fydd y gweithredwr yn defnyddio cerbyd nad yw’n bodloni safonau ECWVTA a gofynion adeiladwaith a defnydd
    Prydain neu Reoliadau Cymeradwyo Cerbydau’r Ffordd 2009 (fel y’u diwygiwyd).
</p>
<p>(i) Ni fydd y gweithredwr na’r gyrrwr yn tramgwyddo deddfwriaethau alcohol.</p>