<div class ="govuk-radios__conditional">
    <p><b>Deallaf y canlynol:</b></p>
    <p>
        <b>
            Drwy barhau Rwy ' n cadarnhau bod y datganiadau yn y cais hwn yn wir a bod y dystiolaeth ategol yn gywir ac yn deall ei bod yn drosedd gwneud datganiad ffug. Rwyf hefyd yn cytuno i drwyddedu gweithredwyr cerbydau gan ddefnyddio fy enw, cyfeiriad a dyddiad geni a ddarperir gan GOV.UK dilysu neu hunaniaeth ddigidol o wlad Ewropeaidd arall.
        </b>
    </p>
</div>
