<div class="newspaper-advert info-box info-box--grey info-box--large-padding">
    <h3>Hysbyseb papur newyddion</h3>
    <p class="info-box__icon-wrapper info-box__text">
        <i class="info-box__icon selfserve-important"></i>
        Bydd angen ichi hysbysebu'r cais mewn papur newyddion lleol ac anfon copi i ni.
    </p>
    <p class="info-box__icon-wrapper info-box__text"><a class="govuk-link" href="%s" target="_blank" rel="external noreferrer noopener">Gwelwch ein canllawiau ar sut i hysbysebu'ch cais <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?></a></p>
</div>
