<h2 class="govuk-heading-m govuk-!-margin-top-7">Cwcis cwbl angenrheidiol</h2>

<p class="govuk-body">
  Pan fyddwch yn defnyddio'r gwasanaeth 'gwneud cais am drwydded', byddwn yn gosod cwci i gofio eich cynnydd twy'r ffurflenni. Nid yw'r cwcis hyn yn storio eich data personol a chânt eu dileu ar ôl i chi gwblhau'r trafodyn.
</p>

<table class="govuk-table">
  <thead class="govuk-table__head">
  <tr class="govuk-table__row">
    <th scope="col" class="govuk-table__header">Enw</th>
    <th scope="col" class="govuk-table__header">Diben</th>
    <th scope="col" class="govuk-table__header">Daw i ben</th>
  </tr>
  </thead>
  <tbody class="govuk-table__body">
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">PHPSESSID</td>
    <td class="govuk-table__cell">Storio gwybodaeth dros dro rhwng tudalennau i gyflymu eich pori</td>
    <td class="govuk-table__cell">Pan fyddwch yn cau eich porwr</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">secureToken</td>
    <td class="govuk-table__cell">Storio gwybodaeth sylfaenol am eich manylion mewngofnodi</td>
    <td class="govuk-table__cell">Pan fyddwch yn cau eich porwr</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">cookies_policy</td>
    <td class="govuk-table__cell">Cadw eich gosodiadau caniatâd cwcis</td>
    <td class="govuk-table__cell">1 flwyddyn</td>
  </tr>
  </tbody>
</table>
