<h2 class="govuk-heading-m govuk-!-margin-top-7">Cwcis diogelwch</h2>

<p class="govuk-body">
  Cwcis parti cyntaf yw'r rhain a bennir gan wasanaeth trydydd parti a ddefnyddiwn i diogelu ein gwasanaeth. Maent yn helpu i nodi gweithgarwch maleisus a diogelu data. Byddant yn casglu gwybodaeth mewn ffurf ddienw heb storio unrhyw wybodaeth bersonol.
</p>

<table class="govuk-table govuk-table--small-text-until-tablet">
  <thead class="govuk-table__head">
  <tr class="govuk-table__row">
    <th scope="col" class="govuk-table__header">Enw</th>
    <th scope="col" class="govuk-table__header">Diben</th>
    <th scope="col" class="govuk-table__header">Daw i ben</th>
  </tr>
  </thead>
  <tbody class="govuk-table__body">
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">incap_ses_{ID}</td>
    <td class="govuk-table__cell">Ddefnyddir gan fur cadarn y cymhwysiad gwe i gysylltu ceisiadau HTTP ag ymweliad penodol a gwella diogelwch y wefan, gan ei diogelu rhag ymosodiad</td>
    <td class="govuk-table__cell">Pan fyddwch yn cau eich porwr</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">nlbi_{ID}</td>
    <td class="govuk-table__cell">Defnyddir gan y llwyfan cyflwyno, i sicrhau bod ceisiadau gan ddefnyddiwr yn cael eu hanfon at yr un gweinydd tarddiad</td>
    <td class="govuk-table__cell">Pan fyddwch yn cau eich porwr</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">visid_incap_{ID}</td>
    <td class="govuk-table__cell">Fe'i defnyddir i gysylltu sesiynau â dyfais ymwelydd penodol ac fe'i defnyddir gan fur cadarn y rhaglen we i wella diogelwch y wefan a'i diogelu rhag ymosodiad</td>
    <td class="govuk-table__cell">1 flwyddyn</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">_utmvm{ID}, _utmva, __utmvb{ID}</td>
    <td class="govuk-table__cell">Mae'r cwcis parti cyntaf hyn yn cael eu gosod gan wasanaeth trydydd parti i hidlo ceisiadau maleisus.</td>
    <td class="govuk-table__cell">15 munud</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">__utmvc</td>
    <td class="govuk-table__cell">Caiff y cwcis parti cyntaf hyn eu gosod gan wasanaeth trydydd parti i hidlo ceisiadau maleisus</td>
    <td class="govuk-table__cell">15 munud</td>
  </tr>
  </tbody>
</table>
