<?php

echo $this->render('partials/read-only/main',
    [
        'header' => 'Overview',
        'multiItems' => [
            0 => [
                [
                    'label' => 'Operator name',
                    'url' => $this->url('operator', ['operator' => $operatorId]),
                    'value' => $operatorName,
                ],
                ['label' => 'Trading name', 'value' => $tradingName],
            ],
            1 => [
                ['label' => 'Original Operator name', 'value' => '???'],
                ['label' => 'Original licence number', 'value' => '???'],
            ],
            2 => [
                ['label' => 'No of licences ', 'numeric' => $numberOfLicences],
                ['label' => 'Current applications ', 'numeric' => $currentApplications],
            ],
            3 => [
                ['label' => 'Licence number', 'value' => $licenceNumber],
                [
                    'label' => 'Licence Start Date',
                    'date' => (!empty($licenceStartDate) ? $licenceStartDate : '<empty>'),
                    'dateFormat' => 'Y-m-d',
                ],
                ['label' => 'Licence Type', 'value' => $licenceType],
                [
                    'label' => '',
                    'value' => null,
                    // Continution date <continutation date - date control>
                    // Label is 'Continuation' if GV or PSV-SR
                    // Label is 'Checklist date' if PSVR,SN,SI
                ],
            ],
            4 => [
                ['label' => 'Licence status', 'value' => $this->translate($licenceStatus)],
                [
                    'label' => 'Surrendered date',
                    'date' => $surrenderedDate,
                    'dateFormat' => 'Y-m-d',
                    'hideIfEmpty' => true,
                ],
            ],
            5 => [
                [
                    'label' => 'No of Vehicles',
                    'numeric' => $numberOfVehicles,
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'Total Vehicle Authorisation',
                    'numeric' => $totalVehicleAuthorisation,
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'No of Operating Centres',
                    'numeric' => $numberOfOperatingCentres,
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'Total Trailer Authorisation',
                    'numeric' => $totalTrailerAuthorisation,
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'No of Issued Discs',
                    'numeric' => $numberOfIssuedDiscs,
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'No of Community Lics',
                    'numeric' => $numberOfCommunityLicences,
                    'hideIfEmpty' => true,
                ],
            ],
            6 => [
                [
                    'label' => 'Open cases',
                    'value' => $openCases, // not numeric, may be suffixed with ' (PI)'
                ],
                [
                    'label' => 'Current Review Complaints',
                    'numeric' => $currentReviewComplaints,
                    'hideIfEmpty' => true,
                ],
            ],
            // out of scope for OLCS-5209
            // 7 => [
            //     ['label' => 'Receives Mail Electronically', 'value' => null],
            //     ['label' => 'Registered for self service', 'value' => null],
            // ],
        ],
    ]
);

echo $this->partial('partials/form', ['form' => $form]);
