<?php
echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->translate('user-forgot-username.page.ask-admin.title'),
    ]
);
?>

<div class="row">
    
  <div class="two-thirds">
    
    <div class="article">
      <p><?php echo $this->translate('user-forgot-username.page.ask-admin.text'); ?></p>
    </div>
  
    <div class="actions-container">
      <a href="<?php echo $this->url('index');?>"><?php echo $this->translate('back-to-home'); ?></a>
    </div>
    
  </div>

</div>