<?php
$this->placeholder('pageTitle')->set('404-title');
?>

<div class="article">
    <?php echo $this->translate('markup-404-text'); ?>
    <hr>
    <p><a href="<?php echo $this->url('dashboard'); ?>"><?php echo $this->translate('back-to-home'); ?></a></p>
</div>

<?php
$this->inlineScript()->appendScript('
    dataLayer.push({
        \'error\' : \'404\',
        \'correlationId\' : \''. $this->id .'\',
    });
');
