<?php
$this->placeholder('right')->set(null);
$this->placeholder('horizontalNavigationId')->set(null);
$this->placeholder('horizontalNavigationContainer')->set(null);
$this->placeholder('status')->set([]);

$this->placeholder('pageTitle')->set('500-title');
?>

<div class="article">
    <?php echo $this->translate('markup-500-text'); ?>
    <hr>
    <p><a href="<?php echo $this->url('dashboard'); ?>"><?php echo $this->translate('back-to-home'); ?></a></p>

    <?php echo $this->partial('partials/error/exception'); ?>
</div>
