<div id="main" role="main">
    <div class="two-thirds">
        <h1><?php echo $this->translate('500-title') ?></h1>
        <p><?php echo $this->translate('500-text') ?></p>
        <div class="actions-container">
            <a href="<?php echo $this->url('dashboard'); ?>" class="action--primary large">
                <?php echo $this->translate('back-to-home'); ?>
            </a>
        </div>
    </div>
</div>
<?php

if (!isset($stopRedirect)) {
    $this->inlineScript()->appendScript(
        '
        OLCS.ready(function() {
            window.location.href = "' . $this->url('server-error') . '";
        });
        '
    );
}
