<?php

echo $this->render('partials/read-only/main',
    [
        'multiItems' => [
            0 => [
                [
                    'label' => 'Operator name',
                    'url' => $this->url('operator/business-details', ['organisation' => $operatorId]),
                    'value' => $operatorName,
                ],
                ['label' => 'Trading name', 'value' => $tradingName],
            ],
            1 => [
                ['label' => 'Previous operator name', 'value' => $previousOperatorName, 'hideIfEmpty' => true],
                ['label' => 'Previous licence No.', 'value' => $previousLicenceNumber, 'hideIfEmpty' => true],
            ],
            2 => [
                ['label' => 'No of licences ', 'numeric' => $numberOfLicences],
                [
                    'label' => 'Current applications ',
                    'value' => $currentApplications,
                    'noEscape' => true
                ]
            ],
            3 => [
                ['label' => 'Licence number', 'value' => $licenceNumber],
                [
                    'label' => 'Licence Start Date',
                    'date' => (!empty($licenceStartDate) ? $licenceStartDate : '<empty>'),
                    'dateFormat' => 'Y-m-d',
                ],
                ['label' => 'Licence Type', 'value' => $this->translate($licenceType)],
                ['label' => 'Licence status', 'value' => $this->status($licenceStatus), 'noEscape' => true],
                ['label' => 'Grace Period', 'value' => $licenceGracePeriods, 'noEscape' => true],
                [
                    'label' => $isPsv ? 'Terminated date' : 'Surrendered date',
                    'date' => $surrenderedDate,
                    'hideIfEmpty' => true,
                ],
            ],
            5 => [
                [
                    'label' => 'No. of Vehicles',
                    'numeric' => $numberOfVehicles,
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'Total vehicle authorisation',
                    'numeric' => $totalVehicleAuthorisation,
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'No. of operating centres',
                    'numeric' => $numberOfOperatingCentres,
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'Total trailer authorisation',
                    'numeric' => $totalTrailerAuthorisation,
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'No. of issued discs',
                    'numeric' => $numberOfIssuedDiscs,
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'No. of community lics',
                    'numeric' => $numberOfCommunityLicences,
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'No. of bus registrations',
                    'numeric' => $numberOfBusRegistrations,
                    'hideIfEmpty' => false,
                ],
            ],
            6 => [
                [
                    'label' => 'Open cases',
                    'value' => $openCases, // not numeric, may be suffixed with ' (PI)'
                ],
                [
                    'label' => 'Current Review Complaints',
                    'numeric' => $currentReviewComplaints,
                    'hideIfEmpty' => true,
                ],
            ],
            7 => [
                [
                    'label' => 'Receives Mail Electronically',
                    'value' => $receivesMailElectronically,
                    'hideIfEmpty' => true
                ],
                [
                    'label' => 'Registered for self service',
                    'value' => $registeredForSelfService,
                    'hideIfEmpty' => true,
                ],
            ],
        ],
    ]
);

echo $this->partial('pages/form', ['form' => $form]);
