<div class="content">
<?php
var_dump($this->placeholder('details')->getValue()['id']);
echo $this->render(
    'sections/licence/partials/surrender/application-details',
    [

    ]
);
?>
<h2> Open Items</h2>
<?php
$casesTable = $this->placeholder('openCases')->getValue();
echo $casesTable;
$busRegTable = $this->placeholder('busRegistrations')->getValue();
echo $busRegTable;
?>
<section>
    <?php
    $form = $this->placeholder('form')->getValue();
    echo $this->form($form);
    ?>
</section>
</div>