<div class="content">
<?php
$details = $this->placeholder('details')->getValue();
$openItems = $this->placeholder('openItems')->getValue();
echo $this->render(
    'sections/licence/partials/surrender/application-details',
    ['surrender' => $details]
);
?>
<?php if ($openItems > 0): ?>
<h2> Open Items</h2>
<?php endif ?>
<?php
$casesTable = $this->placeholder('openCases')->getValue();
echo $casesTable;
$busRegTable = $this->placeholder('busRegistrations')->getValue();
echo $busRegTable;
?>
<section>
    <?php
    $form = $this->placeholder('form')->getValue();
    echo $this->form($form);
    ?>
</section>
</div>