<p class="notice--warning">
    <?php if (!$this->hideCaseLink): ?>
    <a href="<?php echo $this->url('case_hearing_appeal', ['case' => $this->caseId]) ?>">
        <?php echo $this->translate('Case') .' '. (int) $this->caseId ?>
    </a>
    <br>
    <?php endif; ?>
    <strong>
    <?php
    echo $this->translate('Stay') . ' ';
    echo ($this->stay['outcome']) ?
        $this->translate(strtolower($this->stay['outcome']['description']) .' pending appeal') :
        $this->translate('in progress');
    ?>
    </strong>
    <br>
    <?php
    echo ($this->stay['stayType']['id'] == 'stay_t_ut') ?  ' UT ' : ' TC/TR ';
    $date = $this->stay['requestDate'];
    if (!($date instanceof \DateTime)) {
        $date = new \DateTime($this->stay['requestDate']);
    }
    echo $date->format('d/m/Y');
    ?>
</p>
