<?php
$navigation = $this->navigation('navigation')->findOneBy('id', $navigationId);

// If $removePageIds is set on the controller, remove them from the navigation object before rendering.
if(isset($removePageIds)) {
    foreach($removePageIds as $pageId) {
        $navigation->removePage($navigation->findOneBy('route', $pageId), true);
    }
}

if (isset($navigation)): ?>
    <h4 class="title"><?php  echo $this->translate($navigationTitle); ?></h4>
<?php
endif;

/*
 * If we have a stock ID then we are in a drilled-down state for a Permit Stock and so we need to render a custom
 * vertical naviagtion partial.
 */
if (isset($stockId)) {
    foreach ($this->navigation($navigation)->getPages() as $page) {
        $page->setParams(['stockId' => $stockId]);
    }

    echo $this->navigation($navigation)
        ->menu()
        ->setPartial('partials/vertical-navigation');

    return;

}

// Don't render the list if the we only want the title.
if (!isset($singleNav)) {
    echo $this->navigation($navigation)
        ->menu()
        ->setPartial('partials/vertical-navigation');
}
