
<?php echo $this->translate('search-result-on-this-page'); ?>

<p>
  <a href=""><?php echo $this->translate('search-result-section-licence-details'); ?></a>
</p>
<p>
  <a href=""><?php echo $this->translate('search-result-section-operator-details'); ?></a>
</p>
<p>
  <a href=""><?php echo $this->translate('search-result-section-contact-details'); ?></a>
</p>
<p>
  <a href=""><?php echo $this->translate('search-result-section-directors'); ?></a>
</p>
<p>
  <a href=""><?php echo $this->translate('search-result-section-transport-managers'); ?></a>
</p>
<p>
  <a href=""><?php echo $this->translate('search-result-section-operating-centres'); ?></a>
</p>
<p>
  <a href=""><?php echo $this->translate('search-result-section-vehicles'); ?></a>
</p>
<p>
  <a href=""><?php echo $this->translate('search-result-section-applications'); ?></a>
</p>
<p>
  <a href=""><?php echo $this->translate('search-result-section-conditions-undertakings'); ?></a>
</p>
<p>
  <a href=""><?php echo $this->translate('search-result-section-other-licences'); ?></a>
</p>
