
<h3><?php echo $this->translate('search-result-on-this-page'); ?></h3>

<p>
  <a href="#licence-details"><?php echo $this->translate('search-result-nav-licence-details'); ?></a>
</p>
<p>
  <a href="#contact-details"><?php echo $this->translate('search-result-nav-contact-details'); ?></a>
</p>
<p>
  <a href="#operating-centres"><?php echo $this->translate('search-result-nav-operating-centres'); ?></a>
</p>
<p>
  <a href="#transport-managers"><?php echo $this->translate('search-result-nav-transport-managers'); ?></a>
</p>
<p>
  <a href="#licence-details"><?php echo $this->translate('search-result-nav-related-operator-licences'); ?></a>
</p>
