<?php
    echo $this->render('pages/table');
?>
<div class="guidance">
    <p>Changing or removing feature toggles can affect the running of the system. This config should only be changed by
        someone with sufficient understanding of the inner workings.</p>
    <p>Most config will involve switching on/off a group of handlers or controllers using a single config key.
        However we can also switch individual backend command/query handlers by specifying the final part of the FQDN:<br />
        <br /><strong>CommandHandler/Section/Handler</strong> (back end command handlers)
        <br /><strong>QueryHandler/Section/Handler</strong> (backend end query handlers)
    </p>
</div>