<div class="table__header">

    <h3>Agreed and legislation</h3>
    <div class="actions-container">
        <a href="<?php echo $this->url('case_pi_action', ['action' => 'edit', 'section' => 'agreed', 'id' => $pi['id']], [], true); ?>" class="action--secondary" />Edit</a>
    </div>

    <div style="clear: both"></div>

    <?php

    $summary = [
        'agreedDate' => [
            'label' => 'Agreed date',
            'value' => isset($pi['agreedDate']) ? date('m/d/Y', strtotime($pi['agreedDate'])) : 'dd/mm/yyyy',
        ]
    ];

    $types = [];
    foreach ($pi['piTypes'] as $value) {
        $types[] = $value['description'];
    }
    if (is_array($types)) {
        $summary += [
            'piType' => [
                'label' => 'Type of public inquiry',
                'value' => implode(', ', $types),
            ],
        ];
    }

    $summary += [
        'presidingTc' => [
            'label' => 'Agreed by',
            'value' => $pi['agreedByTc']['name'],
        ],
        'agreedByRole' => [
            'label' => 'Agreed by role',
            'value' => $pi['agreedByTcRole']['description'],
        ]/* ,
        'assignedTo' => [
            'label' => 'Assigned To',
            'value' => $pi['assignedTo']['name'],
        ] */,
        'legislation' => [
            'label' => 'Legislation',
            'value' => is_array($pi['reasons']) ? implode(', ', array_map(function($item){return $item['sectionCode'];}, $pi['reasons'])) : 'None selected',
        ],
        'comments' => [
            'label' => 'Comments',
            'value' => $pi['comment']
        ]
    ];

    echo $this->render('partials/summary/summary__list', ['items' => $summary, 'title' => 'Agreement and legislation']); ?>
</div>