<?php

$types = [];
foreach ($pi['piTypes'] as $value) {
    $types[] = $value['description'];
}

$piTypes = implode(', ', $types);

echo $this->render('partials/read-only/main',
    [
        'header' => 'Agreed and legislation',
        'actions' => [
            [
                'label' => 'Edit',
                'url' => $this->url(
                    'case_pi_agreed',
                    ['action' => 'edit'],
                    [],
                    true
                ),
                'class' => 'action--primary right-aligned'
            ],
        ],
        'items' => [
            ['label' => 'Agreed date', 'date' => (isset($pi['agreedDate']) ? $pi['agreedDate'] : null)],
            ['label' => 'Type of public inquiry', 'value' => $piTypes],
            ['label' => 'Agreed by', 'value' => $pi['agreedByTc']['name']],
            ['label' => 'Agreed by role', 'value' => $pi['agreedByTcRole']['description']],
            ['label' => 'Legislation', 'class' => 'full-width', 'value' => is_array($pi['reasons']) ?
                implode(
                    ', ',
                    array_map(
                        function($item){return $item['sectionCode']. ' ' . $item['description'];},
                        $pi['reasons']
                    )
                ) : 'None selected'],
            ['label' => 'Comments', 'value' => $pi['comment'], 'class' => 'full-width'],
        ]
    ]
);
