<div class="table__header">

    <h3>Decision</h3>
    <div class="actions-container">
        <a href="<?php echo $this->url('case_pi_decision', ['action' => 'edit'], [], true); ?>" class="action--secondary" />Edit</a>
    </div>

    <div style="clear: both"></div>

    <?php

    $summary = [
        'decisionPresidingTc' => [
            'label' => 'Presiding commissioner / regulator',
            'value' => $pi['decidedByTc']['name']
        ],
        'presidedByRole' => [
            'label' => 'Presiding commissioner / regulator role',
            'value' => $pi['decidedByTcRole']['description']
        ],
        'decisionType' => [
            'label' => 'Decision',
            'value' => $this->piListData($pi['decisions'])
        ],
        'whitnesses' => [
            'label' => 'Witnesses',
            'value' => $pi['witnesses'],
        ],
        'decisionDate' => [
            'label' => 'Date of decision',
            'value' => isset($pi['decisionDate']) ? date('d/m/Y', strtotime($pi['decisionDate'])) : 'dd/mm/yyyy',
        ],
        'notificationDate' => [
            'label' => 'Date of notification',
            'value' => isset($pi['notificationDate']) ? date('d/m/Y', strtotime($pi['notificationDate'])) : 'dd/mm/yyyy',
        ],
        'decisionNotes' => [
            'label' => "Details to be published",
            'value' => $pi['decisionNotes']
        ]

    ];

    echo $this->render('partials/summary/summary__list', ['items' => $summary, 'title' => 'Agreement and legislation']); ?>
</div>