<div class="table__header">

    <h3>Decision</h3>
    <div class="actions-container">
        <a href="<?php //echo $this->url($this->route, ['action' => 'edit', 'id' => $pi['id'], 'section' => 'decision'], [], true); ?>" class="action--secondary" />Edit</a>
    </div>

    <div style="clear: both"></div>

    <?php

    // Latest hearing.
    $hearing = end($pi['piHearings']);

    $summary = [
        'decisionPresidingTc' => [
            'label' => 'Presiding commissioner / regulator',
            'value' => $hearing['presidingTc']['name']
        ],
        'presidedByRole' => [
            'label' => 'Presiding commissioner / regulator role',
            'value' => $this->translate($hearing['presidedByRole']['id'])
        ],
        'decisionType' => [
            'label' => 'Decision',
            'value' => is_array($pi['decisions']) ? implode(', ', array_map(function($item){return $item['sectionCode'];}, $pi['decisions'])) : 'None selected',
        ],
        'whitnesses' => [
            'label' => 'Witnesses',
            'value' => $pi['witnesses'],
        ],
        'decisionDate' => [
            'label' => 'Date of decision',
            'value' => isset($pi['decisionDate']) ? date('m/d/Y', strtotime($pi['decisionDate'])) : 'dd-mm-yyyy',
        ]/* ,
        'legislation' => [
            'label' => 'Decision Definition',
            'value' => is_array($pi['decisionReasons']) ? implode(', ', array_map(function($item){return $item['sectionCode'];}, $pi['decisionReasons'])) : 'None selected',
        ], */
    ];

    echo $this->render('partials/summary/summary__list', ['items' => $summary, 'title' => 'Agreement and legislation']); ?>
</div>