<?php

echo $this->render('partials/read-only/main',
    [
        'header' => 'Decision',
        'actions' => [
            [
                'label' => 'Edit',
                'url' => $this->url(
                    'case_pi_decision',
                    ['action' => 'edit'],
                    [],
                    true
                ),
                'class' => 'action--secondary js-modal-ajax'
            ],
        ],
        'items' => [
            ['label' => 'Presiding commissioner / regulator', 'value' => $pi['decidedByTc']['name']],
            ['label' => 'Presiding commissioner / regulator role', 'value' => $pi['decidedByTcRole']['description']],
            ['label' => 'Decision', 'value' => $this->piListData($pi['decisions'])],
            [
                'label' => 'Date of decision',
                'date' => $pi['decisionDate']
            ],
            [
                'label' => 'Date of notification',
                'date' => $pi['notificationDate']
            ],
            ['label' => 'Details to be published', 'value' => $pi['decisionNotes'], 'class' => 'full-width'],
        ]
    ]
);
