<div class="read-only">
    <h4><?php echo $this->translate($this->heading); ?>
    <a href="<?php echo $this->url(
        $this->route,
        array(
            'action' => 'add',
            'section' => $this->section,
            'id' => $this->id,
            'pi' => $this->pi['id']),
            array(),
            true
        ); ?>" class="action--primary right-aligned" />Add</a>
    </h4>
</div>
