<div class="table__header">

    <h3>Service level agreement</h3>
    <div class="actions-container">
        <a href="<?php echo $this->url('case_pi_sla', ['action' => 'edit'], [], true); ?>" class="action--secondary" />Edit</a>
    </div>

    <div style="clear: both"></div>

    <?php

    $summary = [
        'dateCallUpLetterIssued' => [
            'label' => 'Date call up letter issued',
            'value' => isset($pi['callUpLetterDate']) ? date('d/m/Y', strtotime($pi['callUpLetterDate'])) : 'dd/mm/yyyy',
        ],
        'dateBriefToTc' => [
            'label' => 'Date brief to TC',
            'value' => isset($pi['briefToTcDate']) ? date('d/m/Y', strtotime($pi['briefToTcDate'])) : 'dd/mm/yyyy',
        ],
        'writtenOutcome' => [
            'label' => 'Written outcome',
            'value' => isset($pi['writtenOutcome']['description']) ? $pi['writtenOutcome']['description'] : ''
        ]
    ];

    if (isset($pi['writtenOutcome']['id'])) {
        switch ($pi['writtenOutcome']['id']) {
            case 'piwo_reason':
                $summary['writtenReasonDate'] = [
                    "label" => "Date of written reason",
                    'value' =>isset($pi['writtenReasonDate']) ? date('d/m/Y', strtotime($pi['writtenReasonDate'])) : 'dd/mm/yyyy'
                ];
                $summary['tcWrittenReasonDate'] = [
                    "label" => "Date of TC's written reason",
                    'value' =>isset($pi['tcWrittenReasonDate']) ? date('d/m/Y', strtotime($pi['tcWrittenReasonDate'])) : 'dd/mm/yyyy'
                ];
                $summary['writtenReasonLetterDate'] = [
                    "label" => "Written reason letter sent",
                    'value' =>isset($pi['writtenReasonLetterDate']) ? date('d/m/Y', strtotime($pi['writtenReasonLetterDate'])) : 'dd/mm/yyyy'
                ];
                break;
            case 'piwo_decision':
                $summary['decisionLetterSentDate'] = [
                    "label" => "Decision letter sent",
                    'value' =>isset($pi['decisionLetterSentDate']) ? date('d/m/Y', strtotime($pi['decisionLetterSentDate'])) : 'dd/mm/yyyy'
                ];
                $summary['tcWrittenDecisionDate'] = [
                    "label" => "Date of TC's written decision",
                    'value' =>isset($pi['tcWrittenDecisionDate']) ? date('d/m/Y', strtotime($pi['tcWrittenDecisionDate'])) : 'dd/mm/yyyy'
                ];
                break;
        }
    }

    $summary['decisionLetterSentAfterWrittenDecisionDate'] = [
        "label" => "Decision letter sent after written decision date",
        'value' =>isset($pi['decisionLetterSentAfterWrittenDecisionDate']) ? date('d/m/Y', strtotime($pi['decisionLetterSentAfterWrittenDecisionDate'])) : 'dd/mm/yyyy'
    ];

    echo $this->render('partials/summary/summary__list', ['items' => $summary, 'title' => 'Agreement and legislation']); ?>
</div>