<?php

$items = [
    ['label' => 'Date call up letter issued', 'date' => $pi['callUpLetterDate']],
    ['label' => 'Date brief to TC', 'date' => $pi['briefToTcDate']],
    [
        'label' => 'Written outcome',
        'value' => isset($pi['writtenOutcome']['description']) ? $pi['writtenOutcome']['description'] : ''
    ]
];

if (isset($pi['writtenOutcome']['id'])) {
    switch ($pi['writtenOutcome']['id']) {
        case 'piwo_reason':
            $items[] = [
                'label' => 'Date of written reason',
                'date' => $pi['writtenReasonDate']
            ];
            $items[] = [
                'label' => 'Date of TC\'s written reason',
                'date' => $pi['tcWrittenReasonDate']
            ];
            $items[] = [
                'label' => 'Written reason letter sent',
                'date' => $pi['writtenReasonLetterDate']
            ];
            break;
        case 'piwo_decision':
            $items[] = [
                'label' => 'Decision letter sent',
                'date' => $pi['decisionLetterSentDate']
            ];
            $items[] = [
                'label' => 'Date of TC\'s written decision',
                'date' => $pi['tcWrittenDecisionDate']
            ];
            break;
    }
}

$items[] = [
    'label' => 'Decision letter sent after written decision date',
    'date' => $pi['decSentAfterWrittenDecDate']
];

echo $this->render('partials/read-only/main',
    [
        'header' => 'Service level agreement',
        'actions' => [
            [
                'label' => 'Edit',
                'url' => $this->url(
                    'case_pi_sla',
                    ['action' => 'edit'],
                    [],
                    true
                ),
                'class' => 'action--primary right-aligned'
            ],
        ],
        'items' => $items
    ]
);
