<div class="table__header">

    <h3>Service level agreement</h3>
    <div class="actions-container">
        <a href="<?php echo $this->url($this->route, ['action' => 'edit', 'id' => $pi['id']], [], true); ?>" class="action--secondary" />Edit</a>
    </div>

    <div style="clear: both"></div>

    <?php

    $summary = [
        'dateCallUpLetterIssued' => [
            'label' => 'Date call up letter issued',
            'value' => date('m/d/Y', strtotime($pi['dateCallUpLetterIssued'])),
        ],
        'dateBriefToTc' => [
            'label' => 'Date brief to TC',
            'value' => isset($pi['dateBriefToTc']) ? date('m/d/Y', strtotime($pi['dateBriefToTc'])) : 'dd-mm-yyyy',
        ],
        'writtenDecision' => [
            'label' => 'Written decision',
            'value' => $pi['writtenDecision']
        ],
        'dateDecisionLetterSent' => [
            'label' => 'Date decision letter sent',
            'value' => isset($pi['dateDecisionLetterSent']) ? date('m/d/Y', strtotime($pi['dateDecisionLetterSent'])) : 'dd-mm-yyyy',
        ],
        'dateOfTcWrittenDecision' => [
            'label' => 'Date of TC\'s written decision',
            'value' => isset($pi['dateOfTcWrittenDecision']) ? date('m/d/Y', strtotime($pi['dateOfTcWrittenDecision'])) : 'dd-mm-yyyy',
        ],
        'dateOfLetterAfterTcWrittenDecision' => [
            'label' => 'Date letter sent after written decision date',
            'value' => isset($pi['dateOfLetterAfterTcWrittenDecision']) ? date('m/d/Y', strtotime($pi['dateOfLetterAfterTcWrittenDecision'])) : 'dd-mm-yyyy',
        ],
    ];

    echo $this->render('partials/summary/summary__list', ['items' => $summary, 'title' => 'Agreement and legislation']); ?>
</div>