<div class="table__header">
    <h3>Revoke</h3>
    <div class="actions-container">
        <a href="<?php echo $this->url('case_revoke', array('action' => 'edit', 'appeal' => $this->revoke['id']), array(), true); ?>" class="action--primary" />Edit</a>
        <a href="<?php echo ''; ?>" class="action--warning" />Delete</a>
    </div>
    <p>
        <strong><?php echo $this->translate('Legislation'); ?></strong><br />
        <?php for ($i=0; $i<count($this->revoke['piReasons']); $i++): ?>
        <?php echo $this->revoke['piReasons'][$i]['description']; ?><?php if ($i != count($this->revoke['piReasons'])-1): ?>, <?php endif; ?>
        <?php endfor; ?>
    </p>
    <p>
        <strong><?php echo $this->translate('DC/DTC agreed'); ?></strong><br />
        <?php echo isset($this->revoke['presidingTc']['name']) ? $this->revoke['presidingTc']['name'] : 'n/a'; ?>
    </p>
    <p>
        <strong><?php echo $this->translate('PTR agreed date'); ?></strong><br />
        <?php echo isset($this->revoke['ptrAgreedDate']) && !empty($this->revoke['ptrAgreedDate']) ?
            date('d/m/Y', strtotime($this->revoke['ptrAgreedDate'])) : '--/--/----'; ?>
    </p>
    <p>
        <strong><?php echo $this->translate('Closed date'); ?></strong><br />
        <?php echo isset($this->revoke['dateClosed']) && !empty($this->revoke['dateClosed']) ?
            date('d/m/Y', strtotime($this->revoke['dateClosed'])) : '--/--/----'; ?>
    </p>
    <p>
        <strong><?php echo $this->translate('Notes'); ?></strong><br />
        <?php echo isset($this->revoke['comment']) ? $this->revoke['comment'] : ''; ?>
    </p>
</div>