<?php
    echo $this->render(
        '/partials/page-header.phtml',
        array(
            'pageTitle' => $this->translate('dashboard.title'),
            'pageSubTitle'=> $this->translate('dashboard.subtitle'),
        )
    );
?>

<div class="three-quarters">
    <?php echo $this->flashMessengerAll(); ?>
    <?php echo $licences->render(); ?>
    <div class="actions-container">
        <a href="<?php echo $this->url('create_application'); ?>" class="action--primary large">
            <?php echo $this->translate('application.new.button'); ?>
        </a>
    </div>
    <?php echo $variations->render(); ?>
    <?php echo $applications->render(); ?>
</div>

<div class="one-quarter">
    <h3>Notifications</h3>
</div>
