<h4 class="title"><?php echo $this->translate('application-details-nav'); ?></h4>
<ul class="app-navigation" role="menu">
    <?php foreach ($sections as $reference => $details) : ?>
        <?php
        $current = false;
        if ($details['route'] === $currentRoute) {
            $current = true;
            $details['class'] = 'current ' . $details['class'];
        }
        ?>
        <li class="app-navigation__item <?php echo $details['class']; ?> <?php echo $details['enabled'] ? '' : 'disabled'; ?>">
            <?php if (!$current && $details['enabled']) : ?>
            <a href="<?php echo $this->url($details['route'], ['application' => $lvaId]); ?>">
                <?php endif; ?>
                <?php
                    $sectionName = $reference;
                    if (isset($details['alias'])) {
                        $sectionName = $details['alias'];
                    }

                    echo $this->translate('section.name.' . $sectionName);
                ?>
                <?php if (!$current && $details['enabled']) : ?>
            </a>
        <?php endif; ?>
            <?php if ($current && isset($filterForm)): ?>
                <?php echo $this->form($filterForm); ?>
            <?php endif;?>
        </li>
    <?php endforeach; ?>
</ul><!-- end .progress -->
