<?php
echo $this->showMarkers();

/**
 * Application quick actions
 *
 * @var \Zend\Navigation\Navigation
 */
$nav = $this->navigation('right-sidebar')
    ->menu($this->navigation()->findOneBy('id', 'application-quick-actions'))
    ->setPartial('partials/record-actions__group');

if ($nav->getContainer()->hasPages(true) && $nav->getContainer()->isVisible()): ?>
    <div class="record-actions">
        <h5>Quick actions</h5>
        <?php echo $nav; ?>
    </div>
<?php endif;

/**
 * Decisions quick actions
 *
 * @var \Zend\Navigation\Navigation
 */
$nav = $this->navigation('right-sidebar')
    ->menu($this->navigation()->findOneBy('id', 'application-decisions'))
    ->setPartial('partials/record-actions__group');

if ($nav->getContainer()->hasPages(true)): ?>
    <div class="record-actions">
        <h5>Decisions</h5>
        <?php echo $nav; ?>
    </div>
<?php endif;
