<?php
$title = 'You will need to apply for an annual ECMT permit';
$this->headTitle($title);
?>
<p><?php echo $this->linkBack($this->backUrl); ?></p>
<p>Step 2 of 3</p>

<h1 class="js-title"><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('permits', array('action' => 'step3')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));

?>
<div class="form-group panel panel-border-wide">
    <p class="guidance">You can apply for up to 12 permits </p>
</div>
<legend>Which countries will you be delivering to?</legend>
<p>Select all the apply</p>
<?php
echo $this->formRow($form->get('deliveryCountries'));

echo $this->formRow($form->get('numberOfTrips'));

echo $this->formRow($form->get('sector'));
?>
<div class="actions-container new-application--wrapper">
    <p><?php echo $this->formSubmit($form->get('submit'));  ?></p>
</div>
<?php echo $this->form()->closeTag(); ?>

<a href=""> Cancel </a>

