<?php
    use Permits\View\Helper\EcmtSection;
    echo $this->permitsBackLink('common.link.back.label', 'permits');
?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <span class="govuk-caption-xl">
            <?php echo $this->escapeHtml($data['application']['applicationRef']); ?>
        </span>
        <h1 class="govuk-heading-xl">
            <?php echo $this->escapeHtml($this->translate('permits.application.overview.main')); ?>
        </h1>
        <?php echo $this->flashMessengerAll(); ?>
        <p class="govuk-body">
            <?php echo $this->escapeHtml($this->translate('permits.application.overview.complete-all-sections')); ?>
            <br>
            <?php
                echo $this->translateReplace(
                    'permits.application.overview.further-guidance',
                    [
                        $this->escapeHtml($this->translate('permits.link.ecmt.guidance'))
                    ]
                );
            ?>
        </p>

        <div class="field">
            <ol class="overview__list">
                <?php
                    foreach ($this->ecmtSection($data['application']) as $section) {
                        echo $this->render($section);
                    }
                ?>
            </ol>
            <?php if ($data['application']['canBeSubmitted']) {
                $url = $this->url(EcmtSection::ROUTE_ECMT_FEE, [], [], true);

                if (!$data['application']['hasOutstandingFees']) {
                    $url = $this->url(EcmtSection::ROUTE_ECMT_DECLARATION, [], [], true);
                }
            ?>
                <a href="<?php echo $url; ?>" class="govuk-button govuk-!-margin-top-5">
                    <?php echo $this->escapeHtml($this->translate('permits.button.accept-and-continue')); ?>
                </a>
            <?php } ?>
        </div>
    </div>
    <aside class="govuk-grid-column-one-third">
        <div class="info-box info-box--grey">
            <h2 class="govuk-heading-m">
                <?php echo $this->escapeHtml($this->translate('permits.application.overview.progress')); ?>
            </h2>
            <p class="govuk-body govuk-!-font-weight-bold">
                <?php echo $this->translateReplace('permits.application.overview.progress.complete', [
                    $this->escapeHtml($data['application']['sectionCompletion']['totalCompleted']),
                    $this->escapeHtml($data['application']['sectionCompletion']['totalSections'])
                ]); ?>
            </p>
            <p class="govuk-body">
                <b><?php echo $this->escapeHtml($this->translate('permits.application.overview.fee-per-permit')); ?></b>
                <?php echo $this->currencyFormatter($data['irhpFeeList']['appFee']); ?>
                <br/>
                <?php echo $this->escapeHtml($this->translate('permits.page.non.refundable')); ?>
            </p>
            <p class="govuk-body">
                <b><?php echo $this->escapeHtml($this->translate('permits.application.overview.total-application-fee')); ?></b>
                <?php echo $this->currencyFormatter($data['irhpFeeList']['appFee'] * $data['application']['permitsRequired']); ?>
            </p>
            <p class="govuk-body"><?php echo $this->escapeHtml($this->translate('permits.application.overview.complete-all-sections-warning')); ?></p>
        </div>
        <div class="info-box info-box--grey">
            <h3 class="govuk-heading-m">
                <?php echo $this->escapeHtml($this->translate('permits.page.ecmt.consideration.application.status')); ?>
            </h3>
            <p class="info-box__icon-wrapper govuk-body">
                <i class="info-box__icon selfserve-important"></i><?php echo $this->escapeHtml($data['application']['status']['description']); ?>
            </p>
            <?php if ($data['application']['canBeCancelled']) { ?>
                <a class="govuk-link" href="<?php echo $this->url(EcmtSection::ROUTE_CANCEL_APPLICATION, [], [], true); ?>">
                    <?php echo $this->escapeHtml($this->translate('permits.page.cancel.question')); ?>
                </a>
            <?php } ?>
        </div>
    </aside>
</div>
