<?php
    $title = $this->translate('permits.page.title.cabotage');
    $this->headTitle($title);
?>
<style>
    .form-control, .cabotageRadio {
        margin: 0 10px 0 10px;
        float: none;
        display: inline;
    }
</style>
<div class="page-header">
    <p>
        <a href="/permits/euro6-emissions" class="back-link"> <?php echo $this->translate('permits.back-link'); ?> </a>
    </p>
</div>
<fieldset id="cabotage" class="inline" data-group="cabotage">
    <legend>
        <div class="page-header__wrapper">
            <h1 class="heading-medium">
                <?php
                    echo $this->translate('permits.application.cabotage.question');
                ?>
            </h1>
        </div>
    </legend>

    <div class="row">
        <div class="dashboard two-thirds js-body">
            <?php
                echo $this->flashMessengerAll();
                echo $this->formErrors($form);
                echo $this->form($form);
            ?>
            <div id="cabotage-hint" data-group="cabotage-hint" class="guidance">
                <p class="hint">
                    <?php echo $this->translate('permits.application.cabotage.hint'); ?>
                </p>
            </div>
        </div>
    </div>
</fieldset>