<?php
    use Permits\View\Helper\EcmtSection;

    $title = $this->translate('permits.page.title.check-answers');
    $this->headTitle($title);
?>

<div class="row ecmt">
    <div class="three-quarters">
        <div class="page-header">
            <p><?php echo $this->permitsBackLink(); ?></p>
            <div class="page-header__wrapper">
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($title); ?>
                </h1>
            </div>
        </div>

        <div class="field">
           <div class="table_wrapper">
                <table>
                    <thead>
                        <tr>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['licenceQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php echo $sessionData['licenceAnswer']; ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_LICENCE); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['meetsEuro6Question'] ?></h4>
                            </td>
                            <td>
                                <?php  echo $sessionData['meetsEuro6Answer']; ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_EURO6); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['cabotageQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php echo $sessionData['cabotageAnswer'] ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_CABOTAGE); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['restrictedCountriesQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php
                                $count = 1;
                                $listSize = count($sessionData['restrictedCountriesAnswer']);
                                if($listSize > 1)
                                {
                                    echo "Yes";
                                    echo "<br>";

                                    foreach ($sessionData['restrictedCountriesAnswer'] as $country) {
                                        if ($count == $listSize) {
                                            echo $country;
                                        } else {
                                            echo $country . ', ';
                                        }
                                        $count++;
                                    }
                                }else{
                                    echo "No";
                                }
                                ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_COUNTRIES); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['tripsQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php echo $sessionData['tripsAnswer'] ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_TRIPS); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['percentageQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php echo $sessionData['percentageAnswer'] ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_INTERNATIONAL_JOURNEY); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['specialistHaulageQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php echo $sessionData['specialistHaulageAnswer'] ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_SECTORS); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['permitsQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php echo $sessionData['permitsAnswer'] ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_NO_OF_PERMITS); ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="actions-container new-application--wrapper">
                <p><a href="<?php echo $this->url('permits/' . EcmtSection::ROUTE_ECMT_DECLARATION, [], [], true); ?>" class="action--primary large"><?php echo $this->translate('permits.button.confirm-and-continue'); ?></a></p>
                <p><a href="<?php echo $this->url('permits') ?>"> <?php echo $this->translate('permits.button.save-return-to-permits'); ?> </a></p>
            </div>
        </div>
    </div>
</div>
