<?php echo $this->permitsBackLink(); ?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <?php echo $this->formErrors($form); ?>
        <span class="govuk-caption-xl">
            <?php echo $this->escapeHtml($data['application']['applicationRef']); ?>
        </span>
        <h1 class="govuk-heading-xl">
            <?php echo $this->escapeHtml($this->translate($data['title'])); ?>
        </h1>
        <dl class="app-check-your-answers app-check-your-answers--long">
            <?php foreach ($data['application']['answers'] as $answer) { ?>
                <div class="app-check-your-answers__contents">
                    <dt class="app-check-your-answers__question">
                        <?php echo $this->escapeHtml($this->translate($answer['question'])); ?>
                    </dt>
                    <dd class="app-check-your-answers__answer">
                        <?php if (is_array($answer['answer'])) {
                            foreach ($answer['answer'] as $answerLine) {
                                echo $this->escapeHtml($this->translate($answerLine)) . '<br />';
                            }
                        } else {
                            echo $this->escapeHtml($this->translate($answer['answer']));
                        } ?>
                    </dd>
                    <dd class="app-check-your-answers__change">
                        <?php echo $this->changeAnswerLink($answer['route'], $this->escapeHtml($this->translate($answer['question']))); ?>
                    </dd>
                </div>
            <?php } ?>
        </dl>
        <?php echo $this->form($form); ?>
        <?php echo $this->saveAndReturnLink('permits.button.save-return-to-overview'); ?>
    </div>
</div>
