<?php
$title = $this->translate('permits.application.declaration.title');
$this->headTitle($title);

    /*
     * HIDDEN FORM TO SAVE TO DATABASE
     */

    $form->setAttribute('action', $this->url('permits', array('action' => 'payment')));

    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formHidden($form->get('intensity'));
    echo $this->formRow($form->get('sectors'));
    echo $this->formRow($form->get('restrictedCountries'));
    echo $this->formRow($form->get('restrictedCountriesList'));
?>
<p><?php echo $this->linkBack($this->backUrl); ?></p>

<h1 class="js-title"><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="two-thirds">
        <?php echo $this->translate('markup-ecmt-declaration'); ?>
        <div class="actions-container new-application--wrapper">
            <p><a href="/permits/payment" class="action--primary large"><?php echo $this->translate('continuation.success.pay'); ?></a></p>
            <p><a href="/permits"> <?php echo $this->translate('Cancel'); ?> </a></p>
        </div
</div>
