<?php
$title = $this->translate('permits.page.declaration.title');
$this->headTitle($title);
?>

<?php echo $this->permitsBackLink(); ?>
<?php echo $this->formErrors($form); ?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <span class="govuk-caption-xl">
            <?php echo $this->escapeHtml($data['application']['applicationRef']); ?>
        </span>
        <div class="govuk-fieldset">
            <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
                <h1 class="govuk-fieldset__heading">
                    <?php echo $this->escapeHtml($this->translate('permits.page.declaration.question')); ?>
                </h1>
            </legend>
            <?php echo $this->translate('markup-ecmt-declaration'); ?>

            <fieldset id="declaration" class="inline" data-group="declaration">
                <?php echo $this->form($form); ?>
            </fieldset>
        </div>
    </div>
</div>
