<?php
    $title = $this->translate('permits.page.declined_permit.title');
    $this->headTitle($title);
?>

<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
            <p><a href="<?php echo $this->url('permits') ?>" class="back-link"> <?php echo $this->escapeHtml($this->translate('common.link.back.label')); ?></a></p>
            <?php echo $this->formErrors($form); ?>
            <div class="page-header__wrapper">
                <h3 class="page-header__subtitle"><?php echo $this->escapeHtml($data['application']['applicationRef']); ?></h3>
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($title); ?>
                </h1>
            </div>
        </div>

        <div class="field">
            <div class="govuk-hint">
                <?php echo $this->translate('markup-ecmt-application-decline'); ?>
            </div>

            <fieldset id="declineApplication" class="inline" data-group="declineApplication">
                <?php echo $this->form($form); ?>
                <fieldset class="actions-container new-application--wrapper">
                    <p><a href="<?php echo $this->url('permits') ?>"> <?php echo $this->escapeHtml($this->translate('permits.button.cancel-and-return')); ?></a></p>

                </fieldset>
            </fieldset>
        </div>

    </div>
</div>
