<?php
$title = $this->translate('permits.page.ecmt.licence.title');
$this->headTitle($title);
$data = $this->ecmtLicenceData($form, $application);
?>
<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
            <p><a href="<?php echo $this->url('permits'); ?>" class="back-link"><?php echo $this->escapeHtml($this->translate('common.link.back.label')); ?></a></p>
            <div class="page-header__wrapper">
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($data['title']); ?>
                </h1>
            </div>
        </div>

                <fieldset id="ecmt-licence" class="inline " data-group="ecmt-licence">
                    <?php
                    echo $data['copy'];

                    if (empty($form->get('Fields')
                        ->get('EcmtLicence')->getValueOptions())) {
                        $form->get('Fields')->get('SubmitButton')->setAttribute('class', 'visually-hidden');
                        $form->get('Fields')->get('EcmtLicence')->setOptions(['label' => '']);
                    }
                    if (!isset($application) && count($form->get('Fields')->get('EcmtLicence')->getValueOptions()) === 1) {
                        $option = $form->get('Fields')->get('EcmtLicence')->getValueOptions()[0];
                        $option['selected'] = true;
                        $option['label_attributes'] = ['class' => 'visually-hidden'];

                        $form->get('Fields')->get('EcmtLicence')->setValueOptions([$option]);
                    }
                    $form->get('Fields')->get('EcmtLicence')->setLabelOptions(array('disable_html_escape' => true));

                    echo $this->formErrors($form);
                    echo $this->form($form);
                    ?>
                </fieldset>
    <?php
            if (count($form->get('Fields')->get('EcmtLicence')->getValueOptions()) > 0 || isset($application)) {
                echo $this->permitsDashboardLink();
            }
    ?>
        </div>

    </div>
</div>
