<?php
$title = $this->translate('permits.page.ecmt.licence.title');
$this->headTitle($title);
?>

<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
            <p><a href="<?php echo $this->url('permits'); ?>" class="back-link"><?php echo $this->escapeHtml($this->translate('common.link.back.label')); ?></a></p>
            <div class="page-header__wrapper">
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($this->ecmtLicenceTitle($application, $licences)); ?>
                </h1>
            </div>
        </div>

        <div class="field">
            <div class="govuk-hint">
                <p class=" guidance-blue extra-space large"><?php echo $this->escapeHtml($this->translate('permits.page.ecmt.licence.info')); ?></p>
            </div>

            <fieldset id="ecmt-licence" class="inline" data-group="ecmt-licence">
                <?php
                    echo $this->form($form);
                    echo $this->translate('markup-ecmt-licence-restricted-info');
                ?>
            </fieldset>
        </div>

    </div>
</div>
