<?php
    use Dvsa\Olcs\Transfer\Query\Permits\EcmtCountriesList;

    $title = $this->translate('permits.application.overwiew.main-title');
    $this->headTitle($title);
?>

    $title = $this->translate('permits.page.ecmt.guidance.header.title');
    $this->headTitle($title);
?>

<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
            <div class="page-header__wrapper">
                <h3 class="page-header__subtitle"><?php echo $this->escapeHtml($ref); ?></h3>
                <h1 class="js-title">
                    <?php echo $this->translate('permits.page.ecmt.guidance.title'); ?>
                </h1>
            </div>
        </div>

        <div class="field">
            <p class="guidance-subtitle"><?php echo $this->translate('permits.page.ecmt.guidance.subtitle'); ?></p>
            <?php echo $this->translate('markup-ecmt-guidance-introduction'); ?>
            <?php echo $this->translate('markup-ecmt-guidance-ecmt-countries'); ?>
            <?php echo sprintf($this->translate('markup-ecmt-guidance-body'), $this->currencyFormatter($applicationFee), $this->currencyFormatter($applicationFee), $this->currencyFormatter($issueFee)); ?>
        </div>
    </div>
</div>
