<?php
    $title = $this->translate('permits.page.ecmt.guidance.header.title');
    $this->escapeHtml($this->headTitle($title));
?>

<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
            <div class="page-header__wrapper">
                <h3 class="page-header__subtitle"><?php echo $this->escapeHtml($ref); ?></h3>
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($this->translate('permits.page.ecmt.guidance.title')); ?>
                </h1>
            </div>
        </div>

        <div class="field">
            <p class="guidance-subtitle"><?php echo $this->escapeHtml($this->translate('permits.page.ecmt.guidance.subtitle')); ?></p>
            <?php echo $this->translate('markup-ecmt-guidance-introduction'); ?>
            <?php echo $this->translate('markup-ecmt-guidance-ecmt-countries'); ?>
            <?php echo $this->translate('markup-ecmt-guidance-body'); ?>
        </div>
    </div>
</div>
