<head>
  <meta charset="UTF-8">
  <title></title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="jquery.js"></script>
</head>

<?php
    $title = 'International haulier permit';
    $this->headTitle($title);
?>
<p><?php echo $this->linkBack($this->backUrl); ?></p>

<p>Step 1 of 3</p>

<h1 class="js-title"><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('permits', array('action' => 'eligible')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<legend>Will you be carrying out cabotage?</legend>
<p>Transport goods between two places in the same country</p>
<div class="form-group"><fieldset class="inline"><?php echo $this->formRow($form->get('willCabotage')); ?></fieldset></div>


<legend>Do your vehicles meet the environmentally compliant standard Euro 6?</legend>
<a href="">Compliant standards</a>
<p hidden>HIDDEN TEXT TO BE DISPLAYED WHEN Compliant Standards IS TOGGLED</p>
<?php echo $this->formRow($form->get('meetsEuro6')); ?>

<legend>Which countries will you be delivering to?</legend>
<div class="input_fields_wrap">
  <?php 
  foreach ($form->get('country') as $element) : 
    echo $this->formRow($element);
  endforeach;
  ?>
  <a href="#" class="add_country_button">Add another country</a>
</div>
<div class="actions-container new-application--wrapper">
    <p><?php echo $this->formSubmit($form->get('submit'));  ?></p>
    <p><a href="/permits"> Cancel </a></p>
</div>
<?php echo $this->form()->closeTag(); ?>



<script>
  $(document).ready(function() {
    var max_fields      = 10; //maximum input boxes allowed
    var wrapper         = $(".input_fields_wrap"); //Fields wrapper
    var add_button      = $(".add_country_button"); //Add button ID
    var country_count   = 1;
    
    var x = 1; //initlal text box count
    $(add_button).click(function(e){ //on add input button click
      e.preventDefault();
        if(x < max_fields){ //max input box allowed
            x++; //text box increment
      country_count++; //label increment
      $(wrapper).append('<div><label>Country ' 
        + country_count 
        + ' </label><input type="text" name="country[]"/>'
                + '<a href="#" class="remove_field">Remove</a></div>'); //add input box
    }
  });
    
    $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
      e.preventDefault(); $(this).parent('div').remove();
      x--;
      country_count--;
    })
  });
</script>

