<head>
  <meta charset="UTF-8">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="jquery.js"></script>
</head>

<?php
    $title = $this->translate('permits.application.eligibility.title');
    $this->headTitle($title);
?>

<div class="page-header">
    <p><?php echo $this->linkBack($this->backUrl); ?></p>
    <div class="page-header__wrapper">
        <h3 class="page-header__subtitle"><?php echo sprintf($this->translate('application.steps'), 1, 3); ?></h3>
        <h1 class="js-title"><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</div>

<?php
$form->setAttribute('action', $this->url('permits', array('action' => 'eligible')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div class="<?php echo ($hasValidationError) ? 'field error__wrapper' : 'field' ?>">
    <fieldset id="cabotage" data-group="cabotage">
        <legend><?php echo $this->escapeHtml($this->translate('permits.application.eligibility.willCabotage.question')); ?></legend>
        <p class="hint"><?php echo $this->escapeHtml($this->translate('permits.application.eligibility.willCabotage.explanation')); ?></p>
        <?php echo $this->formRow($form->get('willCabotage')); ?>
    </fieldset>

    <fieldset id="euro6" data-group="euro6">
        <legend><?php echo $this->escapeHtml($this->translate('permits.application.eligibility.meetsEuro6.question')); ?></legend>
        <p class="hint"><?php echo $this->escapeHtml($this->translate('permits.application.eligibility.meetsEuro6.link')); ?></a>
        <p hidden><?php echo $this->escapeHtml($this->translate('permits.application.eligibility.meetsEuro6.hidden')); ?></p>
        <?php echo $this->formRow($form->get('willCabotage')); ?>
    </fieldset>

    <fieldset id="country" data-group="country">
        <legend><?php echo $this->escapeHtml($this->translate('permits.application.eligibility.country.question')); ?></legend>
        <div class="input_fields_wrap">
            <?php
            foreach ($form->get('country') as $element) :
                echo $this->formRow($element);
            endforeach;
            ?>
            <a href="#" class="add_country_button"><?php echo $this->escapeHtml($this->translate('permits.application.eligibility.country.add')); ?></a>
        </div>
    </fieldset>

    <fieldset class="actions-container new-application--wrapper">
        <p><?php echo $this->formSubmit($form->get('submit'));  ?></p>
        <p><a href="/permits"> <?php echo $this->translate('cancel'); ?> </a></p>
    </fieldset>
</div>

<?php echo $this->form()->closeTag(); ?>

<script>
  $(document).ready(function() {
    var max_fields      = 10; //maximum input boxes allowed
    var wrapper         = $(".input_fields_wrap"); //Fields wrapper
    var add_button      = $(".add_country_button"); //Add button ID
    var country_count   = 1;
    
    var x = 1; //initlal text box count
    $(add_button).click(function(e){ //on add input button click
      e.preventDefault();
        if(x < max_fields){ //max input box allowed
            x++; //text box increment
      country_count++; //label increment
      $(wrapper).append('<div><label>Country ' 
        + country_count 
        + ' </label><input type="text" name="country[]"/>'
                + '<a href="#" class="remove_field">Remove</a></div>'); //add input box
    }
  });
    
    $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
      e.preventDefault(); $(this).parent('div').remove();
      x--;
      country_count--;
    })
  });
</script>

