<?php
$title = $this->translate('permits.application.eligibility.eligible.title');
$this->headTitle($title);
?>
<p><?php echo $this->linkBack($this->backUrl); ?></p>

<h1 class="js-title"><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">

    <div class="two-thirds">

        <?php echo $this->translate('markup-ecmt-eligible'); ?>

        <div class="actions-container new-application--wrapper">
            <p><a href="/permits/application" class="action--primary large"><?php echo $this->translate('continue.button'); ?></a></p>
            <p><a href="/permits"> <?php echo $this->translate('Cancel'); ?> </a></p>
        </div>
    </div>
    <?php echo $this->partial('partials/dashboard-right-column'); ?>
</div>
