<?php

    $title = $this->translate('permits.page.euro6.emissions.title');
    $this->headTitle($title);
?>

<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
            <p><?php echo $this->permitsBackLink(); ?></p>
            <div class="page-header__wrapper">
                <h1 class="js-title">
                    <?php echo $this->translate('permits.page.euro6.emissions.question'); ?>
                </h1>
            </div>
        </div>

        <div class="field">
            <div class="govuk-hint">
                <p><?php echo $this->translate('permits.page.euro6.emissions.info'); ?></p>
            </div>

            <fieldset id="euro6" class="inline" data-group="euro6">
                <?php
                    echo $this->formErrors($form);
                    echo $this->form($form);
                ?>

                <fieldset class="actions-container new-application--wrapper">
                    <p><?php echo $this->permitsBackLink('permits.button.save-return-to-overview'); ?></p>
                </fieldset>
            </fieldset>
        </div>

    </div>
</div>
