<?php echo $this->permitsBackLink(); ?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <?php echo $this->formErrors($form); ?>
        <span class="govuk-caption-xl">
            <?php echo $this->escapeHtml($data['application']['applicationRef']); ?>
        </span>
        <h1 class="govuk-heading-xl">
            <?php echo $this->escapeHtml($this->translate($data['application']['title'])); ?>
        </h1>
        <?php echo $this->partial('partials/guidance-blue-component', ['guidance' => $data['application']['guidance']]); ?>
        <?php echo $this->partial('partials/summary-list', ['data' => $data['application']['summaryData']]); ?>
        <?php echo $this->form($form); ?>
        <?php echo $this->permitsBackLink('permits.link.cancel.return.to.dashboard', 'permits'); ?>
    </div>
</div>
