<?php echo $this->permitsBackLink(); ?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <?php echo $this->formErrors($form); ?>
        <span class="govuk-caption-xl">
            <?php echo $this->escapeHtml($data['application']['applicationRef']); ?>
        </span>
        <h1 class="govuk-heading-xl">
            <?php echo $this->escapeHtml($this->translate('permits.page.irhp-fee.permit.fee')); ?>
        </h1>
        <?php echo $this->partial('partials/warning-component', [
            'translationKey' => 'permits.page.fee.message',
            'disableHtmlEscape' => true
        ]); ?>
        <h3><?php echo $this->translate('permits.page.irhp-fee.fee-summary'); ?></h3>
        <?php echo $this->partial('partials/summary-list', ['data' => $data['application']['summaryData']]); ?>
        <?php echo $this->form($form); ?>
        <?php echo $this->permitsBackLink('permits.button.save-return-to-overview'); ?>
    </div>
</div>
