<?php
    $title = $this->translate('permits.page.title.fee');
    $this->headTitle($title);
?>

<div class="row">
    <div class="three-quarters">
        <div class="page-header">
            <p><a href="/permits/declaration" class="back-link"> <?php echo $this->translate('permits.back-link'); ?> </a></p>
            <div class="page-header__wrapper">
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($title); ?>
                    <span><?php echo $permitsNo; ?></span>
                </h1>
            </div>
        </div>

        <div class="field">
            <div class="form-group">
                <table class="fee-table">
                    <tr>
                        <td><h4>Fee number</h4></td>
                        <td>10090317</td>
                    </tr>
                    <tr>
                        <td><h4>Description</h4></td>
                        <td>Fee for <abbr title="European Conference of Ministers of Transport">ECMT permit 84051</abbr></td>
                    </tr>
                    <tr>
                        <td><h4>Reference</h4></td>
                        <td><?php echo $permitsNo; ?></td>
                    </tr>
                    <tr>
                        <td><h4>Created</h4></td>
                        <td><?php echo date("d F Y"); ?></td>
                    </tr>
                    <tr>
                        <td><h4>Invoice amount</h4></td>
                        <td>£133.00</td>
                    </tr>
                    <tr>
                        <td><h4>Oustanding</h4></td>
                        <td>£133.00</td>
                    </tr>
                </table>

            </div>

            <div class="actions-container new-application--wrapper">
                <?php echo $this->translate('permits.page.message.fee'); ?>
                <p><a href="/permits/submitted" class="action--primary large"><?php echo $this->translate('submit-and-pay.button'); ?></a></p>
                <p><a href="/permits"> <?php echo $this->translate('permits.button.save-return-to-permits'); ?> </a></p>
            </div>
        </div>
    </div>
</div>
