<?php
    $title = $this->translate('permits.page.international.journey.title');
    $this->escapeHtml($this->headTitle($title));
?>

<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
            <p><?php echo $this->escapeHtml($this->permitsBackLink()); ?></p>
            <div class="page-header__wrapper">
                <h3 class="page-header__subtitle"><?php echo $this->escapeHtml($ref); ?></h3>
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($this->translate('permits.page.international.journey.question')); ?>
                </h1>
            </div>
        </div>

        <div class="field">
            <div class="govuk-hint">
            </div>

            <fieldset id="international-journey" class="inline" data-group="international-journey">
                <?php
                    echo $this->formErrors($form);
                    echo $this->form($form);
                ?>
            </fieldset>
        </div>
    </div>
</div>
