<?php
    use Permits\Controller\Config\DataSource\IrhpApplication;
    use Permits\View\Helper\IrhpApplicationSection;
?>

<?php echo $this->permitsBackLink('common.link.back.label', $data['backUri']); ?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-xl">
            <?php echo $this->escapeHtml($this->translate('permits.irhp.under-consideration.title')); ?>
        </h1>
        <h2 class="govuk-heading-m">
            <?php echo $this->escapeHtml($this->translate('permits.irhp.under-consideration.application-details')); ?>
        </h2>
        <?php echo $this->partial('partials/summary-list', ['data' => $data[IrhpApplication::DATA_KEY]['mappedFeeData']]); ?>
        <?php
        if (!empty($data[IrhpApplication::DATA_KEY]['businessProcess']['id'])) {
            echo $this->partial(
                'partials/guidance-blue-component',
                [
                    'guidance' => 'permits.irhp.under-consideration.response-date.'
                        .$data[IrhpApplication::DATA_KEY]['businessProcess']['id']
                ]
            );
        }
        ?>
        <a class="govuk-button" href="<?php echo $this->url(IrhpApplicationSection::ROUTE_WITHDRAW_APPLICATION, [], [], true); ?>">
            <?php echo $this->translate('application.withdraw'); ?>
        </a>
        <p><?php echo $this->permitsDashboardLink('permits.link.return.to.dashboard'); ?></p>
    </div>
</div>
