<?php
    use Permits\Controller\Config\DataSource\IrhpApplication;
?>

<?php echo $this->permitsBackLink('common.link.back.label', $data['backUri']); ?>

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">

        <h1 class="govuk-heading-xl">
            <?php echo $this->escapeHtml($this->translate('permits.page.irhp-fee.permit.fee')); ?>
        </h1>

        <?php
            echo $this->partial('partials/summary-list', ['data' => $data[IrhpApplication::DATA_KEY]['mappedFeeData']]);
        ?>
    </div>
    <?php echo $this->form($form); ?>
    <?php echo $this->permitsBackLink('permits.button.save-return-to-overview', $data['backUri']); ?>
</div>
