<?php
    use Permits\Controller\Config\DataSource\IrhpApplication;

    $feeBreakdownTable = $tables['irhp-fee-breakdown'];
?>

<?php echo $this->permitsBackLink('common.link.back.label', $data['backUri']); ?>

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <?php echo $this->flashMessengerAll(); ?>
        <h1 class="govuk-heading-xl">
            <?php echo $this->escapeHtml($this->translate('permits.page.irhp-fee.permit.fee')); ?>
        </h1>
        <?php 

            if (isset($data[IrhpApplication::DATA_KEY]['showWarningMessage'])) {
                echo $this->partial(
                    'partials/warning-component',
                    [
                        'translationKey' => 'permits.page.irhp-fee.message',
                        'disableHtmlEscape' => true
                    ]
                );
            }

            if ($feeBreakdownTable->hasRows() || isset($data[IrhpApplication::DATA_KEY]['showFeeSummaryTitle'])) {
                ?><h2 class="govuk-heading-m"><?php echo $this->escapeHtml($this->translate('permits.page.irhp-fee.fee-summary')); ?></h2><?php
            }

            echo $this->partial('partials/summary-list', ['data' => $data[IrhpApplication::DATA_KEY]['mappedFeeData']]);

            if ($feeBreakdownTable->hasRows()) {
                ?><h2 class="govuk-heading-m"><?php echo $this->escapeHtml($this->translate('permits.page.irhp-fee.fee-breakdown')); ?></h2><?php
                echo($feeBreakdownTable);
            }

            echo($this->form($form));
    
            echo $this->permitsBackLink('permits.button.save-return-to-overview', $data['backUri']);
        ?>
    </div>

</div>
