<?php
    use Permits\View\Helper\IrhpApplicationSection as Section;
    use Permits\Controller\Config\DataSource\IrhpApplication as IrhpAppDataSource;
    use Permits\Controller\Config\DataSource\QuestionAnswer as QuestionAnswerDataSource;

    $application = $data[IrhpAppDataSource::DATA_KEY];
    $questionAnswer = $data[QuestionAnswerDataSource::DATA_KEY];

    $countriesPageUrlOptions = [
        'query' => ['fromOverview' => 1]
    ];
    $countriesPageUrl = $this->url(Section::ROUTE_COUNTRIES, [], $countriesPageUrlOptions, true);
?>

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <div class="page-header">
            <p><a href="<?php echo $this->url('permits'); ?>" class="govuk-back-link"> <?php echo $this->escapeHtml($this->translate('common.link.back-to-permits.label')); ?></a></p>
            <div class="page-header__wrapper">
                <span class="govuk-caption-xl">
                    <span class="visually-hidden"><?php echo($this->escapeHtml($this->translate('permits.application.overview.application.reference'))); ?></span>
                    <?php echo $this->escapeHtml($application['applicationRef']); ?>
                </span>
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($this->translate('permits.application.overview.browser.title')); ?>
                </h1>
            </div>
        </div>

     <ol class="app-task-list">
        <li>
          <h2 class="app-task-list__section">
            <span class="app-task-list__section-number">1. </span> <?php echo $this->escapeHtml($this->translate('permits.application.overview.start-your-application')); ?>
          </h2>
          <ul class="app-task-list__items">
            <li class="app-task-list__item">
              <span class="app-task-list__task-name">
                <?php echo $this->link($countriesPageUrl, 'permits.application.overview.select-countries'); ?>
              </span>
              <span class="overview__status <?php echo Section::COMPLETION_STATUS_COLOUR[Section::SECTION_COMPLETION_COMPLETED]; ?>"><?php echo $this->escapeHtml($this->translate(Section::COMPLETION_STATUS[Section::SECTION_COMPLETION_COMPLETED])); ?></span>
            </li>
          </ul>
        </li>
        <li>
          <h2 class="app-task-list__section">
            <span class="app-task-list__section-number">2. </span> <?php echo $this->escapeHtml($this->translate('permits.application.overview.answer-country-questions')); ?>
          </h2>
          <ul class="app-task-list__items">
            <?php
    
            foreach ($questionAnswer['countries'] as $country) {
                $countryCode = $country['countryCode'];
                $countryName = $country['countryName'];
                $status = $country['status'];
                $statusCaption = Section::COMPLETION_STATUS[$status];
                $statusColour = Section::COMPLETION_STATUS_COLOUR[$status];
                $countryUrl = ($status === Section::SECTION_COMPLETION_COMPLETED)
                    ? $this->url(Section::ROUTE_IPA_CHECK_ANSWERS, ['irhpPermitApplication' => $country['irhpPermitApplication']], ['query' => ['fromOverview' => 1]], true)
                    : $this->url(Section::ROUTE_ESSENTIAL_INFORMATION, ['country' => $countryCode], [], true);
            ?>

            <li class="app-task-list__item">
              <span class="app-task-list__task-name">
                <?php echo $this->link($countryUrl, $country['countryName']); ?>
              </span>
              <span class="overview__status <?php echo $statusColour; ?>"><?php echo $this->escapeHtml($this->translate($statusCaption)); ?></span>
            </li>

            <?php 
            
            }

            ?>
          </ul>
          <a class="govuk-button govuk-button--secondary" role="button" href="<?php echo $countriesPageUrl; ?>">
            <?php echo $this->escapeHtml($this->translate('permits.application.overview.edit-country-selection')); ?>
          </a>
        </li>
        <li>
          <h2 class="app-task-list__section">
            <span class="app-task-list__section-number">3. </span> <?php echo $this->escapeHtml($this->translate('permits.application.overview.review-and-submit')); ?>
          </h2>
          <ul class="app-task-list__items">
            <li class="app-task-list__item">
              <?php

                $status = $questionAnswer['reviewAndSubmit']['declaration'];
                $statusCaption = Section::COMPLETION_STATUS[$status];
                $statusColour = Section::COMPLETION_STATUS_COLOUR[$status];
                $linkActive = $status != Section::SECTION_COMPLETION_CANNOT_START;

              ?>
              <span class="app-task-list__task-name">
                <?php if ($linkActive) {
                    echo $this->link(
                        $this->url(Section::ROUTE_DECLARATION, [], [], true),
                        'permits.application.overview.read-declaration'
                    );
                } ?>
              </span>
              <span class="overview__status <?php echo $statusColour; ?>"><?php echo $this->escapeHtml($this->translate($statusCaption)); ?></span>
            </li>
            <li class="app-task-list__item">
              <?php

                $status = $questionAnswer['reviewAndSubmit']['submitAndPay'];
                $statusCaption = Section::COMPLETION_STATUS[$status];
                $statusColour = Section::COMPLETION_STATUS_COLOUR[$status];
                $linkActive = $status == Section::SECTION_COMPLETION_NOT_STARTED;

              ?>
              <span class="app-task-list__task-name">
                <?php if ($linkActive) {
                    echo $this->link(
                            $this->url(Section::ROUTE_FEE, [], [], true),
                            'permits.application.overview.submit-and-pay'
                    );
                } ?>
              </span>
              <span class="overview__status <?php echo $statusColour; ?>"><?php echo $this->escapeHtml($this->translate($statusCaption)); ?></span>
            </li>
          </ul>
        </li>
      </ol>

    <?php

    if ($data['displaySubmitApplicationButton']) {
        echo $this->form($form);
    }

    ?>

    </div>
    <!-- SIDE PANEL -->
    <div class="govuk-grid-column-one-third">
        <?php echo $this->partial('partials/irhp-application-overview-right-column', ['application' => $application]); ?>
    </div>
</div>
