<?php
    use Permits\Controller\Config\DataSource\IrhpApplication;
    use Permits\View\Helper\IrhpApplicationSection;

    $title = $this->translate('permits.irhp.under-consideration.browser.title');
    $this->headTitle($title);
?>

<?php echo $this->permitsBackLink('common.link.back.label', $data['backUri']); ?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <div class="heading-box-grey govuk-!-margin-top-0">
            <span class="govuk-caption-xl"><?php echo $this->escapeHtml($this->translate('permits.irhp.under-consideration.header')); ?></span>
            <h1 class="govuk-heading-xl"><?php echo $this->escapeHtml($data[IrhpApplication::DATA_KEY]['licence']['licNo']); ?></h1>
        </div>
        <h2 class="govuk-heading-l">
            <?php echo $this->escapeHtml($this->translate('permits.irhp.under-consideration.title')); ?>
        </h2>
        <?php echo $this->partial('partials/summary-list', ['data' => $data[IrhpApplication::DATA_KEY]['mappedFeeData']]); ?>
        <?php echo $this->partial('partials/guidance-blue-component', ['guidance' => 'permits.irhp.under-consideration.response-date']); ?>
        <a class="govuk-button" href="<?php echo $this->url(IrhpApplicationSection::ROUTE_WITHDRAW_APPLICATION, [], [], true); ?>">
            <?php echo $this->translate('application.withdraw'); ?>
        </a>
        <p><?php echo $this->permitsDashboardLink('permits.link.return.to.dashboard'); ?></p>
    </div>
</div>
