<?php echo $this->permitsBackLink('common.link.back.label', isset($data['backUri']) ? $data['backUri'] : ''); ?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <span class="govuk-caption-xl">
            <span class="visually-hidden">
                <?php echo($this->escapeHtml($this->translate('permits.application.overview.application.reference'))); ?>
            </span>
            <?php echo $this->escapeHtml($data['application']['applicationRef']); ?>
        </span>
        <h1 class="govuk-heading-xl">
            <?php echo $this->escapeHtml($this->translate($data['title'])); ?>
        </h1>
        <dl class="app-check-your-answers app-check-your-answers--long">
            <?php foreach ($data['rows'] as $row) { ?>
                <div class="app-check-your-answers__contents">
                    <dt class="app-check-your-answers__question">
                        <?php echo $this->escapeHtml($this->translate($row['question'])); ?>
                    </dt>
                    <dd class="app-check-your-answers__answer">
                        <?php echo $row['answer']; ?>
                    </dd>
                    <dd class="app-check-your-answers__change">
                    <?php
                        if (isset($row['slug'])) {
                            echo $this->permitsCheckAnswerLink(
                                'permits/application/question',
                                'common.link.change.label',
                                $this->translate($row['question']),
                                [
                                    'slug' => $row['slug']
                                ]
                            );
                        }
                    ?>
                    </dd>
                </div>
            <?php } ?>
        </dl>
        <?php echo $this->form($form); ?>
    </div>
</div>
