<?php
    use Permits\Controller\Config\DataSource\IrhpApplication;

    $feeBreakdownTableExists = isset($tables['irhp-fee-breakdown']);
    if ($feeBreakdownTableExists) {
        $feeBreakdownTable = $tables['irhp-fee-breakdown'];
    }

?>

<?php echo $this->permitsBackLink('common.link.back.label', $data['backUri']); ?>

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <?php echo $this->flashMessengerAll(); ?>
        <h1 class="govuk-heading-xl">
            <?php echo $this->escapeHtml($this->translate('permits.page.irhp-fee.permit.fee')); ?>
        </h1>
        <?php 

            if (isset($data[IrhpApplication::DATA_KEY]['warningMessage'])) {
                echo $this->partial(
                    'partials/warning-component',
                    [
                        'translationKey' => $data[IrhpApplication::DATA_KEY]['warningMessage'],
                        'disableHtmlEscape' => true
                    ]
                );
            }

            if ($feeBreakdownTableExists || isset($data[IrhpApplication::DATA_KEY]['showFeeSummaryTitle'])) {
                ?><h2 class="govuk-heading-m"><?php echo $this->escapeHtml($this->translate('permits.page.irhp-fee.fee-summary')); ?></h2><?php
            }

            echo $this->partial('partials/summary-list', ['data' => $data[IrhpApplication::DATA_KEY]['mappedFeeData']]);

            if ($feeBreakdownTableExists) {
                ?><h2 class="govuk-heading-m"><?php echo $this->escapeHtml($this->translate('permits.page.irhp-fee.fee-breakdown')); ?></h2><?php
                echo($feeBreakdownTable);
            }

            echo($this->form($form));
            echo $this->link($this->url($data['backUri'], [], [], true), 'permits.button.return-to-overview');
        ?>
    </div>

</div>
