<?php
    use Permits\View\Helper\IrhpApplicationSection as Section;
    use Permits\Controller\Config\DataSource\IrhpApplication as IrhpAppDataSource;
    use Permits\Controller\Config\DataSource\QuestionAnswer as QuestionAnswerDataSource;

    $application = $data[IrhpAppDataSource::DATA_KEY];
    $questionAnswer = $data[QuestionAnswerDataSource::DATA_KEY];
?>

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <div class="page-header">
            <p><a href="<?php echo $this->url('permits'); ?>" class="govuk-back-link"> <?php echo $this->escapeHtml($this->translate('common.link.back-to-permits.label')); ?></a></p>
            <div class="page-header__wrapper">
                <span class="govuk-caption-xl">
                    <span class="visually-hidden"><?php echo($this->escapeHtml($this->translate('permits.application.overview.application.reference'))); ?></span>
                    <?php echo $this->escapeHtml($application['applicationRef']); ?>
                </span>
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($this->translate('permits.application.overview.browser.title')); ?>
                </h1>
            </div>
        </div>
        <?php echo $this->flashMessengerAll(); ?>

        <div class="field">
            <div class="table_wrapper">
                <ol class="overview__list">
                    <?php
                    $sections = $this->irhpApplicationSection($application, $questionAnswer);

                    foreach ($sections as $section) {
                        echo $this->render($section);
                    }
                    ?>
                </ol>
            </div>
            <?php
            if ($application['canBeSubmitted']) {
                $url = $this->url(Section::ROUTE_FEE, [], [], true);

                if (!$application['hasOutstandingFees']) {
                    $url = $this->url(Section::ROUTE_DECLARATION, [], [], true);
                }
            ?>
                <a href="<?php echo $url; ?>" class="govuk-button govuk-!-margin-top-5">
                    <?php echo $this->escapeHtml($this->translate('permits.button.accept-and-continue')); ?>
                </a>
            <?php } ?>
        </div>
    </div>
    <!-- SIDE PANEL -->
    <div class="govuk-grid-column-one-third">
        <?php echo $this->partial('partials/irhp-application-overview-right-column', ['application' => $application]); ?>
    </div>
</div>
