<?php
    use Permits\Controller\Config\DataSource\IrhpApplication;
    use Permits\View\Helper\IrhpApplicationSection;
?>

<?php echo $this->permitsBackLink('common.link.back.label', $data['backUri']); ?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <?php echo $this->flashMessengerAll(); ?>
        <?php echo $this->formErrors($form); ?>
        <h1 class="govuk-heading-xl">
            <?php echo $this->escapeHtml($this->translate('permits.page.irhp.awaiting-fee.title')); ?>
        </h1>
        <h3><?php echo $this->escapeHtml($this->translate('permits.page.irhp.awaiting-fee.fee-summary')); ?></h3>
        <?php echo $this->partial('partials/summary-list', ['data' => $data[IrhpApplication::DATA_KEY]['mappedFeeData']]); ?>
        <?php echo $this->form($form); ?>
        <?php echo $this->permitsBackLink('permits.link.cancel.return.to.dashboard', IrhpApplicationSection::ROUTE_PERMITS); ?>
    </div>
</div>
