<?php

    use Permits\View\Helper\IrhpApplicationSection as Section;

    $translationHelper = $this->getHelperPluginManager()->getServiceLocator()->get('Helper\Translation');

    echo $this->permitsBackLink('common.link.back.label', Section::ROUTE_APPLICATION_OVERVIEW);
?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <?php echo $this->formErrors($form); ?>
        <span class="govuk-caption-xl">
            <?php echo $this->escapeHtml($data['irhpApplication']['applicationRef']); ?>
        </span>
        <h1 class="govuk-heading-xl">
            <?php echo $this->escapeHtml($this->translate($data['title'])); ?>
        </h1>


        <dl class="app-check-your-answers app-check-your-answers--long">
            <div class="app-check-your-answers__contents">
                <dt class="app-check-your-answers__question">
                    <?php echo $this->escapeHtml($this->translate('permits.page.fee.permit.type')); ?>
                </dt>
                <dd class="app-check-your-answers__answer">
                    <?php echo $this->escapeHtml($this->translate($data['irhpApplication']['irhpPermitType']['name']['description'])); ?>
                </dd>
                <dd class="app-check-your-answers__change"> </dd>
            </div>

            <div class="app-check-your-answers__contents">
                <dt class="app-check-your-answers__question">
                    <?php echo $this->escapeHtml($this->translate('permits.check-answers.page.question.licence')); ?>
                </dt>
                <dd class="app-check-your-answers__answer">
                    <?php echo $this->escapeHtml($data['irhpApplication']['licence']['licNo']) . '<br />(' . $this->escapeHtml($this->translate($data['irhpApplication']['licence']['trafficArea']['name'])) . ')'; ?>
                </dd>
                <dd class="app-check-your-answers__change">
                    <?php echo $this->changeAnswerLink(Section::ROUTE_LICENCE, $this->escapeHtml($this->translate('common.link.change.label'))); ?>
                </dd>
            </div>

            <div class="app-check-your-answers__contents">
                <dt class="app-check-your-answers__question">
                    <?php echo $this->escapeHtml($this->translate('permits.irhp.application.question.countries')); ?>
                </dt>
                <dd class="app-check-your-answers__answer">
                    <?php
                    foreach ($data['irhpApplication']['irhpPermitApplications'] as $application) {
                        $countries[] = $this->escapeHtml($this->translate($application['irhpPermitWindow']['irhpPermitStock']['country']['countryDesc']));
                    }
                    echo implode(array_unique($countries), ', ');
                    ?>
                </dd>
                <dd class="app-check-your-answers__change">
                    <?php echo $this->changeAnswerLink(Section::ROUTE_COUNTRIES, $this->escapeHtml($this->translate('common.link.change.label'))); ?>
                </dd>
            </div>

            <div class="app-check-your-answers__contents">
                <dt class="app-check-your-answers__question">
                    <?php echo $this->escapeHtml($this->translate('permits.irhp.application.question.no-of-permits')); ?>
                </dt>
                <dd class="app-check-your-answers__answer">
                    <?php
                    foreach ($data['irhpApplication']['irhpPermitApplications'] as $application) {

                        echo $translationHelper->translateReplace(
                            'permits.irhp.application.answers.no-of-permits',
                             [
                                $application['permitsRequired'],
                                $this->escapeHtml($this->translate($application['irhpPermitWindow']['irhpPermitStock']['country']['countryDesc'])),
                                date('Y', strtotime($application['irhpPermitWindow']['irhpPermitStock']['validTo']))
                             ]
                        ) . '<br />';
                    }
                    ?>
                </dd>
                <dd class="app-check-your-answers__change">
                    <?php echo $this->changeAnswerLink(Section::ROUTE_NO_OF_PERMITS, $this->escapeHtml($this->translate('common.link.change.label'))); ?>
                </dd>
            </div>
        </dl>

        <?php echo $this->form($form); ?>
        <?php echo $this->saveAndReturnLink('permits.button.save-return-to-overview', Section::ROUTE_APPLICATION_OVERVIEW); ?>
    </div>
</div>
