<?php echo $this->permitsBackLink('common.link.back.label', 'permits'); ?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-full">
        <span class="govuk-caption-xl">
            <?php echo $this->escapeHtml($data['licence']['licNo']); ?>
        </span>
        <h1 class="govuk-heading-xl">
            <?php echo $this->escapeHtml($data['title']); ?>
        </h1>
        <?php echo $tables['valid-irhp-permits']; ?>
        <?php echo $this->permitsDashboardLink('permits.link.return.to.dashboard'); ?>
    </div>
</div>