<?php
$title = $this->translate('permits.application.non-eligible.title');
$this->headTitle($title);
?>
<p><?php echo $this->linkBack($this->backUrl); ?></p>

<h1 class="js-title"><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="two-thirds">
        <?php echo $this->translate('markup-ecmt-non-eligible'); ?>
        <div class="actions-container new-application--wrapper">
            <p><a href="/dashboard" class="action--primary large"> <?php echo $this->translate('Finish'); ?> </a></p>
        </div>
    </div>
</div>
