<?php
    $title = 'Pay the fee ';
    $this->headTitle($title);
?>

<h1 class="js-title">
    <p>ECMT Permit 84051</p>
    <?php echo $this->escapeHtml($title); ?>
</h1>

<div class="row">
    <div class="two-thirds">
        <div class="actions-container">
            <h2 class="guidance">
                <p>The fee to use your permit is:</p>
                <strong class="bold-large">£XX.00</strong>
            </h2>
            <div class="form-group">
                <fieldset>
                    <legend class="heading-medium">Choose your card</legend>

                    <label for="pay1" class="block-label selection-button-radio">
                        <input id="pay1" type="radio" name="card" value="Card1">
                        Mastercard **** **** **** 2343
                    </label>

                    <label for="pay2" class="block-label selection-button-radio">
                        <input id="pay2" type="radio" name="card" value="Card2">
                        Visa **** **** **** 1897
                    </label>

                    <label for="new" class="block-label selection-button-radio">
                        <input id="new" type="radio" name="card" value="New">
                        Add a new card
                    </label>

                </fieldset>
            </div>
        </div>
        <div class="actions-container new-application--wrapper">
            <p><a href="/permits/submitted" class="action--primary large"><?php echo $this->translate('pay-now'); ?></a></p>
        </div
    </div>
</div>