<?php
$title = $this->translate('permits.page.permits.required.title');
$this->headTitle($title);
?>

<?php echo $this->permitsBackLink(); ?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <?php echo $this->formErrors($form); ?>
        <span class="govuk-caption-xl">
            <?php echo $this->escapeHtml($ref); ?>
        </span>
        <div class="govuk-fieldset">
            <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
                <h1 class="govuk-fieldset__heading">
                    <?php echo $this->escapeHtml($this->translate('permits.page.permits.required.question')); ?>
                </h1>
            </legend>
            <div class="guidance-blue">
                <?php echo $this->translateReplace('permits.form.permits-required.fee.guidance', [$this->currencyFormatter($ecmtApplicationFee)]); ?>
            </div>
            <div class="govuk-form-group">
                <?php echo $this->form($form); ?>
            </div>
        </div>
    </div>
</div>
