<?php
    $title = $this->translate('permits.page.permits.required.title');
    $this->escapeHtml($this->headTitle($title));
?>

<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
            <p><?php echo $this->permitsBackLink(); ?></p>
            <div class="page-header__wrapper">
                <h3 class="page-header__subtitle"><?php echo $this->escapeHtml($ref); ?></h3>
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($this->translate('permits.page.permits.required.question')); ?>
                </h1>
            </div>
        </div>

        <div class="field">
            <div class="govuk-hint">
                <p><?php echo $this->escapeHtml($totalVehicles); ?></p>
            </div>

            <fieldset id="permits-required" class="inline" data-group="permits-required">
                <?php
                echo $this->formErrors($form);
                echo $this->form($form);
                ?>
            </fieldset>
        </div>

    </div>
</div>
