<?php
    $title = $this->translate('permits.page.title.restricted-countries');
    $this->headTitle($title);
?>

<div class="row ecmt">
    <div class="three-quarters">
        <div class="page-header">
            <p><a href="/permits" class="back-link"> <?php echo $this->translate('permits.back-link'); ?> </a></p>
            <div class="page-header__wrapper">
            </div>
        </div>

        <?php
            $form->setAttribute('action', $this->url('permits', array('action' => 'euro6-emissions')));
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));

            $element = $form->get('restrictedCountries');
            $options = $element->getOptions();
            $valueOptions = $options['value_options'];
        ?>

        <div class="field">
            <fieldset id="restricted-countries" class="inline" data-group="restricted-countries">
                <legend>
                    <div class="page-header__wrapper">
                        <h1 class="heading-medium">
                            <?php
                                //Print out Question Title using dynamic list of countries
                                $template = $this->escapeHtml($this->translate('permits.page.field.restricted-countries'));
                                echo sprintf($template, str_replace('%s', 'or', $restrictedCountriesString));
                            ?>
                        </h1>
                    </div>
                </legend>

                <?php echo $this->translate('markup-ecmt-restricted-countries'); ?>

                <label for="yes" class="block-label <?php echo $options['label_attributes']['class'];?> ">
                    <input id="yes" type="radio" name="<?php echo $element->getName();?>" value="1">
                    <?php echo $valueOptions['1'] ?>
                </label>

                <label for="no" class="block-label <?php echo $options['label_attributes']['class'];?> ">
                    <input id="no" type="radio" name="<?php echo $element->getName();?>" value="0">
                    <?php echo $valueOptions['0'] ?>
                </label>

                <fieldset id="restricted-countries-list" data-group="restricted-countries-list" class="guidance">
                    <p class="hint"><?php echo $this->escapeHtml($this->translate('permits.application.ecmt.select')); ?></p>
                    <?php echo $this->formRow($form->get('restrictedCountriesList')); ?>
                </fieldset>
            </fieldset>

            <fieldset class="actions-container new-application--wrapper">
                <p><?php echo $this->formSubmit($form->get('submit'));  ?></p>
                <p><a href="/permits"> <?php echo $this->translate('permits.button.save-return-to-permits'); ?> </a></p>
            </fieldset>
        </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
