<?php
    $title = $this->translate('permits.page.sector.title');
    $this->headTitle($title);
?>

<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
            <p><?php echo $this->permitsBackLink(); ?></p>
            <div class="page-header__wrapper">
                <h3 class="page-header__subtitle"><?php echo $this->escapeHtml($ref); ?></h3>
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($this->translate('permits.page.sector.question')); ?>
                </h1>
            </div>
        </div>

        <div class="field">
            <div class="govuk-hint">
            </div>

            <fieldset id="sector" class="inline" data-group="sector">
                <?php
                    echo $this->form($form);
                ?>
            </fieldset>
        </div>

    </div>
</div>
