<?php echo $this->permitsBackLink('common.link.back.label', isset($data['backUri']) ? $data['backUri'] : ''); ?>

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <?php echo $this->formErrors($form); ?>
        <?php if (isset($data['application']['applicationRef'])) { ?>
            <span class="govuk-caption-xl">
                <?php echo $this->escapeHtml($data['application']['applicationRef']); ?>
            </span>
        <?php } ?>

        <p><?php echo($data['application']['countryName']); ?></p>

        <?php echo $this->partial('partials/single-question-fieldset', ['data' => $data, 'form' => $form]); ?>

        <?php echo isset($data['cancelUri']) ? $this->permitsBackLink('cancel.button', $data['cancelUri']) : ''; ?>
    </div>
</div>
