<?php
    echo $this->permitsBackLink(
        isset($data['backLabel']) ? $data['backLabel'] : 'common.link.back.label',
        isset($data['backUri']) ? $data['backUri'] : '',
        isset($data['backUriParams']) ? $data['backUriParams'] : [],
        isset($data['backUriOptions']) ? $data['backUriOptions'] : []
    ); 
?>

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds js-body">
        <?php echo $this->formErrors($form); ?>
        <?php if (isset($data['application']['applicationRef'])) { ?>
            <span class="govuk-caption-xl">
                <span class="govuk-visually-hidden">
                    <?php echo($this->escapeHtml($this->translate('permits.application.overview.application.reference'))); ?>
                </span>
                <?php echo $this->escapeHtml($data['application']['applicationRef']); ?>
            </span>
        <?php } ?>

        <?php echo $this->partial('partials/single-question-fieldset', ['data' => $data, 'form' => $form]); ?>

        <p><?php echo isset($data['cancelUri']) ? $this->permitsBackLink('cancel.button', $data['cancelUri']) : ''; ?></p>
    </div>
</div>
