<?php $application = isset($data['application']) ? $data['application'] : $data['irhpApplication']; ?>
<?php echo $this->permitsBackLink('common.link.back.label', isset($data['backUri']) ? $data['backUri'] : ''); ?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <?php echo $this->formErrors($form); ?>
        <?php if (isset($application['applicationRef'])) { ?>
            <span class="govuk-caption-xl">
                <?php echo $this->escapeHtml($application['applicationRef']); ?>
            </span>
        <?php } ?>
        <fieldset class="govuk-fieldset">
            <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
                <h1 class="govuk-fieldset__heading">
                    <?php echo $this->translateReplace($data['question'], isset($data['questionArgs']) ? $data['questionArgs'] : []); ?>
                </h1>
            </legend>
            <?php if (isset($data['warning'])) {
                 echo $this->partial('partials/warning-component', ['translationKey' => $data['warning']]);
             }
             if (isset($data['details'])) {
                 echo $this->partial('partials/details-component', ['details' => $data['details']]);
             }
             if (isset($data['guidance'])) {
                 echo $this->partial('partials/guidance-blue-component', ['guidance' => $data['guidance']]);
             }
             if (isset($data['additionalGuidance'])) {
                 echo $this->partial('partials/additional-guidance-component', ['additionalGuidance' => $data['additionalGuidance']]);
             }
             if (isset($data['bulletList'])) { ?>
                <p class="govuk-body-l">
                    <?php echo $this->escapeHtml($this->translate($data['bulletList']['title'])); ?>:
                </p>
                <?php echo $this->partial($data['bulletList']['list']); ?>
            <?php } ?>
            <div class="govuk-form-group">
                <?php echo $this->form($form); ?>
            </div>
        </fieldset>
        <?php echo isset($data['cancelUri']) ? $this->permitsBackLink('cancel.button', $data['cancelUri']) : ''; ?>
    </div>
</div>
