<?php
    echo $this->permitsBackLink(
        'common.link.back.label',
        isset($data['backUri']) ? $data['backUri'] : '',
        isset($data['backUriParams']) ? $data['backUriParams'] : []
    );
?>

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <?php echo $this->formErrors($form); ?>

        <div class="govuk-caption-xl"><?php echo $this->escapeHtml($data['application']['countryName']); ?></div>

        <?php echo $this->partial('partials/single-question-fieldset', ['data' => $data, 'form' => $form]); ?>

        <p><?php echo isset($data['cancelUri']) ? $this->permitsBackLink('cancel.button', $data['cancelUri']) : ''; ?></p>
    </div>
</div>
