<?php
    $title = $this->translate($titleName);
    $this->headTitle($title);
?>

<div class="row ecmt">
    <div class="two-thirds">
        <?php echo sprintf($this->translate($partialName), $this->escapeHtml($title), $this->escapeHtml($data['application']['applicationRef'])); ?>
        <div class="actions-container new-application--wrapper">
            <p>
                <a href="<?php echo $this->escapeHtml($this->url('permits')); ?>" class="action--primary large">
                    <?php echo $this->escapeHtml($this->translate('Finish')); ?>
                </a>
            </p>
        </div>
    </div>
</div>
