<?php
$title = $this->translate('permits.page.number-of-trips.title');
$this->headTitle($title);
?>

<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
            <p><?php echo $this->permitsBackLink(); ?></p>
            <div class="page-header__wrapper">
                <h1 class="js-title">
                    <?php echo $this->translate('permits.page.number-of-trips.question'); ?>
                </h1>
            </div>
        </div>

        <div class="field">

            <fieldset id="number-of-trips" class="inline" data-group="number-of-trips">
                <?php
                echo $this->formErrors($form);
                echo $this->form($form);
                ?>

                <fieldset class="actions-container new-application--wrapper">
                    <p><?php echo $this->permitsBackLink('permits.button.save-return-to-overview'); ?></p>
                </fieldset>
            </fieldset>
        </div>

    </div>
</div>
