<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
            <p><?php echo $this->permitsBackLink(); ?></p>
        </div>
        <div class="guidance-grey">
            <p class=""><?php echo $this->escapeHtml('test '); ?></p>
        </div>
        <div class="field">
            <fieldset id="under-consideration" class="inline" data-group="under-consideration">
                <?php
                    echo $this->formErrors($form);
                    echo $this->form($form);
                ?>
            </fieldset>
        </div>
        <div class="govuk-hint">
            <p class=" guidance-blue extra-space large"><?php echo $this->escapeHtml('We will get back to you by '); ?>
            <b><?php echo $this->escapeHtml('30 November 2018'); ?></b></p>
        </div>
    </div>
</div>
