<?php

$title = $this->translate('permits.page.fee.title');
$this->headTitle($title);
$application = $data['application'];
$translationHelper = $this->getHelperPluginManager()->getServiceLocator()->get('Helper\Translation');
?>
<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
            <p><a href="<?php echo $this->url('permits') ?>" class="back-link"> <?php echo $this->escapeHtml($this->translate('common.link.back.label')); ?></a></p>
            <div class="page-header__wrapper">
                <div class="guidance pre-selected highlight-box">
                    <p><?php echo $this->escapeHtml($application['ref']); ?></p>
                    <h2><?php echo $translationHelper->translateReplace('permits.ecmt.page.valid.title', [$application['count']]); ?></h2>
                </div>
            </div>
        </div>
        <div class="field">
            <fieldset id="under-consideration" class="inline" data-group="under-consideration">
                <?php
                echo $tables['overview-valid-permits'];
                ?>
            </fieldset>
        </div>
        <p><a href="<?php echo $this->url('permits'); ?>"> <?php echo $this->escapeHtml($this->translate('permits.link.return.to.dashboard')); ?></a></p>
    </div>
    <?php
    echo $translationHelper->translateReplace(
            'markup-ecmt-permit-valid-permits-right-column',
            [
                $application['status'],
                date(\DATE_FORMAT, strtotime($application['irhpPermitStock']['validFrom'])),
                date(\DATE_FORMAT, strtotime($application['irhpPermitStock']['validTo']))
            ]
    );
    ?>
</div>
