<?php
    use Permits\View\Helper\EcmtSection;
?>

<div class="row ecmt">
    <div class="two-thirds">
        <div class="field">
            <fieldset id="under-consideration" class="inline" data-group="under-consideration">
                <?php echo $tables['overview-valid-permits'];?>
            </fieldset>
        </div>
    </div>


<!-- SIDE PANEL -->
    <div class="one-third">
        <aside class="sidebar" role="complementary">
            <div class="info-box info-box--grey">
                <h3 class="info-box__heading">Progress</h3>
                <p>You can't submit until you've completed all of the sections</p>
            </div>

            <div class="info-box info-box--grey">
                <h3 class="info-box__heading">Application status</h3>
                    <ul class="info-box__links">
                        <li>
                            <p>test</p>
                        </li>
                    </ul>
            </div>

        </aside>
    </div>
</div>
