<?php echo $this->permitsBackLink('common.link.back.label', 'permits'); ?>
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-xl">
            <?php echo $this->escapeHtml($this->translate('permits.application.window-closed')); ?>
        </h1>
        <?php echo $this->translateReplace(
            'markup-permits-window-closed',
            [
                $data['irhpPermitType']['name']['description'],
                date('d F Y', strtotime($data['lastOpenWindow']['lastOpenWindow'][0]['endDate']))
            ]
        ); ?>
    </div>
</div>
