<?php
    $title = $this->translate('permits.application.withdraw-confirmation');
    $this->headTitle($this->translate('permits.application.withdraw-confirmation.title'));
?>

<div class="govuk-width-container">
  <main class="govuk-main-wrapper govuk-main-wrapper--l" id="main-content" role="main">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <div class="govuk-panel govuk-panel--confirmation">
          <h1 class="govuk-panel__title">
            <?php echo $this->escapeHtml($title); ?>
          </h1>
          <div class="govuk-panel__body">
            <?php echo $this->escapeHtml($this->translate('permits.application.withdraw-confirmation.success')); ?>
            <br><strong><?php echo $this->escapeHtml($data['application']['applicationRef']); ?></strong>
          </div>
        </div>

        <?php echo $this->translate('markup-ecmt-withdraw-confirmation'); ?>

        <br />
        <br />

        <p><a href="<?php echo $this->url('permits'); ?>" class="action--primary large"><?php echo $this->escapeHtml($this->translate('permits.button.confirm-cancel-finish')); ?></a></p>
      </div>
    </div>
  </main>
</div>
