<?php

use Permits\View\Helper\EcmtSection;

    $title = $this->translate('permits.application.withdraw-application');
    $this->headTitle($this->translate('permits.application.withdraw-application.title'));
?>

<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
        <!-- Change to 'under consideration' page when that is complete. -->
        <p><?php echo $this->underConsiderationLink(EcmtSection::ROUTE_ECMT_UNDER_CONSIDERATION); ?></p>
            <div class="page-header__wrapper">
                <h3 class="page-header__subtitle"> <?php echo $this->escapeHtml($ref); ?></h3>
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($title); ?>
                </h1>
            </div>
        </div>

        <div class="field">
            <div class="govuk-hint">
                <?php echo $this->translate('markup-ecmt-application-withdraw'); ?>
            </div>

            <fieldset id="withdrawApplication" class="inline" data-group="withdrawApplication">
                <?php
                    echo $this->formErrors($form);
                    echo $this->form($form);
                ?>
            </fieldset>
        </div>
    </div>
</div>
