<?php
    $title = $this->translate('permits.application.withdraw-confirmation');
    $this->headTitle($this->translate('permits.application.withdraw-confirmation.title'));
?>

<div class="row ecmt">
    <div class="two-thirds">
        <div class="govuk-panel govuk-panel--confirmation">
            <h1 class="govuk-panel__title">
                <?php echo $this->escapeHtml($title); ?>
            </h1>
            <div class="govuk-panel__body">
                <?php echo $this->escapeHtml($this->translate('permits.application.withdraw-confirmation.success')); ?>
                <br><strong><?php echo $this->escapeHtml($data['application']['applicationRef']); ?></strong>
            </div>
        </div>

        <br />

        <div class="govuk-body">
            <?php echo $this->translate('markup-ecmt-withdraw-confirmation'); ?>
        </div>

        <div class="actions-container">
            <a href="<?php echo $this->url('permits'); ?>" class="action--primary large" role="button">
                <?php echo $this->escapeHtml($this->translate('permits.button.confirm-cancel-finish')); ?>
            </a>
        </div>
      </div>
</div>
