<?php

$feeStatusFormatter = new \Common\Service\Table\Formatter\FeeStatus();

echo $this->render(
    'partials/read-only/main',
    [
        'multiItems' => [
            [
                ['label' => 'Fee No:', 'value' => $invoiceNo, 'class' => 'full-width'],
                ['label' => 'Description:', 'value' => $description, 'class' => 'full-width'],
                [
                    'label' => 'Net amount',
                    'money' => $vatInfo ? $netAmount : null,
                    'class' => 'full-width',
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'VAT amount',
                    'money' => $vatInfo ? $vatAmount : null,
                    'class' => 'full-width',
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'VAT rate',
                    'value' => $vatInfo,
                    'class' => 'full-width',
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => $vatInfo ? 'Gross amount' : 'Fee amount:',
                    'money' => $amount,
                    'class' => 'full-width',
                ],
                ['label' => 'Outstanding:', 'money' => $outstanding, 'class' => 'full-width'],
                ['label' => 'Created:', 'date' => $created, 'class' => 'full-width'],
                [
                    'label' => 'Status:',
                    'noEscape' => true,
                    'value' => $feeStatusFormatter->format($fee),
                    'class' => 'full-width',
                ],
            ],
        ]
    ]
);

if ($table) {
    echo $table;
}

if ($form) {
    echo $this->form($form);
}
