<?php

echo $this->render(
    'partials/read-only/main',
    [
        'multiItems' => [
            [
                ['label' => 'No:', 'value' => $transaction['id'], 'class' => 'full-width'],
                ['label' => 'Date:', 'date' => $transaction['completedDate'], 'class' => 'full-width'],
                ['label' => 'Type:', 'value' => $transaction['type']['description'], 'class' => 'full-width'],
                ['label' => 'Method:', 'value' => $transaction['paymentMethod']['description'], 'class' => 'full-width'],
                ['label' => 'Reference:', 'value' => $transaction['reference'], 'class' => 'full-width'],
                ['label' => 'Processed by:', 'value' => $transaction['processedByUser']['loginId'], 'class' => 'full-width'],
                ['label' => 'Amount:', 'money' => $transaction['amount'], 'class' => 'full-width'],
                [
                    'label' => 'Status:',
                    'noEscape' => true,
                    'value' => \Common\Service\Table\Formatter\TransactionStatus::format($transaction),
                    'class' => 'full-width',
                ],
                [
                    'label' => 'Recommended by:',
                    'value' => isset($transaction['waiveRecommenderUser']['loginId'])
                        ? $transaction['waiveRecommenderUser']['loginId']
                        : '',
                    'hideIfEmpty' => true,
                    'class' => 'full-width',
                ],
                [
                    'label' => 'Comment:',
                    'value' => $transaction['comment'],
                    'hideIfEmpty' => true,
                    'class' => 'full-width',
                ],
            ],
        ]
    ]
);

if ($table) {
    echo $table;
}
?>
<div class="actions-container">
    <?php if ($reverseLink): ?>
        <a href="<?php echo $reverseLink; ?>" class="action--primary js-modal-ajax" target="_blank">Reverse payment</a>
    <?php endif; ?>
    <?php if ($receiptLink): ?>
        <a href="<?php echo $receiptLink; ?>" class="action--primary" target="_blank">Generate receipt</a>
    <?php endif; ?>
    <a href="<?php echo $backLink; ?>" class="action--secondary">Back</a>
</div>