<?php

echo $this->render(
    'partials/read-only/main',
    [
        'multiItems' => [
            [
                ['label' => 'Id:', 'value' => $transaction['id'], 'class' => 'full-width'],
                ['label' => 'Date:', 'date' => $transaction['completedDate'], 'class' => 'full-width'],
                ['label' => 'Type:', 'value' => $transaction['type']['description'], 'class' => 'full-width'],
                ['label' => 'Method:', 'value' => $transaction['paymentMethod']['description'], 'class' => 'full-width'],
                ['label' => 'Amount:', 'class' => 'full-width', 'value' => $transaction['displayAmount']],
                [
                    // @todo don't show for refunds
                    'label' => 'Previous payment:',
                    'class' => 'full-width',
                    'url' => "../".$transaction['previousTransactionId'],
                    'value' => $transaction['previousTransactionId'],
                    'hideIfEmpty' => true,
                ],
                ['label' => 'Reference:', 'value' => $transaction['reference'], 'class' => 'full-width'],
                [
                    'label' => 'Payer name:',
                    'value' => $transaction['payerName'],
                    'class' => 'full-width',
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'Slip No:',
                    'value' => $transaction['payingInSlipNumber'],
                    'class' => 'full-width',
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'Cheque/PO Number No:',
                    'value' => $transaction['chequePoNumber'],
                    'class' => 'full-width',
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'Cheque date:',
                    'date' => $transaction['chequePoDate'],
                    'dateFormat' => 'Y-m-d',
                    'class' => 'full-width',
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'Recommendation date:',
                    'date' => $transaction['waiveRecommendationDate'],
                    'class' => 'full-width',
                    'hideIfEmpty' => true,
                ],
                [
                    'label' => 'Recommend by:',
                    'value' => isset($transaction['waiveRecommenderUser']['loginId'])
                        ? $transaction['waiveRecommenderUser']['loginId']
                        : '',
                    'hideIfEmpty' => true,
                    'class' => 'full-width',
                ],
                ['label' => 'Processed by:', 'value' => $transaction['processedByUser']['loginId'], 'class' => 'full-width'],
                [
                    'label' => 'Comment:',
                    'value' => $transaction['comment'],
                    'hideIfEmpty' => true,
                    'class' => 'full-width',
                ],
                [
                    'label' => 'Status:',
                    'noEscape' => true,
                    'value' => \Common\Service\Table\Formatter\TransactionStatus::format($transaction),
                    'class' => 'full-width',
                ],
            ],
        ]
    ]
);

if ($table) {
    echo $table;
}
?>
<div class="actions-container">
    <?php if ($adjustLink): ?>
        <a href="<?php echo $adjustLink; ?>" class="action--primary js-modal-ajax" target="_blank">Adjust payment</a>
    <?php endif; ?>
    <?php if ($reverseLink): ?>
        <a href="<?php echo $reverseLink; ?>" class="action--primary js-modal-ajax" target="_blank">Reverse payment</a>
    <?php endif; ?>
    <?php if ($receiptLink): ?>
        <a href="<?php echo $receiptLink; ?>" class="action--primary" target="_blank">Generate receipt</a>
    <?php endif; ?>
    <a href="<?php echo $backLink; ?>" class="action--secondary">Back</a>
</div>