<thead>
    <tr>
        <th class="text-muted sortable" id="convictionNumber"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('conv-#'); ?></span></th>
        <th class="text-muted sortable" id="name"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('lookup-name'); ?>  /<br><?php echo $this->resourceHelper('def-type'); ?></span></th>
        <th class="text-muted sortable" id="dateOfOffence"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('doo'); ?></span></th>
        <th class="text-muted sortable" id="dateOfConviction"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('doc'); ?></span></th>
        <th class="text-muted sortable" id="description"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('conv-description'); ?></span></th>
        <th class="text-muted sortable" id="courtFpn"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('court/fpn'); ?></span></th>
        <th class="text-muted sortable" id="penalty"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('penalty'); ?></span></th>
        <th class="text-muted sortable" id="msi"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('msi'); ?></span></th>
        <th class="text-muted sortable" id="decToTc"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('dec-to-tc'); ?></span></th>
        <th class="text-muted"><span class="noWrap">Delete</span></th>
        <th class="text-muted"><span class="noWrap">Dealt with</span></th>
    </tr>
</thead>