<div class="row">  
    <div class="col-md-12 tListHeader tBorder2t">
        <div class="pheading"><?php echo $this->resourceHelper('lookup-search-results'); ?></div>
        <div id="searchTerm">
            <ul class="list-inline">
                <?php
                $fieldSet=Array("licenceNumber"=>"Licence Number",
                "operatorTradingName"=>"Operator/Trading Name",
                "town"=>"Town",
                "postcode"=>"Postcode");
                foreach($fieldSet as $key=>$field) {
                    if ( isset($_GET[$key])) {
                    if ( $_GET[$key] != "" ) {
                echo '<li><span class="text-muted">'.$field.': </span><span>'.htmlentities($_GET[$key]).'</span></li>';
                }
                }
                }
                ?>
            </ul>
        </div>
    </div>
</div>
<div  class="row">
        <div class="col-md-2 tBorder1r filter-bar tBgCol tBorder2t">
            <?php if (isset($partials['left-filters'])) echo $this->partial($partials['left-filters']['view'],  isset($partials['left-filters']['params']) ? $partials['left-filters']['params'] : array()); ?>
        </div>
        <div class="col-md-10 nopad">
            <?php echo $this->pagingView ?>
        <div class="clearfix"></div>
            <div class="tbl table-responsive tableContent">
                <table class="olcs-list-table table table-striped" data-base-url="<?php echo $baseUrl ?>"  data-url="<?php echo $ajaxUrl ?>">
                <?php echo $this->listHeaderView ?>
                <?php echo $this->listView ?>
            </table>
            </div>
        </div>
        <div class="col-md-2 tBorder2t"></div>
        <div class="col-md-10 nopad">
            <?php echo $this->pagingView ?>
        <div class="clearfix"></div>
</div>