<?php

echo $this->render('partials/read-only/main',
    [
        'multiItems' => [
            [
                ['label' => $this->translate('No:'), 'value' => $invoiceNo, 'class' => 'full-width'],
                ['label' => $this->translate('Description:'), 'value' => $description, 'class' => 'full-width'],
                ['label' => $this->translate('Amount:'), 'numeric' => $amount, 'class' => 'full-width'],
                ['label' => $this->translate('Created:'), 'date' => $created, 'class' => 'full-width'],
                ['label' => $this->translate('Status:'), 'value' => $status, 'class' => 'full-width'],
            ],
            [
                ['label' => $this->translate('Receipt No:'), 'value' => $receiptNo, 'class' => 'full-width'],
                ['label' => $this->translate('Amount received:'), 'numeric' => $receivedAmount, 'class' => 'full-width'],
                ['label' => $this->translate('Payment method:'), 'value' => $paymentMethod, 'class' => 'full-width'],
                ['label' => $this->translate('Processed by:'), 'value' => $processedBy, 'class' => 'full-width'],
            ]
        ]
    ]);
if ($form) {
    echo $this->form($form);
}
?>