<h3>Diogelu data</h3>

<p>Bydd y Comisiynydd Traffig neu Adran yr Amgylchedd Gogledd Iwerddon yn defnyddio eich gwybodaeth bersonol yn rhan o'u gwaith.</p>
<p>Gallant ei rhannu gyda'i gilydd a gyda:</p>
<ul>
    <li>Comisiynwyr Traffig eraill</li>
    <li>yr Adran Drafnidiaeth</li>
    <li>adrannau eraill y llywodraeth</li>
    <li>asiantaethau gorfodi</li>
</ul>
<p>Gallwch hefyd ei defnyddio i gysylltu â chi am ymchwil defnyddwyr.</p>
<p>Os ydych yn ymgeisio am drwydded safonol, mae'n ofyniad cyfreithiol i ni ychwanegu eich manylion i gofrestr genedlaethol.</p>

<h3>Cyfeiriadau IP</h3>

<p>Rydyn yn defnyddio cyfeiriadau IP i:</p>
<ul>
    <li>fonitro tueddiadau</li>
    <li>weld pa dudalennau mae defnyddwyr yn troi atynt</li>
    <li>ddysgu sut mae gwahanol adrannau o'r boblogaeth yn defnyddio'r safle</li>
</ul>
<p>Ni allwn ddefnyddio eich cyfeiriad IP i'ch adnabod chi'n bersonol.</p>

<h3>Cwcis</h3>

<p>Mae ein gwefan yn gosod ffeiliau bychan a elwir yn gwcis ar eich cyfrifiadur.</p>
<p>Mae cwcis yn casglu gwybodaeth am sut ydych chi'n pori'r safle. Fel cyfeiriadau IP, ni ellir eu defnyddio i’ch adnabod yn bersonol.</p>
<p>Rydym yn eu defnyddio i:</p>
<ul>
    <li>fesur sut ydych chi’n defnyddio’r safle er mwyn i ni allu ei ddiweddaru a gwella</li>
    <li>gofio hysbysiadau yr ydych wedi eu gweld fel nad ydym yn eu dangos i chi eto</li>
</ul>
<p>Dysgwch fwy am <a href="http://www.aboutcookies.org">sut i reoli cwcis</a>.</p>

<h4>Pa gwcis ydyn ni'n eu defnyddio?</h4>

<table>
    <tr>
        <th>Cwci</th>
        <th>Beth mae'n wneud</th>
        <th>Yn dod i ben</th>
    </tr>
    <tr>
        <td>Google Analytics</td>
        <td>Casglu gwybodaeth amdanoch chi a'r safle. <a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage">Darllenwch fwy am gwcis Google Analytics</a></td>
        <td>Gweler <a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage">Canllaw Google i ddefnydd o gwcis</a></td>
    </tr>
    <tr>
        <td>PHPSESSID</td>
        <td>Storio gwybodaeth dros dro rhwng tudalennau i helpu cyflymu eich pori</td>
        <td>Pan fyddwch yn cau eich porwr</td>
    </tr>
    <tr>
        <td>authZpath</td>
        <td>Yn eich anfon at weinyddwyr gwahanol yn ystod adegau prysur fel nad yw'r safle'n rhy araf i lwytho</td>
        <td>Pan fyddwch yn cau eich porwr</td>
    </tr>
    <tr>
        <td>secureAuthN a secureToken</td>
        <td>Storio gwybodaeth sylfaenol am eich manylion mewngofnodi</td>
        <td>Pan fyddwch yn cau eich porwr</td>
    </tr>
    <tr>
        <td>cookieSeen</td>
        <td>Yn rhoi gwybod i ni pa faneri a hysbysiadau naid ydych chi wedi eu gweld fel nad ydym yn eu dangos i chi eto</td>
        <td>Un mis</td>
    </tr>
    <tr>
        <td>langPref</td>
        <td>Yn dangos i ni os ydych yn darllen yn Gymraeg neu Saesneg</td>
        <td>Pan fyddwch chi'n clirio cwcis o'ch porwr</td>
    </tr>
</table>

<h3>Gwasanaethau'r Llywodraeth</h3>

<p>Mae'r rhan fwyaf o wasanaethau yr ydym yn cynnig dolenni iddynt yn cael eu rhedeg gan wahanol adrannau'r llywodraeth fel HMRC a'r Swyddfa Gartref.</p>
<p>Gall y gwasanaethau hyn osod cwcis eraill a bydd ganddynt eu polisïau cwcis eu hunain.</p>
