<h3>Deddfau</h3>
<p>Rheolir gweithredu cerbydau yn y DU gan Ddeddfau gan gynnwys:</p>
<ul>
    <li>Deddf Trwyddedu Gweithredu Cerbydau 1995</li>
    <li>Deddf Cerbydau  Cludo Teithwyr 1981 (diwygiedig)</li>
    <li>Deddf Cerbydau Nwyddau (Trwyddedu Gweithredwyr) (Gogledd Iwerddon) 2010 (diwygiedig)</li>
</ul>

<h3>Caniatâd</h3>
<p>
    Mae'r gwasanaeth hwn ar gyfer gweithredwyr a chynrychiolwyr sydd â chaniatâd i'w ddefnyddio  yn unig. Os na wyddoch
    os oes gennych chi ganiatâd anfonwch e-bost at
    <?php echo $this->partial('en_GB/markup-contact-email-link'); ?>.
</p>

<h3>Gofalu am eich cyfrinair ac enw defnyddiwr</h3>
<p>Er mwyn atal twyll ac i ddiogelu eich trwydded rhaid i chi ofalu am eich cyfrinair a'ch enw defnyddiwr.</p>
<p>Medrwch wneud hyn trwy:</p>
<ul>
    <li>gymryd camau rhesymol i'w cadw'n gyfrinachol</li>
    <li>peidio â gadael i unrhyw un arall eu defnyddio</li>
    <li>peidio â'u nodi heb geisio eu cuddio</li>
    <li>eu defnyddio pan ofynnir i chi wneud a'r pryd hynny yn unig</li>
</ul>
<p>
    Efallai byddwn yn gofyn am eich manylion mewngofnodi megis eich enw defnyddiwr, er mwyn eich adnabod, ond ni ddylai
    unrhyw un ofyn am eich cyfrinair. Peidiwch byth â'u ddatgelu yn llawn.
</p>

<h3>Camddefnydd o'ch gwybodaeth</h3>
<p>
    Os ydych yn meddwl bod gan rhywun arall eich gwybodaeth, neu ei fod yn cael ei gamddefnyddio, dylech newid eich
    cyfrinair ar unwaith ac anfon e-bost at
    <?php echo $this->partial('en_GB/markup-contact-email-link'); ?>.
</p>
<p>
    Nid ydych yn atebol am gam-ddefnydd o'ch cyfrinair neu eich enw defnyddiwr cyn i chi eu derbyn, neu wedi i chi
    ddweud wrthym eu bod yn cael eu camddefnydio.
</p>

<h3>Terfynu neu atal eich cyfrinair a'ch enw defnyddiwr</h3>
<p>
    Efallai byddwn yn terfynu neu'n atal eich hawl i ddefnyddio cyfrinair neu enw defnyddiwr ar unrhyw adeg. Oni bai ein
    bod yn teimlo bod angen gweithredu mewn brys, byddwn yn rhoi rhybudd o leiaf saith niwrnod ichi.
</p>
<p>Gallwn hefyd dynnu eich cyfrinair neu'ch enw defnyddiwr yn ôl:</p>
<ul>
    <li>
        os bu gormod o ymdrechion i fewngofnodi gan ddefnyddio cyfrinair neu enw defnyddiwr anghywir (e-bostiwch
        <?php echo $this->partial('en_GB/markup-contact-email-link'); ?> os digwydd hyn )
    </li>
    <li>os ydym yn teimlo bod angen gwneud hyn am resymau diogelwch</li>
    <li>i atal eich trwydded rhag camddefnydd</li>
    <li>os yw telerau'r defnydd wedi cael eu torri</li>
</ul>

<h3>Data nad oes gennych hawl i'w gyrchu</h3>
<p>
    Os dowch chi ar draws data nad oes gennych hawl i'w gyrchu rhowch wybod i ni ar unwaith trwy e-bostio
    <?php echo $this->partial('en_GB/markup-contact-email-link'); ?>.
</p>
<p>Mae defnyddio data rydych yn ei dderbyn ar ddamwain yn anghyfreithlon.</p>

<h3>Trafodion</h3>
<p>Efallai byddwn yn gwrthod gweithredu neu ddefnyddio trafodion os nad ydym yn sicr am y canlynol:</p>
<ul>
    <li>hunaniaeth neu awdurdod rhywun sydd yn ceisio eu defnyddio</li>
    <li>a yw'r trafodion yn gyfreithlon</li>
</ul>

<h3>Diogelu rhag firysau</h3>
<p>Gweler <?php echo $this->linkNewWindowExternal('https://www.gov.uk/help/terms-conditions', 'GOV.UK telerau ac amodau'); ?>.</p>

<h3>Gwybodaeth statudol</h3>
<p>
    Efallai byddwn yn cyhoeddi gwybodaeth statudol am eich cais am drwydded neu newidiadau i'r cais am drwydded ar ein
    gwefan.
</p>

<h3>Data</h3>
<p>
    Os ydych yn cymryd data o'r gwasanaeth, rhaid i chi ei gadw'n ddiogel a'i ddinistrio wedi i chi orffen ei
    ddefnyddio.
</p>
<p>
    Mae mynediad heb awdurdod i ddata yn anghyfreithlon ac yn drosedd dan Ddeddf Camddefnyddio Cyfrifiadur 1990. Gall
    arwain at erlyniad a /neu hawlio iawndal.
</p>

<h3>Defnyddio manylion eich cerdyn credyd neu ddebyd</h3>
<p>Ni fedrwn gymryd cyfrifoldeb os caiff eich taliad ei wrthod gan y cyflenwr cardiau.</p>
<p>Eich cyfrifoldeb chi yw sicrhau gwneud taliadau yn brydlon.</p>
<p>Rydym yn dal yr hawl i gymryd camau cyfreithiol yn erbyn pobl sydd yn twyllo neu yn ceisio twyllo ar-lein.</p>

<h3>Hyperlincio</h3>
<p>Gweler <?php echo $this->linkNewWindowExternal('https://www.gov.uk/help/terms-conditions', 'GOV.UK telerau ac amodau'); ?>.</p>

<h3>Diweddaru gwybodaeth</h3>
<p>Dan Ddeddf Diogelu Data 1998 gallwch ofyn i ni:</p>
<ul>
    <li>anfon copi atoch o'r wybodaeth bersonol sydd gennym amdanoch</li>
    <li>gywiro unrhyw fanylion sydd yn anghywir</li>
</ul>
<p>
    I wneud cais am gopi neu i wneud newidiadau, anfonwch e-bost at
    <?php echo $this->partial('en_GB/markup-contact-email-link'); ?>. Rydym yn codi tâl o £10 am y
    gwasanaeth hwn.
</p>

<h3>Gwybodaeth gywir a gonest</h3>
<p>
    Eich cyfrifoldeb chi yw sicrhau bod y manylion a gânt eu cyflwyno gennych chi, neu unrhyw un o weithwyr neu asiantau
    eich sefydliad, yn gywir ac yn onest.
</p>

<h3>Tynnu partneriaid, cyfarwyddwyr neu Reolwyr Trafnidaeth yn ôl</h3>
<p>
    Dylech dynnu yn ôl partner, cyfarwyddwr neu Reolwr Trafnidiaeth yn unig os nad ydynt bellach yn gysylltiedig â'r
    drwydded.
</p>

<h3>Atebolrwydd</h3>
<p>
    Nid ydych chi'n atebol am drafodion ar-lein ar eich trwyddedau nad ydych chi yn eu gweithredu, neu fynediad i neu
    ddefnydd o'r gwasanaeth gan rywun arall, oni bai:
</p>
<ul>
    <li>eich bod chi wedi awdurdodi'r trafodion, y mynediad i neu ddefnydd o'r gwasanaeth</li>
    <li>eich bod wedi twyllo neu weithredu yn esgeulus, sydd yn cynnwys peidio â diogelu eich cyfrinair</li>
</ul>
<p>
    Byddwn yn disgwyl i chi gyd-weithredu â'r heddlu os bydd ymchwiliad. Byddwn ninnau yn rhoi unrhyw wybodaeth i'r
    heddlu sydd, yn ein barn ni, yn berthnasol.
</p>

<h3>Rhyddid gwybodaeth</h3>
<p>
    Rydym yn atebol i Ddeddf Rhyddid Gwybodaeth 2000 ac mae'n bosibl y bydd gofyn inni ddatgelu gwybodaeth am y
    gwasanaeth os daw cais am hyn.
</p>
<p>
    Bydd yn rhaid i chi ein helpu i gydymffurfio â'r ceisiadau i ddatgelu gwybodaeth sydd yn gysylltiedig â gwasanaethau
    ar-lein neu eich trwydded os byddwn yn gofyn i chi wneud hynny.
</p>

<h3>Hawlildio a gorfodaeth </h3>
<p>Gweler <?php echo $this->linkNewWindowExternal('https://www.gov.uk/help/terms-conditions', 'GOV.UK telerau ac amodau'); ?>.</p>

<h3>Deddf sy'n gymwys </h3>
<p>Gweler <?php echo $this->linkNewWindowExternal('https://www.gov.uk/help/terms-conditions', 'GOV.UK telerau ac amodau'); ?>.</p>

<h3>Newidiadau</h3>
<p>
    Mae gennym yr hawl i newid y telerau hyn. Os byddwn yn gwneud newidiadau arwyddocaol i'r telerau byddwn yn rhoi
    gwybod i chi.
</p>
<p>
    Mae telerau newydd yn dod i rym unwaith maent wedi eu postio ar y safle. Os byddwch chi'n defnyddio'r safle wedi
    iddynt gael eu postio, rydych yn cytuno iddynt.
</p>

<h3>Aseiniad</h3>
<p>
    Rhaid i chi beidio, heb dderbyn ein caniatâd ysgrifenedig ymlaen llaw, ag aseinio, newid, isgontractio neu gael
    gwared ar neu fel arall ymdrin ag unrhwy un o'ch hawliau neu oblygiadau o dan y telerau hyn, nac unrhyw ran ohonynt.
</p>

<h3>Hawliau trydydd parti</h3>
<p>Ni ellir gorfodi'r hawliau yn y telerau hyn gan unrhyw un ar wahân i chi a ni.</p>

<h3>Cytundeb cyflawn</h3>
<p>
    Mae'r telerau hyn yn cynnwys y dealltwriaeth lawn a chyflawn rhwng y partïon sydd yn berthnasol i destun y telerau
    hyn, ac heblaw lle'r cyfeirir fel arall yn benodol yn y telerau hyn, maent yn disodli pob cyflwyniad, ysgrifeniadau,
    trafodaethau neu ddealltwriaethau blaenorol mewn perthynas â thestun y telerau hyn, gyda phob parti yn cytuno nad yw
    wedi dibynnu ar unrhyw gynrychiolaeth wrth gytuno â'r telerau defnydd amodau hyn.
</p>
<p>
    Fodd bynnag, nid oes unrhyw beth yn y cymal hwn fydd yn gweithredu i gyfyngu ar neu wahardd atebolrwydd mewn
    materion o dwyll.
</p>