<?php echo $this->render('partials/page-header.phtml', ['pageTitle' => 'Admin']); ?>
<div class="two-thirds">
<a href="<?php echo $this->url('admin-dashboard/admin-printing', [], [], true); ?>">
    <?php echo $this->translate('Printing'); ?>
</a><br />
<a href="<?php echo $this->url('admin-dashboard/admin-disc-printing', [], [], true); ?>">
    <?php echo $this->translate('Disc Printing'); ?>
</a><br />
<a href="<?php echo $this->url('admin-dashboard/admin-scanning', [], [], true); ?>">
    <?php echo $this->translate('Scanning'); ?>
</a><br />
<a href="<?php echo $this->url('admin-dashboard/admin-publication', [], [], true); ?>">
    <?php echo $this->translate('Publications'); ?>
</a><br />
<a href="<?php echo $this->url('admin-dashboard/admin-continuation', [], [], true); ?>">
    <?php echo $this->translate('Continuations'); ?>
</a><br />
<a href="<?php echo $this->url('admin-dashboard/admin-report', [], [], true); ?>">
    <?php echo $this->translate('Reports'); ?>
</a><br />
<a href="<?php echo $this->url('admin-dashboard/admin-user-management', [], [], true); ?>">
    <?php echo $this->translate('User management'); ?>
</a><br />
<a href="<?php echo $this->url('admin-dashboard/admin-financial-standing', [], [], true); ?>">
    <?php echo $this->translate('Financial standing rates'); ?>
</a><br />
<a href="<?php echo $this->url('admin-dashboard/admin-public-holiday', [], [], true); ?>">
    <?php echo $this->translate('Public holidays'); ?>
</a><br />
<a href="<?php echo $this->url('admin-dashboard/admin-system-message', [], [], true); ?>">
    <?php echo $this->translate('System messages'); ?>
</a><br />
</div>