<thead>
    <tr>
        <?php
        if (!isset($headers) && isset($tableHeaderParams)) {
            extract($tableHeaderParams);
        }

        $columnClasses = empty($columnClasses) ? array() : (array)$columnClasses;

        $position = 0;
        foreach ($headers as $key => $header) {
            if (!is_array($header)) {
                $header = array('title' => $header);
            }

            $columnAttributes = array(
                'class' => array('text-muted'),
            );
            if (!empty($header['sortable'])) {
                $columnAttributes['class'][] = 'columnSortable';
            }
            if (!empty($header['id'])) {
                $columnAttributes['id'] = $header['id'];
            } else if (!is_numeric($key)) {
                $columnAttributes['id'] = 'column-' . $key;
            }

            if (!empty($columnClasses[$key])) {
                $columnAttributes['class'][] = $columnClasses[$key];
            } else if (!empty($columnClasses[$position])) {
                $columnAttributes['class'][] = $columnClasses[$position];
            }

            $title = $this->resourceHelper($header['title']);
            if (empty($title)) {
                $title = $this->escapeHtml($header['title']);
            }
            ?>
            <th <?php echo $this->formatAttributes($columnAttributes); ?>>
                <span class="noWrap">
                    <?php
                    if (!empty($header['sortable'])) {
                        $dir = 'arrUp';
                        if (isset($sortColumn) && $sortColumn == $key) {
                            if ((isset($sortDir) && $sortDir == 'dn') || !empty($sortReversed)) {
                                $dir = 'arrDn';
                            }
                        }
                        ?><img src="/img/p.png" class="sprt sort-arrow <?php echo $dir; ?>" /><?php
                    }
                    echo $title;
                    ?>
                </span>
            </th>
            <?php
            $position += 1;
        }
        ?>
    </tr>
</thead>
