<tbody>
    <?php
    $columnClasses = empty($columnClasses) ? array() : (array)$columnClasses;

    if (!isset($rows) && isset($listData)) {
        $rows = $listData;
    }
    if (!$rows) {
        $rows = array();
    }

    foreach ($rows as $row) {
        if (isset($row[0])) {
            $row = array('columns' => $row);
        }

        $rowAttributes = array(
            'class' => empty($row['class']) ? array() : (array)$row['class'],
        );

        if (!empty($row['entity-id'])) {
            $rowAttributes['class'][] = 'entity-id-' . $row['entity-id'];
        }
        ?>
        <tr <?php echo $this->formatAttributes($rowAttributes); ?>>
            <?php
            foreach ($row['columns'] as $key => $column) {
                if (!is_array($column)) {
                    $column = array('value' => $column);
                }

                $columnAttributes = array('class' => array());

                if (!empty($column['attributes'])) {
                    $columnAttributes = array_merge($columnAttributes, $column['attributes']);
                }

                if (!empty($columnClasses[$key])) {
                    $columnAttributes['class'][] = $columnClasses[$key];
                }

                if ($column['value'] instanceof \DateTime) {
                    $value = $this->simpleDateFormat($column['value']);
                } else if (isset($column['escape']) && $column['escape'] == false) {
                    $value = $column['value'];
                } else {
                    $value = nl2br($this->escapeHtml($column['value']));
                }
                ?>
                <td <?php echo $this->formatAttributes($columnAttributes); ?>><?php echo $value; ?></td>
            <?php } ?>
        </tr>
    <?php } ?>
</tbody>
