<div class="row">  
    <div class="col-md-12 tListHeader tBorder2t">
        <div class="pheading pull-left"><h1><?php
            if (isset($headerParams)) {
                foreach ($headerParams as $key => $value) {
                    $headerParams[$key] = $this->escapeHtml($value);
                }
            }
            echo $this->resourceHelper($listHeader, isset($headerParams) ? $headerParams : null); 
        ?></h1></div>
        <div id="headingRight" class="pull-right" style="margin-bottom:20px">
            <?php if (isset($partials['topLeftButton'])) echo $this->partial($partials['topLeftButton']['view'],  isset($partials['topLeftButton']['params']) ? $partials['topLeftButton']['params'] : array()); ?>
        </div>
    </div>
</div>
<div  class="row">
        <div class="col-md-12 nopad">
            <?php echo $this->pagingView ?>
            <div class="table-responsive tableContent">
                <table class="clear-both olcs-list-table table table-striped" data-base-url="<?php echo $baseUrl ?>" data-url="<?php echo $ajaxUrl ?>">
                <?php echo $this->listHeaderView ?>
                <?php echo $this->listView ?>
            </table>
            </div>
        </div>
        <div class="col-md-12 nopad">
            <?php echo $this->pagingView ?>
        <div class="clearfix"></div>
</div>