<?php if (!is_null($subNav) && !empty((array)$subNav->getPages())) { ?>
<div class="one-quarter">
    <h4><?php echo $this->translate('In this section'); ?></h4>
    <?php
    echo $this->navigation('navigation')
        ->menu($subNav)
        ->setPartial('layout/partials/subNavigation');
    ?>
</div>
<div class="three-quarters">
<?php } else { ?>
<div class="full-width">
<?php } ?>
    <?php echo $this->flashMessengerAll(); ?>
    <?php echo $this->content; ?>
</div>