<?php

namespace Olcs\Service\Data;

use Common\Service\Data\AbstractData;
use Zend\ServiceManager\ServiceLocatorInterface;

/**
 * Class SubmissionSectionComment
 * @package Olcs\Service
 */
class SubmissionSectionComment extends AbstractData
{
    /**
     * @var integer
     */
    protected $id;

    /**
     * @var string
     */
    protected $serviceName = 'SubmissionSectionComment';

    /**
     * Submission service
     *
     * @var object
     */
    private $submissionService;

    /**
     * Submission section Configuration file
     *
     * @var array
     */
    private $submissionConfig;

    /**
     * Create SubmissionSectionComment service with injected ref data service
     *
     * @param ServiceLocatorInterface $serviceLocator
     * @return object SubmissionSectionComment
     */
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        parent::createService($serviceLocator);

        $submissionConfig = $serviceLocator->get('config')['submission_config'];
        $this->setSubmissionConfig($submissionConfig);

        $submissionService = $serviceLocator->get('Olcs\Service\Data\Submission');
        $this->setSubmissionService($submissionService);

        return $this;
    }


    /**
     * @return array
     */
    public function getBundle()
    {
        $bundle =  array(
            'properties' => 'ALL',
        );

        return $bundle;
    }

    /**
     * Generates an array of comments from the section data. Each comment is generated from the section data
     * generated by calling submissionService->createSubmissionSection
     *
     * @param integer $caseId
     * @param array $data
     * @return array $commentData
     */
    public function generateComments($caseId, $data)
    {
        $commentData = [];
        if (is_array($data['submissionSections']['sections'])) {
            $submissionConfig = $this->getSubmissionConfig();

            foreach ($data['submissionSections']['sections'] as $sectionId) {

                $sectionConfig = isset($submissionConfig['sections'][$sectionId]) ?
                    $submissionConfig['sections'][$sectionId] : [];

                // if section type is text, generate sectionData for comment
                if (in_array('text', $sectionConfig['section_type'])) {
                    $sectionData =
                        $this->getSubmissionService()->createSubmissionSection($caseId, $sectionId, $sectionConfig);
                    array_push(
                        $commentData,
                        [
                            'id' => '',
                            'submissionSection' => $sectionId,
                            'comment' => $this->getDefaultComment($sectionId, $sectionConfig, $sectionData),
                        ]
                    );
                }
            }
        }
        return $commentData;
    }

    /**
     * Returns an array of comments to 'add' and 'remove'. Pools existing comments for the submission and compares
     * against the new sections required for the update. Returns a pre-generated list of section comments to add
     * and those which to remove. Any existing section comments that are still required are left unchanged.
     *
     * @param integer $caseId
     * @param array $data
     * @return array of those to 'add' and 'remove'
     */
    public function updateComments($caseId, $data)
    {
        $commentDataToAdd = [];
        $commentDataToRemove = [];
        $commentDataToKeep = [];
        $submissionConfig = $this->getSubmissionConfig();
        $submission = $this->getSubmissionService()->fetchData($data['id']);
        $existingComments = $submission['submissionSectionComments'];

        // first remove any existing comments no longer required
        foreach ($existingComments as $comment) {
            if (!in_array($comment['submissionSection']['id'], $submissionConfig['mandatory-sections'])) {
                if (!in_array($comment['submissionSection']['id'], $data['submissionSections']['sections'])) {
                    // remove comment
                    $commentDataToRemove[] = $comment['id'];
                } else {
                    $commentDataToKeep[] = $comment['submissionSection']['id'];
                }
            }
        }

        if (is_array($data['submissionSections']['sections'])) {
            foreach ($data['submissionSections']['sections'] as $sectionId) {
                if (!in_array($sectionId, $submissionConfig['mandatory-sections'])) {

                    $sectionConfig = isset($submissionConfig['sections'][$sectionId]) ?
                        $submissionConfig['sections'][$sectionId] : [];

                    // if section type is text, generate sectionData for comment
                    if (in_array('text', $sectionConfig['section_type']) &&
                        !in_array($sectionId, $commentDataToKeep)
                    ) {
                        $sectionData =
                            $this->getSubmissionService()->createSubmissionSection($caseId, $sectionId, $sectionConfig);

                        array_push(
                            $commentDataToAdd,
                            [
                                'id' => '',
                                'submissionSection' => $sectionId,
                                'comment' => $this->getDefaultComment($sectionId, $sectionConfig, $sectionData),
                            ]
                        );
                    }
                }
            }
        }
        return ['add' => $commentDataToAdd, 'remove' => $commentDataToRemove];
    }

    /**
     * Generates the default comment when adding a new section. Generated from the data_field defined in
     * submission config.
     *
     * @param string $sectionId
     * @param array $sectionConfig
     * @param array $sectionData
     * @return string $defaultComment
     */
    private function getDefaultComment($sectionId, $sectionConfig, $sectionData)
    {
        if (!isset($sectionData['text'])) {
            $defaultComment = 'Placeholder for ' . $sectionId;
        } else {
            $defaultComment = $sectionData['text'];
        }
        return $defaultComment;
    }

    /**
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param array $submissionService
     */
    public function setSubmissionService($submissionService)
    {
        $this->submissionService = $submissionService;
        return $this;
    }

    /**
     * @return array
     */
    public function getSubmissionService()
    {
        return $this->submissionService;
    }

    /**
     * @param array $submissionConfig
     */
    public function setSubmissionConfig($submissionConfig)
    {
        $this->submissionConfig = $submissionConfig;
        return $this;
    }

    /**
     * @return array
     */
    public function getSubmissionConfig()
    {
        return $this->submissionConfig;
    }
}
