<p class="govuk-body">These cookies are essential in order to enable you to start using the service, move around the website and use its features. Without these cookies the services you would like to use cannot be provided.</p>
<p class="govuk-body">They always need to be on.</p>
<p class="govuk-body">
  <?php echo $this->link($this->url('cookies'), 'Find out more about cookies on Vehicle Operator Licensing service'); ?>.
</p>
