<div class="govuk-!-margin-top-7">
  <h2 class="govuk-heading-m">Data protection</h2>

  <p class="govuk-body">
    The Traffic Commissioner or Department for Infrastructure Northern Ireland will use your personal information as part of their work. They may share it with each other and:
  </p>

  <ul class="govuk-list govuk-list--bullet govuk-hint">
    <li>Other Traffic Commissioners</li>
    <li>The Department for Transport</li>
    <li>Other government departments</li>
    <li>Enforcement agencies</li>
  </ul>

  <p class="govuk-body">We may also use it to contact you about user research.</p>
  <p class="govuk-body">If you apply for a standard licence we’re legally required to add your details to a national register.</p>
  <div class="govuk-inset-text">
    <p class="govuk-body">We will share anonymised data with GOV.UK on how you used the site.</p>
  </div>
</div>
