<h3 class="govuk-heading-s">Laws</h3>

<p class="govuk-body">Operator licensing in the UK is covered by laws including:</p>

<ul class="govuk-list govuk-list--bullet">
  <li>the Goods Vehicle (Licensing of Operators) Act 1995</li>
  <li>the Public Passenger Vehicles Act 1981 (as amended)</li>
  <li>the Goods Vehicles (Licensing of Operators) Act (Northern Ireland) 2010 (as amended)</li>
</ul>

<h3 class="govuk-heading-s">Permission</h3>

<p class="govuk-body">This service is only for operators and representatives with permission to use it. If you don’t know whether you have permission email <?php echo $this->partial('en_GB/markup-contact-email-link'); ?>.</p>

<p class="govuk-body">The applicant or licence holder is responsible for managing access to the service. Any person seeking unauthorised access to the service may be prohibited from future access.</p>

<h3 class="govuk-heading-s">Representatives</h3>

<p class="govuk-body">If you are applying on behalf of an operator or applicant you must ensure that this is clear.</p>

<p class="govuk-body">You can do this by:</p>

<ul class="govuk-list govuk-list--bullet">
  <li>ensuring the user details are your details and not that of the applicant</li>
  <li>ensuring the user ID reflects your business eg ABConsultants, Xsolicitors</li>
  <li>the e-mail address must be your business e-mail</li>
</ul>

<p class="govuk-body">If you fail to comply with the above requirements or you impersonate the applicant, the user account may be terminated.</p>

<p class="govuk-body">The addresses for correspondence to the applicant or licence holder (including via Email) must be directed to the applicant / licence holder. Correspondence must not be directed to a representative’s address.</p>

<p class="govuk-body">Where a representative is found to have acted dishonestly, their rights to access the service may be removed for any current or future applicant or licence holder.</p>

<h3 class="govuk-heading-s">Care of your password and username</h3>

<p class="govuk-body">To stop fraud and protect your licence you must take care of your password and username.</p>

<p class="govuk-body">You can do this by:</p>

<ul class="govuk-list govuk-list--bullet">
  <li>taking reasonable steps to keep them secret</li>
  <li>not letting anyone else use them</li>
  <li>never writing them down without disguising them</li>
  <li>only entering them when you’re asked to</li>
</ul>

<p class="govuk-body">We may ask for login details like your username to identify you, but nobody should ask for your password. Never give it away in full.</p>

<h3 class="govuk-heading-s">Misuse of your information</h3>

<p class="govuk-body">If you think someone else has your information, or it’s being misused, change your password straight away and email <?php echo $this->partial('en_GB/markup-contact-email-link'); ?>.</p>

<p class="govuk-body">You aren’t liable for misuse of your password or username before you receive them, or after you’ve told us that they’re being misused.</p>

<h3 class="govuk-heading-s">We won’t tolerate inappropriate or abusive behaviour</h3>

<p class="govuk-body">No one should accept any abuse or inappropriate behaviour as part of their employment. Staff are encouraged to report all instances of abuse experienced - in whatever form - without hesitation. The actions of a few should not detract from the contribution and support provided to service users each day.</p>

<p class="govuk-body">Users of the VOL service may find their access terminated or suspended in full or in part, if the user, their agent or employee, is found to have abused any member of staff and/or a traffic commissioner.</p>

<h3 class="govuk-heading-s">Terminating or suspending your password and username</h3>

<p class="govuk-body">We may terminate or suspend your right to use a password or username at any time. Unless we feel more urgent action’s necessary, we’ll give you at least 7 days’ notice.</p>

<p class="govuk-body">We may also withdraw your password or username:</p>

<ul class="govuk-list govuk-list--bullet">
  <li>if there have been too many attempts to log in using an incorrect password or username (email <?php echo $this->partial('en_GB/markup-contact-email-link'); ?> if this happens)</li>
  <li>if we think it’s necessary for security reasons</li>
  <li>to stop your licence being misused</li>
  <li>if you use the system, or the information connected to the use of the system, in a manner that is likely to cause distress, upset, or to defame traffic commissioners or staff of the Office of the Traffic Commissioner</li>
  <li>if you have selected the incorrect user type, e.g. a transport consultant signs up as an Operator Administrator rather than as a Consultant Administrator</li>
  <li>the terms of use have been broken</li>
</ul>

<h3 class="govuk-heading-s">Data you’re not entitled to access</h3>

<p class="govuk-body">If you come across data that you’re not entitled to access let us know immediately by emailing <?php echo $this->partial('en_GB/markup-contact-email-link'); ?>.</p>

<p class="govuk-body">Using data you receive by mistake is illegal.</p>

<h3 class="govuk-heading-s">Transactions</h3>

<p class="govuk-body">We may refuse to carry out or allow transactions if we’re not sure about:</p>

<ul class="govuk-list govuk-list--bullet">
  <li>the identity or authority of anybody who tries to make them</li>
  <li>whether the transaction’s legal</li>
</ul>

<h3 class="govuk-heading-s">Virus protection</h3>

<p class="govuk-body">See the <a class="govuk-link" href="https://www.gov.uk/help/terms-conditions">GOV.UK terms and conditions</a>.</p>

<h3 class="govuk-heading-s">Statutory information</h3>

<p class="govuk-body">We may publish statutory information about your licence application or changes to it on our website.</p>

<h3 class="govuk-heading-s">Data</h3>

<p class="govuk-body">If you take any data from the service, you must keep it secure and destroy it when you’ve finished using it.</p>

<p class="govuk-body">Unauthorised access to data is illegal and may be an offence under the Computer Misuse Act 1990. It can lead to prosecution and/or claims for damages.</p>

<h3 class="govuk-heading-s">Use of your credit or debit card details</h3>

<p class="govuk-body">We can’t accept liability if your payment’s refused or declined by the card supplier.</p>

<p class="govuk-body">It’s your responsibility to make sure payments are made on time.</p>

<p class="govuk-body">We reserve the right to take legal action against people who commit or try to commit online fraud.</p>

<h3 class="govuk-heading-s">Hyperlinking</h3>

<p class="govuk-body">See the <a class="govuk-link" href="https://www.gov.uk/help/terms-conditions">GOV.UK terms and conditions</a>.</p>

<h3 class="govuk-heading-s">Updating information</h3>

<p class="govuk-body">Under the Data Protection Act 2018 you can ask us to:</p>

<ul class="govuk-list govuk-list--bullet">
  <li>send a copy of personal information we hold about you</li>
  <li>correct any inaccuracies</li>
</ul>

<p class="govuk-body">To request a copy or make changes email <?php echo $this->partial('en_GB/markup-contact-email-link'); ?>.</p>

<h3 class="govuk-heading-s">Accurate and truthful information</h3>

<p class="govuk-body">It’s your responsibility to make sure details submitted by you, or any of your organisation’s employees or agents are accurate and truthful.</p>

<h3 class="govuk-heading-s">Removing partners, directors or Transport Managers</h3>

<p class="govuk-body">You should only remove a partner, director or Transport Manager if they’re no longer associated with the licence.</p>

<h3 class="govuk-heading-s">Liability</h3>

<p class="govuk-body">You aren’t liable for online transactions on your licences that aren’t carried out by you, or for access to or use of the service by someone else, unless:</p>

<ul class="govuk-list govuk-list--bullet">
  <li>you authorised the transaction, access to or use of the service</li>
  <li>you acted fraudulently or negligently, which includes not protecting your password</li>
</ul>

<p class="govuk-body">We expect you to co-operate with the police if there’s an investigation. We’ll give the police any information that we think is relevant.</p>

<h3 class="govuk-heading-s">Freedom of information</h3>

<p class="govuk-body">We’re subject to the Freedom of Information Act 2000 and may have to reveal information about the service if there’s a request.</p>

<p class="govuk-body">You must help us comply with information disclosure requests linked to online services or your licence if we ask you to.</p>

<h3 class="govuk-heading-s">Waiver and enforceability</h3>

<p class="govuk-body">See the <a class="govuk-link" href="https://www.gov.uk/help/terms-conditions">GOV.UK terms and conditions</a>.</p>

<h3 class="govuk-heading-s">Applicable law</h3>

<p class="govuk-body">See the <a class="govuk-link" href="https://www.gov.uk/help/terms-conditions">GOV.UK terms and conditions <a>.</p>

<h3 class="govuk-heading-s">Changes</h3>

<p class="govuk-body">We have the right to change these terms. If we make significant changes to them we’ll let you know.</p>

<p class="govuk-body">New terms are effective once they’ve been posted on the site. If you use the site after they’ve been posted, you’re agreeing to them.</p>

<h3 class="govuk-heading-s">Assignment</h3>

<p class="govuk-body">Without written permission from us, you can’t assign, novate, sub-contract or dispose of or deal with your rights or obligations under these terms, or any part of them.</p>

<h3 class="govuk-heading-s">Rights of third parties</h3>

<p class="govuk-body">The rights in these terms can’t be enforced by anyone other than you and us.</p>

<h3 class="govuk-heading-s">Entire agreement</h3>

<p class="govuk-body">These terms of use constitute the entire understanding between the parties relating to the subject matter hereof and save as may be expressly referred to or referenced herein supersedes all prior representations, writings, negotiations or understandings with respect hereto, each party agreeing that it has not relied on any representation in entering into these terms of use.</p>

<p class="govuk-body">Nothing in this clause shall however operate to limit or exclude liability for fraud.</p>
