<div class="newspaper-advert info-box info-box--grey info-box--large-padding">
  <h3>Newspaper advert</h3>
  <p class="govuk-body">You must:</p>
  <ul class="govuk-list govuk-list--bullet">
    <li>make sure all details match the information in this licence application</li>
    <li>choose a newspaper that covers the area your operating centre is in</li>
    <li>upload/send us a copy of the full page on which your advert appears</li>
    <li>ensure the newspaper name and date of publication are legible on the copy you upload/send</li>
    <li>the date of publication must be in the period from 21 days before to 21 days after you submit your application</li>
    <li>use our <a class="govuk-link" title="download the advert template" href="%s" target="_blank">advert template (44kb) <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?></a></li>
  </ul>
  <div class="govuk-inset-text">
    <iframe width="560" height="315" src="{{YOUTUBE_EMBED_URL_OP_ADD_NEWSPAPER_ADVERT_GUIDANCE}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
  </div>
  <p class="info-box__text">
    <a class="govuk-link" href="%s" target="_blank">See our guidelines on how to advertise your application <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?></a>
  </p>
</div>
