<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary" aria-controls="certificate-abroad-text">
        <span class="govuk-details__summary-text">
            If you did not obtain your certificate in Great Britain
        </span>
    </summary>
    <div class="govuk-details__text" id="certificate-abroad-text">
       	You must also upload an original certificate of good repute or an equivalent document issued by the competent authority. This must include an English translation if it’s not in the English language.
    </div>
</details>
