<strong>I declare that:</strong>

<ul>
  <li>The statements made in this application are true. I understand that it is an
  offence to make a false declaration</li>

  <li>The applicant is the holder of the taxi or private hire vehicle licence(s)
  listed in this application. Every vehicle used under the special restricted
  PSV operator’s licence shall be one for which the applicant holds a taxi or
  private hire vehicle licence.</li>

  <li>No vehicle shall be used under the special restricted PSV operator’s licence
  otherwise than for the purpose of providing a local service with one or more
  stopping places within the area which granted the relevant licence for that
  vehicle.</li>
</ul>

