<div class="govuk-warning-text">
    <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
    <strong class="govuk-warning-text__text">
        <span class="govuk-warning-text__assistive">Warning</span>
        Since starting your application to surrender your licence, you have made changes to your licence information.
    </strong>
</div>

<p class="govuk-body">You need to review the information you previously provided.</p>
<p class="govuk-body">You must have your licence documents and vehicle discs to hand.</p>
<p class="govuk-body">During the application process you will need to destroy any documentation relating to this operator licence.</p>