<h3>Declare Convictions on an Operator’s Licence Application</h3>
<p>When applying for an operator’s licence the following must tell us about all convictions and penalties including any offences outside the UK:</p>
<ul>
    <li>Directors, Partners and Transport Managers</li>
    <li>companies that are (or have been) directed by anybody you’ve named</li>
    <li>your parent company, if you’re a limited company</li>
    <li>your employees and agents</li>
</ul>
<p>You should provide full details of the background circumstances of any convictions or penalties declared and it’s a <strong>criminal offence to make a false declaration.</strong></p>

<h3>Spent Convictions</h3>
<p>You do not have to declare convictions which are &ldquo;spent&rdquo; under the Rehabilitation of Offenders (Northern Ireland) Order 1978.</p>
<p>The details below show the rehabilitation period, at the end of which convictions will become spent. The rehabilitation period depends on the sentence for the original offence and runs from the date of conviction. The rehabilitation period for persons under the e age of 18 are halved.</p>
<p>A sentence of imprisonment for life or a sentence of imprisonment, detention in a Young Offenders Institution, a sentence of preventative detention or a sentence of detention during Her Majesty’s pleasure for terms exceeding 30 months are excluded from rehabilitation.</p>
<p>A sentence of imprisonment or corrective training for a term exceeding six months but not exceeding thirty months. The rehabilitation period is ten years.</p>
<p>A sentence of cashiering, discharge with ignominy or dismissal with disgrace from Her Majesty's service. The rehabilitation period is ten years.</p>
<p>A sentence of imprisonment for a term not exceeding six months. The rehabilitation period is seven years.</p>
<p>A sentence of dismissal from Her Majesty's service. The rehabilitation period is seven years.</p>
<p>Any sentence of detention in respect of a conviction in service disciplinary proceedings. The rehabilitation period is five years.</p>
<p>A fine or any other sentence subject to rehabilitation under this Order. The rehabilitation period is five years.</p>

<h3>Rehabilitation periods for certain sentences confined to young offenders</h3>
<p>A sentence of Borstal training. The rehabilitation period is Seven Years.</p>
<p>A custodial order under Schedule 5A to the Army Act 1955 or the Air Force Act 1955 or under Schedule 4A to the Naval Discipline Act 1957 where the maximum period of detention specified in the order is more than six months. The rehabilitation period is seven years.</p>
<p>A custodial order under section 71AA of the Army Act 1955 or the Air Force Act 1955, or under section 43AA of the Naval Discipline Act 1957, where the maximum period of detention specified in the order is more than six months. The rehabilitation period is seven years.</p>
<p>A sentence of detention for a term exceeding six months but not exceeding thirty months passed under Article 45 of the Criminal Justice (Children) (Northern Ireland) Order 19981. The rehabilitation period is five years.</p>
<p>A sentence of detention for a term not exceeding six months passed under that Article 45. The rehabilitation period is three years.</p>
<p>A custodial order under any of the Schedules to the said Acts of 1955 and 1957, where the maximum period of detention specified in the order is six months or less. The rehabilitation period is three years.</p>
<p>A custodial order under section 71AA of the said Acts of 1955, or section 43AA of the said Act of 1957, where the maximum period of detention specified in the order is six months or less. The rehabilitation period is three years.</p>
<p>A later conviction may affect the rehabilitation period for an earlier conviction if it happens before the first period has run out. If you are not sure whether your convictions are &ldquo;spent&rdquo;, you should declare it and the DfI will then consider each case on its merits.</p>
<p>You must inform the Department immediately of any penalties and convictions that occur between the date of you applying for a licence and a decision being made on your application. The Department will decide whether these are relevant to your application.</p>