<p>When you apply to open an operating centre, you must pay to advertise the application in a local newspaper and send a copy of the advert to us.</p>
<hr>
<h3>Template</h3>
<p>
    Write the advert using our <a class="govuk-link" href="{{PLACEHOLDER:ADVERT_TEMPLATE_LINK}}" target="_blank">advert template <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?></a>.
    Remember not to delete or change words on the template unless the instructions say you can.
</p>
<hr>
<h3>Deadline</h3>
<p>
    Your advert must appear in the period from 21 days before to 21 days after you've made your application, to give
    people the chance to object.
</p>
<hr>
<h3>Choosing a newspaper</h3>
<p>The newspaper has to:</p>
<ul>
    <li>be local, not regional or national</li>
    <li>cover the area where the operating centre's based</li>
    <li>carry stories as well as adverts – free sheets aren't suitable</li>
    <li>include other public notices like planning applications</li>
</ul>
<hr>
<h3>Proving you've published the advert</h3>
<p>
    Once it's been published, send the whole newspaper page containing your advert to us. Make sure your copy includes:
</p>
<ul>
    <li>the newspaper's full name</li>
    <li>the publication date</li>
</ul>
<hr>
<h3>Applying for more than one operating centre</h3>
<p>
    When you apply for more than one operating centre, you should publish separate adverts if they're in areas covered
    by different local newspapers.
</p>
<p>If they're in an area covered by the same local newspaper, one advert is enough. But it must include:</p>
<ul>
    <li>each operating centre's address</li>
    <li>the number of vehicles and trailers you'll be keeping at them</li>
</ul>