
<p>Because the Transport Manager doesn't have an email address.</p>
<div class="info-box info-box--large-padding info-box--grey">
    <h3>Next steps</h3>

    <p>You can apply by post if you cannot use the online service, but this may take longer.</p>

    <p>
        You must submit a TM1 form.
    </p>

    <p>If you live in England, Scotland or Wales, contact the Driver and Vehicle Standards Agency (DVSA) to request a form.</p>

    <address class="address-container">
        <p><strong>DVSA customer service centre</strong><br>
            Telephone: 0300 123 9000<br>
            Monday to Friday, 7:30am to 6pm<br>
            <?php
                echo $this->linkNewWindow(
                    $this->translate('call-charges-info-link'),
                    'Find out about call charges'
                );
            ?>
        </p>
    </address>

    <p>Contact the Transport Regulation Unit if you live in Northern Ireland.</p>

    <address class="address-container">
        <p><strong>Transport Regulation Unit</strong><br>
            Telephone: 0300 200 7831<br>
            Monday to Friday, 9am to 5pm<br>
            <?php
                echo $this->linkNewWindow(
                    $this->translate('call-charges-info-link'),
                    'Find out about call charges'
                );
            ?>
        </p>
    </address>

    <p>Send your completed form to the Office of the Traffic Commissioner. The address is on the form.</p>

</div>