<p class="govuk-body"><?php echo $this->escapeHtml($this->translate('permits.page.bilateral.essential.ukraine')); ?></p>
<p class="govuk-body">Each permit costs &pound;8.</p>
<p class="govuk-body"><?php echo $this->escapeHtml($this->translate('permits.page.bilateral.essential.ukraine.validity')); ?></p>
<ul class="govuk-list govuk-list--bullet">
  <li><?php echo $this->escapeHtml($this->translate('permits.page.bilateral.essential.ukraine.bullet-1')); ?></li>
  <li><?php echo $this->escapeHtml($this->translate('permits.page.bilateral.essential.ukraine.bullet-2')); ?></li>
  <li><?php echo $this->escapeHtml($this->translate('permits.page.bilateral.essential.ukraine.bullet-3')); ?></li>
</ul>
