<h2 class="govuk-heading-m">Security cookies</h2>

<p class="govuk-body">
  These are first party cookies set by a third party service that we use to protect our service. They help to identify malicious activity and protect data. They collect information in an anonymous form without storing any personal information.
</p>

<table class="govuk-table govuk-table--small-text-until-tablet">
  <thead class="govuk-table__head">
  <tr class="govuk-table__row">
    <th scope="col" class="govuk-table__header">Name</th>
    <th scope="col" class="govuk-table__header">Purpose</th>
    <th scope="col" class="govuk-table__header">Expires</th>
  </tr>
  </thead>
  <tbody class="govuk-table__body">
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">incap_ses_{ID}</td>
    <td class="govuk-table__cell">
      Used by the web application firewall to relate HTTP requests to a particular visit and to improve the security of the website, protecting it against attack
    </td>
    <td class="govuk-table__cell">When you close your browser</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">nlbi_{ID}</td>
    <td class="govuk-table__cell">
      Used by the delivery platform to ensure requests by a user are sent to the same origin server
    </td>
    <td class="govuk-table__cell">When you close your browser</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">visid_incap_{ID}</td>
    <td class="govuk-table__cell">
      Used to relate sessions to a specific visitor's device and is used by the web application firewall to improve the security of the website and protect it against attack
    </td>
    <td class="govuk-table__cell">1 year</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">_utmvm{ID}, _utmva, __utmvb{ID}</td>
    <td class="govuk-table__cell">
      These first party cookies are set by a third party service to filter out malicious requests
    </td>
    <td class="govuk-table__cell">15 minutes</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">__utmvc</td>
    <td class="govuk-table__cell">
      These first party cookies are set by a third party service to filter out malicious requests
    </td>
    <td class="govuk-table__cell">15 minutes</td>
  </tr>
  </tbody>
</table>
