<div class="govuk-phase-banner govuk-width-container">
  <p class="govuk-phase-banner__content">
    <span class="govuk-phase-banner__text">
      <a class="govuk-link" href="{{URL_SMART_SURVEY_IN_PAGE}}" rel="external noreferrer noopener" target="_blank">
        What did you think of this service? <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?>
      </a> (takes 30 seconds)
    </span>
  </p>
</div>

