<h3 class="govuk-heading-s">You need to provide a written explanation</h3>
<p class="govuk-body">You need to explain how your operation of small vehicles will meet the criteria of forming a ‘small part of the overall business’.</p>
<div class="govuk-inset-text">
  Section 79A of the Public Passenger Vehicles Act states that such vehicles do not need to be licenced as private hire vehicles “where the vehicle is being so provided or made available in the course of a business of carrying passengers by motor vehicles all but a small part of which involves the operation of large buses.”
</div>
<div class="govuk-form-group">
  <div>
    <p class="govuk-body">Your explanation should include the following:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>the nature of the use of the small vehicle(s) and of the large passenger vehicles </li>
      <li>your 12 month forecast and/or business plan including a monthly breakdown of planned income from both the small passenger vehicle(s) and the large passenger vehicles and the overheads/costs for each</li>
      <li>the planned mileage – please give separate figures for large and small vehicles</li>
      <li>the planned frequency of use – please give separate details of how often large and small vehicles will be used</li>
      <li>any other evidence you wish to include to show how use of small vehicles will only be a small part of your overall business</li>
    </ul>
  </div>
</div>
