<div class="info-box info-box--large-padding info-box--grey">
	<h3>Next steps</h3>
	<p class="info-box__text">We’ll send an online form to your Transport Manager at the address you provided.</p>
	<p class="info-box__text">We’ll let you know when they’ve submitted their details.</p>
	<p class="important info-box__text"> <strong>We can’t consider your application until a business director or owner has approved all your Transport Manager’s details.</strong>
</p>
</div>