<p class="govuk-body">
  To be granted a restricted licence you need to prove that the operation of the PSV will not be the licence holders’ main source of income.
</p>
<p class="govuk-body">
  You must submit evidence to demonstrate the applicants main occupation, as well as your plans for the operation of the PSV.
</p>
<ul class="govuk-list govuk-list--bullet">
  <li>All evidence must be for the entity that will hold the licence</li>
  <li>If a limited company or partnership, it is that entity that must demonstrate a main occupation, not the individuals involved</li>
</ul>
<p class="govuk-body"><?php echo $this->linkNewWindow($this->url('main-occupation-criteria-guidance'), 'Click here to see the evidence you need to provide to show you will comply with the main occupation criteria') ?>.</p>
