<!-- GB New application for PSV special restricted licence - PSV356 -->

<p>Section 12(1)(b) of the Transport Act 1985 (as amended) requires all
applicants for special restricted public service vehicle operators licences to
state in their application that they propose to provide a registered local bus
service. You are therefore making the following declaration when submitting
this application</p>

<p><strong>I confirm that I propose to use one or more licensed taxis or
private hire vehicles to provide a local service</strong></p>
