<div class="govuk-warning-text">
    <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
    <strong class="govuk-warning-text__text">
        <span class="govuk-warning-text__assistive">Warning</span>
        Your application to surrender your licence has expired.
    </strong>
</div>

<p class="govuk-body">The information you entered is no longer available.</p>
<p class="govuk-body">Start a new application.</p>
<p class="govuk-body">You must have your licence documents and vehicle discs to hand.</p>
<p class="govuk-body">During the application process you will need to destroy any documentation relating to this operator licence.</p>