<h2 class="govuk-heading-m govuk-!-margin-top-7">Cookies that measure website use</h2>

<h3 class="govuk-heading-s" id="messages-across-govuk">Google Analytics</h3>

<p class="govuk-body">
  We use Google Analytics software (Universal Analytics) to collect anonymised information about how you use this site.
  This helps us make sure the site is meeting the needs of its users and to improve the site and other government digital services.
</p>

<div class="govuk-inset-text">
  We do not allow Google to use or share the data about how you use this site.
</div>

<p class="govuk-body">Google Analytics stores information about:</p>

<ul class="govuk-list govuk-list--bullet govuk-hint">
  <li>How you got to the site</li>
  <li>The pages you visit within the service and how long you spend on them</li>
  <li>What you click on while using the service</li>
</ul>

<p class="govuk-body">Google Analytics sets the following cookies:</p>

<table class="govuk-table">
  <thead class="govuk-table__head">
  <tr class="govuk-table__row">
    <th scope="col" class="govuk-table__header">Name</th>
    <th scope="col" class="govuk-table__header">Purpose</th>
    <th scope="col" class="govuk-table__header">Expires</th>
  </tr>
  </thead>
  <tbody class="govuk-table__body">
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">_ga</td>
    <td class="govuk-table__cell">Used to count how many people visit the service by tracking if you’ve visited before</td>
    <td class="govuk-table__cell">2 years</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">_gid</td>
    <td class="govuk-table__cell">Used to anonymously identify a user</td>
    <td class="govuk-table__cell">24 hours</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">_gat</td>
    <td class="govuk-table__cell">Used to limit the requests to Google</td>
    <td class="govuk-table__cell">1 minute</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">__utmt</td>
    <td class="govuk-table__cell">Used to limit the requests to Google</td>
    <td class="govuk-table__cell">10 minutes</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">_gat_{ID}</td>
    <td class="govuk-table__cell">Used to limit the requests to Google</td>
    <td class="govuk-table__cell">1 minute</td>
  </tr>
  </tbody>
</table>
