<div class="info-box info-box--grey info-box--large-padding">
  <h3>The requirements for adding a Transport Manager when applying for a vehicle operator licence</h3>
  <p class="govuk-body">A quick explainer to help you understand the requirements when adding a Transport Manager to your vehicle operator licence application. Learn what to include, what to avoid, and how to get it right first time.</p>
  <div class="govuk-inset-text">
    <iframe width="560" height="315" src="{{YOUTUBE_EMBED_URL_TM_ADD_TRANSPORT_MANAGER_GUIDANCE}}" title="The requirements for adding a Transport Manager when applying for a vehicle operator licence" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
  </div>
</div>
