<p>Check that you've used the right web address.</p>
<p>If you think you've found a broken link email <?php echo $this->partial('en_GB/markup-contact-email-link'); ?></p>
<p>Let us know:</p>
<ul>
    <li>which page you were visiting</li>
    <li>what you were trying to do</li>
    <?php if (!empty($correlationId)): ?>
        <li>quoting reference <?php echo $this->escapeHtml($correlationId); ?></li>
    <?php endif; ?>
</ul>