<div class="govuk-!-margin-top-8">
  <nav class="govuk-footer__section" role="navigation" aria-labelledby="related-links-heading">
    <h2 class="govuk-heading-m" id="related-links-heading">Elsewhere on the web</h2>
    <ul class="govuk-list">
      <li>
        <a class="govuk-link"
           rel="external noreferrer noopener"
           target="_blank"
           rel="external noreferrer noopener"
           data-track-category="relatedLinkClicked"
           data-track-action="1.1 Elsewhere on the web"
           data-track-label="{{URL_INFORMATION_COMMISSIONER_COOKIE}}"
           data-track-options="{&quot;dimension28&quot;:&quot;1&quot;,&quot;dimension29&quot;:&quot;Information Commissioner's Office: cookies&quot;}"
           href="{{URL_INFORMATION_COMMISSIONER_COOKIE}}" target="_blank">
          Information Commissioner's Office: cookies <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?>
        </a>
      </li>
    </ul>
  </nav>
</div>
