<p class="govuk-body">
  You must provide further information to satisfy the traffic commissioner that a PSV licence is appropriate for the type of work you are wanting to do with your small vehicle(s). Please therefore provide the following:
</p>
<ul class="govuk-list govuk-list--bullet">
  <li>examples of the journeys you intend to operate</li>
  <li>full details of the journeys</li>
  <li>where exactly all the stops will be</li>
  <li>the full schedule of journeys, which days the service will run, which days the service will not run, each scheduled time period the journeys will run</li>
  <li>how they will be advertised, where they will be advertised, including an example of the advert / schedule, include any websites being used and screenshots of the adverts / schedule, include any publications or sites where the service will be advertised and schedules included</li>
  <li>full details of how the fares will be calculated</li>
  <li>full address and post code of the start and end of the journey</li>
</ul>
