<p>
    You are advised that you cannot lawfully operate goods vehicles with a gross plated weight exceeding 3.5 tonnes for
    the carriage of goods in connection with your trade or business or for hire or reward until your application has
    been granted, any relevant grant fee has been paid and the licence documents issued or until you have been issued
    with an interim licence. If you do so, and this is brought to the attention of the Traffic Commissioner you risk
    having your application refused.
</p>