<p><?php echo $this->escapeHtml($this->translate('licence_goods-trailers_trailer.form.add.longersemitrailer.undertakings')); ?></p>

<div class="govuk-warning-text">
    <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
    <strong class="govuk-warning-text__text">
        <span class="govuk-warning-text__assistive"><?php echo $this->escapeHtml($this->translate('govuk.warning.component.title')); ?></span>
        <?php echo $this->escapeHtml($this->translate('licence_goods-trailers_trailer.form.add.longersemitrailer.warning')); ?>
    </strong>
</div>
