<div class="govuk-width-container">

<div class="govuk-panel govuk-panel--confirmation">
  <h1 class="govuk-panel__title centered">
    Review and declarations
  </h1>

  <div class="govuk-panel__body">
    Declaration signed through {{SIGNING_SERVICE_NAME}}<br><strong>Signed by %s on %s</strong>
  </div>
</div>

<a href="%s" type="submit" role="button" draggable="false" data-module="govuk-button" class="govuk-button">
Finish
</a>

</div>
