<p class="govuk-body">
  To be granted a restricted licence, you need to provide evidence to satisfy the Traffic Commissioner that if granted a PSV operator licence, it will not become the applicants main occupation both in terms of time spent and income generated.
</p>

<h3 class="govuk-heading-m">The evidence you need to provide</h3>

<p class="govuk-body">
  All evidence supplied needs to be in the name of the entity applying for the licence.
</p>

<p class="govuk-body">
  You can find guidance on this page about the specific types of evidence you must provide for your particular business type.
</p>

<div class="govuk-accordion" data-module="govuk-accordion" id="accordion-legal-entity">

  <div class="govuk-accordion__section">
    <div class="govuk-accordion__section-header">
      <h2 class="govuk-accordion__section-heading">
        <span class="govuk-accordion__section-button" id="accordion-legal-entity-heading-1">
          If you have applied as a sole trader
        </span>
      </h2>
    </div>
    <div id="accordion-legal-entity-content-1" class="govuk-accordion__section-content">
      <h3 class="govuk-heading-s">Provide a written explanation and supporting documents addressing all of the following:</h3>
      <h3 class="govuk-heading-s">Your main occupation</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>What work you undertake other than the planned PSV operation – include all occupations other than the planned PSV operation.</li>
        <li>Whether you are self employed or an employee – if an employee, you must provide your employer’s details.</li>
        <li>If any other people work for you – if so, you must state how many and what work they usually do for you.</li>
        <li>You must provide any external evidence of your business which can demonstrate that operating PSVs is not your main occupation such as website, invoices, contracts etc.</li>
        <li>The figures for the typical monthly and yearly income you receive for each occupation that is not the PSV, generated over the last 12-18 months.</li>
        <li>Evidence of the income from your employment:
          <ul class="govuk-list govuk-list--number govuk-list--spaced">
            <li>If you are self employed, you should provide your latest self assessment tax return or audited accounts.</li>
            <li>If you are an employee, provide your latest P60 form and payslips for the past 3 months.</li>
          </ul>
        </li>
        <li>A detailed breakdown of the days and hours you usually carry out any occupation that is not the PSV operation.</li>
        <li>Details of the days and hours which you will not work on any occupation, including your planned PSV operation.</li>
      </ul>

      <h3 class="govuk-heading-s">Your plans for the PSV operation</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>What type of PSV work will be carried out (for example, contracts, ad hoc bookings, bus routes etc).</li>
        <li>How any fees that customers give you for the use of the PSV will be made (for example, single fares, group bookings, included in a fee for a wider service).</li>
        <li>How any fees/fares will be calculated.</li>
        <li>A detailed breakdown of the days and hours you plan to carry out the work needed to run your PSV operation safely, effectively and profitably.</li>
        <li>A copy of your business plan for the PSV operation – this should outline the following:
          <ul class="govuk-list govuk-list--number govuk-list--spaced">
            <li>The purpose of the business.</li>
            <li>Estimated income from the operation of the PSV for each month over the period of a year.</li>
            <li>Details of who will be driving for the operation.</li>
            <li>Details of the yearly estimated running costs of the PSV (including MOT, tax, insurance, cleaning, maintenance, repairs, fuel, wages and any other costs).</li>
          </ul>
        </li>
        <li>The full names of the people who will be driving the PSVs if known and a copy of both sides of their driving licence as evidence of their relevant driving category entitlement.</li>
      </ul>

      <h3 class="govuk-heading-s">Drivers hours and working time</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>If your main occupation involves driving you must provide details of how many hours you would spend driving in a typical week and a heavy week.</li>
        <li>How you will make sure that you/your drivers will be compliant with drivers hours/working time rules if your licence were granted.</li>
        <li>If you intend to be a driver, will the hours spent on your main occupation be reduced to accommodate the hours spent driving/operating your PSV – if so, you must tell us:
          <ul class="govuk-list govuk-list--number govuk-list--spaced">
            <li>What the new hours and days per week will be.</li>
            <li>What the new weekly/monthly/yearly income will be.</li>
          </ul>
        </li>
      </ul>
    </div>
  </div>

  <div class="govuk-accordion__section">
    <div class="govuk-accordion__section-header">
      <h2 class="govuk-accordion__section-heading">
        <span class="govuk-accordion__section-button" id="accordion-legal-entity-heading-2">
          If you have applied as a partnership
        </span>
      </h2>
    </div>
    <div id="accordion-legal-entity-content-2" class="govuk-accordion__section-content">
      <h3 class="govuk-heading-s">Provide a written explanation and supporting documents addressing all of the following:</h3>
      <h3 class="govuk-heading-s">The partnership’s main occupation</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>What work the partnership undertakes other than the planned PSV operation.</li>
        <li>If any other people work for your partnership - if so, you must state how many and what work they usually do for you.</li>
        <li>You must provide any external evidence of your business which can demonstrate that operating PSVs is not your main occupation such as website, invoices, contracts etc.</li>
        <li>Figures for the typical monthly and yearly income generated from the main occupation of the partnership over the last 12 – 18 months.</li>
        <li>Evidence of the income generated by the main occupation of the partnership (annual accounts, tax returns).</li>
        <li>A detailed breakdown of the days and hours the partnership carry out any occupation that is not the PSV operation.</li>
      </ul>
      <h3 class="govuk-heading-s">Your plans for the PSV operation</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>What type of PSV work will be carried out (such as contract work, ad hoc bookings, bus routes etc).</li>
        <li>How any fees that customers give you for the use of the PSV will be made (for example, single fares, group bookings, included in a fee for a wider service).</li>
        <li>How any fees/fares will be calculated.</li>
        <li>What day(s) each PSV vehicle will be used and for how many hours each day – you must give the maximum figures this could be in any given week.</li>
        <li>A detailed breakdown of the days and hours you plan to carry out the work needed to run your PSV operation safely, effectively and profitably.</li>
        <li>A copy of your business plan for the PSV operation – this should outline the following:
          <ul class="govuk-list govuk-list--number">
            <li>The purpose of the business.</li>
            <li>Estimated income from the operation of the PSV for each month over the period of a year.</li>
            <li>Details of who will be driving for the operation.</li>
            <li>Details of the yearly estimated running costs of the PSV (including MOT, tax, insurance, cleaning, maintenance, repairs, fuel, wages and any other costs).</li>
          </ul>
        </li>
        <li>The full names of the people who will be driving the PSVs if known and a copy of both sides of their driving licence as evidence of their relevant driving category entitlement.</li>
      </ul>
      <h3 class="govuk-heading-s">Drivers hours and working time</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>If the partnership’s main occupation involves driving you must provide details of how many hours you would spend driving in a typical week and a heavy week.</li>
        <li>How will you make sure that you/your drivers will be compliant with drivers hours/working time rules if your licence were granted.</li>
        <li>If any of the partners intend to be a driver, will the hours they spend on your main occupation be reduced to accommodate the hours spent driving/operating your PSV – if so, you must tell us:
          <ul class="govuk-list govuk-list--number govuk-list--spaced">
            <li>What the new hours and days per week will be.</li>
            <li>What the new weekly/monthly/yearly income will be.</li>
          </ul>
        </li>
      </ul>
    </div>
  </div>

  <div class="govuk-accordion__section">
    <div class="govuk-accordion__section-header">
      <h2 class="govuk-accordion__section-heading">
        <span class="govuk-accordion__section-button" id="accordion-legal-entity-heading-3">
          If you have applied as a limited company
        </span>
      </h2>
    </div>
    <div id="accordion-legal-entity-content-3" class="govuk-accordion__section-content">
      <h3 class="govuk-heading-s">Provide a written explanation and supporting documents addressing all of the following:</h3>
      <h3 class="govuk-heading-s">The limited company’s main occupation</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>What work the limited company undertakes other than the planned PSV operation.</li>
        <li>How many people work for your company and what work they usually do for you.</li>
        <li>A detailed breakdown of the days and hours the main occupation of your company is carried out.</li>
        <li>You must provide any external evidence of your business which can demonstrate that operating PSVs is not your main occupation such as website, invoices, contracts etc.</li>
        <li>Figures for the typical monthly and yearly income generated from the main occupation of the limited company over the last 12 – 18 months.</li>
        <li>Evidence of the income generated by the limited company (annual accounts, tax returns).</li>
      </ul>
      <h3 class="govuk-heading-s">Your plans for the PSV operation</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>What type of PSV work will be carried out (such as contract work, ad hoc bookings, bus routes etc).</li>
        <li>How any fees that customers give you for the use of the PSV will be made (for example, single fares, group bookings, included in a fee for a wider service).</li>
        <li>How any fees/fares will be calculated.</li>
        <li>What day(s) each PSV vehicle will be used and for how many hours each day – you must give the maximum figures this could be in any given week.</li>
        <li>A detailed breakdown of the days and hours you plan to carry out the work needed to run your PSV operation safely, effectively and profitably.</li>
        <li>A copy of your business plan for the PSV operation – this should outline the following:
          <ul class="govuk-list govuk-list--number govuk-list--spaced">
            <li>The purpose of the business.</li>
            <li>Estimated income from the operation of the PSV for each month over the period of a year.</li>
            <li>Details of who will be driving for the operation.</li>
            <li>Details of the yearly estimated running costs of the PSV (including MOT, tax, insurance, cleaning, maintenance, repairs, fuel, wages and any other costs).</li>
          </ul>
        </li>
        <li>The full names of the people who will be driving the PSVs if known and a copy of both sides of their driving licence as evidence of their relevant driving category entitlement.</li>
      </ul>
      <h3 class="govuk-heading-s">Drivers hours and working time</h3>
      <ul class="govuk-list govuk-list--bullet govuk-list--spaced">
        <li>If the limited company’s main occupation involves driving you must provide details of how many hours you would spend driving in a typical week and a heavy week.</li>
        <li>How will you make sure that you/your drivers will be compliant with drivers hours/working time rules if your licence were granted.</li>
        <li>If any of the company directors intend to be a driver, will the hours they spend on the limited company’s main occupation be reduced to accommodate the hours spent driving/operating your PSV – if so, you must tell us:
          <ul class="govuk-list govuk-list--number govuk-list--spaced">
            <li>What the new hours and days per week will be.</li>
            <li>What the new weekly/monthly/yearly income will be.</li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>
