<p class="govuk-body"><?php echo $this->escapeHtml($this->translate('permits.page.bilateral.essential.norway')); ?></p>
<h2 class="govuk-heading-s"><?php echo $this->escapeHtml($this->translate('permits.page.bilateral.essential.norway.heading2')); ?></h2>
<p class="govuk-body"><?php echo $this->escapeHtml($this->translate('permits.page.bilateral.essential.norway.text1')); ?></p>
<h2 class="govuk-heading-s"><?php echo $this->escapeHtml($this->translate('permits.page.bilateral.essential.norway.heading3')); ?></h2>
<p class="govuk-body"><?php echo $this->escapeHtml($this->translate('permits.page.bilateral.essential.norway.text2')); ?></p>
<p class="govuk-body"><?php echo $this->escapeHtml($this->translate('permits.page.bilateral.essential.norway.text3')); ?></p>
<?php echo $this->translate('markup-irhp-essential-information-cabotage'); ?>
<?php echo $this->partial('partials/irhp-bilateral-fee-table'); ?>
