<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary" aria-controls="details-content-average-balance">
        <span class="govuk-details__summary-text">
            Calculate your average balance
        </span>
    </summary>
    <div class="govuk-details__text" id="details-content-average-balance">
        Get your most recent closing balance, then go backwards in 10 day steps using the same dates on each month,
        to exactly 3 months earlier. This gives 10 figures, which are added and then divided by 10 to give the
        average balance.
    </div>
</details>