<h3>Additional information (optional)</h3>

<p>You can upload more details about your vehicle safety and maintenance arrangements below. You do not need to provide your maintenance contract(s). See <?php echo $this->linkNewWindowExternal('https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/321988/guide-to-maintaining-roadworthiness.pdf', 'the safe operator’s guide'); ?> for more information.</p>

<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary" aria-controls="details-content-safety-additional-documents">
        <span class="govuk-details__summary-text">
            Examples of additional information
        </span>
    </summary>
    <div class="govuk-details__text" id="details-content-safety-additional-documents">
        <ul class="govuk-list govuk-list--bullet">
            <li>Compliance reports</li>
            <li>Risk assessments</li>
            <li>Safety inspection records</li>
            <li>What systems you have in place for reporting defects</li>
            <li>What facilities you have for undertaking safety inspections (if relevant)</li>
        </ul>
    </div>
</details>