<p>
    Whilst your application is in progress, you are reminded that that you currently have no authority to operate any
    vehicles for hire or reward or any bus route, in any capacity, until you have been granted authority to do so, in
    writing, by the Traffic Commissioner.
</p>
<p>
    The determination of this application will depend on numerous factors which will be considered by the Traffic
    Commissioner, which will include, but not exclusively, the following;
</p>
<ul>
    <li>liaison with the relevant Local Authority (if appropriate), to verify any Taxi/PHV licence(s) issued;</li>
    <li>
        your response to any request(s) for additional documentation and/or information made by the Office of the
        Traffic Commissioner;
    </li>
</ul>