<div class="govuk-width-container">

<div class="govuk-panel govuk-panel--confirmation">
  <h1 class="govuk-panel__title centered">
    Awaiting operator review
  </h1>

  <div class="govuk-panel__body">
    Declaration signed through {{SIGNING_SERVICE_NAME}}<br><strong>Signed by %s on %s</strong>
  </div>

</div>

<h3 class="govuk-heading-m">What happens next?</h3>

<p class="govuk-body">
    You've submitted your details to the operator. We'll let you know once they've been reviewed.
</p>

<a href="%s" type="submit" role="button" draggable="false" data-module="govuk-button" class="govuk-button">
Finish
</a>

</div>
