<!-- NI New application for Goods licence - GV(NI)79 - restricted -->

<p><strong>I understand that by submitting this application I am accepting the undertakings
below; that they will be recorded on the licence; that failure to comply with
the conditions or undertakings recorded on the licence may result in the licence
being revoked, suspended or curtailed; and that failure to comply with these
conditions is a criminal offence.</strong></p>

<ul>
<?php echo $this->partial('en_GB/bullets/markup-undertakings-gvni-common'); ?>
</ul>
