<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary" aria-controls="details-content-operating-centre">
        <span class="govuk-details__summary-text">
            Help with vehicle authorisation
        </span>
    </summary>
    <div class="govuk-details__text" id="details-content-operating-centre">
        <p>Your total vehicle authorisation can't be:</p>
        <ul class="govuk-list govuk-list--bullet">
            <li>less than the largest operating centre</li>
            <li>more than the total across all centres</li>
        </ul>
        <p>There needs to be sufficient operating centre capacity to accommodate all your vehicles, including those not in use.</p>
    </div>
</details>
