<h2 class="govuk-heading-m govuk-!-margin-top-7">Strictly necessary cookies</h2>

<p class="govuk-body">
  When you use the ‘apply for a licence’ service, we’ll set a cookie to remember your progress through the forms. These cookies do not store your personal data and are deleted once you’ve completed the transaction.
</p>

<table class="govuk-table">
  <thead class="govuk-table__head">
  <tr class="govuk-table__row">
    <th scope="col" class="govuk-table__header">Name</th>
    <th scope="col" class="govuk-table__header">Purpose</th>
    <th scope="col" class="govuk-table__header">Expires</th>
  </tr>
  </thead>
  <tbody class="govuk-table__body">
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">PHPSESSID</td>
    <td class="govuk-table__cell">Stores temporary information between pages to speed up your browsing</td>
    <td class="govuk-table__cell">When you close your browser</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">secureToken</td>
    <td class="govuk-table__cell">Stores basic information about your login details</td>
    <td class="govuk-table__cell">When you close your browser</td>
  </tr>
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">cookies_policy</td>
    <td class="govuk-table__cell">Saves your cookie consent settings</td>
    <td class="govuk-table__cell">1 year</td>
  </tr>
  </tbody>
</table>
