<h2 class="govuk-heading-m govuk-!-margin-top-7">Cookies that remember your settings</h2>

<p class="govuk-body">
  These cookies do things like remember your preferences and the choices you make, to personalise your experience of using the service.
</p>

<table class="govuk-table">
  <thead class="govuk-table__head">
  <tr class="govuk-table__row">
    <th scope="col" class="govuk-table__header">Name</th>
    <th scope="col" class="govuk-table__header">Purpose</th>
    <th scope="col" class="govuk-table__header">Expires</th>
  </tr>
  </thead>
  <tbody class="govuk-table__body">
  <tr class="govuk-table__row">
    <td class="govuk-table__cell">langPref</td>
    <td class="govuk-table__cell">Used to store your current language preference (Welsh or English)</td>
    <td class="govuk-table__cell">10 years</td>
  </tr>
  </tbody>
</table>
