<p>
    Whilst your application is in progress, you are reminded that that you currently have no authority to operate any
    public service vehicles for hire or reward, in any capacity, until you have been granted authority to do so, in
    writing, by the Traffic Commissioner.
</p>
<p>
    The determination of this application will depend on numerous factors which will be considered by the Traffic
    Commissioner, which will include, but not exclusively, the following;
</p>
<ul>
    <li>whether or not statutory opposition has been received in response our Notices and Proceedings publication;</li>
    <li>
        your response to any request(s) for additional documentation and/or information made by the Office of the
        Traffic Commissioner;
    </li>
    <li>
        the results of any application related investigations e.g. in response to information received from an
        enforcement agency.
    </li>
</ul>