<!-- GB Goods Variation application involving an upgrade from restricted to standard
national/international - GV80A -->

<p><strong> I understand that by submitting this application I am accepting the additional
undertakings below; that they will be recorded on the licence; that failure to
comply with the conditions or undertakings recorded on the licence may result
in the licence being revoked, suspended or curtailed; and that failure to
comply with these conditions is a criminal offence.</strong></p>

<ul>
  <?php echo $this->partial('en_GB/bullets/markup-undertakings-gvni-supplemental'); ?>
</ul>