<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary" aria-controls="details-content-licence-type">
        <span class="govuk-details__summary-text">
            Read more about types of licence.
        </span>
    </summary>
    <div class="govuk-details__text" id="details-content-licence-type">

        <h3>Goods vehicles</h3>

        <p>Goods vehicles have either:</p>

        <ul class="govuk-list govuk-list--bullet">
            <li>a gross plated weight of more than 3,500kg</li>
            <li>an unladen weight of more than 1,525kg (where there’s no plated weight)</li>
        </ul>

        <p>Read more about <?php echo $this->linkNewWindow($this->translate('being-an-operator-link'), 'being a goods vehicle operator'); ?> and <?php echo $this->linkNewWindow($this->translate('vehicle-weights-link'), 'goods vehicle weights'); ?>.</p>

        <h3>Public service vehicles</h3>

        <p>Public service vehicles (PSVs) are either:</p>

        <ul class="govuk-list govuk-list--bullet">
            <li>vehicles used for hire or reward that can carry 9 or more passengers</li>
            <li>smaller vehicles used to carry passengers and charge them separate fares</li>
        </ul>

        <p>Read more about <?php echo $this->linkNewWindow($this->translate('public-services-link'), 'PSV operator licences'); ?>.</p>

        <h3>Other rules and exemptions</h3>

        <p>There are different <?php echo $this->linkNewWindow($this->translate('rules_in_ni_link'), 'rules in Northern Ireland'); ?>.</p>

        <p>Some types of vehicles don't need an operator's licence. Read more about <?php echo $this->linkNewWindow($this->translate('vehicle-exceptions'), 'exemptions'); ?>.</p>

    </div>

</details>