
<span id="typeOfLicence-hint-goods">
    <?php echo $this->linkNewWindowExternal('https://www.gov.uk/being-a-goods-vehicle-operator/types-of-licence', 'Read more about types of goods vehicle licence'); ?>.
</span>
<span class="govuk-visually-hidden"> or </span>
<span id="typeOfLicence-hint-psv">
    <?php echo $this->linkNewWindowExternal('https://www.gov.uk/being-a-goods-vehicle-operator/types-of-licence', 'Read more about types of public service vehicle licence'); ?>.
</span>
