<div class="article js-financial-history">
    <h3>Additional information</h3>
    <p class="form-hint">Give more information about any prior insolvency (min 150 characters).</p>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary" aria-controls="details-content-insolvency">
            <span class="govuk-details__summary-text">
                What we need to know:
            </span>
        </summary>
        <div class="govuk-details__text" id="details-content-insolvency">
            <ul class="govuk-list govuk-list--bullet">
                <li>how the insolvency came about</li>
                <li>when it happened</li>
                <li>who was involved</li>
                <li>which courts were involved</li>
                <li>which operator's licences were affected, if any</li>
                <li>any other information you think's relevant </li>
            </ul>
            <p class="field">You can also upload your:</p>
            <ul class="govuk-list govuk-list--bullet">
                <li>certificate of discharge from bankruptcy</li>
                <li>liquidator's report</li>
                <li>receiver's report</li>
                <li>administrator's report</li>
                <li>disqualification orders</li>
            </ul>
        </div>
    </details>
</div>