<div class="govuk-!-margin-top-7">
  <h2 class="govuk-heading-m">IP addresses</h2>

  <p class="govuk-body">
    Vehicle Operator Licensing collects IP addresses to track and aggregate non-personal information. For example, the service uses IP addresses to monitor trends, regions from which users navigate the website, and pages visited.
  </p>

  <div class="govuk-inset-text">
    <p class="govuk-body">
      We can’t use your IP address to identify you personally.
    </p>
  </div>
</div>
