<p class="govuk-body">Securely destroy:</p>
<ul class="govuk-list govuk-list--bullet">
    <li>all vehicle discs in your possession</li>
    <li>your licence document (and any copies)</li>
</ul>
<p class="govuk-body">Make sure that you destroy every document related to your operator licence. This is to make sure the information is not misused.</p>
<p class="govuk-body">Documents can be shredded or burned.</p>