<p>Your details have been confirmed by the operator.</p>

<p>If you haven't already, you need to:</p>

<ul>
    <li><strong><a class="govuk-link" href="%s" target="_blank">print out your details <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?></a></strong></li>
    <li>co-sign them with an owner or business director</li>
    <li>return them to the Central Licensing Office</li>
</ul>

<p>We'll let you know when we've received your details.</p>

<p class="important"><strong><?php echo $this->translate('lva.section.title.transport-manager-application.important') ?></strong></p>