<details  class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary" aria-controls="details-content-vehicle-auth">
        <span class="govuk-details__summary-text">
            About vehicle authorisation
        </span>
    </summary>
    <div class="govuk-details__text" id="details-content-vehicle-auth">
        <p>It is unlawful to hold a licence on which:</p>
        <ul class="govuk-list govuk-list--bullet">
            <li>There are fewer vehicles authorised than you keep at your largest operating centre.</li>
            <li>There are more vehicles authorised than you keep at all of your operating centres combined.</li>
        </ul>
        <p>You can authorise more vehicles on your licence than you plan to operate straight away. This is known as a margin for future expansion. You must include this margin in the total number of vehicles and trailers you want to authorise on your licence.</p>
    </div>
</details>