<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary" aria-controls="details-content-cabotage">
        <span class="govuk-details__summary-text"><?php echo $this->escapeHtml($this->translate('permits.page.bilateral.countries.essential.cabotage.heading')); ?></span>
    </summary>
    <div class="govuk-details__text" id="details-content-cabotage">
        <?php echo $this->escapeHtml($this->translate('permits.page.bilateral.countries.essential.cabotage.desc')); ?>
    </div>
</details>
