<div class="article">
    <p>Great Britain is divided into 8 traffic areas. Each area has a Traffic Commissioner who’s responsible for issuing
        licences. Northern Ireland has a separate system.</p>
    <p>Your operating licence needs to be valid for the area(s) in which your operating centre(s) are based. If you have
        operating centres in more than one traffic area, you will need a separate licence for each area.</p>
    <p>For Standard International licences where only Light goods vehicles are authorised, your operating licence needs
        to be valid for the area in which your address of establishment is based. If you have an address of
        establishment in more than one traffic area, you will need a separate licence for each area.</p>
    <h3>Which parts of the country do the traffic areas cover?</h3>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary" aria-controls="details-content-north-eastern">
            <span class="govuk-details__summary-text">
                North Eastern Traffic Area - Responsible for
            </span>
        </summary>
        <div class="govuk-details__text" id="details-content-north-eastern">
            <h4>The metropolitan boroughs within:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>South Yorkshire</li>
                <li>Tyne and Wear</li>
                <li>West Yorkshire</li>
            </ul>
            <h4>The counties of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Durham</li>
                <li>East Riding of Yorkshire</li>
                <li>Northumberland</li>
                <li>North Yorkshire</li>
                <li>Nottinghamshire</li>
            </ul>
            <h4>The districts of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>North East Lincolnshire</li>
                <li>North Lincolnshire</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                Office of the Traffic Commissioner<br/>
                Quarry House<br/>
                Leeds<br/>
                LS2 7UE
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary" aria-controls="details-content-north-western">
            <span class="govuk-details__summary-text">
                North Western Traffic Area - Responsible for
            </span>
        </summary>
        <div class="govuk-details__text" id="details-content-north-western">
            <h4>The metropolitan boroughs within:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Greater Manchester</li>
                <li>Merseyside</li>
            </ul>
            <h4>The counties of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Cheshire</li>
                <li>Cumbria</li>
                <li>Derbyshire</li>
                <li>Lancashire</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                Suit 4-6<br/>
                Stone Cross Place<br/>
                Stone Cross Lane<br/>
                Golborne<br/>
                Warrington<br/>
                WA3 2SH
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary" aria-controls="details-content-eastern">
            <span class="govuk-details__summary-text">
                Eastern Traffic Area - Responsible for
            </span>
        </summary>
        <div class="govuk-details__text" id="details-content-eastern">
            <h4>The counties of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Bedfordshire</li>
                <li>Buckinghamshire</li>
                <li>Cambridgeshire</li>
                <li>Essex</li>
                <li>Hertfordshire</li>
                <li>Leicestershire</li>
                <li>Lincolnshire (except the Districts of North Lincolnshire and North East Lincolnshire)</li>
                <li>Norfolk</li>
                <li>Northamptonshire</li>
                <li>Rutland</li>
                <li>Suffolk</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                Eastbrook<br/>
                Shaftesbury Road<br/>
                Cambridge<br/>
                CB2 8BF
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary" aria-controls="details-content-wales">
            <span class="govuk-details__summary-text">
                Ardal Traffig Cymru/Welsh Traffic Area - Cyfrifol am/Responsible for
            </span>
        </summary>
        <div class="govuk-details__text" id="details-content-wales">
            <ul class="govuk-list govuk-list--bullet">
                <li>Cymru/Wales</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                38 George Road<br/>
                Edgbaston<br/>
                Birmingham<br/>
                B15 1PL
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary" aria-controls="details-content-west-midlands">
            <span class="govuk-details__summary-text">
                West Midland Traffic Area - Responsible for
            </span>
        </summary>
        <div class="govuk-details__text" id="details-content-west-midlands">
            <h4>The metropolitan boroughs within the West Midlands.</h4>
            <h4>The counties of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Herefordshire</li>
                <li>Shropshire</li>
                <li>Staffordshire</li>
                <li>Warwickshire</li>
                <li>Worcestershire</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                38 George Road<br/>
                Edgbaston<br/>
                Birmingham<br/>
                B15 1PL
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary" aria-controls="details-content-western">
            <span class="govuk-details__summary-text">
                Western Traffic Area - Responsible for
            </span>
        </summary>
        <div class="govuk-details__text" id="details-content-western">
            <h4>The counties of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Berkshire</li>
                <li>Cornwall</li>
                <li>Devon</li>
                <li>Dorset</li>
                <li>Gloucestershire</li>
                <li>Hampshire</li>
                <li>Isle of Wight</li>
                <li>Oxfordshire</li>
                <li>Somerset</li>
                <li>Wiltshire</li>
            </ul>
            <h4>The districts of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Bath and North East Somerset</li>
                <li>Bristol</li>
                <li>North Somerset</li>
                <li>South Gloucestershire</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                Jubilee House<br/>
                Croydon Street<br/>
                Bristol<br/>
                BS5 0GB
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary" aria-controls="details-content-south-eastern">
            <span class="govuk-details__summary-text">
                South Eastern and Metropolitan Traffic Area - Responsible for
            </span>
        </summary>
        <div class="govuk-details__text" id="details-content-south-eastern">
            <ul class="govuk-list govuk-list--bullet">
                <li>Greater London</li>
            </ul>
            <h4>The counties of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Kent</li>
                <li>Surrey</li>
                <li>East Sussex</li>
                <li>West Sussex</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                Ivy House<br/>
                3 Ivy Terrace<br/>
                Eastbourne<br/>
                BN21 4QT
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary" aria-controls="details-content-scotland">
            <span class="govuk-details__summary-text">
                Scottish Traffic Area - Responsible for
            </span>
        </summary>
        <div class="govuk-details__text" id="details-content-scotland">
            <ul class="govuk-list govuk-list--bullet">
                <li>Scotland</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                Level 6<br/>
                The Stamp Office<br/>
                10 Waterloo Palace<br/>
                Edinburgh<br/>
                EH1 3EG
            </div>
        </div>
    </details>
</div>
