<p class="govuk-body">When applying for an operator’s licence you must tell us about all the relevant convictions and penalties relating to:</p>
<ul>
  <li>Directors, Partners and Transport Managers</li>
  <li>Companies that are (or have been) directed by anybody you’ve named</li>
  <li>your parent company, if you’re a limited company</li>
  <li>your employees and agents</li>
</ul>
<p class="govuk-body">You should provide full details of the background circumstances of any convictions or penalties declared and it’s a <strong>criminal offence to make a false declaration.</strong></p>

<h3>Spent Convictions</h3>
<p class="govuk-body">You don’t have to disclose convictions spent under the Rehabilitation of Offenders Act 1974. The table below shows the period, after which convictions don’t need to be disclosed. The rehabilitation period depends on the sentence for the original offence and runs from the date of conviction. The Police, Crime, Sentencing and Courts Act 2022 amends the rehabilitation period for England and Wales as follows:</p>

<table class="govuk-!-margin-bottom-5">
  <thead>
  <tr>
    <th rowspan="2">Where on a conviction the sentence (or equivalent) imposed is:</th>
    <th colspan="2">The rehabilitation period begins on conviction and lasts for:</th>
  </tr>
  <tr>
    <th>Adult</th>
    <th>Offenders Under 18</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>A custodial sentence of more than 4 years</td>
    <td>The end of the period of 7 years beginning with the day on which the sentence (including any licence period) is completed</td>
    <td>The end of the period of 42 months beginning with the day on which the sentence (including any licence period) is completed</td>
  </tr>
  <tr>
    <td>A custodial sentence more than 1 year and up to, or consisting of, 4 years</td>
    <td>The end of the period of 4 years beginning with the day on which the sentence (including any licence period) is completed</td>
    <td>The end of the period of 2 years beginning with the day on which the sentence (including any licence period) is completed</td>
  </tr>
  <tr>
    <td>A custodial sentence of 1 year or less</td>
    <td>The end of the period of 12 months beginning with the day on which the sentence (including any licence period) is completed</td>
    <td>The end of the period of 6 months beginning with the day on which the sentence (including any licence period) is completed</td>
  </tr>
  <tr>
    <td>A fine</td>
    <td>The end of 12 months beginning with the date of the relevant conviction</td>
    <td>The end of 6 months beginning with the date of the relevant conviction</td>
  </tr>
  <tr>
    <td>Compensation Order</td>
    <td colspan="2">The date on which the payment is made in full</td>
  </tr>
  <tr>
    <td>A relevant order (e.g. a community or youth rehabilitation order, Conditional Discharge, Bind over to keep the peace, Hospital Order, Supervision or Care Order, Disqualification, disability, prohibition or other penalty this list is not exhaustive)</td>
    <td colspan="2">The day provided for by or under the order as the last day on which the order is to have effect</td>
  </tr>
  </tbody>
</table>

<p class="govuk-body">The Management of Offenders (Scotland) Act 2019<a href="#1">[1]</a> sets the rehabilitation period for Scotland as follows:</p>

<table class="govuk-!-margin-bottom-5">
  <thead>
  <tr>
    <th rowspan="2">Where on a conviction the sentence (or equivalent) imposed is:</th>
    <th colspan="2">The rehabilitation period begins on conviction and lasts for:</th>
  </tr>
  <tr>
    <th>Adult</th>
    <th>Offenders Under 18</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>A custodial sentence of more than 30 months up to and consisting of, 48 months</td>
    <td>The term of the sentence plus 6 years</td>
    <td>The term of the sentence plus 3 years</td>
  </tr>
  <tr>
    <td>A custodial sentence more than 12 months and up to, or consisting of, 30 months</td>
    <td>The term of the sentence plus 4 years</td>
    <td>The term of the sentence plus 2 years</td>
  </tr>
  <tr>
    <td>A custodial sentence of 12 months or less</td>
    <td>The term of the sentence plus 2 years</td>
    <td>The term of the sentence plus 1 year</td>
  </tr>
  <tr>
    <td>A fine or compensation order</td>
    <td>12 months</td>
    <td>6 months</td>
  </tr>
  </tbody>
</table>

<p class="govuk-body"><a id="1">[1]</a> Due to be amended further by the Disclosure (Scotland) Act 2020 at a date in the future</p>

<p class="govuk-body">The convictions of corporate bodies are not subject to the Rehabilitation of Offenders Act 1974.</p>

<p class="govuk-body">A later conviction may affect the rehabilitation period for an earlier conviction if it happens before the first period has run out. If you are not sure whether your convictions are "spent", you should declare it and the traffic commissioner will then consider each case on its merits.</p>

<h3>Applicants for all licence types must declare:</h3>
<ul>
  <li>An offence under the Goods Vehicles (Licensing of Operators) Act 1995</li>
  <li>An offence under the Transport Act 1968 or the Road Traffic Act 1960 which relates to licences or means of identification</li>
  <li>An offence relating to section 13 of the Hydrocarbon Oil Duties Act 1979 (unlawful use of rebated fuel oil in relation to goods vehicles)</li>
  <li>An offence under Section 74 of the Road Traffic Act 1988 (duty to keep inspection records in relation to goods vehicles)</li>
  <li>An offence under section 53 of the Road Traffic Act 1988 (plating certificates and goods vehicle test certificates)</li>
  <li>An offence in relation to a goods vehicle relating to the maintenance of vehicles in a fit and serviceable condition</li>
  <li>An offence in relation to a goods vehicle relating to speed limits or overloading</li>
  <li>An offence in relation to a goods vehicle relating to the licensing of drivers</li>
  <li>A driver’s hours offence relating to a goods vehicle</li>
  <li>An offence under sections 173 or 174 of the Road Traffic Act 1988 (forgery, false statements or the withholding of information) in relation to an international road haulage permit</li>
  <li>An offence under section 2 of the International Road Haulage Permits Act 1975 (removing, causing, or permitting the removal of a goods vehicle or trailer from the UK in contravention of a prohibition)</li>
  <li>An offence under section 3 of the Control of Pollution Act 1974</li>
  <li>An offence under section 2 of the Refuse Disposal (Amenity) Act 1978</li>
  <li>An offence under section 1 of the Control of Pollution (Amendment) Act 1989</li>
  <li>An offence under section 33 of the Environmental Protection Act 1990</li>
  <li>An offence in relation to a goods vehicle in contravention of a provision prohibiting or restricting waiting vehicles made under the Road Traffic Regulation Act 1984 or a relevant traffic regulation order</li>
</ul>

<h3>Applicants for Standard National and Standard International licences must also declare:</h3>
<p class="govuk-body">Any conviction under the law of Northern Ireland or any country outside the United Kingdom which relates to the offences noted above for all applicants and any conviction where one or more of the following punishments was imposed: </p>
<ul>
  <li>Imprisonment exceeding 3 months</li>
  <li>A fine exceeding level 4 on the standard scale</li>
  <li>A community service order (or equivalent) requiring unpaid work for more than 60 hours</li>
  <li>Any punishment outside the UK corresponding to any of the above</li>
</ul>
<p class="govuk-body">Any conviction or penalty for an offence under UK law relating to road transport, or any corresponding offence outside the UK. In particular, but not limited to offences relating to:</p>
<ul>
  <li>Drivers’ hours of work and rest periods</li>
  <li>The weights and dimensions of commercial vehicles</li>
  <li>Road and vehicle safety</li>
</ul>
<p class="govuk-body">Any conviction or penalty for an offence under UK law relating to road transport, or any corresponding offence outside the UK. In particular:</p>
<ul>
  <li>Exceeding the maximum 6-day or fortnightly driving time limits by margins of 25 % or more.</li>
  <li>Exceeding, during a daily working period, the maximum daily driving time limit by a margin of 50 % or more without taking a break or without an uninterrupted rest period of at least 4.5 hours.</li>
  <li>Not having a tachograph and/or speed limiter, or using a fraudulent device able to modify the records of the recording equipment and/or the speed limiter or falsifying record sheets or data downloaded from the tachograph and/or the driver card.</li>
  <li>Driving without a valid roadworthiness certificate if such a document is required under Community law and/or driving with a very serious deficiency of, among other things, the braking system, the steering linkages, the wheels/tyres, the suspension or chassis that would create such an immediate risk to road safety that it leads to a decision to immobilise the vehicle.</li>
  <li>Transporting dangerous goods that are prohibited for transport or transporting such goods in a prohibited or non-approved means of containment or without identifying them on the vehicle as dangerous goods, thus endangering lives or the environment to such extent that it leads to a decision to immobilise the vehicle.</li>
  <li>Carrying passengers or goods without holding a valid driving licence or carrying by an undertaking not holding a valid Community licence.</li>
  <li>Driving with a driver card that has been falsified, or with a card of which the driver is not the holder, or which has been obtained on the basis of false declarations and/or forged documents.</li>
  <li>Carrying goods exceeding the maximum permissible laden mass by 20 % or more for vehicles the permissible laden weight of which exceeds 12 tonnes, and by 25 % or more for vehicles the permissible laden weight of which does not exceed 12 tonnes.</li>
</ul>

<h4>You must notify any convictions that occur between the date of you applying for a licence and a decision being made on your application.</h4>
