<p class="govuk-body">The application window for permits is closed.</p>
<p class="govuk-body">Any future application windows will be advertised.</p>
<p class="govuk-body">To keep yourself up to date we recommend that you visit the permits page on <a class="govuk-link" href="{{ECMT_PERMITS_GUIDANCE_LINK}}" target="_blank" rel="external noreferrer noopener">GOV.UK <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?></a>.</p>
