<div class="page-header">
    <div class="page-header__wrapper">
        <h1><?php echo $this->translate('search.title.vehicle'); ?></h1>
        <div class="page-header__text"><p><?php echo $this->translate('search.subtitle.vehicle'); ?></p></div>
    </div>
</div><!-- page-header -->

<div class="row">
  
  <div class="two-thirds">
      <?php echo $this->partial('search/form.phtml', ['form' => $this->searchForm]); ?>
  </div>
    
</div>
