<?php
echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->pageTitle(),
    ]
);
?>

<div class="row">

  <div class="two-thirds">
      <?php
        /* @var \Laminas\View\Helper\Navigation\Menu $menu */
        $menu = $this->navigation(
            $this->navigation('navigation')->getContainer()->findBy('id', 'search-bus-tabs')
        )->menu();

        echo $menu->setMinDepth(0)->setMaxDepth(0)->setPartial('partials/tabs-nav');

        echo $this->partial('search/form.phtml', ['form' => $this->searchForm]);
      ?>
  </div>

</div>