<div class="page-header">
    <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partials/breadcrumbs'); ?>
    <div class="page-header__wrapper">
        <h1><?php echo $this->pageTitle(); ?></h1>
        <div class="page-header__text"><p><?php echo $this->translate('search.subtitle.person'); ?></p></div>
    </div>
</div><!-- page-header -->
    
<div class="row">
  
  <div class="two-thirds">
      <?php echo $this->partial('search/form.phtml', ['form' => $this->searchForm]); ?>
  </div>
  
</div>
