<h1>IRHP Permits</h1>
<hr>
<div>
    <?php

    if (!isset($issuedPermitTable)) {
        $issuedPermitTable = $this->placeholder('table')->getValue();
    }

    if (!empty($issuedPermitTable)) {
        if (!empty($readonly)) {
            $issuedPermitTable->setDisabled(true);
        }
        echo $issuedPermitTable;
    }
    ?>
</div>
<hr>
<?php


if (!isset($table)) {
    $table = $this->placeholder('table')->getValue();
}

if (!empty($table)) {
    if (!empty($readonly)) {
        $table->setDisabled(true);
    }

    echo $table;
}
