<ul class="horizontal-navigation">
<?php foreach ($this->container as $page): ?>
    <li class="horizontal-navigation__item<?php if ($page->isActive(true)) { ?> current<?php } ?>">
    <?php if ($page->isActive()): ?>
    <span><?php echo $this->translate($page->getLabel()); ?></span>
    <?php else: ?>
    <?php echo $this->navigation()->menu()->htmlify($page) . PHP_EOL; ?>
    <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>