<?php
echo $this->render(
    'partials/page-header.phtml',
    array(
        'pageTitle' => 'Tables',
        'pageSubTitle'=> 'Standard styling for a range of complex tables and surrounding elements'
    )
);
?>
<div class="full-width">
    <a href="/case/<?php echo $licence; ?>/add">Add Case</a>
    <h2>Cases (<?php echo $count; ?> found)</h2>
    <div class="table__wrapper">
        <?php echo $table; ?>
    </div>
</div>
