<div class="page-header">
    <h1>OLCS FORM index page</h1>
    <div><?php
        $form->prepare();
//echo $this->form()->openTag($form);
        echo $this->form($form);
//echo $this->form()->closeTag($form);
        ?></div>
    <?php
    if (isset($results) && !empty($results)) {
        foreach ($results as $result)
        {
            print '<pre>';
            print_r($results);
            print '</pre>';
        }
    }
    ?>
</div>
