<?php
    echo $this->render(
        '/partials/page-header.phtml',
        array(
            'pageTitle' => 'Add case'
        )
    );
?>

<div class="two-thirds">
<?php
        $form->prepare();
//echo $this->form()->openTag($form);
        echo $this->form($form);
//echo $this->form()->closeTag($form);
        ?></div>
    <?php
    if (isset($results) && !empty($results)) {
        foreach ($results as $result)
        {
            print '<pre>';
            print_r($results);
            print '</pre>';
        }
    }
?>
</div><!-- end .three-quarters -->
