<!-- start progress -->
<div class="full-width">
    <ul class="app-navigation items-8" role="navigation" >
        <?php
            foreach($applicationProcess as $applicationItem) {
                echo $this->render(
                            'self-serve/journey/item.phtml',
                            $applicationItem
                );
            }
        ?>
    </ul>
</div>
<!-- end .progress -->
