<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Form elements', 'pageSubTitle'=> 'Includes form wrapper elements, labelling, inputs and actions')); ?>

<div class="one-quarter">
    <?php echo $this->render('partials/vertical-navigation.phtml', array('navItems' => array('Postal address', 'Personal information', 'About you'))); ?>
</div><!-- end .one-quarter -->

<div class="three-quarters">
    <?php
    echo $this->formErrors($this->form);

    echo $this->form($this->form);

    ?>
</div><!-- end .two-thirds -->