
<pre>
<?php

/**
 * DO NOT REMOVE THIS....
 *
 * This allows us to see the template locations where zend will search.
 */

/* $usrObject = $this;

echo print_r(get_class($usrObject), 1) . PHP_EOL;

echo print_r(get_class_methods($usrObject), 1);

echo get_class($usrObject->resolver()->getIterator());

echo print_r($usrObject->resolver()->getIterator(), 1);

die(); */

?>

</pre>


<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Home')); ?>
<div class="two-thirds">
    <a href="/search">Search</a>
</div>

<div>
    <?php echo $this->table ?>
</div>
