
<pre>
<?php

/**
 * DO NOT REMOVE THIS....
 *
 * This allows us to see the template locations where zend will search.
 */

/* $usrObject = $this;

echo print_r(get_class($usrObject), 1) . PHP_EOL;

echo print_r(get_class_methods($usrObject), 1);

echo get_class($usrObject->resolver()->getIterator());

echo print_r($usrObject->resolver()->getIterator(), 1);

die(); */

?>
</pre>


<div class="two-thirds">
    <a href="/search">Search</a>
</div>
