<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'OLCS Styleguide', 'pageSubTitle'=> 'A living and evolving frontend styleguide for OLCS applications')); ?>

	<div class="one-third">
		<h4><a href="styleguide/typography">Typography</a></h4>
		<p>A typographic system based on the Alphagov toolkit</p>
	</div><!-- end .one-third -->

	<div class="one-third">
		<h4><a href="styleguide/layouts">Layouts</a></h4>
		<p>A simple grid system for laying out pages</p>
	</div><!-- end .one-third -->

	<div class="one-third">
		<h4><a href="styleguide/form-elements">Form elements</a></h4>
		<p>Includes form wrapper elements, labelling, inputs and actions</p>
	</div><!-- end .one-third -->

	<div class="one-third">
		<h4><a href="styleguide/navigation-elements">Navigation elements</a></h4>
		<p>Includes a standard set of vertical and horizontal navigation mechanisms</p>
	</div><!-- end .one-third -->

	<div class="one-third">
		<h4><a href="styleguide/modal-windows">Modal windows</a></h4>
		<p>Includes JavaScript and none-JavaScript versions of pop-ups and alerts</p>
	</div><!-- end .one-third -->

	<div class="one-third">
		<h4><a href="styleguide/tables">Tables</a></h4>
		<p>Standard styling for a range of complex tables and surrounding elements</p>
	</div><!-- end .one-third -->

	<div class="one-third">
		<h3>Naming conventions</h3>
		<p>We have used <a href="http://bem.info/method/">BEM</a> as a methodology for naming and classifying CSS selectors, in order to make them more strict, efficient and informative. <a href="http://csswizardry.com/2011/09/writing-efficient-css-selectors/">Over-qualified</a> selectors and excessive wrappers elements should be avoided.</p>
	</div><!-- end .one-third -->

	<div class="one-third">
		<h3>Alphagov</h3>
		<p>The primary SASS file (main.scss) has a dependency on various functions, variables &amp; mixins within the <a href="https://github.com/alphagov/govuk_frontend_toolkit">Alphagov frontend toolkit</a>. This toolkit should never be edited and should be updated with extreme caution. </p>
	</div><!-- .end one-third -->

	<div class="one-third">
		<h3>Requirements</h3>
		<ul>
			<li><a href="http://sass-lang.com/">Sass 3.3.3 (Maptastic Maple)</a></li>
			<li><a href="http://nodejs.org/">Node v0.10.26</a></li>
		</ul>
	</div><!-- end .one-third -->