<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Layouts', 'pageSubTitle'=> 'A simple grid system for laying out pages')); ?>


		<!-- Standard layout -->
		<div class="one-quarter"></div><!-- end .one-quarter -->
		<div class="three-quarters"></div><!-- end .quarters -->

		<!-- Standard layout -->
		<div class="one-third"></div><!-- end .one-third -->
		<div class="two-thirds"></div><!-- end .two-thirds -->

		<!-- Full width layout -->
		<div class="full-width"></div><!-- end .full-width -->

		<!-- Three column layout -->
		<div class="one-third"></div><!-- end .one-third -->
		<div class="one-third"></div><!-- end .one-third -->
		<div class="one-third"></div><!-- end .one-third -->

		<!-- Reversed standard layout -->
		<div class="two-thirds"></div><!-- end .two-third -->
		<div class="one-third"></div><!-- end .one-third -->
		
		<!-- Split layout -->
		<div class="one-half"></div><!-- end .one-half -->
		<div class="one-half"></div><!-- end .one-half -->

