<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Modal windows')); ?>
				<div class="full-width">
					<ul>
						<li>
							<h4><a href="popup-form-no-js">Popup form no-js</a></4>
						</li>
						<li>
							<h4><a href="popup-form">Popup form</a></h4>
						</li>
						<li>
							<h4><a href="popup-table-no-js">Popup table no-js</a></h4>
						</li>
						<li>
							<h4><a href="popup-table">Popup table</a></h4>
						</li>
						<li>
							<h4><a href="alert">Alert</a></h4>
						</li>
						<li>
							<h4><a href="alert-warning">Alert warning</a></h4>
						</li>
					</ul>
				</div><!-- end .full-width-->
