<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Add operating centre')); ?>

<div class="full-width">
	<form>

		<!-- Operating centre address -->
		<fieldset id="operating_centre_address">
			<legend>Address</legend>
			<div class="field">
				<label for="operating-address">Select from an existing address</label>
				<select id="operating-address" name="operating-address">
					<option value="new">23 Ashburton Grove</option>
					<option value="23-ashburton-grove">23 Ashburton Grove</option>
					<option value="155-beeston-industrial-estate">155 Beeston Industrial Estate</option>
				</select>
			</div>
				<div class="field">
					<label for="address-line-one">Address line 1</label>
	    			<input id="address-line-one" name="address" type="text" class="long">
				</div>
				<div class="field">
					<label for="address-line-two">Address line 2</label>
	    			<input id="address-line-two" name="address" type="text" class="long">
				</div>
				<div class="field">
					<label for="town-city">Town/city</label>
	    			<input id="town-city" name="town-city" type="text" class="long">
				</div>
				<div class="field">
					<label for="postcode">Postcode</label>
	    			<input id="postcode" type="text" name="postcode" class="short">
				</div>
		</fieldset><!-- end operating_centre_address -->

		<!-- Vehicles and trailers -->
		<fieldset id="vehicles_and_trailers">
			<legend>Vehicles and trailers</legend>
			<div class="field">
	            <label for="address-vehicles">Total no. of vehicles at this address</label>
	            <input class="short" id="address-vehicles" name="address-vehicles" placeholder="" type="text" value="">
	        </div>
	        <div class="field">
	            <label for="no-of-trailers">Total no. of trailers at this address</label>
	            <input class="short" id="address-trailers" name="address-trailers" placeholder="" type="text" value="">
	        </div>
	       	<fieldset>
		        <div class="field inline">
		        	<label for="enough-spaces"><input type="checkbox" id="enough-spaces">
		        	By selecting this box you confirm that you have enough parking spaces for the total
		        	number of vehicles and trailer that you want to keep at this address.
		        	</label>
		        </div>
	        </fieldset>
	        <fieldset>
	        	<legend>Do you have permission from the site owner to use the premises to park the number of vehicles and trailers stated</legend>
		        <div class="field inline">
					<label><input type="radio" name="permission" checked>Yes</label>
				</div>
				<div class="field inline">
					<label><input type="radio" name="permission">No</label>
				</div>
			</fieldset>
		</fieldset><!-- end vehicles_and_trailers -->

		<fieldset id="advertisements">
			<legend>Advertisements</legend>	
			<fieldset>
	        	<legend>Have you advertised your application in the local newspaper?</legend>
		        <div class="field inline">
					<label><input type="radio" name="advertised" checked>Yes</label>
				</div>
				<div class="field inline">
					<label><input type="radio" name="advertised">No</label>
				</div>
			</fieldset>
			<div class="field">
				<label>Date of birth</label>
				<select id="day" name="date-of-birth">
					<option value="Day">Day</option>
				</select>
				<select id="month" name="date-of-birth">
					<option value="Month">Month</option>
				</select>
				<select id="year" name="date-of-birth">
					<option value="Year">Year</option>
				</select>
			</div>
			<div class="field">
	            <label for="newspaper-name">Name of local newspaper</label>
	            <input class="long" id="newspaper-names" name="newspaper-name" placeholder="" type="text" value="">
	        </div>
	        <div class="field">
		        <label for="advert-upload">Upload a copy of the advertisement you placed in the local paper</label>
				<input type="file" value="Upload advertisement">
			</div>
		</fieldset><!-- end advertisements -->

		<div class="actions">
			<input class="button--primary" type="submit" value="Save">
			<input class="button--secondary" type="submit" value="Cancel">
		</div><!-- end .actions -->

	</form>
</div><!-- end .three-quarters -->
