

<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Popup table no JS')); ?>
				
				<div class="full-width">
					<table>
						<thead>
							<tr>
								<th>First name</th>
								<th>Last name</th>
								<th>Date of birth</th>
							</tr>
						</thead>
						<tbody>
						<tr>
							<td>James</td>
							<td>Jefferey</td>
							<td>07/02/1963</td>
						</tr>
						<tr>
							<td>Mohammed</td>
							<td>Ali</td>
							<td>23/11/1943</td>
						</tr>
						<tr>
							<td>James</td>
							<td>Jefferey</td>
							<td>07/02/1963</td>
						</tr>
						<tr>
							<td>Mohammed</td>
							<td>Ali</td>
							<td>23/11/1943</td>
						</tr>
						</tbody>
					</table>
					<div class="actions">
						<input class="button--primary" type="submit" value="Save">
						<input class="button--secondary" type="submit" value="Cancel">
					</div><!-- .end actions -->
				</div><!-- .full-width -->