<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Popup table')); ?>

				<div class="overlay"></div>
				<div class="modal__wrapper">
					<div class="modal">
						<a href="" class="modal__close">Close</a>
					</div><!-- end .modal -->
				</div><!-- end .modal__wrapper -->

				<div class="two-thirds">
					<div class="article">
						<p>Services should use clear, easy to read type, with consistent styles and a clear hierarchy of information.</p>
						<p>GOV.UK uses the typeface New Transport, cut especially for government use. This typeface is embedded in the GOV.UK CSS and is served to browsers via a WOFF file (or an EOT file for Internet Explorer 8). The font is hinted to display well on all browsers. Older browsers do not receive the typeface.</p>
						<p><a href="" class="button--primary--large">Launch modal</a></p>
					</div><!-- end .article -->
				</div><!-- end .two-thirds -->
