<div class="content">
    <div class="one-fifth--left">
        <h4><?php echo $this->translate('My details'); ?></h4>

        <?php
        echo $this->navigation('navigation')
            ->menu($this->navigation()->findOneBy('id', 'admin-dashboard/admin-my-details'))
            ->setPartial('partials/vertical-navigation');
        ?>

    </div>

    <div class="four-fifths--right js-body__main">
        <?php echo $this->flashMessengerAll(); ?>
        <?php echo $this->content; ?>
    </div>

</div>