<div class="content">
    <div class="one-fifth--left">
        <h4><?php echo $this->translate('Payment Processing'); ?></h4>

        <?php
            echo $this->navigation('navigation')
                ->menu($this->navigation()->findOneBy('id', 'admin-dashboard/admin-payment-processing'))
                ->setPartial('partials/vertical-navigation');
        ?>

        <h4><?php echo $this->translate('internal-licence-fees-filter-by'); ?></h4>
        <?php echo $this->form($this->form); ?>
    </div>

    <div class="four-fifths--right js-body__main">
        <?php echo $this->flashMessengerAll(); ?>
        <?php echo $this->content; ?>
    </div>

</div>