<?php
$details = $this->placeholder('details')->getValue();
$markupsTable = $this->placeholder('markupsTable')->getValue();

 ?>
<div class="govuk-details">
    <p><strong>Partial Key:</strong> <?php echo $this->escapeHtml($details['partialKey']); ?></p>
    <p><strong>Description:</strong> <?php echo $this->escapeHtml($details['description']); ?></p>
</div>
<div class="govuk-details">
    <?php echo $markupsTable ?>
</div>
<div class="govuk-details">
    <a class="action--tertiary" href="<?php echo $this->url('admin-dashboard/admin-partials', ['action' => 'index']); ?>">
        <button  name="filter" class="action--tertiary" id="filter" value="">New search</button>
    </a>
</div>
