
<div class="form-group">
    <label for="address" class="col-lg-3 control-label"><?php echo $this->resourceHelper('lookup-address'); ?></label>
    <div class="col-lg-4 itext">
      <?php echo $this->formRow($advancedLookupForm->get('address')); ?>
    </div>
  </div>
<div class="form-group">
    <label for="town" class="col-lg-3 control-label"><?php echo $this->resourceHelper('lookup-town'); ?></label>
    <div class="col-lg-4 itext">
      <?php echo $this->formRow($advancedLookupForm->get('town')); ?>
    </div>
  </div>
<div class="form-group">
    <label for="caseNumber" class="col-lg-3 control-label"><?php echo $this->resourceHelper('form-case-number'); ?></label>
    <div class="col-lg-4 itext">
      <?php echo $this->formRow($advancedLookupForm->get('caseNumber')); ?>
    </div>
  </div>
<div class="form-group">
    <label for="transportManagerId" class="col-lg-3 control-label"><?php echo $this->resourceHelper('lookup-transport-manager-id'); ?></label>
    <div class="col-lg-4 itext">
      <?php echo $this->formRow($advancedLookupForm->get('transportManagerId')); ?>
    </div>
  </div>
<div class="form-group">
    <label for="operatorId" class="col-lg-3 control-label"><?php echo $this->resourceHelper('lookup-operator-id'); ?></label>
    <div class="col-lg-4 itext">
      <?php echo $this->formRow($advancedLookupForm->get('operatorId')); ?>
    </div>
  </div>
<div class="form-group">
    <label for="vehicleRegMark" class="col-lg-3 control-label"><?php echo $this->resourceHelper('lookup-vehicle-registration-mark'); ?></label>
    <div class="col-lg-4 itext">
      <?php echo $this->formRow($advancedLookupForm->get('vehicleRegMark')); ?>
    </div>
  </div>
<div class="form-group">
    <label for="diskSerialNumber" class="col-lg-3 control-label"><?php echo $this->resourceHelper('lookup-disk-serial-number'); ?></label>
    <div class="col-lg-4 itext">
      <?php echo $this->formRow($advancedLookupForm->get('diskSerialNumber')); ?>
    </div>
  </div>
<div class="form-group">
    <label for="fabsRef'" class="col-lg-3 control-label"><?php echo $this->resourceHelper('lookup-fabs-ref'); ?></label>
    <div class="col-lg-4 itext">
      <?php echo $this->formRow($advancedLookupForm->get('fabsRef')); ?>
    </div>
  </div>
<div class="form-group">
    <label for="companyNo" class="col-lg-3 control-label"><?php echo $this->resourceHelper('lookup-company-no'); ?></label>
    <div class="col-lg-4 itext">
      <?php echo $this->formRow($advancedLookupForm->get('companyNo')); ?>
    </div>
  </div>
<div class="form-group">
    <div class="col-lg-offset-3 col-lg-10">
      <?php echo $this->formButton($advancedLookupForm->get('submit'), $this->resourceHelper('lookup-advance-search-submit')); ?>
    </div>
 </div>