
  <div class="form-group">
    <label for="licenceNumber" class="col-lg-3 control-label"><?php echo $this->resourceHelper('licence-number'); ?></label>
    <div class="col-lg-4 itext">
      <?php echo $this->formRow($basicLookupForm->get('licenceNumber')); ?>
    </div>
  </div>
  <div class="form-group">
    <label for="operatorTradingName" class="col-lg-3 control-label"><?php echo $this->resourceHelper('lookup-operator-trading-name'); ?></label>
    <div class="col-lg-4 itext">
      <?php echo $this->formRow($basicLookupForm->get('operatorName')); ?>
    </div>
  </div>
    <div class="form-group">
        <label for="postcode" class="col-lg-3 control-label"><?php echo $this->resourceHelper('lookup-postcode'); ?></label>
        <div class="col-lg-4 itext">
            <?php echo $this->formRow($basicLookupForm->get('postcode')); ?>
        </div>
  </div>
    <div class="form-group">
    <label for="firstName" class="col-lg-3 control-label"><?php echo $this->resourceHelper('lookup-name'); ?></label>
    <div class="col-lg-4 itext  inlnf">
      <?php echo $this->formRow($basicLookupForm->get('firstName')); ?>
    </div>
    <div class="col-lg-4 itext">
      <?php echo $this->formRow($basicLookupForm->get('lastName')); ?>
    </div>
  </div>
    <div class="form-group">
        <label for="dobMonth" class="col-lg-3 control-label"><?php echo $this->resourceHelper('lookup-dob'); ?></label>
        <div class="col-lg-1 dob  inlnf">
          <?php echo $this->formRow($basicLookupForm->get('dobDay')); ?>
        </div>
        <div class="col-lg-1 dobMonth  inlnf">
          <?php echo $this->formRow($basicLookupForm->get('dobMonth')); ?>
        </div>
        <div class="col-lg-1 dob  inlnf">
           <?php echo $this->formRow($basicLookupForm->get('dobYear')); ?>
        </div>
      </div>
  <div class="form-group">
    <div class="col-lg-offset-3 col-lg-10">
      <?php echo $this->formButton($basicLookupForm->get('submit'), $this->resourceHelper('lookup-basic-search-submit')); ?>
    </div>
  </div>
