<p class="notice--warning">
    <strong>
        <?php
        if (!$this->hideName) {
            echo $person['forename'] .' '. $person['familyName'] .'<br>';
        }
        echo $this->translate('4/50 limit exceeded');
        ?>
    </strong>
    <br>
    <?php
    echo $this->associatedOrganisationCount;
    echo ' '. $this->translate('operators');
    echo ' / '. $this->associatedTotalAuthVehicles;
    echo ' '. $this->translate('vehicles');
    ?>
</p>