<ul class="olcscrumb">
     <?php
     // iterate through the pages
     foreach ($this->pages as $key => $page):
         ?>
         <li>
             <?php
             // if this isn't the last page, add a link and the separator
             if ($key < count($this->pages) - 1):
                 if ('Home' == $page->getLabel()) :
            ?>
             <a href="/"><img src="/img/p.png" class="sprt sprHome cur"></a>
                <?php else: ?>
                    <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
                <?php endif; ?>
             <?php
             // otherwise, just output the name
             else:
             ?>
                 <?php echo $page->getLabel(); ?>
             <?php endif; ?>
         </li>
         <?php endforeach; ?>
 </ul>
        