<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->headTitle('OLCS')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <link rel="shortcut icon" sizes="16x16" type="image/png" href="<?php echo $this->escapeHtml($this->basePath() . '/img/favicon.png'); ?>" />
        <link rel="icon" sizes="128x128" type="image/png" href="<?php echo $this->escapeHtml($this->basePath() . '/img/favicon-large.png'); ?>" />
        <?php echo $this->headLink(array('rel' => 'apple-touch-icon', 'type' => 'image/png', 'href' => $this->basePath() . '/img/favicon-large.png'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/multiselect.js')
            ->prependFile($this->basePath() . '/js/jquery.magnific-popup.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/tinymce/tinymce.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body class="<?php echo $this->placeholder('body-class'); ?>">
        <div class="header">
            <div class="container">
                <a href="/">
                    <h2>GOV.UK</h2>
                </a>
            </div>
        </div>
        <nav>
            <ul>
                <li><a href="/selfserve/licence-type" title="<?php echo $this->resourceHelper('progress-bar-applicant-details'); ?>"><span><?php echo $this->resourceHelper('progress-bar-applicant-details'); ?></span></a></li>
                <li><a href="#" title="<?php echo $this->resourceHelper('progress-bar-type-of-licence'); ?>"><span><?php echo $this->resourceHelper('progress-bar-type-of-licence'); ?></span></a></li>
                <li class="progress-breadcrumb-on" ><a href="#" title="<?php echo $this->resourceHelper('progress-bar-your-business'); ?>"><span><?php echo $this->resourceHelper('progress-bar-your-business'); ?></span></a></li>
                <li><a href="#" title="<?php echo $this->resourceHelper('progress-bar-operating-centres'); ?>"><span><?php echo $this->resourceHelper('progress-bar-operating-centres'); ?></span></a></li>
                <li><a href="#" title="<?php echo $this->resourceHelper('progress-bar-transport-managers'); ?>"><span><?php echo $this->resourceHelper('progress-bar-transport-managers'); ?></span></a></li>
                <li><a href="#" title="<?php echo $this->resourceHelper('progress-bar-vehicles-safety'); ?>"><span><?php echo $this->resourceHelper('progress-bar-vehicles-safety'); ?></span></a></li>
                <li><a href="#" title="<?php echo $this->resourceHelper('progress-bar-previous-history'); ?>"><span><?php echo $this->resourceHelper('progress-bar-previous-history'); ?></span></a></li>
                <li><a href="#" title="<?php echo $this->resourceHelper('progress-bar-declaration'); ?>"><span><?php echo $this->resourceHelper('progress-bar-declaration'); ?></span></a></li>
                <li><a href="#" title="<?php echo $this->resourceHelper('progress-bar-payment'); ?>"><span><?php echo $this->resourceHelper('progress-bar-payment'); ?></span></a></li>
                <li><a href="#" title="<?php echo $this->resourceHelper('progress-bar-summary'); ?>"><span><?php echo $this->resourceHelper('progress-bar-summary'); ?></span></a></li>

            </ul>
        </nav>
        <div class="container mainc">

            
            <?php echo $this->content; ?>
            
             <div class="clearfix"></div>
        </div> <!-- /container -->
        <footer>
            <div class="container">
        
                <div id="footer-text">
                    <ul>
                        <li><a href="#"><?php 
                        // These translations are keys in src/module/OlcsSelfserve/config/translations.ini SL
                        echo $this->resourceHelper('layout-footer-support');?></a></li>
                        <li><a href="#"><?php echo $this->resourceHelper('layout-footer-cookies');?></a></li>
                        <li><a href="#"><?php echo $this->resourceHelper('layout-footer-feedback');?></a></li>
                        <li><a href="#"><?php echo $this->resourceHelper('layout-footer-cymraeg');?></a></li>
                        <li><?php echo $this->resourceHelper('layout-footer-built-by-the');?></li>
                        <li><a href="#"><?php echo $this->resourceHelper('layout-footer-government-digital-service');?></a></li>

                        <p><?php echo $this->resourceHelper('layout-footer-open-government-licence-statement');?></p>
                        <p><?php echo $this->resourceHelper('layout-footer-disclaimer-statement');?></p>  
                    </ul>
                    
                </div>
                <div id="footer-logo">
                    <img src="/img/favicon-large.png" />
                </div>
            </div>
            
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
