<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->headTitle('OLCS')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

    </head>
    <body class="<?php echo $this->placeholder('body-class'); ?>">
        <div class="popup-overlay">
        
        <?php echo $this->content; ?>
            
        <?php echo $this->inlineScript() ?>
        </div>
    </body>
</html>
