<?php /** @global \Dvsa\Olcs\Api\Entity\Messaging\MessagingMessage $message */ ?>
<?php /** @global bool $enhanced */ ?>
<div class="govuk-!-margin-bottom-6">
  <div class="govuk-summary-card">
    <div class="govuk-summary-card__title-wrapper">
      <h2 class="govuk-summary-card__title">
        <?php
        $createdBy = $message->getCreatedBy();
        $sender = $this->safeUser(
          $createdBy,
          function ($createdBy) use ($enhanced) {
            if ($createdBy->getContactDetails() !== null && $createdBy->getContactDetails()->getPerson()) {
              if (!$enhanced && $createdBy->getTeam() !== null) {
                return $createdBy->getContactDetails()->getPerson()->getForename();
              }
              return $createdBy->getContactDetails()->getPerson()->getFullName();
            }
            return $createdBy->getLoginId();
          }
        );
        echo $sender;
        ?>
      </h2>
      <h2 class="govuk-summary-card__title govuk-summary-card__date">
        <?php
        $createdOn = $message->getCreatedOn(true);
        $createdOn->setTimezone(new \DateTimeZone('Europe/London'));
        echo $createdOn->format('l j F Y \a\t H:ia');
        ?>
      </h2>
    </div>
    <div class="govuk-summary-card__content">
      <p class="govuk-body">
        <?php echo nl2br($message->getMessagingContent()->getText()); ?>
        <?php if ($createdBy !== null && $createdBy->getTeam() !== null): ?>
      <p class="govuk-caption-m">
        <?php echo $sender; ?>
        <br/>
        Caseworker Team
      </p>
      <?php endif; ?>
      <?php if ($enhanced): ?>
        <hr/>
        <?php foreach ($message->getUserMessageReads() as $messageRead): /** @var \Dvsa\Olcs\Api\Entity\Messaging\MessagingUserMessageRead $messageRead */ ?>
          <p>
            <em>
              <?php
              $readBy = $this->safeUser(
                $messageRead->getUser(),
                function ($readByUser) {
                  if ($readByUser->getContactDetails() && $readByUser->getContactDetails()->getPerson()) {
                    return $readByUser->getContactDetails()->getPerson()->getFullName();
                  }
                  if ($readByUser->getContactDetails() && $readByUser->getContactDetails()->getEmailAddress()) {
                    return $readByUser->getContactDetails()->getEmailAddress();
                  }
                  return $readByUser->getLoginId();
                }
              );

              $createdOn = $messageRead->getCreatedOn(true);
              $createdOn->setTimezone(new \DateTimeZone('Europe/London'));
              echo sprintf(
                'Read by %s on %s',
                $readBy,
                $createdOn->format('l j F Y \a\t H:ia')
              ); ?>
            </em>
          </p>
        <?php endforeach; ?>
      <?php endif; ?>
      </p>
    </div>
  </div>
</div>
