<div class="row">

  <div class="two-thirds">
      <?php
      echo $this->partial(
          'partials/page-header-simple',
          [
              'pageTitle' => $this->translate('lva-summary-title'),
              'pageSubTitle' => $this->licence . ' / ' . $this->application,
          ]
      );
      ?>
      <?php if ($justPaid): ?>
      <p>
          <?php
          echo $this->translate(
              ($outstandingFee) ?
              'lva-summary-application-submitted-fee-outstanding' :
              'lva-summary-application-submitted'
          );
          ?>
      </p>
      <div class="confirmation">
          <p><?php echo $this->translate('lva-summary-reference-number'); ?></p>
          <h2><?php echo $this->escapeHtml($licence . '/' . $application); ?></h2>
          <?php if ($paymentRef): ?>
              <p>
                  <a href="<?php echo $this->url('fees/receipt', ['action' => 'print', 'reference' => $paymentRef]);?>" target="blank">
                      <?php echo $this->translate('pay-fees.success.view-receipt'); ?>
                  </a>
              </p>
          <?php endif; ?>
      </div>
      <?php endif; ?>
      <div class="article">
        <?php if (empty($actions) || $hideContent): ?>
            <h2><?php echo $this->translate('What happens next?'); ?></h2>
            <p><?php echo $this->translate('application-summary-complete-what-next-text'); ?></p>
        <?php else: ?>
            <h2><?php echo $this->translate('What do I need to do next?'); ?></h2>
        <?php endif; ?>
      </div>
      <div class="article">

          <?php if (array_key_exists('PRINT_SIGN_RETURN', $actions) && !$hideContent): ?>
              <div class="incomplete-section">
                  <h3><?php echo $this->translate('print-sign-return-declaration-form'); ?></h3>
                  <p><?php echo $this->translate('print-sign-return-declaration-form-text'); ?></p>
                  <p>
                      <a href="<?php echo $this->url('lva-' . $lva . '/declaration', [], [], true); ?>" target="_blank" class="download">
                          <?php echo $this->translate('print-declaration-form'); ?>
                      </a>
                  </p>
              </div>
          <?php endif; ?>

          <?php if (array_key_exists('SUPPLY_SUPPORTING_EVIDENCE', $actions) && !$hideContent): ?>
              <div class="incomplete-section">
                  <h3><?php echo $this->translate('supply-supporting-evidence'); ?></h3>
                  <p><?php echo $this->translate('supply-supporting-evidence-text-1'); ?></p>
                  <ul>
                      <?php
                      foreach ($actions['SUPPLY_SUPPORTING_EVIDENCE'] as $evidence) {
                          ?>
                          <li><?php echo $this->translate($evidence); ?></li>
                          <?php
                      }
                      ?>
                  </ul>
                  <p><?php echo $this->translate('supply-supporting-evidence-text-2'); ?> (<?php echo $licence . '/' . $application; ?>).</p>
              </div>
          <?php endif; ?>

          <?php if (array_key_exists('APPROVE_TM', $actions) && !$hideContent): ?>
              <div class="incomplete-section">
                  <h3><?php echo $this->translate('approve-tm.title'); ?></h3>
                  <div class="table__wrapper">
                      <table>
                          <thead>
                              <tr>
                                  <th><?php echo $this->translate('approve-tm.table.column.name.title'); ?></th>
                                  <th><?php echo $this->translate('approve-tm.table.column.dob.title'); ?></th>
                                  <th><?php echo $this->translate('approve-tm.table.column.actions.title'); ?></th>
                              </tr>
                          </thead>
                          <tbody>
                          <?php
                          foreach ($transportManagers as $transportManager) {

                              $tmPerson = $transportManager['transportManager']['homeCd']['person'];
                              $tmName = sprintf('%s %s', $tmPerson['forename'], $tmPerson['familyName']);
                              $tmStatus = $transportManager['tmApplicationStatus'];
                              $tmLink = $this->url(
                                  'lva-' . $lva . '/transport_manager_details',
                                  ['action' => null, 'child_id' => $transportManager['id']],
                                  [],
                                  true
                              );

                              ?>
                              <tr>
                                  <td>
                                      <?php echo $tmName; ?>
                                      <?php echo $this->transportManagerApplicationStatus($tmStatus['id'], $tmStatus['description']); ?>
                                  </td>
                                  <td><?php echo $this->date(strtotime($tmPerson['birthDate'])); ?></td>
                                  <td><a class="remove" href="<?php echo $tmLink; ?>"
                                      ><?php echo $this->translate('approve-tm.table.action.view-details'); ?></a></td>
                              </tr>
                              <?php
                          }
                          ?>
                          </tbody>
                      </table>
                  </div><!-- .table__wrapper -->
              </div>
          <?php endif; ?>

          <p class="important"><strong><?php echo $this->translate($this->importantText); ?></strong></p>

      </div><!-- .article -->

      <div class="actions-container">
          <a class="action--primary large" href="<?php echo $this->url('dashboard'); ?>"><?php echo $this->translate('return-home-button-text'); ?></a>
      </div>

  </div>

  <div class="one-third">
    <aside class="sidebar" role="complementary">
      <ul class="sidebar__actions">
          <li>
              <a href="<?php echo $this->url('lva-' . $lva . '/review', [], [], true); ?>" target="_blank"
                  class=""><?php echo $this->translate('view-full-application') ?></a>
          </li>
          <?php if ($canWithdraw): ?>
              <li>
                  <a href="<?php echo $this->url('lva-' . $lva . '/withdraw', [], [], true); ?>"
                      class="js-modal-ajax"><?php echo $this->translate('withdraw-application') ?></a>
              </li>
          <?php endif; ?>
      </ul>
      <dl class="meta">
        <?php if ($paymentRef): ?>
          <dt><?php echo $this->translate('payment-reference-no.title'); ?></dt>
          <dd><?php echo $paymentRef; ?>
          <a target="_blank"
            href="<?php echo $this->url('fees/receipt', ['action' => 'print', 'reference' => $paymentRef]);?>">
            <?php echo $this->translate('pay-fees.success.print-receipt'); ?>
          </a></dd>
        <?php endif; ?>
        <dt><?php echo $this->translate('submitted-date.title'); ?></dt>
        <dd><?php echo $this->date(strtotime($submittedDate)); ?></dd>
        <dt><?php echo $this->translate('completion-date.title'); ?></dt>
        <dd><?php echo $this->date(strtotime($completionDate)); ?></dd>
        <dt><?php echo $this->translate('status.title'); ?></dt>
        <dd><?php echo $this->translate($status); ?></dd>
        <?php if ($interimStatus !== null): ?>
          <dt><?php echo $this->translate('interim.status.title'); ?></dt>
          <dd><?php echo $this->translate($interimStatus); ?></dd>
            <dt><?php echo $this->translate('interim.start.title'); ?></dt>
          <dd><?php echo $this->date(strtotime($interimStart)); ?></dd>
        <?php endif; ?>
      </dl>
    </aside>
  </div>

</div>
