<div class="page-header">
    <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partials/breadcrumbs'); ?>
    <div class="page-header__wrapper">
        <h3 class="page-header__subtitle">
            <?php echo $this->translate('lva-post-submit-summary-application-no'); ?><?php echo $application; ?>
        </h3>
        <h1><?php echo $this->translate('lva-post-submit-summary-title'); ?></h1>
        <ul class="page-header__actions">
            <li>
                <a href="<?php echo $this->url('lva-' . $lva . '/review', [], [], true); ?>" target="_blank" class="page-header__action"><?php echo $this->translate('view-full-application') ?></a>
            </li>
            <?php if ($canWithdraw): ?>
              <li>
                  <a
                      href="<?php echo $this->url('lva-' . $lva . '/withdraw', [], [], true); ?>"
                      class="page-header__action js-modal-ajax">
                      <?php echo $this->translate('application.withdraw'); ?>
                  </a>
              </li>
            <?php endif; ?>
        </ul>
    </div><!-- .page-header__wrapper -->
</div><!-- .page-header -->

<div class="two-thirds border">
    <?php // TM table would go here, but is out of scope ?>
    <?php echo $this->partial('partials/shared-application-summary'); ?>
</div>

<div class="one-third sidebar">
    <dl class="meta">
        <dt><?php echo $this->translate('lva-post-submit-summary-reference-number'); ?></dt>
        <dd><?php echo $licence; ?>/<?php echo $application; ?></dd>
        <dt><?php echo $this->translate('submitted-date'); ?></dt>
        <dd><?php echo $submittedDate; ?></dd>
        <dt><?php echo $this->translate('status'); ?></dt>
        <dd><?php echo $status; ?></dd>
        <dt><?php echo $this->translate('target-completion-date'); ?></dt>
        <dd><?php echo $targetCompletionDate; ?></dd>
        
        <?php if ($interimStatus): ?>
            <dt><?php echo $this->translate('interim-status'); ?></dt>
            <dd><?php echo $this->translate($interimStatus); ?></dd>

            <?php if ($interimStartDate): ?>
                <dt><?php echo $this->translate('interim-start-date'); ?></dt>
                <dd><?php echo strftime("%d %B %G",strtotime($interimStartDate)); ?></dd>
            <?php endif; ?>
        <?php endif; ?>
        
    </dl><!-- .meta -->
    <div class="links">
        <h3><?php echo $this->translate('sidebar-applying-for-licence'); ?></h3>
        <ul class="links-list">
            <li class="links-list__item">
                <a href="#Coming-soon">Complete your applications for a goods vehicle operator's licence</a>
            </li>
            <li class="links-list__item">
                <a href="#Coming-soon">Advertise your application for a licence</a>
            </li>
            <li class="links-list__item">
                <a href="#Coming-soon">Financial information</a>
            </li>
            <li class="links-list__item">
                <a href="#Coming-soon">A guide to operator fees</a>
            </li>
            <li class="links-list__item">
                <a href="#Coming-soon">How to draw up a maintenance contract</a>
            </li>
        </ul>
    </div><!-- .links -->
</div><!-- .one-third -->