<div class="printable">
    <div class="printable__address">
        <p><b><?php echo $this->translate('Return to'); ?>:</b></p>
        <?php
        if ($isNi) {
            $addressParts = [
                'Department of the Environment',
                'The Central Licensing Office',
                'PO Box 180',
                'Leeds',
                'LS9 1BU'
            ];
        } else {
            $addressParts = [
                'Office of the Traffic Commissioner',
                'The Central Licensing Office',
                'Hillcrest House',
                '386 Harehills Lane',
                'Leeds',
                'LS9 6NF'
            ];
        }
        ?>
        <p><?php echo implode(',<br />', $addressParts); ?></p>
    </div>
    <div class="printable__meta">
        <dl>
            <dt><?php echo $this->translate('Application reference'); ?></dt>
            <dd><?php echo $reference; ?></dd>
            <dt><?php echo $this->translate('Applicant'); ?></dt>
            <dd><?php echo $name; ?></dd>
        </dl>
    </div>
    <div class="printable__header">
        <h2><?php echo $this->translate($title); ?></h2>
    </div>
    <div class="printable__section">
        <h4>Agreements</h4>
        <p>By applying I agree to follow the rules below, and I'm aware that:</p>
        <ul>
            <li>the rules will be recorded on my licence</li>
            <li>my licence could be revoked, suspended or curtailed if I don't follow them </li>
            <li>it's a criminal offence not to follow the rules</li>
        </ul>

        <h4>Laws</h4>
        <p>I agree to obey laws that cover:</p>
        <ul>
            <li>operating vehicles</li>
            <li>drivers' hours</li>
            <li>tachographs</li>
            <li>speed limits</li>
        </ul>

        <h4>Passengers</h4>
        <p>My vehicles won't carry more passengers than they're permitted to.</p>

        <h4>Records</h4>
        <p>I'll maintain proper records and show them when they're needed.</p>
        <p>I'll also:</p>
        <ul>
            <li>keep records of driver reports for 15 months</li>
            <li>record defects, safety inspections, maintenance and repairs</li>
        </ul>

        <h4>Vehicle condition</h4>
        <p>I'll keep my vehicles in good condition, and:</p>
        <ul>
            <li>promptly report any defects, or symptoms of them</li>
            <li>record the details in writing</li>
            <li>show records when they're needed</li>
        </ul>

        <h4>Informing the Traffic Commissioner</h4>
        <p>I'll tell the Traffic Commissioner within 28 days if:</p>
        <ul>
            <li>there are any other changes</li>
            <li>anyone mentioned in this application is convicted of an offence</li>
        </ul>

        <h4>Declaration</h4>
        <p>I declare that:</p>
        <ul>
            <li>the statements I've made in this application are true</li>
            <li>all supporting evidence is correct</li>
            <li>I understand that it's an offence to make a false declaration</li>
        </ul>

    </div>

    <div class="signature-box">
        <label for="" class="signature-box__label"><?php echo $this->translate($signatureLabel); ?></label>
        <input type="text" class="signature-box__input signature" disabled="disabled">
        <label for="" class="signature-box__label"><?php echo $this->translate('Full name in block capitals'); ?></label>
        <input type="text" class="signature-box__input name" disabled="disabled">
        <label for="" class="signature-box__label"><?php echo $this->translate('Date'); ?></label>
        <input type="text" class="signature-box__input date" disabled="disabled">
    </div>

    <p>
        <?php echo $this->translate('declaration-guidance'); ?><br />
        <b><?php echo $this->translate('Return to'); ?>: </b><?php echo implode(', ', $addressParts); ?>
    </p>

</div>
<script type="text/javascript">
    window.print();
</script>