<div class="printable">
    <div class="printable__address">
        <p><b><?php echo $this->translate('Return to'); ?>:</b></p>
        <?php
        if ($isNi) {
            $addressParts = [
                'Department of the Environment',
                'The Central Licensing Office',
                'PO Box 180',
                'Leeds',
                'LS9 1BU'
            ];
        } else {
            $addressParts = [
                'Office of the Traffic Commissioner',
                'The Central Licensing Office',
                'Hillcrest House',
                '386 Harehills Lane',
                'Leeds',
                'LS9 6NF'
            ];
        }
        ?>
        <p><?php echo implode(',<br />', $addressParts); ?></p>
    </div>
    <div class="printable__meta">
        <dl>
            <dt><?php echo $this->translate('Application reference'); ?></dt>
            <dd><?php echo $reference; ?></dd>
            <dt><?php echo $this->translate('Applicant'); ?></dt>
            <dd><?php echo $name; ?></dd>
        </dl>
    </div>
    <div class="printable__header">
        <h2><?php echo $this->translate($title); ?></h2>
    </div>
    <div class="printable__section">
        <p><?php echo $undertakings; ?></p>
    </div>

    <div class="signature-box">
        <label for="" class="signature-box__label"><?php echo $this->translate($signatureLabel); ?></label>
        <input type="text" class="signature-box__input signature" disabled="disabled">
        <label for="" class="signature-box__label"><?php echo $this->translate('Full name in block capitals'); ?></label>
        <input type="text" class="signature-box__input name" disabled="disabled">
        <label for="" class="signature-box__label"><?php echo $this->translate('Date'); ?></label>
        <input type="text" class="signature-box__input date" disabled="disabled">
    </div>

    <p>
        <?php echo $this->translate('declaration-guidance'); ?><br />
        <b><?php echo $this->translate('Return to'); ?>: </b><?php echo implode(', ', $addressParts); ?>
    </p>

</div>
<script type="text/javascript">
    window.print();
</script>