<div class="printable">
  
    <div class="printable__address">
        <p><b><?php echo $this->translate('Return to'); ?>:</b></p>
        <p><?php echo $this->returnToAddress($isNi, ',<br />'); ?></p>
    </div>
    
    <div class="printable__meta">
        <dl>
            <dt><?php echo $this->translate('Application reference'); ?></dt>
            <dd><?php echo $reference; ?></dd>
            <dt><?php echo $this->translate('Applicant'); ?></dt>
            <dd><?php echo $name; ?></dd>
        </dl>
    </div>
    
    <div class="printable__header">
        <h2><?php echo $this->translate($title); ?></h2>
    </div>
    
    <div class="printable__section">
        <p><?php echo $undertakings; ?></p>
    </div>

    <div class="signature-box">
        <label for="" class="signature-box__label"><?php echo $this->translate($signatureLabel); ?></label>
        <input type="text" class="signature-box__input signature" disabled="disabled">
        <label for="" class="signature-box__label"><?php echo $this->translate('Full name in block capitals'); ?></label>
        <input type="text" class="signature-box__input name" disabled="disabled">
        <label for="" class="signature-box__label"><?php echo $this->translate('Date'); ?></label>
        <input type="text" class="signature-box__input date" disabled="disabled">
    </div>

    <p>
        <?php echo $this->translate('declaration-guidance'); ?><br />
        <b><?php echo $this->translate('Return to'); ?>: </b><?php echo $this->returnToAddress($isNi, ', '); ?>
    </p>

</div>

<script type="text/javascript">
    window.print();
</script>