<?php
/** @var \Zend\Navigation\Page\Mvc $backPage */
$backPage = $this->navigationParentPage();

echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->translate($this->title),
        'backUrl' => [
            'url' => ($backPage !== null ? $backPage->getHref() : null),
        ],
    ]
);
?>

<div class="row">
    
  <div class="three-quarters">
      <?php
  
      $guidanceMessage = $this->placeholder('guidance');
  
      if (!empty($guidanceMessage)) {
          foreach ($guidanceMessage as $message):
            ?>
            <div class="guidance">
                <p><?php echo $this->translate($message); ?></p>
            </div>
            <?php
          endforeach;
      }
  
      echo $content; ?>
  </div>

</div>