<div class="page-header">
  <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partials/breadcrumbs'); ?>
  <div class="page-header__wrapper">
    <h1><?php echo $this->translate($title); ?></h1>
  </div><!-- .page-header__wrapper -->
</div><!-- .page-header-->

<div class="row">
    
  <div class="three-quarters">
      <?php
  
      $guidanceMessage = $this->placeholder('guidance');
  
      if (!empty($guidanceMessage)) {
          foreach ($guidanceMessage as $message):
            ?>
            <div class="guidance">
                <p><?php echo $this->translate($message); ?></p>
            </div>
            <?php
          endforeach;
      }
  
      echo $content; ?>
      <a href="<?php echo $this->url('lva-licence', [], [], true); ?>" class="action--primary large">
          <?php echo $this->translate('back-to-licence-overview'); ?>
      </a>
  </div>

</div>