<div class="page-header">
  <ol class="breadcrumbs">
    <li class="breadcrumbs__item"><a href="">Back to overview</a></li>
  </ol>
  <div class="page-header__wrapper">
    <h3 class="page-header__subtitle">
<?php
if(isset($stepY)):
  echo sprintf($this->translate('application.steps'), $stepX, $stepY);
else:
  echo sprintf($this->translate('application.step'), $stepX);
endif;
?>
    </h3>
    <h1 class="js-title"><?php echo $this->translate($title); ?></h1>
  </div><!-- .page-header__wrapper -->
</div><!-- .page-header-->

<?php if (isset($filterForm)): ?>
<div class="three-eigths">
  <h3>Filter by:</h3>
   <?php echo $this->form($filterForm); ?>
</div>
<div class="five-eigths">
<?php else : ?>
<div class="three-quarters js-body">
<?php endif; ?>
  <?php
  if (isset($sectionText)) {
      ?><p><?php echo $this->translate($sectionText); ?></p><?php
  }
  ?>

  <?php echo $this->flashMessengerAll(); ?>

  <?php if (isset($table)): ?>
    <?php echo $table; ?>
  <?php endif; ?>

  <?php if (isset($form)): ?>
    <?php
    $form->prepare();
    echo $this->formErrors($form);
    echo $this->form($form);
    ?>
  <?php endif; ?>
</div>
