<div class="js-body">
    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); ?>

    <div class="page-header">
      <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partials/breadcrumbs'); ?>
      <div class="page-header__wrapper">
        <h1><?php echo $this->translate($title); ?></h1>
        <div class="page-header__text">
            <p><?php echo $this->translate($subTitle); ?></p>
        </div>
        <ul class="page-header__actions">
            <?php
            foreach ($form->get('form-actions')->getElements() as $element) {

                // Remember the previous attributes
                $attributes = $element->getAttributes();

                // Override the class of the button
                $element->setAttribute('class', 'action--tertiary page-header__action');
                ?>
                <li><?php echo $this->formElement($element); ?></li>
                <?php

                // Restire the previous attributes
                $element->setAttributes($attributes);
            }
            ?>
        </ul>
      </div><!-- .page-header__wrapper -->
    </div><!-- .page-header-->

    <div class="two-thirds border">
    <?php

    $guidanceMessage = $this->placeholder('guidance');

    if (!empty($guidanceMessage)) {
        foreach ($guidanceMessage as $message):
        ?>
        <div class="guidance">
            <p><?php echo $this->translate($message); ?></p>
        </div>
        <?php
        endforeach;
    }

    if (isset($sectionText)) {
        ?><p><?php echo $this->translate($sectionText); ?></p><?php
    }

    echo $this->flashMessengerAll();

    echo $this->formErrors($form);
    echo $this->form()->render($form, false);
    ?>
    </div>
    <div class="one-third sidebar">

      <div class="support">
        <h3>Support</h3>
        <b>Call: 0113 254 3200</b>
        <p>Mon to Thurs: 8:30am – 5pm<br>
           Fri: 8:30am – 4pm
        </p>
        <p>Closed at weekend and on public and bank holidays</p>
        <p>Or email our support team at:<br>
        <a href="">operatorlicensing@otc.gov.uk</a>
        </p>
      </div>

    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>