<div class="page-header">
  <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partials/breadcrumbs'); ?>
  <div class="page-header__wrapper">
    <?php if (isset($stepX)): ?>
    <h3 class="page-header__subtitle">
      <?php
      if(isset($stepY)):
        echo sprintf($this->translate('application.steps'), $stepX, $stepY);
      else:
        echo sprintf($this->translate('application.step'), $stepX);
      endif;
      ?>
    </h3>
    <?php endif; ?>
    <h1 class="js-title"><?php echo $this->translate($title); ?></h1>
  </div>
</div><!-- page-header-->

<div class="row">

  <?php if (isset($filterForm)): ?>

  <div class="one-quarter">
    <h3>Filter by:</h3>
    <?php echo $this->form($filterForm); ?>
    <?php echo $this->translate('markup-support-contact-address');?>
  </div>

  <div class="three-quarters lva-details">
  
    <div class="js-body">
    
    <?php else : ?>
    
  <div class="two-thirds lva-details">
        
    <div class="js-body">
        
    <?php endif; ?>
        
      <?php
        $guidanceMessage = $this->placeholder('guidance');
        if (!empty($guidanceMessage)) {
          foreach ($guidanceMessage as $message):
      ?>
        
      <div class="guidance">
        <p><?php echo $this->translate($message); ?></p>
      </div>
    
      <?php endforeach; }
        if (isset($sectionText)) {
      ?>
      
      <p><?php echo $this->translate($sectionText); ?></p>
      
      <?php } ?>

      <?php
    
        $messages = $this->flashMessengerAll('norender')->getMessagesFromNamespace('prominent-error');
      
        foreach ($messages as $message) {
            ?>
            <div class="validation-summary">
                <?php echo $this->translate($message); ?>
            </div>
            <?php
        }
    
      ?>

      <?php echo $this->flashMessengerAll(); ?>
    
      <?php if (isset($table)): ?>
        <?php echo $table; ?>
      <?php endif; ?>
    
      <?php if (isset($form)): ?>
        <?php
        $form->prepare();
        echo $this->formErrors($form);
        echo $this->form($form);
        ?>
      <?php endif; ?>
  
      </div> <!-- /js-body -->
    </div>

  <?php if (!isset($filterForm)): ?>
    <div class="one-third">
      <div class="sidebar" role="complementary">
        <?php echo $this->translate('markup-support-contact-address');?>
      </div>
    </div>
  <?php endif; ?>
  
</div>