<?php
use Common\Util\Escape;
?>

<div class="js-body">
    <?php
        echo $this->partial(
            'partials/page-header-simple',
            [
                'pageTitle' => $this->translate($this->title),
                'pageSubTitle' => $this->tmFullName
            ]
        );
    ?>

    <div class="row">
        
      <div class="full-width article">


          <p><?php echo $this->content ?></p>

          <?php echo $this->partialLoop(
          'partials/check-answer-section',
            $this->sections
          ); ?>
  
          <?php if (isset($form)): ?>
            <?php
            $form->prepare();
            echo $this->formErrors($form);
            echo $this->form($form);
            ?>
          <?php endif; ?>
  
          <?php if (isset($this->bottomContent)): ?>
              <?php echo $this->bottomContent ?>
          <?php endif; ?>
  
          <?php if (isset($resendForm)): ?>
              <details class="govuk-details" data-module="govuk-details">
                  <summary class="govuk-details__summary" aria-controls="details-content-resend-link">
                      <span class="govuk-details__summary-text">
                          <?php echo Escape::html($this->translate('lva-tmverify-details-checkanswer-resend-tm-link')); ?>
                      </span>
                  </summary>
                  <div class="govuk-details__text" id="details-content-resend-link">
                  <?php
                  $resendForm->prepare();
                  echo $this->formErrors($resendForm);
                  echo $this->form($resendForm);
                  ?>
                  </div>
              </details>
          <?php endif; ?>

          <?php
          if (isset($this->backLink)): ?>
          <p>
              <?php echo $this->link($this->backLink, $this->backText, 'govuk-back-link'); ?>
          </p>
          <?php endif; ?>
      </div>
      
    </div>
    
</div>