<?php
  if ($this->lva === 'application') {
    $progressTranslated = sprintf($this->translate('application.progress'), $this->stepX, $this->stepY);
  } elseif ($this->lva === 'licence') {
    $startDateFormatted =  $startDate ? strftime("%d %B %G",strtotime($startDate)) : '';
    $renewalDateFormatted =  $renewalDate ? strftime("%d %B %G",strtotime($renewalDate)) : '';
  }
  $statusTranslated = $this->translate($status);
  $translator = $this->getHelperPluginManager()->getServiceLocator()->get('Helper\Translation');
?>
<div class="page-header">
  <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partials/breadcrumbs'); ?>
  <div class="page-header__wrapper">
    <?php if (isset($stepX)): ?>
    <h3 class="page-header__subtitle">
      <?php
      if(isset($stepY)):
        echo sprintf($this->translate('application.steps'), $stepX, $stepY);
      else:
        echo sprintf($this->translate('application.step'), $stepX);
      endif;
      ?>
    </h3>
    <?php endif; ?>
    <h1 class="js-title"><?php echo $this->translate($title); ?></h1>
  </div>
</div><!-- page-header-->

<div class="row">

  <?php if (isset($filterForm)): ?>

  <div class="one-quarter sidebar--plain">
    <h4>Filter by:</h4>
    <?php echo $this->form($filterForm); ?>
    <?php
    if ($lva === 'application') {
      echo $translator->translateReplace(
          'markup-application-right-column', [$reference, $progressTranslated, $statusTranslated]
      );
    } elseif ($lva === 'variation') {
      echo $translator->translateReplace(
          'markup-variation-right-column', [$reference, $statusTranslated]
      );
    } else {
      echo $translator->translateReplace(
          'markup-licence-right-column', [$licNo, $statusTranslated, $renewalDateFormatted, $startDateFormatted]
      );
    }
    ?>
    <?php echo $this->translate('markup-support-contact-address');?>
  </div>

  <div class="three-quarters lva-details">

    <div class="js-body">

    <?php else : ?>

  <div class="two-thirds lva-details">

    <div class="js-body">

    <?php endif; ?>

      <?php
        $guidanceMessage = $this->placeholder('guidance');
        if (!empty($guidanceMessage)) {
          foreach ($guidanceMessage as $message):
      ?>

      <div class="guidance">
        <p><?php echo $this->translate($message); ?></p>
      </div>

      <?php endforeach; }
        if (isset($sectionText)) {
      ?>

      <p><?php echo $this->translate($sectionText); ?></p>

      <?php } ?>

      <?php

        $messages = $this->flashMessengerAll('norender')->getMessagesFromNamespace('prominent-error');

        foreach ($messages as $message) {
            ?>
            <div class="validation-summary">
                <?php echo $this->translate($message); ?>
            </div>
            <?php
        }

        echo $this->flashMessengerAll();

        if (isset($searchForm)) {
            $searchForm->prepare();
            echo $this->formErrors($searchForm);
            echo $this->form($searchForm);
        }

        if (isset($table)) {
          echo $table;
        }

        if (isset($form)) {
          $form->prepare();
          echo $this->formErrors($form);
          echo $this->form($form);
        }
      ?>

      </div> <!-- /js-body -->
    </div>

  <?php if (!isset($filterForm)): ?>
    <div class="one-third">
      <aside class="sidebar" role="complementary">
        <?php
            if ($lva === 'application') {
              echo $translator->translateReplace(
                'markup-application-right-column', [$reference, $progressTranslated, $statusTranslated]
              );
            } elseif ($lva === 'variation') {
              echo $translator->translateReplace(
                'markup-variation-right-column', [$reference, $statusTranslated]
              );
            } elseif ($lva === 'licence') {
              echo $translator->translateReplace(
                'markup-licence-right-column', [$licNo, $statusTranslated, $renewalDateFormatted, $startDateFormatted]
              );
            }
      ?>
      </aside>
      <?php echo $this->translate('markup-support-contact-address');?>
    </div>
  <?php endif; ?>

</div>