<div class="row js-body">
    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); ?>

    <div class="two-thirds">
      <?php
      /** @var \Zend\Navigation\Page\Mvc $backPage */
      $backPage = $this->navigationParentPage();

      echo $this->partial(
          'partials/page-header-simple',
          [
              'pageTitle' => $this->translate($this->title),
              'pageHeaderText' => $this->translate($this->subTitle),
              'pageHeaderTextEscape' => false,
              'backUrl' => [
                  'url' => ($backPage !== null ? $backPage->getHref() : null),
              ],
          ]
      );

      //  guidance
      $guidanceMessage = $this->placeholder('guidance');

      if (!empty($guidanceMessage)) {
          foreach ($guidanceMessage as $message):
          ?>
          <div class="guidance">
              <p><?php echo $this->translate($message); ?></p>
          </div>
          <?php
          endforeach;
      }

      if (isset($sectionText)) {
          ?><p><?php echo $this->translate($sectionText); ?></p><?php
      }

      echo $this->flashMessengerAll();

      echo $this->formErrors($form);
      echo $this->form()->render($form, false);
      ?>
    </div>

  <?php echo $this->form()->closeTag(); ?>

</div>
