<div class="js-body">
    <?php
    echo $this->partial(
        'partials/page-header-simple',
        [
            'pageTitle' => $this->translate($this->title),
            'pageSubTitle' => $this->tmFullName,
            'backUrl' => [
                'url' => $this->navigationParentPage()->getHref(),
            ],
        ]
    );
    ?>

    <div class="row">
        
      <div class="two-thirds article">
          <?php
  
          $guidanceMessage = $this->placeholder('guidance');
  
          if (!empty($guidanceMessage)) {
              foreach ($guidanceMessage as $message):
              ?>
              <div class="guidance">
                  <p><?php echo $this->translate($message); ?></p>
              </div>
              <?php
              endforeach;
          }
  
          if (isset($sectionText)) {
              ?><p><?php echo $this->translate($sectionText); ?></p><?php
          }
  
          echo $this->flashMessengerAll();
          ?>
  
          <?php echo $this->content ?>
  
          <?php if (isset($form)): ?>
            <?php
            $form->prepare();
            echo $this->formErrors($form);
            echo $this->form($form);
            ?>
          <?php endif; ?>
  
          <?php if (isset($this->bottomContent)): ?>
              <?php echo $this->bottomContent ?>
          <?php endif; ?>
  
          <?php if (isset($resendForm)): ?>
              <details class="help">
                  <summary class="help__summary">Resend link to Transport Manager</summary>
                  <?php
                  $resendForm->prepare();
                  echo $this->formErrors($resendForm);
                  echo $this->form($resendForm);
                  ?>
              </details>
          <?php endif; ?>


          <?php
          if (isset($this->backLink)): ?>
          <p>
              <a href="<?php echo $this->backLink ?>">
                  <?php echo $this->translate($this->backText); ?>
              </a>
          </p>
          <?php endif; ?>
      </div>
      
    </div>
    
</div>