<?php
    echo $this->render(
        '/partials/page-header.phtml',
        array(
            'pageTitle' => $this->pageTitle(),
            'pageSubTitle'=> isset($this->pageSubtitle) ? $this->translate($this->pageSubtitle) : '',
            'pageHeaderText'=> isset($this->pageHeaderText) ? $this->translate($this->pageHeaderText) : '',
            'pageHeaderUrl'=> isset($this->pageHeaderUrl) ? $this->pageHeaderUrl : null,
            'showNav' => isset($this->showNav) && $this->showNav === false ? false : true,
        )
    );
?>

<div class="row">
  <div class="two-thirds">
      <div class="guidance">
          <p><?php echo $this->translate('name-change.locked.guidance.message'); ?></p>
      </div>
      <p id="top" class="actions-container">
          <a class="action--tertiary" href="<?php echo $this->url('change-password'); ?>">
              <?php echo $this->translate('my-details.change-password.label');?>
          </a>
      </p>
    <?php echo $this->flashMessengerAll(); ?>
    <?php
      echo $this->formErrors($this->form);
      echo $this->form($this->form);
    ?>
  </div>
</div>
