<?php echo $operatingCentres; ?>
<h3><?php echo $this->translate('Authorisation'); ?></h3>
<?php if ($this->isPsv): ?>
<p><?php echo $this->translate('selfserve-app-subSection-operating-centre-oc-info-psv'); ?></p>
<?php else: ?>
<p><?php echo $this->translate('selfserve-app-subSection-operating-centre-oc-info'); ?></p>
<?php endif; ?>
<?php
echo $this->formErrors($form);
echo $this->form($form);
