<?php 
$this->placeholder('body-class')->set("full-page");
$this->headScript()->prependFile($this->basePath() . '/js/olc.ajax.js');
$this->headScript()->prependFile($this->basePath() . '/js/collapsible.init.js');
$this->headScript()->prependFile($this->basePath() . '/js/collapsible.js');
$this->headScript()->prependFile($this->basePath() . '/js/listSort.js');
$this->headScript()->prependFile($this->basePath() . '/js/olc.list.js');
$this->headScript()->prependFile($this->basePath() . '/js/olc.overlay-form.js');
$this->headScript()->prependFile($this->basePath() . '/js/application/olc.application.js');
?>
<?php $detailsForm->prepare(); ?>

<?php echo $this->partial('olcs/common/errorMessages', array('messages' => $messages)); ?>
<?php echo $this->form()->openTag($detailsForm); ?>

<div id="applicationDetailsDiv" class="row">

<?php
    echo $this->partial('olcs/application/partials/header-details');
    echo $this->partial('olcs/application/partials/tabs', array('entityTypeActive' => 'active', 'applicationId' => $applicationId));
    echo $this->partial('olcs/application/partials/registered-company-details-form', array(
        'registeredCompanyDetailsForm' => $detailsForm->get('RegisteredCompanyDetailsForm'),
        'entityType' => $entityType,
        'licenceType' => $licenceType,
        'operatorType' => $operatorType,
    ));
    echo $this->partial('olcs/application/partials/registered-office-details-form', array(
        'registeredOfficeDetailsForm' => $detailsForm->get('RegisteredOfficeDetailsForm'),
    ));
    echo $this->partial('olcs/application/partials/owner-list-form', array(
        'form' => $detailsForm->get('owners'),
        'applicationEntityType' => $application_header_details['entityTypes'],
    ));
    echo $this->partial('olcs/application/partials/subsidiary-company-form', array(
        'form' => $detailsForm->get('subsidiaries'),
        'applicationEntityType' => $application_header_details['entityTypes'],
    ));
?>
    <div class="form-group">
        <button id="cancelbutton" name="cancel" class="btn btn-cancel" type="button"><?php echo $this->resourceHelper('cancel'); ?></button>
        <button id="submitbutton" name="submit" class="btn btn-success btn-save pull-right"><?php echo $this->resourceHelper('save'); ?></button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
