
<?php 

$this->placeholder('body-class')->set("full-page");
$this->headScript()->prependFile($this->basePath() . '/js/olc.ajax.js');
$this->headScript()->prependFile($this->basePath() . '/js/collapsible.init.js');
$this->headScript()->prependFile($this->basePath() . '/js/collapsible.js');
$this->headScript()->prependFile($this->basePath() . '/js/listSort.js');
$this->headScript()->prependFile($this->basePath() . '/js/olc.list.js');
$this->headScript()->prependFile($this->basePath() . '/js/olc.overlay-form.js');
$this->headScript()->prependFile($this->basePath() . '/js/application/olc.application.js');

?>
<?php $soleTraderForm->prepare(); ?>

<?php echo $this->partial('olcs/common/errorMessages', array('messages' => $messages)); ?>
<?php echo $this->form()->openTag($soleTraderForm); ?>

<div id="applicationDetailsDiv" class="row">

<?php
    echo $this->partial('olcs/application/partials/header-details');
    echo $this->partial('olcs/application/partials/tabs', array('entityTypeActive' => 'active'));
    
    echo $this->partial('olcs/application/person-search', array(
        'embedded' => true,
        'header' => 'sole-trader-details-header',
        'form' => $personSearchForm,
    ));

    echo $this->partial('olcs/application/partials/trading-name', array(
        'embedded' => true,
        'header' => 'sole-trader-trading-name',
        'form' => $soleTraderForm,
    ));

?>

    <div class="form-group">
        <button id="cancelbutton" name="cancel" class="btn btn-cancel" type="button"><?php echo $this->resourceHelper('cancel'); ?></button>
        <button id="submitbutton" name="submit" class="btn btn-success btn-save pull-right"><?php echo $this->resourceHelper('save'); ?></button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
