<div class="govuk-width-container">
    <div class="js-body">
        <?php
        echo $this->partial(
            'partials/page-header-simple',
            [
                'pageTitle' => $this->translate($this->title),
                'pageSubTitle' => $this->licNo,
                'backUrl' => [
                    'url' => $this->backLink,
                ],
            ]
        );
        ?>
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-two-thirds">
                <p class="govuk-body"><?php echo $this->translate($this->content); ?></p>
                <?php if ($this->note): ?>
                    <div class="govuk-inset-text">
                        <?php echo $this->translate($this->note); ?>
                    </div>
                <?php endif; ?>
                <?php if (isset($this->form)): ?>
                    <?php
                    $this->form->prepare();
                    echo $this->formErrors($this->form);
                    echo $this->form($this->form);
                    ?>
                <?php endif; ?>

                <?php if (isset($this->vehicleData)): ?>
                    <div class="govuk-phase-banner govuk-!-margin-bottom-6">
                        <h2 class="govuk-heading-m govuk-!-margin-bottom-0">
                            <?php echo $this->translateReplace('licence.vehicle.add.result.header', [$this->vehicleData['registrationNumber']]) ?>
                        </h2>
                    </div>
                    <div class="govuk-inset-text">
                        <?php echo $this->translate('licence.vehicle.add.result.note');?>
                    </div>
                    <?php echo $this->partial('partials/licence/vehicle/vehicle-details', [
                        'vehicleDetails' => $this->vehicleData,
                        'copy' => [
                            'registrationNumberRowHeading' => $this->translate('licence.vehicle.add.result.vrm'),
                            'revenueWeightRowHeading' => $this->translate('licence.vehicle.add.result.weight'),
                            'makeRowHeading' => $this->translate('licence.vehicle.add.result.make'),
                        ],
                    ]); ?>
                    <?php $this->confirmationForm->prepare(); ?>
                    <?php echo $this->form($this->confirmationForm); ?>
                <?php endif; ?>

                <?php
                if (isset($this->bottomLink)): ?>
                    <p>
                        <a href="<?php echo $this->bottomLink ?>">
                            <?php echo $this->translate($this->bottomText); ?>
                        </a>
                    </p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
