<?php $this->form->prepare(); ?>

<div class="govuk-width-container">
    <div class="js-body">
        <?php echo $this->linkBack($this->backUrl); ?>
        <?php if (! empty($this->panel)) { ?>
            <?php echo $this->panel($this->panel['theme'], $this->panel['title'], $this->panel['body'] ?? ''); ?>
        <?php } ?>
        <?php echo $this->partial('partials/page-header-simple', [
            'pageTitle' => $this->translate($this->title),
            'pageSubTitle' => $this->subTitle,
        ]); ?>
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-full">
                <?php echo $this->formErrors($this->form); ?>
                <?php echo $this->form($this->form); ?>
                <p>
                    <?php echo $this->partial(new \Olcs\View\Model\Licence\Vehicle\ViewAndAmendYourLicenceViewModel()); ?>
                </p>
            </div>
        </div>
    </div>
</div>
