<?php
$entity = $this->placeholder('details')->getValue();
$isInternalReadOnly = $this->placeholder('isInternalReadOnly')->getValue();

$actions = [];

if (!$isInternalReadOnly) {
    if ($entity['isApprovable']) {
        $actions[] = [
            'url' => $this->url(null, ['action' => 'approve'], [], true),
            'label' => 'Approve',
            'class' => 'govuk-button',
        ];
    }
    if ($entity['isGeneratable']) {
        $actions[] = [
            'url' => $this->url(null, ['action' => 'generate'], [], true),
            'label' => 'Generate',
            'class' => 'govuk-button',
        ];
    }
    if ($entity['irfoPermitStatus']['id'] === 'irfo_perm_s_pending') {
        $actions[] = [
            'url' => $this->url(null, ['action' => 'withdraw'], [], true),
            'label' => 'Withdraw',
            'class' => 'govuk-button govuk-button--secondary',
        ];
        $actions[] = [
            'url' => $this->url(null, ['action' => 'refuse'], [], true),
            'label' => 'Refuse',
            'class' => 'govuk-button govuk-button--secondary',
        ];
    } else {
        $actions[] = [
            'url' => $this->url(null, ['action' => 'reset'], [], true),
            'label' => 'Reset',
            'class' => 'govuk-button govuk-button--secondary',
        ];
    }
}

echo $this->render('partials/read-only/main',
    [
        'items' => [
            ['label' => 'Permit No', 'value' => $entity['id']],
            ['label' => 'Permit type', 'value' => $entity['irfoGvPermitType']['description'], 'class' => 'full-width'],
            ['label' => 'Year', 'value' => $entity['yearRequired']],
            ['label' => 'Status', 'value' => $entity['irfoPermitStatus']['description']],
            ['label' => 'Create date', 'date' => $entity['createdOn']],
            ['label' => 'In force date', 'date' => $entity['inForceDate'], 'dateFormat' => 'Y-m-d'],
            ['label' => 'Expiry date', 'date' => $entity['expiryDate'], 'dateFormat' => 'Y-m-d'],
            ['label' => 'Fee exempt', 'value' => $entity['isFeeExempt']],
            ['label' => 'Exemption reason', 'value' => $entity['exemptionDetails'], 'class' => 'full-width'],
            ['label' => 'No of copies required', 'numeric' => $entity['noOfCopies']],
        ],
        'actions' => $actions
    ]
);
