<?php
    echo $this->journey("declarations",$completionStatus,$applicationId);

    echo $this->render(
        '/partials/page-header.phtml',
        array(
        'pageTitle' => 'Review & declarations'
        )
    );

?>
<div class="three-quarters">
    <div>
        <h2 class="inline">Application summary</h2>
        <a href="<?php echo $this->url('selfserve/declarations-simple', ['applicationId' => $applicationId]) ?>" class="right-aligned    action--tertiary" target="_blank">View in another window</a>
    </div>
    <?php echo $this->form($form); ?>
</div>
