<?php
    echo $this->journey("declarations",$completionStatus,$applicationId);

    echo $this->render(
        '/partials/page-header.phtml',
        array(
        'pageTitle' => 'Review & declarations'
        )
    );

?>
    <h2>
        <small><a href="<?php echo $currentUrl ?>" class="right-aligned" target="_blank">View in another window</a></small>
        Application summary
    </h2>
<?php

    echo $this->form($form);
?>
