<div class="page-header">
    <div class="page-header__wrapper">
        <h1><?php echo $this->translate($guide . '-title'); ?></h1>
    </div><!-- .page-header__wrapper -->
</div>
<div class="two-thirds">
    <div class="article">
        <?php echo $this->translate('markup-' . $guide); ?>
    </div>
</div>
<div class="one-third sidebar">
    <?php echo $this->translate('markup-support-contact-address'); ?>
</div>
