<?php

switch ($guide) {
    case 'advertising-your-operating-centre-gb-var':
        $identifier = '/guides/Advert_Template_GB_Var.pdf';
        break;
    case 'advertising-your-operating-centre-ni-new':
        $identifier = '/guides/Advert_Template_NI_New.pdf';
        break;
    case 'advertising-your-operating-centre-ni-var':
        $identifier = '/guides/Advert_Template_NI_Var.pdf';
        break;
    default:
        $identifier = '/guides/Advert_Template_GB_New.pdf';
}

$url = $this->url('getfile', ['identifier' => base64_encode($identifier)]);

$this->placeholder('ADVERT_TEMPLATE_LINK')->set($url);

echo $this->partial('pages/guides/default', ['guide' => 'advertising-your-operating-centre']);
