<?php
    $prohibition = $this->placeholder('prohibition')->getValue();
?>
<div class="read-only">
    <div class="read-only__header">
        <h4 class="read-only__title">
            <?php echo $this->translate('Prohibition Detail'); ?>
        </h4>
        <div class="actions-container">
            <a href="<?php echo $this->url('case_prohibition', ['action' => 'index', 'prohibition' => null], [], true); ?>" class="action--secondary right-aligned"><?php echo $this->translate('Return to list'); ?></a>
            <a href="<?php echo $this->url('case_prohibition', ['action' => 'edit'], [], true); ?>" class="action--secondary right-aligned"><?php echo $this->translate('Edit Prohibition'); ?></a>
        </div>
    </div>

    <?php
        echo $this->render('partials/read-only/list',
            [
                'header' => 'Prohibition Detail',
                'actions' => [
                    'url' => ''
                ],
                'items' => [
                    ['label' => 'Prohibition date', 'date' => $prohibition['prohibitionDate']],
                    ['label' => 'Vehicle registration mark', 'value' => $prohibition['vrm']],
                    ['label' => 'Trailer', 'value' => $prohibition['isTrailer']],
                    ['label' => 'Prohibition type', 'value' => $prohibition['prohibitionType']['description']],
                    ['label' => 'Date cleared', 'date' => $prohibition['clearedDate']],
                    ['label' => 'Location prohibition issued', 'value' => $prohibition['imposedAt']]
                ]
            ]
        )
    ?>
</div>