<?php

$case = $this->placeholder('case')->getValue();
$note = $this->placeholder('note')->getValue();

$transportManager = $this->placeholder('transportManager')->getValue();

if (isset($case['licence']) && !empty($case['licence'])): ?>
<?php if ($case['licence']['organisation']): ?>
<div class="small-module">
  <h4 class="title">Operator details</h4>
  <p class="small-module__details">
    <a href="<?php echo $this->url('operator/business-details', ['organisation' => $case['licence']['organisation']['id']], [], true);?>">
        <?php echo $case['licence']['organisation']['name']; ?>
    </a><br>
    <?php echo $this->translate($case['licence']['organisation']['type']['id']); ?><br>
      <?php
      // value checked as errors with minimal applications as trafficArea not set
      echo isset($case['licence']['trafficArea']['name']) ?
          $this->translate($case['licence']['trafficArea']['name']) : '';
      ?><br>
  </p>
</div><!-- end .small-details -->
<?php endif; ?>

<div class="small-module">
  <h4 class="title">Licence details</h4>
    <p class="small-module__details">
      <a href="<?php echo $this->url('lva-licence', ['licence' => $case['licence']['id']], [], false); ?>"><?php echo $case['licence']['licNo']; ?></a><br>
      <?php if (!empty($case['licence']['licenceType']) || count($case['licence']['licenceType']) > 0) : ?>
        <?php echo $this->translate($case['licence']['licenceType']['id']); ?><br/>
      <?php endif; ?>
      <?php if (!empty($case['licence']['status']) || count($case['licence']['status']) > 0) : ?>
        <?php echo $this->translate($case['licence']['status']['id']); ?>
        <?php endif; ?>
    </p>
</div><!-- end .small-details -->
<?php endif; ?>

<?php
if ($transportManager) :
?>
<div class="small-module">
    <h4 class="title">Transport manager details</h4>

    <p class="small-module__details">

    <?php if (isset($transportManager['homeCd']['person'])): ?>
        <p><strong><a href="<?php echo $this->url('transport-manager/details', ['transportManager' => $transportManager['id']], [], true); ?>">
            <?php echo $transportManager['homeCd']['person']['forename']
                . ' ' . $transportManager['homeCd']['person']['familyName']; ?></a></strong>
        </p>
        <p><?php echo $this->date(strtotime($transportManager['homeCd']['person']['birthDate'])); ?></p>

    <?php endif; ?>

    <?php if (isset($transportManager['homeCd']['address'])): ?>
        <p><?php echo $this->addressFormat($transportManager['homeCd']['address']); ?></p>
    <?php endif; ?>

    <?php $tmStatus = $transportManager['tmStatus']['description']; ?>
    <p>
        <span class="status <?php echo strtolower($tmStatus) == 'active' ? 'green' : 'grey'; ?>">
            <?php echo $tmStatus; ?>
        </span>
    </p>
</div>
<?php endif; ?>

<?php
echo $this->showMarkers(
    [
        \Olcs\Service\Marker\CaseAppealMarker::class,
        \Olcs\Service\Marker\CaseStayMarker::class,
        \Olcs\Service\Marker\DisqualificationMarker::class,
    ]
);
?>

<?php if (!empty($note)): ?>
    <div class="latest-note">
        <div class="latest-note__details"><?php echo substr($note, 0, 100); ?></div>
            <a
                class="latest-note__link"
                href="<?php echo $this->url('case_processing_notes', ['case' => $case['id']]); ?>"
            >View all notes</a>
    </div>
<?php endif; ?>
