
<ul class="govuk-service-navigation__list" id="navigation">
  <?php

  foreach ($this->container as $page) {
    if ($page->isVisible() && $this->navigation()->menu()->accept($page)) {
      $activeClass = $page->isActive() ? ' govuk-service-navigation__item--active' : '';
      ?>
      <li class="govuk-service-navigation__item <?php echo $activeClass?>">
        <?php
        if ($page->isActive()) {
          ?>
          <a class="govuk-service-navigation__link" href="<?php echo $page->getHref(); ?>" aria-current="true">
            <strong class="govuk-service-navigation__active-fallback"><?php echo $this->translate($page->getLabel()); ?></strong>
          </a>
          <?php
        }
        else{
          ?>
          <a class="govuk-service-navigation__link" href="<?php echo $page->getHref(); ?>">
            <?php echo $this->translate($page->getLabel()); ?>
          </a>
          <?php
        }
        ?>

      </li>
      <?php
    }
  }

  ?>
</ul>
