<ul id="navigation" class="govuk-header__navigation" aria-label="<?php echo $this->escapeHtml($this->translate('top.level.navigation')); ?>"><?php

foreach ($this->container as $page) {
  if ($page->isVisible()) {
    ?>
    <li class="govuk-header__navigation-item">
      <a href="<?php echo $page->getHref(); ?>" class="govuk-header__link">
        <?php echo $this->escapeHtml($this->translate($page->getLabel())); ?>
      </a>
    </li>
    <?php
  }
}

?></ul>
