<main id="main" role="main">
    <div class="page-header">
        <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partials/breadcrumbs'); ?>
        <div class="page-header__wrapper">
            <h1><?php echo $this->translate('auth.change-password.title'); ?></h1>
            <div class="page-header__text">
                <p><?php echo $this->translate('auth.change-password.subtitle'); ?></p>
            </div>
        </div><!-- .page-header__wrapper -->
    </div><!-- .page-header -->
    <div class="row">
        <div class="two-thirds">
            <?php
            echo $this->flashMessengerAll();
            echo $this->formErrors($form);
            if (isset($failed) && $failed) {
                ?>
                <div class="validation-summary">
                    <h3><?php echo $this->translate('auth.change-password.failed.title'); ?></h3>
                    <p><?php echo $this->translate('auth.change-password.failed.reason.' . $failureReason); ?></p>
                </div>
                <?php
            }

            $oldPassword = $form->get('oldPassword');
            $oldPassword->setAttribute('class', $oldPassword->getAttribute('class') . ' long');

            $newPassword = $form->get('newPassword');
            $newPassword->setAttribute('class', $newPassword->getAttribute('class') . ' long');

            $confirmPassword = $form->get('confirmPassword');
            $confirmPassword->setAttribute('class', $confirmPassword->getAttribute('class') . ' long');

            echo $this->form()->openTag($form); ?>
                <fieldset>
                    <?php echo $this->formRow($form->get('oldPassword')); ?>
                    <?php echo $this->formRow($form->get('newPassword')); ?>
                    <?php echo $this->formRow($form->get('confirmPassword')); ?>
                    <div class="actions-container">
                        <?php echo $this->formElement($form->get('submit')); ?>
                        <?php echo $this->formElement($form->get('cancel')); ?>
                    </div>
                </fieldset>
            <?php echo $this->formElement($form->get('security')); ?>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</main>
