<div id="main" role="main">
    <div class="page-header">
        <div class="page-header__wrapper">
            <h1><?php echo $this->translate('auth.confirm-forgot-password.title'); ?></h1>
        </div><!-- .page-header__wrapper -->
    </div><!-- .page-header -->
    <div class="row">
        <div class="two-thirds">
            <div class="article">
                <?php echo sprintf($this->translate('markup-forgot-password-confirmation'), $email); ?>
            </div><!-- .article -->
        </div><!-- .two-thirds -->
    </div>
</div>
