<main id="main" role="main">
    <?php
    echo $this->partial(
        'partials/page-header-simple', [
            'pageTitle' => $this->translate('auth.confirm-forgot-password.title'),
            'backUrl' => [
                'url' => $this->url('auth/login'),
                'label' => $this->translate('back-to-sign-in'),
            ],
        ]
    );
    ?>    

    <div class="row">
        <div class="two-thirds">
            <div class="article">
                <?php echo $this->translate('markup-forgot-password-confirmation'); ?>
            </div><!-- .article -->
        </div><!-- .two-thirds -->
    </div>
</main>
