<main id="main" role="main">
    <?php
    echo $this->partial(
        'partials/page-header-simple',
        [
            'pageTitle' => $this->translate('auth.expired-password.title'),
            'pageHeaderText' => $this->translate('auth.change-password.subtitle'),
            'pageHeaderTextEscape' => false,
        ]
    );
    ?>

    <div class="row">
        <div class="two-thirds">
            <?php
            echo $this->flashMessengerAll();
            if ($isOpenAM) {
                $oldPassword = $form->get('oldPassword');
                $oldPassword->setAttribute('class', $oldPassword->getAttribute('class') . ' long');
            }

            $newPassword = $form->get('newPassword');
            $newPassword->setAttribute('class', $newPassword->getAttribute('class') . ' long');

            $confirmPassword = $form->get('confirmPassword');
            $confirmPassword->setAttribute('class', $confirmPassword->getAttribute('class') . ' long');

            echo $this->form()->openTag($form); ?>
                <fieldset>
                    <?php if ($isOpenAM) {echo $this->formRow($form->get('oldPassword'));} ?>
                    <?php echo $this->formRow($form->get('newPassword')); ?>
                    <?php echo $this->formRow($form->get('confirmPassword')); ?>
                    <div class="govuk-button-group">
                        <?php echo $this->formElement($form->get('submit')); ?>
                    </div>
                </fieldset>
            <?php echo $this->formElement($form->get('security')); ?>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</main>
