<div id="main" role="main">
    <div class="page-header">
        <div class="page-header__wrapper">
            <h1><?php echo $this->translate('auth.expired-password.title'); ?></h1>
        </div><!-- .page-header__wrapper -->
    </div><!-- .page-header -->
    <div class="row">
        <div class="two-thirds">
            <?php
            echo $this->flashMessengerAll();
            if (isset($failed) && $failed) {
                ?>
                <div class="validation-summary">
                    <h3><?php echo $this->translate('auth.expired-password.failed.title'); ?></h3>
                    <p><?php echo $this->translate('auth.expired-password.failed.reason.' . $failureReason); ?></p>
                </div>
                <?php
            }

            $oldPassword = $form->get('oldPassword');
            $oldPassword->setAttribute('class', $oldPassword->getAttribute('class') . ' long');

            $newPassword = $form->get('newPassword');
            $newPassword->setAttribute('class', $newPassword->getAttribute('class') . ' long');

            $confirmPassword = $form->get('confirmPassword');
            $confirmPassword->setAttribute('class', $confirmPassword->getAttribute('class') . ' long');

            echo $this->form()->openTag($form); ?>
                <fieldset>
                    <div class="field">
                        <?php echo $this->formLabel($form->get('oldPassword')); ?>
                        <?php echo $this->formElement($form->get('oldPassword')); ?>
                    </div>
                    <div class="field">
                        <?php echo $this->formLabel($form->get('newPassword')); ?>
                        <?php echo $this->formElement($form->get('newPassword')); ?>
                    </div>
                    <div class="field">
                        <?php echo $this->formLabel($form->get('confirmPassword')); ?>
                        <?php echo $this->formElement($form->get('confirmPassword')); ?>
                    </div>

                    <div class="actions-container">
                        <?php echo $this->formElement($form->get('submit')); ?>
                    </div>
                </fieldset>
            <?php echo $this->formElement($form->get('security')); ?>
            <?php echo $this->form()->closeTag(); ?>
        </div><!-- .two-thirds -->
        <div class="one-third">
            <?php echo $this->translate('markup-support-contact-address'); ?>
        </div>
    </div>
</div>


<?php echo $this->form()->openTag($form); ?>
