<main id="main" role="main">
    <?php
    echo $this->partial(
        'partials/page-header-simple',
        [
            'pageTitle' => $this->translate('auth.forgot-password.title'),
            'backUrl' => [
                'url' => $this->url('auth/login'),
                'label' => $this->translate('back-to-sign-in'),
            ],
        ]
    );
    ?>

    <div class="row">
        <div class="two-thirds">
            <?php
            echo $this->flashMessengerAll();
            echo $this->formErrors($form);
            if (isset($failed) && $failed) {
                ?>
                <div class="validation-summary">
                    <h3><?php echo $this->translate('auth.forgot-password.failed.title'); ?></h3>
                    <p><?php echo $this->translate('auth.forgot-password.failed.reason.' . $failureReason); ?></p>
                </div>
                <?php
            }

            $username = $form->get('username');
            $username->setAttribute('class', $username->getAttribute('class') . ' long');

            echo $this->form()->openTag($form); ?>
                <fieldset>
                    <?php echo $this->formRow($form->get('username')); ?>
                    <div class="actions-container">
                        <?php echo $this->formElement($form->get('submit')); ?>
                        <?php echo $this->formElement($form->get('cancel')); ?>
                    </div>
                    <div class="actions-container">
                        <a href="<?php echo $this->url('user-forgot-username'); ?>"
                            aria-label="<?php echo $this->translate('auth.forgot-username.label.audio'); ?>">
                            <?php echo $this->translate('auth.forgot-username.label'); ?>
                        </a>
                    </p>
                </fieldset>
            <?php echo $this->formElement($form->get('security')); ?>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</main>
