<main id="main" role="main">

    <div class="page-header">
        <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partials/breadcrumbs'); ?>
        <div class="page-header__wrapper">
            <h1><?php echo $this->translate('auth.forgot-password.title'); ?></h1>
        </div><!-- .page-header__wrapper -->
    </div><!-- .page-header -->
    <div class="row">
        <div class="two-thirds">
            <?php
            echo $this->flashMessengerAll();
            echo $this->formErrors($form);
            if (isset($failed) && $failed) {
                ?>
                <div class="validation-summary">
                    <h3><?php echo $this->translate('auth.forgot-password.failed.title'); ?></h3>
                    <p><?php echo $this->translate('auth.forgot-password.failed.reason.' . $failureReason); ?></p>
                </div>
                <?php
            }

            $username = $form->get('username');
            $username->setAttribute('class', $username->getAttribute('class') . ' long');

            echo $this->form()->openTag($form); ?>
                <fieldset>
                    <?php echo $this->formRow($form->get('username')); ?>
                    <div class="actions-container">
                        <?php echo $this->formElement($form->get('submit')); ?>
                        <?php echo $this->formElement($form->get('cancel')); ?>
                        <a 
                          href="<?php echo $this->url('user-forgot-username'); ?>" 
                          class="action--tertiary list"
                          aria-label="<?php echo $this->translate('auth.forgot-username.label.audio'); ?>"
                        >
                            <?php echo $this->translate('auth.forgot-username.label'); ?>
                        </a>
                    </div>
                </fieldset>
            <?php echo $this->formElement($form->get('security')); ?>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</main>
