
<?php echo $this->partial('partials/page-header-simple', ['pageTitle' => $this->pageTitle()]); ?>

<div class="row">
    <div class="two-thirds">
        <div class="govuk-inset-text">
            <p><?php echo sprintf($this->translate('signin-or-register-text'), $this->url('user-registration')); ?></p>
            <p><?php echo sprintf($this->translate('auth.login.termsAgreed'), $this->url('terms-and-conditions')); ?></p>
            <hr aria-hidden="true">
        </div>
        <?php
        echo $this->flashMessengerAll();
        echo $this->formErrors($form);
        if (isset($failed) && $failed) {
            ?>
            <div class="validation-summary">
                <h2><?php echo $this->escapeHtml($this->translate('auth.login.failed.title')); ?></h2>
                <p><?php echo $this->escapeHtml($this->translate('auth.login.failed.reason.' . $failureReason)); ?></p>
            </div>
            <?php
        }

        $username = $form->get('username');
        $username->setAttribute('class', $username->getAttribute('class') . ' long');

        $password = $form->get('password');
        $password->setAttribute('class', $password->getAttribute('class') . ' long');

        echo $this->form()->openTag($form); ?>
            <fieldset>
                <?php echo $this->formRow($form->get('username')); ?>
                <?php echo $this->formRow($form->get('password')); ?>
                <div class="govuk-button-group">
                    <?php echo $this->formElement($form->get('submit')); ?>
                </div>
                <div>
                    <p><?php echo $this->escapeHtml($this->translate('help-sign-in')); ?></p>
                    <div class="govuk-inset-text">
                        <ul class="govuk-list">
                            <li>
                                <a class="govuk-link" href="<?php echo $this->url('user-forgot-username'); ?>"
                                   aria-label="<?php echo $this->escapeHtml($this->translate('auth.forgot-username.label.audio')); ?>">
                                    <?php echo $this->escapeHtml($this->translate('auth.forgot-username.label')); ?>
                                </a>
                            </li>
                            <li>
                                <a class="govuk-link" href="<?php echo $this->url('auth/forgot-password'); ?>"
                                   aria-label="<?php echo $this->escapeHtml($this->translate('auth.forgot-password.label.audio')); ?>">
                                    <?php echo $this->escapeHtml($this->translate('auth.forgot-password.label')); ?>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </fieldset>
        <?php echo $this->formElement($form->get('security')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
