<main id="main" role="main">
    <div class="page-header">
        <div class="page-header__wrapper">
            <h1><?php echo $this->pageTitle(); ?></h1>
        </div><!-- .page-header__wrapper -->
    </div><!-- .page-header -->
    <div class="row">
        <div class="two-thirds">
            <p><?php echo sprintf($this->translate('signin-or-register-text'), $this->url('user-registration')); ?></p>
            <hr>
            <?php
            echo $this->flashMessengerAll();
            echo $this->formErrors($form);
            if (isset($failed) && $failed) {
                ?>
                <div class="validation-summary">
                    <h3><?php echo $this->translate('auth.login.failed.title'); ?></h3>
                    <p><?php echo $this->translate('auth.login.failed.reason.' . $failureReason); ?></p>
                </div>
                <?php
            }

            $username = $form->get('username');
            $username->setAttribute('class', $username->getAttribute('class') . ' long');

            $password = $form->get('password');
            $password->setAttribute('class', $password->getAttribute('class') . ' long');

            echo $this->form()->openTag($form); ?>
                <fieldset>
                    <?php echo $this->formRow($form->get('username')); ?>
                    <?php echo $this->formRow($form->get('password')); ?>
                    <p><?php echo sprintf($this->translate('auth.login.termsAgreed'), $this->url('terms-and-conditions')); ?></p>
                    <div class="actions-container">
                        <?php echo $this->formElement($form->get('submit')); ?>
                        <a 
                          href="<?php echo $this->url('user-forgot-username'); ?>" 
                          class="action--tertiary list" 
                          aria-label="<?php echo $this->translate('auth.forgot-username.label.audio'); ?>"
                        >
                            <?php echo $this->translate('auth.forgot-username.label'); ?>
                        </a>
                        <a 
                          href="<?php echo $this->url('auth/forgot-password'); ?>" 
                          class="action--tertiary list"
                          aria-label="<?php echo $this->translate('auth.forgot-password.label.audio'); ?>"
                        >
                            <?php echo $this->translate('auth.forgot-password.label'); ?>
                        </a>
                    </div>
                </fieldset>
            <?php echo $this->formElement($form->get('security')); ?>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</main>