<div id="main" role="main">
    <div class="page-header">
        <div class="page-header__wrapper">
            <h1><?php echo $this->translate('auth.login.title'); ?></h1>
        </div><!-- .page-header__wrapper -->
    </div><!-- .page-header -->
    <div class="row">
        <div class="two-thirds">
            <p><?php echo sprintf($this->translate('signin-or-register-text'), $this->url('user-registration')); ?></p>
            <hr>
            <?php
            if (isset($authenticationFailed) && $authenticationFailed) {
                ?>
                <div class="validation-summary">
                    <h3><?php echo $this->translate('auth.login.failed.title'); ?></h3>
                    <p><?php echo $this->translate($authenticationFailureReason); ?></p>
                </div>
                <?php
            }

            $username = $form->get('username');
            $username->setAttribute('class', $username->getAttribute('class') . ' long');

            $password = $form->get('password');
            $password->setAttribute('class', $password->getAttribute('class') . ' long');

            echo $this->form()->openTag($form); ?>
                <fieldset>
                    <div class="field">
                        <?php echo $this->formLabel($form->get('username')); ?>
                        <?php echo $this->formElement($form->get('username')); ?>
                    </div>
                    <div class="field">
                        <?php echo $this->formLabel($form->get('password')); ?>
                        <?php echo $this->formElement($form->get('password')); ?>
                    </div>
                    <div class="actions-container">
                        <?php echo $this->formElement($form->get('submit')); ?>
                        <a href="<?php echo $this->url('auth/forgot-username'); ?>" class="action--tertiary list">
                            Forgotten your username?
                        </a>
                        <a href="<?php echo $this->url('auth/forgot-password'); ?>" class="action--tertiary list">
                            Forgotten your password?
                        </a>
                    </div>
                </fieldset>
            <?php echo $this->formElement($form->get('security')); ?>
            <?php echo $this->form()->closeTag(); ?>
        </div><!-- .two-thirds -->
        <div class="one-third">
            <?php echo $this->translate('markup-support-contact-address'); ?>
        </div>
    </div>
</div>