<?php
$revoke = $this->placeholder('proposeToRevoke')->getValue();
?>

<h4><?php echo $this->translate($this->navigation('navigation')->findOneBy('active', 1)->getLabel()); ?>
    <?php
    if (empty($revoke)){
    ?>
    <a href="<?php echo $this->url(
        'processing_in_office_revocation',
        [
            'action' => 'add'
        ], [], true); ?>" class="action--secondary
        right-aligned"><?php echo $this->translate('Add in office revocation'); ?></a>
</h4>

<?php
} else {
    ?>
    <a href="<?php echo $this->url(
        'processing_in_office_revocation',
        [
            'revoke' => $revoke['id'],
            'action' => 'edit'
        ], [], true); ?>" class="action--secondary
        right-aligned"><?php echo $this->translate('Edit in office revocation'); ?></a>
    </h4>

    <div class="read-only">
        <dl>
            <dt><?php echo $this->translate('Legislation');?></dt>
            <dd class="three-quarters">
                <?php
                    foreach ($revoke['reasons'] as $reason) {
                        echo $reason['sectionCode'] . ' - ' . $reason['description'] .'<br />';
                    }
                ?>
            </dd>
        </dl>
        <dl>
            <dt><?php echo $this->translate('TC/TDC agreed');?></dt>
            <dd><?php echo $revoke['presidingTc']['name']; ?></dd>
        </dl>
        <dl>
            <dt><?php echo $this->translate('Agreed date');?></dt>
            <dd><?php echo $revoke['ptrAgreedDate']; ?></dd>
        </dl>
        <dl>
            <dt><?php echo $this->translate('Closed date');?></dt>
            <dd><?php echo $revoke['closedDate']; ?></dd>
        </dl>
        <dl>
            <dt><?php echo $this->translate('Notes');?></dt>
            <dd class="three-quarters"><?php echo
                $revoke['comment'];
                ?></dd>
        </dl>
    </div>
<?php
    }
?>
