<?php
    echo $this->render(
        '/partials/page-header.phtml',
        array(
            'pageTitle' => $this->translate('dashboard.title'),
            'pageSubTitle'=> $this->translate('dashboard.subtitle'),
        )
    );
?>
<div class="three-quarters">
    <?php echo $applicationsTable; ?>
    <div class="actions-container">
        <a href="<?php echo $this->url('home/dashboard', array('action' => 'create')); ?>" class="action--primary large">
            <?php echo $this->translate('application.new.button'); ?>
        </a>
    </div>
</div>
<div class="one-quarter">
    <h3>Notifications</h3>
</div>
