################################################################
#
#   delete OLCS history (part 2).
#
################################################################

SET @monthago = CURRENT_TIMESTAMP(6) - INTERVAL 4 WEEK;
SET @starttimestamp = CURRENT_TIMESTAMP(6);

SELECT CONCAT(now(),' delete history (part 2)...') AS '';

DELETE FROM message_failures_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM note_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM oc_complaint_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM operating_centre_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM operating_centre_opposition_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM opposer_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM opposition_grounds_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM opposition_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM organisation_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM organisation_person_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM organisation_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM organisation_user_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM other_licence_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM permission_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM person_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM phone_contact_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM pi_decision_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM pi_definition_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM pi_hearing_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM pi_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM pi_reason_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM pi_tm_decision_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM pi_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM postcode_enforcement_area_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM presiding_tc_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM previous_conviction_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM printer_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM private_hire_licence_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM prohibition_defect_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM prohibition_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM propose_to_revoke_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM psv_disc_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM ptr_reason_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM publication_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM publication_link_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM publication_police_data_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM publication_section_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM public_holiday_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM question_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM question_text_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM queue_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM reason_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM recipient_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM recipient_traffic_area_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM ref_data_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM replacement_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM role_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM role_permission_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM s4_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM scan_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM sectors_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM serious_infringement_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM si_category_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM si_category_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM si_penalty_erru_imposed_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM si_penalty_erru_requested_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM si_penalty_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM si_penalty_imposed_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM si_penalty_requested_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM si_penalty_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM sla_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM sla_target_date_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM statement_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM stay_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM submission_action_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM submission_action_reason_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM submission_action_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM submission_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM submission_section_comment_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM sub_category_description_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM sub_category_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM surrender_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM system_info_message_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM system_parameter_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM tag_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM task_allocation_rule_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM task_alpha_split_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM task_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM team_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM team_printer_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM template_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM template_test_data_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM tm_case_decision_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM tm_case_decision_rehab_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM tm_case_decision_unfitness_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM tm_employment_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM tm_qualification_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM trading_name_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM traffic_area_enforcement_area_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM traffic_area_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM trailer_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM translation_key_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM translation_key_text_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM transport_manager_application_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM transport_manager_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM transport_manager_licence_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM txc_inbox_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM txn_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM user_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM user_role_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM vehicle_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM venue_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM workshop_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM messaging_message_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM messaging_content_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM messaging_conversation_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM messaging_subject_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM messaging_user_message_read_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;


SELECT CONCAT(now(), ' ...delete history (part 2) complete.') as '';
