################################################################
#
#   delete OLCS history (part 1).
#
################################################################

SET @monthago = CURRENT_TIMESTAMP(6) - INTERVAL 4 WEEK;
SET @starttimestamp = CURRENT_TIMESTAMP(6);

SELECT CONCAT(now(),' delete history (part 1)...') AS '';

DELETE FROM address_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM admin_area_traffic_area_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM answer_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM appeal_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM application_completion_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM application_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM application_operating_centre_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM application_organisation_person_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM application_path_group_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM application_path_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM application_step_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM application_tracking_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM application_validation_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM bus_notice_period_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM bus_reg_bus_service_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM bus_reg_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM bus_reg_local_auth_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM bus_reg_other_service_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM bus_reg_traffic_area_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM bus_reg_variation_reason_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM bus_service_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM bus_short_notice_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM cases_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM case_category_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM case_outcome_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM category_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM change_of_entity_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM community_lic_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM community_lic_suspension_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM community_lic_suspension_reason_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM community_lic_withdrawal_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM community_lic_withdrawal_reason_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM companies_house_alert_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM companies_house_alert_reason_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM companies_house_company_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM companies_house_insolvency_practitioner_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM companies_house_officer_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM company_subsidiary_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM complaint_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM condition_undertaking_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM contact_details_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM continuation_detail_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM continuation_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM conviction_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM correspondence_inbox_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM country_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM data_retention_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM data_retention_rule_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM decision_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM digital_signature_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM disc_sequence_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM disqualification_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM document_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM doc_bookmark_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM doc_paragraph_bookmark_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM doc_paragraph_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM doc_template_bookmark_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM doc_template_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM ebsr_route_reprint_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM ebsr_submission_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM enforcement_area_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM erru_request_failure_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM erru_request_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM event_history_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM feature_toggle_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM fee_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM fee_txn_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM fee_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM financial_standing_rate_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM goods_disc_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM grace_period_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM hearing_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM impounding_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM impounding_legislation_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM inspection_email_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM inspection_request_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irfo_country_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irfo_gv_permit_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irfo_gv_permit_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irfo_partner_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irfo_permit_stock_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irfo_psv_auth_country_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irfo_psv_auth_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irfo_psv_auth_number_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irfo_psv_auth_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irfo_vehicle_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_application_country_link_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_application_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_candidate_permit_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_permit_application_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_permit_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_permit_jurisdiction_quota_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_permit_range_attribute_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_permit_range_country_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_permit_range_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_permit_request_attribute_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_permit_request_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_permit_sector_quota_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_permit_stock_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_permit_type_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM irhp_permit_window_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM language_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM legacy_case_action_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM legacy_offence_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM legacy_pi_reason_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM legacy_recommendation_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM legacy_recommendation_pi_reason_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM licence_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM licence_no_gen_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM licence_operating_centre_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM licence_status_decision_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM licence_status_rule_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM licence_vehicle_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;
DELETE FROM local_authority_hist WHERE hist_timestamp > @startdatetime OR hist_timestamp < @monthago;

SELECT CONCAT(now(), ' ...delete history (part 1) complete.') as '';
