<?php

$case = $this->placeholder('case')->getValue();
$submission = $this->placeholder('submission')->getValue();
$submissionTitle = $this->placeholder('submissionTitle')->getValue();
$sectionData = $this->placeholder('sectionData')->getValue();
?>
<h4><?php echo $submission['submissionTypeTitle']; ?>
    <a href="<?php echo $this->url(
        'submission', [
            'case' => $case['id'],
            'action' => 'edit',
            'submission' => $submission['id']
        ]
        );?>" class="action--secondary right-aligned">
        <?php echo
        $this->translate('Edit submission');
        ?></a>
</h4>
<?php

foreach ($sectionData as $sectionId => $sectionData) {

    echo $this->submissionSectionDetails($sectionId, $sectionData);

}
?>
