<ul class="horizontal-navigation" role="tablist">
  <li class="horizontal-navigation__item current">Application details</li>
  <li class="horizontal-navigation__item">
    <a href="cases.html">Cases</a>
  </li>
  <li class="horizontal-navigation__item">
    <a href="environmental.html">Environmental</a>
  </li>
  <li class="horizontal-navigation__item">
    <a href="docs&amp;attachments.html">Docs &amp; attachments</a>
  </li>
  <li class="horizontal-navigation__item">
    <a href="tasks.html">Processing</a>
  </li>
  <li class="horizontal-navigation__item">
    <a href="fees.html">Fees</a>
  </li>
</ul>