<h5>Quick actions</h5>
<ul class="record-actions__group">
  <li class="record-actions__item action--secondary"><a href="">Generate publication</a></li>
  <li class="record-actions__item action--secondary"><a href="">Add recommendation</a></li>
  <li class="record-actions__item action--secondary"><a href="">Create case</a></li>
</ul>
<?php if ($showGrant || $showUndoGrant) : ?>
<h5>Decisions</h5>
<ul class="record-actions__group">
    <?php if ($showGrant) : ?>
    <li class="record-actions__item action--secondary"><a href="">Grant application</a></li>
    <?php endif; ?>
    <?php if ($showUndoGrant) : ?>
    <li class="record-actions__item action--secondary"><a href="">Undo grant application</a></li>
    <?php endif; ?>
</ul>
<?php endif;
