<div class="one-fifth--left">
    <h4><?php echo $this->translate('application-details-nav'); ?></h4>
    <ul class="app-navigation" role="menu">
        <?php foreach ($sections as $reference => $details) : ?>
            <?php
            $current = false;
            if ($details['route'] === $currentRoute) {
                $current = true;
                $details['class'] = 'current ' . $details['class'];
            }
            ?>
            <li class="app-navigation__item <?php echo $details['class']; ?> <?php echo $details['enabled'] ? '' : 'disabled'; ?>">
                <?php if (!$current && $details['enabled']) : ?>
                    <a href="<?php echo $this->url($details['route'], ['application' => $lvaId]); ?>">
                <?php endif; ?>
                <?php echo $this->translate('section.name.' . $reference); ?>
                <?php if (!$current && $details['enabled']) : ?>
                    </a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul><!-- end .progress -->
    <?php if ($currentRoute == 'lva-application/vehicles' && isset($filterForm)): ?>
        <?php echo $this->form($filterForm); ?>
    <?php endif; ?>
</div>
<div class="three-fifths">
  <?php echo $this->flashMessengerAll(); ?>
  <?php echo $this->content; ?>
</div>
