<div class="one-fifth--left">
  <h4>Application details</h4>
  <ul class="app-navigation items-8" role="menu">
    <li class="app-navigation__item current no-background">
      <span>Overview</span>
    </li>
    <li class="app-navigation__item complete">
      <a href=""><span>Type of licence</span></a>
    </li>
    <li class="app-navigation__item complete js-hidden">
      <a href=""><span>Business details</span></a>
    </li>
    <li class="app-navigation__item complete">
      <a href=""><span>Addresses</span></a>
    </li>
    <li class="app-navigation__item incomplete">
      <a href=""><span>People</span></a>
    </li>
    <li class="app-navigation__item incomplete">
      <a href=""><span>Operating centres &amp; authorisation</span></a>
    </li>
    <li class="app-navigation__item incomplete">
      <a href=""><span>Transport managers</span></a>
    </li>
    <li class="app-navigation__item disabled">
      <span>Vehicles</span>
    </li>
    <li class="app-navigation__item ">
      <a href=""><span>Safety</span></a>
    </li>
    <li class="app-navigation__item disabled">
      <span>Convictions &amp; penalties</span>
    </li>
    <li class="app-navigation__item disabled">
      <span>Delarations</span>
    </li>
  </ul><!-- end .progress -->
</div>
<div class="three-fifths">
  <?php echo $this->content; ?>
</div>