<div class="one-fifth--left">
    <h4><?php echo $this->translate('application-details-nav'); ?></h4>
    <ul class="app-navigation items-8" role="menu">
        <?php foreach ($sections as $reference => $details) : ?>
            <?php
            if ($details['current']) {
                $details['class'] = 'current ' . $details['class'];
            }
            ?>
            <li class="app-navigation__item <?php echo $details['class']; ?>">
                <?php if (!$details['current']) : ?>
                    <a href="<?php echo $this->url('lva-application/' . $reference, array(), array(), true); ?>">
                <?php endif; ?>
                <span><?php echo $this->translate('section.name.' . $reference); ?></span>
                <?php if (!$details['current']) : ?>
                    </a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul><!-- end .progress -->
</div>
<div class="three-fifths">
  <?php echo $this->content; ?>
</div>