<div class="one-fifth--left">
    <h4><?php echo $this->translate('internal-licence-details'); ?></h4>
    <?php echo $this->navigation($navigation)->menu()->setPartial('layout/partials/subNavigation'); ?>
</div>
<div class="three-fifths">
    <h4><?php echo $this->translate('internal-licence-details-' . $this->section); ?></h4>
    <?php echo $this->flashMessengerAll(); ?>
    <?php echo $this->content; ?>
</div>
<?php

if (isset($scripts)) {
    foreach ($scripts as $script) {
        $this->inlineScript()->appendScript($script);
    }
}
