<table class="govuk-table">
    <caption class="govuk-table__caption govuk-heading-s"><?php echo $copy['title'] ?? $this->translate('licence.vehicle.partial.summary-table.title'); ?></caption>
    <thead class="govuk-table__head">
    <tr class="govuk-table__row">
        <th scope="col" class="govuk-table__header"><?php echo $copy['attributesColumnHeading'] ?? $this->translate('licence.vehicle.partial.summary-table.attributesColumnHeading'); ?></th>
        <th scope="col" class="govuk-table__header"><?php echo $copy['valuesColumnHeading'] ?? $this->translate('licence.vehicle.partial.summary-table.valuesColumnHeading'); ?></th>
    </tr>
    </thead>
    <tbody class="govuk-table__body">
    <tr class="govuk-table__row">
        <th scope="row" class="govuk-table__header"><?php echo $copy['registrationNumberRowHeading'] ?? $this->translate('licence.vehicle.partial.summary-table.registrationNumberRowHeading'); ?>:</th>
        <td class="govuk-table__cell">
            <?php echo $this->escapeHtml($vehicleDetails['registrationNumber']) ?>
        </td>
    </tr>
    <tr class="govuk-table__row">
        <th scope="row" class="govuk-table__header"><?php echo $copy['revenueWeightRowHeading'] ?? $this->translate('licence.vehicle.partial.summary-table.revenueWeightRowHeading'); ?>:</th>
        <td class="govuk-table__cell">
            <?php echo $this->escapeHtml(number_format($vehicleDetails['revenueWeight'])) ?>
        </td>
    </tr>
    <tr class="govuk-table__row">
        <th scope="row" class="govuk-table__header"><?php echo $copy['makeRowHeading'] ?? $this->translate('licence.vehicle.partial.summary-table.makeRowHeading'); ?>:</th>
        <td class="govuk-table__cell">
            <?php echo $this->escapeHtml($vehicleDetails['make']) ?>
        </td>
    </tr>
    </tbody>
</table>
