<?php
// Note: Header date is deliberately hard coded
$data = $this->placeholder('details')->getValue();

echo $this->render('partials/read-only/main',
    [
        'header' => 'Data correct as of 4th November 2011 17:00',
        'items' => [
            ['label' => 'Historical tm id', 'value' => $data['historicId']],
            ['label' => 'Name', 'date' => $data['forename'] . ' ' . $data['familyName']],
            ['label' => 'DOB', 'date' => $data['birthDate']],
            ['label' => 'Qualification type', 'value' => $data['qualificationType']],
            ['label' => 'No of CPC/exemption', 'value' => $data['certificateNo'], 'class' => 'full-width'],
        ]
    ]
);

echo $this->placeholder('applicationsTable')->getValue();

echo $this->placeholder('licencesTable')->getValue();



