<?php

$currentSection = $this->navigation('navigation')->findOneBy('active', 1);
$currentSectionParent = $currentSection->getParent();

?>

<div class="one-fifth--left">
    <h4><?php echo $this->translate($currentSection->getLabel()); ?></h4>
    <?php echo $this->navigation($currentSectionParent)->menu()->setPartial('layout/partials/subNavigation'); ?>
</div>
<div class="three-fifths">
    <h4><?php echo $this->translate($this->navigation('navigation')->findOneBy('active', 1)->getLabel()); ?>
        <a href="<?php $this->url('case', ['case' => $case['id'], 'action' => 'overview'], [], true); ?>" class="action--secondary right-aligned"><?php echo $this->translate('Edit Case'); ?></a>
    </h4>
    <?php echo $this->flashMessengerAll(); ?>
    <?php echo $this->content; ?>
</div>