<?php
    echo $this->render(
        '/partials/page-header.phtml',
        array(
            'pageTitle' => 'Licence: ' . $this->licenceData['licNo'],
            'pageSubTitle'=> $this->licenceData['goodsOrPsv']['id'] . ', ' . $this->licenceData['licenceType']['id']
            . ', ' . $this->licenceData['status']['id']
        )
    );
?>

<div class="full-width">

    <?php
        echo $this->navigation('navigation')
                  ->menu($this->navigation()->findOneBy('id', 'licence'))
                  ->setUlClass('horizontal-navigation')
                  ->setAddClassToListItem(true)
                  ->setPartial('layout/partials/tabs');
    ?>

    <?php echo $table; ?>
</div><!-- end .full-width -->
