<?php
    echo $this->render(
        '/partials/page-header.phtml',
        array(
        'pageTitle' => 'Cases',
        'pageSubTitle'=> 'Cases associated with: ' . $data['organisation']
        )
    );
?>

<div class="full-width">

    <?php
        echo $this->navigation('navigation')
                  ->menu($this->navigation()->findOneBy('id', 'licence'))
                  ->setUlClass('horizontal-navigation')
                  ->setAddClassToListItem(true)
                  ->setPartial('licence/partials/tabs');
    ?>

    <?php echo $table; ?>
</div><!-- end .full-width -->
