<div class="full-width">

    <?php echo $this->render('partials/summary/case-summary', ['items' => $summary, 'title' => 'Case summary information']); ?>

    <?php echo $this->render('partials/mega-menu/mega-menu', ['items' => $tabs, 'current' => $tab]); ?>

     <?php
        /* echo $this->navigation('navigation')
                  ->menu($this->navigation()->findOneBy('id', 'licence_cases'))
                  ->setUlClass('horizontal-navigation')
                  ->setAddClassToListItem(true)
                  ->setPartial('licence/partials/tabs'); */
    ?>

</div><!-- end .full-width -->

<?php

$array = (array)$this->vars();

if (isset($table)) {
    $array['table'] = $table;
}

if($tab == 'stays') {
    $array['stayTypes'] = $stayTypes;
    $array['stayRecords'] = $stayRecords;
    $array['appealRecord'] = $appealRecord;
}

echo $this->render('case/page/' .$tab, $array); ?>
