<?php $case = $this->placeholder('case')->getValue(); ?>

<h4><?php echo $this->translate($this->navigation('navigation')->findOneBy('active', 1)->getLabel()); ?>
    <a href="<?php echo $this->url('case', ['case' => $case['id'], 'action' => 'edit'], [], false); ?>" class="action--secondary right-aligned"><?php echo $this->translate('Edit Case'); ?></a>
</h4>

<div class="read-only">
    <!-- <div class="read-only__header">
    Header
    </div> -->
        <dl>
            <dt>Open Date:</dt>
            <dd><?php echo $this->dateFormat(\DateTime::createFromFormat(\DateTime::ISO8601, $case['openDate']), \IntlDateFormatter::GREGORIAN); ?></dd>
            <dt>ECMS</dt>
            <dd><?php echo $case['ecmsNo']; ?></dd>
            <dt>Description</dt>
            <dd><?php echo $case['description']; ?></dd>

        </dl>
        <dl>
            <dt>Categories:</dt>
            <dd class="three-quarters"><?php echo is_array($case['submissionSections']) ? implode(', ', array_map(function($item){return $item['description'];}, $case['submissionSections'])) : 'None selected'; ?></dd>

        </dl>
</div>

<div class="read-only">
    <h4>
        Last Submission
        <a href="<?php echo $this->url('case', ['case' => $case['id'], 'action' => 'edit'], [], false); ?>" class="action--secondary right-aligned"><?php echo $this->translate('Edit Submission'); ?></a>
    </h4>
        <dl>
            <dt>Submission no.</dt>
            <dd>1234</dd>
            <dt>Type</dt>
            <dd>Lorem ispum</dd>
            <dt>Date created</dt>
            <dd>13:01 12 May 2014</dd>
            <dt>Date closed</dt>
            <dd>N/a</dd>
            <dt>Currently with</dt>
            <dd>Kevin Rooney</dd>
            <dt>Note</dt>
            <dd>This section contains test data.</dd>
        </dl>
</div>
