<?php

$case = $this->placeholder('case')->getValue();
$categories = is_array($case['submissionSections']) ? implode(', ', array_map(function($item){return $item['description'];}, $case['submissionSections'])) : 'None selected';

//case overview
echo $this->render('partials/read-only/main',
    [
        'header' => $this->navigation('navigation')->findOneBy('active', 1)->getLabel(),
        'actions' => [
            [
                'label' => 'Edit case',
                'url' => $this->url('case', ['case' => $case['id'], 'action' => 'edit'], [], false)
            ],
        ],
        'items' => [
            ['label' => 'Open date', 'date' => $case['openDate']],
            ['label' => 'ECMS', 'value' => $case['ecmsNo']],
            ['label' => 'Description', 'value' => $case['description'], 'class' => 'full-width'],
            ['label' => 'Categories', 'value' => $categories, 'class' => 'full-width']
        ]
    ]
);

//last submission
echo $this->render('partials/read-only/main',
    [
        'header' => 'Last Submission',
        'actions' => [
            [
                'label' => 'Edit submission',
                'url' => $this->url('case', ['case' => $case['id'], 'action' => 'edit'], [], false)
            ],
        ],
        'items' => [
            ['label' => 'Submission no.', 'value' => '1234'],
            ['label' => 'Type', 'value' => 'Lorem ispum'],
            ['label' => 'Date created', 'value' => '17/05/2014'],
            ['label' => 'Date closed', 'value' => 'N/a'],
            ['label' => 'Currenly with', 'value' => 'Kevin Rooney'],
            ['label' => 'Note', 'value' => 'This section contains test data.', 'class' => 'full-width']
        ]
    ]
);

?>

<div class="read-only">
    <h4>
        Last Submission
        <a href="<?php echo $this->url('case', ['case' => $case['id'], 'action' => 'edit'], [], false); ?>" class="action--secondary right-aligned"><?php echo $this->translate('Edit Submission'); ?></a>
    </h4>
        <dl>
            <dt>Submission no.</dt>
            <dd>1234</dd>
            <dt>Type</dt>
            <dd>Lorem ispum</dd>
            <dt>Date created</dt>
            <dd>13:01 12 May 2014</dd>
            <dt>Date closed</dt>
            <dd>N/a</dd>
            <dt>Currently with</dt>
            <dd>Kevin Rooney</dd>
            <dt>Note</dt>
            <dd>This section contains test data.</dd>
        </dl>
</div>
