<?php
echo $this->render(
    'partials/page-header.phtml',
    array(
        'pageTitle' => 'Case',
        'pageSubTitle' => $case['licence']['organisation']['name'] . ' ' . '#' . $case['licence']['licNo'],
        'caseId' => $case['id']
    )
);
?>

<div class="full-width">

    <?php echo $this->render('partials/summary/case-summary', ['items' => $summary, 'title' => 'Case summary information']); ?>

    <?php echo $this->render('partials/mega-menu/mega-menu', ['items' => $tabs, 'current' => $tab]); ?>

    <div class="table__header">
        <h3><?php echo $this->translate('offence-detail');?></h3>

        <?php
            if (!($offence)) {
                echo '<p>' . $this->translate('offence-not-found') . '</p>';
            } else {
                $offenceDate = new \DateTime($offence['offenceDate']);
                $offenceToDate = new \DateTime($offence['offenceToDate']);

               echo $this->render(
                    'partials/case/summary-row.phtml',
                    array(
                        'heading' => 'offence-date-from',
                        'content' => $offenceDate->format('d/m/Y')
                    )
               );
               echo $this->render(
                    'partials/case/summary-row.phtml',
                    array(
                        'heading' => 'offence-date-to',
                        'content' => $offenceToDate->format('d/m/Y')
                    )
               );
               echo $this->render(
                    'partials/case/summary-row.phtml',
                    array(
                        'heading' => 'number-of-offences',
                        'content' => $offence['numOfOffences']
                    )
               );
               echo $this->render(
                    'partials/case/summary-row.phtml',
                    array(
                        'heading' => 'originating-authority',
                        'content' => $offence['offenceAuthority']
                    )
               );
               echo $this->render(
                    'partials/case/summary-row.phtml',
                    array(
                        'heading' => 'offender-name',
                        'content' => $offence['offenderName']
                    )
               );
               echo $this->render(
                    'partials/case/summary-row.phtml',
                    array(
                        'heading' => 'position',
                        'content' => $offence['position']
                    )
               );
               echo $this->render(
                    'partials/case/summary-row.phtml',
                    array(
                        'heading' => 'VRM',
                        'content' => $offence['vrm']
                    )
               );
               echo $this->render(
                    'partials/case/summary-row.phtml',
                    array(
                        'heading' => 'trailer',
                        'content' => $offence['isTrailer']
                    )
               );
               echo $this->render(
                    'partials/case/summary-row.phtml',
                    array(
                        'heading' => 'operator',
                        'content' => $case['licence']['organisation']['name']
                    )
               );
               echo $this->render(
                    'partials/case/summary-row.phtml',
                    array(
                        'heading' => 'offence-type',
                        'content' => $offence['offenceType']
                    )
               );
               echo $this->render(
                    'partials/case/summary-row.phtml',
                    array(
                        'heading' => 'offence-definition',
                        'content' => $offence['definition']
                    )
               );
               echo $this->render(
                    'partials/case/summary-row.phtml',
                    array(
                        'heading' => 'offence-notes',
                        'content' => $offence['notes']
                    )
               );
           }
        ?>
    </div>

</div><!-- end .full-width -->


