<?php
echo $this->render(
    'partials/page-header.phtml',
    array(
        'pageTitle' => 'Case',
        'pageSubTitle' => $case['licence']['organisation']['name'] . ' ' . '#' . $case['licence']['licenceNumber'],
        'caseId' => $case['id']
    )
);
?>

<div class="full-width">

    <?php echo $this->render('partials/summary/case-summary', ['items' => $summary, 'title' => 'Case summary information']); ?>

    <?php echo $this->render('partials/mega-menu/mega-menu', ['items' => $tabs, 'current' => $tab]); ?>

    Offence details

</div><!-- end .full-width -->


