<?php echo $this->render(
    'partials/read-only/main',
    [
        'header' => 'pay-fees.success.header',
        'multiItems' => [
            [
                [
                    'label' => 'pay-fees.success.operator-name',
                    'value' => $operatorName,
                ],
                [
                    'label' => 'pay-fees.success.paid-by',
                    // payer is only recorded against fees, not payment record
                    'value' => $fees[0]['payerName'],
                ],
                [
                    'label' => 'pay-fees.success.payment-reference',
                    'value' => $payment['guid'],
                ],
                [
                    'label' => 'pay-fees.success.received',
                    'date' => $payment['completedDate'],
                ],
            ],
          ],
      ]
);?>