<?php echo $this->render(
    'partials/read-only/main',
    [
        'header' => 'pay-fees.success.header',
        'multiItems' => [
            [
                [
                    'label' => 'pay-fees.success.operator-name',
                    'value' => $operatorName,
                ],
                // 'paid by' descoped from OLCS-8792
                [
                    'label' => 'pay-fees.success.payment-reference',
                    'value' => $payment['reference'],
                ],
                [
                    'label' => 'pay-fees.success.received',
                    'date' => $payment['completedDate'],
                ],
            ],
          ],
      ]
);?>