<?php

echo $this->journey($journey, $completionStatus, $applicationId);

if (!empty($subSections)) {
    ?>
<!-- Vertical navigation -->
<div class="one-quarter">
    <ol class="vertical-navigation" role="navigation">
        <?php
        $subsectionNumber = 1;
        foreach ($subSections as $key => $subSection) {

            $label = $this->translate($subSection['label']);

            if ($subSection['active'] || $subSection['disabled']) {
                ?>
                <li class="current vertical-navigation__item">
                    <?php echo $subsectionNumber . '. ' . $label; ?>
                </li>
                <?php
            } else {
                ?>
                <li class="vertical-navigation__item">
                    <a href="<?php echo $this->url($subSection['route'], $subSection['routeParams']); ?>">
                        <?php echo $subsectionNumber . '. ' . $label; ?>
                    </a>
                </li>
                <?php
            }
            $subsectionNumber++;
        }

        ?>
    </ol><!-- end .vertical-navigation -->
</div><!-- end .one-quarter -->
<div class="three-quarters">
    <?php
} else {
    ?>
<div class="full-width">
    <?php
}

?>
    <?php echo $this->main; ?>
</div>
