<?php echo $this->doctype(); ?>
<?php
/**
 * Simplified layout; will probably be used for print pages but not always
 * exclusively. Removes standard headers & footers
 */
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('')); ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php /* echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')); */
                echo $this->headLink()->appendStylesheet($this->basePath() . '/static/stylesheets/main.css') ?>

    </head>

    <body class="<?php echo $this->applicationName(); ?>">

	<div class="page-wrapper">
        <div id="main" role="main">
            <?php
            echo $this->content;

            if (isset($this->children)) {
                foreach ($this->children as $child) {
                    echo $this->$child;
                }
            }
            ?>
        </div>
    </div><!-- .page-wrapper-->
    </body>
</html>
