<?php

echo $this->navigation;

if (!empty($subSections)) {
    ?>
<!-- Vertical navigation -->
<div class="one-quarter">
    <h4><?php echo $this->translate('In this section'); ?></h4>
    <ol class="vertical-navigation" role="navigation">
        <?php
        foreach ($subSections as $key => $subSection) {
            ?>
            <li class="<?php echo $subSection['class']; ?> vertical-navigation__item">
                <?php
                if ($subSection['link']) {
                    ?>
                    <a href="<?php echo $this->url(
                        $subSection['route'],
                        (isset($subSection['routeParams']) ? $subSection['routeParams'] : array())
                    ); ?>">
                    <?php
                }
                echo $this->translate($subSection['label']);

                if ($subSection['link']) {
                    ?>
                    </a>
                    <?php
                }

                if ($subSection['subAction']) {
                    ?>
                        <ul>
                            <li><?php echo $this->translate($subSection['subAction']); ?></li>
                        </ul>
                    <?php
                }
                ?>
            </li>
            <?php
        }
        ?>
    </ol><!-- end .vertical-navigation -->
</div><!-- end .one-quarter -->
<div class="three-quarters">
    <?php
} else {
    ?>
<div class="full-width">
    <?php
}

?>
    <?php echo $this->main; ?>
</div>
