<p>I understand that by signing this declaration:</p>
<ul class="list--bullet">
  <li>I am confirming that the details on my licence are correct.</li>
  <li>I have submitted changes to update any licence details that are incorrect</li>
  <li>I have read and understood the conditions recorded on the licence.</li>
  <li>I have read, understood and accept the undertakings recorded on my licence.</li>
  <li>In respect of each operating centre specified, that the number of vehicles and the number of trailers kept there will not exceed the maximum numbers authorised at each operating centre (which will be noted on the licence);</li>
  %s
  <li>I must be able to prove that I have a formal arrangement for access at all times to at least one vehicle registered or in circulation in GB. This could be by specifying a vehicle for use under an operator's licence or by demonstrating on request that I (the licence holder) have a vehicle available, so that vehicles may be either wholly owned or held under a hire-purchase, hire / leasing or other type of formal arrangement;</li>
  <li>I have an establishment in Great Britain (GB) with premises in which I keep core business documents. These include (as a minimum) accounting and personnel management documents and data on driving time and rest. I understand that the use of a PO Box or third party address is not permitted.</li>
</ul>
%s
