<p>I understand that by signing this declaration:</p>
<ul class="list--bullet">
  <li>I am confirming that the details on my licence are correct.</li>
  <li>I have submitted changes to update any licence details that are incorrect</li>
  <li>I have read and understood the conditions recorded on my licence.</li>
  <li>I have read, understood and accept the undertakings recorded on my licence.</li>
  <li>In respect of each operating centre specified, that the number of vehicles and the number of trailers kept there will not exceed the maximum numbers authorised at each operating centre (which will be noted on the licence);</li>
  <li>I must be able to prove that I have a formal arrangement for access at all times to at least one vehicle registered or in circulation in GB. This could be by specifying a vehicle for use under an operator's licence or by demonstrating on request that I (the licence holder) have a vehicle available, so that vehicles may be either wholly owned or held under a hire-purchase, hire / leasing or other type of formal arrangement;</li>
  <li>I have an establishment in Great Britain (GB) with premises in which I keep core business documents. These include (as a minimum) accounting and personnel management documents and data on driving time and rest. I understand that the use of a PO Box or third party address is not permitted.</li>
</ul>
<p>The licence is issued subject to the following conditions:</p>
<p>a) That the licence holder, shall, within 28 days of their occurrence, inform the traffic commissioner of any:</p>
<ul class="list--bullet">
  <li>Changes in the maintenance and safety inspection arrangements;</li>
  <li>Changes in the ability to ensure authorised vehicles are being operated safely and not causing danger to the public;</li>
  <li>Changes in the ownership of the business including partnership arrangements. Company changes in shareholding need not be notified unless they cause a change in the control of the Company;</li>
  <li>Events which affect:
    <ul class="list--bullet">
      <li>The good repute of the licence holder and transport manager, in particular, relevant convictions as defined in schedule 3 to the 1995 Act (this includes the issue of a fixed penalty notice or conditional offer under Part 3 of the Road Traffic Offenders Act 1988);</li>
      <li>The professional competence of the licence holder and/or transport manager;</li>
      <li>The requirement for the licence holder to be of appropriate financial standing (including details of any bankruptcy, liquidation, sequestration of estate or entry into administration of the holder of the appointment of a receiver, manager or trustee);</li>
      <li>The requirement to have an effective and stable establishment in Great Britain namely; any change to the specified address of establishment, and the requirement to have access at all times to at least one goods vehicle registered or in circulation in Great Britain.</li>
    </ul>
  </li>
</ul>
<p>b) In respect of each operating centre specified, that the number of authorised motor vehicles and the number of authorised trailers kept there will not exceed the maximum numbers recorded against the operating centre on this licence.</p>
<p>The following undertakings will be recorded on the licence:</p>
<ul class="list--bullet">
  <li>The laws relating to the driving and operation of vehicles and trailers used under the licence are observed;</li>
  <li>The rules on drivers' hours and tachographs are observed and proper records are kept for at least 12 months, and that these are made available on request;</li>
  <li>Vehicles and trailers are not overloaded or operated with an insecure load;</li>
  <li>Vehicles operate within speed limits;</li>
  <li>Vehicles and trailers, including hired vehicles and trailers, are kept in a fit and serviceable condition;</li>
  <li>Drivers report promptly any defects or symptoms of defects that could prevent the safe operation of vehicles and/or trailers, and that any defects are recorded in writing;</li>
  <li>Records are kept (for at least 15 months) of all driver defect reports, all safety inspections, routine maintenance and repairs to vehicles and trailers, and these are made available on request.</li>
  <li>An unauthorised operating centre is not used in any traffic area.</li>
</ul>
<p>Any failure to comply with the statements made to obtain a licence, conditions or undert akings recorded on the licence may result in the licence being revoked, suspended or curtailed; and that failure to comply with the conditions is a criminal offence.</p>
