<p class="govuk-body">I understand that by signing this declaration:</p>
<ul class="govuk-list govuk-list--bullet">
    <li>I am confirming that the details on my licence are correct.</li>
    <li>I have submitted changes to update any licence details that are incorrect</li>
    <li>I have read and understood the conditions recorded on the licence</li>
    <li>I have read, understood and accept the undertakings recorded on my licence</li>
    <li>
        I must be able to prove that I have a formal arrangement for access at all times to at least one vehicle
        registered or in circulation in GB. This could be by specifying a vehicle for use under an operator's licence
        or by demonstrating on request that I (the licence holder) have a vehicle available, so that vehicles may be
        either wholly owned or held under a hire-purchase, hire / leasing or other type of formal arrangement;
    </li>
    <li>
        I have an establishment in Great Britain (GB) with premises in which I keep core business documents. These
        include (as a minimum) accounting and personnel management documents and data on driving time and rest. I
        understand that the use of a PO Box or third party address is not permitted.
    </li>
</ul>
<p class="govuk-body">The licence is issued subject to the following conditions:</p>
<p class="govuk-body"><strong>1. Change of circumstances</strong></p>
<p class="govuk-body">In the event of changes to the following;</p>
<ul class="govuk-list govuk-list--bullet">
    <li>a) business address (i.e. the effective address to which correspondence is to be sent);</li>
    <li>b) the requirement to have an effective and stable establishment in Great Britain, including the address of establishment or the requirement to have access to a vehicle;</li>
    <li>c) address(es) of operating centre(s);</li>
    <li>d) the arrangements for the inspection/maintenance of vehicles;</li>
    <li>e) ownership of the business including partnership arrangements and in the persons holding shares in a company, which cause a change in control of the company.</li>
</ul>
<p class="govuk-body"><strong>2. Transport manager</strong></p>
<p class="govuk-body">In the event that any person named on the licence as a transport manager ceases to be employed as a transport manager for this licence</p>
<p class="govuk-body"><strong>3. Bankruptcy or liquidation</strong></p>
<p class="govuk-body">In the event of the bankruptcy or liquidation of the holder, or the sequestration of his estate or the entry into administration of the holder or the appointment of a receiver, manager or trustee of his road passenger transport business</p>
<p class="govuk-body"><strong>4. Relevant convictions</strong></p>
<p class="govuk-body">The holder of the licence shall notify the traffic commissioner in writing of</p>
<ul class="govuk-list govuk-list--bullet">
    <li>a) any conviction of the holder of the licence;</li>
    <li>b) where the licence is held by persons in partnership of any conviction of each such person; and</li>
    <li>c) any conviction of any officer, employee or agent of the holder for an offence committed in the course of the holder's road passenger transport business.</li>
</ul>
<p class="govuk-body">For the purposes of section 91 (1) and (2) the issue of a fixed penalty notice or conditional offer under Part 3 of the Road Traffic Offenders Act 1988 is to be treated as a relevant conviction.</p>
<p class="govuk-body"><strong>5. Occurrences which affect:</strong></p>
<ul class="govuk-list govuk-list--bullet">
    <li>The requirement to be of good repute;</li>
    <li>The requirement to be of appropriate financial standing; or</li>
    <li>The requirement as to professional competence;</li>
    <li>
        The requirement to have an effective and stable establishment in Great Britain namely;
        <ul class="govuk-list govuk-list--bullet">
            <li>a) any changes to the specified address of establishment, and</li>
            <li>b) the requirement to have access at all times to at least one public service vehicle registered or in circulation in Great Britain.</li>
        </ul>
    </li>
</ul>
<p class="govuk-body"><strong>6. Information about vehicles</strong></p>
<p class="govuk-body">The holder of the licence shall report to the Secretary of State as soon as practicable;</p>
<ul class="govuk-list govuk-list--bullet">
    <li>a) any failure or damage to a vehicle owned by the holder which is calculated to affect the safety of its occupants or persons using the road; and</li>
    <li>b) any alteration made in the structure or fixed equipment of any vehicle owned by him.</li>
</ul>
<p class="govuk-body"><strong>7. Requirement to supply additional information</strong></p>
<p class="govuk-body">The holder of the licence shall supply the traffic commissioner with any other information that may reasonably be required about the vehicles owned by the holder or about any material change in his circumstances.</p>
<p class="govuk-body">The following undertakings will be recorded on the licence:</p>
<ul class="govuk-list govuk-list--bullet">
    <li>The laws relating to the driving and operation of vehicles used under this licence are observed;</li>
    <li>The rules on drivers' hours and tachographs are observed and proper records are kept for at least 12 months, and that these are made available on request;</li>
    <li>Vehicles do not carry more than the permitted number of passengers;</li>
    <li>Vehicles will operate within speed limits;</li>
    <li>Vehicles, including hired vehicles, are kept in a fit and serviceable condition;</li>
    <li>Drivers report promptly any defects or symptoms of defects that could prevent the safe operation of vehicles, and that any defects are recorded in writing;</li>
    <li>Records are kept (for at least 15 months) of all driver defect reports, all safety inspections, routine maintenance and repairs to vehicles, and these are made available on request.</li>
</ul>
<p class="govuk-body">Any failure to comply with the statements made to obtain a licence, conditions or undertakings recorded on the licence may result in the licence being revoked, suspended or a condition reducing the number of vehicles authorised; and that failure to comply with the conditions is a criminal offence.</p>
