<p class="govuk-body">
  I declare that the statements of fact or expectation provided in support of this application are correct.
</p>
<ul class="govuk-list govuk-list--bullet">
  <li>I understand that it is the responsibility of the applicant to ensure that they have the required experience and training prior to making an application for an operator’s licence. I confirm that by signing this application that I understand the responsibilities and requirements of holding a goods vehicle operator’s licence and will ensure that I will keep updated on those requirements;</li>
  <li>
    I understand that I must notify the traffic commissioner of any relevant conviction of the applicant incurred since making the application and that a failure to do so is an offence;
  </li>
  <li>I understand that any changes which occur during the consideration of an application, information which materially changes from that originally declared when the application was first submitted including any change in the main occupation of the applicant, must be notified to the traffic commissioner;</li>
  <li>I understand that if a licence is issued it will authorise a maximum number of vehicles that may be used under it at any one time with the required disc correctly displayed, and that it is an offence to use a vehicle without a disc being correctly displayed;</li>
  <li>
    An unauthorised operating centre is not used in any traffic area.
  </li>
</ul>
<p class="govuk-body">I understand that by submitting this application I am accepting that the following undertakings will be recorded on the licence;</p>
<ul class="govuk-list govuk-list--bullet">
  <li>
    The laws relating to the driving and operation of vehicles used under this licence are observed;
  </li>
  <li>
    The rules on drivers’ hours and tachographs are observed and proper records are kept for at least 12 months, and that these are made available on request;
  </li>
  <li>
    Vehicles do not carry more than the permitted number of passengers;
  </li>
  <li>
    Vehicles will operate within speed limits;
  </li>
  <li>
    Vehicles, including hired vehicles, are kept in a fit and serviceable condition;
  </li>
  <li>
    Drivers report promptly any defects or symptoms of defects that could prevent the safe operation of vehicles, and that any defects are recorded in writing;
  </li>
  <li>
    Records are kept (for at least 15 months) of all driver defect reports, all safety inspections, routine maintenance and repairs to vehicles, and these are made available on request.
  </li>
</ul>
<p class="govuk-body">
  I understand that if a licence is issued it will be subject to the following conditions:
</p>
<ol class="govuk-list govuk-list--number">
  <li>
    <strong>Change of circumstances</strong>
    <p class="govuk-body">In the event of changes to the following;</p>
    <ol class="govuk-list">
      <li>
        a) business address (i.e. the effective address to which correspondence is to be sent);
      </li>
      <li>
        b) address(es) of operating centre(s);
      </li>
      <li>
        c) the arrangements for the inspection/maintenance of vehicles;
      </li>
      <li>
        d) ownership of the business including partnership arrangements and in the persons holding shares in a company, which cause a change in control of the company.
      </li>
    </ol>
  </li>
  <li>
    <strong>Bankruptcy of liquidation</strong>
    <p class="govuk-body">
      In the event of the bankruptcy or liquidation of the holder, or the sequestration of his estate or the entry into administration of the holder or the appointment of a receiver, manager or trustee of his road passenger transport business
    </p>
  </li>
  <li>
    <strong>Relevant convictions</strong>
    <p class="govuk-body">The holder of the licence shall notify the traffic commissioner in writing of</p>
    <ol class="govuk-list">
      <li>a) any conviction of the holder of the licence;</li>
      <li>b) where the licence is held by persons in partnership of any conviction of each such person; and</li>
      <li>c) any conviction of any officer, employee or agent of the holder for an offence committed in the course of the holder’s road passenger transport business.</li>
    </ol>
    <p class="govuk-body">
      For the purposes of section 91 (1) and (2) the issue of a fixed penalty notice or conditional offer under Part 3 of the Road Traffic Offenders Act 1988 is to be treated as a relevant conviction.
    </p>
  </li>
  <li>
    <strong>Occurrences which affect:</strong>
    <p class="govuk-body">
      The requirement to be of good repute;<br>
      The requirement to be of appropriate financial standing.
    </p>
  </li>
  <li>
    <strong>Information about vehicles</strong>
    <p class="govuk-body">The holder of the licence shall report to the Secretary of State as soon as practicable;</p>
    <ol class="govuk-list">
      <li>a) any failure or damage to a vehicle owned by the holder which is calculated to affect the safety of its occupants or persons using the road; and</li>
      <li>b) any alteration made in the structure or fixed equipment of any vehicle owned by him.</li>
    </ol>
  </li>
  <li>
    <strong>Requirement to supply additional information</strong>
    <p class="govuk-body">
      The holder of the licence shall supply the traffic commissioner with any other information that may reasonably be required about the vehicles owned by the holder or about any material change in his circumstances.
    </p>
  </li>
</ol>
<p class="govuk-body">
  Any failure to comply with the statements made to obtain a licence, conditions or undertakings recorded on the licence may result in the licence being revoked, suspended or a condition reducing the number of vehicles authorised; and that failure to comply with the conditions is a criminal offence.
</p>
%s
