<dl>
    <dt>Countrysjtjtjheryergrgagagargaegsrhsjtsrjtrjrtjrtjtrwtjwjtwrjrwtj</dt>
    <dd>Country</dd>
    <dt>Reputation</dt>
    <dd>Reputation</dd>
    <dt>Score</dt>
    <dd>Score</dd>
    <dt>Last Check</dt>
    <dd>Last Check</dd>
    <dt>Last Update</dt>
    <dd>Last Update</dd>
    <dt>Details</dt>
    <dd>Detailssdfsdfdsgdshdrfhfjrtjrtjtrjrtjtrjtrjtrjtrjrtjtrjrwtjrwjrwjwrjrj</dd>
</dl>
