<p>I understand that by signing this declaration:</p>
<ul class="list--bullet">
    <li>I am confirming that the details on my licence are correct</li>
    <li>I have submitted changes to update any licence details that are incorrect</li>
    <li>I confirm that the operation of PSVs is not the licence holder's main occupation</li>
    <li>I have read and understood the conditions recorded on the licence</li>
    <li>I have read, understood and accept the undertakings recorded on my licence</li>
</ul>
<p>The licence is issued subject to the following conditions:</p>
<p><strong>1. Change of circumstances</strong></p>
<p>In the event of changes to the following;</p>
<ul class="list--bullet">
    <li>a) business address (i.e. the effective address to which correspondence is to be sent);</li>
    <li>b) address(es) of operating centre(s);</li>
    <li>c) the arrangements for the inspection/maintenance of vehicles;</li>
    <li>d) ownership of the business, including partnership arrangements and in the persons holding shares in a company, which cause a change in control of the company.</li>
</ul>
<p><strong>2. Bankruptcy or liquidation</strong></p>
<p>In the event of the bankruptcy or liquidation of the holder, or the sequestration of his estate or the entry into administration of the holder or the appointment of a receiver, manager or trustee of his road passenger transport business</p>
<p><strong>3. Relevant convictions</strong></p>
<p>The holder of the licence shall notify the traffic commissioner in writing of</p>
<ul class="list--bullet">
    <li>a) any conviction of the holder of the licence;</li>
    <li>b) where the licence is held by persons in partnership of any conviction of each such person; and</li>
    <li>c) any conviction of any officer, employee or agent of the holder for an offence committed in the course of the holder's road passenger transport business.</li>
</ul>
<p>For the purposes of section 91 (1) and (2) the issue of a fixed penalty notice or conditional offer under Part 3 of the Road Traffic Offenders Act 1988 is to be treated as a relevant conviction.</p>
<p><strong>4. Occurrences which affect:</strong></p>
<ul class="list--bullet">
    <li>The requirement to be of good repute;</li>
    <li>The requirement to be of appropriate financial standing.</li>
</ul>
<p><strong>5. Information about vehicles</strong></p>
<p>The holder of the licence shall report to the Secretary of State as soon as practicable;</p>
<ul class="list--bullet">
    <li>a) any failure or damage to a vehicle owned by the holder which is calculated to affect the safety of its occupants or persons using the road; and</li>
    <li>b) any alteration made in the structure or fixed equipment of any vehicle owned by him.</li>
</ul>
<p><strong>6. Requirement to supply additional information</strong></p>
<p>The holder of the licence shall supply the traffic commissioner with any other information that may reasonably be required about the vehicles owned by the holder or about any material change in his circumstances.</p>
<p>The following undertakings will be recorded on the licence:</p>
<ul class="list--bullet">
    <li>The laws relating to the driving and operation of vehicles used under this licence are observed;</li>
    <li>The rules on drivers' hours and tachographs are observed and proper records are kept for at least 12 months, and that these are made available on request;</li>
    <li>Vehicles do not carry more than the permitted number of passengers;</li>
    <li>Vehicles will operate within speed limits;</li>
    <li>Vehicles, including hired vehicles, are kept in a fit and serviceable condition;</li>
    <li>Drivers report promptly any defects or symptoms of defects that could prevent the safe operation of vehicles, and that any defects are recorded in writing;</li>
    <li>Records are kept (for at least 15 months) of all driver defect reports, all safety inspections, routine maintenance and repairs to vehicles, and these are made available on request.</li>
</ul>
<p>Any failure to comply with the statements made to obtain a licence, conditions or undertakings recorded on the licence may result in the licence being revoked, suspended or a condition reducing the number of vehicles authorised; and that failure to comply with the conditions is a criminal offence.</p>
