SELECT 'DROP PROCEDURE IF EXISTS sp_drop_constraints;\nDELIMITER $$\nCREATE PROCEDURE sp_drop_constraints()\nBEGIN' AS '';

SELECT CONCAT(
    'IF EXISTS (SELECT 1 FROM information_schema.REFERENTIAL_CONSTRAINTS ',
    'WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = \'', rc.CONSTRAINT_NAME, '\') THEN ',
    'ALTER TABLE ', rc.TABLE_NAME, ' DROP FOREIGN KEY ', rc.CONSTRAINT_NAME, '; END IF;'
) AS ''
FROM information_schema.REFERENTIAL_CONSTRAINTS rc
WHERE rc.CONSTRAINT_SCHEMA = DATABASE()
ORDER BY rc.TABLE_NAME;

SELECT 'END\n$$' AS '';