SELECT 'DROP PROCEDURE IF EXISTS sp_NI_Extract_update_table_counts;' AS '';
SELECT 'DELIMITER \$\$' AS '';
SELECT 'CREATE PROCEDURE sp_NI_Extract_update_table_counts()' AS '';
SELECT 'BEGIN' AS '';
SELECT CONCAT('UPDATE NI_Extract SET POST_EXTRACT_COUNT = (SELECT COUNT(*) FROM ',TABLE_NAME,'),LAST_MODIFIED_ON = now() WHERE TABLE_NAME =\'',TABLE_NAME,'\';') AS ''
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA=database()
AND TABLE_NAME NOT LIKE '%_hist'
AND TABLE_NAME NOT IN ('NI_Extract')
AND TABLE_TYPE='BASE TABLE'
ORDER BY TABLE_NAME;
SELECT 'END' AS '';
SELECT '\$\$' AS '';
