SELECT 'DROP PROCEDURE IF EXISTS sp_drop_triggers;' AS '';
SELECT 'DELIMITER $$' AS '';
SELECT 'CREATE PROCEDURE sp_drop_triggers()' AS '';
SELECT 'BEGIN' AS '';

SELECT CONCAT('DROP TRIGGER IF EXISTS ', t.TRIGGER_NAME, ';') AS ''
FROM information_schema.TRIGGERS t
WHERE t.TRIGGER_SCHEMA = DATABASE()
ORDER BY t.TRIGGER_NAME;

SELECT 'END$$' AS '';
SELECT 'DELIMITER ;' AS '';
