SELECT 'DROP PROCEDURE IF EXISTS sp_NI_Extract_save_table_counts;\nDELIMITER $$\nCREATE PROCEDURE sp_NI_Extract_save_table_counts()\nBEGIN\nDELETE FROM NI_Extract;' AS '';

SELECT CONCAT(
    'INSERT INTO NI_Extract (TABLE_NAME, ORIGINAL_COUNT) ',
    'SELECT \'', t.TABLE_NAME, '\', COUNT(*) FROM ', t.TABLE_NAME, ';'
) AS ''
FROM information_schema.TABLES t
WHERE t.TABLE_SCHEMA = DATABASE()
  AND t.TABLE_TYPE = 'BASE TABLE'
  AND t.TABLE_NAME NOT LIKE '%\_hist'
  AND t.TABLE_NAME != 'NI_Extract'
ORDER BY t.TABLE_NAME;

SELECT 'END\n$$' AS '';