SELECT 'DROP PROCEDURE IF EXISTS sp_drop_hist_tables;\nDELIMITER $$\nCREATE PROCEDURE sp_drop_hist_tables()\nBEGIN' AS '';

SELECT CONCAT('DROP TABLE IF EXISTS ', t.TABLE_NAME, ';') AS ''
FROM information_schema.TABLES t
WHERE t.TABLE_SCHEMA = DATABASE()
  AND t.TABLE_NAME LIKE '%\_hist'
ORDER BY t.TABLE_NAME;

SELECT 'END\n$$' AS '';