SELECT 'DROP PROCEDURE IF EXISTS sp_add_original_constraints;' AS '';
SELECT 'DELIMITER \$\$' AS '';
SELECT 'CREATE PROCEDURE sp_add_original_constraints()' AS '';
SELECT 'BEGIN' AS '';
SELECT 'SET FOREIGN_KEY_CHECKS=0;' AS '';
SELECT CONCAT('ALTER TABLE ', kcu.TABLE_NAME,' ADD CONSTRAINT ',kcu.CONSTRAINT_NAME,' FOREIGN KEY (',kcu.COLUMN_NAME,') REFERENCES ',kcu.REFERENCED_TABLE_NAME,' (',kcu.REFERENCED_COLUMN_NAME,') ON DELETE ',rc.DELETE_RULE,' ON UPDATE ',rc.UPDATE_RULE,';') AS ''
 from INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
JOIN information_schema.REFERENTIAL_CONSTRAINTS rc
    ON kcu.TABLE_CATALOG = rc.CONSTRAINT_CATALOG  
    AND kcu.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA 
    AND kcu.CONSTRAINT_NAME =rc.CONSTRAINT_NAME
    AND kcu.constraint_schema=database()
JOIN information_schema.columns c
ON c.TABLE_SCHEMA = rc.CONSTRAINT_SCHEMA 
AND c.TABLE_NAME = kcu.TABLE_NAME
AND c.COLUMN_NAME = kcu.COLUMN_NAME
ORDER BY kcu.TABLE_NAME ;
SELECT 'SET FOREIGN_KEY_CHECKS=1;' AS '';
SELECT 'END' AS '';
SELECT '\$\$' AS '';

