SELECT CONCAT('DROP PROCEDURE IF EXISTS sp_drop_hist_tables', CHAR(10), '$$', CHAR(10), 'CREATE PROCEDURE sp_drop_hist_tables()', CHAR(10), 'BEGIN') AS '';

SELECT CONCAT('DROP TABLE IF EXISTS ', t.TABLE_NAME, ';') AS ''
FROM information_schema.TABLES t
WHERE t.TABLE_SCHEMA = DATABASE()
  AND t.TABLE_NAME LIKE '%\_hist'
ORDER BY t.TABLE_NAME;

SELECT CONCAT('END', CHAR(10), '$$') AS '';
