SELECT 'DROP PROCEDURE IF EXISTS sp_add_original_constraints;\nDELIMITER $$\nCREATE PROCEDURE sp_add_original_constraints()\nBEGIN\nSET FOREIGN_KEY_CHECKS=0;' AS '';

SELECT CONCAT(
    'ALTER TABLE ', kcu.TABLE_NAME, 
    ' ADD CONSTRAINT ', kcu.CONSTRAINT_NAME, 
    ' FOREIGN KEY (', 
    GROUP_CONCAT(kcu.COLUMN_NAME ORDER BY kcu.ORDINAL_POSITION SEPARATOR ', '), 
    ') REFERENCES ', kcu.REFERENCED_TABLE_NAME, 
    ' (', 
    GROUP_CONCAT(kcu.REFERENCED_COLUMN_NAME ORDER BY kcu.ORDINAL_POSITION SEPARATOR ', '), 
    ');'
) AS ''
FROM information_schema.KEY_COLUMN_USAGE kcu
JOIN information_schema.REFERENTIAL_CONSTRAINTS rc
    ON kcu.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA 
    AND kcu.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
WHERE kcu.CONSTRAINT_SCHEMA = DATABASE()
  AND kcu.REFERENCED_TABLE_NAME IS NOT NULL
GROUP BY kcu.TABLE_NAME, kcu.CONSTRAINT_NAME, kcu.REFERENCED_TABLE_NAME
ORDER BY kcu.TABLE_NAME;

SELECT 'SET FOREIGN_KEY_CHECKS=1;\nEND\n$$' AS '';