SELECT 'DROP PROCEDURE IF EXISTS sp_drop_constraints;' AS '';
SELECT 'DELIMITER \$\$' AS '';
SELECT 'CREATE PROCEDURE sp_drop_constraints()' AS '';
SELECT 'BEGIN' AS '';
SELECT CONCAT('IF EXISTS ( SELECT 1 FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=database() AND CONSTRAINT_NAME = \'',kcu.CONSTRAINT_NAME,'\') THEN',' ALTER TABLE ', kcu.TABLE_NAME,' DROP FOREIGN KEY ',kcu.CONSTRAINT_NAME,';END IF;') AS ''
 from INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
JOIN information_schema.REFERENTIAL_CONSTRAINTS rc
    ON kcu.TABLE_CATALOG = rc.CONSTRAINT_CATALOG  
AND kcu.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA 
AND kcu.CONSTRAINT_NAME =rc.CONSTRAINT_NAME
AND kcu.constraint_schema=database()
ORDER BY kcu.TABLE_NAME ;
SELECT 'END' AS '';
SELECT '\$\$' AS '';

