<div class="article">
    <?php
        echo $this->translate('markup-ebsr-success');

        echo $this->render('partials/read-only/main',
            [
                'multiItems' => [
                    0 => [
                        ['label' => 'ebsr-summary-file', 'class' => 'full-width', 'value' => $ebsrSubmission['document']['description'], 'url' => $documentUrl],
                    ],
                    1 => [
                        ['label' => 'ebsr-summary-uploaded-date', 'date' => $ebsrSubmission['submittedDate']]
                    ],
                    2 => [
                        ['label' => 'ebsr-summary-bus-status', 'value' => $this->status($ebsrSubmission['busReg']['status']), 'noEscape' => true],
                        ['label' => 'ebsr-summary-reg-number', 'value' => $ebsrSubmission['busReg']['regNo']],
                        ['label' => 'ebsr-summary-var-number', 'value' => $ebsrSubmission['busReg']['variationNo']],
                        ['label' => 'ebsr-summary-service-number', 'value' => $ebsrSubmission['busReg']['serviceNo']]
                    ]
                ]
            ]
        );
    ?>
</div>

<a href="<?php echo $this->url('bus-registration/details', ['busRegId' => $ebsrSubmission['busReg']['id']]);?>" class="action--primary"><?php echo $this->translate('ebsr-view-registration-details'); ?></a>