<?php 
  $data = $form->get('data');
  $actions = $form->get('form-actions');
?>
<?php echo $this->formErrors($form); ?>
<?php echo $this->form()->openTag($form); ?>
<label><?php echo $this->translate('selfserve-app-subSection-previous-history-criminal-conviction-hasConv'); ?></label>
<?php echo $this->formRow($data->get('hasOffence')); ?>
<?php echo $this->formRow($data->get('id')); ?>
<?php echo $this->formRow($data->get('version')); ?>
<div>
<?php echo $criminalConvitions; ?>
</div>
<h3>New Convictions</h3>
<?php echo $this->formRow($data->get('convictionsConfirmation')); ?>
<?php echo $this->formCollection($actions); ?>
<?php echo $this->form()->closeTag($form); ?>