<h3><?php echo $this->resourceHelper('case-details'); ?></h3>
<div class="col-md-12 case-dashboard-details">
    <ul class="details-list details-list-columns">
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('open-date'); ?>:</span>
            <?php echo $this->caseDetails['openTime'] ? $this->simpleDateFormat($this->caseDetails['openTime']) : ''; ?>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('licence-start-date'); ?>:</span>
            <?php echo $this->caseDetails['licence']['startDate'] ? $this->simpleDateFormat($this->caseDetails['licence']['startDate']) : ''; ?>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('status'); ?>:</span>
            <?php echo $this->escapeHtml(ucfirst($this->caseDetails['caseStatus'])); ?>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('licence-category'); ?>:</span>
            <?php echo $this->escapeHtml($this->caseDetails['licence']['goodsOrPsv']); ?>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('entity-type'); ?>:</span>
            <?php echo $this->escapeHtml($this->caseDetails['operator']['entityType']); ?>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('licence-status'); ?>:</span>
            <?php echo $this->escapeHtml($this->caseDetails['licence']['licenceStatus']); ?>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('traffic-area'); ?>:</span>
            <?php echo $this->escapeHtml($this->caseDetails['licence']['licenceType']); ?>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('licence-type'); ?>:</span>
            <?php echo $this->escapeHtml($this->caseDetails['licence']['licenceType']); ?>
        </li>
    </ul>
</div>