<?php 
$this->headScript()->prependFile($this->basePath() . '/js/collapsible.init.js');
$this->headScript()->prependFile($this->basePath() . '/js/collapsible.js');
$this->headScript()->prependFile($this->basePath() . '/js/caseTabs.js');
$this->placeholder('body-class')->set("full-page");
?>
<div class="row">
    <?php
    echo $this->partial('olcs/vcase/partials/details', array(
        'params' => $params,
        'caseId' => $caseId,
        'licenceId' => $licenceId,
        'caseTabs' => array('dashboardActive' => 'active'),
    ));
    ?>
    <?php echo $this->partial('olcs/vcase/dashboard/caseDetails', array('caseDetails' => $params)); ?>
    <div class="accordionAll">
        <div class="dashboard-section">
            <a href="#" class="collapsible acc-collapsed expanded" id="1111"><?php echo $this->resourceHelper('submissions'); ?></a>
            <div id="acc-submissions"class="accordion-row">
                <?php echo $this->dataListView; ?>
            </div>
        </div>
        <div class="dashboard-section">
            <a href="#" class="collapsible acc-collapsed" id="222"><?php echo $this->resourceHelper('applications'); ?></a>
            <div id="acc-applications" class="accordion-row">
                Applications data
            </div>
        </div>
        <div class="dashboard-section">
            <a href="#" class="collapsible acc-collapsed" id="333"><?php echo $this->resourceHelper('nfas'); ?></a>
            <div id="acc-nfas"class="accordion-row">
                NFAS data
            </div>
        </div>
    </div>
    <div class="dashboard-section"></div>
    <?php echo $this->partial('olcs/vcase/partials/action-form', array('form' => $actionForm)); ?>
</div>
    