<thead>
    <tr>
        <th class="text-muted sortable" id="submissionNumber"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('sub-status'); ?></span></th>
        <th class="text-muted sortable" id="Created_On"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('date-created'); ?></th>
        <th class="text-muted sortable" id="closedAt"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('date-closed'); ?></th>
        <th class="text-muted sortable" id="with"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('currently-with'); ?></th>
        <th class="text-muted sortable" id="urgent"><span class="noWrap"><img  src="/img/p.png" class="sprt arrUp" /><?php echo $this->resourceHelper('urgent'); ?></th>
        <th class="text-muted"><span class="noWrap"></th>
    </tr>
</thead>