<?php echo $this->flashMessengerAll(); ?>
<?php echo $this->form()->openTag($form); ?>
    <fieldset>
        <legend><?php echo $this->escapeHtml($this->translate('auth.login.title')); ?></legend>
        <?php
        echo $this->formErrors($form);
        if (isset($failed) && $failed) {
            ?>
            <div class="validation-summary">
                <h2><?php echo $this->escapeHtml($this->translate('auth.login.failed.title')); ?></h2>
                <p><?php echo $this->escapeHtml($this->translate('auth.login.failed.reason.' . $failureReason)); ?></p>
            </div>
            <?php
        }

        $form->get('password')->setOption(
            'hint',
            sprintf('<a tabindex="4" href="%s">%s</a>',
                $this->url('auth/forgot-password'),
                $this->translate('auth.forgot-password.label')
            )
        );
        $form->get('password')->setOption('hint-position', 'above');
        ?>
        <?php echo $this->formRow($form->get('username')); ?>
        <?php echo $this->formRow($form->get('password')); ?>
        <?php echo $this->formElement($form->get('submit')); ?>
    </fieldset>

<?php echo $this->formElement($form->get('security')); ?>
<?php echo $this->form()->closeTag(); ?>
