<div class="row">  
    <div class="col-md-12 tListHeader tBorder2t nopad">
        <div  style="font-size:150%;padding-bottom:5px">You searched for</div>
        <div id="searchTerm">
            <ul class="list-inline">
                <li><span class="text-muted">License number</span><span>OB105237</span></li>
                <li><span class="text-muted">Trading Name</span><span>Big Trucks Ltd</span></li>
                <li><span class="text-muted">Postcode</span><span>LS1 4DY</span></li>
            </ul>
        </div>
    </div>
</div>
<div  class="row">
        <div class="col-md-2 tBorder1r filter-bar tBgCol dev  tBorder2t">Filters to go here...</div>
        <div class="col-md-10 nopad">
            <div class="nopad tPagBar  tBorder2t">
                <div class="tBgCol"><span>Showing 10 of 257 results</span>
                    <ul class="list-inline" style="display: inline;">
                    <li><a href="#">show 25</a></li>
                    <li><a href="#">show 25</a></li>
                    <li><a href="#">show 25</a></li>
                </ul>
                </div>
            </div>
    <div class="tbl table-responsive">
                <table class="table table-striped">
                    <thead>
                      <tr>
                          <th class="text-muted">
                            Lic no.<br>Lic status
                        </th>
                        <th>
                    <div class="text-muted"><span class="noWrap">App ID/</span><br>Status</div>
                        </th>
                        <th>
                        <div class="text-muted"><span class="noWrap">Op Name</span><br><span class="noWrap">(Trading Name)</span></div>
                        </th>
                        <th>
                        <div class="text-muted">Company/<br><span class="noWrap">License Type</span></div>
                        </th>
                        <th>
                        <div class="text-muted"><span class="noWrap">Last act./</span><br>CN/date</div>
                        </th>
                        <th>
                            <div class="text-muted">Correspondence<br>Address</div>
                        </th>
                        <th>
                        <div class="text-muted"><span class="noWrap">Operating Centre</span><br>Address</div>
                        </th>
                        <th>
                            <div class="text-muted">Case</div>
                        </th>
                        <th>
                            <div class="text-muted">MLH</div>
                        </th>
                        <th>
                            <div class="text-muted">Add.<br>info</div>
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                          <td><a href="#">OB77777777</a><br>No pub. var</td>
                        <td><a href="#">2181011</a><br>Surren.</td>
                        <td>A company name (Big Trucks)</td>
                        <td><span class="noWrap">Sole trader<span><br>restricted</td>
                        <td>WL<br><span class="noWrap">26-07-09</span></td>
                        <td>99 White Heart Road, Smithson house</td>
                        <td>99 White Heart Road, Smithson house</td>
                        <td><a href="#">5</a></td>
                        <td><a href="#">Y</a></td>
                        <td><a href="#">i</a></td>
                      </tr>
                      <tr>
                          <td><a href="#">OB77777777</a><br>No pub. var</td>
                        <td><a href="#">2181011</a><br>Surren.</td>
                        <td>A company name (Big Trucks)</td>
                        <td><span class="noWrap">Sole trader<span><br>restricted</td>
                        <td>WL<br><span class="noWrap">26-07-09</span></td>
                        <td>99 White Heart Road, Smithson house</td>
                        <td>99 White Heart Road, Smithson house</td>
                        <td><a href="#">5</a></td>
                        <td><a href="#">Y</a></td>
                        <td><a href="#">i</a></td>
                      </tr>
                      <tr>
                          <td><a href="#">OB77777777</a><br>No pub. var</td>
                        <td><a href="#">2181011</a><br>Surren.</td>
                        <td>A company name (Big Trucks)</td>
                        <td><span class="noWrap">Sole trader<span><br>restricted</td>
                        <td>WL<br><span class="noWrap">26-07-09</span></td>
                        <td>99 White Heart Road, Smithson house</td>
                        <td>99 White Heart Road, Smithson house</td>
                        <td><a href="#">5</a></td>
                        <td><a href="#">Y</a></td>
                        <td><a href="#">i</a></td>
                      </tr>
                    </tbody>
                  </table>
            </div>
        </div>
        <div class="col-md-2 tBorder2t"></div>
        <div class="col-md-10 nopad">
            <div class="nopad tPagBar tBorder2t ">
                <div class="tBgCol"><span>Showing 10 of 257 results</span>
                    <ul class="list-inline" style="display: inline;">
                    <li><a href="#">show 25</a></li>
                    <li><a href="#">show 25</a></li>
                    <li><a href="#">show 25</a></li>
                </ul>
                </div>
            </div>
        <div class="clearfix"></div>
</div>