<?php
    $form->prepare();
    echo $this->form()->openTag($form);
?>
<fieldset>
    <?php $mainLegend =  $form->get('finance')->getOption('label'); ?>
    <?php if (!empty($mainLegend)): ?>
        <legend><?php echo $mainLegend ?></legend>
    <?php endif; ?>
    <label>Has any person named in this application (including partners, directors or transport managers) ever been:<br /><br /></label>
    <?php foreach ($form->get('finance')->getElements() as $element): ?>
        <?php if($element->getName() == 'finance[insolvencyDetails]'): ?>
            <fieldset class="<?php if (count($element->getMessages()) > 0): ?>validation-wrapper<?php else: ?>highlight-box<?php endif; ?>">
                <legend><?php echo $element->getLabel() ?></legend>
                <div class="field">
                    <p class="hint">Please provide additional information relating to any prior insolvency proceedings. You may also upload evidence such as legal documents.</p>
                    <?php echo $this->formElementErrors($element); ?>
                    <?php echo $this->formElement($element); ?>
                </div>
            </fieldset>
            <?php continue; ?>
        <?php endif; ?>
        <?php echo $this->formRow($element); ?>
    <?php endforeach; ?>
    <?php echo $this->formRow($form->get('submit')); ?>
    <?php echo $this->formRow($form->get('version')); ?>
    <?php echo $this->formRow($form->get('crsf')); ?>
</fieldset>
<?php echo $this->form()->closeTag(); ?>
