<h3 class="js-title">Adding an operating centre</h3>
<div class="js-body">
  <p>In order to add an additional operating centre on the licence you must create a variation application</p>
  <p class="govuk-button-group">
    <a href="<?php echo $this->url('create_variation', array('licence' => $licence)); ?>" class="govuk-button">Create variation</a>
    <a href="<?php echo $this->url(null, array('action' => 'index'), array(), true); ?>" class="govuk-button govuk-button--secondary">Cancel</a>
  </p>
</div>
