<?php
$details = $this->placeholder('details')->getValue();

$noRender = array('createdOn', 'lastModifiedOn', 'createdBy', 'lastModifiedBy', 'id', 'version');

$items = [];

foreach ($details as $key => $value) {
    if (!is_array($value) && !in_array($key, $noRender)) {
        $item = ['label' => $key];

        if (strstr(strtolower($key), 'date')) {
            $item[] = ['date' => $value];
        } else {
            $item[] = ['value' => $value];
        }

        $items[] = $item;
    }
}

echo $this->render('partials/read-only/main', ['items' => $items]);
