<?php
$details = $this->placeholder('details')->getValue();

$noRender = array('createdOn', 'lastModifiedOn', 'createdBy', 'lastModifiedBy');

?>

    <div class="read-only">
        <dl>
        <?php foreach ($details as $key => $value): ?>

            <?php if (!is_array($value) && !in_array($key, $noRender)): ?>

            <dt><?php echo $this->translate($key);?></dt>

            <dd><?php echo $value; ?></dd>

            <?php endif; ?>

            <?php endforeach; ?>
        </dl>
    </div>
