<?php
$details = $this->placeholder('details')->getValue();

$noRender = array('createdOn', 'lastModifiedOn', 'createdBy', 'lastModifiedBy', 'id', 'version');

?>

    <div class="read-only">
        <dl>
        <?php foreach ($details as $key => $value): ?>

            <?php if (!is_array($value) && !in_array($key, $noRender)): ?>

            <dt><?php echo $this->translate($key);?></dt>

            <?php if (strstr(strtolower($key), 'date')): ?>
            <dd><?php echo date('d/m/Y', strtotime($value)); ?></dd>
            <?php else: ?>
            <dd><?php echo $value; ?></dd>
            <?php endif; ?>

            <?php endif; ?>

            <?php endforeach; ?>
        </dl>
    </div>
