<?php
	$action = $this->placeholder('action')->getValue();
	$form = $this->placeholder('form')->getValue();

    if (count($form) > 0):
        if ($form->getOption('override_form_label')) {
?>
	<div class="content__header">
    	<h3><?php echo $this->translate($form->getOption('label')); ?></h3>
    </div>
<?php
        } else {
?>
	<div class="content__header">
    	<h3><?php echo is_string($action) ? ucfirst($action) : ''; ?> <?php echo lcfirst($this->translate($form->getOption('label'))); ?></h3>
    </div>
<?php
        }
?>
<?php echo $this->formErrors($form); ?>
<?php echo $this->form($form); ?>

<?php endif; ?>
