
<h1 class="padb20">Search</h1>
<form class="form-horizontal" role="form" action="">
  <div class="form-group">
    <label for="licenceNumber" class="col-lg-2 control-label">Licence number</label>
    <div class="col-lg-4 itext">
      <input type="text" class="form-control" id="licenceNumber" placeholder="">
    </div>
  </div>
  <div class="form-group">
    <label for="operatorName" class="col-lg-2 control-label">Operator/Trading name</label>
    <div class="col-lg-4 itext">
      <input type="text" class="form-control" id="operatorName" placeholder="">
    </div>
  </div>
    <div class="form-group">
        <label for="postcode" class="col-lg-2 control-label">Postcode</label>
        <div class="col-lg-4 itext">
            <input type="text" class="form-control" id="postcode" placeholder="">
        </div>
  </div>
    <div class="form-group">
    <label for="firstName" class="col-lg-2 control-label">Name</label>
    <div class="col-lg-4 itext inlnf">
      <input type="text" class="form-control" id="firstName" placeholder="First Name">
    </div>
    <div class="col-lg-4 itext">
      <input type="text" class="form-control" id="lastName" placeholder="Last Name">
    </div>
  </div>
    <div class="form-group">
        <label for="dobMonth" class="col-lg-2 control-label">Date of birth</label>
        <div class="col-lg-1 dob inlnf">
          <select class="form-control" id="dobDay">
              <option>Day</option>
                <option value="1">1</option>
                <option value="2">2</option>
            </select>
        </div>
        <div class="col-lg-1 dob inlnf">
          <select class="form-control" id="dobMonth">
                <option>Month</option>
                <option value="1">1</option>
                <option value="2">2</option>
            </select>
        </div>
        <div class="col-lg-1 dob inlnf">
            <span ><input type="text" class="form-control"  id="dobYear" placeholder="Year"></span>
        </div>
      </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <button type="submit" class="btn btn-success">Lookup</button>
    </div>
  </div>
</form>
<div><a href="advanced" class="linkBlue">Advanced search</a> <span class="glyphicon glyphicon-chevron-up"></span></div>