<h4><?php echo isset($this->data['sectionInfo']['description']) ? $this->data['sectionInfo']['description'] : ''; ?>
    <a href="<?php echo $this->url(
        'submission', [
            'case' => isset($this->data['data']['id']),
            'action' => 'edit',
            'submission' => $this->data['data']['id']
        ]
        );?>" class="action--secondary right-aligned">
        <?php echo
        $this->translate('Edit section');
        ?></a>
</h4>

