<?php
$case = $this->placeholder('case')->getValue();
?>

    <h4><?php

        echo isset($this->data['description']) ? $this->data['description'] : ''; ?>
        <a href="<?php echo $this->url(
            'submission', [
                'case' => $case['id'],
                'action' => 'edit'
            ]
        );?>" class="action--secondary right-aligned">
            <?php echo
            $this->translate('Edit section');
            ?></a>
    </h4>

    <div class="read-only">
        <?php echo isset($this->data['data']['outline']) ? $this->data['data']['outline'] : ''; ?>
    </div>
