<?php

$operatorName = (isset($this->data['data']['organisationName']) ?
    $this->data['data']['organisationName'] : '') .
    ((isset($this->data['data']['isMlh']) && $this->data['data']['isMlh'] == 'Y') ?
    '(MLH)' : '');

$isMlh = (isset($this->data['data']['isMlh']) ?
    $this->data['data']['isMlh'] : 'N');

$entity = (isset($this->data['data']['organisationType']) ?
    $this->data['data']['organisationType'] : '');

$ecmsNo = (isset($this->data['data']['ecmsNo']) ?
    $this->data['data']['ecmsNo'] : '');

$licenceItems = [
    ['label' => 'Licence number', 'value' => $this->data['data']['licNo']],
    ['label' => 'Licence start date', 'date' => $this->data['data']['licenceStartDate']],
    ['label' => 'Licence type', 'value' => $this->data['data']['licenceType']],
    ['label' => 'Licence status', 'value' => $this->data['data']['licenceStatus']],
    ['label' => 'Type of licence', 'value' => $this->data['data']['goodsOrPsv']]
];

if (isset($this->data['data']['caseType']) && $this->data['data']['caseType'] == 'case_t_app') {
    $licenceItems[] = ['label' => 'Service standard date', 'date' => $this->data['data']['serviceStandardDate']];
}

echo $this->render('partials/read-only/main',
    [
        'multiItems' => [
            0 => [
                ['label' => 'Operator name', 'value' => $operatorName],
                ['label' => 'Is MLH?', 'value' => $isMlh],
                ['label' => 'Entity', 'value' => $entity],
                ['label' => 'ECMS', 'value' => $ecmsNo],
                ['label' => 'Nature of business', 'value' =>
                    isset($this->data['data']['businessType']) ? $this->data['data']['businessType'] : '']
            ],
            1 => $licenceItems,
            2 => [
                ['label' => 'Total vehicle authorisation', 'numeric' => $this->data['data']['totAuthorisedVehicles']],
                ['label' => 'Vehicles in possession', 'numeric' => $this->data['data']['vehiclesInPossession']],
                ['label' => 'Trailer authorisation', 'numeric' => $this->data['data']['totAuthorisedTrailers']],
                ['label' => 'Trailers in possession', 'numeric' => $this->data['data']['trailersInPossession']]
            ]
        ]
    ]
);
