<div class="read-only">
    <ul class="definition-list">
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Operator name');?></dt>
            <dd><?php echo isset($this->data['data']['organisationName']) ?
                    $this->data['data']['organisationName'] : '';
                    echo (isset($this->data['data']['isMlh']) && $this->data['data']['isMlh'] == 'Y') ?
                        '(' . $this->translate('MLH') . ')' : '';
                ?></dd>
        </li>
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Is MLH?');?></dt>
            <dd><?php echo isset($this->data['data']['isMlh']) ?
                    $this->data['data']['isMlh'] : '';
                ?></dd>
        </li>
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Entity');?></dt>
            <dd><?php echo isset($this->data['data']['organisationType']) ?
                    $this->data['data']['organisationType'] : '';?></dd>
        </li>
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('ECMS');?></dt>
            <dd><?php echo isset($this->data['data']['ecmsNo']) ?
                    $this->data['data']['ecmsNo'] : '';?></dd>
        </li>
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Business type');?></dt>
            <dd><?php echo isset($this->data['data']['businessType']) ?
                    $this->data['data']['businessType'] : '';?></dd>
        </li>
    </ul>

    <ul class="definition-list">
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Licence number');?></dt>
            <dd><?php echo isset($this->data['data']['licNo']) ?
                    $this->data['data']['licNo'] : '';?></dd>
        </li>
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Licence start date');?></dt>
            <dd><?php echo isset($this->data['data']['licenceStartDate']) ?
                    $this->dateFormat(
                        \DateTime::createFromFormat(
                            \DateTime::ISO8601,
                            $this->data['data']['licenceStartDate']
                        ),
                        \IntlDateFormatter::SHORT) : '';?></dd>
        </li>
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Licence type');?></dt>
            <dd><?php echo isset($this->data['data']['licenceType']) ?
                    $this->data['data']['licenceType'] : '';?></dd>
        </li>
            <?php
                if (isset($this->data['data']['caseType']) && $this->data['data']['caseType'] == 'case_t_app') {
            ?>
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Service standard date');?></dt>
            <dd><?php echo isset($this->data['data']['serviceStandardDate']) ?
                    $this->dateFormat(
                        \DateTime::createFromFormat(
                            \DateTime::ISO8601,
                            $this->data['data']['serviceStandardDate']
                        ),
                        \IntlDateFormatter::SHORT) : '';?>
            </dd>
        </li>
            <?php
                }
            ?>
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Licence status');?></dt>
            <dd><?php echo isset($this->data['data']['licenceStatus']) ?
                    $this->data['data']['licenceStatus'] : '';?></dd>
        </li>
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Type of licence');?></dt>
            <dd><?php echo isset($this->data['data']['goodsOrPsv']) ?
                    $this->data['data']['goodsOrPsv'] : '';?></dd>
        </li>
    </ul>

    <ul class="definition-list">
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Total vehicle authorisation');?></dt>
            <dd><?php echo isset($this->data['data']['totAuthorisedVehicles']) ?
                    $this->data['data']['totAuthorisedVehicles'] : 0;?></dd>
        </li>
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Vehicles in possession');?></dt>
            <dd><?php echo isset($this->data['data']['vehiclesInPossession']) ?
                    $this->data['data']['vehiclesInPossession'] : 0;?></dd>
        </li>
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Trailer authorisation');?></dt>
            <dd><?php echo isset($this->data['data']['totAuthorisedTrailers']) ?
                    $this->data['data']['totAuthorisedTrailers'] : 0;?></dd>
        </li>
        <li class="definition-list__item ">
            <dt><?php echo $this->translate('Trailers in possession');?></dt>
            <dd><?php echo isset($this->data['data']['trailersInPossession']) ?
                    $this->data['data']['trailersInPossession'] : 0;?></dd>
        </li>
    </ul>
</div>
