<?php
$case = $this->placeholder('case')->getValue();
?>
<h4><?php echo isset($this->data['description']) ? $this->data['description'] : ''; ?>
    <a href="<?php echo $this->url(
        'submission', [
            'case' => $case['id'],
            'action' => 'edit',
        ]
    );?>" class="action--secondary right-aligned">
        <?php echo
        $this->translate('Edit section');
        ?></a>
</h4>
<div class="read-only">
    <dl>
        <dt><?php echo $this->translate('Operator name');?></dt>
        <dd><?php echo isset($this->data['data']['organisationName']) ?
                $this->data['data']['organisationName'] : '';
                echo ($this->data['data']['isMlh'] == 'Y') ?
                    '(' . $this->translate('MLH') . ')' : '';
            ?></dd>
        <dt><?php echo $this->translate('Entity');?></dt>
        <dd><?php echo isset($this->data['data']['organisationType']) ?
                $this->data['data']['organisationType'] : '';?></dd>
        <dt><?php echo $this->translate('ECMS');?></dt>
        <dd><?php echo isset($this->data['data']['ecmsNo']) ?
                $this->data['data']['ecmsNo'] : '';?></dd>
        <dt><?php echo $this->translate('Business type');?></dt>
        <dd><?php echo isset($this->data['data']['businessType']) ?
                $this->data['data']['businessType'] : '';?></dd>
    </dl>
</div>
<div class="read-only">
    <dl>
        <dt><?php echo $this->translate('Licence number');?></dt>
        <dd><?php echo isset($this->data['data']['licNo']) ?
                $this->data['data']['licNo'] : '';?></dd>
        <dt><?php echo $this->translate('Licence start date');?></dt>
        <dd><?php echo isset($this->data['data']['licenceStartDate']) ?
                $this->dateFormat(
                    \DateTime::createFromFormat(
                        \DateTime::ISO8601,
                        $this->data['data']['licenceStartDate']
                    ),
                    \IntlDateFormatter::SHORT) : '';?></dd>
        <dt><?php echo $this->translate('Licence type');?></dt>
        <dd><?php echo isset($this->data['data']['licenceType']) ?
                $this->data['data']['licenceType'] : '';?></dd>
        <dt><?php echo $this->translate('Service standard date');?></dt>
        <dd><?php echo isset($this->data['data']['serviceStandardDate']) ?
                $this->dateFormat(
                    \DateTime::createFromFormat(
                        \DateTime::ISO8601,
                        $this->data['data']['serviceStandardDate']
                    ),
                    \IntlDateFormatter::SHORT) : '';?></dd>
        <dt><?php echo $this->translate('Licence status');?></dt>
        <dd><?php echo isset($this->data['data']['licenceStatus']) ?
                $this->data['data']['licenceStatus'] : '';?></dd>
    </dl>
</div>
<div class="read-only">
    <dl>
        <dt><?php echo $this->translate('Total vehicle authorisation');?></dt>
        <dd><?php echo isset($this->data['data']['totAuthorisedVehicles']) ?
                $this->data['data']['totAuthorisedVehicles'] : 0;?></dd>

        <dt><?php echo $this->translate('Vehicles in possession');?></dt>
        <dd><?php echo isset($this->data['data']['licence']['vehiclesInPossession']) ?
                $this->data['data']['licence']['vehiclesInPossession'] : 0;?></dd>

        <dt><?php echo $this->translate('Trailer authorisation');?></dt>
        <dd><?php echo isset($this->data['data']['totAuthorisedTrailers']) ?
                $this->data['data']['totAuthorisedTrailers'] : 0;?></dd>

        <dt><?php echo $this->translate('Trailers in possession');?></dt>
        <dd><?php echo isset($this->data['data']['licence']['trailersInPossession']) ?
                $this->data['data']['licence']['trailersInPossession'] : 0;?></dd>
    </dl>
</div>
