<?php
$case = $this->placeholder('case')->getValue();

echo $this->render('partials/read-only/main',
    [
        'header' => (isset($this->data['description']) ? $this->data['description'] : ''),
        'actions' => [
            [
                'label' => 'Edit section',
                'url' => $this->url(
                    'submission', [
                        'case' => $case['id'],
                        'action' => 'edit'
                    ]
                )
            ],
        ],
        'freetext' => (isset($this->data['data']['outline']) ? $this->data['data']['outline'] : '')
    ]
);
