<?php 
$this->headScript()->prependFile($this->basePath() . '/js/application/olcs.licence.js');
?>
    <div class="row">
        <div class="pheading">
            <a href="#" class="acc-buttons collapsible acc-collapsed expanded"><?php echo $this->resourceHelper('header-correspondence-details'); ?></a>
        </div>
        <div class="accordion">
            <?php echo $this->formRow($form->get('correspondence[contact_type]')); ?>
            <div class="row form-group" >
                <label for="correspondence[fao]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-fao'); ?></label>
                <div class="col-lg-4 itext">
                    <?php echo $this->formRow($form->get('correspondence[fao]')); ?>
                </div>
            </div>
            
            <div class="row form-group required" >
                <label for="correspondence[postcode]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-postcode'); ?></label>
                <div class="col-lg-4 itext">
                    <?php echo $this->formRow($form->get('correspondence[postcode]')); ?>
                </div>                
                <div class="col-lg-2">
                    <?php echo $this->formButton($form->get('correspondence[findaddressbutton]'), $this->resourceHelper('correspondence-address-form-button-find-address')); ?>
                </div>
                <div class="col-lg-9 pull-right">
                    <!-- todo address drop down goes here -->
                </div> 
            </div>
            
            <div class="row form-group required" >
                <label for="correspondence[addressLine1]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-address1'); ?></label>
                <div class="col-lg-4 itext">
                    <?php echo $this->formRow($form->get('correspondence[addressLine1]')); ?>
                </div>
            </div>
            
            <div class="row form-group" >
                <label for="correspondence[addressLine2]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-address2'); ?></label>
                <div class="col-lg-4 itext">
                    <?php echo $this->formRow($form->get('correspondence[addressLine2]')); ?>
                </div>
            </div>
            
            <div class="row form-group" >
                <label for="correspondence[addressLine3]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-address3'); ?></label>
                <div class="col-lg-4 itext">
                    <?php echo $this->formRow($form->get('correspondence[addressLine3]')); ?>
                </div>
            </div>
            
            <div class="row form-group" >
                <label for="correspondence[addressLine4]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-address4'); ?></label>
                <div class="col-lg-4 itext">
                    <?php echo $this->formRow($form->get('correspondence[addressLine4]')); ?>
                </div>
            </div>
            
            <div class="row form-group required" >
                <label for="correspondence[townCity]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-town-city'); ?></label>
                <div class="col-lg-4 itext">
                    <?php echo $this->formRow($form->get('correspondence[townCity]')); ?>
                </div>
            </div>
            
            <div class="form-group required">
                <label for="correspondence[country]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-country'); ?></label>
                <div class="col-lg-4 itext">
                <?php echo $this->formRow($form->get('correspondence[country]')); ?>
                </div>
            </div>
            <?php
                // olcs-666 AC4 Only show the establishment address select box 
                //      if licence is of a particular type
                if (in_array(strtolower($licence['licenceType']), array('standard national', 'standard international')))
                {
            ?>
            <div class="form-group required">
                <label for="establishmentAddressYN" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-establishment-address'); ?></label>
                <div class="col-lg-4 itext">
                <?php echo $this->formRow($form->get('establishmentAddressYN')); ?>
                </div>
            </div>
            <?php
                }
            ?>
            <div class="form-group">
                <label for="correspondence[email]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-email'); ?></label>
                <div class="col-lg-4 itext">
                <?php echo $this->formRow($form->get('correspondence[email]')); ?>
                </div>
            </div>
        </div>
             
        <div id="establishmentAddressForm">
            <div class="pheading">
                <a href="#" class="acc-buttons collapsible acc-collapsed expanded"><?php echo $this->resourceHelper('header-establishment-address'); ?></a>
            </div>
            <div class="accordion">
                <?php echo $this->formRow($form->get('establishment[contact_type]')); ?>

                <div class="row form-group required" >
                    <label for="establishment[postcode]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-postcode'); ?></label>
                    <div class="col-lg-4 itext">
                        <?php echo $this->formRow($form->get('establishment[postcode]')); ?>
                    </div>
                    <div class="col-lg-2">
                        <?php echo $this->formButton($form->get('establishment[findaddressbutton]'), $this->resourceHelper('correspondence-address-form-button-find-address')); ?>
                    </div>
                    <div class="col-lg-9 pull-right">
                        <!-- todo address drop down goes here -->
                    </div> 
                </div>

                <div class="row form-group required" >
                    <label for="establishment[addressLine1]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-address1'); ?></label>
                    <div class="col-lg-4 itext">
                        <?php echo $this->formRow($form->get('establishment[addressLine1]')); ?>
                    </div>
                </div>

                <div class="row form-group" >
                    <label for="establishment[addressLine2]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-address2'); ?></label>
                    <div class="col-lg-4 itext">
                        <?php echo $this->formRow($form->get('establishment[addressLine2]')); ?>
                    </div>
                </div>

                <div class="row form-group" >
                    <label for="establishment[addressLine3]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-address3'); ?></label>
                    <div class="col-lg-4 itext">
                        <?php echo $this->formRow($form->get('establishment[addressLine3]')); ?>
                    </div>
                </div>

                <div class="row form-group" >
                    <label for="establishment[addressLine4]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-address4'); ?></label>
                    <div class="col-lg-4 itext">
                        <?php echo $this->formRow($form->get('establishment[addressLine4]')); ?>
                    </div>
                </div>

                <div class="row form-group required" >
                    <label for="establishment[townCity]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-town-city'); ?></label>
                    <div class="col-lg-4 itext">
                        <?php echo $this->formRow($form->get('establishment[townCity]')); ?>
                    </div>
                </div>

                <div class="form-group required">
                    <label for="establishment[country]" class="col-lg-3 control-label"><?php echo $this->resourceHelper('correspondence-address-form-label-country'); ?></label>
                    <div class="col-lg-4 itext">
                    <?php echo $this->formRow($form->get('establishment[country]')); ?>
                    </div>
                </div>

            </div>
        </div>
    </div>
