<script>
    <?php if (isset($this->status)) : ?>
    olcs.paymentStatus = '<?php echo $this->status; ?>';
    <?php endif; ?>
</script>
<?php
$this->placeholder('body-class')->set("full-page");
$this->headScript()->prependFile($this->basePath() . '/js/collapsible.init.js');
$this->headScript()->prependFile($this->basePath() . '/js/collapsible.js');
$this->headScript()->prependFile($this->basePath() . '/js/caseTabs.js');
$this->headScript()->prependFile($this->basePath() . '/js/olc.ajax.js');
$this->headScript()->prependFile($this->basePath() . '/js/fees.js');
$this->headScript()->prependFile($this->basePath() . '/js/olc.list.js');

$invoices = '';
if ($this->invoices) {
    $invoicesArr = explode(',', base64_decode($this->invoices));
    $invoices = (count($invoicesArr) > 1) ? 'invoices ' : 'invoice ';
    $invoices .= htmlentities('#'.implode(', #', $invoicesArr));
}

$rows = array();
foreach ($this->dataList as $key => $listItem) {
    if ((float)$listItem['outstandingAmount'] > 0) {
        $options = '';
        if (isset($this->selectedInvoices)) {
            $options = ' '.implode(' ', array(isset($this->selectedInvoices) ? 'disabled' : '', in_array($key, $this->selectedInvoices) ? 'checked' : '')).' ';
        }
        $dateInvoiced = isset($listItem['dateInvoiced']['date']) ? new \DateTime($listItem['dateInvoiced']['date']) : '';
        $rows[] = array('identity-id' => $key,
                                    'columns' => array($listItem['description'], 
                                    $dateInvoiced, 
                                    $listItem['outstandingAmount'], 
                                    array( 'escape' => false, 'value' => '<input type="checkbox" name="invoices[]" value="'.$key.'"'.$options.'>')
                                ));
    }
}
//print_r($rows);
?>
<!-- overlay markup -->
<div class="popup-overlay mfp-hide" id="paymentDialog">
    <div class="popup-header"><?php echo $this->resourceHelper('payment-for'); ?> <?php echo $invoices; ?></div>
    <div class="popup-content">
        <?php if (isset($this->status)) : ?>
            <?php if ($this->status == 'success') : ?>
                    <div class="centre"><h2><?php echo $this->resourceHelper('payment-successful'); ?></h2></div>
            <?php else : ?>
                    <div class="error-lookup" style="background-color: pink">
                        <p class="error-lookup-header"><?php echo $this->resourceHelper('payment-declined'); ?></p>
                        <p><?php echo $this->resourceHelper('card-declined'); ?></p>
                    </div>
            <?php endif; ?>
        <?php endif; ?>
        <div class="pull-right form-group">
            <button type="button" name="cancel" class="btn btn-success btn-cancel" id="paymentOverlayCancelbutton" value="Cancel">Close</button>
        </div>
        <div class="clear-both"></div>
    </div>
</div>
<!-- end overlay markup -->

<div id="applicationDetailsDiv" class="row">
    <?php echo $this->partial('olcs/application/partials/tabs', array('feesActive' => 'active')); ?>
    <div class="accordionAll">
        <div class="dashboard-section" id="feesSection">
            <a href="#" class="collapsible acc-collapsed expanded"><?php echo $this->resourceHelper('fee-details'); ?></a>
            <div class="accordion-row fee-list-sortable">
                <form method="POST" name="paymentType" class="form-horizontal" id="paymentType">
                    <?php echo $this->partial('olcs/application/partials/fees-list-form', array(
                                'rows' => $rows,
                                'header' => 'fee-details',
                            ));
                    ?>
                    <div class="row" id="paymentFormExtras">
                        <div class="col-lg-4">
                            <select class="multiselect" disabled="disable" name="paymentTypeSelect" id="paymentTypeSelect" data-type="html" data-url="<?php echo$this->ajaxUrl; ?>">
                                <option value="0"><?php echo $this->resourceHelper('select-payment-method'); ?></option>
                                <option value="receipt" <?php echo $this->paymentType == 'receipt' ? 'selected' : ''; ?>><?php echo $this->resourceHelper('receipt'); ?></option>
                                <option value="card-payment" <?php echo $this->paymentType == 'card-payment' ? 'selected' : ''; ?>><?php echo $this->resourceHelper('credit-debit-card'); ?></option>
                                <option value="account-balance" <?php echo $this->paymentType == 'account-balance' ? 'selected' : ''; ?>><?php echo $this->resourceHelper('account-balance'); ?></option>
                            </select>
                        </div>
                    </div>
                </form>
                <div id="cardPaymentFormContainer"></div>
            </div>
        </div>
    </div>
</div>