<div class="page-header">
  <div class="page-header__wrapper">
    <h1><?php echo $this->translate('dashboard.title'); ?></h1>
  </div>
</div><!-- page-header-->

<div class="row">

  <div class="dashboard two-thirds js-body">
      <?php
      echo $this->flashMessengerAll();

      /* @var \Zend\View\Helper\Navigation\Menu $menu */
      $menu = $this->navigation($this->navigation('navigation')->getContainer()->findBy('id', 'dashboard-licences-applications'))->menu();
      
      echo $menu->setMinDepth(0)->setMaxDepth(0)
      ->setPartial('partials/tabs-nav');

      if (isset($table)):
        echo $table->render();
      endif;
      ?>
  </div>

  <?php echo $this->partial('partials/dashboard-right-column'); ?>

</div>