<?php
echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->translate('dashboard.title'),
    ]
);
?>

<div class="row">

  <div class="dashboard two-thirds js-body">
      <?php
      echo $this->flashMessengerAll();

      /* @var \Zend\View\Helper\Navigation\Menu $menu */
      $menu = $this->navigation($this->navigation('navigation')->getContainer()->findBy('id', 'dashboard-licences-applications'))->menu();
      
      echo $menu->setMinDepth(0)->setMaxDepth(0)
      ->setPartial('partials/tabs-nav');

      if (isset($table)):
        echo $table;
      endif;
      ?>
  </div>

  <?php echo $this->partial('partials/dashboard-right-column'); ?>

</div>