<?php
echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->translate('dashboard.title'),
    ]
);
?>

<div class="row">
  
  <div class="dashboard two-thirds">
    
    <?php echo $this->flashMessengerAll(); ?>
    
    <?php
    
      /* @var \Zend\View\Helper\Navigation\Menu $menu */
      $menu = $this->navigation($this->navigation('navigation')->getContainer()->findBy('id', 'dashboard-licences-applications'))->menu();
      
      echo $menu->setMinDepth(0)->setMaxDepth(0)
      ->setPartial('partials/tabs-nav');
    
    ?>
    
    <?php if (isset($table)): ?>
      <?php echo $table; ?>
    <?php endif; ?>
    
  </div>

  <?php echo $this->partial('partials/dashboard-right-column'); ?>

</div>