<?php
echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->translate('dashboard.title'),
    ]
);
?>

<div class="row">
    
  <div class="dashboard two-thirds">
    <?php echo $this->flashMessengerAll(); ?>
    <?php echo $this->translate('markup-dashboard-tm-intro'); ?>
    <?php echo $applicationsTable; ?>
  </div>

  <?php echo $this->partial('partials/dashboard-right-column'); ?>

</div>