<div class="empty__wrapper">
    <div class="empty">
        <p><?php echo $this->translate('dashboard-no-licences-text'); ?></p>
        <div class="actions-container">
            <a class="action--primary large" href="<?php echo $this->url('create_application'); ?>" >
                <?php echo $this->translate('application.new.button.first'); ?>
            </a>
        </div>
    </div><!-- empty -->
</div>
