<?php
/* @var \Laminas\View\Helper\Navigation\Menu $menu */
$menu = $this->navigation($this->navigation('navigation')->getContainer()
    ->findBy('id', 'dashboard-licences-applications'))->menu();

echo $menu->setMinDepth(0)->setMaxDepth(0)
    ->setPartial('partials/tabs-nav');

echo $licences;
if ($showVariationTable) {
    echo $variations;
}
if ($showApplicationTable) {
    echo $applications;
}
?>
<div class="govuk-button-group new-application--wrapper">
        <a href="<?php echo $this->url('create_application'); ?>" class="govuk-button" role="button" draggable="false" data-module="govuk-button">
            <?php echo $this->translate('application.new.button'); ?>
</a>
</div>
