<?php
/* @var \Zend\View\Helper\Navigation\Menu $menu */
$menu = $this->navigation($this->navigation('navigation')->getContainer()
    ->findBy('id', 'dashboard-licences-applications'))->menu();

echo $menu->setMinDepth(0)->setMaxDepth(0)
    ->setPartial('partials/dashboard-nav');

echo $licences;
if ($showVariationTable) {
    echo $variations;
}
if ($showApplicationTable) {
    echo $applications;
}
?>
<div class="actions-container new-application--wrapper">
        <a href="<?php echo $this->url('create_application'); ?>" class="action--primary large">
            <?php echo $this->translate('application.new.button'); ?>
</a>
</div>
