

<div class="page-header">
  <div class="page-header__wrapper">
  <h1><?php echo $this->translate('index.title'); ?></h1>
    <div class="page-header__text"><p><?php echo $this->translate('index.subtitle'); ?></p></div>
  </div><!-- .page-header__wrapper -->
</div><!-- .page-header-->


<div class="two-thirds">

  <div class="article">
    <p>What would you like to search for?</p>

    <ul class="search-navigation">

      <li class="search-navigation__item"><a href="<?php echo $this->url('search', ['index'=> 'operator']); ?>">Vehicle Operator details</a></li>
      <li class="search-navigation__item"><a href="<?php echo $this->url('search', ['index'=> 'bus']); ?>">Bus registrations</a></li>
      <li class="search-navigation__item"><a href="<?php echo $this->url('search', ['index'=> 'traffic-commissioner']); ?>">Traffic Commissioner publications</a></li>
      <li class="search-navigation__item"><a href="<?php echo $this->url('search', ['index'=> 'vehicle']); ?>">Vehicles</a></li>

    </ul>
  </div>
</div>