<?php
/**
 * @NOTE: might want to DRY up with Licence / Application Variation overview
 * templates if maintaining three is a pain. Lots of common ground, but they're
 * small templates so no biggie to have them separate for now
 */
?>

<div class="row">
  <?php echo $this->flashMessengerAll(); ?>
  <div class="two-thirds">
    <div class="page-header">
      <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partials/breadcrumbs'); ?>
        <div class="page-header__wrapper">
          <h3 class="page-header__subtitle">
              <?php echo $this->escapeHtml($licenceId); ?>
          </h3>
          <h1><?php echo $this->translate('licence.overview.title'); ?></h1>
        </div>
    </div><!-- page-header -->
    <ul class="overview-navigation">
        <?php
        foreach ($sections as $section) {
            echo $this->render($section);
        }
        ?>
    </ul>
  </div>
  <div class="one-third">

    <dl class="meta">
      <dt><?php echo $this->translate('selfserve-dashboard-target-start-date'); ?></dt>
      <dd><?php echo $startDate ? strftime("%d %B %G",strtotime($startDate)) : ''; ?></dd>
      <dt><?php echo $this->translate('selfserve-dashboard-target-renewal-date'); ?></dt>
      <dd><?php echo $renewalDate ? strftime("%d %B %G",strtotime($renewalDate)) : ''; ?></dd>
      <dt><?php echo $this->translate('status'); ?></dt>
      <dd><?php echo $this->translate($status); ?></dd>
    </dl>

  </div>
</div>


