<li class="overview-item ">
  <div class="overview-item__header">
    <a href="<?php echo $this->url($route, array('id' => $identifier)); ?>" class="overview-item__control">
        <h4><?php echo $this->translate($name); ?></h4>
    </a>
    <?php if (isset($status)): ?>
        <span class="status <?php echo $statusColour; ?>"><?php echo $this->translate($status); ?></span>
    <?php endif; ?>
    <a href="<?php echo $this->url($route, array('id' => $identifier)); ?>" class="overview-item__edit"><?php echo $this->translate($link); ?></a>
  </div>
</li>