<?php
/**
 * @NOTE: might want to DRY up with Licence / Application Variation overview
 * templates if maintaining three is a pain. Lots of common ground, but they're
 * small templates so no biggie to have them separate for now
 */
?>

<div class="page-header">
  <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partials/breadcrumbs'); ?>
  <div class="row">
    <div class="page-header__wrapper two-thirds">
      <h3 class="page-header__subtitle">
          <?php
            echo !empty($licNo) ? $licNo . ' / ' : '';
            echo !empty($applicationId) ? $applicationId : '';
          ?>
      </h3>
      <h1><?php echo $this->translate('application.apply-for-new-licence.title'); ?></h1>
    </div>
    <ul class="page-header__actions one-third">
      <?php if ($canCancel): ?>
      <li>
          <a
              href="<?php echo $this->url('lva-application/cancel', [], [], true); ?>"
              class="page-header__action js-modal-ajax"
          >
              <?php echo $this->translate('application.cancel'); ?>
          </a>
      </li>
      <?php endif; ?>
    </ul>
  </div>
</div><!-- page-header -->

<div class="row">

  <div class="two-thirds border">
      
      <?php echo $this->flashMessengerAll(); ?>
      
      <ul class="overview-navigation">
          <?php 
              foreach ($sections as $section) {
                  echo $this->render($section);
              } 
          ?>
      </ul>
  
      <?php if (isset($submissionForm)): ?>
          <?php echo $this->form($submissionForm); ?>
      <?php endif ?>
    
  </div>
  
  <div class="one-third">
    
    <aside class="sidebar" role="complementary">
      
        <dl class="meta">
            <dt><?php echo $this->translate('progress'); ?></dt>
            <dd><?php echo sprintf($this->translate('application.progress'), $progressX, $progressY); ?></dd>
            <dt><?php echo $this->translate('status'); ?></dt>
            <dd><?php echo $this->translate($status); ?></dd>
            <?php if ($receivedDate): ?>
                <dt><?php echo $this->translate('selfserve-dashboard-submission-date'); ?></dt>
                <dd><?php echo strftime("%d %B %G",strtotime($receivedDate)); ?></dd>
            <?php endif; ?>
            <?php if ($completionDate): ?>
                <dt><?php echo $this->translate('target-completion-date'); ?></dt>
                <dd><?php echo strftime("%d %B %G",strtotime($completionDate)); ?></dd>
            <?php endif; ?>
        </dl>
    
        <div class="links">
            <h3>Applying for a new licence</h3>
            <ul class="links-list">
                <li class="links-list__item">
                    <a href="<?php echo $this->translate('being-an-operator-link'); ?>" target="_blank">
                        <?php echo $this->translate('sidebar-variation-being-an-operator'); ?>
                    </a>
                </li>
                <li class="links-list__item">
                    <a href="<?php echo $this->translate('public-services-link'); ?>" target="_blank">
                        <?php echo $this->translate('sidebar-variation-public-service'); ?>
                    </a>
                </li>
                <li class="links-list__item">
                    <a href="<?php echo $this->translate('vehicle-safety-link'); ?>" target="_blank">
                        <?php echo $this->translate('sidebar-variation-safety-and-maintenance'); ?>
                    </a>
                </li>
            </ul>
        </div>
      
     </aside>
    
  </div>

</div>
