<?php
/**
 * @NOTE: might want to DRY up with Licence / Application Variation overview
 * templates if maintaining three is a pain. Lots of common ground, but they're
 * small templates so no biggie to have them separate for now
 */
?>

<div class="row">
  <div class="two-thirds">
    <?php echo $this->flashMessengerAll(); ?>
    <?php
    echo $this->partial(
        'partials/page-header-simple',
        [
            'pageTitle' => $this->translate('application.apply-for-new-licence.title'),
            'pageSubTitle' => (
                !empty($this->licNo)
                ? $this->licNo . (!empty($this->applicationId) ? ' / ' . $this->applicationId : '')
                : ''
            ),
            'backUrl' => [
                'url' => $this->url('dashboard'),
            ],
        ]
    );
    ?>
    <p><?php echo $this->translate('application.apply-for-new-licence.guide.text'); ?></p>
    <ul class="overview-navigation">
        <?php
            foreach ($sections as $section) {
                echo $this->render($section);
            }
        ?>
    </ul>
  </div>

  <div class="one-third">
    <aside class="sidebar" role="complementary">
      <div class="sidebar__panel">
        <h4 class="sidebar__panel__title">Submit application</h4>

        <?php if (isset($submissionForm)): ?>
          <?php echo $this->form($submissionForm); ?>
        <?php endif ?>
      </div>

      <?php if ($canCancel): ?>
        <ul class="sidebar__actions">
          <li>
              <a href="<?php echo $this->url('lva-application/cancel', [], [], true); ?>" class="js-modal-ajax">
                  <?php echo $this->translate('application.cancel'); ?>
              </a>
          </li>
        </ul>
      <?php endif; ?>

      <dl class="meta">
        <dt><?php echo $this->translate('progress'); ?></dt>
        <dd><?php echo sprintf($this->translate('application.progress'), $progressX, $progressY); ?></dd>
        <dt><?php echo $this->translate('status'); ?></dt>
        <dd><?php echo $this->translate($status); ?></dd>
        <?php if ($receivedDate): ?>
          <dt><?php echo $this->translate('selfserve-dashboard-submission-date'); ?></dt>
          <dd><?php echo strftime("%d %B %G",strtotime($receivedDate)); ?></dd>
        <?php endif; ?>
        <?php if ($completionDate): ?>
          <dt><?php echo $this->translate('target-completion-date'); ?></dt>
          <dd><?php echo strftime("%d %B %G",strtotime($completionDate)); ?></dd>
        <?php endif; ?>
      </dl>
    </aside>
  </div>
</div>
