<?php
/**
 * @NOTE: might want to DRY up with Licence / Application Variation overview
 * templates if maintaining three is a pain. Lots of common ground, but they're
 * small templates so no biggie to have them separate for now
 */
?>

<div class="page-header">
  <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partials/breadcrumbs'); ?>
  <div class="page-header__wrapper">
    <h3 class="page-header__subtitle">
        <?php echo $this->translate('application.overview.application-no'); ?> <?php echo $applicationId; ?>
    </h3>
    <h1><?php echo $this->translate('application.overview.title'); ?></h1>
  </div><!-- end .page-header__wrapper -->
  <ul class="page-header__actions">
    <?php if ($canCancel): ?>
      <li>
        <a
          href="<?php echo $this->url('lva-variation/cancel', [], [], true); ?>"
          class="page-header__action js-modal-ajax">
          <?php echo $this->translate('application.cancel'); ?>
        </a>
      </li>
    <?php endif; ?>
  </ul>
</div>
<div class="two-thirds border">
  <?php echo $this->flashMessengerAll(); ?>
  <ul class="overview-navigation">
      <?php
      foreach ($sections as $section) {
          echo $this->render($section);
      }
      ?>
  </ul>
  <?php if (isset($submissionForm)): ?>
    <?php echo $this->form($submissionForm); ?>
  <?php endif ?>
</div>
<div class="one-third sidebar">
  <dl class="meta">
    <dt><?php echo $this->translate('status'); ?></dt>
    <dd><?php echo $this->translate($status); ?></dd>
    <?php if ($receivedDate): ?>
        <dt><?php echo $this->translate('selfserve-dashboard-submission-date'); ?></dt>
        <dd><?php echo strftime("%d %B %G",strtotime($receivedDate)); ?></dd>
    <?php endif; ?>
    <?php if ($completionDate): ?>
        <dt><?php echo $this->translate('target-completion-date'); ?></dt>
        <dd><?php echo strftime("%d %B %G",strtotime($completionDate)); ?></dd>
    <?php endif; ?>
  </dl>

  <div class="links">
    <h3>Applying for a variation</h3>
    <ul class="links-list">
        <li class="links-list__item"><a target="blank" href="http://gov.uk/being-a-goods-vehicle-operator">Being a goods vehicle operator</a></li>
        <li class="links-list__item"><a target="blank" href="https://www.gov.uk/psv-operator-licences">Public Service Vehicle operator licences</a></li>
        <li class="links-list__item"><a href="/guides/advertising-your-operating-centre-gb/">How to advertise your goods application</a></li>
        <li class="links-list__item"><a href="/guides/financial-evidence">How to provide financial evidence</a></li>
        <li class="links-list__item"><a target="blank" href="https://gov.uk/government/collections/vehicle-safety-and-maintenance-guides ">Vehicle safety and maintenance guides</a></li>
    </ul>
  </div>
</div>
