<?php
/**
 * @NOTE: might want to DRY up with Licence / Application Variation overview
 * templates if maintaining three is a pain. Lots of common ground, but they're
 * small templates so no biggie to have them separate for now
*/
?>

<div class="row">
  <?php echo $this->flashMessengerAll(); ?>
  <div class="two-thirds">
    <div class="page-header">
      <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partials/breadcrumbs'); ?>
        <div class="page-header__wrapper">
         <?php
                if (!empty($licNo)) {
              ?>
              <h3 class="page-header__subtitle">
                  <?php
                  $reference = $licNo;
                  $reference .= !empty($applicationId) ? ' / ' . $applicationId : '';
                  echo $this->escapeHtml($reference);
                  ?>
              </h3>
              <?php
                }
              ?>
              <h1><?php echo $this->translate('application.apply-to-change-licence.title'); ?></h1>
        </div>
    </div><!-- page-header -->
    <p><?php echo $this->translate('application.apply-to-change-licence.guide.text'); ?></p>
    <ul class="overview-navigation">
        <?php
            foreach ($sections as $section) {
                echo $this->render($section);
            }
        ?>
    </ul>
  </div>
  <div class="one-third">
    <aside class="sidebar" role="complementary">
      <div class="sidebar__panel">
        <h4 class="sidebar__panel__title">Submit application</h4>

        <?php if (isset($submissionForm)): ?>
            <?php echo $this->form($submissionForm); ?>
        <?php endif ?>
      </div>

      <?php if ($canCancel): ?>
        <ul class="sidebar__actions">
          <li>
            <a href="<?php echo $this->url('lva-variation/cancel', [], [], true); ?>"
               class="js-modal-ajax"
              >
              <?php echo $this->translate('application.cancel'); ?>
            </a>
          </li>
        </ul>
      <?php endif; ?>

      <dl class="meta">
        <dt><?php echo $this->translate('status'); ?></dt>
        <dd><?php echo $this->translate($status); ?></dd>
        <?php if ($receivedDate): ?>
          <dt><?php echo $this->translate('selfserve-dashboard-submission-date'); ?></dt>
          <dd><?php echo strftime("%d %B %G",strtotime($receivedDate)); ?></dd>
        <?php endif; ?>
        <?php if ($completionDate): ?>
          <dt><?php echo $this->translate('target-completion-date'); ?></dt>
          <dd><?php echo strftime("%d %B %G",strtotime($completionDate)); ?></dd>
        <?php endif; ?>
      </dl>
    </aside>
  </div>
</div>




