<div class="page-header">
  <?php echo $this->navigation('Olcs\Navigation\DashboardNavigation')
    ->breadcrumbs()
    ->setPartial('partials/breadcrumbs'); ?>
  <div class="page-header__wrapper">
    <h1><?php echo $this->translate('pay-fees.success.title'); ?></h1>
  </div><!-- end .page-header__wrapper -->
</div>
<div class="three-quarters">

<?php echo $this->render(
    'partials/read-only/main',
    [
        'header' => 'pay-fees.success.header',
        'multiItems' => [
            [
                [
                    'label' => 'pay-fees.success.operator-name',
                    'value' => $operatorName,
                ],
                [
                    'label' => 'pay-fees.success.paid-by',
                    'value' => $fees[0]['payerName'],
                ],
                [
                    'label' => 'pay-fees.success.payment-reference',
                    'value' => $payment['guid'],
                ],
                [
                    'label' => 'pay-fees.success.received',
                    'date' => $fees[0]['receivedDate'],
                ],
            ],
          ],
      ]
    );
  ?>
  <!-- table -->
  <?php if (isset($table)): ?>
    <?php echo $table; ?>
  <?php endif; ?>

  <hr>

  <?php echo $this->translate('markup-pay-fees-success-notice'); ?>

  <hr>

  <div class="actions-container">
    <a href="<?php echo $this->url('fees');?>" class="action--primary large"><?php echo $this->translate('pay-fees.success.back-to-home'); ?></a>
    <a href="<?php echo $this->url('fees/receipt', ['action' => 'print'], [], true);?>" class="action--secondary large"><?php echo $this->translate('pay-fees.success.print-receipt'); ?></a>
  </div>

</div>