<?php echo $this->doctype(); ?>
<html lang="en" class="review">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle($this->translate(''));
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headLink()->appendStylesheet($this->assetPath('/styles/' . $this->applicationName() . '.css'));
        echo $this->headScript();
        ?>
    </head>
    <body>
        <h1><?php echo $this->translate('pay-fees.success.print-title'); ?></h1>

<?php echo $this->render(
    'partials/read-only/main',
    [
        'header' => 'pay-fees.success.header',
        'multiItems' => [
            [
                [
                    'label' => 'pay-fees.success.operator-name',
                    'value' => $operatorName,
                ],
                [
                    'label' => 'pay-fees.success.paid-by',
                    'value' => $fees[0]['payerName'],
                ],
                [
                    'label' => 'pay-fees.success.payment-reference',
                    'value' => $payment['guid'],
                ],
                [
                    'label' => 'pay-fees.success.received',
                    'date' => $fees[0]['receivedDate'],
                ],
            ],
          ],
      ]
    );
  ?>
  <!-- table -->
  <?php if (isset($table)): ?>
    <?php echo $table; ?>
  <?php endif; ?>

  <hr>

  <?php echo $this->translate('markup-pay-fees-success-notice'); ?>
