<div class="page-header">
  <ol class="breadcrumbs">
    <li class="breadcrumbs__item"><a href="">Back to overview</a></li>
  </ol>
  <div class="page-header__wrapper">
  <h3 class="page-header__subtitle">Step X of Y</h3>
  <h1><?php echo $this->translate($title); ?></h1>
  </div><!-- .page-header__wrapper -->
</div><!-- .page-header-->

<div class="three-quarters">

  <?php echo $this->flashMessengerAll(); ?>

  <?php if (isset($table)): ?>
    <?php echo $table; ?>
  <?php endif; ?>

  <?php if (isset($form)): ?>
    <?php
    $form->prepare();
    echo $this->formErrors($form);
    echo $this->form($form);
    ?>
  <?php endif; ?>
</div><!-- .three-quarters -->
