<div class="full-width">
    <?php echo $this->flashMessengerAll(); ?>

    <?php if (isset($title)): ?>
        <h2><?php echo $this->translate($title); ?></h2>
    <?php endif; ?>


    <?php if (isset($table)): ?>
        <?php echo $table; ?>
    <?php endif; ?>

    <?php if (isset($form)): ?>
        <?php
        $form->prepare();
        echo $this->formErrors($form);
        echo $this->form($form);
        ?>
    <?php endif; ?>
</div>
