<div class="page-header">
    <div class="page-header__wrapper">
        <h1>Thank you</h1>
    </div><!-- .page-header__wrapper -->
</div><!-- .page-header -->

<div class="two-thirds">
    <div class="confirmation">
        <h2>Application submitted</h2>
        <p><b>Reference number:</b></p>
        <h2>OB127253/9734</h2>
    </div><!-- .confirmation -->
    <div class="article">
        <h3 class="important">Important</h3>
        <p>You are advised that you cannot lawfully operate goods vehicles with a gross plated weight exceeding 3.5 tonnes for the carriage of goods in connection with your trade or business or for hire or reward until your application has been granted, any relevant grant fee has been paid and the licence documents issued or until you have been issued with an interim licence.  If you do so, and this is brought to the attention of the Traffic Commissioner you risk having your application refused.</p>
        <h3>Before your application can be processed you must:</h3>
        <ul>
            <li>Approve any outstanding Transport Manager applications</li>
            <li>
                Send any supporting documents that were requested but you did not upload during the application. Please write the application reference on any paper copies you send to:<br>
                <br>Central Licensing Office<br>386 Hillcrest House<br>Harehills Lane<br>Leeds<br>LS9 6NF
            </li>
        </ul>
        <h3>What happens next?</h3>
        <p>The Central Licensing Office aims to process your application as soon as possible. The information provided will be checked and further information may be requested.</p>
        <a href="<?php echo $this->url('dashboard'); ?>" class="action--primary large">Back to dashboard</a>
    </div><!-- .article -->
</div><!-- .two-thirds -->