<div class="page-header">
    <div class="page-header__wrapper">
        <h1><?php echo $this->translate('lva-summary-title'); ?></h1>
    </div><!-- .page-header__wrapper -->
</div><!-- .page-header -->

<div class="two-thirds">
    <div class="confirmation">
        <h2><?php echo $this->translate('lva-summary-application-submitted'); ?></h2>
        <p><b><?php echo $this->translate('lva-summary-reference-number'); ?></b></p>
        <h2><?php echo $licence;?>/<?php echo $application; ?></h2>
    </div><!-- .confirmation -->
    <div class="article">
        <h3 class="important"><?php echo $this->translate('lva-summary-important'); ?></h3>
        <?php echo $this->translate($warningText); ?>
        <h3><?php echo $this->translate('lva-summary-application-before-processing'); ?></h3>
        <ul>
            <?php foreach ($actions as $action) : ?>
            <li><?php echo $this->translate($action); ?></li>
            <?php endforeach; ?>
        </ul>
        <h3><?php echo $this->translate('lva-summary-what-next-title'); ?></h3>
        <p><?php echo $this->translate('lva-summary-application-what-next-text'); ?></p>
        <a href="<?php echo $this->url('dashboard'); ?>" class="action--primary large">
            <?php echo $this->translate('lva-summary-back-to-dashboard'); ?>
        </a>
    </div><!-- .article -->
</div><!-- .two-thirds -->