<div class="page-header">
    <div class="page-header__wrapper">
        <h3 class="page-header__subtitle"><?php echo $this->currentUser()->getOrganisationName() ?></h3>
        <h1><?php echo $this->translate('Manage users'); ?></h1>
    </div>
</div><!-- page-header-->

<div class="row">

  <div class="dashboard two-thirds js-body">
      <?php echo $this->flashMessengerAll(); ?>
      <?php echo $users->render(); ?>
  </div>

</div>
