<?php
    echo $this->render(
        '/partials/page-header.phtml',
        [
            'pageTitle' => $this->pageTitle(),
            'backUrl' => [
                'url' => $this->url('manage-user'),
            ],
        ]
    );
?>
<div class="row">
  <div class="two-thirds">
    <?php
        $guidanceMessage = $this->placeholder('guidance');
        if (!empty($guidanceMessage)) {
            foreach ($guidanceMessage as $message):
                ?>
                <div class="govuk-inset-text">
                    <p><?php echo $this->translate($message); ?></p>
                </div>
            <?php
            endforeach;
        }

      echo $this->flashMessengerAll();
      echo $this->formErrors($this->form);
      echo $this->form($this->form);
    ?>
  </div>
</div>
