<?php
    echo $this->render(
        '/partials/page-header.phtml',
        [
            'pageTitle' => $this->pageTitle(),
            'backUrl' => [
                'url' => $this->url('manage-user'),
            ],
        ]
    );
?>
<div class="row">
  <div class="two-thirds">
    <?php
      echo $this->flashMessengerAll();
      echo $this->formErrors($this->form);
      echo $this->form($this->form);
    ?>
  </div>
</div>
