<?php

declare(strict_types=1);

namespace Common\Util;

use Laminas\Uri\Exception\ExceptionInterface as UriException;
use Laminas\Uri\Http as HttpUri;

/**
 * Decides whether a caller-supplied redirect target is safe to send a user to.
 *
 * Any redirect whose destination comes from the request is an open redirect unless the
 * destination is constrained. An unconstrained one is a phishing primitive: the victim
 * follows a link on the real, authenticated site and lands on an attacker's page.
 *
 * Two shapes are considered safe, and nothing else is:
 *
 *  - a root-relative path, which cannot leave the origin at all. This is the shape the
 *    apps actually produce — Request::getRequestUri() returns a path.
 *  - an absolute URL whose host equals the host of the current request.
 *
 * Everything else is rejected, including scheme-bearing URLs (javascript:, data:),
 * protocol-relative URLs (//evil.example) and their backslash variants, which several
 * browsers normalise to forward slashes and would otherwise slip past a naive check.
 *
 * Why this is hand-written, since that is the first question it invites
 * ------------------------------------------------------------------------------------
 * Not because URL parsing is being reimplemented — the parsing is delegated to
 * Laminas\Uri below. It is because the two things disagree about what a backslash is,
 * and the disagreement is the whole vulnerability.
 *
 * RFC 3986 says a backslash is an ordinary path character, so "/\evil.example" is a
 * perfectly ordinary absolute path and every RFC-conformant parser will say so. The
 * WHATWG URL Standard, which is what browsers actually implement, folds "\" into "/"
 * while parsing the authority of an http(s) URL — so a browser handed that same string
 * in a Location header navigates to http://evil.example. Both parsers are correct; only
 * one of them predicts where the user ends up, and that is the one that matters here.
 *
 * So an off-the-shelf RFC 3986 validator cannot stand in for this. It would accept
 * "/\evil.example" and "/\/evil.example" and reopen the hole this class was written to
 * close. Verified rather than assumed: run those two through any RFC-conformant parser's
 * "is this an absolute path" check and it returns true.
 *
 * Nor is the policy itself something a library can own. "Safe" is application-specific —
 * whether sibling subdomains count as same-origin, whether a bare relative path is
 * acceptable, whether an absolute URL is allowed at all. Libraries supply the parse; the
 * decision stays here.
 *
 * Revisit on PHP 8.5
 * ------------------------------------------------------------------------------------
 * PHP 8.5 ships a WHATWG-conformant parser in core as Uri\WhatWg\Url. Once the apps are
 * on it, the browser-quirk handling in isSafePath() — the backslash normalisation, the
 * leading-whitespace and control-character rejection — can be deleted in favour of
 * parsing the candidate with that class and comparing origins, because it models the
 * same behaviour the browser will apply. What should stay is the policy: which shapes
 * this service is willing to redirect to.
 *
 * Until then the checks below are load-bearing. Do not "simplify" them into a scheme
 * test or a generic URL validator without re-reading the paragraph above.
 */
class SafeRedirectUrl
{
    /**
     * True if $candidate is a root-relative path that cannot leave the current origin.
     *
     * Use this where the redirect target is generated by the app itself as a path, which
     * is the common case. It needs no knowledge of the current request.
     */
    public static function isSafePath(?string $candidate): bool
    {
        if ($candidate === null || $candidate === '') {
            return false;
        }

        // Browsers treat a backslash as a forward slash when parsing the authority, so
        // "/\evil.example" and "\\evil.example" are protocol-relative in practice. Test
        // the normalised form rather than the literal one.
        $normalised = str_replace('\\', '/', $candidate);

        // Leading whitespace and control characters are stripped by browsers before
        // parsing, so " javascript:alert(1)" would otherwise pass a scheme check.
        if ($normalised !== trim($normalised, " \t\n\r\0\x0B")) {
            return false;
        }

        if (preg_match('/[\x00-\x1F\x7F]/', $normalised) === 1) {
            return false;
        }

        // Must be root-relative. A bare "foo" is resolved against the current directory,
        // which is origin-safe, but accepting it invites confusion for no benefit.
        if (!str_starts_with($normalised, '/')) {
            return false;
        }

        // "//host" and "/\host" are protocol-relative: same scheme, different origin.
        if (str_starts_with($normalised, '//')) {
            return false;
        }

        return true;
    }

    /**
     * True if $candidate is safe to redirect to given the host of the current request.
     *
     * Accepts a root-relative path, or an absolute URL on $currentHost. Pass the host of
     * the incoming request, not a configured one, so the check holds behind any hostname
     * the service answers on.
     */
    public static function isSafeForHost(?string $candidate, ?string $currentHost): bool
    {
        if (self::isSafePath($candidate)) {
            return true;
        }

        if ($candidate === null || $candidate === '' || $currentHost === null || $currentHost === '') {
            return false;
        }

        // HttpUri throws rather than returning an invalid instance when the scheme is one
        // it does not accept, so "javascript:alert(1)" raises here rather than failing
        // isValid(). Anything unparseable is unsafe by definition.
        try {
            $uri = new HttpUri($candidate);
        } catch (UriException $e) {
            return false;
        }

        if (!$uri->isValid() || !$uri->isAbsolute()) {
            return false;
        }

        // Only ever http(s). HttpUri rejects other schemes, but be explicit — this is the
        // property that matters, not an incidental consequence of the parser.
        if (!in_array(strtolower((string) $uri->getScheme()), ['http', 'https'], true)) {
            return false;
        }

        return strcasecmp((string) $uri->getHost(), $currentHost) === 0;
    }
}
