<?php

declare(strict_types=1);

namespace Common\Util;

use Laminas\Uri\Exception\ExceptionInterface as UriException;
use Laminas\Uri\Http as HttpUri;

/**
 * Decides whether a caller-supplied redirect target is safe to send a user to.
 *
 * Any redirect whose destination comes from the request is an open redirect unless the
 * destination is constrained. An unconstrained one is a phishing primitive: the victim
 * follows a link on the real, authenticated site and lands on an attacker's page.
 *
 * Two shapes are considered safe, and nothing else is:
 *
 *  - a root-relative path, which cannot leave the origin at all. This is the shape the
 *    apps actually produce — Request::getRequestUri() returns a path.
 *  - an absolute URL whose host equals the host of the current request.
 *
 * Everything else is rejected, including scheme-bearing URLs (javascript:, data:),
 * protocol-relative URLs (//evil.example) and their backslash variants, which several
 * browsers normalise to forward slashes and would otherwise slip past a naive check.
 */
class SafeRedirectUrl
{
    /**
     * True if $candidate is a root-relative path that cannot leave the current origin.
     *
     * Use this where the redirect target is generated by the app itself as a path, which
     * is the common case. It needs no knowledge of the current request.
     */
    public static function isSafePath(?string $candidate): bool
    {
        if ($candidate === null || $candidate === '') {
            return false;
        }

        // Browsers treat a backslash as a forward slash when parsing the authority, so
        // "/\evil.example" and "\\evil.example" are protocol-relative in practice. Test
        // the normalised form rather than the literal one.
        $normalised = str_replace('\\', '/', $candidate);

        // Leading whitespace and control characters are stripped by browsers before
        // parsing, so " javascript:alert(1)" would otherwise pass a scheme check.
        if ($normalised !== trim($normalised, " \t\n\r\0\x0B")) {
            return false;
        }

        if (preg_match('/[\x00-\x1F\x7F]/', $normalised) === 1) {
            return false;
        }

        // Must be root-relative. A bare "foo" is resolved against the current directory,
        // which is origin-safe, but accepting it invites confusion for no benefit.
        if (!str_starts_with($normalised, '/')) {
            return false;
        }

        // "//host" and "/\host" are protocol-relative: same scheme, different origin.
        if (str_starts_with($normalised, '//')) {
            return false;
        }

        return true;
    }

    /**
     * True if $candidate is safe to redirect to given the host of the current request.
     *
     * Accepts a root-relative path, or an absolute URL on $currentHost. Pass the host of
     * the incoming request, not a configured one, so the check holds behind any hostname
     * the service answers on.
     */
    public static function isSafeForHost(?string $candidate, ?string $currentHost): bool
    {
        if (self::isSafePath($candidate)) {
            return true;
        }

        if ($candidate === null || $candidate === '' || $currentHost === null || $currentHost === '') {
            return false;
        }

        // HttpUri throws rather than returning an invalid instance when the scheme is one
        // it does not accept, so "javascript:alert(1)" raises here rather than failing
        // isValid(). Anything unparseable is unsafe by definition.
        try {
            $uri = new HttpUri($candidate);
        } catch (UriException $e) {
            return false;
        }

        if (!$uri->isValid() || !$uri->isAbsolute()) {
            return false;
        }

        // Only ever http(s). HttpUri rejects other schemes, but be explicit — this is the
        // property that matters, not an incidental consequence of the parser.
        if (!in_array(strtolower((string) $uri->getScheme()), ['http', 'https'], true)) {
            return false;
        }

        return strcasecmp((string) $uri->getHost(), $currentHost) === 0;
    }
}
