<?php
echo $this->partial('olcs/common/generic-list/genericListWrapperPlain', array(
'id' => 'fees-list',
//'idListForm' => 'fees-form',
'sortable' => true,
'data' => null,
'headers' => array(array('sortable' => true, 'title' => 'Description'),
                                array('sortable' => true, 'title' => 'Date invoiced'),
                                array('sortable' => true, 'title' => 'Fee amount £'),
                                array('sortable' => true, 'title' => 'Select')),
                    'columnClasses' => array('column-description', 'fcolumn-date-invoiced', 'column-amount', 'column-select'),
                    'rows' => $rows
));
?>
