    <div class="col-md-12 tFormHeader application-details-header">
       
        <ul class="details-list col">
            <li>
                <span class="details-list-label"><?php echo $this->resourceHelper('licence-application-number'); ?>:</span>
                <?php echo isset($application_header_details['licenceNumber']) ? $this->escapeHtml($application_header_details['licenceNumber']) : ''; ?>
                (<?php echo isset($application_header_details['applicationNumber']) ? $this->escapeHtml($application_header_details['applicationNumber']) : ''; ?>)
            </li>
            <li>
                <span class="details-list-label"><?php echo $this->resourceHelper('operator-type'); ?>:</span>
                <?php echo $this->escapeHtml($application_header_details['operatorTypes']); ?>
            </li>
            <li>
                <span class="details-list-label"><?php echo $this->resourceHelper('type-of-licence'); ?>:</span>
                <?php echo $this->escapeHtml($application_header_details['licenceTypes']); ?>
            </li>
        </ul>
        <ul class="details-list col">
            <li>
                <span class="details-list-label"><?php echo $this->resourceHelper('entity-type'); ?>:</span>
                <?php echo $this->escapeHtml($application_header_details['entityTypes']); ?>
            </li>
            <li>
                <span class="details-list-label"><?php echo $this->resourceHelper('date-app-rec'); ?>:</span>
                <?php echo $this->simpleDateFormat($application_header_details['dateApplicationReceived']);
                ?>
            </li>
            <li>
                <span class="details-list-label"><?php echo $this->resourceHelper('traffic-area'); ?>:</span>
                <?php echo $this->escapeHtml($application_header_details['trafficAreaType']); ?>
            </li>
        </ul>
        <ul class="actions">
            <li class="action-edit"><a class="linkBlue" href="<?php echo $this->url('application_new');?>"><?php echo $this->resourceHelper('edit'); ?></a></li>
        </ul>
    </div>