<h2 class="inline"><?php echo $this->translate('application.review-declarations.summary'); ?></h2>
<a href="<?php echo $this->url(null, array('action' => 'simple'), array(), true) ?>" class="right-aligned action--tertiary" target="_blank">
    <?php echo $this->translate('application.review-declarations.summary.new-window'); ?>
</a>
<?php
if (isset($form)) {

    $form->prepare();
    echo $this->form()->openTag($form);

    ?>
    <div class="read-only">
        <?php
        foreach ($form->getFieldsets() as $fieldset) {

            if ($fieldset->getName() != 'form-actions') {
                echo $this->formCollection($fieldset);
            }
        }
        ?>
    </div>
    <?php

    echo $this->formCollection($form->get('form-actions'));
    echo $this->form()->closeTag();
}
