<?php
$irhpPermit = $this->placeholder('irhpPermit')->getValue();
$note = $this->placeholder('note')->getValue();
?>
<div class="small-module">
    <h4 class="title">Operator details</h4>
    <p class="small-module__details">
        <a href="<?php echo $this->url('operator/business-details', ['organisation' => $irhpPermit['licence']['organisation']['id']], [], true);?>">
            <?php echo $this->escapeHtml($irhpPermit['licence']['organisation']['name']); ?>
        </a>
    </p>
</div>

<div class="small-module">
    <h4 class="title">Licence details</h4>
    <p class="small-module__details">
        <a href="<?php echo $this->url('lva-licence', ['licence' => $irhpPermit['licence']['id']], [], false); ?>"><?php echo $this->escapeHtml($irhpPermit['licence']['licNo']); ?></a><br>
        <?php echo $this->escapeHtml($this->translate($irhpPermit['licence']['licenceType']['id'])); ?><br/>
        <?php echo $this->escapeHtml($this->translate($irhpPermit['licence']['status']['id'])); ?>
    </p>
</div>

<?php
/**
 * Case quick actions
 *
 * @var \Zend\Navigation\Navigation
 */
$nav = $this->navigation('right-sidebar')
    ->menu($this->navigation()->findOneBy('id', 'irhp-permit-quick-actions'))
    ->setPartial('partials/record-actions__group');
?>
<?php if (count($nav->getContainer()) > 0): ?>
    <div class="record-actions">
        <h4 class="title">Quick actions</h4>
        <?php echo $nav; ?>
    </div>
<?php endif; ?>


<?php
/**
 * Permit Descsions
 *
 * @var \Zend\Navigation\Navigation
 */
$nav = $this->navigation('right-sidebar')
    ->menu($this->navigation()->findOneBy('id', 'irhp-permit-decisions'))
    ->setPartial('partials/record-actions__group');
?>
<?php if (count($nav->getContainer()) > 0): ?>
    <div class="record-actions">
        <h4 class="title">Decisions</h4>
        <?php echo $nav; ?>
    </div>
<?php endif; ?>