<?php
$irhpPermit = $this->placeholder('irhpPermit')->getValue();
$note = $this->placeholder('note')->getValue();
$isPriorityNote = $this->placeholder('isPriorityNote')->getValue();
?>
<div class="small-module">
    <h4 class="title"><?php echo $this->translate('entity-details-nav-operator-details'); ?></h4>
    <p class="small-module__details">
        <?php
        echo $this->link(
            $this->url('operator/business-details', ['organisation' => $irhpPermit['licence']['organisation']['id']], [], true),
            $irhpPermit['licence']['organisation']['name']
        );
        ?>
    </p>
</div>

<div class="small-module">
    <h4 class="title"><?php $this->translate('entity-details-nav-licence-details'); ?></h4>
    <p class="small-module__details">
        <?php
            echo $this->link(
                $this->url('lva-licence', ['licence' => $irhpPermit['licence']['id']], [], false),
                $irhpPermit['licence']['licNo']
            );
        ?>
        <br>
        <?php echo $this->escapeHtml($this->translate($irhpPermit['licence']['licenceType']['id'])); ?><br/>
        <?php echo $this->escapeHtml($this->translate($irhpPermit['licence']['status']['id'])); ?>
    </p>
</div>

<?php
/**
 * Case quick actions
 *
 * @var \Laminas\Navigation\Navigation
 */
$nav = $this->navigation('right-sidebar')
    ->menu($this->navigation()->findOneBy('id', 'irhp-permit-quick-actions'))
    ->setPartial('partials/record-actions__group');
?>
<?php if (count($nav->getContainer()) > 0): ?>
    <div class="record-actions">
        <h4 class="title"><?php echo $this->translate('internal-operator-quick-actions'); ?></h4>
        <?php echo $nav; ?>
    </div>
<?php endif; ?>


<?php
/**
 * Permit Decisions
 *
 * @var \Laminas\Navigation\Navigation
 */
$nav = $this->navigation('right-sidebar')
    ->menu($this->navigation()->findOneBy('id', 'irhp-permit-decisions'))
    ->setPartial('partials/record-actions__group');
?>
<?php if (count($nav->getContainer()) > 0): ?>
    <div class="record-actions">
        <h4 class="title"><?php echo $this->translate('decisions'); ?></h4>
        <?php echo $nav; ?>
    </div>
<?php endif; ?>

<?php if (!empty($note) && !$this->isGranted(Common\RefData::PERMISSION_INTERNAL_LIMITED_READ_ONLY)): ?>
    <div class="latest-note">
        <div class="latest-note__<?php echo ($isPriorityNote ? "priority" : "details"); ?>">
            <?php echo $this->escapeHtml(substr($note, 0, 100)); ?>
        </div>
        <?php
        echo $this->link(
            $this->url('licence/irhp-application-processing/notes', ['licence' => $irhpPermit['licence']['id'], 'irhpAppId' => $irhpPermit['id']]),
            'View all notes',
            'latest-note__link'
        );
        ?>
    </div>
<?php endif; ?>
