<?php 
$this->placeholder('body-class')->set("full-page");
$this->headScript()->prependFile($this->basePath() . '/js/olc.ajax.js');
?>
<?php $detailsForm->prepare(); ?>
 <?php echo $this->form()->openTag($detailsForm); ?>
<div id="caseDetailsDiv" class="row">
    <div class="col-md-12 tFormHeader case-details-header">
        <ul class="actions">
            <li class="action-case-note"><a class="btn btn-note" href="#"><?php echo $this->resourceHelper('view-add-case-notes'); ?></a></li>
            <li class="action-save"><a data-url="/case/ajax-detail-save" data-params="caseDetailsNote detailTypes" class="btn btn-save" href="#"><?php echo $this->resourceHelper('save'); ?></a></li>
            <li class="action-edit"><a class="btn" href="#"><?php echo $this->resourceHelper('edit'); ?></a></li>
        </ul>
        <ul class="details-list">
            <li class="description">
                <span class="details-list-label"><?php echo $this->resourceHelper('summary'); ?>:</span>
                <?php echo $this->escapeHtml($params['description']); ?>
            </li>
            <li>
                <span class="details-list-label"><?php echo $this->resourceHelper('case-number'); ?>:</span>
                <?php echo $this->escapeHtml($params['caseNumber']); ?>
            </li>
            <li>
                <span class="details-list-label"><?php echo $this->resourceHelper('operator-name'); ?>:</span>
                <?php echo $this->escapeHtml($params['operatorName']); ?>
            </li>
            <li>
                <span class="details-list-label"><?php echo $this->resourceHelper('licence-number'); ?>:</span>
                <?php echo $this->escapeHtml($params['licenceNumber']); ?>
            </li>
            <li>
                <span class="details-list-label"><?php echo $this->resourceHelper('categories'); ?>:</span>
                <?php echo $this->escapeHtml(implode(', ', $params['categories'])); ?>
            </li>
            <li>
                <span class="details-list-label"><?php echo $this->resourceHelper('ecms-number'); ?>:</span>
                <?php echo $this->escapeHtml($params['ecms']); ?>
            </li>
        </ul>
        <?php echo $this->partial('olcs/vcase/partials/tabs', array('caseId' => $caseId, 'convictionActive' => 'active')); ?>
    </div>
    <div>
        <textarea class="tmce" data-mce-size="300" id='caseDetailsNote' name="caseDetailsNote"></textarea>
    </div>
    <div>
        <div class="convLink"><a class="show-collapsed">Conviction input form</a></div>
        <hr>
        <div  class="row">
            <div class="col-md-4">
                <?php echo $this->formRow($detailsForm->get('detailTypeId')); ?>
                    <?php echo $this->formRow($detailsForm->get('caseId')); ?>
            </div>
            <div class="col-md-4">
                <div class="col-md-11 required"><?php echo $this->formRow($detailsForm->get('submitActionTypes')); ?></div>
                <div class="col-md-1"></div>
            </div>
            <div class="col-md-4" style="text-align: right"><?php echo $this->formRow($detailsForm->get('submit')); ?></div>
        </div>
        <div id="showit"></div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
