<?php

    $left = '';
    $right = '';
    $toggle = 0;

    // Remove duplicate continuations page in Navigation. Used to correctly display continuation filters and
    // 'Generate continuations' back link which would otherwise be an inactive link.
    $continuationsPage = $this->container->findOneById('admin-dashboard/continuations-details');
    $this->container->removePage($continuationsPage);

    foreach ($this->container as $key => $page) :
        if ($page->isVisible(true) && $this->navigation()->accept($page, false)) {
            $leftOrRight = ($toggle%2==0) ? 'left' : 'right';
                $$leftOrRight .= '<li class="admin__item ' . ($page->isActive(true) ? 'current' : '') .'">';
                $$leftOrRight .= $this->navigation()->menu()->htmlify($page);
                $$leftOrRight .= '</li>';
                $toggle++;
        }
    endforeach;
?>

<ul class="admin">
    <li class="admin__title"><?php echo $this->translate('Admin'); ?>
        <div class="admin__menu">
            <span class="admin__arrow"></span>
            <ul class="admin__submenu">
                <?php echo $left; ?>
            </ul>
            <ul class="admin__submenu">
                <?php echo $right; ?>
            </ul><!-- admin__submenu -->
        </div><!-- admin__menu -->
    </li>
</ul><!-- .vertical-navigation -->
