<div role="banner" class="global-header">
    <div class="global-header__wrapper">
        <h2 class="global-header__title"><a href="/">OLCS</a></h2>
        <?php echo $this->partial('layout/partials/search'); ?>
        <?php
        if ($this->isGranted('internal-case-worker') || $this->isGranted('internal-admin')) {
            $navigation = $this->navigation('navigation')->findOneBy('id', 'admin-dashboard');
            echo $this->navigation('navigation')->menu($navigation)->setPartial('layout/partials/admin-menu');
        }
        ?>
    </div><!-- end global-header__wrapper -->
</div><!-- end global-header -->
