<div class="page-header">
  <div class="page-header__wrapper">
    <div class="user-header">
      <?php  echo $this->navigation('navigation') // <-- Update this!!
      ->breadcrumbs()
      ->setMinDepth(0)
      ->setPartial(array('layout/partials/breadcrumbs.phtml', 'Olcs'));
      ?>
      <ul class="user-menu">
        <li class="user-menu__item">Sam Quayle:</li>
        <li class="user-menu__item"><a href="">My settings</a></li>
        <li class="user-menu__item"><a href="">Sign out</a></li>
      </ul>
    </div><!-- user-header -->

    <h1><?php echo (isset($pageTitle) ? $pageTitle : ''); ?></h1>
    <h3 class="page-header__subtitle"><?php echo (isset($pageSubTitle) ? $pageSubTitle : ''); ?></h3>

  </div><!-- end .page-header__wrapper-->
</div><!-- end .page-header-->