<div class="search">
    <div class="search__wrapper">
        <?php
        {
            $searchForm = $this->placeholder('headerSearch')->getValue();
            if (!empty($searchForm)):
                ?>
                <form action="<?php echo $this->url('search')?>" method="POST">
                    <?php echo $this->formInput($searchForm->get('search')); ?>
                    <div class="search__select">
                        <?php echo $this->formSelect($searchForm->get('index')); ?>
                    </div><!-- .search__select -->
                    <?php echo $this->formSubmit($searchForm->get('submit')); ?>
                </form>
            <?php
            endif;
        }
        ?>
    </div>
</div><!--  search -->