<?php
$appeal = $this->placeholder('appeal')->getValue();

//die('<pre>' . print_r($appeal, 1));
$caseId = $this->placeholder('case')->getValue();
$stayRecords = $this->placeholder('stays')->getValue();

/**
 * First we need to check for an appeal.
 */
if (empty($appeal)){
    echo $this->render('partials/read-only/empty',
        [
            'header' => $this->navigation('navigation')->findOneBy('active', 1)->getLabel(),
            'helpText' => 'There is currently no appeal',
            'url' => $this->url('case_appeal', ['case' => $caseId, 'action' => 'add'], [], false),
            'label' => 'Add appeal',
            'class' => 'action--primary js-modal-ajax'
        ]
    );
} else {
    echo $this->render('partials/read-only/main',
        [
            'header' => $this->navigation('navigation')->findOneBy('active', 1)->getLabel(),
            'actions' => [
                [
                    'label' => 'Edit appeal',
                    'url' => $this->url(
                        'case_appeal',
                        ['case' => $caseId, 'appeal' => $appeal['id'], 'action' => 'edit'],
                        [],
                        false
                    ),
                    'class' => 'action--secondary js-modal-ajax'
                ]
            ],
            'multiItems' => [
                0 => [
                    ['label' => 'Appeal number', 'value' => $appeal['appealNo']],
                    ['label' => 'Appeals deadline', 'date' => $appeal['deadlineDate']],
                    ['label' => 'Date of appeal', 'date' => $appeal['appealDate']],
                    ['label' => 'Reason', 'value' => (isset($appeal['reason']['description']) ?
                        $appeal['reason']['description'] : '')],
                    ['label' => 'Outline ground', 'value' => $appeal['outlineGround'], 'class' => 'full-width']
                ],
                1 => [
                    ['label' => 'Date of appeal hearing', 'date' => $appeal['hearingDate']],
                    ['label' => 'Date of decision', 'date' => $appeal['decisionDate'], 'dateFormat' => 'Y-m-d'],
                    ['label' => 'Papers due at tribunal', 'date' => $appeal['papersDueDate']],
                    ['label' => 'Papers sent date', 'date' => $appeal['papersSentDate'], 'dateFormat' => 'Y-m-d'],
                    ['label' => 'Outcome', 'value' => (isset($appeal['outcome']['description']) ?
                        $appeal['outcome']['description'] : '')],
                    ['label' => 'TM case Id', 'value' => isset($appeal['tmCaseId']) ? $appeal['tmCaseId'] : ''],
                    ['label' => 'Is withdrawn', 'value' => (empty($appeal['withdrawnDate']) ? 'N' : 'Y')],
                    ['label' => 'Withdrawn date', 'date' => $appeal['withdrawnDate']]
                ],
                2 => [
                    ['label' => 'Comments', 'value' => $appeal['comment'], 'class' => 'full-width']
                ]
            ]
        ]
    );

    if (empty($appeal['withdrawnDate'])) {
        if (isset($stayRecords['stay_t_tc']) && !empty($stayRecords['stay_t_tc'])):

            echo $this->partial('sections/cases/pages/stay-details', $stayRecords['stay_t_tc']);

        else:
            echo $this->render('partials/read-only/empty',
                [
                    'header' => 'Traffic Commissioner / Transport Regulator stay',
                    'helpText' => 'There is currently no Traffic Commissioner / Transport Regulator stay',
                    'url' => $this->url(
                        'case_stay',
                        ['case' => $caseId, 'action' => 'add', 'stayType' => 'stay_t_tc'],
                        [],
                        false
                    ),
                    'label' => 'Add stay',
                    'class' => 'action--primary js-modal-ajax'
                ]
            );

        endif;

        if (isset($stayRecords['stay_t_ut']) && !empty($stayRecords['stay_t_ut'])):

            echo $this->partial('sections/cases/pages/stay-details', $stayRecords['stay_t_ut']);

        else:

            echo $this->render('partials/read-only/empty',
                [
                    'header' => 'Upper Tribunal stay',
                    'helpText' => 'There is currently no Upper Tribunal stay',
                    'url' => $this->url(
                        'case_stay',
                        ['case' => $caseId, 'action' => 'add', 'stayType' => 'stay_t_ut'],
                        [],
                        false
                    ),
                    'label' => 'Add stay',
                    'class' => 'action--primary js-modal-ajax'
                ]
            );
        endif;
    }
}
