<?php
$appeal = $this->placeholder('appeal')->getValue();

$caseId = $this->placeholder('caseId')->getValue();
$stayRecords = $this->placeholder('stays')->getValue();

/**
 * First we need to check for an appeal.
 */
if (empty($appeal)){
    echo $this->render('partials/read-only/empty',
        [
            'header' => $this->navigation('navigation')->findOneBy('active', true)->getLabel(),
            'helpText' => 'There is currently no appeal',
            'url' => $this->url('case_appeal', ['case' => $caseId, 'action' => 'add'], [], false),
            'label' => 'Add appeal',
            'class' => 'govuk-button js-modal-ajax'
        ]
    );
} else {
    echo $this->render('partials/read-only/main',
        [
            'header' => $this->navigation('navigation')->findOneBy('active', true)->getLabel(),
            'actions' => [
                [
                    'label' => 'Edit appeal',
                    'url' => $this->url(
                        'case_appeal',
                        ['case' => $caseId, 'appeal' => $appeal['id'], 'action' => 'edit'],
                        [],
                        false
                    ),
                    'class' => 'govuk-button govuk-button--secondary js-modal-ajax'
                ]
            ],
            'multiItems' => [
                0 => [
                    ['label' => 'Appeal number', 'value' => $appeal['appealNo']],
                    ['label' => 'Appeals deadline', 'date' => $appeal['deadlineDate']],
                    ['label' => 'Date of appeal', 'date' => $appeal['appealDate']],
                    ['label' => 'Reason', 'value' => (isset($appeal['reason']['description']) ?
                        $appeal['reason']['description'] : '')],
                    ['label' => 'Outline ground', 'value' => $appeal['outlineGround'], 'class' => 'full-width']
                ],
                1 => [
                    ['label' => 'Date of appeal hearing', 'date' => $appeal['hearingDate']],
                    [
                        'label' => 'Date of decision',
                        'date' => $appeal['decisionDate'],
                        // NB! dateFormat is not an output format, it's an input format,
                        // we need it to convert the date to our standard formats (see list-item.phtml)
                        'dateFormat' => \DB_DATE_FORMAT
                    ],
                    [
                        'label' => 'Papers due at TC/DTC',
                        'date' => $appeal['papersDueTcDate'],
                        'dateFormat' => \DB_DATE_FORMAT
                    ],
                    [
                        'label' => 'Papers sent to TC/DTC',
                        'date' => $appeal['papersSentTcDate'],
                        'dateFormat' => \DB_DATE_FORMAT
                    ],
                    ['label' => 'Papers due at tribunal', 'date' => $appeal['papersDueDate']],
                    [
                        'label' => 'Papers sent to tribunal',
                        'date' => $appeal['papersSentDate'],
                        'dateFormat' => \DB_DATE_FORMAT
                    ],
                    ['label' => 'Outcome', 'value' => (isset($appeal['outcome']['description']) ?
                        $appeal['outcome']['description'] : '')],
                    ['label' => 'TM case Id', 'value' => isset($appeal['tmCaseId']) ? $appeal['tmCaseId'] : ''],
                    ['label' => 'Is withdrawn', 'value' => (empty($appeal['withdrawnDate']) ? 'N' : 'Y')],
                    ['label' => 'Withdrawn date', 'date' => $appeal['withdrawnDate']],
                    ['label' => 'DVSA/DVA notified?',
                        'type' => 'yesno',
                        'value' => $appeal['dvsaNotified']
                    ]
                ],
                2 => [
                    ['label' => 'Comments', 'value' => $appeal['comment'], 'class' => 'full-width']
                ]
            ]
        ]
    );

    if (empty($appeal['withdrawnDate'])) {
        if (isset($stayRecords['stay_t_tc']) && !empty($stayRecords['stay_t_tc'])):
            echo $this->partial('sections/cases/pages/stay-details', $stayRecords['stay_t_tc']);
        else:
            echo $this->render('partials/read-only/empty',
                [
                    'header' => 'Traffic Commissioner / Transport Regulator stay',
                    'helpText' => 'There is currently no Traffic Commissioner / Transport Regulator stay',
                    'url' => $this->url(
                        'case_stay',
                        ['case' => $caseId, 'action' => 'add', 'stayType' => 'stay_t_tc'],
                        [],
                        false
                    ),
                    'label' => 'Add stay',
                    'class' => 'govuk-button js-modal-ajax'
                ]
            );

        endif;

        if (isset($stayRecords['stay_t_ut']) && !empty($stayRecords['stay_t_ut'])):
            echo $this->partial('sections/cases/pages/stay-details', $stayRecords['stay_t_ut']);
        else:
            echo $this->render('partials/read-only/empty',
                [
                    'header' => 'Upper Tribunal stay',
                    'helpText' => 'There is currently no Upper Tribunal stay',
                    'url' => $this->url(
                        'case_stay',
                        ['case' => $caseId, 'action' => 'add', 'stayType' => 'stay_t_ut'],
                        [],
                        false
                    ),
                    'label' => 'Add stay',
                    'class' => 'govuk-button js-modal-ajax'
                ]
            );
        endif;
    }
}
