<?php
$revoke = $this->placeholder('proposeToRevoke')->getValue();

if (empty($revoke)) {
    echo $this->render('partials/read-only/empty',
        [
            'header' => $this->navigation('navigation')->findOneBy('active', true)->getLabel(),
            'helpText' => 'There is no in-office revocation',
            'url' => $this->url('processing_in_office_revocation', ['action' => 'add'], [], true),
            'label' => 'Add in-office revocation'
        ]
    );
} else {
    $revokeReasons = '';

    foreach ($revoke['reasons'] as $reason) {
        $revokeReasons .= $reason['sectionCode'] . ' - ' . $reason['description'] . '<br />';
    }

    echo $this->render('partials/read-only/main',
        [
            'header' => 'In-office revocation',
            'actions' => [
                [
                    'label' => 'Edit',
                    'url' => $this->url(
                        'processing_in_office_revocation',
                        ['revoke' => $revoke['id'], 'action' => 'edit'],
                        [],
                        true
                    )
                ],
            ],
            'multiItems' => [
                0 => [
                    ['label' => 'Legislation', 'value' => $revokeReasons, 'noEscape' => true, 'class' => 'full-width'],
                    ['label' => 'TC/TDC agreed', 'value' => $revoke['presidingTc']['name']],
                    ['label' => 'Agreed date', 'date' => $revoke['ptrAgreedDate']],
                    ['label' => 'Closed date', 'date' => $revoke['closedDate']],
                    ['label' => 'Notes', 'value' => $revoke['comment'], 'class' => 'full-width']
                ]
            ]
        ]
    );

    echo $this->render('sections/cases/pages/in-office-revocation-sla', array('revoke' => $revoke));
}
