<?php
$details = $this->placeholder('details')->getValue();
$details['oorDate'] = isset($details['oorDate']) ? $details['oorDate'] : '';
$details['oooDate'] = isset($details['oooDate']) ? $details['oooDate'] : '';
echo $this->render('partials/read-only/main',
    [
        'items' => [
            ['label' => 'OOO Date', 'date' => $details['oooDate'], 'showNotSet' => true],
            ['label' => 'OOR Date', 'date' => $details['oorDate'], 'showNotSet' => true],
        ]
    ]
);

$oppositionsTable = $this->placeholder('oppositionsTable')->getValue();
echo $oppositionsTable;

$envComplaintsTable = $this->placeholder('envComplaintsTable')->getValue();
echo $envComplaintsTable;
