<?php

$url = null;
if (!$readonly) {
    $url = $this->url(
        $this->route,
        array(
            'action' => 'add',
            'section' => $this->section,
            'id' => $this->id,
            'pi' => $this->pi['id']),
        array(),
        true
    );
}

echo $this->render('partials/read-only/empty',
    [
        'header' => $this->heading,
        'helpText' => 'There is currently no ' . $this->shortHeading,
        'url' => $url,
        'label' => 'Add ' . $this->shortHeading,
        'class' => 'action--primary left-aligned js-modal-ajax'
    ]
);
