
<div class="submission">
<?php
$case = $this->placeholder('case')->getValue();
$submission = $this->placeholder('submission')->getValue();
$selectedSectionsArray = $this->placeholder('selectedSectionsArray')->getValue();
$submissionConfig = $this->placeholder('submissionConfig')->getValue();

$allSections = $this->placeholder('allSections')->getValue();
$readonly = $this->placeholder('readonly')->getValue();

$freetext = '';

$selectedIds = array_column($selectedSectionsArray, 'sectionId');
foreach ($allSections as $sectionId => $sectionDescription) {
    if (array_key_exists($sectionId, $selectedSectionsArray))
    {
        $additionalConfig = isset($submissionConfig[$sectionId]['config']) ? $submissionConfig[$sectionId]['config']
            : [];
        $selectedSectionsArray[$sectionId]['config'] = $additionalConfig;

        $freetext .= $this->submissionSectionDetails(
            $sectionId,
            $selectedSectionsArray[$sectionId],
            $readonly,
            $submission['version']
        );
        // if (isset($submissionConfig[$sectionId]['allow_attachments']) &&
        //     $submissionConfig[$sectionId]['allow_attachments'] && !$readonly) {

        //     $freetext .= $this->partial(
        //         'pages/form',
        //         ['form' => $selectedSectionsArray[$sectionId]['attachmentsForm']]
        //     );
        // }
        if (isset($submissionConfig[$sectionId]['allow_comments']) && $submissionConfig[$sectionId]['allow_comments']) {
            $freetext .= $this->partial('sections/cases/pages/submission/attach-comment',
                [
                    'submissionConfig' => $submissionConfig,
                    'form' => $selectedSectionsArray[$sectionId]['attachmentsForm'],
                    'sectionId' => $sectionId,
                    'section' => $selectedSectionsArray[$sectionId],
                    'caseId' => $case['id'],
                    'submissionId' => $submission['id'],
                    'readonly' => $readonly
                ]
            );
        }
    }
}
$actions = [];
if ($submission['canClose']) {
    $params = ['case' => $submission['case']['id'], 'submission' => $submission['id'], 'action' => 'close'];
    $closeActionUrl = [
        'label' => 'Close submission',
        'url' => $this->url(
            'submission', $params
        )
    ];
    array_push($actions, $closeActionUrl);
}
if ($submission['canReopen']) {
    $params = ['case' => $submission['case']['id'], 'submission' => $submission['id'], 'action' => 'reopen'];
    $closeActionUrl = [
        'label' => 'Reopen submission',
        'url' => $this->url(
            'submission', $params
        )
    ];
    array_push($actions, $closeActionUrl);
}
array_push($actions, [
    'label' => 'Return to list',
    'url' => $this->url(
        'submission', [
            'case' => $case['id'],
            'action' => 'index'
        ]
    )
]);
if (!$readonly) {
    array_push($actions, [
        'label' => 'Edit submission',
        'url' => $this->url(
            'submission', [
                'case' => $case['id'],
                'action' => 'edit',
                'submission' => $submission['id']
            ]
        )
    ]);
}


array_push($actions, [
    'label' => 'Print submission',
    'attributes' => ['target' => '_blank'],
    'class' => 'action--secondary',
    'url' => $this->url(
        'submission', [
            'case' => $case['id'],
            'action' => 'print',
            'submission' => $submission['id']
        ]
    )
]);

//last submission
echo $this->render('partials/read-only/header',
    [
        'header' => $submission['submissionTypeTitle']['description'],
        'actions' => $actions
    ]
);

echo $this->partial(
    'sections/cases/pages/submission/submission-declaration',
    [
        'submission' => $submission,
    ]
);


?>

<?php echo $freetext; ?>


<?php if (count($submission['submissionActions']) > 0): ?>
<h4 class="title">Submission actions</h4>

<ul class="submission-actions" style="width: 100%">
    <?php foreach ($submission['submissionActions'] as $sa): ?>
    <li class="submission-item">

        <h4><?php echo $sa['isDecision'] == 'Y' ? 'Decision reason' : 'Recommendation'; ?>:
            <?php
            echo implode(', ', array_column($sa['actionTypes'], 'description'));
            ?></h4>

        <?php if (!$readonly): ?>
            <?php $route = 'submission_action_' . ($sa['isDecision'] == 'Y' ? 'decision' : 'recommendation'); ?>
            <a class="submission-item__edit js-modal-ajax" href="<?php echo $this->url($route, ['action' => 'edit', 'id' => $sa['id']], [], true); ?>">Edit</a>
        <?php endif; ?>

        <p><?php echo nl2br($sa['comment']); ?></p>
        <p><strong>Legislation:</strong><br /><?php echo implode('<br />', array_map(function($item){return $item['sectionCode'] . ' - '. $item['description'];}, $sa['reasons'])); ?></p>
        <p><b>Created:</b><br /><?php echo $this->date(strtotime($sa['createdOn']), 'H:i d/m/Y'); ?></p>
    </li><!-- submission-item -->
  <?php endforeach; ?>
</ul>

<?php endif; ?>

<div>&nbsp;</div>

<?php if (!$readonly): ?>
<div class="actions-container" data-group="form-actions">
    <a href="<?php echo $this->url('submission_action_recommendation', ['action' => 'add'], [], true); ?>"
       class="action--primary large js-modal-ajax">Add recommendation</a>
    <a href="<?php echo $this->url('submission_action_decision', ['action' => 'add'], [], true); ?>"
       class="action--primary large js-modal-ajax">Add decision reason</a>
    <a href="<?php echo $this->url('submission_process', ['action' => 'information-complete'], [],
        true); ?>" class="action--secondary large js-modal-ajax">Set info complete</a>
    <?php
    if (!empty($submission['informationCompleteDate'])) {
    ?>
    <a href="<?php echo $this->url('submission_process', ['action' => 'assign'], [],
        true); ?>" class="action--secondary large js-modal-ajax">Assign submission</a>
    <?php
    }
    ?>

</div>
    <?php
    if (!empty($submission['informationCompleteDate'])) {
    ?>
<div>
    <p><strong>Information complete : <?php echo date('d/m/Y', strtotime($submission['informationCompleteDate']));?>
            </strong></p>
</div>
    <?php
    }
    ?>

<?php endif; ?>
</div>
