<div id="finance-authorisation">
    <h1><?php echo $this->translate('Operating centres');?></h1>


<!-- end .page-header -->


<!-- Vertical navigation -->
<div class="one-quarter">

	<h4>Content</h4>
	<ol class="vertical-navigation" role="navigation">
			<li class="vertical-navigation__item">
			<a href="#operating-centres">Operating centres</a>
		</li>
			<li class="vertical-navigation__item">
			<a href="#authorised-vehicles">Authorised vehicles</a>
		</li>
			<li class="vertical-navigation__item">
			<a href="#financial-evidence">Financial evidence</a>
		</li>
		</ol><!-- end .vertical-navigation -->

</div><!-- end .one-quarter -->


<div class="three-quarters">
	<form>
       <?php
            echo $operatingCentres;
       ?>
	</form>

	<!-- Authorised vehicles -->
	<form>
		<fieldset>
			<legend id="authorised-vehicles">Authorised vehicles</legend>
	        <p class="hint">Enter the total amount of vehicles &amp; trailers that you want authorised on the licence your are applying for</p>
			<div class="field">
	            <label for="no-of-vehicles">Total no. of vehicles</label>
	            <input class="short" id="no-of-vehicles" name="no-of-vehicles" placeholder="" type="text" value="">
	        </div>
	        <div class="field">
	            <label for="no-of-trailers">Total no. of trailers</label>
	            <input class="short" id="no-of-trailers" name="no-of-trailers" placeholder="" type="text" value="">
	        </div>
		</fieldset>
		<div class="actions-container">
			<input class="action--primary large" type="submit" value="Calculate">
		</div><!-- end .actions -->
	</form>

	<!-- Financial evidence -->
	<form>
		<div class="table__header">
			<h3 id="financial-evidence">Financial evidence</h3>
			<div class="actions-container">
				<input class="action--primary" type="submit" value="Upload">
				<input class="action--warning" type="submit" value="Delete">
			</div><!-- end .actions-container -->
		</div><!-- end .table__header -->
		<div class="table__wrapper">
			<table>
				<thead>
					<tr>
						<th></th>
						<th>File name</th>
						<th>Evidence type</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><input name="row" type="radio"></td>
						<td>Amber_taxis_accounts_2012-2013.xls</td>
						<td>Accounts</td>
					</tr>
				</tbody>
			</table>
		</div><!-- end .table_wrapper -->
		<p class="hint">Please upload copies of your accounts or bank statements to prove you have sufficient funds</p>
	</form>

	<!-- Totals -->
	<h3 id="totals">Totals</h3>
	<div class="table__wrapper">
		<table class="totals">
			<tfoot>
				<tr>
					<th>Total finance available</th>
					<td style="width: 12%;">£22,083</td>
				</tr>
				<tr>
					<th>Required finance</th>
					<td style="width: 12%;"><strong>£10,000</strong></td>
				</tr>
			</tfoot>
		</table>
	</div><!-- end .table-wrapper -->

</div>