<div id="finance-authorisation">
    <h1><?php echo $this->translate('Operating centres'); ?></h1>
    <!-- Vertical navigation -->
    <div class="one-quarter">
        <h4>Content</h4>
        <ol class="vertical-navigation" role="navigation">
            <li class="vertical-navigation__item">
                <a href="<?php
                echo $this->url(
                    'selfserve/finance/operating_centre_action',
                    array('applicationId' => $applicationId)
                );
                ?>">Operating centres &amp; authorisation</a>
            </li>
            <li class="vertical-navigation__item">
                <a href="#financial-evidence">Financial evidence</a>
            </li>
        </ol><!-- end .vertical-navigation -->
    </div><!-- end .one-quarter -->


    <div class="three-quarters">
        <?php echo $this->main; ?>
    </div>
</div>