<div id="finance-authorisation">
    <h1><?php echo $this->translate('Operating centres');?></h1>


<!-- end .page-header -->


<!-- Vertical navigation -->
<div class="one-quarter">
    
	<h4>Content</h4>
	<ol class="vertical-navigation" role="navigation">
			<li class="vertical-navigation__item">
			<a href="#operating-centres">Operating centres</a>
		</li>
			<li class="vertical-navigation__item">
			<a href="#authorised-vehicles">Authorised vehicles</a>
		</li>
			<li class="vertical-navigation__item">
			<a href="#financial-evidence">Financial evidence</a>
		</li>
		</ol><!-- end .vertical-navigation -->

</div><!-- end .one-quarter -->


<div class="three-quarters">
	<form>

		<!-- Operating centers -->
		<div class="table__header">
			<h3>Operating centres</h3>
			<div class="actions-container">
				<a href="<?php echo $this->url('selfserve/finance/operating_centre_action', ['action' => 'add'], true); ?>" class="action--primary">Add</a>
				<input class="action--secondary" type="submit" value="Edit">
				<input class="action--warning" type="submit" value="Delete">
			</div><!-- end .actions-container -->
		</div><!-- end .table__header -->
		<div class="table__wrapper">
			<table>
				<thead>
					<tr>
						<th></th>
						<th>Address</th>
						<th>Vehicles</th>
						<th>Trailers</th>
						<th>Permission</th>
						<th>Advertised</th>
						<th>Proof</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><input name="row" type="radio"></td>
						<td><a href="">24 Dulwich Road, Southwell</a></td>
						<td>3</td>
						<td>5</td>
						<td>Yes</td>
						<td>Yes</td>
						<td>No</td>
					</tr>
					<tr>
						<td><input name="row" type="radio"></td>
						<td><a href="">177 Beeston Industrial Park</a></td>
						<td>26</td>
						<td>2</td>
						<td>Yes</td>
						<td>Yes</td>
						<td>Yes</td>
					</tr>
				</tbody>
			</table>
		</div><!-- end .table-wrapper -->
	</form>

	<!-- Financial evidence -->
	<form>
		<div class="table__header">
			<h3 id="financial-evidence">Financial evidence</h3>
			<div class="actions-container">
				<input class="action--primary" type="submit" value="Upload">
				<input class="action--warning" type="submit" value="Delete">
			</div><!-- end .actions-container -->
		</div><!-- end .table__header -->
		<div class="table__wrapper">
			<table>
				<thead>
					<tr>
						<th></th>
						<th>File name</th>
						<th>Evidence type</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><input name="row" type="radio"></td>
						<td>Amber_taxis_accounts_2012-2013.xls</td>
						<td>Accounts</td>
					</tr>
				</tbody>
			</table>
		</div><!-- end .table_wrapper -->
		<p class="hint">Please upload copies of your accounts or bank statements to prove you have sufficient funds</p>		
	</form>

	<!-- Totals -->
	<h3 id="totals">Totals</h3>
	<div class="table__wrapper">
		<table class="totals">
			<tfoot>
				<tr>
					<th>Total finance available</th>
					<td style="width: 12%;">£22,083</td>
				</tr>
				<tr>
					<th>Required finance</th>
					<td style="width: 12%;"><strong>£10,000</strong></td>
				</tr>
			</tfoot>
		</table>
	</div><!-- end .table-wrapper -->

</div>