<div class="read-only">
    <div class="read-only__header">
        <h4 id="licence-details" class="read-only__title">
            <?php echo $this->translate(
                    'search-result-section-header-licence-details'
                ) . ' (' . $this->result['licNo'] . ')';
            ?></h4>
    </div><!-- read-only__header -->
    <?php
    echo $this->partial('partials/entity-view/partner-licence-details');
    ?>
</div>

<div class="read-only">
    <div class="read-only__header">
        <h4 id="contact-details" class="read-only__title"><?php echo $this->translate
            ('search-result-section-header-contact-details');?></h4>
    </div><!-- read-only__header -->
    <?php
    echo $this->partial('partials/entity-view/contact-details');
    ?>
</div>

<?php
if (!empty($operatingCentresTable)) {
    ?>
    <div class="read-only">
        <div class="read-only__header">
            <h4 id="operating-centres" class="read-only__title"><?php echo $this->translate
                ('search-result-section-header-operating-centres'); ?></h4>
        </div>
        <!-- read-only__header -->
        <?php
        echo $operatingCentresTable;
        ?>
    </div>
    <?php
}
?>

<?php
if (!empty($transportManagerTable)) {
    ?>
    <div class="read-only">
        <div class="read-only__header">
            <h4 id="transport-managers" class="read-only__title"><?php echo $this->translate
                ('search-result-section-header-transport-managers'); ?></h4>
        </div>
        <!-- read-only__header -->
        <?php
        echo $transportManagerTable;
        ?>
    </div>
    <?php
}
?>

<?php
if (!empty($relatedOperatorLicencesTable)) {
    ?>
    <div class="read-only">
        <div class="read-only__header">
            <h4 id="related-operator-licences" class="read-only__title"><?php echo $this->translate
                ('search-result-section-header-related-operator-licences'); ?></h4>
        </div>
        <!-- read-only__header -->
        <?php
        echo $relatedOperatorLicencesTable;
        ?>
    </div>
    <?php
}
?>

<div class="actions-container">
    <a href="#to-do"><?php echo $this->translate('search-result-nav-back-to-top');?></a>
    <a href="#to-do"><?php echo $this->translate('search-result-nav-back-to-operator-search');?></a>
</div>
