<div class="read-only">
    <div class="read-only__header">
        <h4 id="licence-details" class="read-only__title">
            <?php echo $this->translate(
                    'entity-details-section-header-licence-details'
                ) . ' (' . $this->escapeHtml($this->result['licNo']) . ')';
            ?></h4>
    </div><!-- read-only__header -->
    <?php
    echo $this->partial('partials/entity-view/partner-licence-details');
    ?>
</div>

<div class="read-only">
    <div class="read-only__header">
        <h4 id="contact-details" class="read-only__title"><?php echo $this->translate
            ('entity-details-section-header-contact-details');?></h4>
    </div><!-- read-only__header -->
    <?php
    echo $this->partial('partials/entity-view/partner-contact-details');
    ?>
</div>

<div class="read-only">
    <div class="read-only__header">
        <h4 id="contact" class="read-only__title"><?php echo $this->translate
            ('entity-view-section-header-registered-company-details');?></h4>
    </div><!-- read-only__header -->
    <?php
    echo $this->partial('partials/entity-view/partner-registered-company-details');
    ?>
</div>

<?php
if (!empty($operatingCentresTable)) {
    ?>
    <div class="read-only">
        <div class="read-only__header">
            <h4 id="operating-centres" class="read-only__title"><?php echo $this->translate
                ('entity-details-section-header-operating-centres'); ?></h4>
        </div>
        <!-- read-only__header -->
        <?php
        echo $operatingCentresTable;
        ?>
    </div>
    <?php
}
?>

<?php
if (!empty($oppositionsTable)) {
    ?>
    <div class="read-only">
        <div class="read-only__header">
            <h4 id="operating-centres" class="read-only__title"><?php echo $this->translate
                ('search-result-label-oppositions'); ?></h4>
        </div>
        <!-- read-only__header -->
        <?php
        echo $oppositionsTable;
        ?>
    </div>
    <?php
}
?>

<?php
if (!empty($transportManagerTable)) {
    ?>
    <div class="read-only">
        <div class="read-only__header">
            <h4 id="transport-managers" class="read-only__title"><?php echo $this->translate
                ('entity-details-section-header-transport-managers'); ?></h4>
        </div>
        <!-- read-only__header -->
        <?php
        echo $transportManagerTable;
        ?>
    </div>
    <?php
}
?>

<?php
if (!empty($relatedOperatorLicencesTable)) {
    ?>
    <div class="read-only">
        <div class="read-only__header">
            <h4 id="related-operator-licences" class="read-only__title"><?php echo $this->translate
                ('entity-details-section-header-related-operator-licences'); ?></h4>
        </div>
        <!-- read-only__header -->
        <?php
        echo $relatedOperatorLicencesTable;
        ?>
    </div>
    <?php
}
?>

<?php
if (!empty($vehiclesTable)) {
    ?>
    <div class="read-only">
        <div class="read-only__header">
            <h4 id="vehicles" class="read-only__title"><?php echo $this->translate
                ('entity-details-section-header-vehicles'); ?></h4>
        </div>
        <!-- read-only__header -->
        <?php
        echo $vehiclesTable;
        ?>
    </div>
    <?php
}
?>

<?php
if (!empty($currentApplicationsTable)) {
    ?>
    <div class="read-only">
        <div class="read-only__header">
            <h4 id="current-applications" class="read-only__title"><?php echo $this->translate
                ('entity-details-section-header-current-applications'); ?></h4>
        </div>
        <!-- read-only__header -->
        <?php
        echo $currentApplicationsTable;
        ?>
    </div>
    <?php
}
?>

<?php
if (!empty($conditionsUndertakingsTable)) {
    ?>
    <div class="read-only">
        <div class="read-only__header">
            <h4 id="conditions-undertakings" class="read-only__title"><?php echo $this->translate
                ('entity-details-section-header-conditions-undertakings'); ?></h4>
        </div>
        <!-- read-only__header -->
        <?php
        echo $conditionsUndertakingsTable;
        ?>
    </div>
    <?php
}
?>
