<?php
echo $this->render(
    '/partials/page-header.phtml',
    array(
        'pageTitle' => $this->translate('ebsr-upload-title')
    )
);
?>
<div class="two-thirds">
    <div class="article">
        <p><?php echo $this->translate('ebsr-upload-subtitle');?></p>
        <h3>Please check the following</h3>
        <ul>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Consectetur adipiscing elit tempor incididun</li>
            <li>Aliquip ex ea commodo consequa</li>
            <li>Ut enim ad minim veniam</li>
        </ul>
    </div>
    <?php echo $this->flashMessengerAll(); ?>

    <?php
    echo $this->formErrors($this->form, true);
    $this->form->prepare();
    echo $this->form()->render($this->form);
    ?>
</div>

<div class="one-third sidebar">
    <?php echo $this->translate('markup-support-contact-address');?>
</div><!-- .one-quarter -->
