<?php
echo $this->render(
    '/partials/page-header.phtml',
    array(
        'pageTitle' => $this->translate('ebsr-upload-title')
    )
);
?>
<div class="two-thirds">
    <div class="article">
        <p><?php echo $this->translate('ebsr-upload-subtitle');?></p>
        <ul>
            <li>your EBSR is in .ZIP format</li>
            <li>you’ve included supporting information like maps, timetables and letters of support</li>
        </ul>
        <p>Once you’ve submitted your application you must pay all your fees before we can consider it.</p>
    </div>
    <?php echo $this->flashMessengerAll(); ?>

    <?php
    echo $this->formErrors($this->form, true);
    $this->form->prepare();
    echo $this->form()->render($this->form);
    ?>
</div>

<div class="one-third sidebar">
    <?php echo $this->translate('markup-support-contact-address');?>
</div><!-- .one-quarter -->
