<?php
  echo $this->render(
    '/partials/page-header.phtml',
    array(
      'pageTitle' => $this->translate('ebsr-upload-title')
    )
  );
?>

<div class="row">

  <div class="two-thirds">
    <div class="article">
      <p><?php echo $this->translate('ebsr-upload-subtitle');?></p>
      <ul>
        <li><?php echo $this->translate('ebsr-ensure-format');?></li>
        <li><?php echo $this->translate('ebsr-supporting-info');?></li>
      </ul>
      <p><?php echo $this->translate('ebsr-what-next');?></p>
    </div>
    <?php echo $this->flashMessengerAll(); ?>
    <?php
      echo $this->formErrors($this->form, true);
      $this->form->prepare();
      echo $this->form()->render($this->form);
    ?>
  </div>
  
  <div class="one-third">
    <div class="sidebar" role="complementary">
      <?php echo $this->translate('markup-support-contact-address');?>
    </div>
  </div>

</div>