<p>
  Mae'r trwyddedau canlynol sydd â ffioedd yn ddyledus rhwng <?php echo $this->escapeHtml($this->startDate); ?>
  a <?php echo $this->escapeHtml($this->endDate) ?> wedi'u gosod i CNS:
</p>

<table>
  <?php foreach ($this->licences as $licence): ?>
    <tr>
      <td width="125"><?php echo $this->escapeHtml($licence['licNo']); ?></td>
      <td><?php echo $this->escapeHtml($licence['taName']); ?></td>
    </tr>
  <?php endforeach; ?>
</table>
