<p>Annwyl weithredwr,</p>
<p>
    Mae dogfennaeth bwysig ynghylch eich Trwydded Gweithredwr <?php echo $this->escapeHtml($this->licNo); ?> wedi'i
    hanfon drwy'r post danfon cofnodedig i'ch cyfeiriad gohebiaeth. Mae hyn yn dilyn tynnu eich Rheolwr Trafnidiaeth olaf;
    sicrhewch eich bod yn ymateb cyn y dyddiad cau a nodwyd.
</p>
<p>
    SYLWER. Bydd methu ag ymateb i'r llythyr hwn yn arwain at ddirymu eich trwydded. Byddai dirymu'r
    drwydded yn gwneud gweithredu cerbydau y mae angen trwydded gweithredwr ar eu cyfer yn
    anghyfreithlon.
</p>
<?php if (!$this->registeredToSelfserve) : ?>
    <p>Gallwch ddiweddaru eich trwydded gweithredwr ar-lein, er enghraifft gallwch:
    <ul>
        <li>ychwanegu neu dynnu rheolwr trafnidiaeth</li>
        <li>ychwanegu mwy o gerbydau at eich trwydded</li>
        <li>cynyddu'r terfyn cerbydau ar eich trwydded</li>
        <li>newid math eich trwydded</li>
    </ul>
    I gofrestru ar gyfer y gwasanaeth ar-lein, defnyddiwch y ddolen ganlynol:
    <p>
        <a href="https://www.vehicle-operator-licensing.service.gov.uk/auth/login/">https://www.vehicle-operator-licensing.service.gov.uk/auth/login/</a>
    <p>
        Mae'r gwasanaeth ar-lein yn syml ac yn hawdd i'w ddefnyddio. Mae'n lleihau'r amser sydd ei angen i fwrw ymlaen â'r
        rhan fwyaf o newidiadau i drwyddedau. Mae newidiadau i gerbydau yn dod i rym ar unwaith.
    </p>
<?php endif; ?>
