<p>Helô,</p>

<p>Fe'ch ychwanegwyd at y gwasanaeth Trwyddedu Gweithredwyr Cerbydau ar gyfer <?php echo $this->escapeHtml($this->orgName); ?>.</p>

<p>Eich enw defnyddiwr yw: <?php echo $this->escapeHtml($this->loginId); ?></p>

<p>Byddwch yn derbyn ail e-bost gyda chyfrinair dros dro yn y ddwy awr nesaf. Os na fydd yn cyrraedd e-bostiwch notifications@vehicle-operator-licensing.service.gov.uk</p>

<p>
    <a href="<?php echo $this->escapeHtml($this->url); ?>">Mewngofnodi</a>
</p>
