<?php

namespace Cli\Controller;

use Zend\Mvc\Controller\AbstractConsoleController;
use Zend\View\Model\ConsoleModel;

/**
 * DevUtilsController
 *
 * @author Mat Evans <mat.evans@valtech.co.uk>
 */
class DevUtilsController extends AbstractConsoleController
{
    /**
     * Source file is a list of translation keys (probably generated by the missing translations logger)
     * This action will iterate through the file and generate a CSV file that can be used by translators
     */
    public function createTranslationCsvAction()
    {
        $source = $this->getSource();
        if (!file_exists($source)) {
            throw new \RuntimeException("Source '{$source}' does not exist");
        }

        $destination = $this->getDestination();
        $translator = $this->getServiceLocator()->get('Translator');

        $destinationFile = fopen($destination, 'w');
        fputcsv($destinationFile, ['Translation key', 'English', 'Welsh']);

        $keysWritten = [];

        $sourceFile = file($source);
        foreach ($sourceFile as $key) {
            $trimmedKey = trim($key);
            if (isset($keysWritten[$key])) {
                continue;
            }
            fputcsv($destinationFile, [$trimmedKey, $translator->translate($trimmedKey)]);
            $keysWritten[$key] = true;
        }

        fclose($destinationFile);
    }

    /**
     * Get the source parameter
     *
     * @return string
     */
    private function getSource()
    {
        return $this->getRequest()->getParam('source');
    }

    /**
     * Get the destination parameter
     *
     * @return string
     */
    private function getDestination()
    {
        return $this->getRequest()->getParam('destination');
    }
}
