<?php
    echo $this->render(
        '/view-new/partials/page-header.phtml',
        array(
            'pageTitle' => $this->translate($this->params['pageTitle']),
            'pageSubTitle'=> $this->translate($this->params['pageSubTitle'])
        )
    );
?>
<div class="full-width">
<?php
    foreach($this->params['submission']['views'] as $key => $section) { 
        echo $this->partial('submission/partials/section.phtml', array(
        'config' => $this->params['submissionConfig'],
        'routeParams' => $this->params['routeParams'],
        'heading' => $key,
        'data' => $section)); 
    } 
?>
</div>
<?php if (isset($this->params['submission']['submissionActions'])) : ?>
    <?php 
        echo $this->partial('submission/partials/decRecDisplay.phtml', array(
        'heading' => $key,
        'data' => $this->params['submission']['submissionActions'])); 
?>
<?php endif; ?>
<div  class="two-thirds">
    <form method="POST" action="<?php echo $this->params['formAction']; ?>">
        <div class="actions-container">
            <input id="recommend" class="action--primary" name="recommend" type="submit" value="Add recommendation">
            <input id="decision" class="action--primary" name="decision" type="submit" value="Add decision">
        </div>
    </form>
</div>