<div class="page-header">
  <div class="page-header__wrapper">
    <div class="user-header">
        <?php
        echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)
            ->setPartial(array('layout/partials/breadcrumbs.phtml', 'Olcs'));
        ?>

      <ul class="user-menu">
        <li class="user-menu__item">Sam Quayle:</li>
        <li class="user-menu__item"><a href="/styleguides/selfserve/">My settings</a></li>
        <li class="user-menu__item"><a href="">Sign out</a></li>
      </ul>
    </div><!-- user-header -->

    <h1><?php echo $licNo; ?></h1>
    <h3 class="page-header__subtitle"><?php echo $companyName; ?>  <span class="status orange"><?php echo $description; ?></span></h3>

  </div><!-- end .page-header__wrapper-->
</div>
