<?php
    echo $this->render(
        '/partials/page-header.phtml',
        array(
            'pageTitle' => 'Licence: ' . $this->licence['licenceNumber'],
            'pageSubTitle'=> $this->licence['goodsOrPsv'] . ', ' . $this->licence['licenceType']
            . ', ' . $this->licence['licenceStatus']
        )
    );
?>
<div class="three-quarters">
    <?php
        echo $this->navigation('navigation')
                  ->menu($this->navigation()->findOneBy('id', 'licence'))
                  ->setUlClass('horizontal-navigation')
                  ->setAddClassToListItem(true)
                  ->setPartial('licence/partials/tabs');
    ?>

    <div>&nbsp;</div>
    <h3>Licence Summary</h3>


    <div class="notes-container">
    	<div class="note">
    		<div class="note__text">
    			<p><b>Note:</b> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    		</div>
    		<div class="note__meta">
    			<p><b>By:</b> Kerry Lane</p>
    			<p><b>Created:</b> 13:32 03/03/14</p>
    		</div>
    	</div><!-- end .note -->
    </div>

    <h3>Compliance Summary</h3>


    <div class="notes-container">
    	<div class="note">
    		<div class="note__text">
    			<p><b>Note:</b> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    		</div>
    		<div class="note__meta">
    			<p><b>By:</b> Kerry Lane</p>
    			<p><b>Created:</b> 13:32 03/03/14</p>
    		</div>
    	</div><!-- end .note -->
    	</div>

</div><!-- end .three-quarters -->

<div class="one-quarter">

</div><!-- end .three-quarters -->