<div class="four-fifths--left">
  <?php
  echo $this->navigation('navigation')
  ->menu($this->navigation()->findOneBy('id', 'licence'))
  ->setPartial('layout/partials/tabs');
  ?>
  <div class="content">
      <?php echo $this->content; ?>
  </div>
</div>
<div class="one-fifth--right">
  <div class="record-actions">
    <?php echo $this->actions; ?>
  </div>

  <?php if (is_array($markers)): ?>
    <?php foreach($markers as $marker): ?>
      <?php echo $this->markers($marker, 'appeal') ?>
      <?php echo $this->markers($marker, 'stay') ?>
    <?php endforeach; ?>
  <?php endif; ?>
</div>
