<div class="col-md-12 nopad tPagBar <?php echo isset($class) ? $class : ''; ?> tBorder2t">
    <div class="col-md-6 tBgCol" id="pagRange">
        <span>
            <?php
            $pagingHeader = $this->translate('lookup-search-results-total-pages');
            if ($paginator->realCurrentPage == 1) {
                $start = 1;
                $end = $paginator->getCurrentItemCount();
            } else {
                $start = ($paginator->realCurrentPage - 1) * 10 +1;
                $end = $start + $paginator->getCurrentItemCount() -1;
            }
            echo sprintf($pagingHeader, $start, $end, $paginator->totalCount);
            ?>
        </span>
        <ul class="list-inline" style="display: inline;">
       <?php
                        $routeParams = $paginator->routeParams;
                        $routeParams['page'] = 1;
                        if ($paginator->totalCount > 10) :
        ?>
            <li>
                <?php echo $this->translate('lookup-search-results-prefix'); ?>
                <?php if ($paginator->getItemCountPerPage() != 10) : 
                                    $routeParams['s'] = 10;
                ?>
                    <a href="<?php echo $this->url($paginator->route, $routeParams, array('query' => $paginator->queryString)) ?>">
                        <?php echo $this->translate('lookup-search-results-first-ten'); ?>
                    </a>
                <?php else: ?>
                    <?php echo $this->translate('lookup-search-results-first-ten'); ?>
                <?php endif; ?>
            </li>
            <li>
                <?php if ($paginator->getItemCountPerPage() != 25) :
                                    $routeParams['s'] = 25;
                ?>
                    <a  href="<?php echo $this->url($paginator->route, $routeParams, array('query' => $paginator->queryString)) ?>">
                        <?php echo $this->translate('lookup-search-results-first-twenty-five'); ?>
                    </a>
                <?php else: ?>
                    <?php echo $this->translate('lookup-search-results-first-twenty-five'); ?>
                <?php endif; ?>
            </li>
            <li>
                <?php if ($paginator->getItemCountPerPage() != 50) :
                                    $routeParams['s'] = 50;
                ?>
                    <a href="<?php echo $this->url($paginator->route, $routeParams, array('query' => $paginator->queryString)) ?>">
                        <?php echo $this->translate('lookup-search-results-first-fifty'); ?>
                    </a>
                <?php else: ?>
                    <?php echo $this->translate('lookup-search-results-first-fifty'); ?>
                <?php endif; ?>
            </li>
            <li>
                <?php if ($paginator->getItemCountPerPage() != 100) :
                                    $routeParams['s'] = 100;
                ?>
                    <a href="<?php echo $this->url($paginator->route, $routeParams, array('query' => $paginator->queryString)) ?>">
                        <?php echo $this->translate('lookup-search-results-first-hundred'); ?>
                    </a>
                <?php else: ?>
                    <?php echo $this->translate('lookup-search-results-first-hundred'); ?>
                    <?php endif; ?>
            </li>
                <?php endif; ?>
        </ul>
    </div>
    <div class="col-md-6 tBgCol text-right" id="pagNumbers">
        <?php
        $paginator->setCurrentPageNumber($paginator->realCurrentPage);
        if (isset($paginator)) {
            echo $this->paginationControl(
            $paginator,
            'sliding',
            array('olcs/common/generic-list/paginator.phtml', 'Olcs'),
            array('route' => $paginator->route,'routeParams' => $paginator->routeParams, 'queryString' => $paginator->queryString));
        }
    ?>
    </div>
</div>