<?php if ($this->pageCount): 
                $params = $this->routeParams;
                $pageSwitch = $this->pageCount > 5 ? 3 : 5;
?>
        <ul class="inlinePaginator">
            <?php if ($this->pageCount > 1) : ?>
            <!-- Previous page link -->
            <?php if (isset($this->previous)):
                            $params['page'] = $this->previous;
            ?>
                <li>
                    <a href="<?php echo $this->url($this->route, $params, array('query' => $this->queryString)); ?>">Previous</a>
                </li>
            <?php endif; ?>
            <?php if ($this->current > $pageSwitch):
                            $params['page'] = 1;
            ?>
                <li>
                    <a href="<?php echo $this->url($this->route, $params, array('query' => $this->queryString)); ?>">1</a>
                </li>
                <li>...</li>
            <?php endif; ?>    
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current):
                                $params['page'] = $page;
                    ?>
                    <li>
                        <a href="<?php echo $this->url($this->route, $params, array('query' => $this->queryString));?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li><?php echo $page; ?></li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php 
                if (isset($this->next)): 
                    $params['page'] = $this->pageCount;
                    $range = $this->pagesInRange;
                    $lastPageInRange = end($range);
                    if ($this->pageCount > 5 && $this->last != $lastPageInRange):  
            ?>
                    <li>...</li>
                    <li>
                        <a href="<?php echo $this->url($this->route, $params, array('query' => $this->queryString)); ?>"><?php echo $this->last; ?></a>
                    </li>
            <?php endif; ?>
                <li>
                    <a href="<?php 
                                        $params['page'] = $this->next;
                                        echo $this->url($this->route, $params, array('query' => $this->queryString)); 
                                    ?>">Next</a>
                </li>
                
            <?php endif; ?>
        <?php else: ?>
                <ul class="list-blank">
                    <li></li>
                </ul>
        <?php endif; ?>
        </ul>
<?php else: ?>
<ul class="inlinePaginator">
    <li class="noSep"></li>
</ul>
<?php endif; ?>
