<?php
$addressLines = array_filter(array(
    empty($address['line1']) ? '' : $address['line1'],
    empty($address['line2']) ? '' : $address['line2'],
    empty($address['line3']) ? '' : $address['line3'],
    empty($address['line4']) ? '' : $address['line4'],
    empty($address['town']) ? '' : $address['town'],
    empty($address['postcode']) ? '' : $address['postcode'],
));

if (empty($noFold) && !empty($addressLines)) {
    $folded = true;

    ?><span class="noWrap"><img src="/img/p.png" class="sprt arrRt" /> <?php

    echo $this->escapeHtml(array_shift($addressLines));

    ?></span><div class="fullAddr hide"><?php
} else {
    $folded = false;
}

if (!empty($addressLines)) {
    $escaper = $this->plugin('escapeHtml')->getEscaper();

    echo '<span class="noWrap">' . implode('</span><br><span class="noWrap">', array_map(array($escaper, 'escapeHtml'), $addressLines)) . '</span>';
}

if ($folded) {
    ?></div><?php
}
