<div class="two-thirds">
    <a href="<?php echo $this->url('dashboard'); ?>">Home</a>
    <div class="page-header">
      <div class="page-header__wrapper">
        <h3 class="page-header__subtitle">
            <?php echo $this->translate('application.overview.application-no'); ?> <?php echo $applicationId; ?>
        </h3>
        <h1><?php echo $this->translate('application.overview.title'); ?></h1>
      </div>
    </div>
</div>
<div class="one-third">
  <a href="#">Print application</a>
  <a href="#">Delete application</a>
  <p>
    Created <br />
    <strong><?php echo $createdOn; ?></strong>
  </p>
  <p>
    Progress
    <strong>X of Y sections complete</strong>
  </p>
  <p>
    Status
    <strong><?php echo $this->translate($status); ?></strong>
  </p>
</div>