<div class="three-fifths">
    <a href="<?php echo $this->url('dashboard'); ?>">Home</a>
    <div class="page-header">
      <div class="page-header__wrapper">
        <h3 class="page-header__subtitle">
            <?php echo $this->translate('application.overview.application-no'); ?> <?php echo $applicationId; ?>
        </h3>
        <h1><?php echo $this->translate('application.overview.title'); ?></h1>
      </div>
    </div>
</div>
<div class="two-fifths">
a
</div>