<h4 class="title"><?php echo $this->translate('licence-details-nav'); ?></h4>
<?php
/**
 * @todo Needs changing for Zend Navigation
 */
if (isset($this->sections)): ?>
    <ol class="vertical-navigation" role="menu">
        <?php foreach ($sections as $reference => $details) : ?>
            <?php $current = ($details['route'] === $currentRoute); ?>
            <li class="vertical-navigation__item <?php echo $current ? 'current' : ''; ?>">
                <?php if (!$current) : ?>
                <a href="<?php echo $this->url($details['route'], ['licence' => $lvaId]); ?>">
                    <?php endif; ?>
                    <?php echo $this->translate('section.name.' . $reference); ?>
                    <?php if (!$current) : ?>
                </a>
            <?php endif; ?>
                <?php if ($current && isset($filterForm)): ?>
                    <div class="filters">
                        <?php echo $this->form($filterForm); ?>
                    </div>
                <?php endif;?>
            </li>
        <?php endforeach; ?>
    </ol><!-- end .progress -->
<?php endif; ?>