<?php
echo $this->render(
    '/partials/page-header.phtml',
    array(
        'pageTitle' => $this->translate('Bus registration details'),
        'pageSubTitle'=> $this->registrationDetails['regNo'],
    )
);
?>

<div class="three-quarters">

<?php

$busServiceTypes = [];
$localAuthoritiesList = [];
$trafficAreasList = [];
if (!empty($this->registrationDetails['busServiceTypes'])) {
    for($i = 0; $i<count($this->registrationDetails['busServiceTypes']);$i++) {
        $label = ($i == 0) ? 'Service type' : '';
        $busServiceTypes[] = [
            'label' => $label,
            'value' => $this->registrationDetails['busServiceTypes'][$i]['description']
        ];
    }
} else {
    $busServiceTypes[] = [
        'label' => 'Service type',
        'value' => ''
    ];
}

if (!empty($this->registrationDetails['localAuthoritys'])) {
    for($i = 0; $i<count($this->registrationDetails['localAuthoritys']);$i++) {
        $label = ($i == 0) ? 'Local authorities covered by route' : '';
        $localAuthoritiesList[] = [
            'label' => $label,
            'value' => $this->registrationDetails['localAuthoritys'][$i]['description']
        ];
    }
} else {
    $localAuthoritiesList[] = [
        'label' => 'Local authorities covered by route',
        'value' => ''
    ];
}

if (!empty($this->registrationDetails['trafficAreas'])) {
    for($i = 0; $i<count($this->registrationDetails['trafficAreas']);$i++) {
        $label = ($i == 0) ? 'TAOs covered by route' : '';
        $trafficAreasList[] = [
            'label' => $label,
            'value' => $this->registrationDetails['trafficAreas'][$i]['name']
        ];
    }
} else {
    $trafficAreasList[] = [
        'label' => 'TAOs covered by route',
        'value' => ''
    ];
}
echo $this->render('partials/read-only/main',
    [
        'multiItems' => [
            0 => [
                ['label' => 'Bus registration', 'value' => $this->registrationDetails['regNo']],
            ],
            1 => [
                ['label' => 'Variation No.', 'value' => $this->registrationDetails['variationNo']]
            ],
            2 => [
                ['label' => 'Status', 'value' => $this->registrationDetails['status']['description']]
            ],
            3 => [
                ['label' => 'Service No.()', 'value' => $this->registrationDetails['serviceNo']]
            ],
            4 => $busServiceTypes,
            5 => [
                ['label' => 'Start point', 'value' => $this->registrationDetails['startPoint']],
                ['label' => 'Finish point', 'value' => $this->registrationDetails['finishPoint']],
                ['label' => 'Via', 'value' => $this->registrationDetails['via']]
            ],
            6 => [
                ['label' => 'Date received', 'value' => $this->registrationDetails['receivedDate']],
                ['label' => 'Effective date', 'value' => $this->registrationDetails['effectiveDate']],
                ['label' => 'End date', 'value' => $this->registrationDetails['endDate']]
            ],
            7 => [
                [
                    'label' => 'Supported by subsidies?',
                    'type' => 'yesno',
                    'value' => $this->registrationDetails['subsidised']['description']
                ]
            ],
            8 => $localAuthoritiesList,
            9 => $trafficAreasList,
            10 => [
                ['label' => 'N&P Reference', 'value' => $this->registrationDetails['npRreferenceNo']]
            ]
        ]
    ]
);
?>
<?php echo $this->variationHistoryTable; ?>

    <h3>Documents</h3>
    <div class="files">
        <div class="field file-upload">
            <p><a href=""><b>Example Uploaded EBSR pack</b></a><span> (1.4MB)</span></p>
        </div>
        <div class="field file-upload">
            <p><a href=""><b>Example Official VOSA record</b></a><span> (156KB)</span></p>
        </div>
        <div class="field file-upload">
            <p><a href=""><b>Example Route track map</b></a><span> (1.2MB)</span></p>
        </div>
    </div>

</div>
