<?php
echo $this->render(
    '/partials/page-header.phtml',
    array(
        'pageTitle' => $this->translate('Ebsr packs'),
        'pageSubTitle'=> $this->translate('These are all the EBSR pack files you have uploaded.'),
    )
);
?>

<div class="three-quarters">
<?php echo $this->flashMessengerAll();?>
<?php echo $this->ebsrPackTable; ?>

<?php

$busServiceTypes = '';
if (!empty($this->registrationDetails['busServiceTypes'])) {
    foreach($this->registrationDetails['busServiceTypes'] as $busServiceType) {
        $busServiceTypes .= $busServiceType['description'] . '<br />';
    }
}
echo $this->render('partials/read-only/main',
    [
        'header' => 'Bus registration details',
        'multiItems' => [
            0 => [
                ['label' => 'Bus registration', 'value' => $this->registrationDetails['regNo']],
            ],
            1 => [
                ['label' => 'Variation No.', 'value' => $this->registrationDetails['variationNo']]
            ],
            2 => [
                ['label' => 'Status', 'value' => $this->registrationDetails['status']['description']]
            ],
            3 => [
                ['label' => 'Service No.()', 'value' => $this->registrationDetails['serviceNo']]
            ],
            4 => [
                ['label' => 'Service type', 'value' => $busServiceTypes]
            ],
            5 => [
                ['label' => 'Start point', 'value' => $this->registrationDetails['startPoint']],
                ['label' => 'Finish point', 'value' => $this->registrationDetails['finishPoint']],
                ['label' => 'Via', 'value' => $this->registrationDetails['via']]
            ],
            6 => [
                ['label' => 'Date received', 'value' => $this->registrationDetails['receivedDate']],
                ['label' => 'Effective date', 'value' => $this->registrationDetails['effectiveDate']],
                ['label' => 'End date', 'value' => $this->registrationDetails['endDate']]
            ],
            7 => [
                [
                    'label' => 'Supported by subsidies?',
                    'type' => 'yesno',
                    'value' => $this->registrationDetails['subsidyDetail']
                ]
            ],
            8 => [
                ['label' => 'TAOs covered by route', 'value' => $this->registrationDetails['status']['description']],
                ['label' => 'Local authorities covered by route', 'value' => $this->registrationDetails['status']['description']]
            ],
            9 => [
                ['label' => 'N&P Reference', 'value' => $this->registrationDetails['status']['description']]
            ],
            10 => [
                ['label' => 'Official record', 'value' => $this->registrationDetails['status']['description']]
            ],
            11 => [
                ['label' => 'File submitted', 'value' => $this->registrationDetails['status']['description']]
            ],
            12 => [
                ['label' => 'Route track map', 'value' => $this->registrationDetails['status']['description']]
            ]
        ]
    ]
);
?>
<?php echo $this->variationHistoryTable; ?>

</div>
