<?php if (isset($form)): ?>
    <?php echo $this->formErrors($form); ?>
    <?php if (!is_null($this->successStatus)): ?>
        <div class="notice-container">
            <div class="notice--<?php echo $this->successStatus == 1 ? 'info' : 'warning'; ?>">
                <p><?php echo ($this->successStatus == 1 ? $this->translate('Disc printing successful') : $this->translate('Disc printing failed')); ?></p>
            </div>
        </div>
    <?php endif; ?>
    <?php echo $this->form($form); ?>
<?php endif; ?>
