<h4><?php echo $this->translate('search-result-on-this-page'); ?></h4>
<ul class="vertical-navigation">
  <li>
    <a href="#licence-details"><?php echo $this->translate('search-result-nav-licence-details'); ?></a>
  </li>
  <li>
    <a href="#contact-details"><?php echo $this->translate('search-result-nav-contact-details'); ?></a>
  </li>
  <li>
    <a href="#operating-centres"><?php echo $this->translate('search-result-nav-operating-centres'); ?></a>
  </li>
  <li>
    <a href="#transport-managers"><?php echo $this->translate('search-result-nav-transport-managers'); ?></a>
  </li>
  <li>
    <a href="#related-operator-licences"><?php echo $this->translate('search-result-nav-related-operator-licences');
    ?></a>
  </li>
</ul>
