<h4><?php echo $this->translate('search-result-on-this-page'); ?></h4>
<ul class="vertical-navigation">
  <li>
      <?php echo $this->link('#licence-details', 'search-result-nav-licence-details'); ?>
  </li>
  <li>
      <?php echo $this->link('#contact-details', 'search-result-nav-contact-details'); ?>
  </li>
  <li>
      <?php echo $this->link('#operating-centres', 'search-result-nav-operating-centres'); ?>
  </li>
  <li>
      <?php echo $this->link('#transport-managers', 'search-result-nav-transport-managers'); ?>
  </li>
  <li>
      <?php echo $this->link('#related-operator-licences', 'search-result-nav-related-operator-licences'); ?>
  </li>
</ul>
