<h4><?php echo $this->translate('entity-details-on-this-page'); ?></h4>
<ul class="vertical-navigation">
    <li>
        <a href="#licence-details"><?php echo $this->translate('entity-details-nav-licence-details'); ?></a>
    </li>
    <li>
        <a href="#contact-details"><?php echo $this->translate('entity-details-nav-contact-details'); ?></a>
    </li>
    <li>
        <a href="#company-details"><?php echo $this->translate('entity-details-nav-company-details'); ?></a>
    </li>
    <li>
        <a href="#operating-centres"><?php echo $this->translate('entity-details-nav-operating-centres'); ?></a>
    </li>
    <li>
        <a href="#transport-managers"><?php echo $this->translate('entity-details-nav-transport-managers'); ?></a>
    </li>
    <li>
        <a href="#related-operator-licences"><?php echo $this->translate('entity-details-nav-related-operator-licences');
            ?></a>
    </li>
    <li>
        <a href="#vehicles"><?php echo $this->translate('entity-details-nav-vehicles');
            ?></a>
    </li>
    <li>
        <a href="#current-applications"><?php echo $this->translate('entity-details-nav-current-applications');
            ?></a>
    </li>
    <li>
        <a href="#conditions-undertakings"><?php echo $this->translate('entity-details-nav-conditions-undertakings');
            ?></a>
    </li>
</ul>
