<h4><?php echo $this->translate('entity-details-on-this-page'); ?></h4>
<ul class="vertical-navigation">
    <li>
        <?php echo $this->link('#licence-details', 'entity-details-nav-licence-details'); ?>
    </li>
    <li>
        <?php echo $this->link('#contact-details', 'entity-details-nav-contact-details'); ?>
    </li>
    <li>
        <?php echo $this->link('#company-details', 'entity-details-nav-company-details'); ?>
    </li>
    <li>
        <?php echo $this->link('#operating-centres', 'entity-details-nav-operating-centres'); ?>
    </li>
    <li>
        <?php echo $this->link('#transport-managers', 'entity-details-nav-transport-managers'); ?>
    </li>
    <li>
        <?php echo $this->link('#related-operator-licences', 'entity-details-nav-related-operator-licences'); ?>
    </li>
    <li>
        <?php echo $this->link('#vehicles', 'entity-details-nav-vehicles'); ?>
    </li>
    <li>
        <?php echo $this->link('#current-applications', 'entity-details-nav-current-applications'); ?>
    </li>
    <li>
        <?php echo $this->link('#conditions-undertakings', 'entity-details-nav-conditions-undertakings'); ?>
    </li>
</ul>
