<h2><?php echo $this->translate('operator-details');?></h2>
<?php
$registeredCompanyName = isset($this->result['organisation']['name']) ?
    $this->result['organisation']['name'] : '';
$companyNumber = isset($this->result['organisation']['companyOrLlpNo']) ? $this->result['organisation']['companyOrLlpNo'] : '';
$registeredAddress = isset($this->result['organisation']['contactDetails']['address']) ?
    $this->address($this->result['organisation']['contactDetails']['address']) : '';
$subsidiaries = isset($this->result['companySubsidiaries']) ? $this->result['companySubsidiaries'] : '';

$existingPiRecords = isset($this->result['existingPiRecords']) ? $this->result['existingPiRecords'] : '';
$isDisqualified = isset($this->result['isDisqualified']) ? $this->result['isDisqualified'] : '';
$multipleLicenceHolder = isset($this->result['multipleLicenceHolder']) ? $this->result['multipleLicenceHolder'] : '';

echo $this->render('partials/read-only/main',
    [
        'multiItems' => [
            0 => [
                ['label' => 'registered-company-name', 'value' => $registeredCompanyName],
                ['label' => 'company-number', 'value' => $companyNumber],
                ['label' => 'registered-address', 'value' => $registeredAddress],
                ['label' => 'subsidiaries', 'value' => $subsidiaries],
            ],
            2 => [
                ['label' => 'existing-pi-records', 'value' => $existingPiRecords],
                ['label' => 'operator-disqualified', 'type' => 'yesno', 'value' => $isDisqualified],
                ['label' => 'multiple-licence-holder', 'type' => 'yesno', 'value' =>
                    $multipleLicenceHolder]
            ]
        ]
    ]
);
