<?php

use Common\RefData;

$items = [];
$additional = [];
$faxCount = 0;
$phoneCount = 0;

$address = isset($this->result['licenceContactDetails']['address']) ?
    $this->address($this->result['licenceContactDetails']['address']) : '';

$items[] = [
    0 => [
        'noEscape' => true,
        'label' => 'search-result-label-address',
        'value' => $address
    ]
];

$phoneContacts = $this->result['licenceContactDetails']['phoneContacts'];
$primaryList = [];
$secondaryList = [];
if (!empty($phoneContacts)) {
    for ($i = 0, $n = count($phoneContacts); $i < $n; $i++) {
        if ($phoneContacts[$i]['phoneContactType']['id'] === RefData::PHONE_TYPE_PRIMARY) {
            $primaryList[] = [
                'label' => 'search-result-label-primary-number',
                'value' => $phoneContacts[$i]['phoneNumber']
            ];
        }
        if ($phoneContacts[$i]['phoneContactType']['id'] === RefData::PHONE_TYPE_SECONDARY) {
            $secondaryList[] = [
                'label' => 'search-result-label-secondary-number',
                'value' => $phoneContacts[$i]['phoneNumber']
            ];
        }
    }
} else {
    $primaryList[] = [
        'label' => 'search-result-label-primary-number',
        'value' => ''
    ];
}

if (empty($primaryList)) {
    $primaryList[] = [
        'label' => 'search-result-label-phone-numbers',
        'value' => ''
    ];
}
$items[] = $primaryList;
if (!empty($secondaryList)) {
    $items[] = $secondaryList;
}
$items[] = [
    0 => [
        'label' => 'search-result-label-email',
        'value' => $this->result['licenceContactDetails']['emailAddress']
    ]
];

echo $this->render('partials/read-only/main',
    [
        'multiItems' =>
            $items

    ]
);
