<?php
$registeredCompanyName = isset($this->result['organisation']['name']) ?
    $this->result['organisation']['name'] : '';
$companyNumber = isset($this->result['organisation']['companyOrLlpNo']) ? $this->result['organisation']['companyOrLlpNo'] : '';
$registeredAddress = isset($this->result['organisation']['contactDetails']['address']) ?
    $this->address($this->result['organisation']['contactDetails']['address']) : '';
$subsidiaries = isset($this->result['companySubsidiaries']) ? $this->result['companySubsidiaries'] : '';

$existingPiRecords = isset($this->result['existingPiRecords']) ? $this->result['existingPiRecords'] : '';
$isDisqualified = isset($this->result['isDisqualified']) ? $this->result['isDisqualified'] : '';
$multipleLicenceHolder = isset($this->result['multipleLicenceHolder']) ? $this->result['multipleLicenceHolder'] : '';

echo $this->render('partials/read-only/main',
    [
        'multiItems' => [
            0 => [
                ['label' => 'entity-view-label-company-registration-number', 'value' => $companyNumber],
                ['label' => 'entity-view-label-registered-company-name', 'value' => $registeredCompanyName],
                ['label' => 'entity-view-label-registered-address', 'value' => $registeredAddress],
            ],
            //1 => $directorsList,
            //2 => $subsidiaries
        ]
    ]
);
