<?php

$items = [];
if (!empty($this->result['organisation']['tradingNames'])) {
    for($i = 0; $i<count($this->result['organisation']['tradingNames']);$i++) {
        $label = ($i == 0) ? 'search-result-label-trading-names' : '';
        $tradingNamesList[] = [
            'label' => $label,
            'value' => $this->result['organisation']['tradingNames'][$i]['name']
        ];
    }
} else {
    $tradingNamesList[] = [
        'label' => 'search-result-label-trading-names',
        'value' => ''
    ];
}
$items[] = $tradingNamesList;

if (!in_array($this->result['organisation']['type']['id'], $this->soleTraderOrRegisteredCompany)) {
    if (!empty($this->result['partners'])) {
        for ($i = 0; $i < count($this->result['partners']); $i++) {
            $label = ($i == 0) ? 'search-result-label-partners' : '';
            $partnersList[] = [
                'label' => $label,
                'value' =>
                    $this->result['partners'][$i]['person']['forename'] . ' ' .
                    $this->result['partners'][$i]['person']['familyName']
            ];
        }
    } else {
        $partnersList[] = [
            'label' => 'search-result-label-partners',
            'value' => ''
        ];
    }
    $items[] = $partnersList;
}


if (!empty($this->result['directors'])) {
    for($i = 0; $i<count($this->result['directors']);$i++) {
        $label = ($i == 0) ? 'search-result-label-directors' : '';
        $directorsList[] = [
            'label' => $label,
            'value' =>
                $this->result['directors'][$i]['person']['forename'] . ' ' .
                $this->result['directors'][$i]['person']['familyName']
        ];
    }
} else {
    $directorsList[] = [
        'label' => 'search-result-label-directors',
        'value' => ''
    ];
}
$items[] = $directorsList;

$licenceType = isset($this->result['licenceType']['description']) ? $this->result['licenceType']['description'] : '';
$licenceReviewDate = isset($this->result['reviewDate']) ? $this->result['reviewDate'] : '';

$totalVehicleAuthority = isset($this->result['totalAuthVehicles']) ? $this->result['totalAuthVehicles'] : '';
$vehiclesInPossession = isset($this->result['totalVehiclesInPossession']) ?
    $this->result['totalVehiclesInPossession'] : '';
$totalTrailerAuthority = isset($this->result['totalAuthTrailers']) ? $this->result['totalAuthTrailers'] : '';
$trailersInPossession = isset($this->result['trailersInPossession']) ? $this->result['trailersInPossession'] : '';

$totalPiRecords = isset($this->result['totalPiRecords']) ? $this->result['totalPiRecords'] : '';
$isDisqualified = isset($this->result['isDisqualified']) ? $this->result['isDisqualified'] : 'TODO';

$activeCommunityLicences = isset($this->result['activeCommunityLicences']) ?
    $this->result['activeCommunityLicences'] : '';

$multipleLicenceHolder = isset($this->result['otherLicences']) && count($this->result['otherLicences']) > 0 ?
    'Y' : 'N';

$leadTrafficCommissioner = isset($this->result['organisation']['leadTcArea']['contactDetails']['person']) ?
    $this->personName($this->result['organisation']['leadTcArea']['contactDetails']['person']) : '';

$trafficArea = isset($this->result['trafficArea']['description']) ? $this->result['trafficArea']['description'] : '';

$licenceStartDate = isset($this->result['inForceDate']) ? $this->result['inForceDate'] : '';
$licenceStatus = isset($this->result['status']['description']) ? $this->result['status']['description'] : '';
$continuationDate = isset($this->result['expiryDate']) ? $this->result['expiryDate'] : '';
$trafficArea = isset($this->result['trafficArea']['name']) ? $this->result['trafficArea']['name'] : '';

echo $this->render('partials/read-only/main',
    [
        'multiItems' =>
            array_merge(
                $items,
                [
                    3 => [
                        ['label' => 'search-result-label-licence-start-date', 'value' => $licenceStartDate],
                        ['label' => 'search-result-label-licence-review-date', 'value' => $licenceReviewDate],
                        ['label' => 'search-result-label-licence-type', 'value' => $licenceType],
                        ['label' => 'search-result-label-licence-status', 'value' => $licenceStatus],
                        [
                            'label' => 'search-result-label-continuation-date',
                            'dateFormat' => 'Y-m-d',
                            'date' => $continuationDate
                        ]
                    ],
                    4 => [
                        ['label' => 'search-result-label-vauth', 'value' => $totalVehicleAuthority],
                        ['label' => 'search-result-label-vip', 'value' => $vehiclesInPossession],
                        ['label' => 'search-result-label-tauth', 'value' => $totalTrailerAuthority],
                        ['label' => 'search-result-label-tip', 'value' => $trailersInPossession],
                    ],
                    5 => [
                        ['label' => 'search-result-label-existing-pi', 'value' => $totalPiRecords],
                        ['label' => 'search-result-label-operator-disqualified', 'value' =>
                            $isDisqualified],
                        [
                            'label' => 'search-result-label-total-community-licences',
                            'value' => $activeCommunityLicences
                        ],
                        [
                            'label' => 'search-result-label-multiple-licence-holder',
                            'type' => 'yesno',
                            'value' => $multipleLicenceHolder
                        ],
                    ],
                    6 => [
                        ['label' => 'search-result-label-lead-tc', 'value' => $leadTrafficCommissioner],
                        ['label' => 'search-result-label-traffic-area', 'value' => $trafficArea],
                    ]
                ]
            )
    ]
);
