<?php
$registeredCompanyName = isset($this->result['organisation']['name']) ?
    $this->result['organisation']['name'] : '';
$companyNumber = isset($this->result['organisation']['companyOrLlpNo']) ? $this->result['organisation']['companyOrLlpNo'] : '';
$registeredAddress = isset($this->result['organisation']['contactDetails']['address']) ?
    $this->address($this->result['organisation']['contactDetails']['address']) : '';

if (!empty($this->result['directors'])) {
    for ($i = 0, $n = count($this->result['directors']); $i < $n; $i++) {
        $label = ($i == 0) ? 'search-result-label-directors' : '';
        $directorsList[] = [
            'label' => $label,
            'value' =>
                $this->result['directors'][$i]['person']['forename'] . ' ' .
                $this->result['directors'][$i]['person']['familyName']
        ];
    }
} else {
    $directorsList[] = [
        'label' => 'search-result-label-directors',
        'value' => ''
    ];
}
$subsidiaryList = [];
foreach ($this->result['companySubsidiaries'] as $cs) {
    $subsidiaryList[] = $cs['name'];
}

echo $this->render('partials/read-only/main',
    [
        'multiItems' => [
            0 => [
                [
                    'label' => 'entity-view-label-company-registration-number',
                    'value' => $companyNumber
                ],
                [
                    'label' => 'entity-view-label-registered-company-name',
                    'value' => $registeredCompanyName
                ],
                [
                    'noEscape' => true,
                    'label' => 'entity-view-label-registered-address',
                    'value' => $registeredAddress
                ],
            ],
            1 => $directorsList,
            2 => [
                [
                    'label' => 'entity-view-label-subsidiaries',
                    'value' => implode(', ', $subsidiaryList)
                ]
            ]
        ]
    ]
);
