<ul class="horizontal-navigation">
<?php foreach ($this->container as $page): ?>
    <?php if($page->isVisible(true)): ?>
        <li class="horizontal-navigation__item<?php if ($page->isActive(true)) { ?> current<?php } ?>">
        <?php if ($page->isActive(true)): ?>
        <span><?php echo $this->translate($page->getLabel()); ?></span>
        <?php else: ?>
        <?php echo $this->navigation()->menu()->htmlify($page) . PHP_EOL; ?>
        <?php endif; ?>
        </li>
    <?php endif; ?>
<?php endforeach; ?>
</ul>