<?php
    /**
     * @NOTE: might want to DRY up with Application / Application Variation overview
     * templates if maintaining three is a pain. Lots of common ground, but they're
     * small templates so no biggie to have them separate for now
     */
?>
<div class="two-thirds">
    <a href="<?php echo $this->url('dashboard'); ?>"><?php echo $this->translate('dashboard.link'); ?></a>
    <div class="page-header">
      <div class="page-header__wrapper">
        <h3 class="page-header__subtitle">
            <?php echo $this->translate('licence.overview.licence-no'); ?> <?php echo $licenceId; ?>
        </h3>
        <h1><?php echo $this->translate('licence.overview.title'); ?></h1>
      </div>
    </div>
    <ul style="list-style: none; clear: both;">
        <?php
        foreach ($sections as $section) {
            echo $this->render($section);
        }
        ?>
    </ul>
</div>
<div class="one-third">
  <a href="#"><?php echo $this->translate('licence.print'); ?></a><br />
  <a href="#"><?php echo $this->translate('licence.delete'); ?></a>
  <p>
    <?php echo $this->translate('created'); ?><br />
    <strong><?php echo $createdOn; ?></strong>
  </p>
  <p>
    <?php echo $this->translate('renewal'); ?><br />
    <strong><?php echo $renewal; ?></strong>
  </p>
  <p>
    <?php echo $this->translate('status'); ?><br />
    <strong><?php echo $this->translate($status); ?></strong>
  </p>
</div>
