<div class="govuk-grid-row">

    <?php echo $this->flashMessengerAll(); ?>
    <div class="govuk-!-width-two-thirds">
        <?php
        echo $this->partial(
            'partials/page-header-simple',
            [
                'pageTitle' => $this->translate($pageTitle),
                'pageSubTitle' => $licNo,
                'backUrl' => [
                    'url' => $backUrl,
                ],
            ]
        );
        ?>
        <div class="govuk-!-width-two-thirds">
            <?php echo $this->form($form); ?>

        </div>
        <p><a href="<?php echo $returnLink;?>" title="return to previous step"><?php $this->translate($returnLinkText);?></a></p>
    </div>
</div>