<div class="row">
    <?php echo $this->flashMessengerAll(); ?>
    <div class="two-thirds">
        <?php
        echo $this->partial(
            'partials/page-header-simple',
            [
                'pageTitle' => $this->translate($pageTitle),
                'pageSubTitle' => $licNo,
                'backUrl' => [
                    'url' => $backUrl,
                ],
            ]
        );
        ?>
        <?php echo $this->translateReplace($body, $cancelBus) ?>

        <?php echo $this->form($form); ?>
    </div>
</div>