<div class="govuk-grid-row">

    <?php echo $this->flashMessengerAll();?>
    <div class="govuk-!-width-two-thirds">
        <?php
        echo $this->partial(
            'partials/page-header-simple',
            [
                'pageTitle' => $this->translate($pageTitle),
                'pageSubTitle' => $licNo,
                'backUrl' => [
                    'url' => $backUrl,
                ],
            ]
        );
        ?>
        <?php echo $this->translate($content); ?>
        <?php echo $this->form($form); ?>
    </div>
</div>