<div class="page-header">
  <div class="page-header__wrapper">
  <h3 class="page-header__subtitle"><?php echo $this->currentUser()->getOrganisationName() ?></h3>
  <h1><?php echo $this->translate('dashboard.title'); ?></h1>
  </div><!-- .page-header__wrapper -->
</div><!-- .page-header-->

<div class="dashboard two-thirds">
  <?php echo $this->flashMessengerAll(); ?>

  <?php

  /* @var \Zend\View\Helper\Navigation\Menu $menu */
  $menu = $this->navigation($this->navigation('navigation')->getContainer()->findBy('id', 'dashboard-licences-applications'))->menu();

  echo $menu->setMinDepth(0)->setMaxDepth(0)
      ->setPartial('partials/dashboard-nav');
  ?>

  <?php if (isset($table)): ?>
    <?php echo $table; ?>
  <?php endif; ?>
</div>

<?php echo $this->partial('partials/dashboard-right-column'); ?>