<?php
/** @var \Zend\Navigation\Page\Mvc $backPage */
$backPage = $this->navigationParentPage();

echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->translate('pay-fees.title'),
        'backUrl' => [
            'url' => ($backPage !== null ? $backPage->getHref() : $this->url('fees')),
        ],
    ]
);
?>

<div class="row">
  
  <div class="three-quarters">
  
      <?php
      $guidanceMessage = $this->placeholder('guidance');
      if (!empty($guidanceMessage)) {
          foreach ($guidanceMessage as $message):
              ?>
              <div class="guidance">
                  <p><?php echo $this->translate($message); ?></p>
              </div>
              <?php
          endforeach;
      }
      ?>
  
      <!-- table -->
    <?php if (isset($table)): ?>
      <?php echo $table; ?>
    <?php endif; ?>
  
    <hr>
  
    <?php echo $this->translate('markup-pay-fees-notice' . ($hasContinuation ? '-continuation' : '')); ?>
  
    <hr>
  
    <?php if (isset($form)): ?>
      <?php echo $this->form($form); ?>
    <?php endif ?>
  
  </div>

</div>