<?php $this->placeholder('body-class')->set("full-page") ?>
<tbody id="listTable">
    <?php foreach ($listData as $licence) : ?>
        <tr>
            <td><a href="#"><?php echo $this->escapeHtml($licence['licenceNumber']); ?></a><br><?php echo $this->escapeHtml($licence['licenceStatus']); ?></td>
            <td></td>
            <td><?php
                echo $this->escapeHtml($licence['operator']['operatorName']);
                if (!empty($licence['tradingNames'])) {
                    echo "<br/>(" . $this->escapeHtml(implode(', ', $licence['tradingNames'])) . ")";
                }
            ?></td>
            <td>
                <span class="noWrap"><?php echo $this->escapeHtml($licence['operator']['entityType']); ?></span><br>
                <?php echo $this->escapeHtml($licence['licenceType']); ?>
            </td>
            <td>
                WL
                <img data-toggle="tooltip" title="first tooltip<br>second tip<br>etc." data-placement="left" data-trigger="click" data-html="true" src="/img/p.png" class="sprt sprpage ttips cur" /><br>

            </td>
            <td class="cur correAddress">
                <?php echo $this->partial('olcs/common/address', array('address' => $licence['address'])); ?>
            </td>
            <td class="cur opCentAddress"></td>
            <td class="centre"><?php if ($licence['caseCount'] < 1) : ?>
                            <a href="/case/new/<?php echo $this->escapeHtml($licence['licenceId']); ?>"><img  src="/img/p.png" class="sprt plsBl" /></a>
                        <?php else: ?>
                            <a href="/case/list/<?php echo $this->escapeHtml($licence['licenceId']); ?>/page/1/10"><?php echo $licence['caseCount']; ?></a>
                        <?php endif; ?>
                </td>
            <td class="centre"><a href="#">Y</a></td>
            <td class="centre"><img rel="tooltip" data-toggle="tooltip" title="<?php
                    echo $this->resourceHelper('start-date') . ": " .$this->simpleDateFormat($licence['startDate'], 'default', 'n/a') . "<br/>";
                    echo $this->resourceHelper('review-date') . ": " .$this->simpleDateFormat($licence['reviewDate'], 'default', 'n/a') . "<br/>";
                    echo $this->resourceHelper('end-date') . ": " .$this->simpleDateFormat($licence['endDate'], 'default', 'n/a') . "<br/>";
                    echo $this->resourceHelper('fabs-reference').": ".$this->escapeHtml($licence['fabsReference'])."<br/>"
            ?>" data-trigger="click" data-placement="left"  data-html="true" src="/img/p.png" class="sprt sprinfo ttips cur" /></td>
        </tr>
    <?php endforeach; ?>
</tbody>
