<?php
$form = $this->placeholder('form')->getValue();
?>
<?php if (count($form) > 0): ?>

    <?php
    if ($form->getOption('alter_label') === false) {
    ?>
        <h3><?php echo 'Add / Edit ' . $this->translate($form->getOption('label')); ?></h3>
    <?php
    } else {
    ?>
        <h3><?php echo 'Add / Edit ' . ucwords(strtolower($this->translate($form->getOption('label')))); ?></h3>
    <?php
    }
    ?>

<?php echo $this->formErrors($form); ?>
<?php echo $this->form($form); ?>

<?php endif; ?>
