<?php echo $this->doctype(); ?>
<html lang="en-GB">

  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->pageTitle()); ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>
    <?php echo $this->headLink()->appendStylesheet($this->assetPath('/styles/' . $this->applicationName() . '.css'), ['media' => 'screen,print']); ?>
    <?php echo $this->headScript(); ?>
    <!--[if IE]>
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body class="selfserve" id="<?php echo $this->pageId(); ?>">

    <script type="text/javascript">
      var dataLayer = [{
        
      }];
    </script>

    <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PN74L4"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-PN74L4');</script>
    <!-- End Google Tag Manager -->

    <?php echo $this->version(); ?>
    
    <script>document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');</script>

    <a class="visually-hidden" id="skipToContent" href="#main"><?php echo $this->translate('skip-content'); ?></a>

    <header role="banner" class="global-header">
      <div class="global-header__wrapper">

        <a href="/" title="Go to dashboard" class="global-header__logo">
          <img aria-label="GOV-dot-U.K logo" src="<?php echo $this->assetPath('/images/bitmap/gov.uk_logotype_crown.png') ?>" alt="GOV.UK logo">
          <span aria-hidden="true">GOV.UK</span>
        </a>

        <div class="proposition" role="navigation">

          <h2 class="proposition__title">
            <?php echo $this->translate('header-vehicle-operator-licensing'); ?>
          </h2>

          <a class="proposition__toggle" href="#">Menu</a>

            <?php

            /* @var \Zend\View\Helper\Navigation\Menu $menu */
            $menu = $this->navigation($this->navigation('navigation')->getContainer()->findBy('id', 'home'))->menu();

            $menu->setAddClassToListItem(true);

            // This seems irrelevant, but it's very important as the partial is set elsewhere
            $menu->setPartial(null);
            $menu->setMaxDepth(0);
            $menu->setMinDepth(0);

            echo $menu->setUlClass('proposition-nav');
            ?>

        </div>

      </div>
    </header><!-- .global-header -->

    <?php
    //  system info messages
    if (! $this->currentUser()->isLoggedIn()) :
        echo $this->systemInfoMessages(false);
    endif;

    //  use cookie notification
    $showCookieBanner = $this->getPlaceholder('showCookieBanner')->asBool();
    if ($showCookieBanner === true) { ?>
      <div class="cookie-banner">
        <div class="cookie-banner__wrapper">
            <p>
              <?php echo $this->translate('cookie-banner'); ?>
              <a href="<?php echo $this->url('cookies'); ?>"><?php echo $this->translate('Find out more'); ?></a>
            </p>
        </div>
      </div>
    <?php } ?>

    <div class="page-wrapper">
        <div class="user-header">
            <?php echo $this->translate('markup-alpha-banner'); ?>
            <ul class="user-menu">
                <?php if($this->currentUser()->isLoggedIn()):?>
                    <li class="user-menu__item"><?php echo $this->currentUser()->getFullName() ?>, <b><?php echo $this->currentUser()->getOrganisationName() ?></b></li>
                    <li class="user-menu__item">
                        <a href="<?php echo $this->url('auth/logout');?>">
                            <?php echo $this->translate('Sign out'); ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="user-menu__item">
                        <a href="<?php echo $this->url('auth/login');?>">
                            <?php echo $this->translate('Sign in'); ?>
                        </a>
                    </li>
                <?php endif;?>
            </ul>
        </div><!-- user-header -->

        <main id="main" role="main">
            <?php echo $this->content; ?>
        </main><!-- main -->

    </div><!-- page-wrapper-->

    <footer class="global-footer" role="contentinfo">
      <div class="global-footer__wrapper">
        <ul class="global-footer__links">
          <li class="global-footer__support">
            <?php echo $this->translate('markup-support-helpline');?>
          </li>
          <li class="global-footer__link">
            <a href="<?php echo $this->url('terms-and-conditions');?>"><?php echo $this->translate('terms-and-conditions-title') ?></a>
          </li>
          <li class="global-footer__link">
            <a href="<?php echo $this->url('cookies');?>"><?php echo $this->translate('privacy-and-cookies-title') ?></a>
          </li>
          <li class="global-footer__link">
            <?php echo $this->languageLink(); ?>
          </li>
          <li class="global-footer__link">
            <?php echo $this->translate('built-by'); ?> <a href="<?php echo $this->translate('DVSA-link'); ?>">Driver and Vehicle Standards Agency</a>
          </li>
        </ul>
        <div class="global-footer__copyright">
          <a href="<?php echo $this->translate('crown-copyright-link'); ?>" target="blank">&copy; <?php echo $this->translate('crown-copyright'); ?></a>
        </div>
      </div>
    </footer><!-- global-footer -->

    <?php echo $this->inlineScript()
        ->prependFile($this->assetPath('js/' . $this->applicationName() . '.js')) ?>

    <script>
      OLCS.ready(function() {
        OLCS.eventEmitter.emit("render");
      });
    </script>

    <script>

      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];
      a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      <?php $userId = $this->currentUser()->getUniqueId(); if (!empty($userId)) { ?>
        ga('create', 'UA-56588861-1', 'auto', {
          'userId': '<?php echo $userId; ?>',
          anonymizeIp: true
        });
        ga('set', 'dimension1', '<?php echo $userId; ?>');
      <?php } else { ?>
        ga('create', 'UA-56588861-1', 'auto', {
          anonymizeIp: true
        });
      <?php } ?>
      ga('send', 'pageview');

    </script>

  </body>
</html>
