<div class="submission-section submission-details">
    <ul class="submission-owner details-list">
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('from'); ?>:</span>
            <?php echo $this->escapeHtml($caseOwner); ?>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('date-prepared'); ?>:</span>
            <?php echo $this->simpleDateFormat($submissionCreatedAt, 'd.m.Y'); ?>
        </li>
    </ul>

    <h1><?php echo $this->resourceHelper('submission-view-title', array(
        '@operatorType' => $this->escapeHtml(ucfirst($submissionType)),
    )); ?></h1>
    <p class="submission-notice"><?php echo $this->resourceHelper('submission-notice'); ?></p>

    <ul class="submission-details details-list details-list-columns">
        <li class="long-detail">
            <span class="details-list-label"><?php echo $this->resourceHelper('case-summary'); ?>:</span>
            <p><?php echo $this->escapeHtml($description); ?></p>
            <div>
                <?php echo $this->resourceHelper('ecms-number'); ?>:
                <?php echo $this->escapeHtml($ecms); ?>
            </div>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('operator-name'); ?>:</span>
            <?php echo $this->escapeHtml($operator['operatorName']); ?>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('licence-number'); ?>:</span>
            <?php echo $this->escapeHtml($licence['licenceNumber']); ?>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('licence-type'); ?>:</span>
            <?php echo $this->escapeHtml($licence['licenceType']); ?>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('business-type'); ?>:</span>
            <?php echo $this->escapeHtml($licence['tradeType']); ?>
        </li>
        <li class="long-detail">
            <span class="details-list-label"><?php echo $this->resourceHelper('mlh'); ?>:</span>
            <?php echo $this->escapeHtml($mlh); ?>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('submission-vehicle-trailer'); ?>:</span>
            <?php echo $this->resourceHelper('vehicle-count', array('@count' => $this->escapeHtml($vehicleCount))); ?>,
            <?php echo $this->resourceHelper('trailer-count', array('@count' => $this->escapeHtml($trailerCount))); ?>
        </li>
        <li>
            <span class="details-list-label"><?php echo $this->resourceHelper('submission-vehicle-possession'); ?>:</span>
            <?php echo $this->escapeHtml($vehicleInPossession); ?>
        </li>
        <li class="long-detail">
            <span class="details-list-label"><?php echo $this->resourceHelper('start-date'); ?>:</span>
            <?php echo $this->simpleDateFormat($licence['startDate'], 'Y-m-d'); ?>
        </li>
        <li class="long-detail">
            <span class="details-list-label"><?php echo $this->resourceHelper('entity-type'); ?>:</span>
            <?php echo $this->escapeHtml($operator['entityType']); ?>
        </li>
    </ul>
</div>
