<?php
$section = null;
foreach ($list as $key => $row) { ?>
    <?php
    if ($section !== $row['recommendation']) {
        $section = $row['recommendation'];
        if ($key != 0) {
            ?></div><?php
        }
        if ($row['recommendation']) {
            ?>
            <div class="submission-section submission-recommendations">
                <h2><?php echo $this->resourceHelper('recommendations'); ?></h2><?php
        } else {
            ?>
            <div class="submission-section submission-decisions">
                <h2><?php echo $this->resourceHelper('decisions'); ?></h2><?php
        }
    }
    ?>
    <div class="submission-recommendation-item">
        <div class="submission-recommendation-author">
            <?php echo $this->escapeHtml($row['author-name']); ?>,
            <?php echo $this->escapeHtml($row['author-role']); ?>,
            <?php echo $this->escapeHtml($row['author-location']); ?>.
            <?php echo $row['date-created']->format('d.m.Y'); ?>:
        </div>
        <div class="submission-recommendation-type"><?php echo $this->escapeHtml($row['type']); ?></div>
        <div class="submission-recommendation-comment"><?php echo $row['comment']; ?></div>
    </div>
<?php } ?>
<?php if ($section !== null) { ?>
    </div>
<?php } ?>
