        <div class="global-footer">
			<div class="global-footer__wrapper">
				<ul class="global-footer__links">
					<li class="global-footer__link"><a href=""><?php echo $this->translate('helpdesk');?></a></li>
					<li class="global-footer__link"><a href=""><?php echo $this->translate('privacy-and-cookies');?></a></li>
					<li class="global-footer__link"><?php echo $this->translate('built-by');?> <a href="https://www.gov.uk/government/organisations/driver-and-vehicle-standards-agency"><?php echo $this->translate('driver-vehicle-standards-agency');?></a></li>
				</ul>
				<div class="global-footer__copyright">
					<a href="">&copy; <?php echo $this->translate('crown-copyright');?></a>
				</div>
		    </div><!-- end global-wrapper -->
		</div><!-- end global-footer -->