<div role="banner" class="global-header">
    <div class="global-header__wrapper">
        <a href="https://www.gov.uk" title="Go to the gov.uk homepage" class="global-header__logo">
            <img src="<?php echo $this->assetPath('/images/gov.uk_logotype_crown.png') ?>" alt="GOV.UK logo">GOV.UK
        </a>
        <h2 class="global-header__title">Operator Licensing<span class="global-header__phase-tag">alpha <?php echo $this->version(); ?></span></h2>
    </div><!-- end .global-header__wrapper -->
</div><!-- end .global-header -->
