<?php echo $this->showMarkers();?>
<div class="record-actions">
    <?php
    if (!isset($this->hideQuickActions) || $this->hideQuickActions === false) {
        ?>
        <h5><?php echo $this->translate('internal-operator-quick-actions'); ?></h5>
        <ul class="record-actions__group">
            <li class="record-actions__item">
                <a class="action--secondary<?php echo $this->disable ? ' disabled' : ''; ?> js-modal-ajax" href="<?php echo $this->url('operator/new-application', [], [], true); ?>">
                    <?php echo $this->translate('internal-operator-new-application'); ?>
                </a>
            </li>
        </ul>
    <?php
    }
    ?>
</div>

<?php
if (!$this->disable):
    /* @var $nav \Zend\View\Helper\Navigation\Menu */
    $nav = $this->navigation('right-sidebar')
        ->menu($this->navigation()->findOneBy('id', 'operator-decisions'))
        ->setPartial('partials/record-actions__group');

    if ($nav->getContainer()->hasPages(true)): ?>
    <div class="record-actions">
        <h5><?php echo $this->translate('decisions'); ?></h5>
        <?php echo $nav; ?>
    </div>
    <?php endif; ?>
<?php endif; ?>