<div class="record-actions">
    <h5>Quick actions</h5>
    <ul class="record-actions__group">
      <li class="record-actions__item">
          <a href="<?php echo $this->url('lva-application/review', [], [], true); ?>" target="_blank" class="action--secondary">
              <?php echo $this->translate('view-full-application'); ?>
          </a>
      </li>
      <li class="record-actions__item"><a href="" class="action--secondary">Generate publication</a></li>
      <li class="record-actions__item"><a href="" class="action--secondary">Add recommendation</a></li>
      <li class="record-actions__item actions--secondary">
        <a href="<?php echo $this->url('case', ['action'=>'add'], [], true) ?>" class="action--secondary">
            Create case
        </a>
      </li>
    </ul>
    <?php if ($showGrant || $showUndoGrant) : ?>
    <h5>Decisions</h5>
    <ul class="record-actions__group">
        <?php if ($showGrant) : ?>
        <li class="record-actions__item">
            <a href="<?php echo $this->url('lva-application/grant', array(), array(), true); ?>" class="js-modal-ajax action--secondary">
                Grant application
            </a>
        </li>
        <?php endif; ?>
        <?php if ($showUndoGrant) : ?>
        <li class="record-actions__item">
            <a href="<?php echo $this->url('lva-application/undo-grant', array(), array(), true); ?>" class="js-modal-ajax action--secondary">
                Undo grant application
            </a>
        </li>
        <?php endif; ?>
    </ul>
</div><!-- record-actions -->
<?php endif;
