<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];
        a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    <?php

    $userId = $this->currentUser()->getUniqueId();
    $urlParts = parse_url($this->url('dashboard', [], ['force_canonical' => true]));
    $gaDomain = isset($urlParts['host']) ? $urlParts['host'] : 'auto';

    if (!empty($userId)) {
    ?>
      ga('create', 'UA-56585177-1', '<?php echo $gaDomain ?>', {'userId': '<?php echo $userId; ?>'});
      ga('set', 'dimension1', '<?php echo $userId; ?>');
      <?php
    } else {
      ?>
    ga('create', 'UA-56585177-1', '<?php echo $gaDomain ?>');
    <?php
  }
  ?>

    ga('send', 'pageview');
</script>