<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];
        a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    <?php

    $userId = $this->currentUser()->getUniqueId();

    if (!empty($userId)) {
    ?>
      ga('create', 'UA-56585177-1', 'auto', {'userId': '<?php echo $userId; ?>'});
      ga('set', 'dimension1', '<?php echo $userId; ?>');
      <?php
    } else {
      ?>
    ga('create', 'UA-56585177-1', 'auto');
    <?php
  }
  ?>

    ga('send', 'pageview');
</script>