<div class="page-header">
  <div class="page-header__wrapper">
    <div class="user-header">
        <?php
        echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)
            ->setPartial(array('partials/breadcrumbs.phtml', 'Olcs'));

        $userNav = $this->navigation('user-details')
            ->menu($this->navigation()->findOneBy('id', 'admin-my-account'))
            ->setPartial('partials/user-details');

        if (count($userNav->getContainer()) > 0) {
            echo $userNav;
        }
      ?>
    </div><!-- user-header -->

    <h1><?php echo $licNo; ?></h1>
    <h3 class="page-header__subtitle"><?php echo $companyName; ?>
      <?php echo $this->licenceStatus($status) ?>
    </h3>

  </div><!-- end .page-header__wrapper-->
</div>
