<ul class="pagination right-aligned" role="navigation">
    <li class="pagination__item"><a href="" rel="previous">Previous</a></li>
    <li class="pagination__item"><a href="">1</a></li>
    <li class="pagination__item"><a href="">2</a></li>
    <li class="pagination__item">3</li>
    <li class="pagination__item"><a href="">4</a></li>
    <li class="pagination__item"><a href="">5</a></li>
    <li class="pagination__item">...</li>
    <li class="pagination__item"><a href="">14</a></li>
    <li class="pagination__item"><a href="" rel="next">Next</a></li>
</ul><!-- end .pagination.right-aligned -->