<?php
echo $this->render('partials/read-only/main',
    [
        'header' => $stayType['description'],
        'actions' => [
            [
                'label' => 'Edit',
                'url' => $this->url('case_stay',
                    [
                        'case' => $case['id'],
                        'action' => 'edit',
                        'stayType' => $stayType['id'],
                    ], [], false),
                'class' => 'action--secondary js-modal-ajax'
            ],
        ],
        'items' => [
            ['label' => 'Outcome', 'value' => (isset($outcome['description']) ? $outcome['description'] : '')],
            ['label' => 'Requested date', 'date' => $requestDate],
            ['label' => 'Decision date', 'date' => $decisionDate],
            ['label' => 'Is withdrawn', 'value' => (empty($withdrawnDate) ? 'N' : 'Y')],
            ['label' => 'Withdrawn date', 'date' => $withdrawnDate],
            ['label' => 'Notes', 'value' => $notes, 'class' => 'full-width']
        ]
    ]
);
