<ul class="vertical-navigation" role="menu">
    <?php
    /** @var \Zend\Navigation\Page\AbstractPage $page */
    foreach ($this->container as $page) : ?>
        <?php

        if (! $this->navigation()->accept($page, false)) {
            continue;
        }

        // Ensure that the Permit System Settings page is set correctly.
        $page->route = $page->id;

        // Only add the Stock ID parameter if it exists on the parent and $page is not the Permit System Settings page.
        if (array_key_exists('stockId', $page->parent->params)) {
            if (strpos($page->id, 'permits-system-settings') === false) {
                $route = explode('/', $page->route);
                $matchedRoute = explode('/', $page->routeMatch->getMatchedRouteName());
                $page->setParams(['stockId' => $page->parent->params['stockId']]);

                // Set the page to active if the navigation is printing the current route.
                if ($matchedRoute[count($matchedRoute) - 1] === $route[count($route) - 1]) {
                    $page->active = true;
                }
            }
        }

        $isActive = $page->isActive(true);
        $isVisible = $page->isVisible(true);

        ?>
        <?php if($isVisible): ?>
            <li class="vertical-navigation__item <?php echo $isActive ? 'current' : ''; ?>">
                <?php if (!$isActive) : ?>
                    <?php echo $this->navigation()->menu()->htmlify($page); ?>
                <?php else: ?>
                    <span><?php echo $this->translate($page->getLabel()); ?></span>
                    <?php
                        $tableFilters = $this->placeholder('tableFilters')->getValue();

                        if($tableFilters instanceof \Zend\Form\Form) {
                            echo $this->form($tableFilters);
                        }
                    ?>
                <?php endif; ?>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul><!-- .vertical-navigation -->
