<ul class="vertical-navigation" role="menu">
    <?php foreach ($this->container as $key => $page) : ?>
        <li class="vertical-navigation__item <?php echo $page->isActive(true) ? 'current' : ''; ?>">
            <?php if (!$page->isActive(true)) : ?>
                <?php echo $this->navigation()->menu()->htmlify($page); ?>
            <?php else: ?>
                <span><?php echo $this->translate($page->getLabel()); ?></span>
                <div class="filters">
                <?php
                $tableFilters = $this->placeholder('tableFilters')->getValue();
                if($tableFilters instanceof \Zend\Form\Form) {
                  echo $this->form($tableFilters);
                }
                ?>
                </div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul><!-- .vertical-navigation -->
