<?php
    echo $this->render(
        '/partials/page-header.phtml',
        array(
        'pageTitle' => 'Add/Edit vehicles',    
        'pageSubTitle'=> 'Vehicle details'
        )
    );
?>

<div class="two-thirds">
    <?php 
    echo $this->partial('self-serve/forms/add-'.strtolower($goodsOrPsv).'-vehicle', array(
        'form' => $form,
    ));
    ?>
    <a href="<?php echo $this->url('selfserve/vehicle-safety', array(), true); ?>">Cancel</a>
</div>