<?php
    $stockId = $this->placeholder('stockId')->getValue();
    $operationBaseUrl = 'admin-dashboard/admin-permits/scoring';
    $runHref = $this->url($operationBaseUrl, ['stockId' => $stockId, 'action' => 'run']);
    $acceptHref = $this->url($operationBaseUrl, ['stockId' => $stockId, 'action' => 'accept']);
?>
<div style="float: right;">
    <a id="runButton" style="visibility: hidden;" class="action--primary large js-modal-ajax" href="<?php echo($runHref); ?>">
        Run
    </a>
    <a id="acceptButton" style="margin-left: 20px; visibility: hidden;" class="action--primary large js-modal-ajax" href="<?php echo($acceptHref); ?>">
        Accept
    </a>
</div>

<div id="statusContainer" data-stock-id="<?php echo($this->placeholder('stockId')->getValue()); ?>">
    <h2>One moment please...</h2>
</div>
