<?php

namespace Dvsa\OlcsTest\Api\Entity\Pi;

use Dvsa\OlcsTest\Api\Entity\Abstracts\EntityTester;
use Dvsa\Olcs\Api\Entity\Pi\PiSlaException as Entity;
use Dvsa\Olcs\Api\Entity\Pi\Pi as PiEntity;
use Dvsa\Olcs\Api\Entity\Pi\SlaException as SlaExceptionEntity;
use Mockery as m;

/**
 * PiSlaException Entity Unit Tests
 *
 * @covers \Dvsa\Olcs\Api\Entity\Pi\PiSlaException
 */
class PiSlaExceptionEntityTest extends EntityTester
{
    /**
     * Define the entity to test
     *
     * @var string
     */
    protected $entityClass = Entity::class;

    /**
     * Test that the entity can be instantiated with required parameters
     */
    public function testEntityInstantiation()
    {
        $pi = m::mock(PiEntity::class);
        $slaException = m::mock(SlaExceptionEntity::class);
        
        $entity = new Entity($pi, $slaException);
        $this->assertInstanceOf(Entity::class, $entity);
        $this->assertSame($pi, $entity->getPi());
        $this->assertSame($slaException, $entity->getSlaException());
    }

    /**
     * Test PI relationship getter
     */
    public function testPiGetter()
    {
        $pi = m::mock(PiEntity::class);
        $slaException = m::mock(SlaExceptionEntity::class);
        
        $entity = new Entity($pi, $slaException);
        $this->assertSame($pi, $entity->getPi());
    }

    /**
     * Test SlaException relationship getter
     */
    public function testSlaExceptionGetter()
    {
        $pi = m::mock(PiEntity::class);
        $slaException = m::mock(SlaExceptionEntity::class);
        
        $entity = new Entity($pi, $slaException);
        $this->assertSame($slaException, $entity->getSlaException());
    }

    /**
     * Test entity properties
     */
    public function testEntityProperties()
    {
        $pi = m::mock(PiEntity::class);
        $slaException = m::mock(SlaExceptionEntity::class);
        $entity = new Entity($pi, $slaException);
        
        // Test that all expected properties exist
        $this->assertObjectHasProperty('id', $entity);
        $this->assertObjectHasProperty('pi', $entity);
        $this->assertObjectHasProperty('slaException', $entity);
    }

    /**
     * Test ID setter and getter
     */
    public function testIdGetter()
    {
        $pi = m::mock(PiEntity::class);
        $slaException = m::mock(SlaExceptionEntity::class);
        $entity = new Entity($pi, $slaException);
        
        // ID should be null initially (auto-generated by database)
        $this->assertNull($entity->getId());
    }

    /**
     * Test entity creation with relationships
     */
    public function testEntityWithRelationships()
    {
        $pi = m::mock(PiEntity::class);
        $slaException = m::mock(SlaExceptionEntity::class);
        
        $entity = new Entity($pi, $slaException);
        
        $this->assertSame($pi, $entity->getPi());
        $this->assertSame($slaException, $entity->getSlaException());
    }

    /**
     * Test JSON serialization includes expected fields
     */
    public function testJsonSerialization()
    {
        $pi = m::mock(PiEntity::class);
        $pi->shouldReceive('getId')->andReturn(1);
        
        $slaException = m::mock(SlaExceptionEntity::class);
        $slaException->shouldReceive('getId')->andReturn(2);
        $slaException->shouldReceive('getDescription')->andReturn('Test Exception');
        
        $entity = new Entity($pi, $slaException);

        $jsonData = $entity->jsonSerialize();
        
        $this->assertIsArray($jsonData);
        $this->assertArrayHasKey('id', $jsonData);
    }

    /**
     * Test bundle serialization
     */
    public function testBundleSerialization()
    {
        $pi = m::mock(PiEntity::class);
        $pi->shouldReceive('serialize')->andReturn(['id' => 1]);
        
        $slaException = m::mock(SlaExceptionEntity::class);
        $slaException->shouldReceive('serialize')->andReturn(['id' => 2, 'description' => 'Test Exception']);
        
        $entity = new Entity($pi, $slaException);

        $bundle = [];
        $serialized = $entity->serialize($bundle);
        
        $this->assertIsArray($serialized);
        $this->assertArrayHasKey('id', $serialized);
    }

    /**
     * Test constructor requires both parameters
     */
    public function testConstructorRequiresParameters()
    {
        $this->expectException(\ArgumentCountError::class);
        new Entity();
    }

    /**
     * Test entity creation and validation
     */
    public function testEntityCreation()
    {
        $pi = m::mock(PiEntity::class);
        $slaException = m::mock(SlaExceptionEntity::class);
        
        $entity = new Entity($pi, $slaException);
        
        // Verify all properties are set correctly
        $this->assertNull($entity->getId()); // ID is null until persisted to database
        $this->assertInstanceOf(PiEntity::class, $entity->getPi());
        $this->assertInstanceOf(SlaExceptionEntity::class, $entity->getSlaException());
    }
}
