<<?php /* Template Hack */ ?>?php

declare(strict_types=1);

namespace <?php echo $namespace; ?>;

use Doctrine\ORM\Mapping as ORM;

/**
 * <?php echo $className; ?> Entity
 */
#[ORM\Table(name: '<?php echo $tableName; ?>')]
<?php if (isset($repositoryClass) && $repositoryClass !== null): ?>
#[ORM\Entity(repositoryClass: \<?php echo ltrim($repositoryClass, '\\'); ?>::class)]
<?php else: ?>
#[ORM\Entity]
<?php endif; ?>
class <?php echo $className; ?> extends <?php echo $abstractClassName; ?>

{
}
