<?php
//print_r($this->sectionData);
?>
<div class="case-summary">
    <div class="case-summary__header">
        <h5><?php echo $this->translate('case-summary'); ?></h5>
    </div>
    <ul class="case-summary__list">
        <li class="summary__item">
            <b><?php echo $this->translate('licence-number-full') ?></b><?php echo $this->escapeHtml($this->sectionData['licNo']); ?>
        </li>
        <li class="summary__item">
            <b><?php echo $this->translate('operator-name') ?></b><?php echo $this->escapeHtml($this->sectionData['name']); ?>
        </li>
        <li class="summary__item">
            <b><?php echo $this->translate('MLH') ?></b><?php echo $this->escapeHtml($this->sectionData['isMlh']); ?>
        </li>
        <li class="summary__item">
            <b><?php echo $this->translate('business-type') ?></b>
                <?php echo !empty($this->sectionData['sicCode']) ? $this->translate('sic_code.'.$this->escapeHtml($this->sectionData['sicCode']['id'])) : ''; ?>
        </li>
        <li class="summary__item">
            <b><?php echo $this->translate('licence-type') ?></b><?php echo $this->escapeHtml($this->sectionData['licenceType']['id']); ?>
        </li>
        <li class="summary__item">
            <b><?php echo $this->translate('v-auth-t-auth') ?></b>
                <?php
                if ($this->sectionData['authorisedVehicles']) {
                    echo $this->escapeHtml($this->sectionData['authorisedVehicles'].' vehicles');
                }
                if ($this->sectionData['authorisedTrailers']) {
                    echo $this->escapeHtml(', '.$this->sectionData['authorisedTrailers'].' trailers');
                }
                ?>
        </li>
        <li class="summary__item">
            <b><?php echo $this->translate('start-date') ?></b><?php echo date('d/m/Y', strtotime($this->sectionData['startDate']));  ?>
        </li>
        <li class="summary__item">
            <b><?php echo $this->translate('vehicles-in-posession') ?></b>TBD
        </li>
        <li class="summary__item">
            <b><?php echo $this->translate('entity-type') ?></b><?php echo $this->escapeHtml($this->sectionData['type']['id']); ?>
        </li>
        <li class="summary__item">
            <b><?php echo $this->translate('ecmsNo') ?></b><?php echo $this->escapeHtml($this->sectionData['ecmsNo']); ?>
        </li>
        <li class="summary__item">
            <b><?php echo $this->translate('case-summary') ?></b><?php echo $this->escapeHtml($this->sectionData['description']); ?>
        </li>
    </ul>
</div>