<div class="three-quarters">
    <h2><?php echo $this->translate('submission-actions'); ?></h2>	
    <ul class="submission-actions">
        <?php 
        foreach($data as $key => $action) :
        ?>
        <li class="submission-actions__item">
            <h3><?php echo $this->escapeHtml(ucfirst($action['submissionActionType'])); ?>: <?php echo $this->escapeHtml($action['submissionActionStatus']); ?></h3>
            <p><?php echo $this->escapeHtml($action['comment']); ?></p>
            <?php 
                if (!empty($action['piReasons'])) {
            ?>        
                <p><strong><?php echo $this->translate('Legislation'); ?></strong><br />
                <?php for ($i=0; $i<count($action['piReasons']); $i++): ?>
                <?php echo $this->escapeHtml($action['piReasons'][$i]['description']); ?><?php if ($i != count($action['piReasons'])-1): ?>, <?php endif; ?>
                <?php endfor; ?>
                </p>
            <?php } ?>
            
            <ul class="summary__list">
                <li class="summary__item"><b>From</b><?php echo $this->escapeHtml(ucfirst($action['userSender']['name'])); ?></li>
                <li class="summary__item"><b>To</b><?php echo $this->escapeHtml(ucfirst($action['userRecipient']['name'])); ?></li>
                <li class="summary__item"><b>Created</b><?php echo date('d/m/Y', strtotime($action['createdOn'])); ?></li>
                <li class="summary__item"><b>Urgent</b><?php echo $this->escapeHtml(ucfirst($action['urgent'])); ?></li>
            </ul>
        </li>
        <?php    
        endforeach; 
        ?>
    </ul>
</div>