<div class="table__wrapper">
    <table>
        <thead>
            <tr>
                <th><?php echo $this->translate('last-name'); ?></th>
                <th><?php echo $this->translate('first-name'); ?></th>
                <th><?php echo $this->translate('dob'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php
            foreach ($this->sectionData as $organisationOwner) :
        ?>
            <tr>
                <td><?php echo $this->escapeHtml($organisationOwner['lastName']); ?></td>
                <td><?php echo $this->escapeHtml($organisationOwner['firstName']); ?></td>
                <td><?php echo date('d/m/Y', strtotime($organisationOwner['dob']));  ?></td>
            </tr>
        <?php
            endforeach;
        ?>
        </tbody>
    </table>
</div>