<div class="table__header">
    <?php if ($heading != 'case-summary-info') : ?>
        <h3><?php echo $this->translate($heading); ?></h3>
    <?php endif; ?>
</div>
<div>
<?php
$routeParams['action'] = 'addnote';
echo $data;
?>
</div>
<div>
    <form method="POST" action=<?php echo $this->url('submission', $routeParams); ?>>
        <input type="hidden" name="section" value="<?php echo $heading;  ?>" />
        <div class="actions-container">
            <input id="recommend" class="action--primary" name="recommend" type="submit" value="Add Note">
        </div>
    </form>
</div>