<div class="table__wrapper">
    <table>
        <thead>
            <tr>
                <th><?php echo $this->translate('last-name'); ?></th>
                <th><?php echo $this->translate('first-name'); ?></th>
                <th><?php echo $this->translate('dob'); ?></th>
                <th><?php echo $this->translate('qualification-type'); ?></th>
                <th><?php echo $this->translate('other-licences-or-apps'); ?></th>
                <th><?php echo $this->translate('internal-external'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php
            foreach ($this->sectionData as $transportManagerLicence) :
        ?>
            <tr>
                <td><?php echo $this->escapeHtml($transportManagerLicence['lastName']); ?></td>
                <td><?php echo $this->escapeHtml($transportManagerLicence['firstName']); ?></td>
                <td><?php echo date('d/m/Y', strtotime($transportManagerLicence['dob']));  ?></td>
                <td><?php echo $this->escapeHtml($transportManagerLicence['qualifications']); ?></td>
                <td>-<?php //echo $this->escapeHtml($transportManagerLicence['qualification']); ?></td>
                <td><?php echo $this->escapeHtml($transportManagerLicence['tmType']); ?></td>
            </tr>
        <?php
            endforeach;
        ?>
        </tbody>
    </table>
</div>