<div class="js-body">
    <?php
        echo $this->render(
            '/partials/page-header.phtml',
            array(
                'pageTitle'=> $this->translate('ebsr-upload-result-title'),
                'pageSubTitle' => $ebsrSubmission['document']['description']
            )
        );

        if ($ebsrSubmission['isBeingProcessed']) {
            $childView = './partial/detail-processing';
        } elseif ($ebsrSubmission['isFailure']) {
            $childView = './partial/detail-failed';
        } elseif ($ebsrSubmission['isSuccess']) {
            $childView = './partial/detail-success';
        } else {
            echo'There is no additional information for this file'; //very basic handling of legacy until data is cleansed
            return;
        }

        $documentUrl = $this->url(
            'getfile',
            [
                'identifier' => $ebsrSubmission['document']['id']
            ]
        );
    ?>

    <div class="row">
        <div class="two-thirds">
            <?php echo $this->render($childView, ['documentUrl' => $documentUrl, 'ebsrSubmission' => $ebsrSubmission]); ?>
        </div>
    </div>

</div>
