<p>Rwy'n deall, drwy lofnodi'r datganiad hwn:</p>
<ul class="list--bullet">
  <li>Rwy'n cadarnhau bod y manylion ar fy nhrwydded yn gywir.</li>
  <li>Rwyf wedi cyflwyno newidiadau i ddiweddaru unrhyw fanylion trwydded sy'n anghywir</li>
  <li>Rwyf wedi darllen a deall yr amodau a gofnodwyd ar y drwydded.</li>
  <li>Rwyf wedi darllen, deall a derbyn yr ymrwymiadau a gofnodwyd ar fy nhrwydded.</li>
  <li>Mewn perthynas â phob canolfan weithredu a bennir, na fydd nifer y cerbydau a nifer y trelars a gedwir yno yn fwy na'r niferoedd uchaf a awdurdodwyd ym mhob canolfan weithredu (a fydd yn cael eu nodi ar y drwydded);</li>
  %s
  <li>Rhaid i mi allu profi bod gennyf drefniant ffurfiol ar gyfer mynediad bob amser i o leiaf un cerbyd sydd wedi'i gofrestru neu mewn cylchrediad ym Mhrydain Fawr. Gallai hyn fod drwy nodi cerbyd i'w ddefnyddio o dan drwydded gweithredwr neu drwy ddangos ar gais fod gen i (deiliad y drwydded) gerbyd ar gael, fel y gellir naill ai berchen yn llwyr ar gerbydau neu eu dal o dan drefniant llogi-brynu, llogi / prydlesu neu fath arall o drefniant ffurfiol;</li>
  <li>Mae gen i sefydliad ym Mhrydain Fawr (GB) gyda safle lle rwy'n cadw dogfennau busnes craidd. Mae'r rhain yn cynnwys (o leiaf) dogfennau cyfrifyddu a rheoli personél a data ar amser gyrru a gorffwys. Rwy'n deall na chaniateir defnyddio Blwch Post na chyfeiriad trydydd parti.</li>
</ul>
%s
