<p>Cyhoeddir y drwydded yn amodol ar yr amodau canlynol:</p>
<p>a) Bydd deiliad y drwydded, o fewn 28 diwrnod i'r digwyddiad, yn hysbysu'r comisiynydd traffig o unrhyw:</p>
<ul class="list--bullet">
  <li>Newidiadau yn y trefniadau cynnal a chadw ac archwilio diogelwch;</li>
  <li>Newidiadau yn y gallu i sicrhau bod cerbydau awdurdodedig yn cael eu gweithredu'n ddiogel ac nad ydynt yn achosi perygl i'r cyhoedd;</li>
  <li>Newidiadau ym mherchnogaeth y busnes gan gynnwys trefniadau partneriaeth. Nid oes angen hysbysu newidiadau mewn cyfranddaliadau cwmni oni bai eu bod yn achosi newid yn rheolaeth y Cwmni;</li>
  <li>Digwyddiadau sy'n effeithio ar:
    <ul class="list--bullet">
      <li>Enw da deiliad y drwydded a'r rheolwr trafnidiaeth, yn benodol, euogfarnau perthnasol fel y'u diffinnir yn atodlen 3 i Ddeddf 1995 (mae hyn yn cynnwys cyhoeddi hysbysiad cosb sefydlog neu gynnig amodol o dan Ran 3 o Ddeddf Troseddwyr Traffig Ffyrdd 1988);</li>
      <li>Cymhwysedd proffesiynol deiliad y drwydded a/neu'r rheolwr trafnidiaeth;</li>
      <li>Y gofyniad i ddeiliad y drwydded fod o sefyllfa ariannol briodol (gan gynnwys manylion unrhyw fethdaliad, diddymiad, atafaelu ystâd neu fynd i weinyddiaeth deiliad penodiad derbynnydd, rheolwr neu ymddiriedolwr);</li>
      <li>Y gofyniad i gael sefydliad effeithiol a sefydlog ym Mhrydain Fawr sef; unrhyw newid i gyfeiriad penodedig y sefydliad, a'r gofyniad i gael mynediad bob amser i o leiaf un cerbyd nwyddau sydd wedi'i gofrestru neu mewn cylchrediad ym Mhrydain Fawr.</li>
    </ul>
  </li>
</ul>
<p>b) Mewn perthynas â phob canolfan weithredu benodedig, na fydd nifer y cerbydau modur awdurdodedig a nifer y trelars awdurdodedig a gedwir yno yn fwy na'r niferoedd uchaf a gofnodwyd yn erbyn y ganolfan weithredu ar y drwydded hon.</p>
<p>Bydd yr ymrwymiadau canlynol yn cael eu cofnodi ar y drwydded:</p>
<ul class="list--bullet">
  <li>Mae'r cyfreithiau sy'n ymwneud â gyrru a gweithredu cerbydau a threlars a ddefnyddir o dan y drwydded yn cael eu dilyn;</li>
  <li>Mae'r rheolau ar oriau gyrwyr a thacograffau yn cael eu dilyn a chedwir cofnodion priodol am o leiaf 12 mis, a bod y rhain ar gael ar gais;</li>
  <li>Nid yw cerbydau a threlars yn cael eu gorlwytho na'u gweithredu gyda llwyth ansicr;</li>
  <li>Mae cerbydau'n gweithredu o fewn terfynau cyflymder;</li>
  <li>Cerbydau a threlars, gan gynnwys cerbydau wedi'u llogi a threlars, yn cael eu cadw mewn cyflwr addas a gwasanaethadwy;</li>
  <li>Mae gyrwyr yn rhoi gwybod ar unwaith am unrhyw ddiffygion neu symptomau diffygion a allai atal gweithrediad diogel cerbydau a/neu drelars, a bod unrhyw ddiffygion yn cael eu cofnodi'n ysgrifenedig;</li>
  <li>Cedwir cofnodion (am o leiaf 15 mis) o bob adroddiad diffyg gyrwyr, pob archwiliad diogelwch, cynnal a chadw arferol ac atgyweiriadau i gerbydau a threlars, ac mae'r rhain ar gael ar gais.</li>
  <li>Ni ddefnyddir canolfan weithredu heb awdurdod mewn unrhyw ardal draffig.</li>
  <li>Gall unrhyw fethiant i gydymffurfio â'r datganiadau a wneir i gael trwydded, amodau neu ymrwymiadau a gofnodwyd ar y drwydded arwain at ddirymu, atal neu gwtogi'r drwydded; a bod methu â chydymffurfio â'r amodau yn drosedd.</li>
</ul>
