<p class="govuk-body">
  Rwy'n datgan bod y datganiadau ffeithiol neu ddisgwyliad a ddarparwyd i gefnogi'r cais hwn yn gywir.
</p>
<ul class="govuk-list govuk-list--bullet">
  <li>Rwy'n deall mai cyfrifoldeb yr ymgeisydd yw sicrhau bod ganddo'r profiad a'r hyfforddiant gofynnol cyn gwneud cais am drwydded gweithredwr. Rwy'n cadarnhau, drwy lofnodi'r cais hwn, fy mod yn deall cyfrifoldebau a gofynion dal trwydded gweithredwr cerbyd nwyddau a byddaf yn sicrhau y byddaf yn cael y wybodaeth ddiweddaraf am y gofynion hynny;</li>
  <li>
    Rwy'n deall bod yn rhaid i mi hysbysu'r comisiynydd traffig o unrhyw gollfarn berthnasol i'r ymgeisydd neu'r rheolwr trafnidiaeth a gafwyd ers gwneud y cais a bod methu â gwneud hynny yn drosedd;
  </li>
  <li>Rwy'n deall bod rhaid hysbysu'r comisiynydd traffig am unrhyw newidiadau sy'n digwydd wrth ystyried cais, gwybodaeth sy'n newid yn sylweddol o'r hyn a ddatganwyd yn wreiddiol pan gyflwynwyd y cais gyntaf gan gynnwys colli rheolwr trafnidiaeth;</li>
  <li>Rwy'n deall, os cyhoeddir trwydded, y bydd yn awdurdodi uchafswm nifer o gerbydau y gellir eu defnyddio oddi tani ar unrhyw adeg gyda'r ddisg ofynnol wedi'i harddangos yn gywir, a'i bod yn drosedd defnyddio cerbyd heb i ddisg gael ei harddangos yn gywir;</li>
  <li>Rhaid i mi allu profi bod gennyf drefniant ffurfiol ar gyfer mynediad bob amser i o leiaf un cerbyd sydd wedi'i gofrestru neu mewn cylchrediad ym Mhrydain Fawr. Gallai hyn fod trwy nodi cerbyd i'w ddefnyddio o dan drwydded gweithredwr neu drwy ddangos ar gais fod gennyf (deiliad y drwydded) gerbyd ar gael, fel y gellir naill ai berchen yn llwyr ar gerbydau neu eu dal o dan hurbrynu, llogi / prydlesu neu fath arall o drefniant ffurfiol;</li>
  <li>
    Mae gennyf sefydliad ym Mhrydain Fawr (GB) gyda safle lle rwy'n cadw dogfennau busnes craidd. Mae'r rhain yn cynnwys (o leiaf) dogfennau cyfrifyddu a rheoli personél a data ar amser gyrru a gorffwys. Rwy'n deall na chaniateir defnyddio Blwch Post na chyfeiriad trydydd parti;
  </li>
  <li>
    Ni ddefnyddir canolfan weithredu heb awdurdod mewn unrhyw ardal draffig.
  </li>
</ul>
<p class="govuk-body">Rwy'n deall, drwy gyflwyno'r cais hwn, fy mod yn derbyn y bydd yr ymrwymiadau canlynol yn cael eu cofnodi ar y drwydded;</p>
<ul class="govuk-list govuk-list--bullet">
  <li>
    Cydymffurfir â'r cyfreithiau sy'n ymwneud â gyrru a gweithredu cerbydau a ddefnyddir o dan y drwydded hon;
  </li>
  <li>
    Cydymffurfir â'r rheolau ar oriau gyrwyr a thacograffau a chedwir cofnodion priodol am o leiaf 12 mis, a bod y rhain ar gael ar gais;
  </li>
  <li>
    Nid yw cerbydau'n cludo mwy na'r nifer a ganiateir o deithwyr;
  </li>
  <li>
    Bydd cerbydau'n gweithredu o fewn terfynau cyflymder;
  </li>
  <li>
    Cedwir cerbydau, gan gynnwys cerbydau wedi'u llogi, mewn cyflwr addas a gwasanaethadwy;
  </li>
  <li>
    Mae gyrwyr yn rhoi gwybod ar unwaith am unrhyw ddiffygion neu symptomau diffygion a allai atal gweithrediad diogel cerbydau, a bod unrhyw ddiffygion yn cael eu cofnodi'n ysgrifenedig;
  </li>
  <li>
    Cedwir cofnodion (am o leiaf 15 mis) o bob adroddiad diffyg gyrwyr, pob archwiliad diogelwch, cynnal a chadw arferol ac atgyweiriadau i gerbydau, a darperir y rhain ar gais.
  </li>
</ul>
<p class="govuk-body">
  Rwy'n deall, os rhoddir trwydded, y bydd yn ddarostyngedig i'r amodau canlynol:
</p>
<ol class="govuk-list govuk-list--number">
  <li>
    <strong>Newid amgylchiadau</strong>
    <p class="govuk-body">Os bydd newidiadau i'r canlynol;</p>
    <ol class="govuk-list">
      <li>
        a) cyfeiriad busnes (h.y. y cyfeiriad effeithiol y dylid anfon gohebiaeth ato);
      </li>
      <li>
        b) y gofyniad i gael sefydliad effeithiol a sefydlog ym Mhrydain Fawr, gan gynnwys cyfeiriad y sefydliad neu'r gofyniad i gael mynediad at gerbyd;
      </li>
      <li>
        c) cyfeiriad(au) y ganolfan(nau) gweithredu;
      </li>
      <li>
        ch) y trefniadau ar gyfer archwilio/cynnal a chadw cerbydau;
      </li>
      <li>
        e) perchnogaeth y busnes gan gynnwys trefniadau partneriaeth ac yn y bobl sy'n dal cyfranddaliadau mewn cwmni, sy'n achosi newid yn rheolaeth y cwmni.
      </li>
    </ol>
  </li>
  <li>
    <strong>Rheolwr trafnidiaeth</strong>
    <p class="govuk-body">
      Os bydd unrhyw berson a enwir ar y drwydded fel rheolwr trafnidiaeth yn peidio â chael ei gyflogi fel rheolwr trafnidiaeth ar gyfer y drwydded hon
    </p>
  </li>
  <li>
    <strong>Methdaliad neu ddiddymiad</strong>
    <p class="govuk-body">
      Os bydd y deiliad yn fethdalu neu'n cael ei ddiddymu, neu os bydd ei ystâd yn cael ei hatafaelu neu os bydd y deiliad yn mynd i weinyddiaeth neu os bydd derbynnydd, rheolwr neu ymddiriedolwr ei fusnes cludo teithwyr ffordd yn cael ei benodi
    </p>
  </li>
  <li>
    <strong>Collfarnau perthnasol</strong>
    <p class="govuk-body">Rhaid i ddeiliad y drwydded hysbysu'r comisiynydd traffig yn ysgrifenedig o</p>
    <ol class="govuk-list">
      <li>a) unrhyw gollfarn yn erbyn deiliad y drwydded;</li>
      <li>b) lle mae'r drwydded yn cael ei dal gan bersonau mewn partneriaeth o unrhyw gollfarn yn erbyn pob person o'r fath; a</li>
      <li>c) unrhyw gollfarn yn erbyn unrhyw swyddog, gweithiwr neu asiant y deiliad am drosedd a gyflawnwyd wrth gyflawni busnes cludo teithwyr ffordd y deiliad.</li>
    </ol>
    <p class="govuk-body">
      At ddibenion adran 91 (1) a (2) mae cyhoeddi hysbysiad cosb benodedig neu gynnig amodol o dan Ran 3 o Ddeddf Troseddwyr Traffig Ffyrdd 1988 i'w drin fel collin perthnasol.
    </p>
  </li>
  <li>
    <strong>Digwyddiadau sy'n effeithio ar:</strong>
    <p class="govuk-body">
      Y gofyniad i fod o enw da;<br>
      Y gofyniad i fod o sefyllfa ariannol briodol.<br>
      Y gofyniad o ran cymhwysedd proffesiynol;<br>
      Y gofyniad i gael sefydliad effeithiol a sefydlog ym Mhrydain Fawr sef;<br>
    </p>
    <ol class="govuk-list">
      <li>a) unrhyw newidiadau i gyfeiriad penodedig y sefydliad, a</li>
      <li>b) y gofyniad i gael mynediad bob amser at o leiaf un cerbyd gwasanaeth cyhoeddus sydd wedi'i gofrestru neu mewn cylchrediad ym Mhrydain Fawr.</li>
    </ol>
  </li>
  <li>
    <strong>Gwybodaeth am gerbydau</strong>
    <p class="govuk-body">Rhaid i ddeiliad y drwydded adrodd i'r Ysgrifennydd Gwladol cyn gynted ag y bo'n ymarferol;</p>
    <ol class="govuk-list">
      <li>a) unrhyw fethiant neu ddifrod i gerbyd sy'n eiddo i'r deiliad y cyfrifir ei fod yn effeithio ar ddiogelwch ei deithwyr neu bersonau sy'n defnyddio'r ffordd; a</li>
      <li>b) unrhyw newid a wneir yn strwythur neu offer sefydlog unrhyw gerbyd sy'n eiddo iddo.</li>
    </ol>
  </li>
  <li>
    <strong>Gofyniad i ddarparu gwybodaeth ychwanegol</strong>
    <p class="govuk-body">
      Rhaid i ddeiliad y drwydded ddarparu i'r comisiynydd traffig unrhyw wybodaeth arall y gellir ei gwneud yn rhesymol ofynnol am y cerbydau sy'n eiddo i'r deiliad neu am unrhyw newid sylweddol yn ei amgylchiadau.
    </p>
  </li>
</ol>
<p class="govuk-body">
  Gall unrhyw fethiant i gydymffurfio â'r datganiadau a wneir i gael trwydded, amodau neu ymrwymiadau a gofnodwyd ar y drwydded arwain at ddirymu'r drwydded, ei hatal neu amod i leihau nifer y cerbydau a awdurdodwyd; a bod methu â chydymffurfio â'r amodau yn drosedd.
</p>
%s
