<?php 
?>
    <div>
        <h1>
            <?php echo $this->resourceHelper('your-business-type-of-business-header'); ?>
        </h1>
        
        <?php echo $this->formRow($this->businessDetailsForm->get('business[entityTypes]')); ?>
        
        <h2>
            <?php echo $this->resourceHelper('your-business-company-details-header'); ?>
        </h2>
        
        <?php echo $this->formRow($this->businessDetailsForm->get('business[companyNumber]')); ?>
        <?php echo $this->formRow($this->businessDetailsForm->get('organisationSearchBtn')); ?>

        <div class="instruction-text">
            <p><?php echo $this->resourceHelper('your-business-form-instruction-company-number-text'); ?></p>
        </div>

        <?php echo $this->formRow($this->businessDetailsForm->get('business[companyName]')); ?>
        <div class="instruction-text">
            <p><?php echo $this->resourceHelper('your-business-form-instruction-company-name-text'); ?></p>
        </div>
        
        <h2>
            <?php echo $this->resourceHelper('your-business-trading-names-header'); ?>
        </h2>
                
        <div class="" id="tradingNameContainer">

            <div class="">
                <?php echo $this->formRow($businessDetailsForm->get('business[tradingNameId]')); ?>
                <span class="trading-names-collection"><?php
                    echo $this->formCollection($businessDetailsForm->get('business[tradingNames]'));
                ?></span>
                <div id="tradingNameText" class=""></div>
            </div>
            <div class="">
                <?php echo $this->formButton($businessDetailsForm->get('tradingAddAnother')); ?>
            </div>
        </div>
        <div class="instruction-text">
            <p><?php echo $this->resourceHelper('your-business-form-instruction-trading-name-text'); ?></p>
        </div>

        <h2>
            <?php echo $this->resourceHelper('your-business-types-of-business-header'); ?>
        </h2>
        
        <?php echo $this->formRow($this->businessDetailsForm->get('business[businessTypes]')); ?>


        
        
    </div>
