<?php 
?>
    <div>
        <h1>
            <?php echo $this->resourceHelper('your-business-type-of-business-header'); ?>
        </h1>
        
        
        <label for="<?php echo $businessDetailsForm->get('entityType')->getAttribute('id');?>"><?php echo $this->resourceHelper('your-business-form-label-type-of-business'); ?></label>
        <?php echo $this->formRow($businessDetailsForm->get('entityType')); ?>
     
        
        <h2><?php echo $this->resourceHelper('your-business-company-details-header'); ?></h2>
        
        <label for="<?php echo $businessDetailsForm->get('companyNumId')->getAttribute('id');?>"><?php echo $this->resourceHelper('your-business-form-label-registered-company-number'); ?></label>
        <?php echo $this->formRow($businessDetailsForm->get('companyNumId')); ?>
        <?php echo $this->formButton($businessDetailsForm->get('organisationSearchBtn'), $this->resourceHelper('common-button-find')); ?>

        <div class="instruction-text">
            <p><?php echo $this->resourceHelper('your-business-form-instruction-company-number-text'); ?></p>
        </div>

        <?php echo $this->formRow($businessDetailsForm->get('operatorId')); ?>
        <label for="<?php echo $businessDetailsForm->get('operatorName')->getAttribute('id');?>"><?php echo $this->resourceHelper('your-business-form-label-registered-company-name'); ?></label>
        <?php echo $this->formRow($businessDetailsForm->get('operatorName')); ?>
        <div class="instruction-text">
            <p><?php echo $this->resourceHelper('your-business-form-instruction-company-name-text'); ?></p>
        </div>
        
        <h2>
            <?php echo $this->resourceHelper('your-business-trading-names-header'); ?>
        </h2>
                
        <div class="" id="tradingNameContainer">

            <div class="">
                <label for=""><?php echo $this->resourceHelper('your-business-form-label-trading-name'); ?></label>
                <?php echo $this->formRow($businessDetailsForm->get('business[tradingNameId]')); ?>
                <span class="trading-names-collection"><?php
                    echo $this->formCollection($businessDetailsForm->get('business[tradingNames]'));
                ?></span>
                <div id="tradingNameText" class=""></div>
            </div>
            <div class="">
                <?php echo $this->formButton($businessDetailsForm->get('tradingAddAnother'), $this->resourceHelper('common-button-add-another')); ?>
            </div>
        </div>
        <div class="instruction-text">
            <p><?php echo $this->resourceHelper('your-business-form-instruction-trading-name-text'); ?></p>
        </div>

        <h2>
            <?php echo $this->resourceHelper('your-business-types-of-business-header'); ?>
        </h2>

        <label for=""><?php echo $this->resourceHelper('your-business-form-label-types-of-business'); ?></label>
        <?php echo $this->formRow($this->businessDetailsForm->get('business[businessTypes]')); ?>


        
        
    </div>
