<?php 
$this->placeholder('body-class')->set("full-page");

?>
<?php $businessDetailsForm->prepare(); ?>

<?php //echo $this->partial('OlcsSelfserve/common/errorMessages', array('messages' => $messages)); ?>
<?php echo $this->form()->openTag($businessDetailsForm); ?>

<div id="businessDetailsDiv">
    <div>
        <?php echo $this->resourceHelper('your-business-header'); ?>
    </div>

    <?php echo $this->partial('OlcsSelfserve/application/forms/business-details-form', array(
        'businessDetailsForm' => $businessDetailsForm
    ));
    
?>
    <div>
        <button id="cancelbutton" name="cancel" class="" type="button"><?php echo $this->resourceHelper('common-button-cancel'); ?></button>
        <button id="submitbutton" name="submit" class="" type="submit"><?php echo $this->resourceHelper('common-button-save-and-next'); ?></button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
