<?php
$appeal = $this->placeholder('appeal')->getValue();

if (empty($appeal)){
    echo $this->render('partials/read-only/empty',
        [
            'header' => $this->navigation('navigation')->findOneBy('active', 1)->getLabel(),
            'helpText' => 'There is currently no appeal',
            'url' => $this->url('case_appeal', ['case' => $case['id'], 'action' => 'add'], [], false),
            'label' => 'Add appeal'
        ]
    );
} else {
    echo $this->render('partials/read-only/main',
        [
            'header' => $this->navigation('navigation')->findOneBy('active', 1)->getLabel(),
            'actions' => [
                [
                    'label' => 'Edit appeal',
                    'url' => $this->url(
                        'case_appeal',
                        ['case' => $case['id'], 'appeal' => $appeal['id'], 'action' => 'edit'],
                        [],
                        false
                    )
                ]
            ],
            'multiItems' => [
                0 => [
                    ['label' => 'Appeal number', 'value' => $appeal['appealNo']],
                    ['label' => 'Appeals deadline', 'date' => $appeal['deadlineDate']],
                    ['label' => 'Date of appeal', 'date' => $appeal['appealDate']],
                    ['label' => 'Reason', 'value' => (isset($appeal['reason']['description']) ?
                        $appeal['reason']['description'] : '')],
                    ['label' => 'Outline ground', 'value' => $appeal['outlineGround'], 'class' => 'full-width']
                ],
                1 => [
                    ['label' => 'Date of appeal hearing', 'date' => $appeal['hearingDate']],
                    ['label' => 'Date of decision', 'date' => $appeal['decisionDate']],
                    ['label' => 'Papers due at tribunal', 'date' => $appeal['papersDueDate']],
                    ['label' => 'Papers sent date', 'date' => $appeal['papersSentDate']],
                    ['label' => 'Outcome', 'value' => (isset($appeal['outcome']['description']) ?
                        $appeal['outcome']['description'] : '')],
                    ['label' => 'TM case Id', 'value' => $appeal['tmCaseId']],
                    ['label' => 'Is withdrawn', 'value' => (empty($appeal['withdrawnDate']) ? 'N' : 'Y')],
                    ['label' => 'Withdrawn date', 'date' => $appeal['withdrawnDate']]
                ],
                2 => [
                    ['label' => 'Comments', 'value' => $appeal['comment'], 'class' => 'full-width']
                ]
            ]
        ]
    );

    if (empty($appeal['withdrawnDate'])) {
        if (!empty($stayRecords['stay_t_tc'][0]))
        {
            echo $this->partial('case/hearing-appeal/stay-details.phtml', $stayRecords['stay_t_tc'][0]);
        } else {
            echo $this->render('partials/read-only/empty',
                [
                    'header' => 'Traffic Commissioner / Transport Regulator stay',
                    'helpText' => 'There is currently no Traffic Commissioner / Transport Regulator stay',
                    'url' => $this->url(
                        'case_stay',
                        ['case' => $case['id'], 'action' => 'add', 'stayType' => 'stay_t_tc'],
                        [],
                        false
                    ),
                    'label' => 'Add stay'
                ]
            );
        }

        if (!empty($stayRecords['stay_t_ut'][0]))
        {
            echo $this->partial('case/hearing-appeal/stay-details.phtml', $stayRecords['stay_t_ut'][0]);
        } else {
            echo $this->render('partials/read-only/empty',
                [
                    'header' => 'Upper Tribunal stay',
                    'helpText' => 'There is currently no Upper tribunal stay',
                    'url' => $this->url(
                        'case_stay',
                        ['case' => $case['id'], 'action' => 'add', 'stayType' => 'stay_t_ut'],
                        [],
                        false
                    ),
                    'label' => 'Add stay'
                ]
            );
        }
    }
}
