<?php
$appeal = $this->placeholder('appeal')->getValue(); ?>

<h4><?php echo $this->translate($this->navigation('navigation')->findOneBy('active', 1)->getLabel()); ?>
    <?php
    if (empty($appeal)){
    ?>
    <a href="<?php echo $this->url(
        'case_appeal',
        [
            'case' => $case['id'],
            'action' => 'add'
        ], [], false); ?>" class="action--secondary
        right-aligned"><?php echo $this->translate('Add appeal'); ?></a>
</h4>

<?php
} else {
    ?>
    <a href="<?php echo $this->url(
        'case_appeal',
        [
            'case' => $case['id'],
            'appeal' => $appeal['id'],
            'action' => 'edit'
        ], [], false); ?>" class="action--secondary
        right-aligned"><?php echo $this->translate('Edit appeal'); ?></a>

    </h4>

    <div class="read-only">
        <dl>
            <dt><?php echo $this->translate('Appeal number');?></dt>
            <dd><?php echo isset($appeal['appealNo']) ? $appeal['appealNo'] : ''; ?></dd>
            <dt><?php echo $this->translate('Appeals deadline');?></dt>
            <dd><?php echo isset($appeal['deadlineDate']) ? $appeal['deadlineDate'] : ''; ?></dd>
            <dt><?php echo $this->translate('Date of appeal');?></dt>
            <dd><?php echo isset($appeal['appealDate']) ? $appeal['appealDate'] : ''; ?></dd>
            <dt><?php echo $this->translate('Reason');?></dt>
            <dd><?php echo isset($appeal['reason']['description']) ? $appeal['reason']['description'] : ''; ?></dd>
        </dl>

        <dl>
            <dt><?php echo $this->translate('Outline ground');?></dt>
            <dd class="three-quarters"><?php echo isset($appeal['outlineGround']) ? $appeal['outlineGround'] : '';
                ?></dd>
        </dl>
        <dl>
            <dt><?php echo $this->translate('Date of appeal hearing');?></dt>
            <dd><?php echo isset($appeal['hearingDate']) ? $appeal['hearingDate'] : ''; ?></dd>
            <dt><?php echo $this->translate('Date of decision');?></dt>
            <dd><?php echo isset($appeal['decisionDate']) ? $appeal['decisionDate'] : ''; ?></dd>

            <dt><?php echo $this->translate('Papers due at tribual');?></dt>
            <dd><?php echo isset($appeal['papersDueDate']) ? $appeal['papersDueDate'] : ''; ?></dd>
            <dt><?php echo $this->translate('Papers sent date');?></dt>
            <dd><?php echo isset($appeal['papersSentDate']) ? $appeal['papersSentDate'] : ''; ?></dd>
            <dt><?php echo $this->translate('Outcome');?></dt>
            <dd><?php echo isset($appeal['outcome']['description']) ? $appeal['outcome']['description'] : ''; ?></dd>

        </dl>
        <dl>
            <dt><?php echo $this->translate('Tm Case Id');?></dt>
            <dd><?php echo isset($appeal['tmCaseId']) ? $appeal['tmCaseId'] : ''; ?></dd>

            <dt><?php echo $this->translate('Is withdrawn');?></dt>
            <dd><?php echo $this->translate(empty($appeal['withdrawnDate']) ?
                    'N' : 'Y'); ?></dd>
            <dt><?php echo $this->translate('Withdrawn date');?></dt>
            <dd><?php echo isset($appeal['withdrawnDate']) ? $appeal['withdrawnDate'] : ''; ?></dd>
        </dl>
        <dl>
            <dt><?php echo $this->translate('Comments');?></dt>
            <dd class="three-quarters"><?php echo
                isset($appeal['comment']) ? $appeal['comment'] : '';
                ?></dd>
        </dl>
    </div>

    <?php
    if (!empty($stayRecords['stay_t_tc'][0]))
    {
        echo $this->partial('case/hearing-appeal/stay-details.phtml',
                $stayRecords['stay_t_tc'][0]);
    } else {
        echo $this->partial('case/hearing-appeal/stay-details.phtml',
            [
                'case' =>  $case,
                'stayType' => [
                    'id' => 'stay_t_tc',
                    'description' => 'Traffic commissioner / transport
                    regulator stay'
                ]
            ]
        );
    }
    ?>
    <?php
    if (!empty($stayRecords['stay_t_ut'][0]))
    {
        echo $this->partial('case/hearing-appeal/stay-details.phtml',
            $stayRecords['stay_t_ut'][0]);
    } else {
        echo $this->partial('case/hearing-appeal/stay-details.phtml',
            [
                'case' =>  $case,
                'stayType' => [
                    'id' => 'stay_t_ut',
                    'description' => 'Upper tribunal stay'
                ]
            ]
        );
    }
}
?>
