<?php
if (empty($noFormtags)) {
    $form->prepare();
    echo $this->form()->openTag($form);
}
?>
<div class="row form-section">
    <div class="col-md-4">
        <?php echo $this->formRow($form->get('caseId')); ?>
        <?php echo $this->formRow($form->get('licenceId')); ?>
    </div>
    <div class="col-md-4">
        <div class="col-md-11 required"><?php echo $this->formRow($form->get('submitActionTypes')); ?></div>
        <div class="col-md-1"></div>
    </div>
    <div class="col-md-4" style="text-align: right"><?php echo $this->formRow($form->get('submit')); ?></div>
</div>
<?php
if (empty($noFormtags)) {
    echo $this->form()->closeTag();
}
?>
