<div class="submission-section submission-operating-centre">
    <h2><?php echo $this->resourceHelper('submission-operating-centre-header'); ?></h2>
    <div class="table-responsive tableContent">
        <table class="olcs-list-table table table-striped">
            <thead>
                <tr>
                    <th class="text-muted"><span class="noWrap">
                        <?php echo $this->resourceHelper('address'); ?>
                    </span></th>
                    <th class="text-muted"><span class="noWrap">
                        <?php echo $this->resourceHelper('v-auth'); ?>
                    </span></th>
                    <th class="text-muted"><span class="noWrap">
                        <?php echo $this->resourceHelper('t-auth'); ?>
                    </span></th>
                    <th class="text-muted fluid"><span class="noWrap">
                        <?php echo $this->resourceHelper('conditions-and-undertakings'); ?>
                    </span></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($list as $row) : ?>
                    <tr>
                        <td><?php
                            echo $this->escapeHtml($row['address']['line1']) . '<br />';
                            echo empty($row['address']['line2']) ? '' : ($this->escapeHtml($row['address']['line2']) . '<br />');
                            echo empty($row['address']['line3']) ? '' : ($this->escapeHtml($row['address']['line3']) . '<br />');
                            echo empty($row['address']['line4']) ? '' : ($this->escapeHtml($row['address']['line4']) . '<br />');
                            echo $this->escapeHtml($row['address']['town']) . '<br />';
                            echo empty($row['address']['country']) ? '' : ($this->escapeHtml($row['address']['country']) . '<br />');
                            echo $this->escapeHtml($row['address']['postcode']);
                        ?></td>
                        <td><?php echo $this->escapeHtml($row['vehicle_auth']); ?></td>
                        <td><?php echo $this->escapeHtml($row['trailer_auth']); ?></td>
                        <td class="fluid"><?php echo nl2br($this->escapeHtml(implode("\n", $row['conditions']))); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="readmore">
            <?php echo $this->resourceHelper('readmore-pager', array(
                '@currentCount' => '<span class="current-count">' . count($list) . '</span>',
                '@totalCount' => '<span class="total-count">' . count($list) . '</span>',
            )); ?>
        </div>
    </div>
</div>
