<div class="submission-section submission-person-owner">
    <h2><?php echo $this->escapeHtml($header); ?></h2>
    <div class="table-responsive tableContent">
        <table class="olcs-list-table table table-striped">
            <thead>
                <tr>
                    <th class="text-muted"><span class="noWrap">
                        <?php echo $this->resourceHelper('last-name'); ?>
                    </span></th>
                    <th class="text-muted"><span class="noWrap">
                        <?php echo $this->resourceHelper('first-name'); ?>
                    </span></th>
                    <th class="text-muted fluid"><span class="noWrap">
                        <?php echo $this->resourceHelper('dob'); ?>
                    </span></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($list as $row) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml( $row['lastName'] ); ?></td>
                        <td><?php echo $this->escapeHtml( $row['firstName']); ?></td>
                        <td class="fluid"><?php echo $this->simpleDateFormat($row['dob'], 'd/m/Y'); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="readmore">
            <?php echo $this->resourceHelper('readmore-pager', array(
                '@currentCount' => '<span class="current-count">' . count($list) . '</span>',
                '@totalCount' => '<span class="total-count">' . count($list) . '</span>',
            )); ?>
        </div>
    </div>
</div>
