<?php
    echo $this->render(
        '/partials/page-header.phtml',
        array(
        'pageTitle' => 'Your business',
        // 'pageSubTitle'=> 'Tell us about the type of licence you are applying for'
        )
    );
?>

<div class="two-thirds">
<?php
    echo $this->partial('self-serve/forms/business-type', array(
        'form' => $form,
    ));
?>
<a href="<?php echo $this->url('selfserve/licence-type', ['step' => 'operator-location'], null, true); ?>">Back</a>
</div><!-- end .two-thirds -->