<?php

$guidanceMessage = $this->placeholder('guidance');

if (!empty($guidanceMessage)) {
    foreach ($guidanceMessage as $message):
        ?>
        <div class="guidance">
            <p><?php echo $this->translate($message); ?></p>
        </div>
    <?php
    endforeach;
}

if (isset($sectionText)) {
    ?><p><?php echo $this->translate($sectionText); ?></p><?php
}

if (isset($table)) {
    echo $table;
}

if (isset($form)) {
    $form->prepare();
    echo $this->formErrors($form);
    echo $this->form($form);
}
