<?php
echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->pageTitle(),
    ]
);
?>

<div class="row">
  
  <div class="two-thirds">
    
    <div class="article">
      <p><?php echo $this->translate('user-registration.page.account-created.text'); ?></p>
    </div>
  
    <div class="actions-container">
        <?php echo $this->link($this->url('index'), 'back-to-home'); ?>
    </div>
    
  </div>
  
</div>
