<?php

echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->pageTitle(),
        'pageHeaderText' =>
          $this->translateReplace(
            'user-registration.page.check-email-consultant-inset.content',
            [
              $this->consultantEmailAddress,
              $this->operatorEmailAddress
            ]
          ),
        'pageHeaderTextEscape' => false,
    ]
);
?>

<div class="row">

  <div class="two-thirds">
    <div class="article">
      <p>
          <?php echo $this->translateReplace(
                'user-registration.page.check-email-consultant.content',
                [
                    $this->url('auth/login/GET')
                ]
            ); ?>
      </p>
      <p><a href="<?php echo $this->url('auth/login/GET'); ?>" class="govuk-button" >Sign in</a>
      </p>
      <?php echo $this->translate('markup-problems-signing-in');?>
    </div>
  </div>

</div>
