<?php
/** @var \Common\Service\Helper\TranslationHelperService $translationHlp */
$translationHlp = $this->getHelperPluginManager()->getServiceLocator()->get('Helper\Translation');

echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->pageTitle(),
        'pageHeaderText' =>
            '<div class="guidance"><p>' .
                $translationHlp->translateReplace(
                    'user-registration.page.check-email.guidance', [$this->emailAddress]
                ) .
            '</p></div>',
        'pageHeaderTextEscape' => false,
    ]
);
?>

<div class="row">
  
  <div class="two-thirds">
    <div class="article">
      <p>
          <?php echo $this->getHelperPluginManager()
            ->getServiceLocator()->get('Helper\Translation')
            ->translateReplace(
                'user-registration.page.check-email.content',
                [
                    $this->getHelperPluginManager()->getServiceLocator()->get('Helper\Url')->fromRoute('auth/login')
                ]
            ); ?>
      </p>
      <?php echo $this->translate('markup-problems-signing-in');?>
    </div>
  </div>

</div>
