<?php

echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->translate('user-registration.page.contact-your-administrator.title'),

    ]
);
?>

<div class="row">

  <div class="two-thirds">
    <div class="article">
      <p>
          <?php echo $this->translateReplace(
                'user-registration.page.contact-your-administrator.content',
                [
                    $this->url('auth/login/GET')
                ]
            ); ?>
      </p>
      <p><a href="<?php echo $this->url('auth/login/GET'); ?>" class="govuk-button" >Back to Login</a>
      </p>
    </div>
  </div>

</div>
