<div class="page-header">
  <div class="page-header__wrapper">
    <h1><?php echo $this->translate('user-registration.page.create-account.title'); ?></h1>
  </div>
</div><!-- page-header -->

<div class="row">
  
  <div class="two-thirds">
    <?php echo $this->flashMessengerAll(); ?>
    <?php
      echo $this->formErrors($form);
      echo $this->form($form);
    ?>
  </div>
  
  <div class="one-third">
    <aside class="sidebar" role="complementary">
      <?php echo $this->translate('markup-support-contact-address');?>
    </aside>
  </div>

</div>