<?php
echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->pageTitle(),
        'backUrl' => [
            'url' => $this->url('auth/login'),
        ],
    ]
);
?>

<div class="row">
  
  <div class="two-thirds">
    <?php echo $this->flashMessengerAll(); ?>
    <?php
      echo $this->formErrors($form);
      echo $this->form($form);
    ?>
  </div>

</div>