name: App

on:
  workflow_call:
    inputs:
      ref:
        description: "The branch or tag ref to checkout"
        type: string
        required: false
      project:
        description: "The project name"
        type: string
        required: true
        default: "all"
      object-prefix:
        type: string
        description: The prefix that will be added to the object name
        required: true
      should-upload:
        description: Whether to upload the artefact
        type: boolean
        required: true
        default: false

jobs:
  verify:
    name: Verify
    if: ${{ inputs.should-upload }}
    runs-on: ubuntu-latest
    outputs:
      object-exists: ${{ steps.check-s3.outputs.exists }}
      artefact-prefix: ${{ steps.prefix.outputs.safe-artefact-prefix }}
      artefact-name: ${{ steps.prefix.outputs.safe-artefact-prefix }}/${{ inputs.project }}
    env:
      PROJECT: ${{ inputs.project }}
      OBJECT_PREFIX: ${{ inputs.object-prefix }}
    steps:
      - name: Get app prefix
        id: prefix
        run: |
          echo "safe-artefact-prefix=$(echo '$OBJECT_PREFIX' | sed 's/[^a-zA-Z0-9.]/-/g')" >> $GITHUB_OUTPUT
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.TF_OIDC_ROLE }}
          aws-region: ${{ vars.TF_AWS_REGION }}
      - name: Check if image already exists
        id: check-s3
        run: |
          exists=$(aws --output json s3api list-objects --bucket '${{ vars.ARTEFACT_BUCKET }}' --prefix '${{ steps.prefix.outputs.safe-artefact-prefix }}/$PROJECT' | jq '.Contents | length')

          if [ $exists -gt 0 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

  php:
    name: PHP
    needs:
      - verify
    if: ${{ always() && (needs.verify.result == 'skipped' || !needs.verify.outputs.object-exists) }}
    uses: ./.github/workflows/php.yaml
    with:
      ref: ${{ inputs.ref }}
      project: ${{ inputs.project }}
      artefact-name: app-${{ needs.verify.outputs.artefact-name }}
      upload-artefact: ${{ inputs.should-upload }}

  docker:
    name: Docker
    needs:
      - verify
      - php
    if: ${{ always() && needs.php.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artefact
        uses: actions/download-artifact@v4
        with:
          name: app-${{ needs.verify.outputs.artefact-name }}
      ## Build...
      - name: Upload artefact
        if: ${{ inputs.should-upload }}
        uses: actions/upload-artifact@v4
        with:
          name: docker-${{ needs.verify.outputs.artefact-name }}
          path: ${{ inputs.project }}.tar
          retention-days: 7

  upload:
    name: Upload
    needs:
      - verify
      - docker
    if: ${{ always() && inputs.should-upload && needs.docker.result == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
    steps:
      - name: Get build artefact
        uses: actions/download-artifact@v4
        with:
          name: docker-${{ needs.verify.outputs.artefact-name }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.TF_OIDC_ROLE }}
          aws-region: ${{ vars.TF_AWS_REGION }}
      - name: Upload Docker image to artefact bucket
        run: aws s3 cp . s3://${{ vars.ARTEFACT_BUCKET }}/${{ needs.verify.outputs.artefact-name }}/ --recursive
