name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          target-branch: ${{ github.ref_name }}

  orchestrator:
    name: Orchestrator
    needs:
      - release-please
    runs-on: ubuntu-latest
    outputs:
      should-deploy-docs: ${{ steps.changed-website-files.outputs.any_changed == 'true' || null }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v42
        id: changed-website-files
        with:
          files: |
            website/**
            docs/**

  docs:
    name: Documentation
    concurrency:
      group: deploy-documentation
    if: ${{ needs.orchestrator.outputs.should-deploy-docs }}
    needs:
      - orchestrator
    uses: ./.github/workflows/deploy-documentation.yaml
    with:
      deploy: true
    permissions:
      contents: write
