name: CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  app:
    name: App
    concurrency:
      group: app-${{ matrix.project }}-${{ needs.get-version.outputs[matrix.project] }}
    strategy:
      fail-fast: false
      matrix:
        project:
          - api
          - selfserve
          - internal
    uses: ./.github/workflows/php.yaml
    with:
      project: ${{ matrix.project }}
      should-upload-artefact: true
      artefact-name: app-${{ matrix.project}}-test
      retention-days: 1
    permissions:
      contents: read

  docker:
    name: Docker
    concurrency:
      group: docker-${{ matrix.project }}-test
    strategy:
      fail-fast: false
      matrix:
        project:
          - api
          - selfserve
          - internal
    uses: ./.github/workflows/docker.yaml
    with:
      project: ${{ matrix.project }}
      app-artefact-name: app-${{ matrix.project}}-test
      should-upload-artefact-to-ecr: false
    permissions:
      contents: read
      id-token: write
