name: Test E2E Integration

on:
  workflow_dispatch:

jobs:
  e2e-smoke-test:
    name: E2E Smoke Test on Dev
    uses: dvsa/vol-functional-tests/.github/workflows/e2etest.yaml@main
    with:
      platform_env: dev
      cucumber_tags: "@ec2_smoke"
      browser_name: "edge"
      browser_version: "latest"
      exclude_tags: "none"

  e2e-full-regression-test:
    name: E2E Full Regression Test on Dev
    needs:
      - e2e-smoke-test
    uses: dvsa/vol-functional-tests/.github/workflows/e2etest.yaml@main
    with:
      platform_env: dev
      cucumber_tags: "@FullRegression"
      browser_name: "edge"
      browser_version: "latest"
      exclude_tags: "none"
