name: GHCR Hygiene

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at 00:00 UTC
  workflow_dispatch:   # Can trigger manually to resolve existing issues

jobs:
  prune-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        project: [api, cli, selfserve, internal] # All the largest images, which are the most likely to cause issues if left unchecked
    steps:
      - name: Delete old versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'vol-app/${{ matrix.project }}'
          package-type: 'container'
          min-versions-to-keep: 20
          # For safety, if we only want to delete untagged versions for now. This may be moved to tagged later.
          delete-only-untagged-versions: true