name: Security

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: 5.3.0
        required: false
      project:
        type: string
        required: true

jobs:
  dependency-scan:
    name: Dependency Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/${{ inputs.project }}
    env:
      # Temporary until this repository becomes a mono-repository: https://dvsa.atlassian.net/browse/VOL-4961.
      REMOTE_REPOSITORY: ${{ inputs.project == 'api' && 'dvsa/olcs-backend' || format('dvsa/olcs-{0}', inputs.project) }}
      WORKING_DIR: infra/docker/${{ inputs.project }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ inputs.ref || null }}
          path: app/${{ inputs.project }}
      - name: Setup Snyk
        uses: snyk/actions/setup@master
      - name: Scan dependencies
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Scan docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "https://github.com/dvsa/vol-app/tree/${{ env.BRANCH_NAME }}/${{ env.WORKING_DIR }}/Dockerfile"
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload scan results to GitHub security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
