<?php
return 
array(
    'AF' => array('label' => 'Afghanistan'),
    'AX' => array('label' => 'Aland Islands'),
    'AL' => array('label' => 'Albania'),
    'DZ' => array('label' => 'Algeria'),
    'AS' => array('label' => 'American Samoa'),
    'AD' => array('label' => 'Andorra'),
    'AO' => array('label' => 'Angola'),
    'AI' => array('label' => 'Anguilla'),
    'AQ' => array('label' => 'Antarctica'),
    'AG' => array('label' => 'Antigua And Barbuda'),
    'AR' => array('label' => 'Argentina'),
    'AM' => array('label' => 'Armenia'),
    'AW' => array('label' => 'Aruba'),
    'AU' => array('label' => 'Australia'),
    'AT' => array('label' => 'Austria'),
    'AZ' => array('label' => 'Azerbaijan'),
    'BS' => array('label' => 'Bahamas'),
    'BH' => array('label' => 'Bahrain'),
    'BD' => array('label' => 'Bangladesh'),
    'BB' => array('label' => 'Barbados'),
    'BY' => array('label' => 'Belarus'),
    'BE' => array('label' => 'Belgium'),
    'BZ' => array('label' => 'Belize'),
    'BJ' => array('label' => 'Benin'),
    'BM' => array('label' => 'Bermuda'),
    'BT' => array('label' => 'Bhutan'),
    'BO' => array('label' => 'Bolivia'),
    'BA' => array('label' => 'Bosnia And Herzegovina'),
    'BW' => array('label' => 'Botswana'),
    'BV' => array('label' => 'Bouvet Island'),
    'BR' => array('label' => 'Brazil'),
    'IO' => array('label' => 'British Indian Ocean Territory'),
    'BN' => array('label' => 'Brunei Darussalam'),
    'BG' => array('label' => 'Bulgaria'),
    'BF' => array('label' => 'Burkina Faso'),
    'BI' => array('label' => 'BurundI'),
    'KH' => array('label' => 'Cambodia'),
    'CM' => array('label' => 'Cameroon'),
    'CA' => array('label' => 'Canada'),
    'CV' => array('label' => 'Cape Verde'),
    'KY' => array('label' => 'Cayman Islands'),
    'CF' => array('label' => 'Central African Republic'),
    'TD' => array('label' => 'Chad'),
    'CL' => array('label' => 'Chile'),
    'CN' => array('label' => 'China'),
    'CX' => array('label' => 'Christmas Island'),
    'CC' => array('label' => 'Cocos (Keeling) Islands'),
    'CO' => array('label' => 'Colombia'),
    'KM' => array('label' => 'Comoros'),
    'CG' => array('label' => 'Congo'),
    'CD' => array('label' => 'Congo, The Democratic Republic Of The'),
    'CK' => array('label' => 'Cook IslandS'),
    'CR' => array('label' => 'Costa Rica'),
    'CI' => array('label' => 'Cote D\'Ivoire'),
    'HR' => array('label' => 'Croatia'),
    'CU' => array('label' => 'Cuba'),
    'CY' => array('label' => 'Cyprus'),
    'CZ' => array('label' => 'Czech Republic'),
    'DK' => array('label' => 'Denmark'),
    'DJ' => array('label' => 'Djibouti'),
    'DM' => array('label' => 'Dominica'),
    'DO' => array('label' => 'Dominican Republic'),
    'EC' => array('label' => 'Ecuador'),
    'EG' => array('label' => 'Egypt'),
    'SV' => array('label' => 'El Salvador'),
    'GQ' => array('label' => 'Equatorial Guinea'),
    'ER' => array('label' => 'Eritrea'),
    'EE' => array('label' => 'Estonia'),
    'ET' => array('label' => 'Ethiopia'),
    'FK' => array('label' => 'Falkland Islands (Malvinas)'),
    'FO' => array('label' => 'Faroe Islands'),
    'FJ' => array('label' => 'Fiji'),
    'FI' => array('label' => 'Finland'),
    'FR' => array('label' => 'France'),
    'GF' => array('label' => 'French Guiana'),
    'PF' => array('label' => 'French Polynesia'),
    'TF' => array('label' => 'French Southern Territories'),
    'GA' => array('label' => 'Gabon'),
    'GM' => array('label' => 'Gambia'),
    'GE' => array('label' => 'Georgia'),
    'DE' => array('label' => 'Germany'),
    'GH' => array('label' => 'Ghana'),
    'GI' => array('label' => 'Gibraltar'),
    'GR' => array('label' => 'Greece'),
    'GL' => array('label' => 'Greenland'),
    'GD' => array('label' => 'Grenada'),
    'GP' => array('label' => 'Guadeloupe'),
    'GU' => array('label' => 'Guam'),
    'GT' => array('label' => 'Guatemala'),
    'GG' => array('label' => 'Guernsey'),
    'GN' => array('label' => 'Guinea'),
    'GW' => array('label' => 'Guinea-Bissau'),
    'GY' => array('label' => 'Guyana'),
    'HT' => array('label' => 'Haiti'),
    'HM' => array('label' => 'Heard Island And Mcdonald Islands'),
    'VA' => array('label' => 'Holy See (Vatican City State)'),
    'HN' => array('label' => 'Honduras'),
    'HK' => array('label' => 'Hong Kong'),
    'HU' => array('label' => 'Hungary'),
    'IS' => array('label' => 'Iceland'),
    'IN' => array('label' => 'India'),
    'ID' => array('label' => 'Indonesia'),
    'IR' => array('label' => 'Iran, Islamic Republic Of'),
    'IQ' => array('label' => 'Iraq'),
    'IE' => array('label' => 'Ireland'),
    'IM' => array('label' => 'Isle Of Man'),
    'IL' => array('label' => 'Israel'),
    'IT' => array('label' => 'Italy'),
    'JM' => array('label' => 'Jamaica'),
    'JP' => array('label' => 'Japan'),
    'JE' => array('label' => 'Jersey'),
    'JO' => array('label' => 'Jordan'),
    'KZ' => array('label' => 'Kazakhstan'),
    'KE' => array('label' => 'Kenya'),
    'KI' => array('label' => 'Kiribati'),
    'KP' => array('label' => 'Korea, Democratic People\'S Republic OF'),
    'KR' => array('label' => 'Korea, Republic Of'),
    'KW' => array('label' => 'Kuwait'),
    'KG' => array('label' => 'Kyrgyzstan'),
    'LA' => array('label' => 'Lao People\'S Democratic Republic'),
    'LV' => array('label' => 'Latvia'),
    'LB' => array('label' => 'Lebanon'),
    'LS' => array('label' => 'Lesotho'),
    'LR' => array('label' => 'Liberia'),
    'LY' => array('label' => 'Libyan Arab Jamahiriya'),
    'LI' => array('label' => 'Liechtenstein'),
    'LT' => array('label' => 'Lithuania'),
    'LU' => array('label' => 'Luxembourg'),
    'MO' => array('label' => 'Macao'),
    'MK' => array('label' => 'Macedonia, The Former Yugoslav Republic Of'),
    'MG' => array('label' => 'Madagascar'),
    'MW' => array('label' => 'Malawi'),
    'MY' => array('label' => 'Malaysia'),
    'MV' => array('label' => 'Maldives'),
    'ML' => array('label' => 'Mali'),
    'MT' => array('label' => 'Malta'),
    'MH' => array('label' => 'Marshall Islands'),
    'MQ' => array('label' => 'Martinique'),
    'MR' => array('label' => 'Mauritania'),
    'MU' => array('label' => 'Mauritius'),
    'YT' => array('label' => 'Mayotte'),
    'MX' => array('label' => 'MexicO'),
    'FM' => array('label' => 'Micronesia, Federated States Of'),
    'MD' => array('label' => 'Moldova, Republic Of'),
    'MC' => array('label' => 'Monaco'),
    'MN' => array('label' => 'Mongolia'),
    'MS' => array('label' => 'Montserrat'),
    'MA' => array('label' => 'Morocco'),
    'MZ' => array('label' => 'Mozambique'),
    'MM' => array('label' => 'Myanmar'),
    'NA' => array('label' => 'Namibia'),
    'NR' => array('label' => 'Nauru'),
    'NP' => array('label' => 'Nepal'),
    'NL' => array('label' => 'Netherlands'),
    'AN' => array('label' => 'Netherlands Antilles'),
    'NC' => array('label' => 'New Caledonia'),
    'NZ' => array('label' => 'New Zealand'),
    'NI' => array('label' => 'Nicaragua'),
    'NE' => array('label' => 'Niger'),
    'NG' => array('label' => 'Nigeria'),
    'NU' => array('label' => 'Niue'),
    'NF' => array('label' => 'Norfolk Island'),
    'MP' => array('label' => 'Northern Mariana Islands'),
    'NO' => array('label' => 'Norway'),
    'OM' => array('label' => 'Oman'),
    'PK' => array('label' => 'Pakistan'),
    'PW' => array('label' => 'Palau'),
    'PS' => array('label' => 'Palestinian Territory, Occupied'),
    'PA' => array('label' => 'Panama'),
    'PG' => array('label' => 'Papua New Guinea'),
    'PY' => array('label' => 'Paraguay'),
    'PE' => array('label' => 'Peru'),
    'PH' => array('label' => 'Philippines'),
    'PN' => array('label' => 'Pitcairn'),
    'PL' => array('label' => 'Poland'),
    'PT' => array('label' => 'Portugal'),
    'PR' => array('label' => 'Puerto Rico'),
    'QA' => array('label' => 'Qatar'),
    'RE' => array('label' => 'Reunion'),
    'RO' => array('label' => 'Romania'),
    'RU' => array('label' => 'Russian Federation'),
    'RW' => array('label' => 'Rwanda'),
    'SH' => array('label' => 'Saint Helena'),
    'KN' => array('label' => 'Saint Kitts And Nevis'),
    'LC' => array('label' => 'Saint Lucia'),
    'PM' => array('label' => 'Saint Pierre And Miquelon'),
    'VC' => array('label' => 'Saint Vincent And The Grenadines'),
    'WS' => array('label' => 'Samoa'),
    'SM' => array('label' => 'San Marino'),
    'ST' => array('label' => 'Sao Tome And Principe'),
    'SA' => array('label' => 'Saudi Arabia'),
    'SN' => array('label' => 'Senegal'),
    'CS' => array('label' => 'Serbia And Montenegro'),
    'SC' => array('label' => 'Seychelles'),
    'SL' => array('label' => 'Sierra Leone'),
    'SG' => array('label' => 'Singapore'),
    'SK' => array('label' => 'Slovakia'),
    'SI' => array('label' => 'Slovenia'),
    'SB' => array('label' => 'Solomon Islands'),
    'SO' => array('label' => 'Somalia'),
    'ZA' => array('label' => 'South Africa'),
    'GS' => array('label' => 'South Georgia And The South Sandwich Islands'),
    'ES' => array('label' => 'Spain'),
    'LK' => array('label' => 'Sri Lanka'),
    'SD' => array('label' => 'Sudan'),
    'SR' => array('label' => 'Suriname'),
    'SJ' => array('label' => 'Svalbard And Jan Mayen'),
    'SZ' => array('label' => 'Swaziland'),
    'SE' => array('label' => 'Sweden'),
    'CH' => array('label' => 'Switzerland'),
    'SY' => array('label' => 'Syrian Arab Republic'),
    'TW' => array('label' => 'Taiwan, Province Of China'),
    'TJ' => array('label' => 'Tajikistan'),
    'TZ' => array('label' => 'Tanzania, United Republic Of'),
    'TH' => array('label' => 'Thailand'),
    'TL' => array('label' => 'Timor-Leste'),
    'TG' => array('label' => 'Togo'),
    'TK' => array('label' => 'Tokelau'),
    'TO' => array('label' => 'Tonga'),
    'TT' => array('label' => 'Trinidad And Tobago'),
    'TN' => array('label' => 'Tunisia'),
    'TR' => array('label' => 'Turkey'),
    'TM' => array('label' => 'Turkmenistan'),
    'TC' => array('label' => 'Turks And Caicos Islands'),
    'TV' => array('label' => 'Tuvalu'),
    'UG' => array('label' => 'Uganda'),
    'UA' => array('label' => 'Ukraine'),
    'AE' => array('label' => 'United Arab Emirates'),
    'GB' => array('label' => 'United Kingdom'),
    'US' => array('label' => 'United States'),
    'UM' => array('label' => 'United States Minor Outlying Islands'),
    'UY' => array('label' => 'Uruguay'),
    'UZ' => array('label' => 'Uzbekistan'),
    'VU' => array('label' => 'Vanuatu'),
    'VE' => array('label' => 'Venezuela'),
    'VN' => array('label' => 'Viet Nam'),
    'VG' => array('label' => 'Virgin Islands, British'),
    'VI' => array('label' => 'Virgin Islands, U.S.'),
    'WF' => array('label' => 'Wallis And Futuna'),
    'EH' => array('label' => 'Western Sahara'),
    'YE' => array('label' => 'Yemen'),
    'ZM' => array('label' => 'Zambia'),
    'ZW' => array('label' => 'Zimbabwe'),
    'ZZ' => array('label' => '(Not Specified)')
);
?>
