<div class="one-fifth--left">
    <h4><?php echo $this->translate('internal-licence-bus-' . $this->section); ?></h4>
    <?php
        echo $this->navigation($navigation)->menu()->setPartial('layout/partials/subNavigation');
        echo $this->tableFilters();
    ?>
</div>
<div class="three-fifths">
    <h4><?php echo $this->translate('internal-licence-bus-' . $this->section . ($this->item ? '-' . $this->item : '')); ?></h4>
    <?php echo $this->content; ?>
</div>